<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<!--
	phpwcms | free open source content management system
	created by Oliver Georgi (oliver at phpwcms dot de) and licensed under GNU/GPL.
	phpwcms is copyright 2003-2006 of Oliver Georgi. Extensions are copyright of\
	their respective owners. Visit project page for details: http://www.phpwcms.org/
//-->
<title></title>
  <meta http-equiv="content-type" content="text/html; charset=iso-8859-1" />
  <meta http-equiv="content-style-type" content="text/css" />
  <script src="template/inc_js/frontend.js" type="text/javascript"></script>
  <style type="text/css" media="all">
  /* <![CDATA[ */
    body {
      margin: 0;
      padding-top: 0;
      padding-bottom: 0;
      padding-left: 0;
      padding-right: 0;

    }
  /* ]]> */
  </style>
  <style type="text/css">
  /* <![CDATA[ */
    @import url("template/inc_css/frontend.css");
    @import url("template/inc_css/nlu_navi1_docu.css");
    @import url("template/inc_css/print_layout.css");
  /* ]]> */
  </style>


<META NAME="Title" CONTENT="Die phpWCMS Dokumentation">
<meta name="author" content="Oliver Frohnert">
<meta name="Publisher" content="Oliver Frohnert">
<meta name="Copyright" content="Oliver Frohnert">
<meta name="keywords" content="frohnert,documentation, dokumentation, phpwcms, cms, opensource, open source">
<meta name="description" content="Das Dokumentations Projekt für das Open Source CMS phpWCMS">
<meta name="Audience" content="Alle">
<meta name="Content-language" content="DE">
<META NAME="robots"      CONTENT="index,follow">
<META NAME="expires" CONTENT="0">
<meta name="revisit-after" content="7 days">
<meta name="resource-type" content="document">
<meta name="distribution" content="Global">
<meta name="generator" content="PHPWCMS">

  <!--[if lt IE 7]>
  <style type="text/css">
    body { behavior: url("template/inc_css/specific/csshover2.htc"); }
    img { behavior: url("template/inc_css/specific/pngbehavior.htc"); }
  </style>
  <![endif]-->
</head>
<body>
<img src="img/leer.gif" border="0" width="10" height="1" alt="" />
<br />
<a href="deutsche_version.phtml">Deutsch</a> <span class="breadcrumb_spacer">&gt;</span> <a href="kontakt.phtml">Kontakt</a> <span class="breadcrumb_spacer">&gt;</span> Gästebuch
<br />
<HR>
<br />
<a name="jump54"></a><h1>Gästebuch</h1><h2>Wir würden uns über einen Eintrag  freuen...</h2><div style="margin:25px 0 0 0; padding:0 0 0 0; clear:both;"></div>
   
<table width="100%"  border="0" cellspacing="0" cellpadding="0" style="margin-top:5px;">
  <tr>
    <td><strong><a href="102.54.1.1.1.0.phtml">&lt;&lt;</a> <a href="102.54.1.1.1.55.phtml">&lt;</a></strong> <a href="102.54.1.1.1.54.phtml">55</a>&nbsp;<a href="102.54.1.1.1.55.phtml">56</a>&nbsp;<strong>57</strong>&nbsp;<a href="102.54.1.1.1.57.phtml">58</a>&nbsp;<a href="102.54.1.1.1.58.phtml">59</a> <strong><a href="102.54.1.1.1.57.phtml">&gt;</a>
        <a href="102.54.1.1.1.62.phtml">&gt;&gt;</a></strong></td>
    <td align="right">&nbsp;<form name="guestbookjump" id="guestbookjump" method="post" action="index.php?id=102,54,1,1,1,56"><select name="showguestbookpage" id="showpage" onchange="document.guestbookjump.submit();"><option value="1">page
      1</option>
<option value="2">page
      2</option>
<option value="3">page
      3</option>
<option value="4">page
      4</option>
<option value="5">page
      5</option>
<option value="6">page
      6</option>
<option value="7">page
      7</option>
<option value="8">page
      8</option>
<option value="9">page
      9</option>
<option value="10">page
      10</option>
<option value="11">page
      11</option>
<option value="12">page
      12</option>
<option value="13">page
      13</option>
<option value="14">page
      14</option>
<option value="15">page
      15</option>
<option value="16">page
      16</option>
<option value="17">page
      17</option>
<option value="18">page
      18</option>
<option value="19">page
      19</option>
<option value="20">page
      20</option>
<option value="21">page
      21</option>
<option value="22">page
      22</option>
<option value="23">page
      23</option>
<option value="24">page
      24</option>
<option value="25">page
      25</option>
<option value="26">page
      26</option>
<option value="27">page
      27</option>
<option value="28">page
      28</option>
<option value="29">page
      29</option>
<option value="30">page
      30</option>
<option value="31">page
      31</option>
<option value="32">page
      32</option>
<option value="33">page
      33</option>
<option value="34">page
      34</option>
<option value="35">page
      35</option>
<option value="36">page
      36</option>
<option value="37">page
      37</option>
<option value="38">page
      38</option>
<option value="39">page
      39</option>
<option value="40">page
      40</option>
<option value="41">page
      41</option>
<option value="42">page
      42</option>
<option value="43">page
      43</option>
<option value="44">page
      44</option>
<option value="45">page
      45</option>
<option value="46">page
      46</option>
<option value="47">page
      47</option>
<option value="48">page
      48</option>
<option value="49">page
      49</option>
<option value="50">page
      50</option>
<option value="51">page
      51</option>
<option value="52">page
      52</option>
<option value="53">page
      53</option>
<option value="54">page
      54</option>
<option value="55">page
      55</option>
<option value="56">page
      56</option>
<option value="57" selected="selected">page
      57</option>
<option value="58">page
      58</option>
<option value="59">page
      59</option>
<option value="60">page
      60</option>
<option value="61">page
      61</option>
<option value="62">page
      62</option>
<option value="63">page
      63</option>
</select>&nbsp;<input name="jumpsubmit" class="guestbookJumpSubmit" type="submit" value="go" /></form></td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
</table>

<table width="100%"  border="0" cellspacing="0" cellpadding="2">
  
  <tr bgcolor="#F5F5F5">
    <td width="99%">561 | 24/01/2006 19:04</td>
  </tr>
  <tr>
    <td colspan="2"><strong>Juan Alberto Gonzalez</strong> <a href="http://www.mediartistes-asso.fr" target="_blank">visit
      website</a> macaronesico at gmail  dot com<br />
      Vielen Dank für die tolle Sammlung hilfreiche Texte die hier sien, und für dieses wunderbaren cms<br />
(Übrigens - error entdeckt? Before den signing könnte ich nicht durch das Guestbook surfen... mal sehen wenn ich signiert habe :) <br />
cu</td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
  
  <tr bgcolor="#F5F5F5">
    <td width="99%">562 | 17/01/2006 09:22</td>
  </tr>
  <tr>
    <td colspan="2"><strong>Basti</strong>  <br />
      Vielen dank für Eure tolle Seite! Ich habe gerade ein &quot;Mararthon-CMS-Test_Wochenende&quot; hinter mir. Folgende CMS´s habe ich getestet: Mambo, Contenido, Joomla, papoo und phpwcms.<br />
<br />
mein eindeutiger Sieger:  phpwcms.<br />
<br />
Eure Seite hilft dem Einsteiger imens. Obwohl ich sagen muss, das phpwcms sehr leicht und schnell zu verstehen ist.<br />
<br />
Vielen Dank!, Weiter so und liebe Grüße aus Hamburg!!!</td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
  
  <tr bgcolor="#F5F5F5">
    <td width="99%">563 | 21/12/2005 18:43</td>
  </tr>
  <tr>
    <td colspan="2"><a href="mailto:paul@whitework.se"><strong>Paul</strong></a>  paul@whitework.se<br />
      Hi, dident know so much of this and i still have lots to learn.<br />
Thanks a million for all help from this site.<br />
couldent have don it without you.</td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
  
  <tr bgcolor="#F5F5F5">
    <td width="99%">564 | 14/11/2005 16:37</td>
  </tr>
  <tr>
    <td colspan="2"><strong>Leon</strong>  <br />
      This system is absolutely impressive and professional, just downloaded it, congratulations to the main developer and support team.</td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
  
  <tr bgcolor="#F5F5F5">
    <td width="99%">565 | 16/10/2005 21:23</td>
  </tr>
  <tr>
    <td colspan="2"><strong>Peyter</strong>  <br />
      Great site</td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
  
  <tr bgcolor="#F5F5F5">
    <td width="99%">566 | 06/10/2005 02:54</td>
  </tr>
  <tr>
    <td colspan="2"><strong>Antonis</strong> <a href="http://fuzzfree.com" target="_blank">visit
      website</a> <br />
      I discovered phpWCMS 2 weeks ago in Fantastico, and since yesterday I&#039;ve been playin with it - looks great tool, very promising!! I need to explore it more and I am thinking contributing the Greek language pack! Keep on the good work guys!</td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
  
  <tr bgcolor="#F5F5F5">
    <td width="99%">567 | 02/10/2005 20:33</td>
  </tr>
  <tr>
    <td colspan="2"><a href="mailto:david@hotmale.com"><strong>david</strong></a> <a href="http://www.emcbe.com" target="_blank">visit
      website</a> david@hotmale.com<br />
      is version 2 going to be available throught cpanel and fantastico ??<br />
<span style="color:#00CC00;">how should we told you that? ask fantastico or install it manually &quot;Pappnase&quot; Oliver</span></td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
  
  <tr bgcolor="#F5F5F5">
    <td width="99%">568 | 26/09/2005 12:00</td>
  </tr>
  <tr>
    <td colspan="2"><strong>Webdisign CMS</strong> <a href="http://www.qrios.nl" target="_blank">visit
      website</a> keesje76 at hotmail  dot com<br />
      Great tool! Only thing I&#039;d like to see different: User must log in to backend to change content. Modern CMS should provide login-and content adding/editing within de site structure!<br />
<span style="color:#00CC00;">thanks :-) but i need to ay i like it like it is. cos if there would be the possibility to login you would have on all articles an login field or something like that! &quot;Pappnase&quot; Oliver</span></td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
  
  <tr bgcolor="#F5F5F5">
    <td width="99%">569 | 21/09/2005 02:11</td>
  </tr>
  <tr>
    <td colspan="2"><a href="mailto:street@jdmworld.co.uk"><strong>Rob James</strong></a> <a href="http://JDMWorld.co.uk" target="_blank">visit
      website</a> street@jdmworld.co.uk<br />
      ive been using phpwcms for a while now, but this site is great, cleared up a few things i wasnt sure of! Still having problems doing a fresh install of 1.2.5-Dev but im sure i will sort that in the future!<br />
<br />
Top Stuff!</td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
  
  <tr bgcolor="#F5F5F5">
    <td width="99%">570 | 24/08/2005 18:56</td>
  </tr>
  <tr>
    <td colspan="2"><strong>Melli</strong>  <br />
      Mein Herz ich liebe dich über alles <br />
<br />
Dein Ungeheuer :X</td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
  
</table>

<table width="100%"  border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td colspan="2"><HR></td>
  </tr>
  <tr>
    <td width="50%">Artikel erstellt: 2004/08/16</td>
    <td align="right" width="50%">Letzte Änderung:2007/01/26</td>
  </tr>
  <tr>
    <td colspan="2">&nbsp;</td>
  </tr>
  <tr>
    <td colspan="2" class="comment">Wenn Sie einen Fehler entdecken eine Ergänzung oder Frage haben benutzen Sie bitte folgendes <a href="#" onClick="javascript:window.open('./content/pages/nachricht.htm','frage','width=400, height=250, screenX=440,screenY=200,menubar=no,statusbar=yes,scrollbar=yes,resizable=no');" target="" style="max-width:148px; overflow:hidden;"><u>Formular</u></a>.<br /><br />
Hat Ihnen oder Ihrem Kunden diese Docu weitergeholfen ? Dann würde ich mich freuen wenn Sie das Projekt unterstützen würden. Bitte nutzen Sie dafür diesen <a href="#paypal">PayPal</a> Link. Jeder Betrag ist möglich und hilft der Weiterentwicklung und Aktualisierung dieser Dokumentation.<br />
Diese Seite nutzt die version:</td>
  </tr>
  <tr>

    <td colspan="2"><img src="img/leer.gif" border="0" width="10" height="10" alt="" /></td>
  </tr>
</table>

</body>
</html>