<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<!--
	phpwcms | free open source content management system
	created by Oliver Georgi (oliver at phpwcms dot de) and licensed under GNU/GPL.
	phpwcms is copyright 2003-2007 of Oliver Georgi. Extensions are copyright of
	their respective owners. Visit project page for details: http://www.phpwcms.org/
//-->
<title>Gästebuch | Gästebuch</title>
  <meta http-equiv="content-type" content="text/html; charset=iso-8859-1" />
  <meta http-equiv="content-style-type" content="text/css" />
  <script src="template/inc_js/frontend.js" type="text/javascript"></script>
  <style type="text/css" media="all">
  <!-- 
    body {
      margin: 0;
      padding-top: 0;
      padding-bottom: 0;
      padding-left: 0;
      padding-right: 0;

    }
  //-->
  </style>
  <style type="text/css">
  <!-- 
    @import url("template/inc_css/frontend.css");
    @import url("template/inc_css/nlu_navi1_docu.css");
  //-->
  </style>


<META NAME="Title" CONTENT="Die phpWCMS Dokumentation">
<meta name="author" content="Oliver Frohnert">
<meta name="Publisher" content="Oliver Frohnert">
<meta name="Copyright" content="Oliver Frohnert">
<meta name="keywords" content="frohnert,documentation, dokumentation, phpwcms, cms, opensource, open source">
<meta name="description" content="Das Dokumentations Projekt für das Open Source CMS phpWCMS">
<meta name="Audience" content="Alle">
<meta name="Content-language" content="DE">
<META NAME="robots"      CONTENT="index,follow">
<META NAME="expires" CONTENT="0">
<meta name="revisit-after" content="7 days">
<meta name="resource-type" content="document">
<meta name="distribution" content="Global">
<meta name="generator" content="PHPWCMS">

  <!--[if lt IE 7]>
  <style type="text/css">
    body { behavior: url("template/inc_css/specific/csshover2.htc"); }
    img { behavior: url("template/inc_css/specific/pngbehavior.htc"); }
  </style>
  <![endif]-->
</head>
<body>


<!--

	this is the default PDF template
	use it to add additional header or
	footer information or whatever you 
	like to be rendered 

//-->
URL: <a href="deutsche_version.phtml?id=102,54,1,1,1,6" target="_blank">deutsche_version.phtml?id=102,54,1,1,1,6</a>
<hr />
<img src="img/leer.gif" border="0" width="10" height="1" alt="" />
<br />
<a href="deutsche_version.phtml">Deutsch</a> <span class="breadcrumb_spacer">&gt;</span> <a href="kontakt.phtml">Kontakt</a> <span class="breadcrumb_spacer">&gt;</span> Gästebuch
<br />
<HR>
<br />
<a name="jump54"></a><div>
<h1 style="margin:0 0 5px 0;">Gästebuch</h1>
<h3 style="margin:0 0 5px 0;">Wir würden uns über einen Eintrag  freuen...</h3>

</div><div style="margin:25px 0 0 0;padding:0;" class="spaceBeforeCP"></div>
   
<table width="100%"  border="0" cellspacing="0" cellpadding="0" style="margin-top:5px;">
  <tr>
    <td><strong><a href="102.54.1.1.1.0.phtml">&lt;&lt;</a> <a href="102.54.1.1.1.5.phtml">&lt;</a></strong> <a href="102.54.1.1.1.4.phtml">5</a>&nbsp;<a href="102.54.1.1.1.5.phtml">6</a>&nbsp;<strong>7</strong>&nbsp;<a href="102.54.1.1.1.7.phtml">8</a>&nbsp;<a href="102.54.1.1.1.8.phtml">9</a> <strong><a href="102.54.1.1.1.7.phtml">&gt;</a>
        <a href="102.54.1.1.1.8.phtml">&gt;&gt;</a></strong></td>
    <td align="right">&nbsp;<form name="guestbookjump" id="guestbookjump" method="post" action="index.php?id=102,54,1,1,1,6"><select name="showguestbookpage" id="showpage" onchange="document.guestbookjump.submit();"><option value="1">Seite
      1</option>
<option value="2">Seite
      2</option>
<option value="3">Seite
      3</option>
<option value="4">Seite
      4</option>
<option value="5">Seite
      5</option>
<option value="6">Seite
      6</option>
<option value="7" selected="selected">Seite
      7</option>
<option value="8">Seite
      8</option>
<option value="9">Seite
      9</option>
</select>&nbsp;<input name="jumpsubmit" class="guestbookJumpSubmit" type="submit" value="go" /></form></td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
</table>

<table width="100%"  border="0" cellspacing="0" cellpadding="2">
  
  <tr bgcolor="#F5F5F5">
    <td width="1%" align="right"><strong>61&nbsp;&nbsp;</strong></td>
    <td width="99%"><!-- 21 | -->10/04/2004 17:17</td>
  </tr>
  <tr>
    <td colspan="2"><a href="mailto:"><strong>Markus</strong></a>  <br />
      Vielen veilen Dank!<br />
Genau DAS habe ich gesucht. Hab mich nun erst wenige stunden damit befasst, und begreife es schon. Ihr macht da eine wirklich gute Sache. :-)</td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
  
  <tr bgcolor="#F5F5F5">
    <td width="1%" align="right"><strong>62&nbsp;&nbsp;</strong></td>
    <td width="99%"><!-- 20 | -->09/27/2004 18:12</td>
  </tr>
  <tr>
    <td colspan="2"><a href="mailto:"><strong>webmaster anywhere</strong></a>  <br />
      hi folks,<br />
ne klasse anleitung entsteht hier.<br />
danke</td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
  
  <tr bgcolor="#F5F5F5">
    <td width="1%" align="right"><strong>63&nbsp;&nbsp;</strong></td>
    <td width="99%"><!-- 19 | -->09/22/2004 20:57</td>
  </tr>
  <tr>
    <td colspan="2"><a href="mailto:robert@headshake.nl"><strong>robert</strong></a>  robert@headshake.nl<br />
      Only wanna say GREAT job GREAT cms! <br />
(stimulating_comments) :)</td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
  
  <tr bgcolor="#F5F5F5">
    <td width="1%" align="right"><strong>64&nbsp;&nbsp;</strong></td>
    <td width="99%"><!-- 18 | -->09/17/2004 00:30</td>
  </tr>
  <tr>
    <td colspan="2"><a href="mailto:kelleylaw at mac dot com"><strong>Kelley Law</strong></a>  kelleylaw at mac dot com<br />
      Great work! I am so glad to see such a well defind manual. The only down side is that you might see less of me on the support forum. :-)</td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
  
  <tr bgcolor="#F5F5F5">
    <td width="1%" align="right"><strong>65&nbsp;&nbsp;</strong></td>
    <td width="99%"><!-- 17 | -->09/15/2004 02:23</td>
  </tr>
  <tr>
    <td colspan="2"><a href="mailto:info at taog dot de"><strong>Torsten Goltz</strong></a>  info at taog dot de<br />
      Jungens, gute Software :D Ich stelle gerade meine eigene Seite auf das CMS um und habe nach einigen Startschwierigkeiten nun doch den Faden gefunden.<br />
<br />
Es wäre toll, wenn bei der Installation eine Bsp. Seite voranden wäre. so kann man sich mal einlesen. Das die Daten in der MySQL Datenbank nicht vorhanden seinen können ist klar. Was ich meine ist eine Grundversion von den Templates etc.<br />
Das wird bestimmt schon in irgend einer Form gemacht, aber das war der Grund warum mein Start sich etwas herraus zögerte :)</td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
  
  <tr bgcolor="#F5F5F5">
    <td width="1%" align="right"><strong>66&nbsp;&nbsp;</strong></td>
    <td width="99%"><!-- 16 | -->09/14/2004 15:39</td>
  </tr>
  <tr>
    <td colspan="2"><a href="mailto:as1528734 at sapo dot pt"><strong>Isac</strong></a>  as1528734 at sapo dot pt<br />
      Hi,<br />
<br />
A lot of work you guys have here and very usefull too. I would like to sugest a new section, tips &amp; tricks. Maybe there isn&#039;t to much tricks and tips at all... ;-)<br />
<br />
Best regards,<br />
Isac.<br />
<br />
<span style="color:#00CC00;">hello isac, thanks for your entry. and an tips and tricks section is planned. but at the monent there  the layout and templtes the more important thing! but as i say i will come. kind regards Oliver &quot;Pappnase&quot;</span></td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
  
  <tr bgcolor="#F5F5F5">
    <td width="1%" align="right"><strong>67&nbsp;&nbsp;</strong></td>
    <td width="99%"><!-- 15 | -->09/13/2004 11:54</td>
  </tr>
  <tr>
    <td colspan="2"><a href="mailto:jswnz@xtra.co.nz"><strong>John</strong></a>  jswnz@xtra.co.nz<br />
      I find myself coming here often....a great reference for a great cms. Thanks Pappnase and Thanks OliverG!</td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
  
  <tr bgcolor="#F5F5F5">
    <td width="1%" align="right"><strong>68&nbsp;&nbsp;</strong></td>
    <td width="99%"><!-- 14 | -->09/13/2004 04:35</td>
  </tr>
  <tr>
    <td colspan="2"><a href="mailto:test@test.com"><strong>test</strong></a>  test@test.com<br />
      test msg<br />
<br />
<span style="color:#00CC00;"> a big thanks to vietnam for this great entry! kind regards Oliver &quot;Pappnase&quot;</span></td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
  
  <tr bgcolor="#F5F5F5">
    <td width="1%" align="right"><strong>69&nbsp;&nbsp;</strong></td>
    <td width="99%"><!-- 13 | -->09/11/2004 09:59</td>
  </tr>
  <tr>
    <td colspan="2"><a href="mailto:"><strong>webkidz</strong></a>  <br />
      Mach weiter so mit Deiner Seite wie bisher! Du hast mir mit deiner Seite schon das eine oder andere mal geholfen!<br />
<br />
<span style="color:#00CC00;">hallo, danke. aber Bitte bedenke das ich das nicht alleine mache. Sondern das es hier mehr Flinke finger gibt*zwinker* Gruß Oliver &quot;Pappnase&quot;</span></td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
  
  <tr bgcolor="#F5F5F5">
    <td width="1%" align="right"><strong>70&nbsp;&nbsp;</strong></td>
    <td width="99%"><!-- 12 | -->09/06/2004 23:01</td>
  </tr>
  <tr>
    <td colspan="2"><a href="mailto:mseydel@achumer-wiese-40.de"><strong>Matthias Seydel</strong></a>  mseydel@achumer-wiese-40.de<br />
      Hallo,<br />
ersteinmal herzlichen Glückwunsch zu dieser Seite. Endlich ein Anlaufpunkt (ausser  dem  guten Forum und der Seite von Herrn Pepperkorn ;-) ) Das CMS ist wirkliches das beste was ich bis jetzt gefunden habe und weitersuchen lohnt wohl auch nicht...<br />
<br />
Mir ist bei &quot;Content Parts &gt; Gästebuch&quot; aufgefallen  das das bei mir etwas anders aussieht . Nix mit Wortsperre etc. Habe ich etwas verpasst ? <br />
Meine Version 1.1 - RC4 22.06.2004.<br />
<br />
mfg<br />
Matthias<br />
<br />
<span style="color:#00CC00;">Hallo, erstmal danke für den netten Eintrag. Ja du hast was verpasst am 27.08 gab es ein kleines aber feines Update.<br />
<br />
Gruß Oliver &quot;Pappnase&quot;</span></td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
  
</table>

<table width="100%"  border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td colspan="2"><HR></td>
  </tr>
  <tr>
    <td width="50%">Artikel erstellt: 2004/08/16</td>
    <td align="right" width="50%">Letzte Änderung:2007/06/29</td>
  </tr>
  <tr>
    <td colspan="2">&nbsp;</td>
  </tr>
  <tr>
    <td colspan="2" class="comment">Wenn Sie einen Fehler entdecken eine Ergänzung oder Frage haben benutzen Sie bitte folgendes <a href="#" onClick="javascript:window.open('./content/pages/nachricht.htm','frage','width=400, height=250, screenX=440,screenY=200,menubar=no,statusbar=yes,scrollbar=yes,resizable=no');" target="" style="max-width:148px; overflow:hidden;"><u>Formular</u></a>.<br /><br />
Hat Ihnen oder Ihrem Kunden diese Docu weitergeholfen ? Dann würde ich mich freuen wenn Sie das Projekt unterstützen würden. Bitte nutzen Sie dafür diesen <a href="#paypal">PayPal</a> Link. Jeder Betrag ist möglich und hilft der Weiterentwicklung und Aktualisierung dieser Dokumentation.<br />
Diese Seite nutzt die version:</td>
  </tr>
  <tr>

    <td colspan="2"><img src="img/leer.gif" border="0" width="10" height="10" alt="" /></td>
  </tr>
</table>


</body>
</html>