<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<!--
	phpwcms | free open source content management system
	created by Oliver Georgi (oliver at phpwcms dot de) and licensed under GNU/GPL.
	phpwcms is copyright 2003-2007 of Oliver Georgi. Extensions are copyright of
	their respective owners. Visit project page for details: http://www.phpwcms.org/
//-->
<title>Gästebuch | Gästebuch</title>
  <meta http-equiv="content-type" content="text/html; charset=iso-8859-1" />
  <meta http-equiv="content-style-type" content="text/css" />
  <script src="template/inc_js/frontend.js" type="text/javascript"></script>
  <style type="text/css" media="all">
  <!-- 
    body {
      margin: 0;
      padding-top: 0;
      padding-bottom: 0;
      padding-left: 0;
      padding-right: 0;

    }
  //-->
  </style>
  <style type="text/css">
  <!-- 
    @import url("template/inc_css/print_layout.css");
  //-->
  </style>
<script type="text/javascript" language="javascript">
<!--
function MM_jumpMenu(targ,selObj,restore){ //v3.0
  eval(targ+".location='"+selObj.options[selObj.selectedIndex].value+"'");
  if (restore) selObj.selectedIndex=0;
}

function MM_findObj(n, d) { //v4.01
  var p,i,x;  if(!d) d=document; if((p=n.indexOf("?"))>0&&parent.frames.length) {
    d=parent.frames[n.substring(p+1)].document; n=n.substring(0,p);}
  if(!(x=d[n])&&d.all) x=d.all[n]; for (i=0;!x&&i<d.forms.length;i++) x=d.forms[i][n];
  for(i=0;!x&&d.layers&&i<d.layers.length;i++) x=MM_findObj(n,d.layers[i].document);
  if(!x && d.getElementById) x=d.getElementById(n); return x;
}

function MM_jumpMenuGo(selName,targ,restore){ //v3.0
  var selObj = MM_findObj(selName); if (selObj) MM_jumpMenu(targ,selObj,restore);
}
//-->
</script>
<meta name="Title" content="Die phpWCMS Dokumentation" />
<meta name="author" content="Oliver Frohnert, Mario Perez Leal" />
<meta name="Publisher" content="Oliver Frohnert, Mario Perez Leal, creacion" />
<meta name="Copyright" content="Oliver Frohnert, Mario Perez Leal, creacion" />
<meta name="keywords" content="frohnert, perez leal, creacion, documentation, dokumentation, phpwcms, cms, opensource, open source, docu" />
<meta name="description" content="Das Dokumentations Projekt für das Open Source CMS phpWCMS" />
<meta name="Audience" content="Alle" />
<meta name="Content-language" content="DE" />
<meta name="robots" content="index,follow" />
<meta name="expires" content="0" />
<meta name="revisit-after" content="7 days" />
<meta name="resource-type" content="document" />
<meta name="distribution" content="Global" />
<meta name="generator" content="PHPWCMS" />
<meta name="verify-v1" content="1ZpxZ7AZsjm7PxjqXQVus0eiUYqOsp5URTJn9q4KNz8=" />
  <!--[if lt IE 7]>
  <style type="text/css">
    body { behavior: url("template/inc_css/specific/csshover2.htc"); }
    img { behavior: url("template/inc_css/specific/pngbehavior.htc"); }
  </style>
  <![endif]-->
</head>
<body id="myid_102">


<!--

	this is the default PDF template
	use it to add additional header or
	footer information or whatever you 
	like to be rendered 

//-->

<div style="width:50%; border:1px solid #0f57a6; padding:10px; margin:10px;">
<p style="margin-bottom:20px;"><img src="./template/img/printlogo.gif" width="255" height="91" alt="" border="0" /></p>

<div id="container"><a name="top" id="top"></a>

		<a name="jump54"></a><!-- 
custom article template to split up the view / entry area for the guestbook
template by oliver@phpwcms-docu.de
===========================================================================
//-->
<div>
<h1 style="margin:0 0 5px 0;">Gästebuch</h1>
<h3 style="margin:0 0 5px 0;">Wir würden uns über einen Eintrag  freuen...</h3>
</div>

<div style="margin:25px 0 0 0;padding:0;" class="spaceBeforeCP"></div>
  
  
  
  

<table width="100%"  border="0" cellspacing="0" cellpadding="0" style="margin-top:5px;">
  <tr>
    <td><strong><a href="102.54.1.1.1.0.phtml">&laquo;&laquo;</a> <a href="102.54.1.1.1.2.phtml">&laquo;</a></strong> <a href="102.54.1.1.1.1.phtml">2</a>&nbsp;<a href="102.54.1.1.1.2.phtml">3</a>&nbsp;<strong>4</strong>&nbsp;<a href="102.54.1.1.1.4.phtml">5</a>&nbsp;<a href="102.54.1.1.1.5.phtml">6</a> <strong><a href="102.54.1.1.1.4.phtml">&raquo;</a>
        <a href="102.54.1.1.1.14.phtml">&raquo;&raquo;</a></strong></td>
    <td align="right"></td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
</table>


	  <table width="100%" border="0" cellspacing="0" cellpadding="0">
  
	  <tr class="tbb">
	  <td width="130" class="tbh"> &nbsp;31 </td>
	  <td align="right" class="tbh">Vom 02.02.2010 um 10:20 Uhr&nbsp;</td>
	  </tr>
	  <tr class="tbr">
	  <td class="tbl" valign="top">
	  <strong>JuNet</strong><br /><br />
	  <a href="http://www.junet.at" target="_blank"><img src="template/lang/all/icons/home.gif" width="20" height="21" alt="Website besuchen" title="Website besuchen"border="0" /></a><br />
	  <a href="mailto:martin.simperl@ibisacam.at"><img src="template/lang/all/icons/mail.gif" width="20" height="21" alt="E-Mail senden" title="E-Mail senden"border="0" /></a></td>
	  <td valign="top" style="padding:10PX;">JuNet - Wir können für Sie arbeiten!<br />
<br />
T-Shirt - Druck und Copy Shop! Textilveredelung, Farbkopien und Drucke, Visitenkarten, kuvertieren, falten, Postwurfsendungen bündeln und liefern, Briefpapier, Laminationen, Kuverts, Handarbeiten, Einladungen, Plakate, Flyer, Postkarten, Prospekte, Mailings, Etiketten, Mappen, Speisekarten, Aufkleber, SW-Kopien, Layouts &amp; Designs, Logoerstellung, Cd´s brennen, uvm. <br />
 <br />
Dienstleistungen für Sie- Arbeitsplätze für Jugendliche! <br />
<br />
Mit freundlichen Grüßen<br />
&gt;JuNet TEAM &lt; <br />
<br />
Projekt JuNet<br />
Bruggfeldstrasse 5 (LanTech)<br />
6500 Landeck <br />
Tel: 05442 67112<br />
Fax: 05442 67112-18<br />
www.junet.at<br />
martin.simperl@ibisacam.at</td>
	  </tr>
  
	  <tr class="tbb">
	  <td width="130" class="tbh"> &nbsp;32 </td>
	  <td align="right" class="tbh">Vom 22.01.2010 um 12:29 Uhr&nbsp;</td>
	  </tr>
	  <tr class="tbr">
	  <td class="tbl" valign="top">
	  <strong>Imsa</strong><br /><br />
	  <a href="http://www.imsa-gmbh.de" target="_blank"><img src="template/lang/all/icons/home.gif" width="20" height="21" alt="Website besuchen" title="Website besuchen"border="0" /></a><br />
	  <a href="mailto:imsa@trash-mail.com"><img src="template/lang/all/icons/mail.gif" width="20" height="21" alt="E-Mail senden" title="E-Mail senden"border="0" /></a></td>
	  <td valign="top" style="padding:10PX;">Sehr gut, hat mir weitergeholfen. Sehr zu empfehlen, vielen Dank !!!</td>
	  </tr>
  
	  <tr class="tbb">
	  <td width="130" class="tbh"> &nbsp;33 </td>
	  <td align="right" class="tbh">Vom 22.01.2010 um 07:07 Uhr&nbsp;</td>
	  </tr>
	  <tr class="tbr">
	  <td class="tbl" valign="top">
	  <strong>Reiner</strong><br /><br />
	  <a href="http://www.greetsiel-feriendomizil.de" target="_blank"><img src="template/lang/all/icons/home.gif" width="20" height="21" alt="Website besuchen" title="Website besuchen"border="0" /></a><br />
	  <a href="mailto:rebisa@gmx.de"><img src="template/lang/all/icons/mail.gif" width="20" height="21" alt="E-Mail senden" title="E-Mail senden"border="0" /></a></td>
	  <td valign="top" style="padding:10PX;">schöne Seite. Respekt</td>
	  </tr>
  
	  <tr class="tbb">
	  <td width="130" class="tbh"> &nbsp;34 </td>
	  <td align="right" class="tbh">Vom 22.01.2010 um 01:11 Uhr&nbsp;</td>
	  </tr>
	  <tr class="tbr">
	  <td class="tbl" valign="top">
	  <strong>Tom</strong><br /><br />
	  <a href="http://www.b2bizness.com/link/Online-Roulette.38.html" target="_blank"><img src="template/lang/all/icons/home.gif" width="20" height="21" alt="Website besuchen" title="Website besuchen"border="0" /></a><br />
	  </td>
	  <td valign="top" style="padding:10PX;">Vielen Danke für die Infos!</td>
	  </tr>
  
	  <tr class="tbb">
	  <td width="130" class="tbh"> &nbsp;35 </td>
	  <td align="right" class="tbh">Vom 20.01.2010 um 09:41 Uhr&nbsp;</td>
	  </tr>
	  <tr class="tbr">
	  <td class="tbl" valign="top">
	  <strong>Michael</strong><br /><br />
	  <a href="http://www.mkschubert.de" target="_blank"><img src="template/lang/all/icons/home.gif" width="20" height="21" alt="Website besuchen" title="Website besuchen"border="0" /></a><br />
	  </td>
	  <td valign="top" style="padding:10PX;">Hallo, mir hat Deine Webseite sehr gefallen, auf die ich heute durch Zufall gekommen bin. Du hast Dir sehr viel Mühe gegeben! Freue mich natürlich immer auch auf einen Gegenbesuch bei mir. Auf meinen Reiseseiten berichte ich u.a. über meine wunderschönen Reisen nach Australien, Neuseeland, Thailand und in die USA, über meine interessanten Arbeitserfahrungen in England und Irland sowie über meine traumatischen Erfahrungen in einem österreichischen Krankenhaus. Weiterhin viel Erfolg mit Deiner Seite wünscht Dir Michael!<br />
http://www.michaels-reisetagebuch.de</td>
	  </tr>
  
	  <tr class="tbb">
	  <td width="130" class="tbh"> &nbsp;36 </td>
	  <td align="right" class="tbh">Vom 15.01.2010 um 06:43 Uhr&nbsp;</td>
	  </tr>
	  <tr class="tbr">
	  <td class="tbl" valign="top">
	  <strong>Marie</strong><br /><br />
	  <a href="http://www.llogin.com/projekt/" target="_blank"><img src="template/lang/all/icons/home.gif" width="20" height="21" alt="Website besuchen" title="Website besuchen"border="0" /></a><br />
	  <a href="mailto:mmb@msn.com"><img src="template/lang/all/icons/mail.gif" width="20" height="21" alt="E-Mail senden" title="E-Mail senden"border="0" /></a></td>
	  <td valign="top" style="padding:10PX;">nette Seite, wünsche viel Erfolg und<br />
Schöne Grüße,<br />
Marie.</td>
	  </tr>
  
	  <tr class="tbb">
	  <td width="130" class="tbh"> &nbsp;37 </td>
	  <td align="right" class="tbh">Vom 11.01.2010 um 06:49 Uhr&nbsp;</td>
	  </tr>
	  <tr class="tbr">
	  <td class="tbl" valign="top">
	  <strong>T. Pöhler</strong><br /><br />
	  <a href="http://www.poewatec.de" target="_blank"><img src="template/lang/all/icons/home.gif" width="20" height="21" alt="Website besuchen" title="Website besuchen"border="0" /></a><br />
	  <a href="mailto:info@poewatec.de"><img src="template/lang/all/icons/mail.gif" width="20" height="21" alt="E-Mail senden" title="E-Mail senden"border="0" /></a></td>
	  <td valign="top" style="padding:10PX;">Tolle Seite, weiterhin viel Erfolg für 2010!<br />
<br />
LG<br />
<br />
Torsten</td>
	  </tr>
  
	  <tr class="tbb">
	  <td width="130" class="tbh"> &nbsp;38 </td>
	  <td align="right" class="tbh">Vom 02.01.2010 um 03:29 Uhr&nbsp;</td>
	  </tr>
	  <tr class="tbr">
	  <td class="tbl" valign="top">
	  <strong>Markus</strong><br /><br />
	  <a href="http://www.blurayking.com" target="_blank"><img src="template/lang/all/icons/home.gif" width="20" height="21" alt="Website besuchen" title="Website besuchen"border="0" /></a><br />
	  <a href="mailto:mmmhome@web.de"><img src="template/lang/all/icons/mail.gif" width="20" height="21" alt="E-Mail senden" title="E-Mail senden"border="0" /></a></td>
	  <td valign="top" style="padding:10PX;">Ich wünsche euch alles gute im Jahr 2010<br />
<br />
LG<br />
Markus</td>
	  </tr>
  
	  <tr class="tbb">
	  <td width="130" class="tbh"> &nbsp;39 </td>
	  <td align="right" class="tbh">Vom 27.12.2009 um 10:03 Uhr&nbsp;</td>
	  </tr>
	  <tr class="tbr">
	  <td class="tbl" valign="top">
	  <strong>Urlaub mal auf Sylt</strong><br /><br />
	  <a href="http://www.Urlaub-Lange.de" target="_blank"><img src="template/lang/all/icons/home.gif" width="20" height="21" alt="Website besuchen" title="Website besuchen"border="0" /></a><br />
	  <a href="mailto:vo-la@web.de"><img src="template/lang/all/icons/mail.gif" width="20" height="21" alt="E-Mail senden" title="E-Mail senden"border="0" /></a></td>
	  <td valign="top" style="padding:10PX;">Ein Kompliment für diese tolle Seite.<br />
*** bin ich durch Zufall darauf gestoßen und dachte mir,<br />
einen netten Eintrag und viele Grüße zu hinterlassen.<br />
_____ &#92;&#92;&#92;!!!///____<br />
______( ô ô )_____<br />
___ooO-(_)-Ooo___<br />
Vielleicht schauen sie mal auf meiner Homepage vorbei!<br />
<br />
http://www.MeerblickSylt.de</td>
	  </tr>
  
	  <tr class="tbb">
	  <td width="130" class="tbh"> &nbsp;40 </td>
	  <td align="right" class="tbh">Vom 16.12.2009 um 22:30 Uhr&nbsp;</td>
	  </tr>
	  <tr class="tbr">
	  <td class="tbl" valign="top">
	  <strong>Urs</strong><br /><br />
	  <a href="http://www.glasamsee.ch" target="_blank"><img src="template/lang/all/icons/home.gif" width="20" height="21" alt="Website besuchen" title="Website besuchen"border="0" /></a><br />
	  </td>
	  <td valign="top" style="padding:10PX;">Vielen Dank für diese hilfreiche und effiziente Unterstützungswebsite...</td>
	  </tr>
  
</table>

  <form name="sign_guestbook" action="index.php?id=102,54,1,1,1,3" method="post">

			<table border="0" cellspacing="2" cellpadding="2">
			<tr>
			<td valign="top"><label for="guestbook_email">E-Mail *</label></td>
			<td valign="top"><input name="guestbook_email" type="text" id="guestbook_email" class="gbInputField" value="" size="50" maxlength="250" /></td>
			</tr>		
			<tr>	
			<td valign="top"><label for="guestbook_name">Name *</label></td>
			<td valign="top"><input name="guestbook_name" type="text" id="guestbook_name" class="gbInputField" value="" size="50" maxlength="500" /></td>
			</tr>
			<tr>
			<td valign="top"><label for="guestbook_url">Website</label></td>
			<td valign="top"><input name="guestbook_url" type="text" id="guestbook_url" class="gbInputField" value="" size="50" maxlength="1000" /></td>
			</tr>		
			<tr>
			<td valign="top"><label for="guestbook_msg">Kommentar*</label></td>
			<td valign="top"><textarea name="guestbook_msg" cols="50" rows="6" id="guestbook_msg" class="gbInputTextarea"></textarea></td>
			</tr>
			
			<tr>
			<td><label>E-Mail </label></td>
			<td>			
			<input name="guestbook_show" type="radio" value="0" id="guestbook_show0" checked="checked" />
			<label for="guestbook_show0">zeigen</label>
			<input name="guestbook_show" type="radio" value="1" id="guestbook_show1" />
			<label for="guestbook_show1">verstecken</label>
			<input name="guestbook_show" type="radio" value="2" id="guestbook_show2" />
			<label for="guestbook_show2">als &quot;info at mail dot de&quot; zeigen</label>
			</td>
			</tr>
<!--CAPTCHA_START//-->
			<tr>
			<td>&nbsp;</td>
			<td><br />
				<table width="100%" border="0" cellspacing="0" cellpadding="0">
					<tr>
						<td><label for="guestbook_captcha">Code ablesen ...</label></td>
						<td>... und hier eintragen</td>
					</tr>
					<tr><td><img src="img/captcha.php?regen=y&amp;length=5&amp;1291248953" alt="Captcha" border="0" id="gbCaptchaImage" /></td>
						<td><input name="guestbook_captcha" type="text" id="guestbook_captcha" class="gbInputFieldCaptcha" value="" size="10" maxlength="10" /></td>
					</tr>
				</table>
			</td>
			</tr>
			<tr><td colspan="2">&nbsp;</td></tr>		
<!--CAPTCHA_END//-->
			<tr>
			<td>&nbsp;</td>
			<td>
			<input name="guestbook_send" class="button" type="submit" id="guestbook_send" value="Eintrag vornehmen" />
			</td>
			</tr>
			</table>
<input type="hidden" name="946865f6099ece37d5c46dfad381d81c" value="314201" /></form> 

  


		
</div>
</div><br />
<strong>URL:<a href="deutsche_version.phtml?id=102,54,1,1,1,3" target="_blank">deutsche_version.phtml?id=102,54,1,1,1,3</a></strong>
</body>
</html>