<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<!--
	phpwcms | free open source content management system
	created by Oliver Georgi (oliver at phpwcms dot de) and licensed under GNU/GPL.
	phpwcms is copyright 2003-2007 of Oliver Georgi. Extensions are copyright of
	their respective owners. Visit project page for details: http://www.phpwcms.org/
//-->
<title>Gästebuch | Gästebuch</title>
  <meta http-equiv="content-type" content="text/html; charset=iso-8859-1" />
  <meta http-equiv="content-style-type" content="text/css" />
  <script src="template/inc_js/frontend.js" type="text/javascript"></script>
  <style type="text/css" media="all">
  <!-- 
    body {
      margin: 0;
      padding-top: 0;
      padding-bottom: 0;
      padding-left: 0;
      padding-right: 0;

    }
  //-->
  </style>
  <style type="text/css">
  <!-- 
    @import url("template/inc_css/print_layout.css");
  //-->
  </style>
<script type="text/javascript" language="javascript">
<!--
function MM_jumpMenu(targ,selObj,restore){ //v3.0
  eval(targ+".location='"+selObj.options[selObj.selectedIndex].value+"'");
  if (restore) selObj.selectedIndex=0;
}

function MM_findObj(n, d) { //v4.01
  var p,i,x;  if(!d) d=document; if((p=n.indexOf("?"))>0&&parent.frames.length) {
    d=parent.frames[n.substring(p+1)].document; n=n.substring(0,p);}
  if(!(x=d[n])&&d.all) x=d.all[n]; for (i=0;!x&&i<d.forms.length;i++) x=d.forms[i][n];
  for(i=0;!x&&d.layers&&i<d.layers.length;i++) x=MM_findObj(n,d.layers[i].document);
  if(!x && d.getElementById) x=d.getElementById(n); return x;
}

function MM_jumpMenuGo(selName,targ,restore){ //v3.0
  var selObj = MM_findObj(selName); if (selObj) MM_jumpMenu(targ,selObj,restore);
}
//-->
</script>
<meta name="Title" content="Die phpWCMS Dokumentation" />
<meta name="author" content="Oliver Frohnert, Mario Perez Leal" />
<meta name="Publisher" content="Oliver Frohnert, Mario Perez Leal, creacion" />
<meta name="Copyright" content="Oliver Frohnert, Mario Perez Leal, creacion" />
<meta name="keywords" content="frohnert, perez leal, creacion, documentation, dokumentation, phpwcms, cms, opensource, open source, docu" />
<meta name="description" content="Das Dokumentations Projekt für das Open Source CMS phpWCMS" />
<meta name="Audience" content="Alle" />
<meta name="Content-language" content="DE" />
<meta name="robots" content="index,follow" />
<meta name="expires" content="0" />
<meta name="revisit-after" content="7 days" />
<meta name="resource-type" content="document" />
<meta name="distribution" content="Global" />
<meta name="generator" content="PHPWCMS" />
<meta name="verify-v1" content="1ZpxZ7AZsjm7PxjqXQVus0eiUYqOsp5URTJn9q4KNz8=" />
  <!--[if lt IE 7]>
  <style type="text/css">
    body { behavior: url("template/inc_css/specific/csshover2.htc"); }
    img { behavior: url("template/inc_css/specific/pngbehavior.htc"); }
  </style>
  <![endif]-->
</head>
<body id="myid_102">


<!--

	this is the default PDF template
	use it to add additional header or
	footer information or whatever you 
	like to be rendered 

//-->

<div style="width:50%; border:1px solid #0f57a6; padding:10px; margin:10px;">
<p style="margin-bottom:20px;"><img src="./template/img/printlogo.gif" width="255" height="91" alt="" border="0" /></p>

<div id="container"><a name="top" id="top"></a>

		<a name="jump54"></a><!-- 
custom article template to split up the view / entry area for the guestbook
template by oliver@phpwcms-docu.de
===========================================================================
//-->
<div>
<h1 style="margin:0 0 5px 0;">Gästebuch</h1>
<h3 style="margin:0 0 5px 0;">Wir würden uns über einen Eintrag  freuen...</h3>
</div>

<div style="margin:25px 0 0 0;padding:0;" class="spaceBeforeCP"></div>
  
  
  
  

<table width="100%"  border="0" cellspacing="0" cellpadding="0" style="margin-top:5px;">
  <tr>
    <td><strong><a href="102.54.1.1.1.0.phtml">&laquo;&laquo;</a> <a href="102.54.1.1.1.3.phtml">&laquo;</a></strong> <a href="102.54.1.1.1.2.phtml">3</a>&nbsp;<a href="102.54.1.1.1.3.phtml">4</a>&nbsp;<strong>5</strong>&nbsp;<a href="102.54.1.1.1.5.phtml">6</a>&nbsp;<a href="102.54.1.1.1.6.phtml">7</a> <strong><a href="102.54.1.1.1.5.phtml">&raquo;</a>
        <a href="102.54.1.1.1.14.phtml">&raquo;&raquo;</a></strong></td>
    <td align="right"></td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
</table>


	  <table width="100%" border="0" cellspacing="0" cellpadding="0">
  
	  <tr class="tbb">
	  <td width="130" class="tbh"> &nbsp;41 </td>
	  <td align="right" class="tbh">Vom 15.12.2009 um 21:42 Uhr&nbsp;</td>
	  </tr>
	  <tr class="tbr">
	  <td class="tbl" valign="top">
	  <strong>Torsten</strong><br /><br />
	  <a href="http://www.poewatec.de" target="_blank"><img src="template/lang/all/icons/home.gif" width="20" height="21" alt="Website besuchen" title="Website besuchen"border="0" /></a><br />
	  </td>
	  <td valign="top" style="padding:10PX;">Eine tolle Seite, kann ich ur weiterempfehlen!<br />
<br />
Liebe Grüße und ein fohes Weihnachtsfest<br />
<br />
Torsten</td>
	  </tr>
  
	  <tr class="tbb">
	  <td width="130" class="tbh"> &nbsp;42 </td>
	  <td align="right" class="tbh">Vom 13.12.2009 um 20:27 Uhr&nbsp;</td>
	  </tr>
	  <tr class="tbr">
	  <td class="tbl" valign="top">
	  <strong>EinEuroShopping</strong><br /><br />
	  <a href="http://www.eineuroshopping.de" target="_blank"><img src="template/lang/all/icons/home.gif" width="20" height="21" alt="Website besuchen" title="Website besuchen"border="0" /></a><br />
	  </td>
	  <td valign="top" style="padding:10PX;">Hi, Kompliment zu dieser schönen Seite.<br />
Eigentlich sind wir nur durch Zufall auf diese Seite gestoßen und dachten uns wir<br />
hinterlassen mal einen netten Eintrag und<br />
viele Grüße im Gästebuch.<br />
<br />
Vielleicht schauen sie mal auf unserer Homepage vorbei!<br />
<br />
Herzliche Grüße vom<br />
EinEuroShopping.de Team</td>
	  </tr>
  
	  <tr class="tbb">
	  <td width="130" class="tbh"> &nbsp;43 </td>
	  <td align="right" class="tbh">Vom 10.12.2009 um 09:03 Uhr&nbsp;</td>
	  </tr>
	  <tr class="tbr">
	  <td class="tbl" valign="top">
	  <strong>Reinhard</strong><br /><br />
	  <a href="http://www.falcana.com" target="_blank"><img src="template/lang/all/icons/home.gif" width="20" height="21" alt="Website besuchen" title="Website besuchen"border="0" /></a><br />
	  office at falcana dot com</td>
	  <td valign="top" style="padding:10PX;">Tolle Website, finde ich sehr hilfreich.</td>
	  </tr>
  
	  <tr class="tbb">
	  <td width="130" class="tbh"> &nbsp;44 </td>
	  <td align="right" class="tbh">Vom 07.12.2009 um 21:29 Uhr&nbsp;</td>
	  </tr>
	  <tr class="tbr">
	  <td class="tbl" valign="top">
	  <strong>Peter</strong><br /><br />
	  <a href="http://www.massage-atem.ch" target="_blank"><img src="template/lang/all/icons/home.gif" width="20" height="21" alt="Website besuchen" title="Website besuchen"border="0" /></a><br />
	  </td>
	  <td valign="top" style="padding:10PX;">Eine Gute Dokumentation -- war mir eine gute Hilfe beim Problemlösen. Danke.</td>
	  </tr>
  
	  <tr class="tbb">
	  <td width="130" class="tbh"> &nbsp;45 </td>
	  <td align="right" class="tbh">Vom 04.12.2009 um 08:18 Uhr&nbsp;</td>
	  </tr>
	  <tr class="tbr">
	  <td class="tbl" valign="top">
	  <strong>martin</strong><br /><br />
	  <a href="http://verdiene-dein-geld-im-schlaf.de.tl" target="_blank"><img src="template/lang/all/icons/home.gif" width="20" height="21" alt="Website besuchen" title="Website besuchen"border="0" /></a><br />
	  <a href="mailto:glura@web.de"><img src="template/lang/all/icons/mail.gif" width="20" height="21" alt="E-Mail senden" title="E-Mail senden"border="0" /></a></td>
	  <td valign="top" style="padding:10PX;">Fichten, Lametta, Kugeln und Lichter, Bratäpfelduft und frohe Gesichter, Freude am Schenken - das Herz wird so weit. Ich wünsch allen: Eine fröhliche Weihnachtszeit!</td>
	  </tr>
  
	  <tr class="tbb">
	  <td width="130" class="tbh"> &nbsp;46 </td>
	  <td align="right" class="tbh">Vom 28.11.2009 um 15:34 Uhr&nbsp;</td>
	  </tr>
	  <tr class="tbr">
	  <td class="tbl" valign="top">
	  <strong>Tom</strong><br /><br />
	  <a href="http://www.coaching-meilen.ch" target="_blank"><img src="template/lang/all/icons/home.gif" width="20" height="21" alt="Website besuchen" title="Website besuchen"border="0" /></a><br />
	  </td>
	  <td valign="top" style="padding:10PX;">Super dieses Forum, ich konnte so mein Problem lösen. Weiter so...</td>
	  </tr>
  
	  <tr class="tbb">
	  <td width="130" class="tbh"> &nbsp;47 </td>
	  <td align="right" class="tbh">Vom 31.10.2009 um 08:51 Uhr&nbsp;</td>
	  </tr>
	  <tr class="tbr">
	  <td class="tbl" valign="top">
	  <strong>Berg Andi</strong><br /><br />
	  <a href="http://www.arcom-center.de/store" target="_blank"><img src="template/lang/all/icons/home.gif" width="20" height="21" alt="Website besuchen" title="Website besuchen"border="0" /></a><br />
	  <a href="mailto:arcom-gmbh@gmx.de"><img src="template/lang/all/icons/mail.gif" width="20" height="21" alt="E-Mail senden" title="E-Mail senden"border="0" /></a></td>
	  <td valign="top" style="padding:10PX;">Guter Aufbau der Seite. Interessant auch die Docu. Werde ich gerne weiter empfehlen. Gruß aus München</td>
	  </tr>
  
	  <tr class="tbb">
	  <td width="130" class="tbh"> &nbsp;48 </td>
	  <td align="right" class="tbh">Vom 23.10.2009 um 08:06 Uhr&nbsp;</td>
	  </tr>
	  <tr class="tbr">
	  <td class="tbl" valign="top">
	  <strong>Volker Lange</strong><br /><br />
	  <a href="http://www.ostseeblickholm.de" target="_blank"><img src="template/lang/all/icons/home.gif" width="20" height="21" alt="Website besuchen" title="Website besuchen"border="0" /></a><br />
	  <a href="mailto:vo-la@web.de"><img src="template/lang/all/icons/mail.gif" width="20" height="21" alt="E-Mail senden" title="E-Mail senden"border="0" /></a></td>
	  <td valign="top" style="padding:10PX;">Hallo!Ich bin beim Surfen auf eure Homepage gekommen, eine schöne und informative Seite habt ihr hier ins Netz gestellt, da kommt man gern wieder zu Besuch. Viele  Grüße und weiterhin viel Erfolg</td>
	  </tr>
  
	  <tr class="tbb">
	  <td width="130" class="tbh"> &nbsp;49 </td>
	  <td align="right" class="tbh">Vom 20.10.2009 um 11:14 Uhr&nbsp;</td>
	  </tr>
	  <tr class="tbr">
	  <td class="tbl" valign="top">
	  <strong>doris</strong><br /><br />
	  <a href="http://www.free-sex-films-sado-maso.us" target="_blank"><img src="template/lang/all/icons/home.gif" width="20" height="21" alt="Website besuchen" title="Website besuchen"border="0" /></a><br />
	  <a href="mailto:doris078@gmail.com"><img src="template/lang/all/icons/mail.gif" width="20" height="21" alt="E-Mail senden" title="E-Mail senden"border="0" /></a></td>
	  <td valign="top" style="padding:10PX;">Ich finde den Aufbau der Seite sehr gut. Macht weiter so.</td>
	  </tr>
  
	  <tr class="tbb">
	  <td width="130" class="tbh"> &nbsp;50 </td>
	  <td align="right" class="tbh">Vom 19.10.2009 um 01:28 Uhr&nbsp;</td>
	  </tr>
	  <tr class="tbr">
	  <td class="tbl" valign="top">
	  <strong>André Baldeweg</strong><br /><br />
	  <a href="http://www.sokole-fans.de" target="_blank"><img src="template/lang/all/icons/home.gif" width="20" height="21" alt="Website besuchen" title="Website besuchen"border="0" /></a><br />
	  </td>
	  <td valign="top" style="padding:10PX;">Sehr gelungene und hilfreiche Seite! Danke!</td>
	  </tr>
  
</table>

  <form name="sign_guestbook" action="index.php?id=102,54,1,1,1,4" method="post">

			<table border="0" cellspacing="2" cellpadding="2">
			<tr>
			<td valign="top"><label for="guestbook_email">E-Mail *</label></td>
			<td valign="top"><input name="guestbook_email" type="text" id="guestbook_email" class="gbInputField" value="" size="50" maxlength="250" /></td>
			</tr>		
			<tr>	
			<td valign="top"><label for="guestbook_name">Name *</label></td>
			<td valign="top"><input name="guestbook_name" type="text" id="guestbook_name" class="gbInputField" value="" size="50" maxlength="500" /></td>
			</tr>
			<tr>
			<td valign="top"><label for="guestbook_url">Website</label></td>
			<td valign="top"><input name="guestbook_url" type="text" id="guestbook_url" class="gbInputField" value="" size="50" maxlength="1000" /></td>
			</tr>		
			<tr>
			<td valign="top"><label for="guestbook_msg">Kommentar*</label></td>
			<td valign="top"><textarea name="guestbook_msg" cols="50" rows="6" id="guestbook_msg" class="gbInputTextarea"></textarea></td>
			</tr>
			
			<tr>
			<td><label>E-Mail </label></td>
			<td>			
			<input name="guestbook_show" type="radio" value="0" id="guestbook_show0" checked="checked" />
			<label for="guestbook_show0">zeigen</label>
			<input name="guestbook_show" type="radio" value="1" id="guestbook_show1" />
			<label for="guestbook_show1">verstecken</label>
			<input name="guestbook_show" type="radio" value="2" id="guestbook_show2" />
			<label for="guestbook_show2">als &quot;info at mail dot de&quot; zeigen</label>
			</td>
			</tr>
<!--CAPTCHA_START//-->
			<tr>
			<td>&nbsp;</td>
			<td><br />
				<table width="100%" border="0" cellspacing="0" cellpadding="0">
					<tr>
						<td><label for="guestbook_captcha">Code ablesen ...</label></td>
						<td>... und hier eintragen</td>
					</tr>
					<tr><td><img src="img/captcha.php?regen=y&amp;length=5&amp;1291248972" alt="Captcha" border="0" id="gbCaptchaImage" /></td>
						<td><input name="guestbook_captcha" type="text" id="guestbook_captcha" class="gbInputFieldCaptcha" value="" size="10" maxlength="10" /></td>
					</tr>
				</table>
			</td>
			</tr>
			<tr><td colspan="2">&nbsp;</td></tr>		
<!--CAPTCHA_END//-->
			<tr>
			<td>&nbsp;</td>
			<td>
			<input name="guestbook_send" class="button" type="submit" id="guestbook_send" value="Eintrag vornehmen" />
			</td>
			</tr>
			</table>
<input type="hidden" name="946865f6099ece37d5c46dfad381d81c" value="314203" /></form> 

  


		
</div>
</div><br />
<strong>URL:<a href="deutsche_version.phtml?id=102,54,1,1,1,4" target="_blank">deutsche_version.phtml?id=102,54,1,1,1,4</a></strong>
</body>
</html>