<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<!--
	phpwcms | free open source content management system
	created by Oliver Georgi (oliver at phpwcms dot de) and licensed under GNU/GPL.
	phpwcms is copyright 2003-2007 of Oliver Georgi. Extensions are copyright of
	their respective owners. Visit project page for details: http://www.phpwcms.org/
//-->
<title>Gästebuch | Gästebuch</title>
  <meta http-equiv="content-type" content="text/html; charset=iso-8859-1" />
  <meta http-equiv="content-style-type" content="text/css" />
  <script src="template/inc_js/frontend.js" type="text/javascript"></script>
  <style type="text/css" media="all">
  <!-- 
    body {
      margin: 0;
      padding-top: 0;
      padding-bottom: 0;
      padding-left: 0;
      padding-right: 0;

    }
  //-->
  </style>
  <style type="text/css">
  <!-- 
    @import url("template/inc_css/frontend.css");
    @import url("template/inc_css/nlu_navi1_docu.css");
  //-->
  </style>


<META NAME="Title" CONTENT="Die phpWCMS Dokumentation">
<meta name="author" content="Oliver Frohnert">
<meta name="Publisher" content="Oliver Frohnert">
<meta name="Copyright" content="Oliver Frohnert">
<meta name="keywords" content="frohnert,documentation, dokumentation, phpwcms, cms, opensource, open source">
<meta name="description" content="Das Dokumentations Projekt für das Open Source CMS phpWCMS">
<meta name="Audience" content="Alle">
<meta name="Content-language" content="DE">
<META NAME="robots"      CONTENT="index,follow">
<META NAME="expires" CONTENT="0">
<meta name="revisit-after" content="7 days">
<meta name="resource-type" content="document">
<meta name="distribution" content="Global">
<meta name="generator" content="PHPWCMS">

  <!--[if lt IE 7]>
  <style type="text/css">
    body { behavior: url("template/inc_css/specific/csshover2.htc"); }
    img { behavior: url("template/inc_css/specific/pngbehavior.htc"); }
  </style>
  <![endif]-->
</head>
<body>


<!--

	this is the default PDF template
	use it to add additional header or
	footer information or whatever you 
	like to be rendered 

//-->
URL: <a href="deutsche_version.phtml?id=102,54,1,1,1,7" target="_blank">deutsche_version.phtml?id=102,54,1,1,1,7</a>
<hr />
<img src="img/leer.gif" border="0" width="10" height="1" alt="" />
<br />
<a href="deutsche_version.phtml">Deutsch</a> <span class="breadcrumb_spacer">&gt;</span> <a href="kontakt.phtml">Kontakt</a> <span class="breadcrumb_spacer">&gt;</span> Gästebuch
<br />
<HR>
<br />
<a name="jump54"></a><div>
<h1 style="margin:0 0 5px 0;">Gästebuch</h1>
<h3 style="margin:0 0 5px 0;">Wir würden uns über einen Eintrag  freuen...</h3>

</div><div style="margin:25px 0 0 0;padding:0;" class="spaceBeforeCP"></div>
   
<table width="100%"  border="0" cellspacing="0" cellpadding="0" style="margin-top:5px;">
  <tr>
    <td><strong><a href="102.54.1.1.1.0.phtml">&lt;&lt;</a> <a href="102.54.1.1.1.6.phtml">&lt;</a></strong> <a href="102.54.1.1.1.3.phtml">4</a>&nbsp;<a href="102.54.1.1.1.4.phtml">5</a>&nbsp;<a href="102.54.1.1.1.5.phtml">6</a>&nbsp;<a href="102.54.1.1.1.6.phtml">7</a>&nbsp;<strong>8</strong> <strong>&gt;
        &gt;&gt;</strong></td>
    <td align="right">&nbsp;</td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
</table>

<table width="100%"  border="0" cellspacing="0" cellpadding="2">
  
  <tr bgcolor="#F5F5F5">
    <td width="1%" align="right"><strong>71&nbsp;&nbsp;</strong></td>
    <td width="99%"><!-- 8 | -->08/26/2004 12:07</td>
  </tr>
  <tr>
    <td colspan="2"><a href="mailto:"><strong>tom</strong></a>  <br />
      Hallo wertes Doku-Team,<br />
ich bewundere Euren Einsatz und das Engagement für eine umfassende zentrale Dokumentation von phpwcms.<br />
Damit wird es sicherlich noch viel mehr Installationen von phpwcms geben und die Möglichkeit bestehen, viele interessante Menschen durch dieses Projekt kennenzulernen.<br />
Der gute Geist des Forums trägt sicher auch hier Früchte - ich wünsche allen viel Erfolg und gutes Gelingen bei allen Projekten.<br />
<br />
Beste Grüße<br />
<br />
Thomas<br />
<br />
<span style="color:#00CC00;">Hi Thomas, vielen Dank für die Anerkennung, auch wenn ich selber (brans) noch nicht viel geschrieben habe, denke ich, darf ich im Namen von allen sprechen und sagen, dass nur durch gegenseitige Anerkennung der gute Geist des WCMS-Forums erhalten bleibt.<br />
brans</span></td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
  
  <tr bgcolor="#F5F5F5">
    <td width="1%" align="right"><strong>72&nbsp;&nbsp;</strong></td>
    <td width="99%"><!-- 7 | -->08/16/2004 14:27</td>
  </tr>
  <tr>
    <td colspan="2"><a href="mailto:stephan at rackco dot com"><strong>Stephan Mackenzie</strong></a>  stephan at rackco dot com<br />
      PHPWCMS is the greatest... keep up the good work, a centralized documentation is a fantastic idea... kudos to the ones responsible!</td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
  
  <tr bgcolor="#F5F5F5">
    <td width="1%" align="right"><strong>73&nbsp;&nbsp;</strong></td>
    <td width="99%"><!-- 6 | -->08/16/2004 02:19</td>
  </tr>
  <tr>
    <td colspan="2"><a href="mailto:cfoxgrover@foxpath.com"><strong>Chick Foxgrover</strong></a>  cfoxgrover@foxpath.com<br />
      Great resource for a terrific CMS script. Thanks!</td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
  
  <tr bgcolor="#F5F5F5">
    <td width="1%" align="right"><strong>74&nbsp;&nbsp;</strong></td>
    <td width="99%"><!-- 5 | -->08/15/2004 19:30</td>
  </tr>
  <tr>
    <td colspan="2"><a href="mailto:uwe.twelker at eyelikeit dot de"><strong>Uwe Twelker</strong></a>  uwe.twelker at eyelikeit dot de<br />
      I&#039;m using the PHPWCMS for about half a year. And I think it&#039;s dynamite. What makes it great is of course the PHPWCMS itself. Easy to install, easy to use (you feel like driving a Mac!). But that&#039;s far form being everything. There is an Oliver who talks and listens to his users and works and works and works... There is a great community assisting in the forum. They are fast, they are friendly, there are competencies for almost everything and this knowledge is generously shared. There is another Oliver, and Manfred and Achim and Jayenne who work there butts off to set up this documentation. And there a lot of more unknown people with a lot of unknown useful contributions.<br />
<br />
Thank you all. I&#039;m proud to be part of this community!<br />
<br />
<span style="color:#00CC00;">hello mac and thank you for the translation and the correction of some articles.<br />
Oliver &quot;Pappnase&quot;</span></td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
  
  <tr bgcolor="#F5F5F5">
    <td width="1%" align="right"><strong>75&nbsp;&nbsp;</strong></td>
    <td width="99%"><!-- 4 | -->08/14/2004 16:34</td>
  </tr>
  <tr>
    <td colspan="2"><a href="mailto:timdriever@hotmail.com"><strong>Tim Driever</strong></a>  timdriever@hotmail.com<br />
      PHPWcms is a great CMS!! Good work Oliver and the crew from this site that you make a documenation for PHPWcms! Succes..!</td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
  
  <tr bgcolor="#F5F5F5">
    <td width="1%" align="right"><strong>76&nbsp;&nbsp;</strong></td>
    <td width="99%"><!-- 3 | -->08/14/2004 01:10</td>
  </tr>
  <tr>
    <td colspan="2"><a href="mailto:spam@jerome-gamez.de"><strong>Jérôme Gamez</strong></a>  spam@jerome-gamez.de<br />
      Sehr gute Arbeit. Die Seite wird fortwährend umfangreicher und besser. Vielen Dank für euren unermüdlichen Einsatz, insb. Oliver (Pappnase), bei dem man sich fragen &quot;muss&quot;, ob er eigentlich irgendwann auch mal schläft oder etwas anderes macht :).<br />
<br />
Viele Grüße<br />
- Jérôme</td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
  
  <tr bgcolor="#F5F5F5">
    <td width="1%" align="right"><strong>77&nbsp;&nbsp;</strong></td>
    <td width="99%"><!-- 2 | -->08/12/2004 21:31</td>
  </tr>
  <tr>
    <td colspan="2"><a href="mailto:design@istwan.com"><strong>Stefan Bachfischer</strong></a>  design@istwan.com<br />
      Einfach ein super CMS. Dieses Verwaltungssystem wird in zukunft in jede Website meiner Kunden eingebunden. (Und auch in die eigene:-)<br />
<br />
Macht weiter so!!</td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
  
  <tr bgcolor="#F5F5F5">
    <td width="1%" align="right"><strong>78&nbsp;&nbsp;</strong></td>
    <td width="99%"><!-- 1 | -->08/11/2004 13:40</td>
  </tr>
  <tr>
    <td colspan="2"><a href="mailto:webmaster@familie-eilert.com"><strong>Enrico Eilert</strong></a>  webmaster@familie-eilert.com<br />
      hallo,<br />
ich fange gerade an mit phpwcms zu arbeiten und bin gerade auf eurer Seite gelandet. Sie hilft auf jedem Fall weiter. Danke und weiter so.</td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
  
</table>

<table width="100%"  border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td colspan="2"><HR></td>
  </tr>
  <tr>
    <td width="50%">Artikel erstellt: 2004/08/16</td>
    <td align="right" width="50%">Letzte Änderung:2007/06/29</td>
  </tr>
  <tr>
    <td colspan="2">&nbsp;</td>
  </tr>
  <tr>
    <td colspan="2" class="comment">Wenn Sie einen Fehler entdecken eine Ergänzung oder Frage haben benutzen Sie bitte folgendes <a href="#" onClick="javascript:window.open('./content/pages/nachricht.htm','frage','width=400, height=250, screenX=440,screenY=200,menubar=no,statusbar=yes,scrollbar=yes,resizable=no');" target="" style="max-width:148px; overflow:hidden;"><u>Formular</u></a>.<br /><br />
Hat Ihnen oder Ihrem Kunden diese Docu weitergeholfen ? Dann würde ich mich freuen wenn Sie das Projekt unterstützen würden. Bitte nutzen Sie dafür diesen <a href="#paypal">PayPal</a> Link. Jeder Betrag ist möglich und hilft der Weiterentwicklung und Aktualisierung dieser Dokumentation.<br />
Diese Seite nutzt die version:</td>
  </tr>
  <tr>

    <td colspan="2"><img src="img/leer.gif" border="0" width="10" height="10" alt="" /></td>
  </tr>
</table>


</body>
</html>