<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<!--
	phpwcms | free open source content management system
	created by Oliver Georgi (oliver at phpwcms dot de) and licensed under GNU/GPL.
	phpwcms is copyright 2003-2007 of Oliver Georgi. Extensions are copyright of
	their respective owners. Visit project page for details: http://www.phpwcms.org/
//-->
<title>Gästebuch | Gästebuch</title>
  <meta http-equiv="content-type" content="text/html; charset=iso-8859-1" />
  <meta http-equiv="content-style-type" content="text/css" />
  <script src="template/inc_js/frontend.js" type="text/javascript"></script>
  <style type="text/css" media="all">
  <!-- 
    body {
      margin: 0;
      padding-top: 0;
      padding-bottom: 0;
      padding-left: 0;
      padding-right: 0;

    }
  //-->
  </style>
  <style type="text/css">
  <!-- 
    @import url("template/inc_css/print_layout.css");
  //-->
  </style>
<script type="text/javascript" language="javascript">
<!--
function MM_jumpMenu(targ,selObj,restore){ //v3.0
  eval(targ+".location='"+selObj.options[selObj.selectedIndex].value+"'");
  if (restore) selObj.selectedIndex=0;
}

function MM_findObj(n, d) { //v4.01
  var p,i,x;  if(!d) d=document; if((p=n.indexOf("?"))>0&&parent.frames.length) {
    d=parent.frames[n.substring(p+1)].document; n=n.substring(0,p);}
  if(!(x=d[n])&&d.all) x=d.all[n]; for (i=0;!x&&i<d.forms.length;i++) x=d.forms[i][n];
  for(i=0;!x&&d.layers&&i<d.layers.length;i++) x=MM_findObj(n,d.layers[i].document);
  if(!x && d.getElementById) x=d.getElementById(n); return x;
}

function MM_jumpMenuGo(selName,targ,restore){ //v3.0
  var selObj = MM_findObj(selName); if (selObj) MM_jumpMenu(targ,selObj,restore);
}
//-->
</script>
<meta name="Title" content="Die phpWCMS Dokumentation" />
<meta name="author" content="Oliver Frohnert, Mario Perez Leal" />
<meta name="Publisher" content="Oliver Frohnert, Mario Perez Leal, creacion" />
<meta name="Copyright" content="Oliver Frohnert, Mario Perez Leal, creacion" />
<meta name="keywords" content="frohnert, perez leal, creacion, documentation, dokumentation, phpwcms, cms, opensource, open source, docu" />
<meta name="description" content="Das Dokumentations Projekt für das Open Source CMS phpWCMS" />
<meta name="Audience" content="Alle" />
<meta name="Content-language" content="DE" />
<meta name="robots" content="index,follow" />
<meta name="expires" content="0" />
<meta name="revisit-after" content="7 days" />
<meta name="resource-type" content="document" />
<meta name="distribution" content="Global" />
<meta name="generator" content="PHPWCMS" />

  <!--[if lt IE 7]>
  <style type="text/css">
    body { behavior: url("template/inc_css/specific/csshover2.htc"); }
    img { behavior: url("template/inc_css/specific/pngbehavior.htc"); }
  </style>
  <![endif]-->
</head>
<body id="myid_102">


<!--

	this is the default PDF template
	use it to add additional header or
	footer information or whatever you 
	like to be rendered 

//-->

<div style="width:50%; border:1px solid #0f57a6; padding:10px; margin:10px;">
<p style="margin-bottom:20px;"><img src="./template/img/printlogo.gif" width="255" height="91" alt="" border="0" /></p>

<div id="container"><a name="top" id="top"></a>

		<a name="jump54"></a><!-- 
custom article template to split up the view / entry area for the guestbook
template by oliver@phpwcms-docu.de
===========================================================================
//-->
<div>
<h1 style="margin:0 0 5px 0;">Gästebuch</h1>
<h3 style="margin:0 0 5px 0;">Wir würden uns über einen Eintrag  freuen...</h3>
</div>

<div style="margin:25px 0 0 0;padding:0;" class="spaceBeforeCP"></div>
  
  
  
  

<table width="100%"  border="0" cellspacing="0" cellpadding="0" style="margin-top:5px;">
  <tr>
    <td><strong><a href="102.54.1.1.1.0.phtml">&laquo;&laquo;</a> <a href="102.54.1.1.1.11.phtml">&laquo;</a></strong> <a href="102.54.1.1.1.8.phtml">9</a>&nbsp;<a href="102.54.1.1.1.9.phtml">10</a>&nbsp;<a href="102.54.1.1.1.10.phtml">11</a>&nbsp;<a href="102.54.1.1.1.11.phtml">12</a>&nbsp;<strong>13</strong> <strong>&raquo;
        &raquo;&raquo;</strong></td>
    <td align="right"></td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
</table>


	  <table width="100%" border="0" cellspacing="0" cellpadding="0">
  
	  <tr class="tbb">
	  <td width="130" class="tbh"> &nbsp;121 </td>
	  <td align="right" class="tbh">Vom 01.09.2004 um 08:15 Uhr&nbsp;</td>
	  </tr>
	  <tr class="tbr">
	  <td class="tbl" valign="top">
	  <strong>Jason Benedict</strong><br /><br />
	  <a href="http://http://www.zaptech.net" target="_blank"><img src="template/lang/all/icons/home.gif" width="20" height="21" alt="Website besuchen" title="Website besuchen"border="0" /></a><br />
	  </td>
	  <td valign="top" style="padding:10PX;">Great work ! phpWCMS is one of the best system i ever used. I started with v1.1-RC1 and had been follow till now 1.1-RC4 -:)<br />
<br />
BTW, this site is very kool as well :).</td>
	  </tr>
  
	  <tr class="tbb">
	  <td width="130" class="tbh"> &nbsp;122 </td>
	  <td align="right" class="tbh">Vom 29.08.2004 um 20:57 Uhr&nbsp;</td>
	  </tr>
	  <tr class="tbr">
	  <td class="tbl" valign="top">
	  <strong>Rolf Dahl</strong><br /><br />
	  
	  </td>
	  <td valign="top" style="padding:10PX;">Nice work!</td>
	  </tr>
  
	  <tr class="tbb">
	  <td width="130" class="tbh"> &nbsp;123 </td>
	  <td align="right" class="tbh">Vom 26.08.2004 um 12:07 Uhr&nbsp;</td>
	  </tr>
	  <tr class="tbr">
	  <td class="tbl" valign="top">
	  <strong>tom</strong><br /><br />
	  
	  </td>
	  <td valign="top" style="padding:10PX;">Hallo wertes Doku-Team,<br />
ich bewundere Euren Einsatz und das Engagement für eine umfassende zentrale Dokumentation von phpwcms.<br />
Damit wird es sicherlich noch viel mehr Installationen von phpwcms geben und die Möglichkeit bestehen, viele interessante Menschen durch dieses Projekt kennenzulernen.<br />
Der gute Geist des Forums trägt sicher auch hier Früchte - ich wünsche allen viel Erfolg und gutes Gelingen bei allen Projekten.<br />
<br />
Beste Grüße<br />
<br />
Thomas<br />
<br />
<div style="background-color:#c1dbf7; padding:2px; border:1px dotted #517ba5;"><strong>Kommentar:</strong><br />Hi Thomas, vielen Dank für die Anerkennung, auch wenn ich selber (brans) noch nicht viel geschrieben habe, denke ich, darf ich im Namen von allen sprechen und sagen, dass nur durch gegenseitige Anerkennung der gute Geist des WCMS-Forums erhalten bleibt.<br />
brans</div></td>
	  </tr>
  
	  <tr class="tbb">
	  <td width="130" class="tbh"> &nbsp;124 </td>
	  <td align="right" class="tbh">Vom 16.08.2004 um 14:27 Uhr&nbsp;</td>
	  </tr>
	  <tr class="tbr">
	  <td class="tbl" valign="top">
	  <strong>Stephan Mackenzie</strong><br /><br />
	  <a href="http://http://www.rackco.com" target="_blank"><img src="template/lang/all/icons/home.gif" width="20" height="21" alt="Website besuchen" title="Website besuchen"border="0" /></a><br />
	  stephan at rackco dot com</td>
	  <td valign="top" style="padding:10PX;">PHPWCMS is the greatest... keep up the good work, a centralized documentation is a fantastic idea... kudos to the ones responsible!</td>
	  </tr>
  
	  <tr class="tbb">
	  <td width="130" class="tbh"> &nbsp;125 </td>
	  <td align="right" class="tbh">Vom 16.08.2004 um 02:19 Uhr&nbsp;</td>
	  </tr>
	  <tr class="tbr">
	  <td class="tbl" valign="top">
	  <strong>Chick Foxgrover</strong><br /><br />
	  
	  <a href="mailto:cfoxgrover@foxpath.com"><img src="template/lang/all/icons/mail.gif" width="20" height="21" alt="E-Mail senden" title="E-Mail senden"border="0" /></a></td>
	  <td valign="top" style="padding:10PX;">Great resource for a terrific CMS script. Thanks!</td>
	  </tr>
  
	  <tr class="tbb">
	  <td width="130" class="tbh"> &nbsp;126 </td>
	  <td align="right" class="tbh">Vom 15.08.2004 um 19:30 Uhr&nbsp;</td>
	  </tr>
	  <tr class="tbr">
	  <td class="tbl" valign="top">
	  <strong>Uwe Twelker</strong><br /><br />
	  <a href="http://http://www.eyelikeit.de" target="_blank"><img src="template/lang/all/icons/home.gif" width="20" height="21" alt="Website besuchen" title="Website besuchen"border="0" /></a><br />
	  uwe.twelker at eyelikeit dot de</td>
	  <td valign="top" style="padding:10PX;">I&#039;m using the PHPWCMS for about half a year. And I think it&#039;s dynamite. What makes it great is of course the PHPWCMS itself. Easy to install, easy to use (you feel like driving a Mac!). But that&#039;s far form being everything. There is an Oliver who talks and listens to his users and works and works and works... There is a great community assisting in the forum. They are fast, they are friendly, there are competencies for almost everything and this knowledge is generously shared. There is another Oliver, and Manfred and Achim and Jayenne who work there butts off to set up this documentation. And there a lot of more unknown people with a lot of unknown useful contributions.<br />
<br />
Thank you all. I&#039;m proud to be part of this community!<br />
<br />
<div style="background-color:#c1dbf7; padding:2px; border:1px dotted #517ba5;"><strong>Kommentar:</strong><br />hello mac and thank you for the translation and the correction of some articles.<br />
Oliver &quot;Pappnase&quot;</div></td>
	  </tr>
  
	  <tr class="tbb">
	  <td width="130" class="tbh"> &nbsp;127 </td>
	  <td align="right" class="tbh">Vom 14.08.2004 um 16:34 Uhr&nbsp;</td>
	  </tr>
	  <tr class="tbr">
	  <td class="tbl" valign="top">
	  <strong>Tim Driever</strong><br /><br />
	  
	  <a href="mailto:timdriever@hotmail.com"><img src="template/lang/all/icons/mail.gif" width="20" height="21" alt="E-Mail senden" title="E-Mail senden"border="0" /></a></td>
	  <td valign="top" style="padding:10PX;">PHPWcms is a great CMS!! Good work Oliver and the crew from this site that you make a documenation for PHPWcms! Succes..!</td>
	  </tr>
  
	  <tr class="tbb">
	  <td width="130" class="tbh"> &nbsp;128 </td>
	  <td align="right" class="tbh">Vom 14.08.2004 um 01:10 Uhr&nbsp;</td>
	  </tr>
	  <tr class="tbr">
	  <td class="tbl" valign="top">
	  <strong>Jérôme Gamez</strong><br /><br />
	  <a href="http://http://jerome-gamez.de/" target="_blank"><img src="template/lang/all/icons/home.gif" width="20" height="21" alt="Website besuchen" title="Website besuchen"border="0" /></a><br />
	  <a href="mailto:spam@jerome-gamez.de"><img src="template/lang/all/icons/mail.gif" width="20" height="21" alt="E-Mail senden" title="E-Mail senden"border="0" /></a></td>
	  <td valign="top" style="padding:10PX;">Sehr gute Arbeit. Die Seite wird fortwährend umfangreicher und besser. Vielen Dank für euren unermüdlichen Einsatz, insb. Oliver (Pappnase), bei dem man sich fragen &quot;muss&quot;, ob er eigentlich irgendwann auch mal schläft oder etwas anderes macht :).<br />
<br />
Viele Grüße<br />
- Jérôme</td>
	  </tr>
  
	  <tr class="tbb">
	  <td width="130" class="tbh"> &nbsp;129 </td>
	  <td align="right" class="tbh">Vom 12.08.2004 um 21:31 Uhr&nbsp;</td>
	  </tr>
	  <tr class="tbr">
	  <td class="tbl" valign="top">
	  <strong>Stefan Bachfischer</strong><br /><br />
	  <a href="http://http://www.istwan.com" target="_blank"><img src="template/lang/all/icons/home.gif" width="20" height="21" alt="Website besuchen" title="Website besuchen"border="0" /></a><br />
	  <a href="mailto:design@istwan.com"><img src="template/lang/all/icons/mail.gif" width="20" height="21" alt="E-Mail senden" title="E-Mail senden"border="0" /></a></td>
	  <td valign="top" style="padding:10PX;">Einfach ein super CMS. Dieses Verwaltungssystem wird in zukunft in jede Website meiner Kunden eingebunden. (Und auch in die eigene:-)<br />
<br />
Macht weiter so!!</td>
	  </tr>
  
	  <tr class="tbb">
	  <td width="130" class="tbh"> &nbsp;130 </td>
	  <td align="right" class="tbh">Vom 11.08.2004 um 13:40 Uhr&nbsp;</td>
	  </tr>
	  <tr class="tbr">
	  <td class="tbl" valign="top">
	  <strong>Enrico Eilert</strong><br /><br />
	  <a href="http://http://www.familie-eilert.com" target="_blank"><img src="template/lang/all/icons/home.gif" width="20" height="21" alt="Website besuchen" title="Website besuchen"border="0" /></a><br />
	  <a href="mailto:webmaster@familie-eilert.com"><img src="template/lang/all/icons/mail.gif" width="20" height="21" alt="E-Mail senden" title="E-Mail senden"border="0" /></a></td>
	  <td valign="top" style="padding:10PX;">hallo,<br />
ich fange gerade an mit phpwcms zu arbeiten und bin gerade auf eurer Seite gelandet. Sie hilft auf jedem Fall weiter. Danke und weiter so.</td>
	  </tr>
  
</table>

   

  


		
</div>
</div><br />
<strong>URL:<a href="deutsche_version.phtml?id=102,54,1,1,1,12" target="_blank">deutsche_version.phtml?id=102,54,1,1,1,12</a></strong>
</body>
</html>