<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<!--
	phpwcms | free open source content management system
	created by Oliver Georgi (oliver at phpwcms dot de) and licensed under GNU/GPL.
	phpwcms is copyright 2003-2006 of Oliver Georgi. Extensions are copyright of\
	their respective owners. Visit project page for details: http://www.phpwcms.org/
//-->
<title>phpwcms documentation | Gästebuch</title>
  <meta http-equiv="content-type" content="text/html; charset=iso-8859-1" />
  <meta http-equiv="content-style-type" content="text/css" />
  <script src="template/inc_js/frontend.js" type="text/javascript"></script>
  <style type="text/css" media="all">
  /* <![CDATA[ */
    body {
      margin: 0;
      padding-top: 0;
      padding-bottom: 0;
      padding-left: 0;
      padding-right: 0;

      background-color: #FFFFFF;
      color: #000000;
    }
    a, a:link, a:active, a:visited, a:hover { color: #FF9900; }
    a:visited { color: #FF9900; }
    a:active { color: #FF9900; }
  /* ]]> */
  </style>
  <style type="text/css">
  /* <![CDATA[ */
    @import url("template/inc_css/frontend.css");
    @import url("template/inc_css/nlu_navi1_docu.css");
  /* ]]> */
  </style>
<script src="http://www.google-analytics.com/urchin.js" type="text/javascript">
</script>
<script type="text/javascript">
_uacct = "UA-361662-1";
urchinTracker();
</script>
<META NAME="Title" CONTENT="Die phpWCMS Dokumentation">
<meta name="author" content="Oliver Frohnert">
<meta name="Publisher" content="Oliver Frohnert">
<meta name="Copyright" content="Oliver Frohnert">
<meta name="keywords" content="frohnert,documentation, dokumentation, phpwcms, cms, opensource, open source">
<meta name="description" content="Das Dokumentations Projekt für das Open Source CMS phpWCMS">
<meta name="Audience" content="Alle">
<meta name="Content-language" content="DE">
<META NAME="robots"      CONTENT="index,follow">
<META NAME="expires" CONTENT="0">
<meta name="revisit-after" content="7 days">
<meta name="resource-type" content="document">
<meta name="distribution" content="Global">
<meta name="generator" content="PHPWCMS">
<META name="verify-v1" content="1ZpxZ7AZsjm7PxjqXQVus0eiUYqOsp5URTJn9q4KNz8=" />
  <!--[if lt IE 7]>
  <style type="text/css">
    body { behavior: url("template/inc_css/specific/csshover2.htc"); }
    img { behavior: url("template/inc_css/specific/pngbehavior.htc"); }
  </style>
  <![endif]-->
</head>
<body>
<table border="0" cellspacing="0" cellpadding="0" width="760" bgcolor="#ffffff" class="maintable" align="center">
<tr>
<td colspan="2" style="height:60px;"  bgcolor="#ffffff"><a name="top"></a><table width="760" height="135" border="0" cellpadding="0" cellspacing="0">
  <tr valign="top">
    <td width="1334" height="122" colspan="6"><IMG src="/template/lang/de/header.jpg" alt="" border="0">
</td>
  </tr>
  <tr>
	<td height="27" background="template/lang/all/top_menu.jpg"><table width="570" border="0" align="left" cellpadding="0" cellspacing="0">
      <tr>
        <td align="center" width="254"><a href="deutsche_version.phtml"><img src="picture/flags/de.gif" width="16" height="10" hspace="10" border="0"  alt="Deutsche Version" title="Deutsche Version"></a>
<a href="english_version.phtml"><img src="picture/flags/gb.gif" width="16" height="10" hspace="10" border="0"  alt="English Version" title="English Version"></a></td>
        <td valign="middle"><div align="center"><a href="replacement_tags_de.phtml"><img src="content/gt/8c10fcb16c44a7b9c26a5a932c5e4ae9.png" alt="Replacement Tags" title="Replacement Tags" width="115" height="13" border="0" /></a></div></td>
        <td width="30" valign="middle"><div align="center"><img src="template/lang/all/sep.gif" width="5" height="5" border="0"></div></td>
        <td valign="middle"><div align="center"><a href="content_parts_de.phtml"><img src="content/gt/02725c45a346fbf433a4c83e02d8dc5a.png" alt="Content Parts" title="Content Parts" width="94" height="13" border="0" /></a></div></td>
        <td width="30" valign="middle"><div align="center"><img src="template/lang/all/sep.gif" width="5" height="5" border="0"></div></td>
        <td valign="middle"><div align="center"><a href="links_de.phtml"><img src="content/gt/2c41bfb28d6dd3d4bbc8bb7688fd62ee.png" alt="Links" title="Links" width="36" height="13" border="0" /></a></div></td>
        <td width="30" valign="middle"><div align="center"><img src="template/lang/all/sep.gif" width="5 " height="5" border="0"></div></td>
        <td valign="middle"><div align="center"><a href="impressum.phtml"><img src="content/gt/d7380cf01602233e53be03b55123cf90.png" alt="Impressum" title="Impressum" width="64" height="13" border="0" /></a></div></td>
     </tr>
    </table>    </td>
  </tr>
</table>
</td>
</tr>
<tr>
<td valign="top" width="185" background="img/menu.gif"><table width="180" border="0" cellpadding="0" cellspacing="0">
  <tr>
    <td width="180" height="20">&nbsp;</td>
  </tr>
  <tr>
    <td style="padding-left: 1px;"><div class="nlu_navi1_docu">
<ul>
	<li class="sub_no"><a href="news_de.phtml">News</a></li>
	<li class="sub_no"><a href="inst_de.phtml">Installation &amp; Upgrade</a></li>
	<li class="sub_no"><a href="die_docu.phtml">Die Docu</a></li>
	<li class="sub_no"><a href="add_on.phtml">Add Ons</a></li>
	<li class="sub_no"><a href="fehlermeldungen.phtml">Fehlermeldungen</a></li>
	<li class="sub_no"><a href="suche.phtml">Suche</a></li>
	<li class="sub_ul active"><a href="kontakt.phtml">Kontakt</a>
	<ul>
		<li class="sub_no"><a href="impressum.phtml">Impressum</a></li>
		<li class="sub_no active"><a href="gaestebuch.phtml">Gästebuch</a></li>
	</ul>
	</li>
	<li class="sub_no"><a href="faq_de.phtml">FAQ</a></li>
</ul>
</div></td>
  </tr>
   <tr>
    <td style="padding:10px; color:#000000;">
<img src="picture/seperate.gif" border="0" alt="" /><br /><br />
<img src="content/gt/4ed113c59a3746cabc12bacb98382a26.png" alt="Letzte Finale Version:" title="Letzte Finale Version:" width="149" height="13" border="0" /><br /><br />
<img src="content/gt/8da415b6626786310c726135c1d9ce1a.png" alt="phpwcms 1.3.0" title="phpwcms 1.3.0" width="83" height="13" border="0" /><br />
<img src="content/gt/bec27e6d56965cbe357a54097865c5f0.png" alt="Vö: 07.03.2007" title="Vö: 07.03.2007" width="89" height="13" border="0" /><br /><br />
<a href="http://www.phpwcms.de/forum/viewtopic.php?t=14006"><img src="content/gt/17ec582052b0d3ac3eddfbb9e5ff97f1.png" alt="weiter..." title="weiter..." width="52" height="13" border="0" /></a><br /><br />
<img src="picture/seperate.gif" border="0" alt="" /><br /><br />
</TD>
  </tr>
  <tr>
    <td align="center"><span><script language='JavaScript' type='text/javascript'><!--
/* openads=./externals/ads bannerid=12 zoneid=0 source= */
if (typeof phpAds_adg == 'undefined') {
	document.write('<scr'+'ipt language="JavaScript" type="text/javascript" src="./externals/ads/adg.js"></scr'+'ipt>');
}
//--></script><script type="text/javascript"><!--
google_ad_client = "pub-5747379735451868";
google_ad_width = 120;
google_ad_height = 240;
google_ad_format = "120x240_as_rimg";
google_cpa_choice = "CAAQwdqWhAIaCA7_S2iOQTQoKOPC93M";
google_ad_channel = "";
//--></script>
<script type="text/javascript" src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script></span><div id="beacon_12" style="position: absolute; left: 0px; top: 0px; visibility: hidden;"><img src='./externals/ads/adlog.php?bannerid=12&amp;clientid=15&amp;zoneid=0&amp;source=&amp;block=0&amp;capping=0&amp;cb=266c6ec2d76ead1965e841779028beaa' width='0' height='0' alt='' style='width: 0px; height: 0px;'></div><br />WERBUNG<br /><br /><img src="picture/seperate.gif" border="0" alt="" /><P>
</td>
  </tr>
<tr>
    <td height="20">&nbsp;</td>
  </tr>
  <tr>
    <td align="center"></td>
  </tr>
  <tr>
    <td align="center" height="20">&nbsp</td>
  </tr>
</table>


</body>
</html>
</td>
<td valign="top" width="555" bgcolor="#ffffff" class="maincontent"><img src="img/leer.gif" border="0" width="10" height="1" alt="" />
<br />
<a href="deutsche_version.phtml">Deutsch</a> <span class="breadcrumb_spacer">&gt;</span> <a href="kontakt.phtml">Kontakt</a> <span class="breadcrumb_spacer">&gt;</span> Gästebuch
<br />
<HR>
<br />
<a name="jump54"></a><h1>Gästebuch</h1><h2>Wir würden uns über einen Eintrag  freuen...</h2><div style="margin:25px 0 0 0; padding:0 0 0 0; clear:both;"></div>
  <form name="sign_guestbook" action="deutsche_version.phtml?id=102,54,0,1,1,49" method="post">
<table border="0" align="center" cellpadding="1" cellspacing="0" bgcolor="#F5F5F5" style="margin-bottom:10px;">
  <tr bgcolor="#E1E1E1">
    <td colspan="2"><strong>&nbsp;&nbsp;sign my guestbook</strong> <span style="font-size:10px;color:#CC3300;">(fields
        marked * are obligatory)</span></td>
  </tr>
  <tr bgcolor="#E1E1E1">
    <td colspan="2"><img src="img/leer.gif" width="1" height="1" alt="" /></td>
  </tr>
  
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
  <tr>
    <td align="right" class="v10">email<span style="color:#CC3300;">*</span>:&nbsp;</td>
    <td><input name="guestbook_email" type="text" id="guestbook_email" style="width: 350px" class="v12" value="" size="50" maxlength="250" />&nbsp;</td>
  </tr>
  <tr>
    <td align="right" class="v10">name<span style="color:#CC3300;">*</span>:&nbsp;</td>
    <td><input name="guestbook_name" type="text" id="guestbook_name" style="width: 350px" class="v12" value=""  size="50" maxlength="500" /></td>
  </tr>
  <tr>
    <td align="right" class="v10">website:&nbsp;</td>
    <td><input name="guestbook_url" type="text" id="guestbook_url" style="width: 350px" class="v12" value="" size="50" maxlength="1000" /></td>
  </tr>
  <tr>
    <td align="right" valign="top" class="v10">&nbsp;&nbsp;message:&nbsp;</td>
    <td><textarea name="guestbook_msg" cols="50" rows="6" id="guestbook_msg" class="v12" style="width: 350px"></textarea></td>
  </tr>
  <tr>
    <td align="right" valign="top" class="v10">display:&nbsp;</td>
    <td><input name="guestbook_show" type="radio" value="0" checked>show email<br /><input name="guestbook_show" type="radio" value="1">hide email<br /><input type="radio" name="guestbook_show" value="2">show email as &quot;info at mail dot com&quot;</td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="4" alt="" /></td>
  </tr>
  <tr>
  	<td align="right" class="v10">code<span style="color:#CC3300;">*</span>:&nbsp;</td>
  	<td><table cellpadding="0" cellspacing="0" border="0">
		<tr>
			<td><input name="guestbook_captcha" type="text" id="guestbook_captcha" style="width: 100px" class="v12" value="" size="10" maxlength="10" />&nbsp;&nbsp;</td>
			<td><img src="img/captcha.php?regen=y&amp;1177194590" alt="Captcha" border="0" /></td>
		</tr>
		</table></td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="10" alt="" /></td>
  </tr>
  <tr>
    <td align="right">&nbsp;</td>
    <td><input name="guestbook_send" type="submit" id="guestbook_send" value="sign guestbook" class="v11" /></td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="6" alt="" /></td>
  </tr>
</table>
<input type="hidden" name="4623f253d5f4943c73e8f33fa58870e2" value="27522" /></form> 
<table width="100%"  border="0" cellspacing="0" cellpadding="0" style="margin-top:5px;">
  <tr>
    <td><strong><a href="102.54.0.1.1.0.phtml">&lt;&lt;</a> <a href="102.54.0.1.1.48.phtml">&lt;</a></strong> <a href="102.54.0.1.1.47.phtml">48</a>&nbsp;<a href="102.54.0.1.1.48.phtml">49</a>&nbsp;<strong>50</strong>&nbsp;<a href="102.54.0.1.1.50.phtml">51</a>&nbsp;<a href="102.54.0.1.1.51.phtml">52</a> <strong><a href="102.54.0.1.1.50.phtml">&gt;</a>
        <a href="102.54.0.1.1.54.phtml">&gt;&gt;</a></strong></td>
    <td align="right"><form name="guestbookarchive" id="guestbookarchive" method="post" action="index.php?id=102,54,0,1,1,49"><select name="showarchive" id="showarchive" onchange="document.guestbookarchive.submit();"><option value="">all entries</option>
<option value="2007/04">2007/04</option>
<option value="2007/03">2007/03</option>
<option value="2006/10">2006/10</option>
<option value="2006/03">2006/03</option>
<option value="2006/02">2006/02</option>
<option value="2006/01">2006/01</option>
<option value="2005/12">2005/12</option>
<option value="2005/11">2005/11</option>
<option value="2005/10">2005/10</option>
<option value="2005/09">2005/09</option>
<option value="2005/08">2005/08</option>
<option value="2005/07">2005/07</option>
<option value="2005/06">2005/06</option>
<option value="2005/05">2005/05</option>
<option value="2005/03">2005/03</option>
<option value="2005/02">2005/02</option>
<option value="2005/01">2005/01</option>
<option value="2004/12">2004/12</option>
<option value="2004/11">2004/11</option>
<option value="2004/10">2004/10</option>
<option value="2004/09">2004/09</option>
<option value="2004/08">2004/08</option>
</select><input type="hidden" name="archivedate" value="%Y/%m" />&nbsp;<input name="archivesubmit" class="guestbookArchiveSubmit" type="submit" value="go" /></form>&nbsp;<form name="guestbookjump" id="guestbookjump" method="post" action="index.php?id=102,54,0,1,1,49"><select name="showguestbookpage" id="showpage" onchange="document.guestbookjump.submit();"><option value="1">page
      1</option>
<option value="2">page
      2</option>
<option value="3">page
      3</option>
<option value="4">page
      4</option>
<option value="5">page
      5</option>
<option value="6">page
      6</option>
<option value="7">page
      7</option>
<option value="8">page
      8</option>
<option value="9">page
      9</option>
<option value="10">page
      10</option>
<option value="11">page
      11</option>
<option value="12">page
      12</option>
<option value="13">page
      13</option>
<option value="14">page
      14</option>
<option value="15">page
      15</option>
<option value="16">page
      16</option>
<option value="17">page
      17</option>
<option value="18">page
      18</option>
<option value="19">page
      19</option>
<option value="20">page
      20</option>
<option value="21">page
      21</option>
<option value="22">page
      22</option>
<option value="23">page
      23</option>
<option value="24">page
      24</option>
<option value="25">page
      25</option>
<option value="26">page
      26</option>
<option value="27">page
      27</option>
<option value="28">page
      28</option>
<option value="29">page
      29</option>
<option value="30">page
      30</option>
<option value="31">page
      31</option>
<option value="32">page
      32</option>
<option value="33">page
      33</option>
<option value="34">page
      34</option>
<option value="35">page
      35</option>
<option value="36">page
      36</option>
<option value="37">page
      37</option>
<option value="38">page
      38</option>
<option value="39">page
      39</option>
<option value="40">page
      40</option>
<option value="41">page
      41</option>
<option value="42">page
      42</option>
<option value="43">page
      43</option>
<option value="44">page
      44</option>
<option value="45">page
      45</option>
<option value="46">page
      46</option>
<option value="47">page
      47</option>
<option value="48">page
      48</option>
<option value="49">page
      49</option>
<option value="50" selected="selected">page
      50</option>
<option value="51">page
      51</option>
<option value="52">page
      52</option>
<option value="53">page
      53</option>
<option value="54">page
      54</option>
<option value="55">page
      55</option>
</select>&nbsp;<input name="jumpsubmit" class="guestbookJumpSubmit" type="submit" value="go" /></form></td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
</table>

<table width="100%"  border="0" cellspacing="0" cellpadding="2">
  
  <tr bgcolor="#F5F5F5">
    <td width="99%">491 | 11/05/2005 17:57</td>
  </tr>
  <tr>
    <td colspan="2"><strong>Rene Schoone</strong>  <br />
      Hi Oliver and Team,<br />
<br />
Just read all the documentation, excellent!! I&#039;ve read alot about different cms&#039;s but yours is by far the most user friendly, best documented one i&#039;ve seen. Even I (very limited programmer) could install it and make it all work. I&#039;m hooked!!!! Thanks alot!</td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
  
  <tr bgcolor="#F5F5F5">
    <td width="99%">492 | 31/03/2005 03:29</td>
  </tr>
  <tr>
    <td colspan="2"><a href="mailto:info@stakka.de"><strong>OuZo</strong></a>  info@stakka.de<br />
      WUSAHH, verdammt gutes CMS!<br />
Nachdem ich mich stundenlang mit Googl eherumgeschlagen habe, habe ich dieses CMS endlich gefunden und bin begeistert.<br />
.. oder eher sprachlos ...<br />
Weiter so!<br />
<br />
MfG<br />
OuZo</td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
  
  <tr bgcolor="#F5F5F5">
    <td width="99%">493 | 30/03/2005 21:12</td>
  </tr>
  <tr>
    <td colspan="2"><a href="mailto:ruwg@gmx.de"><strong>Rainer G</strong></a> <a href="http://www.gnuelps.de" target="_blank">visit
      website</a> ruwg@gmx.de<br />
      Ich muss das auch mal loswerden:<br />
Klasse phpWCMS-Dokumentation :-)<br />
<br />
Noch eine Frage:<br />
Mit welcher Software kann man diese virtuellen Programmverpackungen herstellen (so wie auf der Startseite links oben)?</td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
  
  <tr bgcolor="#F5F5F5">
    <td width="99%">494 | 23/02/2005 19:57</td>
  </tr>
  <tr>
    <td colspan="2"><strong>rob</strong> <a href="http://hostfury.net" target="_blank">visit
      website</a> rob at hostfury  dot net<br />
      thank you so much for an excellent backend script! i love it. one of the easiest i have ever used.<br />
<br />
keep up the great work!</td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
  
  <tr bgcolor="#F5F5F5">
    <td width="99%">495 | 22/02/2005 23:13</td>
  </tr>
  <tr>
    <td colspan="2"><strong>Marc</strong> <a href="http://pliester.nl" target="_blank">visit
      website</a> marc at pliester  dot nl<br />
      Wow, Oliver. <br />
This is really great. For smaller CMS sites it´s really perfect and easy to learn. Keep up the good work. I´m very interested how version 2 will work.</td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
  
  <tr bgcolor="#F5F5F5">
    <td width="99%">496 | 22/02/2005 16:08</td>
  </tr>
  <tr>
    <td colspan="2"><strong>hmm Stefan</strong> <a href="http://habichnicht.de" target="_blank">visit
      website</a> stefanrhro at gmx  dot net<br />
      Hey Oli aka Pappnase, cooles Stück hast hier gebaut, mach weiter so. Grüße von der Küste.</td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
  
  <tr bgcolor="#F5F5F5">
    <td width="99%">497 | 09/02/2005 14:39</td>
  </tr>
  <tr>
    <td colspan="2"><strong>Dmitrii</strong>  <br />
      phpWCMS looks nice and promising. Honestly, probably the only CMS that doesn&#039;t look like another phpNuke rip-off<br />
<br />
Keep up the good work!</td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
  
  <tr bgcolor="#F5F5F5">
    <td width="99%">498 | 01/02/2005 20:20</td>
  </tr>
  <tr>
    <td colspan="2"><strong>Max</strong>  <br />
      Auch ich möchte mal ein dickes Lob für phpwcms loslassen. Seit Ende letzten Jahres bin ich hier unterwegs und verfolge immer, was es Neues gibt. <br />
Wer den aktuellen RC mal installieren.<br />
Danke für die Arbeit und Grüße - Max</td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
  
  <tr bgcolor="#F5F5F5">
    <td width="99%">499 | 12/01/2005 11:28</td>
  </tr>
  <tr>
    <td colspan="2"><strong>Charles Coleman</strong>  <br />
      Your site design is impeccable.  Keep up the good work!</td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
  
  <tr bgcolor="#F5F5F5">
    <td width="99%">500 | 07/01/2005 12:31</td>
  </tr>
  <tr>
    <td colspan="2"><strong>Andrusch</strong> <a href="http://analogfotografie.de" target="_blank">visit
      website</a> andreas.broemme at web  dot de<br />
      Hallo, habe diese Seite schon sooft besucht, weil ich immer wissen will, was es neues hier gibt. Außerdem kenne ich den BEtreiber ganz gut. Also erstmal ein dickes fettes Lob an alle Macher dieser Doku-Seite. Das bekommt ihr echt toll hin und ich hoffe, ihr macht weiter so. Von dieser Doku-Seite kann sich manch ein CMS mal was abschneiden. <br />
<br />
ICh freue mich auch endlich auf die VErsion 2 und hoffe - zwinker zu OliG - du hast sie bald online. ICh warte gespannt. <br />
<br />
Greetz from BErlin<br />
<br />
Andrusch</td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
  
</table>

<table width="100%"  border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td colspan="2"><HR></td>
  </tr>
  <tr>
    <td width="50%">Artikel erstellt: 2004/08/16</td>
    <td align="right" width="50%">Letzte Änderung:2007/01/26</td>
  </tr>
  <tr>
    <td colspan="2">&nbsp;</td>
  </tr>
  <tr>
    <td colspan="2" class="comment">Wenn Sie einen Fehler entdecken eine Ergänzung oder Frage haben benutzen Sie bitte folgendes <a href="#" onClick="javascript:window.open('./content/pages/nachricht.htm','frage','width=400, height=250, screenX=440,screenY=200,menubar=no,statusbar=yes,scrollbar=yes,resizable=no');" target="" style="max-width:148px; overflow:hidden;"><u>Formular</u></a>.<br /><br />
Hat Ihnen oder Ihrem Kunden diese Docu weitergeholfen ? Dann würde ich mich freuen wenn Sie das Projekt unterstützen würden. Bitte nutzen Sie dafür diesen <a href="#paypal">PayPal</a> Link. Jeder Betrag ist möglich und hilft der Weiterentwicklung und Aktualisierung dieser Dokumentation.<br />
Diese Seite nutzt die version:</td>
  </tr>
  <tr>

    <td colspan="2"><img src="img/leer.gif" border="0" width="10" height="10" alt="" /></td>
  </tr>
</table>
</td>
</tr>
<tr>
<td colspan="2" style="height:10px;"  bgcolor="#ffffff" class="footer"><table width="100%" height="20" background="img/footer.gif" cellpadding="0" cellspacing="0" border="0">
	<tr><td width="180" align="center" valign="middle">4 User online</td>
	<td>
	<table width="100%"cellpadding="0" cellspacing="0" border="0">
   <tr>
    <td align="center"><a href="javascript:history.back();" target="_top" title="go back"><img src="picture/back_.gif" border="0" alt="Zurueck"><img src="content/gt/13c1f733e9ee7693bf810fd5f035d0b7.png" alt="Zurück" title="Zurück" width="45" height="13" border="0" /></a></td>
	<td align="center"><a href="sitemap_de.phtml"><img src="picture/sitemap_.gif" border="0"  alt="Sitemap"><img src="content/gt/38062c01670c74843cc0b291d94966c6.png" alt="Sitemap" title="Sitemap" width="50" height="13" border="0" /></a></td>
	<td align="center"><a href="102.54.1.1.1.49.phtml" target="_blank"><img src="picture/print_.gif" border="0" alt="Drucken"><img src="content/gt/811a35c6cb2c5555a2f32d85b1bb5deb.png" alt="Drucken" title="Drucken" width="52" height="13" border="0" /></a></td>
	<td align="center"><a href="gaestebuch.phtml"><img src="picture/icon_gaestebuch.gif" border="0" align="top" alt="Gästebuch"><img src="content/gt/1257c79a2b085b5641453b0f6e0fe1fd.png" alt="Gästebuch" title="Gästebuch" width="66" height="13" border="0" /></a></td>
	<td align="center"><a href="#" onclick="BookMark_Page();return false;" title=""><img src="picture/favoriten_.gif" border="0"  alt="Lesezeichen"><img src="content/gt/7ce0fe74ab60b3da559a77c54fb85a80.png" alt="Lesezeichen" title="Lesezeichen" width="78" height="13" border="0" /></a></td>
    </tr>
</table></td>
	</tr>
</table>
<img src="img/leer.gif" border="0" width="760" height="10" alt="" /><br />
<script type="text/javascript"><!--
google_ad_client = "pub-5747379735451868";
google_ad_width = 728;
google_ad_height = 90;
google_ad_format = "728x90_as";
google_ad_type = "text_image";
google_ad_channel ="1196150249";
//--></script>
<script type="text/javascript"
  src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script></td>
</tr>
</table>

</body>
</html>