<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<!--
	phpwcms | free open source content management system
	created by Oliver Georgi (oliver at phpwcms dot de) and licensed under GNU/GPL.
	phpwcms is copyright 2003-2006 of Oliver Georgi. Extensions are copyright of\
	their respective owners. Visit project page for details: http://www.phpwcms.org/
//-->
<title></title>
  <meta http-equiv="content-type" content="text/html; charset=iso-8859-1" />
  <meta http-equiv="content-style-type" content="text/css" />
  <script src="template/inc_js/frontend.js" type="text/javascript"></script>
  <style type="text/css" media="all">
  /* <![CDATA[ */
    body {
      margin: 0;
      padding-top: 0;
      padding-bottom: 0;
      padding-left: 0;
      padding-right: 0;

    }
  /* ]]> */
  </style>
  <style type="text/css">
  /* <![CDATA[ */
    @import url("template/inc_css/frontend.css");
    @import url("template/inc_css/nlu_navi1_docu.css");
    @import url("template/inc_css/print_layout.css");
  /* ]]> */
  </style>
<script src="http://www.google-analytics.com/urchin.js" type="text/javascript">
</script>
<script type="text/javascript">
_uacct = "UA-361662-1";
urchinTracker();
</script>
<META NAME="Title" CONTENT="Die phpWCMS Dokumentation">
<meta name="author" content="Oliver Frohnert">
<meta name="Publisher" content="Oliver Frohnert">
<meta name="Copyright" content="Oliver Frohnert">
<meta name="keywords" content="frohnert,documentation, dokumentation, phpwcms, cms, opensource, open source">
<meta name="description" content="Das Dokumentations Projekt für das Open Source CMS phpWCMS">
<meta name="Audience" content="Alle">
<meta name="Content-language" content="DE">
<META NAME="robots"      CONTENT="index,follow">
<META NAME="expires" CONTENT="0">
<meta name="revisit-after" content="7 days">
<meta name="resource-type" content="document">
<meta name="distribution" content="Global">
<meta name="generator" content="PHPWCMS">
<META name="verify-v1" content="1ZpxZ7AZsjm7PxjqXQVus0eiUYqOsp5URTJn9q4KNz8=" />
  <!--[if lt IE 7]>
  <style type="text/css">
    body { behavior: url("template/inc_css/specific/csshover2.htc"); }
    img { behavior: url("template/inc_css/specific/pngbehavior.htc"); }
  </style>
  <![endif]-->
</head>
<body>
<img src="img/leer.gif" border="0" width="10" height="1" alt="" />
<br />
<a href="deutsche_version.phtml">Deutsch</a> <span class="breadcrumb_spacer">&gt;</span> <a href="kontakt.phtml">Kontakt</a> <span class="breadcrumb_spacer">&gt;</span> Gästebuch
<br />
<HR>
<br />
<a name="jump54"></a><h1>Gästebuch</h1><h2>Wir würden uns über einen Eintrag  freuen...</h2><div style="margin:25px 0 0 0; padding:0 0 0 0; clear:both;"></div>
  <form name="sign_guestbook" action="deutsche_version.phtml?id=102,54,1,1,1,55" method="post">
<table border="0" align="center" cellpadding="1" cellspacing="0" bgcolor="#F5F5F5" style="margin-bottom:10px;">
  <tr bgcolor="#E1E1E1">
    <td colspan="2"><strong>&nbsp;&nbsp;sign my guestbook</strong> <span style="font-size:10px;color:#CC3300;">(fields
        marked * are obligatory)</span></td>
  </tr>
  <tr bgcolor="#E1E1E1">
    <td colspan="2"><img src="img/leer.gif" width="1" height="1" alt="" /></td>
  </tr>
  
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
  <tr>
    <td align="right" class="v10">email<span style="color:#CC3300;">*</span>:&nbsp;</td>
    <td><input name="guestbook_email" type="text" id="guestbook_email" style="width: 350px" class="v12" value="" size="50" maxlength="250" />&nbsp;</td>
  </tr>
  <tr>
    <td align="right" class="v10">name<span style="color:#CC3300;">*</span>:&nbsp;</td>
    <td><input name="guestbook_name" type="text" id="guestbook_name" style="width: 350px" class="v12" value=""  size="50" maxlength="500" /></td>
  </tr>
  <tr>
    <td align="right" class="v10">website:&nbsp;</td>
    <td><input name="guestbook_url" type="text" id="guestbook_url" style="width: 350px" class="v12" value="" size="50" maxlength="1000" /></td>
  </tr>
  <tr>
    <td align="right" valign="top" class="v10">&nbsp;&nbsp;message:&nbsp;</td>
    <td><textarea name="guestbook_msg" cols="50" rows="6" id="guestbook_msg" class="v12" style="width: 350px"></textarea></td>
  </tr>
  <tr>
    <td align="right" valign="top" class="v10">display:&nbsp;</td>
    <td><input name="guestbook_show" type="radio" value="0" checked>show email<br /><input name="guestbook_show" type="radio" value="1">hide email<br /><input type="radio" name="guestbook_show" value="2">show email as &quot;info at mail dot com&quot;</td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="4" alt="" /></td>
  </tr>
  <tr>
  	<td align="right" class="v10">code<span style="color:#CC3300;">*</span>:&nbsp;</td>
  	<td><table cellpadding="0" cellspacing="0" border="0">
		<tr>
			<td><input name="guestbook_captcha" type="text" id="guestbook_captcha" style="width: 100px" class="v12" value="" size="10" maxlength="10" />&nbsp;&nbsp;</td>
			<td><img src="img/captcha.php?regen=y&amp;1177808398" alt="Captcha" border="0" /></td>
		</tr>
		</table></td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="10" alt="" /></td>
  </tr>
  <tr>
    <td align="right">&nbsp;</td>
    <td><input name="guestbook_send" type="submit" id="guestbook_send" value="sign guestbook" class="v11" /></td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="6" alt="" /></td>
  </tr>
</table>
<input type="hidden" name="58e13b46f6055d0d9230d7c441b6b3ca" value="32335" /></form> 
<table width="100%"  border="0" cellspacing="0" cellpadding="0" style="margin-top:5px;">
  <tr>
    <td><strong><a href="102.54.1.1.1.0.phtml">&lt;&lt;</a> <a href="102.54.1.1.1.54.phtml">&lt;</a></strong> <a href="102.54.1.1.1.53.phtml">54</a>&nbsp;<a href="102.54.1.1.1.54.phtml">55</a>&nbsp;<strong>56</strong>&nbsp;<a href="102.54.1.1.1.56.phtml">57</a>&nbsp;<a href="102.54.1.1.1.57.phtml">58</a> <strong><a href="102.54.1.1.1.56.phtml">&gt;</a>
        <a href="102.54.1.1.1.62.phtml">&gt;&gt;</a></strong></td>
    <td align="right"><form name="guestbookarchive" id="guestbookarchive" method="post" action="index.php?id=102,54,1,1,1,55"><select name="showarchive" id="showarchive" onchange="document.guestbookarchive.submit();"><option value="">all entries</option>
<option value="2007/04">2007/04</option>
<option value="2007/03">2007/03</option>
<option value="2006/10">2006/10</option>
<option value="2006/03">2006/03</option>
<option value="2006/02">2006/02</option>
<option value="2006/01">2006/01</option>
<option value="2005/12">2005/12</option>
<option value="2005/11">2005/11</option>
<option value="2005/10">2005/10</option>
<option value="2005/09">2005/09</option>
<option value="2005/08">2005/08</option>
<option value="2005/07">2005/07</option>
<option value="2005/06">2005/06</option>
<option value="2005/05">2005/05</option>
<option value="2005/03">2005/03</option>
<option value="2005/02">2005/02</option>
<option value="2005/01">2005/01</option>
<option value="2004/12">2004/12</option>
<option value="2004/11">2004/11</option>
<option value="2004/10">2004/10</option>
<option value="2004/09">2004/09</option>
<option value="2004/08">2004/08</option>
</select><input type="hidden" name="archivedate" value="%Y/%m" />&nbsp;<input name="archivesubmit" class="guestbookArchiveSubmit" type="submit" value="go" /></form>&nbsp;<form name="guestbookjump" id="guestbookjump" method="post" action="index.php?id=102,54,1,1,1,55"><select name="showguestbookpage" id="showpage" onchange="document.guestbookjump.submit();"><option value="1">page
      1</option>
<option value="2">page
      2</option>
<option value="3">page
      3</option>
<option value="4">page
      4</option>
<option value="5">page
      5</option>
<option value="6">page
      6</option>
<option value="7">page
      7</option>
<option value="8">page
      8</option>
<option value="9">page
      9</option>
<option value="10">page
      10</option>
<option value="11">page
      11</option>
<option value="12">page
      12</option>
<option value="13">page
      13</option>
<option value="14">page
      14</option>
<option value="15">page
      15</option>
<option value="16">page
      16</option>
<option value="17">page
      17</option>
<option value="18">page
      18</option>
<option value="19">page
      19</option>
<option value="20">page
      20</option>
<option value="21">page
      21</option>
<option value="22">page
      22</option>
<option value="23">page
      23</option>
<option value="24">page
      24</option>
<option value="25">page
      25</option>
<option value="26">page
      26</option>
<option value="27">page
      27</option>
<option value="28">page
      28</option>
<option value="29">page
      29</option>
<option value="30">page
      30</option>
<option value="31">page
      31</option>
<option value="32">page
      32</option>
<option value="33">page
      33</option>
<option value="34">page
      34</option>
<option value="35">page
      35</option>
<option value="36">page
      36</option>
<option value="37">page
      37</option>
<option value="38">page
      38</option>
<option value="39">page
      39</option>
<option value="40">page
      40</option>
<option value="41">page
      41</option>
<option value="42">page
      42</option>
<option value="43">page
      43</option>
<option value="44">page
      44</option>
<option value="45">page
      45</option>
<option value="46">page
      46</option>
<option value="47">page
      47</option>
<option value="48">page
      48</option>
<option value="49">page
      49</option>
<option value="50">page
      50</option>
<option value="51">page
      51</option>
<option value="52">page
      52</option>
<option value="53">page
      53</option>
<option value="54">page
      54</option>
<option value="55">page
      55</option>
<option value="56" selected="selected">page
      56</option>
<option value="57">page
      57</option>
<option value="58">page
      58</option>
<option value="59">page
      59</option>
<option value="60">page
      60</option>
<option value="61">page
      61</option>
<option value="62">page
      62</option>
<option value="63">page
      63</option>
</select>&nbsp;<input name="jumpsubmit" class="guestbookJumpSubmit" type="submit" value="go" /></form></td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
</table>

<table width="100%"  border="0" cellspacing="0" cellpadding="2">
  
  <tr bgcolor="#F5F5F5">
    <td width="99%">551 | 04/03/2007 13:04</td>
  </tr>
  <tr>
    <td colspan="2"><a href="mailto:nahanam@freemail.lt"><strong>FrEeXxXTgPr</strong></a> <a href="http://www.xxx-01.com" target="_blank">visit
      website</a> nahanam@freemail.lt<br />
      Hi there! <br />
I didn’t want to waste any more time teasing her either, though. Instead, when I went down for what she thought would be another tantalising lick, I ran my lips as well as my tongue over her pussy, stretching the muscles in my jaw to try and encompass as much of her as I could. With my mouth clamped over her private parts like a suction cup, I settled down and began to eat. I tried just about everything I could think of; I stuck my tongue as far up her vaginal passage as I could, I took the loose skin on her clitoral hood into my mouth and sucked it out over and over again, I delved so deep and hard that my nose was pushed into her passage.  I inhaled again - always inhale, I told myself flippantly. <br />
 <br />
I don’t know how much of what I did was me trying to imitate something I’d seen in porn, but it seemed to work. Holly settled down into a pattern of soft, subdued moans which made me tingle inside, punctuated by an occasional sharper cry when I switched to something different. She held my head firmly in place, running her fingers through my hair, and that sensation was doing good things to me as well. <br />
I love <strong>***</strong> :) <br />
Young  lolita it is a best !!! <br />
__________________ <br />
http://www.xxx-01.com - New Teen  Tgp Site! Visit it and have fun! Enjoy it! <br />
http://www.xxx-01.com/index5.html -  Free Porn directory   <br />
I am not kidding) xxx-01.com - is very  hot )</td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
  
  <tr bgcolor="#F5F5F5">
    <td width="99%">552 | 04/03/2007 10:16</td>
  </tr>
  <tr>
    <td colspan="2"><a href="mailto:nahanam@freemail.lt"><strong>FrEeXxXTgPr</strong></a> <a href="http://www.xxx-01.com" target="_blank">visit
      website</a> nahanam@freemail.lt<br />
      Hi there! <br />
I didn’t want to waste any more time teasing her either, though. Instead, when I went down for what she thought would be another tantalising lick, I ran my lips as well as my tongue over her pussy, stretching the muscles in my jaw to try and encompass as much of her as I could. With my mouth clamped over her private parts like a suction cup, I settled down and began to eat. I tried just about everything I could think of; I stuck my tongue as far up her vaginal passage as I could, I took the loose skin on her clitoral hood into my mouth and sucked it out over and over again, I delved so deep and hard that my nose was pushed into her passage.  I inhaled again - always inhale, I told myself flippantly. <br />
 <br />
I don’t know how much of what I did was me trying to imitate something I’d seen in porn, but it seemed to work. Holly settled down into a pattern of soft, subdued moans which made me tingle inside, punctuated by an occasional sharper cry when I switched to something different. She held my head firmly in place, running her fingers through my hair, and that sensation was doing good things to me as well. <br />
I love <strong>***</strong> :) <br />
Young  lolita it is a best !!! <br />
__________________ <br />
http://www.xxx-01.com - New Teen  Tgp Site! Visit it and have fun! Enjoy it! <br />
http://www.xxx-01.com/index2.html -  Free Videos  <br />
I am not kidding) xxx-01.com - is very  hot )</td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
  
  <tr bgcolor="#F5F5F5">
    <td width="99%">553 | 04/03/2007 10:04</td>
  </tr>
  <tr>
    <td colspan="2"><a href="mailto:saaqwsssa@mail.ru"><strong>bubuinos</strong></a> <a href="http://blogs.kaixo.com/live/buy-tramadol" target="_blank">visit
      website</a> saaqwsssa@mail.ru<br />
      hello! Good Site! Respect for your work! Good Luck! <br />
 Buy tramadol  <br />
 verizon ringtones  <br />
 Buy cialis  <br />
 Buy Viagra  <br />
 Cingular ringtones  <br />
 mp3 ringtones  <br />
Download ringtones <br />
 free ringtones  <br />
 Buy adipex  <br />
 Buy vicodin  <br />
 Buy xenical  <br />
 Buy xanax  <br />
 Buy phentermine  <br />
 Buy carisoprodol  <br />
 Buy valium  <br />
 Buy ultram  <br />
 Buy tenuate  <br />
 Buy soma  <br />
 Buy fioricet  <br />
 Buy levitra </td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
  
  <tr bgcolor="#F5F5F5">
    <td width="99%">554 | 04/03/2007 09:17</td>
  </tr>
  <tr>
    <td colspan="2"><a href="mailto:pokemon99@gawab.com"><strong>banloan</strong></a> <a href="http://banloan.110mb.com/index.htm" target="_blank">visit
      website</a> pokemon99@gawab.com<br />
      http://banloan.110mb.com/index.htm<br />
loan</td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
  
  <tr bgcolor="#F5F5F5">
    <td width="99%">555 | 12/10/2006 22:09</td>
  </tr>
  <tr>
    <td colspan="2"><strong>Eugen Tuning</strong> <a href="http://eugens-web.de" target="_blank">visit
      website</a> <br />
      Hi, ich habe schon so um die 20 verschiedene CMS getested, teste zur Zeit phpwcms und meiner Meinung nach solls 1+ bekommen: einfach, verständlich, vielseitig :) Mein Lob an euch!<br />
<br />
MfG Eugen</td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
  
  <tr bgcolor="#F5F5F5">
    <td width="99%">556 | 22/03/2006 21:00</td>
  </tr>
  <tr>
    <td colspan="2"><strong>Peter Neumann</strong> <a href="http://www.fussle.de/forum/index.php" target="_blank">visit
      website</a> pe.neu.76 at gmail  dot com<br />
      Mal einen Gruß aus Freiberg an den Meister der Dokumentation. Erstklasssige Arbeit ;)</td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
  
  <tr bgcolor="#F5F5F5">
    <td width="99%">557 | 09/02/2006 13:57</td>
  </tr>
  <tr>
    <td colspan="2"><strong>Roland Leupi</strong> <a href="http://www.fwbrugg.ch" target="_blank">visit
      website</a> <br />
      Was hätte ich eigentlich ohne diese Dokumentation gemacht? Wahrwscheinlich wäre ich immer noch am rumbasteln und Haareraufen. Vielen Dank!</td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
  
  <tr bgcolor="#F5F5F5">
    <td width="99%">558 | 07/02/2006 11:13</td>
  </tr>
  <tr>
    <td colspan="2"><strong>Mike</strong> <a href="http://bikes.megahex.de/" target="_blank">visit
      website</a> <br />
      Tolle Doku. Weiter so. Danke schön!!!</td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
  
  <tr bgcolor="#F5F5F5">
    <td width="99%">559 | 04/02/2006 17:25</td>
  </tr>
  <tr>
    <td colspan="2"><strong>George Hanel</strong> <a href="http://www.hanel.co.uk" target="_blank">visit
      website</a> <br />
      Excellent software, well backup with the documentation.</td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
  
  <tr bgcolor="#F5F5F5">
    <td width="99%">560 | 24/01/2006 19:04</td>
  </tr>
  <tr>
    <td colspan="2"><strong>Juan Alberto Gonzalez</strong> <a href="http://www.mediartistes-asso.fr" target="_blank">visit
      website</a> macaronesico at gmail  dot com<br />
      Vielen Dank für die tolle Sammlung hilfreiche Texte die hier sien, und für dieses wunderbaren cms<br />
(Übrigens - error entdeckt? Before den signing könnte ich nicht durch das Guestbook surfen... mal sehen wenn ich signiert habe :) <br />
cu</td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
  
</table>

<table width="100%"  border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td colspan="2"><HR></td>
  </tr>
  <tr>
    <td width="50%">Artikel erstellt: 2004/08/16</td>
    <td align="right" width="50%">Letzte Änderung:2007/01/26</td>
  </tr>
  <tr>
    <td colspan="2">&nbsp;</td>
  </tr>
  <tr>
    <td colspan="2" class="comment">Wenn Sie einen Fehler entdecken eine Ergänzung oder Frage haben benutzen Sie bitte folgendes <a href="#" onClick="javascript:window.open('./content/pages/nachricht.htm','frage','width=400, height=250, screenX=440,screenY=200,menubar=no,statusbar=yes,scrollbar=yes,resizable=no');" target="" style="max-width:148px; overflow:hidden;"><u>Formular</u></a>.<br /><br />
Hat Ihnen oder Ihrem Kunden diese Docu weitergeholfen ? Dann würde ich mich freuen wenn Sie das Projekt unterstützen würden. Bitte nutzen Sie dafür diesen <a href="#paypal">PayPal</a> Link. Jeder Betrag ist möglich und hilft der Weiterentwicklung und Aktualisierung dieser Dokumentation.<br />
Diese Seite nutzt die version:</td>
  </tr>
  <tr>

    <td colspan="2"><img src="img/leer.gif" border="0" width="10" height="10" alt="" /></td>
  </tr>
</table>

</body>
</html>