<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<!--
	phpwcms | free open source content management system
	created by Oliver Georgi (oliver at phpwcms dot de) and licensed under GNU/GPL.
	phpwcms is copyright 2003-2006 of Oliver Georgi. Extensions are copyright of\
	their respective owners. Visit project page for details: http://www.phpwcms.org/
//-->
<title></title>
  <meta http-equiv="content-type" content="text/html; charset=iso-8859-1" />
  <meta http-equiv="content-style-type" content="text/css" />
  <script src="template/inc_js/frontend.js" type="text/javascript"></script>
  <style type="text/css" media="all">
  /* <![CDATA[ */
    body {
      margin: 0;
      padding-top: 0;
      padding-bottom: 0;
      padding-left: 0;
      padding-right: 0;

    }
  /* ]]> */
  </style>
  <style type="text/css">
  /* <![CDATA[ */
    @import url("template/inc_css/frontend.css");
    @import url("template/inc_css/nlu_navi1_docu.css");
    @import url("template/inc_css/print_layout.css");
  /* ]]> */
  </style>


<META NAME="Title" CONTENT="Die phpWCMS Dokumentation">
<meta name="author" content="Oliver Frohnert">
<meta name="Publisher" content="Oliver Frohnert">
<meta name="Copyright" content="Oliver Frohnert">
<meta name="keywords" content="frohnert,documentation, dokumentation, phpwcms, cms, opensource, open source">
<meta name="description" content="Das Dokumentations Projekt für das Open Source CMS phpWCMS">
<meta name="Audience" content="Alle">
<meta name="Content-language" content="DE">
<META NAME="robots"      CONTENT="index,follow">
<META NAME="expires" CONTENT="0">
<meta name="revisit-after" content="7 days">
<meta name="resource-type" content="document">
<meta name="distribution" content="Global">
<meta name="generator" content="PHPWCMS">

  <!--[if lt IE 7]>
  <style type="text/css">
    body { behavior: url("template/inc_css/specific/csshover2.htc"); }
    img { behavior: url("template/inc_css/specific/pngbehavior.htc"); }
  </style>
  <![endif]-->
</head>
<body>
<img src="img/leer.gif" border="0" width="10" height="1" alt="" />
<br />
<a href="deutsche_version.phtml">Deutsch</a> <span class="breadcrumb_spacer">&gt;</span> <a href="kontakt.phtml">Kontakt</a> <span class="breadcrumb_spacer">&gt;</span> Gästebuch
<br />
<HR>
<br />
<a name="jump54"></a><h1>Gästebuch</h1><h2>Wir würden uns über einen Eintrag  freuen...</h2><div style="margin:25px 0 0 0; padding:0 0 0 0; clear:both;"></div>
   
<table width="100%"  border="0" cellspacing="0" cellpadding="0" style="margin-top:5px;">
  <tr>
    <td><strong><a href="102.54.1.1.1.0.phtml">&lt;&lt;</a> <a href="102.54.1.1.1.58.phtml">&lt;</a></strong> <a href="102.54.1.1.1.57.phtml">58</a>&nbsp;<a href="102.54.1.1.1.58.phtml">59</a>&nbsp;<strong>60</strong>&nbsp;<a href="102.54.1.1.1.60.phtml">61</a>&nbsp;<a href="102.54.1.1.1.61.phtml">62</a> <strong><a href="102.54.1.1.1.60.phtml">&gt;</a>
        <a href="102.54.1.1.1.62.phtml">&gt;&gt;</a></strong></td>
    <td align="right">&nbsp;<form name="guestbookjump" id="guestbookjump" method="post" action="index.php?id=102,54,1,1,1,59"><select name="showguestbookpage" id="showpage" onchange="document.guestbookjump.submit();"><option value="1">page
      1</option>
<option value="2">page
      2</option>
<option value="3">page
      3</option>
<option value="4">page
      4</option>
<option value="5">page
      5</option>
<option value="6">page
      6</option>
<option value="7">page
      7</option>
<option value="8">page
      8</option>
<option value="9">page
      9</option>
<option value="10">page
      10</option>
<option value="11">page
      11</option>
<option value="12">page
      12</option>
<option value="13">page
      13</option>
<option value="14">page
      14</option>
<option value="15">page
      15</option>
<option value="16">page
      16</option>
<option value="17">page
      17</option>
<option value="18">page
      18</option>
<option value="19">page
      19</option>
<option value="20">page
      20</option>
<option value="21">page
      21</option>
<option value="22">page
      22</option>
<option value="23">page
      23</option>
<option value="24">page
      24</option>
<option value="25">page
      25</option>
<option value="26">page
      26</option>
<option value="27">page
      27</option>
<option value="28">page
      28</option>
<option value="29">page
      29</option>
<option value="30">page
      30</option>
<option value="31">page
      31</option>
<option value="32">page
      32</option>
<option value="33">page
      33</option>
<option value="34">page
      34</option>
<option value="35">page
      35</option>
<option value="36">page
      36</option>
<option value="37">page
      37</option>
<option value="38">page
      38</option>
<option value="39">page
      39</option>
<option value="40">page
      40</option>
<option value="41">page
      41</option>
<option value="42">page
      42</option>
<option value="43">page
      43</option>
<option value="44">page
      44</option>
<option value="45">page
      45</option>
<option value="46">page
      46</option>
<option value="47">page
      47</option>
<option value="48">page
      48</option>
<option value="49">page
      49</option>
<option value="50">page
      50</option>
<option value="51">page
      51</option>
<option value="52">page
      52</option>
<option value="53">page
      53</option>
<option value="54">page
      54</option>
<option value="55">page
      55</option>
<option value="56">page
      56</option>
<option value="57">page
      57</option>
<option value="58">page
      58</option>
<option value="59">page
      59</option>
<option value="60" selected="selected">page
      60</option>
<option value="61">page
      61</option>
<option value="62">page
      62</option>
<option value="63">page
      63</option>
</select>&nbsp;<input name="jumpsubmit" class="guestbookJumpSubmit" type="submit" value="go" /></form></td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
</table>

<table width="100%"  border="0" cellspacing="0" cellpadding="2">
  
  <tr bgcolor="#F5F5F5">
    <td width="99%">591 | 23/12/2004 11:28</td>
  </tr>
  <tr>
    <td colspan="2"><a href="mailto:Tommy.kurtze@nilgen.de"><strong>Tommy</strong></a>  Tommy.kurtze@nilgen.de<br />
      Kann mir jemad beim Einsatz von phpadsnew Adserver helfen? Versuche zwei Banner zu verknüpfen (TandemAds) und der Wahnsinn ist momentan näher als die Aussicht auf Erfolg...:-))<br />
Wäre seeehr net...<br />
<br />
<span style="color:#00CC00;">hallo bitte postet keine support anfragen im gästebuch. wendet euch bitte ans forum!<br />
<br />
hello please post no support questions into the guestbook. please use for that the forum<br />
<br />
cheers / gruß Oliver &quot;Pappnase&quot; Frohnert</span></td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
  
  <tr bgcolor="#F5F5F5">
    <td width="99%">592 | 22/12/2004 19:40</td>
  </tr>
  <tr>
    <td colspan="2"><a href="mailto:revmtthws@aol.com"><strong>Darryl Matthews</strong></a> <a href="http://www.pastordarryl.com" target="_blank">visit
      website</a> revmtthws@aol.com<br />
      What a great resource you have developed here.  I am looking to revamp my website and would like to focus more on content that layout (not that layout doesn&#039;t matter but I would like to get a style and then be done with the layout).  Your website gives me some insight into what can be done with WCMS.  How do you make the decision between going with WCMS and using tools like Dreamweaver for site creation and maintenance?<br />
Keep up the good work and hope to see more content here in the future.<br />
<br />
<span style="color:#00CC00;">hello thanks for the compliments, you will see more content. also template and layout things.<br />
<br />
cheers Oliver &quot;Pappnase&quot; Frohnert</span></td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
  
  <tr bgcolor="#F5F5F5">
    <td width="99%">593 | 07/12/2004 17:25</td>
  </tr>
  <tr>
    <td colspan="2"><strong>Yves Malouin</strong> <a href="http://www.malouin.ws" target="_blank">visit
      website</a> <br />
      You guys, Oliver and all, are doing a great job and contribution here for PhpWCMS. Thanks a bunch for it, and for all of us! Keep Up the Great Work ;)<br />
<br />
Cheers,<br />
<br />
Yves</td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
  
  <tr bgcolor="#F5F5F5">
    <td width="99%">594 | 30/11/2004 00:49</td>
  </tr>
  <tr>
    <td colspan="2"><strong>sebastian</strong> <a href="http://www.derechopenalonline.com/index.php" target="_blank">visit
      website</a> <br />
      no puedo hacer andar el guestbook<br />
<span style="color:#00CC00;">hello, please write in english or german. Cheers Pappnase</span></td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
  
  <tr bgcolor="#F5F5F5">
    <td width="99%">595 | 28/11/2004 22:12</td>
  </tr>
  <tr>
    <td colspan="2"><a href="mailto:remo.boeni@bluewin.ch"><strong>Remo</strong></a>  remo.boeni@bluewin.ch<br />
      Der absolute Hammer !!!!<br />
<br />
Dank dieser Seite ist es vermutlich vielen phpwcms Benutzern esrt möglich etwas aus deren Seiten rauszuholen !!!!<br />
<br />
Ein ganz ganz dickes Lob....macht weiter so.......<br />
<br />
Ich hoffe diese Docu wird immer und immer weiter entwickelt und ausgebaut, da noch einige Erklärungen fehlen, die noch wichtig sein könnten!!<br />
<br />
Liebe Grüsse aus der Schweiz<br />
<br />
<span style="color:#00CC00;">Danke für das Lob, klar machen wir weiter. Gruß Oliver &quot;Pappnase&quot; Frohnert</span></td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
  
  <tr bgcolor="#F5F5F5">
    <td width="99%">596 | 25/11/2004 17:34</td>
  </tr>
  <tr>
    <td colspan="2"><a href="mailto:info@cgi-freepool.de"><strong>Heinz Walter</strong></a> <a href="http://www.cgi-freepool.de" target="_blank">visit
      website</a> info@cgi-freepool.de<br />
      Hallo,<br />
<br />
gratulation die dieser Seite.<br />
<br />
Habe lange keine Seite gesehen, bei der man so detalisierte Infos bekommt.<br />
<br />
Gruß Heinz</td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
  
  <tr bgcolor="#F5F5F5">
    <td width="99%">597 | 25/11/2004 15:51</td>
  </tr>
  <tr>
    <td colspan="2"><strong>Alex Kink</strong>  alexkink at linux  dot ca<br />
      Love the new design :) Keep up the great work</td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
  
  <tr bgcolor="#F5F5F5">
    <td width="99%">598 | 25/11/2004 14:01</td>
  </tr>
  <tr>
    <td colspan="2"><strong>Andi &quot;brans&quot; Brenner</strong> <a href="http://www.mobifiles.de" target="_blank">visit
      website</a> powerpac at gmx  dot li<br />
      Hi Oliver und Team,<br />
<br />
echt wahnsinn, jetzt ist die Seite hier nicht nur vom Inhalt her der reinste Überflieger, sondern hat zusätzlich noch ihre letzte Schwäche, das Design auf einen zeitgemässen, hohen Standard transformiert. Bin echt beeindruckt, würde gerne wieder Zeit investieren, wenn ich welche hätte ;-)<br />
<br />
Ihr seid auf dem richtigen Weg! Diese Seite steigt von Woche zu Woche auf der kurzen Leiter von sehr gut zu perfekt immer eine der sehr kleinen Stufen weiter.<br />
<br />
grüsse aus der Schweiz</td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
  
  <tr bgcolor="#F5F5F5">
    <td width="99%">599 | 25/11/2004 10:06</td>
  </tr>
  <tr>
    <td colspan="2"><strong>H.J. Munzinger</strong>  <br />
      Wow, sehr schönes, neues Design. Macht grad nen ganz anderen, übrigens sehr angenehmen Einrduck!<br />
<br />
cyber<br />
mediaDesigner</td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
  
  <tr bgcolor="#F5F5F5">
    <td width="99%">600 | 24/11/2004 15:42</td>
  </tr>
  <tr>
    <td colspan="2"><strong>Mikko Levanen aka &quot;Lumimies&quot;</strong>  <br />
      Hey! New design is nice! (mean this website...)</td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
  
</table>

<table width="100%"  border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td colspan="2"><HR></td>
  </tr>
  <tr>
    <td width="50%">Artikel erstellt: 2004/08/16</td>
    <td align="right" width="50%">Letzte Änderung:2007/01/26</td>
  </tr>
  <tr>
    <td colspan="2">&nbsp;</td>
  </tr>
  <tr>
    <td colspan="2" class="comment">Wenn Sie einen Fehler entdecken eine Ergänzung oder Frage haben benutzen Sie bitte folgendes <a href="#" onClick="javascript:window.open('./content/pages/nachricht.htm','frage','width=400, height=250, screenX=440,screenY=200,menubar=no,statusbar=yes,scrollbar=yes,resizable=no');" target="" style="max-width:148px; overflow:hidden;"><u>Formular</u></a>.<br /><br />
Hat Ihnen oder Ihrem Kunden diese Docu weitergeholfen ? Dann würde ich mich freuen wenn Sie das Projekt unterstützen würden. Bitte nutzen Sie dafür diesen <a href="#paypal">PayPal</a> Link. Jeder Betrag ist möglich und hilft der Weiterentwicklung und Aktualisierung dieser Dokumentation.<br />
Diese Seite nutzt die version:</td>
  </tr>
  <tr>

    <td colspan="2"><img src="img/leer.gif" border="0" width="10" height="10" alt="" /></td>
  </tr>
</table>

</body>
</html>