<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<!--
	phpwcms | free open source content management system
	created by Oliver Georgi (oliver at phpwcms dot de) and licensed under GNU/GPL.
	phpwcms is copyright 2003-2006 of Oliver Georgi. Extensions are copyright of\
	their respective owners. Visit project page for details: http://www.phpwcms.org/
//-->
<title></title>
  <meta http-equiv="content-type" content="text/html; charset=iso-8859-1" />
  <meta http-equiv="content-style-type" content="text/css" />
  <script src="template/inc_js/frontend.js" type="text/javascript"></script>
  <style type="text/css" media="all">
  /* <![CDATA[ */
    body {
      margin: 0;
      padding-top: 0;
      padding-bottom: 0;
      padding-left: 0;
      padding-right: 0;

    }
  /* ]]> */
  </style>
  <style type="text/css">
  /* <![CDATA[ */
    @import url("template/inc_css/frontend.css");
    @import url("template/inc_css/nlu_navi1_docu.css");
    @import url("template/inc_css/print_layout.css");
  /* ]]> */
  </style>


<META NAME="Title" CONTENT="Die phpWCMS Dokumentation">
<meta name="author" content="Oliver Frohnert">
<meta name="Publisher" content="Oliver Frohnert">
<meta name="Copyright" content="Oliver Frohnert">
<meta name="keywords" content="frohnert,documentation, dokumentation, phpwcms, cms, opensource, open source">
<meta name="description" content="Das Dokumentations Projekt für das Open Source CMS phpWCMS">
<meta name="Audience" content="Alle">
<meta name="Content-language" content="DE">
<META NAME="robots"      CONTENT="index,follow">
<META NAME="expires" CONTENT="0">
<meta name="revisit-after" content="7 days">
<meta name="resource-type" content="document">
<meta name="distribution" content="Global">
<meta name="generator" content="PHPWCMS">

  <!--[if lt IE 7]>
  <style type="text/css">
    body { behavior: url("template/inc_css/specific/csshover2.htc"); }
    img { behavior: url("template/inc_css/specific/pngbehavior.htc"); }
  </style>
  <![endif]-->
</head>
<body>
<img src="img/leer.gif" border="0" width="10" height="1" alt="" />
<br />
<a href="deutsche_version.phtml">Deutsch</a> <span class="breadcrumb_spacer">&gt;</span> <a href="kontakt.phtml">Kontakt</a> <span class="breadcrumb_spacer">&gt;</span> Gästebuch
<br />
<HR>
<br />
<a name="jump54"></a><h1>Gästebuch</h1><h2>Wir würden uns über einen Eintrag  freuen...</h2><div style="margin:25px 0 0 0; padding:0 0 0 0; clear:both;"></div>
   
<table width="100%"  border="0" cellspacing="0" cellpadding="0" style="margin-top:5px;">
  <tr>
    <td><strong><a href="102.54.1.1.1.0.phtml">&lt;&lt;</a> <a href="102.54.1.1.1.53.phtml">&lt;</a></strong> <a href="102.54.1.1.1.52.phtml">53</a>&nbsp;<a href="102.54.1.1.1.53.phtml">54</a>&nbsp;<strong>55</strong>&nbsp;<a href="102.54.1.1.1.55.phtml">56</a>&nbsp;<a href="102.54.1.1.1.56.phtml">57</a> <strong><a href="102.54.1.1.1.55.phtml">&gt;</a>
        <a href="102.54.1.1.1.59.phtml">&gt;&gt;</a></strong></td>
    <td align="right">&nbsp;</td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
</table>

<table width="100%"  border="0" cellspacing="0" cellpadding="2">
  
  <tr bgcolor="#F5F5F5">
    <td width="99%">541 | 18/05/2005 09:43</td>
  </tr>
  <tr>
    <td colspan="2"><strong>dastel</strong>  dastel at gmx  dot net<br />
      hallo jungs, super hilfreiche seite, aber manchmal führt auch eure tolle seite nicht immer zum gewünschten ergebniss. <br />
<br />
<br />
<span style="color:#00CC00;">EDIT by PAPPNASE: Hallo Das hier ist das GB nicht das Forum Bitte immr daran denken!</span></td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
  
  <tr bgcolor="#F5F5F5">
    <td width="99%">542 | 11/05/2005 17:57</td>
  </tr>
  <tr>
    <td colspan="2"><strong>Rene Schoone</strong>  <br />
      Hi Oliver and Team,<br />
<br />
Just read all the documentation, excellent!! I&#039;ve read alot about different cms&#039;s but yours is by far the most user friendly, best documented one i&#039;ve seen. Even I (very limited programmer) could install it and make it all work. I&#039;m hooked!!!! Thanks alot!</td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
  
  <tr bgcolor="#F5F5F5">
    <td width="99%">543 | 31/03/2005 03:29</td>
  </tr>
  <tr>
    <td colspan="2"><a href="mailto:info@stakka.de"><strong>OuZo</strong></a>  info@stakka.de<br />
      WUSAHH, verdammt gutes CMS!<br />
Nachdem ich mich stundenlang mit Googl eherumgeschlagen habe, habe ich dieses CMS endlich gefunden und bin begeistert.<br />
.. oder eher sprachlos ...<br />
Weiter so!<br />
<br />
MfG<br />
OuZo</td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
  
  <tr bgcolor="#F5F5F5">
    <td width="99%">544 | 30/03/2005 21:12</td>
  </tr>
  <tr>
    <td colspan="2"><a href="mailto:ruwg@gmx.de"><strong>Rainer G</strong></a> <a href="http://www.gnuelps.de" target="_blank">visit
      website</a> ruwg@gmx.de<br />
      Ich muss das auch mal loswerden:<br />
Klasse phpWCMS-Dokumentation :-)<br />
<br />
Noch eine Frage:<br />
Mit welcher Software kann man diese virtuellen Programmverpackungen herstellen (so wie auf der Startseite links oben)?</td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
  
  <tr bgcolor="#F5F5F5">
    <td width="99%">545 | 23/02/2005 19:57</td>
  </tr>
  <tr>
    <td colspan="2"><strong>rob</strong> <a href="http://hostfury.net" target="_blank">visit
      website</a> rob at hostfury  dot net<br />
      thank you so much for an excellent backend script! i love it. one of the easiest i have ever used.<br />
<br />
keep up the great work!</td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
  
  <tr bgcolor="#F5F5F5">
    <td width="99%">546 | 22/02/2005 23:13</td>
  </tr>
  <tr>
    <td colspan="2"><strong>Marc</strong> <a href="http://pliester.nl" target="_blank">visit
      website</a> marc at pliester  dot nl<br />
      Wow, Oliver. <br />
This is really great. For smaller CMS sites it´s really perfect and easy to learn. Keep up the good work. I´m very interested how version 2 will work.</td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
  
  <tr bgcolor="#F5F5F5">
    <td width="99%">547 | 22/02/2005 16:08</td>
  </tr>
  <tr>
    <td colspan="2"><strong>hmm Stefan</strong> <a href="http://habichnicht.de" target="_blank">visit
      website</a> stefanrhro at gmx  dot net<br />
      Hey Oli aka Pappnase, cooles Stück hast hier gebaut, mach weiter so. Grüße von der Küste.</td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
  
  <tr bgcolor="#F5F5F5">
    <td width="99%">548 | 09/02/2005 14:39</td>
  </tr>
  <tr>
    <td colspan="2"><strong>Dmitrii</strong>  <br />
      phpWCMS looks nice and promising. Honestly, probably the only CMS that doesn&#039;t look like another phpNuke rip-off<br />
<br />
Keep up the good work!</td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
  
  <tr bgcolor="#F5F5F5">
    <td width="99%">549 | 01/02/2005 20:20</td>
  </tr>
  <tr>
    <td colspan="2"><strong>Max</strong>  <br />
      Auch ich möchte mal ein dickes Lob für phpwcms loslassen. Seit Ende letzten Jahres bin ich hier unterwegs und verfolge immer, was es Neues gibt. <br />
Wer den aktuellen RC mal installieren.<br />
Danke für die Arbeit und Grüße - Max</td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
  
  <tr bgcolor="#F5F5F5">
    <td width="99%">550 | 12/01/2005 11:28</td>
  </tr>
  <tr>
    <td colspan="2"><strong>Charles Coleman</strong>  <br />
      Your site design is impeccable.  Keep up the good work!</td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
  
</table>

<table width="100%"  border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td colspan="2"><HR></td>
  </tr>
  <tr>
    <td width="50%">Artikel erstellt: 2004/08/16</td>
    <td align="right" width="50%">Letzte Änderung:2007/01/26</td>
  </tr>
  <tr>
    <td colspan="2">&nbsp;</td>
  </tr>
  <tr>
    <td colspan="2" class="comment">Wenn Sie einen Fehler entdecken eine Ergänzung oder Frage haben benutzen Sie bitte folgendes <a href="#" onClick="javascript:window.open('./content/pages/nachricht.htm','frage','width=400, height=250, screenX=440,screenY=200,menubar=no,statusbar=yes,scrollbar=yes,resizable=no');" target="" style="max-width:148px; overflow:hidden;"><u>Formular</u></a>.<br /><br />
Hat Ihnen oder Ihrem Kunden diese Docu weitergeholfen ? Dann würde ich mich freuen wenn Sie das Projekt unterstützen würden. Bitte nutzen Sie dafür diesen <a href="#paypal">PayPal</a> Link. Jeder Betrag ist möglich und hilft der Weiterentwicklung und Aktualisierung dieser Dokumentation.<br />
Diese Seite nutzt die version:</td>
  </tr>
  <tr>

    <td colspan="2"><img src="img/leer.gif" border="0" width="10" height="10" alt="" /></td>
  </tr>
</table>

</body>
</html>