<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<!--
	phpwcms | free open source content management system
	created by Oliver Georgi (oliver at phpwcms dot de) and licensed under GNU/GPL.
	phpwcms is copyright 2003-2007 of Oliver Georgi. Extensions are copyright of
	their respective owners. Visit project page for details: http://www.phpwcms.org/
//-->
<title>phpwcms-docu for  phpwcms :: web based content management system | Gästebuch | Gästebuch</title>
  <meta http-equiv="content-type" content="text/html; charset=iso-8859-1" />
  <meta http-equiv="content-style-type" content="text/css" />
  <script src="template/inc_js/frontend.js" type="text/javascript"></script>
  <style type="text/css">
  <!-- 
    @import url("template/inc_css/mpl_docu.css");
    @import url("template/inc_css/mpl_frontend.css");
    @import url("template/inc_css/mpl_menu.css");
    @import url("template/inc_css/mpl_objects.css");
  //-->
  </style>
<script type="text/javascript" language="javascript">
<!--
function MM_jumpMenu(targ,selObj,restore){ //v3.0
  eval(targ+".location='"+selObj.options[selObj.selectedIndex].value+"'");
  if (restore) selObj.selectedIndex=0;
}

function MM_findObj(n, d) { //v4.01
  var p,i,x;  if(!d) d=document; if((p=n.indexOf("?"))>0&&parent.frames.length) {
    d=parent.frames[n.substring(p+1)].document; n=n.substring(0,p);}
  if(!(x=d[n])&&d.all) x=d.all[n]; for (i=0;!x&&i<d.forms.length;i++) x=d.forms[i][n];
  for(i=0;!x&&d.layers&&i<d.layers.length;i++) x=MM_findObj(n,d.layers[i].document);
  if(!x && d.getElementById) x=d.getElementById(n); return x;
}

function MM_jumpMenuGo(selName,targ,restore){ //v3.0
  var selObj = MM_findObj(selName); if (selObj) MM_jumpMenu(targ,selObj,restore);
}
//-->
</script>
<meta name="Title" content="Die phpWCMS Dokumentation" />
<meta name="author" content="Oliver Frohnert, Mario Perez Leal" />
<meta name="Publisher" content="Oliver Frohnert, Mario Perez Leal, creacion" />
<meta name="Copyright" content="Oliver Frohnert, Mario Perez Leal, creacion" />
<meta name="keywords" content="frohnert, perez leal, creacion, documentation, dokumentation, phpwcms, cms, opensource, open source, docu" />
<meta name="description" content="Das Dokumentations Projekt für das Open Source CMS phpWCMS" />
<meta name="Audience" content="Alle" />
<meta name="Content-language" content="DE" />
<meta name="robots" content="index,follow" />
<meta name="expires" content="0" />
<meta name="revisit-after" content="7 days" />
<meta name="resource-type" content="document" />
<meta name="distribution" content="Global" />
<meta name="generator" content="PHPWCMS" />

  <!--[if lt IE 7]>
  <style type="text/css">
    body { behavior: url("template/inc_css/specific/csshover2.htc"); }
    img { behavior: url("template/inc_css/specific/pngbehavior.htc"); }
  </style>
  <![endif]-->
</head>
<body id="myid_102">
<div id="container"><a name="top" id="top"></a>


	<div id="head">
		
	<div id="mainnavi">
		<div class="fleft"><a href="deutsche_version.phtml">Startseite</a> | <a href="news_de.phtml">News</a> | <a href="die_docu.phtml">Die Docu</a> | <a href="Nuetzliche_Links_und_Tools.phtml">Links &amp; Tools</a> | <a href="downloads.phtml">Downloads</a> | <span style="text-decoration:none;font-weight:bold;"><a href="kontakt.phtml">Kontakt</a></span> | <a href="faq_de.phtml">FAQ</a> | <a href="http://forum.phpwcms.org/" target="_blank">Forum</a> | <a href="howto_de.phtml">HowTo</a></div>				
		<div class="sys">Dienstag, 15. Oktober 2013<img src="img/leer.gif" border="0" width="5" height="1" alt="" />|<img src="img/leer.gif" border="0" width="5" height="1" alt="" />4 User online<img src="img/leer.gif" border="0" width="10" height="1" alt="" />
		<a href="deutsche_version.phtml" title="Deutsche Version"><img src="picture/../template/lang/all/flag_de.gif" border="0" alt="" /></a>
		<a href="english_version.phtml"  title="English version"><img src="picture/../template/lang/all/flag_en.gif" border="0" alt="" /></a>
		</div>
	</div>
	
	<a href="./" title="phpwcms-docu Startseite aufrufen" class="homelink">
	<span>&raquo; Zur phpwcms-docu Startseite</span></a>
	<h2>phpwcms-docu - Die Dokumentation f&uuml;r f&uuml;r das CMS phpWCMS</h2>
	<p>phpwcms-docu ist eine Art Kompass, der Ihnen die M&ouml;glichkeiten von phpWcms aufzeigt und Sie erfolgreich, ohne gro&szlig;e Umwege, zu Ihrer fertigen Web-Anwendung f&uuml;hren soll.
	</p>
	</div>

	
	<div id="left">
	<div class="leftnav" style="margin-top:24px;">
	
<div id="ul_div_71">
<ul>
	<li class="sub_no"><a href="impressum.phtml">Impressum</a></li>
	<li class="sub_no"><a href="nutzung.phtml">Nutzungsbedingungen</a></li>
	<li class="sub_no"><a href="linkus.phtml">Link us</a></li>
	<li class="sub_no"><a href="newsletter_de.phtml">Newsletter</a></li>
	<li class="sub_no active"><a href="gaestebuch.phtml">Gästebuch</a></li>
</ul>
</div>

		
		
		

	</div> 
	</div> 
	  
	<div id="right">
		<div style="margin-top:24px;">			
		<form action="#" method="post" name="searchFE" onsubmit="s=document.getElementById('customSearchInput');if(s.value=='Suchen')return false;">
			<table width="100%" border="0" cellpadding="0" cellspacing="0">
			<tr>
					<td><input type="text" name="search_input_field" size="20" maxlength="200" id="customSearchInput" class="customSearchInput" value="" onfocus="if(this.value=='Suchen')this.value='';" onblur="if(this.value=='')this.value='Suchen';" /></td>
					<td><input type="image" name="search_go" onfocus="this.blur();" title="Suchen" src="/template/lang/all/submit.gif" /></td>
				</tr>
			</table>
			</form>
			
			      <script type="text/javascript" language="javascript">
			  <!-- 
			        document.getElementById("customSearchInput").value="Suchen";
			  //-->
			      </script>
				  
			<!-- <p style="margin-top:10px;">Schriftgrad &auml;ndern: <a href="[FontSize-]"><img src="template/lang/all/icons/reduce.gif" width="18" height="17" alt="" title="Verkleinern" border="0" /></a>
			<a href="[FontSize+]"><img src="template/lang/all/icons/extend.gif" width="18" height="17" alt="" title="Vergr&ouml;&szlig;ern" border="0" /></a>
			</p> -->
			
	
<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div>


<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div>
<!-- <a href="http://validator.w3.org/check?uri=http%3A%2F%2Fwww.phpwcms-docu.de%2Findex.php%3Fdeutsche_version" title="W3C Standard XHTML" target="_blank"><img src="picture/w3c/w3c_xhtml.gif" border="0" alt="" /></a>
<a href="http://jigsaw.w3.org/css-validator/validator?uri=http://www.phpwcms-docu.de" title="W3C Standard CSS" target="_blank"><img src="picture/w3c/w3c_css.gif" border="0" alt="" /></a><br />			
<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div> -->
<h3>Partnersites</h3>






<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div>

<div style="margin-top:10px; margin-bottom:15px;"></div>


<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div>
</div>

	</div> 
	
	<div id="content">
	<div id="bread">Sie sind hier: <a href="deutsche_version.phtml">Deutsch</a> <span class="breadcrumb_spacer">&gt;</span> <a href="kontakt.phtml">Kontakt</a> <span class="breadcrumb_spacer">&gt;</span> Gästebuch</div>
		
		<a name="jump54"></a><!-- 
custom article template to split up the view / entry area for the guestbook
template by oliver@phpwcms-docu.de
===========================================================================
//-->
<div>
<h1 style="margin:0 0 5px 0;">Gästebuch</h1>
<h3 style="margin:0 0 5px 0;">Wir würden uns über einen Eintrag  freuen...</h3>
</div>

<div class="cpPagination">

	<a href="aid=54-2.phtml" class="cpPaginationNext">Ins Gästebuch eintragen &raquo;</a>
</div>

<div style="margin:25px 0 0 0;padding:0;" class="spaceBeforeCP"></div>
  
  
  
  

<table width="100%"  border="0" cellspacing="0" cellpadding="0" style="margin-top:5px;">
  <tr>
    <td><strong><a href="102.54.0.1.1.0.phtml">&laquo;&laquo;</a> <a href="102.54.0.1.1.0.phtml">&laquo;</a></strong> <a href="102.54.0.1.1.0.phtml">1</a>&nbsp;<strong>2</strong>&nbsp;<a href="102.54.0.1.1.2.phtml">3</a>&nbsp;<a href="102.54.0.1.1.3.phtml">4</a>&nbsp;<a href="102.54.0.1.1.4.phtml">5</a> <strong><a href="102.54.0.1.1.2.phtml">&raquo;</a>
        <a href="102.54.0.1.1.25.phtml">&raquo;&raquo;</a></strong></td>
    <td align="right"></td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
</table>


	  <table width="100%" border="0" cellspacing="0" cellpadding="0">
  
	  <tr class="tbb">
	  <td width="130" class="tbh"> &nbsp;11 </td>
	  <td align="right" class="tbh">Vom 15.06.2013 um 15:03 Uhr&nbsp;</td>
	  </tr>
	  <tr class="tbr">
	  <td class="tbl" valign="top">
	  <strong>Hans</strong><br /><br />
	  <a href="http://ero.mag.su" target="_blank"><img src="template/lang/all/icons/home.gif" width="20" height="21" alt="Website besuchen" title="Website besuchen"border="0" /></a><br />
	  <a href="mailto:asdfg@hotmail.com"><img src="template/lang/all/icons/mail.gif" width="20" height="21" alt="E-Mail senden" title="E-Mail senden"border="0" /></a></td>
	  <td valign="top" style="padding:10PX;">Hello. Good work!</td>
	  </tr>
  
	  <tr class="tbb">
	  <td width="130" class="tbh"> &nbsp;12 </td>
	  <td align="right" class="tbh">Vom 30.05.2013 um 12:42 Uhr&nbsp;</td>
	  </tr>
	  <tr class="tbr">
	  <td class="tbl" valign="top">
	  <strong>LordTommon</strong><br /><br />
	  <a href="http://viagratimoonmaster.com" target="_blank"><img src="template/lang/all/icons/home.gif" width="20" height="21" alt="Website besuchen" title="Website besuchen"border="0" /></a><br />
	  <a href="mailto:lordtommon@hotmail.com"><img src="template/lang/all/icons/mail.gif" width="20" height="21" alt="E-Mail senden" title="E-Mail senden"border="0" /></a></td>
	  <td valign="top" style="padding:10PX;">http://viagratimoonmaster.com <br />
tamoxifen</td>
	  </tr>
  
	  <tr class="tbb">
	  <td width="130" class="tbh"> &nbsp;13 </td>
	  <td align="right" class="tbh">Vom 28.05.2013 um 17:07 Uhr&nbsp;</td>
	  </tr>
	  <tr class="tbr">
	  <td class="tbl" valign="top">
	  <strong>Jana</strong><br /><br />
	  <a href="http://www.erlebnissegutscheine.com" target="_blank"><img src="template/lang/all/icons/home.gif" width="20" height="21" alt="Website besuchen" title="Website besuchen"border="0" /></a><br />
	  <a href="mailto:janaj@gmail.com"><img src="template/lang/all/icons/mail.gif" width="20" height="21" alt="E-Mail senden" title="E-Mail senden"border="0" /></a></td>
	  <td valign="top" style="padding:10PX;">Danke für die tolle Seite und Grüße aus Kiel.</td>
	  </tr>
  
	  <tr class="tbb">
	  <td width="130" class="tbh"> &nbsp;14 </td>
	  <td align="right" class="tbh">Vom 02.05.2013 um 11:13 Uhr&nbsp;</td>
	  </tr>
	  <tr class="tbr">
	  <td class="tbl" valign="top">
	  <strong>Bernd</strong><br /><br />
	  <a href="http://www.allround-talk-forum.com" target="_blank"><img src="template/lang/all/icons/home.gif" width="20" height="21" alt="Website besuchen" title="Website besuchen"border="0" /></a><br />
	  </td>
	  <td valign="top" style="padding:10PX;">Spitzenmäßige Seite. Tolle Links und interessante Tools. Grüße zum Donnerstag. Bernd.</td>
	  </tr>
  
	  <tr class="tbb">
	  <td width="130" class="tbh"> &nbsp;15 </td>
	  <td align="right" class="tbh">Vom 22.04.2013 um 21:09 Uhr&nbsp;</td>
	  </tr>
	  <tr class="tbr">
	  <td class="tbl" valign="top">
	  <strong>Susan</strong><br /><br />
	  <a href="http://www.faehrenguenstig.com" target="_blank"><img src="template/lang/all/icons/home.gif" width="20" height="21" alt="Website besuchen" title="Website besuchen"border="0" /></a><br />
	  <a href="mailto:susanm@gmx.de"><img src="template/lang/all/icons/mail.gif" width="20" height="21" alt="E-Mail senden" title="E-Mail senden"border="0" /></a></td>
	  <td valign="top" style="padding:10PX;">Wir wünschen einen schönen Montag. Vielen Dank für die tolle Seite.</td>
	  </tr>
  
	  <tr class="tbb">
	  <td width="130" class="tbh"> &nbsp;16 </td>
	  <td align="right" class="tbh">Vom 18.04.2013 um 07:22 Uhr&nbsp;</td>
	  </tr>
	  <tr class="tbr">
	  <td class="tbl" valign="top">
	  <strong>Ronny</strong><br /><br />
	  <a href="http://www.liebeskummerueberwinden.com/" target="_blank"><img src="template/lang/all/icons/home.gif" width="20" height="21" alt="Website besuchen" title="Website besuchen"border="0" /></a><br />
	  </td>
	  <td valign="top" style="padding:10PX;">Nach genau der Seite habe ich lange gesucht, haben das System nämlich bei uns im Einsatz. Wurde von meinem Vorgänger eingespielt allerdings ohne Hinweise auf diese offizielle Dokumentation. Bin daher glücklich, endlich hier gelandet zu sein!</td>
	  </tr>
  
	  <tr class="tbb">
	  <td width="130" class="tbh"> &nbsp;17 </td>
	  <td align="right" class="tbh">Vom 17.04.2013 um 18:04 Uhr&nbsp;</td>
	  </tr>
	  <tr class="tbr">
	  <td class="tbl" valign="top">
	  <strong>Lisa</strong><br /><br />
	  <a href="http://www.laminareifen.de/" target="_blank"><img src="template/lang/all/icons/home.gif" width="20" height="21" alt="Website besuchen" title="Website besuchen"border="0" /></a><br />
	  </td>
	  <td valign="top" style="padding:10PX;">Interessante Seite. PHP ist schon was tolles!</td>
	  </tr>
  
	  <tr class="tbb">
	  <td width="130" class="tbh"> &nbsp;18 </td>
	  <td align="right" class="tbh">Vom 08.04.2013 um 15:02 Uhr&nbsp;</td>
	  </tr>
	  <tr class="tbr">
	  <td class="tbl" valign="top">
	  <strong>Jana</strong><br /><br />
	  <a href="http://www.faehrentickets.com" target="_blank"><img src="template/lang/all/icons/home.gif" width="20" height="21" alt="Website besuchen" title="Website besuchen"border="0" /></a><br />
	  <a href="mailto:janaf@aol.com"><img src="template/lang/all/icons/mail.gif" width="20" height="21" alt="E-Mail senden" title="E-Mail senden"border="0" /></a></td>
	  <td valign="top" style="padding:10PX;">Ein Bekannter hat mir ihre Seite empfohlen. Ich finde sie sehr gelungen und wünsche einen tollen Sonntag.</td>
	  </tr>
  
	  <tr class="tbb">
	  <td width="130" class="tbh"> &nbsp;19 </td>
	  <td align="right" class="tbh">Vom 04.04.2013 um 09:39 Uhr&nbsp;</td>
	  </tr>
	  <tr class="tbr">
	  <td class="tbl" valign="top">
	  <strong>Rene</strong><br /><br />
	  <a href="http://www.weberfolgsstrategien.de" target="_blank"><img src="template/lang/all/icons/home.gif" width="20" height="21" alt="Website besuchen" title="Website besuchen"border="0" /></a><br />
	  </td>
	  <td valign="top" style="padding:10PX;">Sehr gute Webseite, gefällt mir sehr gut.</td>
	  </tr>
  
	  <tr class="tbb">
	  <td width="130" class="tbh"> &nbsp;20 </td>
	  <td align="right" class="tbh">Vom 01.04.2013 um 21:25 Uhr&nbsp;</td>
	  </tr>
	  <tr class="tbr">
	  <td class="tbl" valign="top">
	  <strong>dsd</strong><br /><br />
	  <a href="http://www.snoups.de" target="_blank"><img src="template/lang/all/icons/home.gif" width="20" height="21" alt="Website besuchen" title="Website besuchen"border="0" /></a><br />
	  </td>
	  <td valign="top" style="padding:10PX;">Tolle Website! :)</td>
	  </tr>
  
</table>

		 
		
		<br /><br />
		<div class="sub">
			
		</div>
				
	</div>
	
<div id="footer"><br /><br />
<br />





	<table width="97%" border="0" cellspacing="0" cellpadding="0">
		<tr>
			<td valign="bottom">	
			&copy; phpwcms-docu 2004-2013
			<img src="img/leer.gif" border="0" width="10" height="0" alt="" /><a href="impressum.phtml" class="phpwcmsIntLink"><img src="template/lang/all/icons/imprint.gif" width="9" height="15" alt="Impressum" title="Impressum" border="0" /></a>&nbsp; 
			<a href="sitemap_de.phtml" class="phpwcmsIntLink"><img src="template/lang/all/icons/sitemap.gif" width="19" height="15" alt="Sitemap" title="Sitemap" border="0" /></a>&nbsp; 
			<a href="gaestebuch.phtml" class="phpwcmsIntLink"><img src="template/lang/all/icons/gbook.gif" width="20" height="16" alt="Ins G&auml;stebuch eintragen" title="Ins G&auml;stebuch eintragen" border="0" /></a>&nbsp; 
			<a href="#" onclick="BookMark_Page();return false;" title="" class="phpwcmsBookmarkLink"><img src="template/lang/all/icons/favo.gif" width="12" height="15" alt="Seite als Bookmark speichern" title="Seite als Bookmark speichern" border="0" /></a>&nbsp; 
			     
			</td>
			<td valign="bottom" style="padding-right:25px;">
			
			
			
			</td>		
			<td width="150">
			</td>
		</tr>
	</table>
</div><br/>

</div>
</body>
</html>