<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<!--
	phpwcms | free open source content management system
	created by Oliver Georgi (oliver at phpwcms dot de) and licensed under GNU/GPL.
	phpwcms is copyright 2003-2007 of Oliver Georgi. Extensions are copyright of
	their respective owners. Visit project page for details: http://www.phpwcms.org/
//-->
<title>Guestbook | Guestbook</title>
  <meta http-equiv="content-type" content="text/html; charset=iso-8859-1" />
  <meta http-equiv="content-style-type" content="text/css" />
  <script src="template/inc_js/frontend.js" type="text/javascript"></script>
  <style type="text/css" media="all">
  <!-- 
    body {
      margin: 0;
      padding-top: 0;
      padding-bottom: 0;
      padding-left: 0;
      padding-right: 0;

    }
  //-->
  </style>
  <style type="text/css">
  <!-- 
    @import url("template/inc_css/print_layout.css");
  //-->
  </style>
<meta name="Title" content="The phpWCMS Documentation" />
<meta name="author" content="Oliver Frohnert, Mario Perez Leal" />
<meta name="Publisher" content="Oliver Frohnert, Mario Perez Leal, creacion" />
<meta name="Copyright" content="Oliver Frohnert, Mario Perez Leal, creacion" />
<meta name="keywords" content="frohnert, perez leal, creacion, documentation, dokumentation, phpwcms, cms, opensource, open source, docu" />
<meta name="description" content="A Documentation Project for the  Open Source CMS phpWCMS" />
<meta name="Audience" content="Alle" />
<meta name="Content-language" content="EN" />
<meta name="robots"      content="index,follow" />
<meta name="expires" content="0" />
<meta name="revisit-after" content="7 days" />
<meta name="resource-type" content="document" />
<meta name="distribution" content="Global" />
<meta name="generator" content="PHPWCMS" />
<meta name="verify-v1" content="1ZpxZ7AZsjm7PxjqXQVus0eiUYqOsp5URTJn9q4KNz8=" />
  <!--[if lt IE 7]>
  <style type="text/css">
    body { behavior: url("template/inc_css/specific/csshover2.htc"); }
    img { behavior: url("template/inc_css/specific/pngbehavior.htc"); }
  </style>
  <![endif]-->
</head>
<body id="myid_105">


<!--

	this is the default PDF template
	use it to add additional header or
	footer information or whatever you 
	like to be rendered 

//-->

<div style="width:50%; border:1px solid #0f57a6; padding:10px; margin:10px;">
<p style="margin-bottom:20px;"><img src="./template/img/printlogo.gif" width="255" height="91" alt="" border="0" /></p>

<div id="container"><a name="top" id="top"></a>

		<a name="jump60"></a><!-- 
custom article template to split up the view / entry area for the guestbook
template by oliver@phpwcms-docu.de
===========================================================================
//-->
<div>
<h1 style="margin:0 0 5px 0;">Guestbook</h1>

</div>

<div style="margin:25px 0 0 0;padding:0;" class="spaceBeforeCP"></div>
  <form name="sign_guestbook" action="index.php?id=105,60,1,1,1,0" method="post">  <input type="hidden" name="c09fbacce0ed8e40906c0e4248fd9c07" value="282976" /></form> 
<table width="100%"  border="0" cellspacing="0" cellpadding="0" style="margin-top:5px;">
  <tr>
    <td><strong>&laquo;&laquo; &laquo;</strong> <strong>1</strong>&nbsp;<a href="105.60.1.1.1.1.phtml">2</a>&nbsp;<a href="105.60.1.1.1.2.phtml">3</a>&nbsp;<a href="105.60.1.1.1.3.phtml">4</a>&nbsp;<a href="105.60.1.1.1.4.phtml">5</a> <strong><a href="105.60.1.1.1.1.phtml">&raquo;</a>
        <a href="105.60.1.1.1.27.phtml">&raquo;&raquo;</a></strong></td>
    <td align="right"></td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
</table>

<table width="100%"  border="0" cellspacing="0" cellpadding="2">
  
  
  	  <tr class="tbb">
	  <td width="130" class="tbh"> &nbsp;1 </td>
	  <td align="right" class="tbh">Wrote 2010/07/05 at 22:28&nbsp;</td>
	  </tr>
	  <tr class="tbr">
	  <td class="tbl" valign="top">
	  <strong>Moti</strong><br /><br />
	  <a href="http://www.einfachbilliger.com" target="_blank"><img src="template/lang/all/icons/home.gif" width="20" height="21" alt="visit website" border="0" /></a><br />
	  </td>
	  <td valign="top" style="padding:10PX;">Haben dieses System lange eingesetzt, waren sehr zufrieden! Eines der ersten CMS, die wirklich was taugten.</td>
	  </tr>

  
  	  <tr class="tbb">
	  <td width="130" class="tbh"> &nbsp;2 </td>
	  <td align="right" class="tbh">Wrote 2010/06/25 at 01:19&nbsp;</td>
	  </tr>
	  <tr class="tbr">
	  <td class="tbl" valign="top">
	  <strong>Birgit</strong><br /><br />
	  <a href="http://www.tattooentfernung-tattoo-entfernung.info" target="_blank"><img src="template/lang/all/icons/home.gif" width="20" height="21" alt="visit website" border="0" /></a><br />
	  </td>
	  <td valign="top" style="padding:10PX;">Hallo,<br />
ich bin durch Zufall beim surfen über deine Seite gestolpert<br />
und ich fand sie so toll das ich hier meine Fußspuren verewigen möchte.<br />
<br />
Lieben Gruß<br />
Birgit</td>
	  </tr>

  
  	  <tr class="tbb">
	  <td width="130" class="tbh"> &nbsp;3 </td>
	  <td align="right" class="tbh">Wrote 2010/06/16 at 11:26&nbsp;</td>
	  </tr>
	  <tr class="tbr">
	  <td class="tbl" valign="top">
	  <strong>aqmos</strong><br /><br />
	  <a href="http://www.aqmos.com" target="_blank"><img src="template/lang/all/icons/home.gif" width="20" height="21" alt="visit website" border="0" /></a><br />
	  <a href="mailto:info@aqmos.com"><img src="template/lang/all/icons/mail.gif" width="20" height="21" alt="Write email" border="0" /></a></td>
	  <td valign="top" style="padding:10PX;">Nette Webseite...<br />
Viel Erfolg</td>
	  </tr>

  
  	  <tr class="tbb">
	  <td width="130" class="tbh"> &nbsp;4 </td>
	  <td align="right" class="tbh">Wrote 2010/05/24 at 00:10&nbsp;</td>
	  </tr>
	  <tr class="tbr">
	  <td class="tbl" valign="top">
	  <strong>Chris</strong><br /><br />
	  <a href="http://www.chaletaire.com/proxy.php" target="_blank"><img src="template/lang/all/icons/home.gif" width="20" height="21" alt="visit website" border="0" /></a><br />
	  <a href="mailto:chrh@yahoo.com"><img src="template/lang/all/icons/mail.gif" width="20" height="21" alt="Write email" border="0" /></a></td>
	  <td valign="top" style="padding:10PX;">Complimenten voor jullie website,<br />
met vriendelijke groet!</td>
	  </tr>

  
  	  <tr class="tbb">
	  <td width="130" class="tbh"> &nbsp;5 </td>
	  <td align="right" class="tbh">Wrote 2010/05/20 at 10:50&nbsp;</td>
	  </tr>
	  <tr class="tbr">
	  <td class="tbl" valign="top">
	  <strong>R.Sakowski</strong><br /><br />
	  <a href="http://www.greetsiel-feriendomizil.de" target="_blank"><img src="template/lang/all/icons/home.gif" width="20" height="21" alt="visit website" border="0" /></a><br />
	  <a href="mailto:greetsiel@gmx.de"><img src="template/lang/all/icons/mail.gif" width="20" height="21" alt="Write email" border="0" /></a></td>
	  <td valign="top" style="padding:10PX;">Viele Gruesse aus dem schoenen Fischerdorf Greetsiel.</td>
	  </tr>

</table>

  <form name="sign_guestbook" action="index.php?id=105,60,1,1,1,0" method="post">

			<table border="0" cellspacing="2" cellpadding="2">
			<tr>
			<td valign="top"><label for="guestbook_email">Email *</label></td>
			<td valign="top"><input name="guestbook_email" type="text" id="guestbook_email" class="gbInputField" value="" size="50" maxlength="250" /></td>
			</tr>		
			<tr>	
			<td valign="top"><label for="guestbook_name">Name *</label></td>
			<td valign="top"><input name="guestbook_name" type="text" id="guestbook_name" class="gbInputField" value="" size="50" maxlength="500" /></td>
			</tr>
			<tr>
			<td valign="top"><label for="guestbook_url">Website</label></td>
			<td valign="top"><input name="guestbook_url" type="text" id="guestbook_url" class="gbInputField" value="" size="50" maxlength="1000" /></td>
			</tr>		
			<tr>
			<td valign="top"><label for="guestbook_msg">Message*</label></td>
			<td valign="top"><textarea name="guestbook_msg" cols="50" rows="6" id="guestbook_msg" class="gbInputTextarea"></textarea></td>
			</tr>
			
			<tr>
			<td><label>Email </label></td>
			<td>			
			<input name="guestbook_show" type="radio" value="0" id="guestbook_show0" checked="checked" />
			<label for="guestbook_show0">show</label>
			<input name="guestbook_show" type="radio" value="1" id="guestbook_show1" />
			<label for="guestbook_show1">hide</label>
			<input name="guestbook_show" type="radio" value="2" id="guestbook_show2" />
			<label for="guestbook_show2">display as &quot;info at mail dot de&quot; </label>
			</td>
			</tr>
<!--CAPTCHA_START//-->
			<tr>
			<td>&nbsp;</td>
			<td><br />
				<table width="100%" border="0" cellspacing="0" cellpadding="0">
					<tr>
						<td><label for="guestbook_captcha">read code ...</label></td>
						<td>... enter here</td>
					</tr>
					<tr><td><img src="img/captcha.php?regen=y&amp;length=5&amp;1278792839" alt="Captcha" border="0" id="gbCaptchaImage" /></td>
						<td><input name="guestbook_captcha" type="text" id="guestbook_captcha" class="gbInputFieldCaptcha" value="" size="10" maxlength="10" /></td>
					</tr>
				</table>
			</td>
			</tr>
			<tr><td colspan="2">&nbsp;</td></tr>		
<!--CAPTCHA_END//-->
			<tr>
			<td>&nbsp;</td>
			<td>
			<input name="guestbook_send" class="button" type="submit" id="guestbook_send" value="Sign guestbook" />
			</td>
			</tr>
			</table>
<input type="hidden" name="c09fbacce0ed8e40906c0e4248fd9c07" value="282977" /></form> 

  


		
</div>
</div><br />
<strong>URL:<a href="deutsche_version.phtml?id=105,60,1,1,1,0" target="_blank">deutsche_version.phtml?id=105,60,1,1,1,0</a></strong>
</body>
</html>