<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<!--
	phpwcms | free open source content management system
	created by Oliver Georgi (oliver at phpwcms dot de) and licensed under GNU/GPL.
	phpwcms is copyright 2003-2007 of Oliver Georgi. Extensions are copyright of
	their respective owners. Visit project page for details: http://www.phpwcms.org/
//-->
<title>Guestbook | Guestbook</title>
  <meta http-equiv="content-type" content="text/html; charset=iso-8859-1" />
  <meta http-equiv="content-style-type" content="text/css" />
  <script src="template/inc_js/frontend.js" type="text/javascript"></script>
  <style type="text/css" media="all">
  <!-- 
    body {
      margin: 0;
      padding-top: 0;
      padding-bottom: 0;
      padding-left: 0;
      padding-right: 0;

    }
  //-->
  </style>
  <style type="text/css">
  <!-- 
    @import url("template/inc_css/print_layout.css");
  //-->
  </style>
<meta name="Title" content="The phpWCMS Documentation" />
<meta name="author" content="Oliver Frohnert, Mario Perez Leal" />
<meta name="Publisher" content="Oliver Frohnert, Mario Perez Leal, creacion" />
<meta name="Copyright" content="Oliver Frohnert, Mario Perez Leal, creacion" />
<meta name="keywords" content="frohnert, perez leal, creacion, documentation, dokumentation, phpwcms, cms, opensource, open source, docu" />
<meta name="description" content="A Documentation Project for the  Open Source CMS phpWCMS" />
<meta name="Audience" content="Alle" />
<meta name="Content-language" content="EN" />
<meta name="robots"      content="index,follow" />
<meta name="expires" content="0" />
<meta name="revisit-after" content="7 days" />
<meta name="resource-type" content="document" />
<meta name="distribution" content="Global" />
<meta name="generator" content="PHPWCMS" />

  <!--[if lt IE 7]>
  <style type="text/css">
    body { behavior: url("template/inc_css/specific/csshover2.htc"); }
    img { behavior: url("template/inc_css/specific/pngbehavior.htc"); }
  </style>
  <![endif]-->
</head>
<body id="myid_105">


<!--

	this is the default PDF template
	use it to add additional header or
	footer information or whatever you 
	like to be rendered 

//-->

<div style="width:50%; border:1px solid #0f57a6; padding:10px; margin:10px;">
<p style="margin-bottom:20px;"><img src="./template/img/printlogo.gif" width="255" height="91" alt="" border="0" /></p>

<div id="container"><a name="top" id="top"></a>

		<a name="jump60"></a><!-- 
custom article template to split up the view / entry area for the guestbook
template by oliver@phpwcms-docu.de
===========================================================================
//-->
<div>
<h1 style="margin:0 0 5px 0;">Guestbook</h1>

</div>

<div style="margin:25px 0 0 0;padding:0;" class="spaceBeforeCP"></div>
   
<table width="100%"  border="0" cellspacing="0" cellpadding="0" style="margin-top:5px;">
  <tr>
    <td><strong><a href="105.60.1.1.1.0.phtml">&laquo;&laquo;</a> <a href="105.60.1.1.1.35.phtml">&laquo;</a></strong> <a href="105.60.1.1.1.34.phtml">35</a>&nbsp;<a href="105.60.1.1.1.35.phtml">36</a>&nbsp;<strong>37</strong>&nbsp;<a href="105.60.1.1.1.37.phtml">38</a>&nbsp;<a href="105.60.1.1.1.38.phtml">39</a> <strong><a href="105.60.1.1.1.37.phtml">&raquo;</a>
        <a href="105.60.1.1.1.42.phtml">&raquo;&raquo;</a></strong></td>
    <td align="right"></td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
</table>

<table width="100%"  border="0" cellspacing="0" cellpadding="2">
  
  
  	  <tr class="tbb">
	  <td width="130" class="tbh"> &nbsp;181 </td>
	  <td align="right" class="tbh">Wrote 2004/11/25 at 15:51&nbsp;</td>
	  </tr>
	  <tr class="tbr">
	  <td class="tbl" valign="top">
	  <strong>Alex Kink</strong><br /><br />
	  
	  alexkink at linux dot ca</td>
	  <td valign="top" style="padding:10PX;">Love the new design :) Keep up the great work</td>
	  </tr>

  
  	  <tr class="tbb">
	  <td width="130" class="tbh"> &nbsp;182 </td>
	  <td align="right" class="tbh">Wrote 2004/11/25 at 14:01&nbsp;</td>
	  </tr>
	  <tr class="tbr">
	  <td class="tbl" valign="top">
	  <strong>Andi &quot;brans&quot; Brenner</strong><br /><br />
	  <a href="http://http://www.mobifiles.de" target="_blank"><img src="template/lang/all/icons/home.gif" width="20" height="21" alt="visit website" border="0" /></a><br />
	  powerpac at gmx dot li</td>
	  <td valign="top" style="padding:10PX;">Hi Oliver und Team,<br />
<br />
echt wahnsinn, jetzt ist die Seite hier nicht nur vom Inhalt her der reinste Überflieger, sondern hat zusätzlich noch ihre letzte Schwäche, das Design auf einen zeitgemässen, hohen Standard transformiert. Bin echt beeindruckt, würde gerne wieder Zeit investieren, wenn ich welche hätte ;-)<br />
<br />
Ihr seid auf dem richtigen Weg! Diese Seite steigt von Woche zu Woche auf der kurzen Leiter von sehr gut zu perfekt immer eine der sehr kleinen Stufen weiter.<br />
<br />
grüsse aus der Schweiz</td>
	  </tr>

  
  	  <tr class="tbb">
	  <td width="130" class="tbh"> &nbsp;183 </td>
	  <td align="right" class="tbh">Wrote 2004/11/25 at 10:06&nbsp;</td>
	  </tr>
	  <tr class="tbr">
	  <td class="tbl" valign="top">
	  <strong>H.J. Munzinger</strong><br /><br />
	  
	  </td>
	  <td valign="top" style="padding:10PX;">Wow, sehr schönes, neues Design. Macht grad nen ganz anderen, übrigens sehr angenehmen Einrduck!<br />
<br />
cyber<br />
mediaDesigner</td>
	  </tr>

  
  	  <tr class="tbb">
	  <td width="130" class="tbh"> &nbsp;184 </td>
	  <td align="right" class="tbh">Wrote 2004/11/24 at 15:42&nbsp;</td>
	  </tr>
	  <tr class="tbr">
	  <td class="tbl" valign="top">
	  <strong>Mikko Levanen aka &quot;Lumimies&quot;</strong><br /><br />
	  
	  </td>
	  <td valign="top" style="padding:10PX;">Hey! New design is nice! (mean this website...)</td>
	  </tr>

  
  	  <tr class="tbb">
	  <td width="130" class="tbh"> &nbsp;185 </td>
	  <td align="right" class="tbh">Wrote 2004/11/18 at 07:20&nbsp;</td>
	  </tr>
	  <tr class="tbr">
	  <td class="tbl" valign="top">
	  <strong>Robert</strong><br /><br />
	  <a href="http://http://wandschrank.at" target="_blank"><img src="template/lang/all/icons/home.gif" width="20" height="21" alt="visit website" border="0" /></a><br />
	  </td>
	  <td valign="top" style="padding:10PX;">Nette Seite, hat mir weiter geholfen, nur die Einrichtung für das Gästebuch ist mir noch ein Rätsel....<br />
<br />
lg</td>
	  </tr>

</table>

   

  


		
</div>
</div><br />
<strong>URL:<a href="deutsche_version.phtml?id=105,60,1,1,1,36" target="_blank">deutsche_version.phtml?id=105,60,1,1,1,36</a></strong>
</body>
</html>