<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<!--
	phpwcms | free open source content management system
	created by Oliver Georgi (oliver at phpwcms dot de) and licensed under GNU/GPL.
	phpwcms is copyright 2003-2007 of Oliver Georgi. Extensions are copyright of
	their respective owners. Visit project page for details: http://www.phpwcms.org/
//-->
<title>Guestbook | Guestbook</title>
  <meta http-equiv="content-type" content="text/html; charset=iso-8859-1" />
  <meta http-equiv="content-style-type" content="text/css" />
  <script src="template/inc_js/frontend.js" type="text/javascript"></script>
  <style type="text/css" media="all">
  <!-- 
    body {
      margin: 0;
      padding-top: 0;
      padding-bottom: 0;
      padding-left: 0;
      padding-right: 0;

    }
  //-->
  </style>
  <style type="text/css">
  <!-- 
    @import url("template/inc_css/print_layout.css");
  //-->
  </style>
<meta name="Title" content="The phpWCMS Documentation" />
<meta name="author" content="Oliver Frohnert, Mario Perez Leal" />
<meta name="Publisher" content="Oliver Frohnert, Mario Perez Leal, creacion" />
<meta name="Copyright" content="Oliver Frohnert, Mario Perez Leal, creacion" />
<meta name="keywords" content="frohnert, perez leal, creacion, documentation, dokumentation, phpwcms, cms, opensource, open source, docu" />
<meta name="description" content="A Documentation Project for the  Open Source CMS phpWCMS" />
<meta name="Audience" content="Alle" />
<meta name="Content-language" content="EN" />
<meta name="robots"      content="index,follow" />
<meta name="expires" content="0" />
<meta name="revisit-after" content="7 days" />
<meta name="resource-type" content="document" />
<meta name="distribution" content="Global" />
<meta name="generator" content="PHPWCMS" />

  <!--[if lt IE 7]>
  <style type="text/css">
    body { behavior: url("template/inc_css/specific/csshover2.htc"); }
    img { behavior: url("template/inc_css/specific/pngbehavior.htc"); }
  </style>
  <![endif]-->
</head>
<body id="myid_105">


<!--

	this is the default PDF template
	use it to add additional header or
	footer information or whatever you 
	like to be rendered 

//-->

<div style="width:50%; border:1px solid #0f57a6; padding:10px; margin:10px;">
<p style="margin-bottom:20px;"><img src="./template/img/printlogo.gif" width="255" height="91" alt="" border="0" /></p>

<div id="container"><a name="top" id="top"></a>

		<a name="jump60"></a><!-- 
custom article template to split up the view / entry area for the guestbook
template by oliver@phpwcms-docu.de
===========================================================================
//-->
<div>
<h1 style="margin:0 0 5px 0;">Guestbook</h1>

</div>

<div style="margin:25px 0 0 0;padding:0;" class="spaceBeforeCP"></div>
   
<table width="100%"  border="0" cellspacing="0" cellpadding="0" style="margin-top:5px;">
  <tr>
    <td><strong><a href="105.60.1.1.1.0.phtml">&laquo;&laquo;</a> <a href="105.60.1.1.1.24.phtml">&laquo;</a></strong> <a href="105.60.1.1.1.21.phtml">22</a>&nbsp;<a href="105.60.1.1.1.22.phtml">23</a>&nbsp;<a href="105.60.1.1.1.23.phtml">24</a>&nbsp;<a href="105.60.1.1.1.24.phtml">25</a>&nbsp;<strong>26</strong> <strong>&raquo;
        &raquo;&raquo;</strong></td>
    <td align="right"></td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
</table>

<table width="100%"  border="0" cellspacing="0" cellpadding="2">
  
  
  	  <tr class="tbb">
	  <td width="130" class="tbh"> &nbsp;126 </td>
	  <td align="right" class="tbh">Wrote 2004/08/15 at 19:30&nbsp;</td>
	  </tr>
	  <tr class="tbr">
	  <td class="tbl" valign="top">
	  <strong>Uwe Twelker</strong><br /><br />
	  <a href="http://http://www.eyelikeit.de" target="_blank"><img src="template/lang/all/icons/home.gif" width="20" height="21" alt="visit website" border="0" /></a><br />
	  uwe.twelker at eyelikeit dot de</td>
	  <td valign="top" style="padding:10PX;">I&#039;m using the PHPWCMS for about half a year. And I think it&#039;s dynamite. What makes it great is of course the PHPWCMS itself. Easy to install, easy to use (you feel like driving a Mac!). But that&#039;s far form being everything. There is an Oliver who talks and listens to his users and works and works and works... There is a great community assisting in the forum. They are fast, they are friendly, there are competencies for almost everything and this knowledge is generously shared. There is another Oliver, and Manfred and Achim and Jayenne who work there butts off to set up this documentation. And there a lot of more unknown people with a lot of unknown useful contributions.<br />
<br />
Thank you all. I&#039;m proud to be part of this community!<br />
<br />
<div style="background-color:#c1dbf7; padding:2px; border:1px dotted #517ba5;"><strong>Comment:</strong><br />hello mac and thank you for the translation and the correction of some articles.<br />
Oliver &quot;Pappnase&quot;</div></td>
	  </tr>

  
  	  <tr class="tbb">
	  <td width="130" class="tbh"> &nbsp;127 </td>
	  <td align="right" class="tbh">Wrote 2004/08/14 at 16:34&nbsp;</td>
	  </tr>
	  <tr class="tbr">
	  <td class="tbl" valign="top">
	  <strong>Tim Driever</strong><br /><br />
	  
	  <a href="mailto:timdriever@hotmail.com"><img src="template/lang/all/icons/mail.gif" width="20" height="21" alt="Write email" border="0" /></a></td>
	  <td valign="top" style="padding:10PX;">PHPWcms is a great CMS!! Good work Oliver and the crew from this site that you make a documenation for PHPWcms! Succes..!</td>
	  </tr>

  
  	  <tr class="tbb">
	  <td width="130" class="tbh"> &nbsp;128 </td>
	  <td align="right" class="tbh">Wrote 2004/08/14 at 01:10&nbsp;</td>
	  </tr>
	  <tr class="tbr">
	  <td class="tbl" valign="top">
	  <strong>Jérôme Gamez</strong><br /><br />
	  <a href="http://http://jerome-gamez.de/" target="_blank"><img src="template/lang/all/icons/home.gif" width="20" height="21" alt="visit website" border="0" /></a><br />
	  <a href="mailto:spam@jerome-gamez.de"><img src="template/lang/all/icons/mail.gif" width="20" height="21" alt="Write email" border="0" /></a></td>
	  <td valign="top" style="padding:10PX;">Sehr gute Arbeit. Die Seite wird fortwährend umfangreicher und besser. Vielen Dank für euren unermüdlichen Einsatz, insb. Oliver (Pappnase), bei dem man sich fragen &quot;muss&quot;, ob er eigentlich irgendwann auch mal schläft oder etwas anderes macht :).<br />
<br />
Viele Grüße<br />
- Jérôme</td>
	  </tr>

  
  	  <tr class="tbb">
	  <td width="130" class="tbh"> &nbsp;129 </td>
	  <td align="right" class="tbh">Wrote 2004/08/12 at 21:31&nbsp;</td>
	  </tr>
	  <tr class="tbr">
	  <td class="tbl" valign="top">
	  <strong>Stefan Bachfischer</strong><br /><br />
	  <a href="http://http://www.istwan.com" target="_blank"><img src="template/lang/all/icons/home.gif" width="20" height="21" alt="visit website" border="0" /></a><br />
	  <a href="mailto:design@istwan.com"><img src="template/lang/all/icons/mail.gif" width="20" height="21" alt="Write email" border="0" /></a></td>
	  <td valign="top" style="padding:10PX;">Einfach ein super CMS. Dieses Verwaltungssystem wird in zukunft in jede Website meiner Kunden eingebunden. (Und auch in die eigene:-)<br />
<br />
Macht weiter so!!</td>
	  </tr>

  
  	  <tr class="tbb">
	  <td width="130" class="tbh"> &nbsp;130 </td>
	  <td align="right" class="tbh">Wrote 2004/08/11 at 13:40&nbsp;</td>
	  </tr>
	  <tr class="tbr">
	  <td class="tbl" valign="top">
	  <strong>Enrico Eilert</strong><br /><br />
	  <a href="http://http://www.familie-eilert.com" target="_blank"><img src="template/lang/all/icons/home.gif" width="20" height="21" alt="visit website" border="0" /></a><br />
	  <a href="mailto:webmaster@familie-eilert.com"><img src="template/lang/all/icons/mail.gif" width="20" height="21" alt="Write email" border="0" /></a></td>
	  <td valign="top" style="padding:10PX;">hallo,<br />
ich fange gerade an mit phpwcms zu arbeiten und bin gerade auf eurer Seite gelandet. Sie hilft auf jedem Fall weiter. Danke und weiter so.</td>
	  </tr>

</table>

   

  


		
</div>
</div><br />
<strong>URL:<a href="deutsche_version.phtml?id=105,60,1,1,1,25" target="_blank">deutsche_version.phtml?id=105,60,1,1,1,25</a></strong>
</body>
</html>