<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<!--
	phpwcms | free open source content management system
	created by Oliver Georgi (oliver at phpwcms dot de) and licensed under GNU/GPL.
	phpwcms is copyright 2003-2007 of Oliver Georgi. Extensions are copyright of
	their respective owners. Visit project page for details: http://www.phpwcms.org/
//-->
<title>Guestbook | Guestbook</title>
  <meta http-equiv="content-type" content="text/html; charset=iso-8859-1" />
  <meta http-equiv="content-style-type" content="text/css" />
  <script src="template/inc_js/frontend.js" type="text/javascript"></script>
  <style type="text/css" media="all">
  <!-- 
    body {
      margin: 0;
      padding-top: 0;
      padding-bottom: 0;
      padding-left: 0;
      padding-right: 0;

    }
  //-->
  </style>
  <style type="text/css">
  <!-- 
    @import url("template/inc_css/print_layout.css");
  //-->
  </style>
<meta name="Title" content="The phpWCMS Documentation" />
<meta name="author" content="Oliver Frohnert, Mario Perez Leal" />
<meta name="Publisher" content="Oliver Frohnert, Mario Perez Leal, creacion" />
<meta name="Copyright" content="Oliver Frohnert, Mario Perez Leal, creacion" />
<meta name="keywords" content="frohnert, perez leal, creacion, documentation, dokumentation, phpwcms, cms, opensource, open source, docu" />
<meta name="description" content="A Documentation Project for the  Open Source CMS phpWCMS" />
<meta name="Audience" content="Alle" />
<meta name="Content-language" content="EN" />
<meta name="robots"      content="index,follow" />
<meta name="expires" content="0" />
<meta name="revisit-after" content="7 days" />
<meta name="resource-type" content="document" />
<meta name="distribution" content="Global" />
<meta name="generator" content="PHPWCMS" />

  <!--[if lt IE 7]>
  <style type="text/css">
    body { behavior: url("template/inc_css/specific/csshover2.htc"); }
    img { behavior: url("template/inc_css/specific/pngbehavior.htc"); }
  </style>
  <![endif]-->
</head>
<body id="myid_105">


<!--

	this is the default PDF template
	use it to add additional header or
	footer information or whatever you 
	like to be rendered 

//-->

<div style="width:50%; border:1px solid #0f57a6; padding:10px; margin:10px;">
<p style="margin-bottom:20px;"><img src="./template/img/printlogo.gif" width="255" height="91" alt="" border="0" /></p>

<div id="container"><a name="top" id="top"></a>

		<a name="jump60"></a><!-- 
custom article template to split up the view / entry area for the guestbook
template by oliver@phpwcms-docu.de
===========================================================================
//-->
<div>
<h1 style="margin:0 0 5px 0;">Guestbook</h1>

</div>

<div style="margin:25px 0 0 0;padding:0;" class="spaceBeforeCP"></div>
   
<table width="100%"  border="0" cellspacing="0" cellpadding="0" style="margin-top:5px;">
  <tr>
    <td><strong><a href="105.60.1.1.1.0.phtml">&laquo;&laquo;</a> <a href="105.60.1.1.1.6.phtml">&laquo;</a></strong> <a href="105.60.1.1.1.5.phtml">6</a>&nbsp;<a href="105.60.1.1.1.6.phtml">7</a>&nbsp;<strong>8</strong>&nbsp;<a href="105.60.1.1.1.8.phtml">9</a>&nbsp;<a href="105.60.1.1.1.9.phtml">10</a> <strong><a href="105.60.1.1.1.8.phtml">&raquo;</a>
        <a href="105.60.1.1.1.26.phtml">&raquo;&raquo;</a></strong></td>
    <td align="right"></td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
</table>

<table width="100%"  border="0" cellspacing="0" cellpadding="2">
  
  
  	  <tr class="tbb">
	  <td width="130" class="tbh"> &nbsp;36 </td>
	  <td align="right" class="tbh">Wrote 2009/10/20 at 11:14&nbsp;</td>
	  </tr>
	  <tr class="tbr">
	  <td class="tbl" valign="top">
	  <strong>doris</strong><br /><br />
	  <a href="http://www.free-sex-films-sado-maso.us" target="_blank"><img src="template/lang/all/icons/home.gif" width="20" height="21" alt="visit website" border="0" /></a><br />
	  <a href="mailto:doris078@gmail.com"><img src="template/lang/all/icons/mail.gif" width="20" height="21" alt="Write email" border="0" /></a></td>
	  <td valign="top" style="padding:10PX;">Ich finde den Aufbau der Seite sehr gut. Macht weiter so.</td>
	  </tr>

  
  	  <tr class="tbb">
	  <td width="130" class="tbh"> &nbsp;37 </td>
	  <td align="right" class="tbh">Wrote 2009/10/19 at 01:28&nbsp;</td>
	  </tr>
	  <tr class="tbr">
	  <td class="tbl" valign="top">
	  <strong>André Baldeweg</strong><br /><br />
	  <a href="http://www.sokole-fans.de" target="_blank"><img src="template/lang/all/icons/home.gif" width="20" height="21" alt="visit website" border="0" /></a><br />
	  </td>
	  <td valign="top" style="padding:10PX;">Sehr gelungene und hilfreiche Seite! Danke!</td>
	  </tr>

  
  	  <tr class="tbb">
	  <td width="130" class="tbh"> &nbsp;38 </td>
	  <td align="right" class="tbh">Wrote 2009/10/12 at 14:57&nbsp;</td>
	  </tr>
	  <tr class="tbr">
	  <td class="tbl" valign="top">
	  <strong>vitalij</strong><br /><br />
	  
	  <a href="mailto:asd@web.de"><img src="template/lang/all/icons/mail.gif" width="20" height="21" alt="Write email" border="0" /></a></td>
	  <td valign="top" style="padding:10PX;">Tixuma ist eine Suchmaschine, die seinen Teilnehmern ermöglicht, <br />
Geld damit zu verdienen, daß diese Tixuma als Suchmaschine im Internet verwenden.<br />
Zusätzlich erhält man Provisionen dafür, Teilnehmer für Tixuma zu werben.<br />
<br />
Dies wird ermöglicht, weil Tixuma bis zu 80% seiner Werbeeinnahmen<br />
an seine User als Provisionen weitergibt. <br />
<br />
Die Teilnahme ist kostenlos und unverbindlich.<br />
<br />
<br />
http://www.tixuma.de/?ref=19347</td>
	  </tr>

  
  	  <tr class="tbb">
	  <td width="130" class="tbh"> &nbsp;39 </td>
	  <td align="right" class="tbh">Wrote 2009/10/12 at 03:59&nbsp;</td>
	  </tr>
	  <tr class="tbr">
	  <td class="tbl" valign="top">
	  <strong>Sara</strong><br /><br />
	  <a href="http://www.sara-wyler.com" target="_blank"><img src="template/lang/all/icons/home.gif" width="20" height="21" alt="visit website" border="0" /></a><br />
	  </td>
	  <td valign="top" style="padding:10PX;">Vielen Dank für die Infos! Hat mir sehr gehlofen.</td>
	  </tr>

  
  	  <tr class="tbb">
	  <td width="130" class="tbh"> &nbsp;40 </td>
	  <td align="right" class="tbh">Wrote 2009/09/24 at 09:38&nbsp;</td>
	  </tr>
	  <tr class="tbr">
	  <td class="tbl" valign="top">
	  <strong>doris</strong><br /><br />
	  <a href="http://www.sexydollar.tv" target="_blank"><img src="template/lang/all/icons/home.gif" width="20" height="21" alt="visit website" border="0" /></a><br />
	  <a href="mailto:doris078@gmail.com"><img src="template/lang/all/icons/mail.gif" width="20" height="21" alt="Write email" border="0" /></a></td>
	  <td valign="top" style="padding:10PX;">Ich finde den Aufbau der Seite sehr gut. Macht weiter so.</td>
	  </tr>

</table>

   

  


		
</div>
</div><br />
<strong>URL:<a href="deutsche_version.phtml?id=105,60,1,1,1,7" target="_blank">deutsche_version.phtml?id=105,60,1,1,1,7</a></strong>
</body>
</html>