<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<!--
	phpwcms | free open source content management system
	created by Oliver Georgi (oliver at phpwcms dot de) and licensed under GNU/GPL.
	phpwcms is copyright 2003-2007 of Oliver Georgi. Extensions are copyright of
	their respective owners. Visit project page for details: http://www.phpwcms.org/
//-->
<title>Guestbook | Guestbook</title>
  <meta http-equiv="content-type" content="text/html; charset=iso-8859-1" />
  <meta http-equiv="content-style-type" content="text/css" />
  <script src="template/inc_js/frontend.js" type="text/javascript"></script>
  <style type="text/css" media="all">
  <!-- 
    body {
      margin: 0;
      padding-top: 0;
      padding-bottom: 0;
      padding-left: 0;
      padding-right: 0;

    }
  //-->
  </style>
  <style type="text/css">
  <!-- 
    @import url("template/inc_css/print_layout.css");
  //-->
  </style>
<meta name="Title" content="The phpWCMS Documentation" />
<meta name="author" content="Oliver Frohnert, Mario Perez Leal" />
<meta name="Publisher" content="Oliver Frohnert, Mario Perez Leal, creacion" />
<meta name="Copyright" content="Oliver Frohnert, Mario Perez Leal, creacion" />
<meta name="keywords" content="frohnert, perez leal, creacion, documentation, dokumentation, phpwcms, cms, opensource, open source, docu" />
<meta name="description" content="A Documentation Project for the  Open Source CMS phpWCMS" />
<meta name="Audience" content="Alle" />
<meta name="Content-language" content="EN" />
<meta name="robots"      content="index,follow" />
<meta name="expires" content="0" />
<meta name="revisit-after" content="7 days" />
<meta name="resource-type" content="document" />
<meta name="distribution" content="Global" />
<meta name="generator" content="PHPWCMS" />

  <!--[if lt IE 7]>
  <style type="text/css">
    body { behavior: url("template/inc_css/specific/csshover2.htc"); }
    img { behavior: url("template/inc_css/specific/pngbehavior.htc"); }
  </style>
  <![endif]-->
</head>
<body id="myid_105">


<!--

	this is the default PDF template
	use it to add additional header or
	footer information or whatever you 
	like to be rendered 

//-->

<div style="width:50%; border:1px solid #0f57a6; padding:10px; margin:10px;">
<p style="margin-bottom:20px;"><img src="./template/img/printlogo.gif" width="255" height="91" alt="" border="0" /></p>

<div id="container"><a name="top" id="top"></a>

		<a name="jump60"></a><!-- 
custom article template to split up the view / entry area for the guestbook
template by oliver@phpwcms-docu.de
===========================================================================
//-->
<div>
<h1 style="margin:0 0 5px 0;">Guestbook</h1>

</div>

<div style="margin:25px 0 0 0;padding:0;" class="spaceBeforeCP"></div>
   
<table width="100%"  border="0" cellspacing="0" cellpadding="0" style="margin-top:5px;">
  <tr>
    <td><strong><a href="105.60.1.1.1.0.phtml">&laquo;&laquo;</a> <a href="105.60.1.1.1.9.phtml">&laquo;</a></strong> <a href="105.60.1.1.1.8.phtml">9</a>&nbsp;<a href="105.60.1.1.1.9.phtml">10</a>&nbsp;<strong>11</strong>&nbsp;<a href="105.60.1.1.1.11.phtml">12</a>&nbsp;<a href="105.60.1.1.1.12.phtml">13</a> <strong><a href="105.60.1.1.1.11.phtml">&raquo;</a>
        <a href="105.60.1.1.1.26.phtml">&raquo;&raquo;</a></strong></td>
    <td align="right"></td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
</table>

<table width="100%"  border="0" cellspacing="0" cellpadding="2">
  
  
  	  <tr class="tbb">
	  <td width="130" class="tbh"> &nbsp;51 </td>
	  <td align="right" class="tbh">Wrote 2009/03/12 at 12:26&nbsp;</td>
	  </tr>
	  <tr class="tbr">
	  <td class="tbl" valign="top">
	  <strong>nide</strong><br /><br />
	  
	  </td>
	  <td valign="top" style="padding:10PX;">eine wirklich super gelungende docu!!!<br />
hat mir schon einige male das leben leichter gemacht. :o)<br />
aber schade das es schon länger keine updates mehr gab. es findet sich ja eh schon kaum was über phpwcms im netz, obwohl es, wie ich finde, eindeutig das einfachste cms system ist. (mit der docu eh ;o) )<br />
wie schauts denn mal mit den templates aus? oder ein paar berichte zu der neuesten version?</td>
	  </tr>

  
  	  <tr class="tbb">
	  <td width="130" class="tbh"> &nbsp;52 </td>
	  <td align="right" class="tbh">Wrote 2009/01/15 at 20:20&nbsp;</td>
	  </tr>
	  <tr class="tbr">
	  <td class="tbl" valign="top">
	  <strong>Jennifer</strong><br /><br />
	  <a href="http://www.lemonbirds.de" target="_blank"><img src="template/lang/all/icons/home.gif" width="20" height="21" alt="visit website" border="0" /></a><br />
	  </td>
	  <td valign="top" style="padding:10PX;">Hallo zusammen,<br />
<br />
wollte auf diesem Weg nur mal Danke sagen. Ihr habt ja gar keine Ahnung, wie oft mir die Docu schon geholfen hat... ;-)<br />
Weiter so!</td>
	  </tr>

  
  	  <tr class="tbb">
	  <td width="130" class="tbh"> &nbsp;53 </td>
	  <td align="right" class="tbh">Wrote 2008/11/26 at 20:18&nbsp;</td>
	  </tr>
	  <tr class="tbr">
	  <td class="tbl" valign="top">
	  <strong>Alexander Kravtsov</strong><br /><br />
	  <a href="http://www.alexanderkravtsov.com" target="_blank"><img src="template/lang/all/icons/home.gif" width="20" height="21" alt="visit website" border="0" /></a><br />
	  info at alexanderkravtsov dot com</td>
	  <td valign="top" style="padding:10PX;">Hallo, vielen Dank für Eure Hilfe!</td>
	  </tr>

  
  	  <tr class="tbb">
	  <td width="130" class="tbh"> &nbsp;54 </td>
	  <td align="right" class="tbh">Wrote 2008/10/23 at 15:20&nbsp;</td>
	  </tr>
	  <tr class="tbr">
	  <td class="tbl" valign="top">
	  <strong>Dominik</strong><br /><br />
	  
	  </td>
	  <td valign="top" style="padding:10PX;">Herzlichen Glückwunsch zur der sehr Informativen Seite.<br />
<br />
Macht weiter so...<br />
<br />
LG Dominik</td>
	  </tr>

  
  	  <tr class="tbb">
	  <td width="130" class="tbh"> &nbsp;55 </td>
	  <td align="right" class="tbh">Wrote 2008/08/10 at 12:01&nbsp;</td>
	  </tr>
	  <tr class="tbr">
	  <td class="tbl" valign="top">
	  <strong>Humbold</strong><br /><br />
	  
	  humbold at wert dot at</td>
	  <td valign="top" style="padding:10PX;">Wäre toll wenn auf Dieser Seite Anleitungen uusw aktuallisiert würden. ist ja alles veraltet !<br />
es gibt wcms 1.3.9</td>
	  </tr>

</table>

   

  


		
</div>
</div><br />
<strong>URL:<a href="deutsche_version.phtml?id=105,60,1,1,1,10" target="_blank">deutsche_version.phtml?id=105,60,1,1,1,10</a></strong>
</body>
</html>