<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<!--
	phpwcms | free open source content management system
	created by Oliver Georgi (oliver at phpwcms dot de) and licensed under GNU/GPL.
	phpwcms is copyright 2003-2007 of Oliver Georgi. Extensions are copyright of
	their respective owners. Visit project page for details: http://www.phpwcms.org/
//-->
<title>Guestbook | Guestbook</title>
  <meta http-equiv="content-type" content="text/html; charset=iso-8859-1" />
  <meta http-equiv="content-style-type" content="text/css" />
  <script src="template/inc_js/frontend.js" type="text/javascript"></script>
  <style type="text/css" media="all">
  <!-- 
    body {
      margin: 0;
      padding-top: 0;
      padding-bottom: 0;
      padding-left: 0;
      padding-right: 0;

    }
  //-->
  </style>
  <style type="text/css">
  <!-- 
    @import url("template/inc_css/print_layout.css");
  //-->
  </style>
<meta name="Title" content="The phpWCMS Documentation" />
<meta name="author" content="Oliver Frohnert, Mario Perez Leal" />
<meta name="Publisher" content="Oliver Frohnert, Mario Perez Leal, creacion" />
<meta name="Copyright" content="Oliver Frohnert, Mario Perez Leal, creacion" />
<meta name="keywords" content="frohnert, perez leal, creacion, documentation, dokumentation, phpwcms, cms, opensource, open source, docu" />
<meta name="description" content="A Documentation Project for the  Open Source CMS phpWCMS" />
<meta name="Audience" content="Alle" />
<meta name="Content-language" content="EN" />
<meta name="robots"      content="index,follow" />
<meta name="expires" content="0" />
<meta name="revisit-after" content="7 days" />
<meta name="resource-type" content="document" />
<meta name="distribution" content="Global" />
<meta name="generator" content="PHPWCMS" />

  <!--[if lt IE 7]>
  <style type="text/css">
    body { behavior: url("template/inc_css/specific/csshover2.htc"); }
    img { behavior: url("template/inc_css/specific/pngbehavior.htc"); }
  </style>
  <![endif]-->
</head>
<body id="myid_105">


<!--

	this is the default PDF template
	use it to add additional header or
	footer information or whatever you 
	like to be rendered 

//-->

<div style="width:50%; border:1px solid #0f57a6; padding:10px; margin:10px;">
<p style="margin-bottom:20px;"><img src="./template/img/printlogo.gif" width="255" height="91" alt="" border="0" /></p>

<div id="container"><a name="top" id="top"></a>

		<a name="jump60"></a><!-- 
custom article template to split up the view / entry area for the guestbook
template by oliver@phpwcms-docu.de
===========================================================================
//-->
<div>
<h1 style="margin:0 0 5px 0;">Guestbook</h1>

</div>

<div style="margin:25px 0 0 0;padding:0;" class="spaceBeforeCP"></div>
   
<table width="100%"  border="0" cellspacing="0" cellpadding="0" style="margin-top:5px;">
  <tr>
    <td><strong><a href="105.60.1.0.1.0.phtml">&laquo;&laquo;</a> <a href="105.60.1.0.1.5.phtml">&laquo;</a></strong> <a href="105.60.1.0.1.4.phtml">5</a>&nbsp;<a href="105.60.1.0.1.5.phtml">6</a>&nbsp;<strong>7</strong>&nbsp;<a href="105.60.1.0.1.7.phtml">8</a>&nbsp;<a href="105.60.1.0.1.8.phtml">9</a> <strong><a href="105.60.1.0.1.7.phtml">&raquo;</a>
        <a href="105.60.1.0.1.29.phtml">&raquo;&raquo;</a></strong></td>
    <td align="right"></td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
</table>

<table width="100%"  border="0" cellspacing="0" cellpadding="2">
  
  
  	  <tr class="tbb">
	  <td width="130" class="tbh"> &nbsp;31 </td>
	  <td align="right" class="tbh">Wrote 2010/01/22 at 12:29&nbsp;</td>
	  </tr>
	  <tr class="tbr">
	  <td class="tbl" valign="top">
	  <strong>Imsa</strong><br /><br />
	  <a href="http://www.imsa-gmbh.de" target="_blank"><img src="template/lang/all/icons/home.gif" width="20" height="21" alt="visit website" border="0" /></a><br />
	  <a href="mailto:imsa@trash-mail.com"><img src="template/lang/all/icons/mail.gif" width="20" height="21" alt="Write email" border="0" /></a></td>
	  <td valign="top" style="padding:10PX;">Sehr gut, hat mir weitergeholfen. Sehr zu empfehlen, vielen Dank !!!</td>
	  </tr>

  
  	  <tr class="tbb">
	  <td width="130" class="tbh"> &nbsp;32 </td>
	  <td align="right" class="tbh">Wrote 2010/01/22 at 07:07&nbsp;</td>
	  </tr>
	  <tr class="tbr">
	  <td class="tbl" valign="top">
	  <strong>Reiner</strong><br /><br />
	  <a href="http://www.greetsiel-feriendomizil.de" target="_blank"><img src="template/lang/all/icons/home.gif" width="20" height="21" alt="visit website" border="0" /></a><br />
	  <a href="mailto:rebisa@gmx.de"><img src="template/lang/all/icons/mail.gif" width="20" height="21" alt="Write email" border="0" /></a></td>
	  <td valign="top" style="padding:10PX;">schöne Seite. Respekt</td>
	  </tr>

  
  	  <tr class="tbb">
	  <td width="130" class="tbh"> &nbsp;33 </td>
	  <td align="right" class="tbh">Wrote 2010/01/22 at 01:11&nbsp;</td>
	  </tr>
	  <tr class="tbr">
	  <td class="tbl" valign="top">
	  <strong>Tom</strong><br /><br />
	  <a href="http://www.b2bizness.com/link/Online-Roulette.38.html" target="_blank"><img src="template/lang/all/icons/home.gif" width="20" height="21" alt="visit website" border="0" /></a><br />
	  </td>
	  <td valign="top" style="padding:10PX;">Vielen Danke für die Infos!</td>
	  </tr>

  
  	  <tr class="tbb">
	  <td width="130" class="tbh"> &nbsp;34 </td>
	  <td align="right" class="tbh">Wrote 2010/01/20 at 09:41&nbsp;</td>
	  </tr>
	  <tr class="tbr">
	  <td class="tbl" valign="top">
	  <strong>Michael</strong><br /><br />
	  <a href="http://www.mkschubert.de" target="_blank"><img src="template/lang/all/icons/home.gif" width="20" height="21" alt="visit website" border="0" /></a><br />
	  </td>
	  <td valign="top" style="padding:10PX;">Hallo, mir hat Deine Webseite sehr gefallen, auf die ich heute durch Zufall gekommen bin. Du hast Dir sehr viel Mühe gegeben! Freue mich natürlich immer auch auf einen Gegenbesuch bei mir. Auf meinen Reiseseiten berichte ich u.a. über meine wunderschönen Reisen nach Australien, Neuseeland, Thailand und in die USA, über meine interessanten Arbeitserfahrungen in England und Irland sowie über meine traumatischen Erfahrungen in einem österreichischen Krankenhaus. Weiterhin viel Erfolg mit Deiner Seite wünscht Dir Michael!<br />
http://www.michaels-reisetagebuch.de</td>
	  </tr>

  
  	  <tr class="tbb">
	  <td width="130" class="tbh"> &nbsp;35 </td>
	  <td align="right" class="tbh">Wrote 2010/01/15 at 06:43&nbsp;</td>
	  </tr>
	  <tr class="tbr">
	  <td class="tbl" valign="top">
	  <strong>Marie</strong><br /><br />
	  <a href="http://www.llogin.com/projekt/" target="_blank"><img src="template/lang/all/icons/home.gif" width="20" height="21" alt="visit website" border="0" /></a><br />
	  <a href="mailto:mmb@msn.com"><img src="template/lang/all/icons/mail.gif" width="20" height="21" alt="Write email" border="0" /></a></td>
	  <td valign="top" style="padding:10PX;">nette Seite, wünsche viel Erfolg und<br />
Schöne Grüße,<br />
Marie.</td>
	  </tr>

</table>

   

  


		
</div>
</div><br />
<strong>URL:<a href="deutsche_version.phtml?id=105,60,1,0,1,6" target="_blank">deutsche_version.phtml?id=105,60,1,0,1,6</a></strong>
</body>
</html>