<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<!--
	phpwcms | free open source content management system
	created by Oliver Georgi (oliver at phpwcms dot de) and licensed under GNU/GPL.
	phpwcms is copyright 2003-2006 of Oliver Georgi. Extensions are copyright of\
	their respective owners. Visit project page for details: http://www.phpwcms.org/
//-->
<title></title>
  <meta http-equiv="content-type" content="text/html; charset=iso-8859-1" />
  <meta http-equiv="content-style-type" content="text/css" />
  <script src="template/inc_js/frontend.js" type="text/javascript"></script>
  <style type="text/css" media="all">
  /* <![CDATA[ */
    body {
      margin: 0;
      padding-top: 0;
      padding-bottom: 0;
      padding-left: 0;
      padding-right: 0;

    }
  /* ]]> */
  </style>
  <style type="text/css">
  /* <![CDATA[ */
    @import url("template/inc_css/frontend.css");
    @import url("template/inc_css/nlu_navi1_docu.css");
    @import url("template/inc_css/print_layout.css");
  /* ]]> */
  </style>


<META NAME="Title" CONTENT="The phpWCMS Documentation">
<meta name="author" content="Oliver Frohnert">
<meta name="Publisher" content="Oliver Frohnert">
<meta name="Copyright" content="Oliver Frohnert">
<meta name="keywords" content="frohnert,documentation, dokumentation, phpwcms, cms. opensource, open source">
<meta name="description" content="A Documentation Project for the  Open Source CMS phpWCMS">
<meta name="Audience" content="Alle">
<meta name="Content-language" content="EN">
<META NAME="robots"      CONTENT="index,follow">
<META NAME="expires" CONTENT="0">
<meta name="revisit-after" content="7 days">
<meta name="resource-type" content="document">
<meta name="distribution" content="Global">
<meta name="generator" content="PHPWCMS">

  <!--[if lt IE 7]>
  <style type="text/css">
    body { behavior: url("template/inc_css/specific/csshover2.htc"); }
    img { behavior: url("template/inc_css/specific/pngbehavior.htc"); }
  </style>
  <![endif]-->
</head>
<body>
<img src="img/leer.gif" border="0" width="10" height="1" alt="" />
<br />
<a href="english_version.phtml">English</a> <span class="breadcrumb_spacer">&gt;</span> <a href="contact.phtml">Contact</a> <span class="breadcrumb_spacer">&gt;</span> Guestbook
<br />
<HR>
<br />
<a name="jump60"></a><h1>Guestbook</h1><div style="margin:25px 0 0 0; padding:0 0 0 0; clear:both;"></div>
   
<table width="100%"  border="0" cellspacing="0" cellpadding="0" style="margin-top:5px;">
  <tr>
    <td><strong><a href="105.60.1.1.1.0.phtml">&lt;&lt;</a> <a href="105.60.1.1.1.115.phtml">&lt;</a></strong> <a href="105.60.1.1.1.114.phtml">115</a>&nbsp;<a href="105.60.1.1.1.115.phtml">116</a>&nbsp;<strong>117</strong>&nbsp;<a href="105.60.1.1.1.117.phtml">118</a>&nbsp;<a href="105.60.1.1.1.118.phtml">119</a> <strong><a href="105.60.1.1.1.117.phtml">&gt;</a>
        <a href="105.60.1.1.1.121.phtml">&gt;&gt;</a></strong></td>
    <td align="right">&nbsp;</td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
</table>

<table width="100%"  border="0" cellspacing="0" cellpadding="2">
  
  <tr bgcolor="#F5F5F5">
    <td width="99%">581 | 11/24/2004 15:42</td>
  </tr>
  <tr>
    <td colspan="2"><strong>Mikko Levanen aka &quot;Lumimies&quot;</strong>  <br />
      Hey! New design is nice! (mean this website...)</td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
  
  <tr bgcolor="#F5F5F5">
    <td width="99%">582 | 11/18/2004 07:20</td>
  </tr>
  <tr>
    <td colspan="2"><strong>Robert</strong> <a href="http://wandschrank.at" target="_blank">visit
      website</a> <br />
      Nette Seite, hat mir weiter geholfen, nur die Einrichtung für das Gästebuch ist mir noch ein Rätsel....<br />
<br />
lg</td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
  
  <tr bgcolor="#F5F5F5">
    <td width="99%">583 | 11/08/2004 09:57</td>
  </tr>
  <tr>
    <td colspan="2"><strong>Satelle</strong> <a href="http://www.fatumoperandi.org" target="_blank">visit
      website</a> satelle at fatumoperandi  dot org<br />
      Great document site, very helpful to us phpwcms fans!</td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
  
  <tr bgcolor="#F5F5F5">
    <td width="99%">584 | 10/18/2004 21:32</td>
  </tr>
  <tr>
    <td colspan="2"><a href="mailto:info@klarmedia.de"><strong>Alexander Klar</strong></a> <a href="http://www.klarmedia.de" target="_blank">visit
      website</a> info@klarmedia.de<br />
      Hallo Oliver und Redaktion!<br />
<br />
Seit längerer Zeit habe ich mal wieder den Weg auf diese Seite gefunden. Wow, ist ja wirklich umfangreich geworden. Ich freue mich zu sehen, wie meine ersten Ansätze einer Dokumentation erwachsen geworden sind und weiter gepflegt werden. Eine Dokumentation ist so wichtig für dieses wunderbare OpenSource-Projekt! Daumen hoch für die Community und ihre Vorreiter.<br />
<br />
Liebe Grüße aus Köln<br />
Alexander</td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
  
  <tr bgcolor="#F5F5F5">
    <td width="99%">585 | 10/15/2004 21:27</td>
  </tr>
  <tr>
    <td colspan="2"><strong>Thomas</strong>  <br />
      Hi, wirklich eine Klasse Hilfe, freu mich immer über neue Info:-)<br />
<br />
Thomas</td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
  
</table>

<table width="100%"  border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td colspan="2"><HR></td>
  </tr>
  <tr>
    <td width="50%">Article created: 2004/08/17</td>
    <td align="right" width="50%">Last Changes: 2006/06/06</td>
  </tr>
  <tr>
    <td colspan="2">&nbsp;</td>
  </tr>
  <tr>
    <td colspan="2" class="comment">In case you find any mistakes or have enhancments, please use this <a href="#" onClick="javascript:window.open('./content/pages/message.htm','frage','width=400, height=250, screenX=440,screenY=200,menubar=no,statusbar=yes,scrollbar=yes,resizable=no');" target="" style="max-width:148px; overflow:hidden;"><u>form</u></a> .<br /><br />
Have you found this website a helpful resource in understanding the Phpwcms content management system? If so, would you consider making a donation?  Please click here: <a href="#paypal">PayPal</a>. We welcome any donation amount. Your contribution helps make this website an even better resource and helps underwrite the associated server expenses of accomodating a growing number of visitors.<br />
This page use the version:</td>
  </tr>
  <tr>

    <td colspan="2"><img src="img/leer.gif" border="0" width="10" height="10" alt="" /></td>
  </tr>
</table>

</body>
</html>