<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<!--
	phpwcms | free open source content management system
	created by Oliver Georgi (oliver at phpwcms dot de) and licensed under GNU/GPL.
	phpwcms is copyright 2003-2007 of Oliver Georgi. Extensions are copyright of
	their respective owners. Visit project page for details: http://www.phpwcms.org/
//-->
<title>Guestbook | Guestbook</title>
  <meta http-equiv="content-type" content="text/html; charset=iso-8859-1" />
  <meta http-equiv="content-style-type" content="text/css" />
  <script src="template/inc_js/frontend.js" type="text/javascript"></script>
  <style type="text/css" media="all">
  <!-- 
    body {
      margin: 0;
      padding-top: 0;
      padding-bottom: 0;
      padding-left: 0;
      padding-right: 0;

    }
  //-->
  </style>
  <style type="text/css">
  <!-- 
    @import url("template/inc_css/print_layout.css");
  //-->
  </style>
<meta name="Title" content="The phpWCMS Documentation" />
<meta name="author" content="Oliver Frohnert, Mario Perez Leal" />
<meta name="Publisher" content="Oliver Frohnert, Mario Perez Leal, creacion" />
<meta name="Copyright" content="Oliver Frohnert, Mario Perez Leal, creacion" />
<meta name="keywords" content="frohnert, perez leal, creacion, documentation, dokumentation, phpwcms, cms, opensource, open source, docu" />
<meta name="description" content="A Documentation Project for the  Open Source CMS phpWCMS" />
<meta name="Audience" content="Alle" />
<meta name="Content-language" content="EN" />
<meta name="robots"      content="index,follow" />
<meta name="expires" content="0" />
<meta name="revisit-after" content="7 days" />
<meta name="resource-type" content="document" />
<meta name="distribution" content="Global" />
<meta name="generator" content="PHPWCMS" />
<meta name="verify-v1" content="1ZpxZ7AZsjm7PxjqXQVus0eiUYqOsp5URTJn9q4KNz8=" />
  <!--[if lt IE 7]>
  <style type="text/css">
    body { behavior: url("template/inc_css/specific/csshover2.htc"); }
    img { behavior: url("template/inc_css/specific/pngbehavior.htc"); }
  </style>
  <![endif]-->
</head>
<body id="myid_105">


<!--

	this is the default PDF template
	use it to add additional header or
	footer information or whatever you 
	like to be rendered 

//-->

<div style="width:50%; border:1px solid #0f57a6; padding:10px; margin:10px;">
<p style="margin-bottom:20px;"><img src="./template/img/printlogo.gif" width="255" height="91" alt="" border="0" /></p>

<div id="container"><a name="top" id="top"></a>

		<a name="jump60"></a><!-- 
custom article template to split up the view / entry area for the guestbook
template by oliver@phpwcms-docu.de
===========================================================================
//-->
<div>
<h1 style="margin:0 0 5px 0;">Guestbook</h1>

</div>

<div style="margin:25px 0 0 0;padding:0;" class="spaceBeforeCP"></div>
  <form name="sign_guestbook" action="index.php?id=105,60,1,1,1,4" method="post">  <input type="hidden" name="fc4a25bac54ff498dab69e57d794cd90" value="564031" /></form> 
<table width="100%"  border="0" cellspacing="0" cellpadding="0" style="margin-top:5px;">
  <tr>
    <td><strong><a href="105.60.1.1.1.0.phtml">&laquo;&laquo;</a> <a href="105.60.1.1.1.3.phtml">&laquo;</a></strong> <a href="105.60.1.1.1.2.phtml">3</a>&nbsp;<a href="105.60.1.1.1.3.phtml">4</a>&nbsp;<strong>5</strong>&nbsp;<a href="105.60.1.1.1.5.phtml">6</a>&nbsp;<a href="105.60.1.1.1.6.phtml">7</a> <strong><a href="105.60.1.1.1.5.phtml">&raquo;</a>
        <a href="105.60.1.1.1.42.phtml">&raquo;&raquo;</a></strong></td>
    <td align="right"></td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
</table>

<table width="100%"  border="0" cellspacing="0" cellpadding="2">
  
  
  	  <tr class="tbb">
	  <td width="130" class="tbh"> &nbsp;21 </td>
	  <td align="right" class="tbh">Wrote 2012/10/08 at 14:30&nbsp;</td>
	  </tr>
	  <tr class="tbr">
	  <td class="tbl" valign="top">
	  <strong>Damiao</strong><br /><br />
	  <a href="http://www.facebook.com/profile.php" target="_blank"><img src="template/lang/all/icons/home.gif" width="20" height="21" alt="visit website" border="0" /></a><br />
	  </td>
	  <td valign="top" style="padding:10PX;">sagt:Liebe Frau Stadtmf6we, ich verstehe das zu gut  ich hatte brieets eine Woche vor dem ET das Geffchl, bald zu platzen   jede Bewegung war eine Qual. Bis auf den Tag vor der Geburt, da war ich plf6tzlich total fit und irgendwie energiegeladen. Nachts wachte ich dann auf und hatte alle zehn Minuten Wehen, die ich dann irgendwann auch veratmen mudfte   da war ich mir sicher, dass es losgeht! ~ Von der Eipollf6sung wfcrde ich auch dringend abraten, die Hebamme hat das bei mir gemacht, ohne mich vorher zu fragen oder etwas dazu zu sagen, und dann ging auf einmal alles viel zu schnell  nee, nie wieder. Ich habe mir bei aller Ungeduld immer gesagt: Das Mausekind wird genau dann kommen, wenn es bereit ist. Genauso wird das Mupfelchen das sicherlich auch machen    ~ Ich denk&#039; an Sie, liebe Stadtmf6we, bleiben Sie tapfer. Alles Liebe!</td>
	  </tr>

  
  	  <tr class="tbb">
	  <td width="130" class="tbh"> &nbsp;22 </td>
	  <td align="right" class="tbh">Wrote 2012/10/08 at 07:07&nbsp;</td>
	  </tr>
	  <tr class="tbr">
	  <td class="tbl" valign="top">
	  <strong>Jojo</strong><br /><br />
	  <a href="http://www.facebook.com/profile.php" target="_blank"><img src="template/lang/all/icons/home.gif" width="20" height="21" alt="visit website" border="0" /></a><br />
	  </td>
	  <td valign="top" style="padding:10PX;">ek net net graag se dat hulle absoluut stnuning lyk en dat julle as  n span fantasties is.Ek is regtig geraak deur die fotos en die 2 wondelike mense wat julle afgeneem het. chantalle en corne is vriende van my ean al wat ek kan se is stnuning!!!!</td>
	  </tr>

  
  	  <tr class="tbb">
	  <td width="130" class="tbh"> &nbsp;23 </td>
	  <td align="right" class="tbh">Wrote 2012/10/08 at 03:52&nbsp;</td>
	  </tr>
	  <tr class="tbr">
	  <td class="tbl" valign="top">
	  <strong>&#12458;&#12540;&#12463;&#12522;&#12540; &#12463;&#12525;&#12473;&#12522;&#12531;&#12463;</strong><br /><br />
	  <a href="http://www.oakleymainiti.com" target="_blank"><img src="template/lang/all/icons/home.gif" width="20" height="21" alt="visit website" border="0" /></a><br />
	  <a href="mailto:asdgasdassd@gmail.com"><img src="template/lang/all/icons/mail.gif" width="20" height="21" alt="Write email" border="0" /></a></td>
	  <td valign="top" style="padding:10PX;">sadgasd</td>
	  </tr>

  
  	  <tr class="tbb">
	  <td width="130" class="tbh"> &nbsp;24 </td>
	  <td align="right" class="tbh">Wrote 2012/10/08 at 03:06&nbsp;</td>
	  </tr>
	  <tr class="tbr">
	  <td class="tbl" valign="top">
	  <strong>Yara</strong><br /><br />
	  <a href="http://www.facebook.com/profile.php" target="_blank"><img src="template/lang/all/icons/home.gif" width="20" height="21" alt="visit website" border="0" /></a><br />
	  </td>
	  <td valign="top" style="padding:10PX;">When you think about it, that&#039;s got to be the right awsner.</td>
	  </tr>

  
  	  <tr class="tbb">
	  <td width="130" class="tbh"> &nbsp;25 </td>
	  <td align="right" class="tbh">Wrote 2012/10/08 at 02:24&nbsp;</td>
	  </tr>
	  <tr class="tbr">
	  <td class="tbl" valign="top">
	  <strong>Minnie</strong><br /><br />
	  <a href="http://www.facebook.com/" target="_blank"><img src="template/lang/all/icons/home.gif" width="20" height="21" alt="visit website" border="0" /></a><br />
	  </td>
	  <td valign="top" style="padding:10PX;">Great stuff, you heelpd me out so much!</td>
	  </tr>

</table>

  <form name="sign_guestbook" action="index.php?id=105,60,1,1,1,4" method="post">

			<table border="0" cellspacing="2" cellpadding="2">
			<tr>
			<td valign="top"><label for="guestbook_email">Email *</label></td>
			<td valign="top"><input name="guestbook_email" type="text" id="guestbook_email" class="gbInputField" value="" size="50" maxlength="250" /></td>
			</tr>		
			<tr>	
			<td valign="top"><label for="guestbook_name">Name *</label></td>
			<td valign="top"><input name="guestbook_name" type="text" id="guestbook_name" class="gbInputField" value="" size="50" maxlength="500" /></td>
			</tr>
			<tr>
			<td valign="top"><label for="guestbook_url">Website</label></td>
			<td valign="top"><input name="guestbook_url" type="text" id="guestbook_url" class="gbInputField" value="" size="50" maxlength="1000" /></td>
			</tr>		
			<tr>
			<td valign="top"><label for="guestbook_msg">Message*</label></td>
			<td valign="top"><textarea name="guestbook_msg" cols="50" rows="6" id="guestbook_msg" class="gbInputTextarea"></textarea></td>
			</tr>
			
			<tr>
			<td><label>Email </label></td>
			<td>			
			<input name="guestbook_show" type="radio" value="0" id="guestbook_show0" checked="checked" />
			<label for="guestbook_show0">show</label>
			<input name="guestbook_show" type="radio" value="1" id="guestbook_show1" />
			<label for="guestbook_show1">hide</label>
			<input name="guestbook_show" type="radio" value="2" id="guestbook_show2" />
			<label for="guestbook_show2">display as &quot;info at mail dot de&quot; </label>
			</td>
			</tr>
<!--CAPTCHA_START//-->
			<tr>
			<td>&nbsp;</td>
			<td><br />
				<table width="100%" border="0" cellspacing="0" cellpadding="0">
					<tr>
						<td><label for="guestbook_captcha">read code ...</label></td>
						<td>... enter here</td>
					</tr>
					<tr><td><img src="img/captcha.php?regen=y&amp;length=5&amp;1352854142" alt="Captcha" border="0" id="gbCaptchaImage" /></td>
						<td><input name="guestbook_captcha" type="text" id="guestbook_captcha" class="gbInputFieldCaptcha" value="" size="10" maxlength="10" /></td>
					</tr>
				</table>
			</td>
			</tr>
			<tr><td colspan="2">&nbsp;</td></tr>		
<!--CAPTCHA_END//-->
			<tr>
			<td>&nbsp;</td>
			<td>
			<input name="guestbook_send" class="button" type="submit" id="guestbook_send" value="Sign guestbook" />
			</td>
			</tr>
			</table>
<input type="hidden" name="fc4a25bac54ff498dab69e57d794cd90" value="564032" /></form> 

  


		
</div>
</div><br />
<strong>URL:<a href="deutsche_version.phtml?id=105,60,1,1,1,4" target="_blank">deutsche_version.phtml?id=105,60,1,1,1,4</a></strong>
</body>
</html>