<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<!--
	phpwcms | free open source content management system
	created by Oliver Georgi (oliver at phpwcms dot de) and licensed under GNU/GPL.
	phpwcms is copyright 2003-2007 of Oliver Georgi. Extensions are copyright of
	their respective owners. Visit project page for details: http://www.phpwcms.org/
//-->
<title>Guestbook | Guestbook</title>
  <meta http-equiv="content-type" content="text/html; charset=iso-8859-1" />
  <meta http-equiv="content-style-type" content="text/css" />
  <script src="template/inc_js/frontend.js" type="text/javascript"></script>
  <style type="text/css" media="all">
  <!-- 
    body {
      margin: 0;
      padding-top: 0;
      padding-bottom: 0;
      padding-left: 0;
      padding-right: 0;

    }
  //-->
  </style>
  <style type="text/css">
  <!-- 
    @import url("template/inc_css/print_layout.css");
  //-->
  </style>
<meta name="Title" content="The phpWCMS Documentation" />
<meta name="author" content="Oliver Frohnert, Mario Perez Leal" />
<meta name="Publisher" content="Oliver Frohnert, Mario Perez Leal, creacion" />
<meta name="Copyright" content="Oliver Frohnert, Mario Perez Leal, creacion" />
<meta name="keywords" content="frohnert, perez leal, creacion, documentation, dokumentation, phpwcms, cms, opensource, open source, docu" />
<meta name="description" content="A Documentation Project for the  Open Source CMS phpWCMS" />
<meta name="Audience" content="Alle" />
<meta name="Content-language" content="EN" />
<meta name="robots"      content="index,follow" />
<meta name="expires" content="0" />
<meta name="revisit-after" content="7 days" />
<meta name="resource-type" content="document" />
<meta name="distribution" content="Global" />
<meta name="generator" content="PHPWCMS" />

  <!--[if lt IE 7]>
  <style type="text/css">
    body { behavior: url("template/inc_css/specific/csshover2.htc"); }
    img { behavior: url("template/inc_css/specific/pngbehavior.htc"); }
  </style>
  <![endif]-->
</head>
<body id="myid_105">


<!--

	this is the default PDF template
	use it to add additional header or
	footer information or whatever you 
	like to be rendered 

//-->

<div style="width:50%; border:1px solid #0f57a6; padding:10px; margin:10px;">
<p style="margin-bottom:20px;"><img src="./template/img/printlogo.gif" width="255" height="91" alt="" border="0" /></p>

<div id="container"><a name="top" id="top"></a>

		<a name="jump60"></a><!-- 
custom article template to split up the view / entry area for the guestbook
template by oliver@phpwcms-docu.de
===========================================================================
//-->
<div>
<h1 style="margin:0 0 5px 0;">Guestbook</h1>

</div>

<div style="margin:25px 0 0 0;padding:0;" class="spaceBeforeCP"></div>
   
<table width="100%"  border="0" cellspacing="0" cellpadding="0" style="margin-top:5px;">
  <tr>
    <td><strong><a href="105.60.1.1.1.0.phtml">&laquo;&laquo;</a> <a href="105.60.1.1.1.8.phtml">&laquo;</a></strong> <a href="105.60.1.1.1.7.phtml">8</a>&nbsp;<a href="105.60.1.1.1.8.phtml">9</a>&nbsp;<strong>10</strong>&nbsp;<a href="105.60.1.1.1.10.phtml">11</a>&nbsp;<a href="105.60.1.1.1.11.phtml">12</a> <strong><a href="105.60.1.1.1.10.phtml">&raquo;</a>
        <a href="105.60.1.1.1.26.phtml">&raquo;&raquo;</a></strong></td>
    <td align="right"></td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
</table>

<table width="100%"  border="0" cellspacing="0" cellpadding="2">
  
  
  	  <tr class="tbb">
	  <td width="130" class="tbh"> &nbsp;46 </td>
	  <td align="right" class="tbh">Wrote 2009/08/22 at 09:17&nbsp;</td>
	  </tr>
	  <tr class="tbr">
	  <td class="tbl" valign="top">
	  <strong>Martina</strong><br /><br />
	  <a href="http://www.singles-singles.net" target="_blank"><img src="template/lang/all/icons/home.gif" width="20" height="21" alt="visit website" border="0" /></a><br />
	  <a href="mailto:tramail@web.de"><img src="template/lang/all/icons/mail.gif" width="20" height="21" alt="Write email" border="0" /></a></td>
	  <td valign="top" style="padding:10PX;">tramail@web.de<br />
<br />
Weiterso !<br />
<br />
Ich finde es ist eine gelungene Homepage<br />
sehr schön gestaltet und informativ,<br />
liebe Grüsse aus Hamburg<br />
Martina von <br />
http://www.singles-singles.net und <br />
http://www.einsameherzen.net</td>
	  </tr>

  
  	  <tr class="tbb">
	  <td width="130" class="tbh"> &nbsp;47 </td>
	  <td align="right" class="tbh">Wrote 2009/08/13 at 21:08&nbsp;</td>
	  </tr>
	  <tr class="tbr">
	  <td class="tbl" valign="top">
	  <strong>Martina</strong><br /><br />
	  <a href="http://www.singles-singles.net" target="_blank"><img src="template/lang/all/icons/home.gif" width="20" height="21" alt="visit website" border="0" /></a><br />
	  <a href="mailto:tramail@web.de"><img src="template/lang/all/icons/mail.gif" width="20" height="21" alt="Write email" border="0" /></a></td>
	  <td valign="top" style="padding:10PX;">Gut gelungene Homepage - weiterso !<br />
<br />
Liebe Grüsse sendet Euch Martina von www.singles-singles.net</td>
	  </tr>

  
  	  <tr class="tbb">
	  <td width="130" class="tbh"> &nbsp;48 </td>
	  <td align="right" class="tbh">Wrote 2009/08/13 at 10:50&nbsp;</td>
	  </tr>
	  <tr class="tbr">
	  <td class="tbl" valign="top">
	  <strong>Heinz Oberdanne</strong><br /><br />
	  <a href="http://www.xxx-restposten.de" target="_blank"><img src="template/lang/all/icons/home.gif" width="20" height="21" alt="visit website" border="0" /></a><br />
	  <a href="mailto:oberdanne@gmx.de"><img src="template/lang/all/icons/mail.gif" width="20" height="21" alt="Write email" border="0" /></a></td>
	  <td valign="top" style="padding:10PX;">Vielen Dank für die tolle Seite. Die Tips und Hilfen haben mir echt geholfen.<br />
<br />
Lieben Gruss <br />
Heinz aus Bremen</td>
	  </tr>

  
  	  <tr class="tbb">
	  <td width="130" class="tbh"> &nbsp;49 </td>
	  <td align="right" class="tbh">Wrote 2009/07/31 at 08:47&nbsp;</td>
	  </tr>
	  <tr class="tbr">
	  <td class="tbl" valign="top">
	  <strong>Sabie</strong><br /><br />
	  
	  </td>
	  <td valign="top" style="padding:10PX;">danke für die tolle doku zum cms, hat mir sehr geholfen.</td>
	  </tr>

  
  	  <tr class="tbb">
	  <td width="130" class="tbh"> &nbsp;50 </td>
	  <td align="right" class="tbh">Wrote 2009/07/15 at 20:20&nbsp;</td>
	  </tr>
	  <tr class="tbr">
	  <td class="tbl" valign="top">
	  <strong>Patrick</strong><br /><br />
	  
	  info at maus-tastatur dot de</td>
	  <td valign="top" style="padding:10PX;">Hallo probier gerade rum - danke für die Doku - liebe grüsse Patrick</td>
	  </tr>

</table>

   

  


		
</div>
</div><br />
<strong>URL:<a href="deutsche_version.phtml?id=105,60,1,1,1,9" target="_blank">deutsche_version.phtml?id=105,60,1,1,1,9</a></strong>
</body>
</html>