<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<!--
	phpwcms | free open source content management system
	created by Oliver Georgi (oliver at phpwcms dot de) and licensed under GNU/GPL.
	phpwcms is copyright 2003-2006 of Oliver Georgi. Extensions are copyright of\
	their respective owners. Visit project page for details: http://www.phpwcms.org/
//-->
<title></title>
  <meta http-equiv="content-type" content="text/html; charset=iso-8859-1" />
  <meta http-equiv="content-style-type" content="text/css" />
  <script src="template/inc_js/frontend.js" type="text/javascript"></script>
  <style type="text/css" media="all">
  /* <![CDATA[ */
    body {
      margin: 0;
      padding-top: 0;
      padding-bottom: 0;
      padding-left: 0;
      padding-right: 0;

    }
  /* ]]> */
  </style>
  <style type="text/css">
  /* <![CDATA[ */
    @import url("template/inc_css/frontend.css");
    @import url("template/inc_css/nlu_navi1_docu.css");
    @import url("template/inc_css/print_layout.css");
  /* ]]> */
  </style>
<script src="http://www.google-analytics.com/urchin.js" type="text/javascript">
</script>
<script type="text/javascript">
_uacct = "UA-361662-1";
urchinTracker();
</script>
<META NAME="Title" CONTENT="The phpWCMS Documentation">
<meta name="author" content="Oliver Frohnert">
<meta name="Publisher" content="Oliver Frohnert">
<meta name="Copyright" content="Oliver Frohnert">
<meta name="keywords" content="frohnert,documentation, dokumentation, phpwcms, cms. opensource, open source">
<meta name="description" content="A Documentation Project for the  Open Source CMS phpWCMS">
<meta name="Audience" content="Alle">
<meta name="Content-language" content="EN">
<META NAME="robots"      CONTENT="index,follow">
<META NAME="expires" CONTENT="0">
<meta name="revisit-after" content="7 days">
<meta name="resource-type" content="document">
<meta name="distribution" content="Global">
<meta name="generator" content="PHPWCMS">
<META name="verify-v1" content="1ZpxZ7AZsjm7PxjqXQVus0eiUYqOsp5URTJn9q4KNz8=" />
  <!--[if lt IE 7]>
  <style type="text/css">
    body { behavior: url("template/inc_css/specific/csshover2.htc"); }
    img { behavior: url("template/inc_css/specific/pngbehavior.htc"); }
  </style>
  <![endif]-->
</head>
<body>
<img src="img/leer.gif" border="0" width="10" height="1" alt="" />
<br />
<a href="english_version.phtml">English</a> <span class="breadcrumb_spacer">&gt;</span> <a href="contact.phtml">Contact</a> <span class="breadcrumb_spacer">&gt;</span> Guestbook
<br />
<HR>
<br />
<a name="jump60"></a><h1>Guestbook</h1><div style="margin:25px 0 0 0; padding:0 0 0 0; clear:both;"></div>
  <form name="sign_guestbook" action="deutsche_version.phtml?id=105,60,1,1,1,77" method="post">
<table border="0" align="center" cellpadding="1" cellspacing="0" bgcolor="#F5F5F5" style="margin-bottom:10px;">
  <tr bgcolor="#E1E1E1">
    <td colspan="2"><strong>&nbsp;&nbsp;sign my guestbook</strong> <span style="font-size:10px;color:#CC3300;">(fields
        marked * are obligatory)</span></td>
  </tr>
  <tr bgcolor="#E1E1E1">
    <td colspan="2"><img src="img/leer.gif" width="1" height="1" alt="" /></td>
  </tr>
  
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
  <tr>
    <td align="right" class="v10">email<span style="color:#CC3300;">*</span>:&nbsp;</td>
    <td><input name="guestbook_email" type="text" id="guestbook_email" style="width: 350px" class="v12" value="" size="50" maxlength="250" />&nbsp;</td>
  </tr>
  <tr>
    <td align="right" class="v10">name<span style="color:#CC3300;">*</span>:&nbsp;</td>
    <td><input name="guestbook_name" type="text" id="guestbook_name" style="width: 350px" class="v12" value=""  size="50" maxlength="500" /></td>
  </tr>
  <tr>
    <td align="right" class="v10">website:&nbsp;</td>
    <td><input name="guestbook_url" type="text" id="guestbook_url" style="width: 350px" class="v12" value="" size="50" maxlength="1000" /></td>
  </tr>
  <tr>
    <td align="right" valign="top" class="v10">&nbsp;&nbsp;message:&nbsp;</td>
    <td><textarea name="guestbook_msg" cols="50" rows="6" id="guestbook_msg" class="v12" style="width: 350px"></textarea></td>
  </tr>
  <tr>
    <td align="right" valign="top" class="v10">display:&nbsp;</td>
    <td><input name="guestbook_show" type="radio" value="0" checked>show email<br /><input name="guestbook_show" type="radio" value="1">hide email<br /><input type="radio" name="guestbook_show" value="2">show email as &quot;info at mail dot com&quot;</td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="4" alt="" /></td>
  </tr>
  <tr>
  	<td align="right" class="v10">code<span style="color:#CC3300;">*</span>:&nbsp;</td>
  	<td><table cellpadding="0" cellspacing="0" border="0">
		<tr>
			<td><input name="guestbook_captcha" type="text" id="guestbook_captcha" style="width: 100px" class="v12" value="" size="10" maxlength="10" />&nbsp;&nbsp;</td>
			<td><img src="img/captcha.php?regen=y&amp;1172205342" alt="Captcha" border="0" /></td>
		</tr>
		</table></td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="10" alt="" /></td>
  </tr>
  <tr>
    <td align="right">&nbsp;</td>
    <td><input name="guestbook_send" type="submit" id="guestbook_send" value="sign guestbook" class="v11" /></td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="6" alt="" /></td>
  </tr>
</table>
<input type="hidden" name="365c36ca552b6eda764bfb03d06b0f82" value="60211" /></form> 
<table width="100%"  border="0" cellspacing="0" cellpadding="0" style="margin-top:5px;">
  <tr>
    <td><strong><a href="105.60.1.1.1.0.phtml">&lt;&lt;</a> <a href="105.60.1.1.1.76.phtml">&lt;</a></strong> <a href="105.60.1.1.1.75.phtml">76</a>&nbsp;<a href="105.60.1.1.1.76.phtml">77</a>&nbsp;<strong>78</strong>&nbsp;<a href="105.60.1.1.1.78.phtml">79</a>&nbsp;<a href="105.60.1.1.1.79.phtml">80</a> <strong><a href="105.60.1.1.1.78.phtml">&gt;</a>
        <a href="105.60.1.1.1.85.phtml">&gt;&gt;</a></strong></td>
    <td align="right"><form name="guestbookarchive" id="guestbookarchive" method="post" action="index.php?id=105,60,1,1,1,77"><select name="showarchive" id="showarchive" onchange="document.guestbookarchive.submit();"><option value="">all entries</option>
<option value="2007/02">2007/02</option>
<option value="2007/01">2007/01</option>
<option value="2006/10">2006/10</option>
<option value="2006/03">2006/03</option>
<option value="2006/02">2006/02</option>
<option value="2006/01">2006/01</option>
<option value="2005/12">2005/12</option>
<option value="2005/11">2005/11</option>
<option value="2005/10">2005/10</option>
<option value="2005/09">2005/09</option>
<option value="2005/08">2005/08</option>
<option value="2005/07">2005/07</option>
<option value="2005/06">2005/06</option>
<option value="2005/05">2005/05</option>
<option value="2005/03">2005/03</option>
<option value="2005/02">2005/02</option>
<option value="2005/01">2005/01</option>
<option value="2004/12">2004/12</option>
<option value="2004/11">2004/11</option>
<option value="2004/10">2004/10</option>
<option value="2004/09">2004/09</option>
<option value="2004/08">2004/08</option>
</select><input type="hidden" name="archivedate" value="%Y/%m" />&nbsp;<input name="archivesubmit" class="guestbookArchiveSubmit" type="submit" value="go" /></form>&nbsp;<form name="guestbookjump" id="guestbookjump" method="post" action="index.php?id=105,60,1,1,1,77"><select name="showguestbookpage" id="showpage" onchange="document.guestbookjump.submit();"><option value="1">page
      1</option>
<option value="2">page
      2</option>
<option value="3">page
      3</option>
<option value="4">page
      4</option>
<option value="5">page
      5</option>
<option value="6">page
      6</option>
<option value="7">page
      7</option>
<option value="8">page
      8</option>
<option value="9">page
      9</option>
<option value="10">page
      10</option>
<option value="11">page
      11</option>
<option value="12">page
      12</option>
<option value="13">page
      13</option>
<option value="14">page
      14</option>
<option value="15">page
      15</option>
<option value="16">page
      16</option>
<option value="17">page
      17</option>
<option value="18">page
      18</option>
<option value="19">page
      19</option>
<option value="20">page
      20</option>
<option value="21">page
      21</option>
<option value="22">page
      22</option>
<option value="23">page
      23</option>
<option value="24">page
      24</option>
<option value="25">page
      25</option>
<option value="26">page
      26</option>
<option value="27">page
      27</option>
<option value="28">page
      28</option>
<option value="29">page
      29</option>
<option value="30">page
      30</option>
<option value="31">page
      31</option>
<option value="32">page
      32</option>
<option value="33">page
      33</option>
<option value="34">page
      34</option>
<option value="35">page
      35</option>
<option value="36">page
      36</option>
<option value="37">page
      37</option>
<option value="38">page
      38</option>
<option value="39">page
      39</option>
<option value="40">page
      40</option>
<option value="41">page
      41</option>
<option value="42">page
      42</option>
<option value="43">page
      43</option>
<option value="44">page
      44</option>
<option value="45">page
      45</option>
<option value="46">page
      46</option>
<option value="47">page
      47</option>
<option value="48">page
      48</option>
<option value="49">page
      49</option>
<option value="50">page
      50</option>
<option value="51">page
      51</option>
<option value="52">page
      52</option>
<option value="53">page
      53</option>
<option value="54">page
      54</option>
<option value="55">page
      55</option>
<option value="56">page
      56</option>
<option value="57">page
      57</option>
<option value="58">page
      58</option>
<option value="59">page
      59</option>
<option value="60">page
      60</option>
<option value="61">page
      61</option>
<option value="62">page
      62</option>
<option value="63">page
      63</option>
<option value="64">page
      64</option>
<option value="65">page
      65</option>
<option value="66">page
      66</option>
<option value="67">page
      67</option>
<option value="68">page
      68</option>
<option value="69">page
      69</option>
<option value="70">page
      70</option>
<option value="71">page
      71</option>
<option value="72">page
      72</option>
<option value="73">page
      73</option>
<option value="74">page
      74</option>
<option value="75">page
      75</option>
<option value="76">page
      76</option>
<option value="77">page
      77</option>
<option value="78" selected="selected">page
      78</option>
<option value="79">page
      79</option>
<option value="80">page
      80</option>
<option value="81">page
      81</option>
<option value="82">page
      82</option>
<option value="83">page
      83</option>
<option value="84">page
      84</option>
<option value="85">page
      85</option>
<option value="86">page
      86</option>
</select>&nbsp;<input name="jumpsubmit" class="guestbookJumpSubmit" type="submit" value="go" /></form></td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
</table>

<table width="100%"  border="0" cellspacing="0" cellpadding="2">
  
  <tr bgcolor="#F5F5F5">
    <td width="99%">386 | 01/12/2005 11:28</td>
  </tr>
  <tr>
    <td colspan="2"><strong>Charles Coleman</strong>  <br />
      Your site design is impeccable.  Keep up the good work!</td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
  
  <tr bgcolor="#F5F5F5">
    <td width="99%">387 | 01/07/2005 12:31</td>
  </tr>
  <tr>
    <td colspan="2"><strong>Andrusch</strong> <a href="http://analogfotografie.de" target="_blank">visit
      website</a> andreas.broemme at web  dot de<br />
      Hallo, habe diese Seite schon sooft besucht, weil ich immer wissen will, was es neues hier gibt. Außerdem kenne ich den BEtreiber ganz gut. Also erstmal ein dickes fettes Lob an alle Macher dieser Doku-Seite. Das bekommt ihr echt toll hin und ich hoffe, ihr macht weiter so. Von dieser Doku-Seite kann sich manch ein CMS mal was abschneiden. <br />
<br />
ICh freue mich auch endlich auf die VErsion 2 und hoffe - zwinker zu OliG - du hast sie bald online. ICh warte gespannt. <br />
<br />
Greetz from BErlin<br />
<br />
Andrusch</td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
  
  <tr bgcolor="#F5F5F5">
    <td width="99%">388 | 01/06/2005 16:20</td>
  </tr>
  <tr>
    <td colspan="2"><strong>bons</strong> <a href="http://bonstronics.com" target="_blank">visit
      website</a> <br />
      Very great resource. Very timely and informative.<br />
<br />
<span style="color:#00CC00;"> edit by Oliver &quot;Pappnase&quot; Frohnert, This is not the Support Forum! So please stop to post Questions. The forum is here http://www.phpwcms.de/forum</span></td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
  
  <tr bgcolor="#F5F5F5">
    <td width="99%">389 | 01/02/2005 23:29</td>
  </tr>
  <tr>
    <td colspan="2"><strong>Markus Kösters</strong> <a href="http://www.musicstar.de" target="_blank">visit
      website</a> Markus.koesters at web  dot de<br />
      Hallo,<br />
<br />
zuerst mal möchte ich euch allen ein frohes neues Jahr wünschen.<br />
Ich möchte einfach mal die Gelegenheit nutzen und allen die an der Entwicklung von phpwcms und dem ganzen drum herum (Doku, etc.) beteiligt sind, zu danken.<br />
Was Ihr hier mal wieder auf die Beine gestellt habt, ist echt großartig.<br />
Macht Bitte weiter so.<br />
<br />
Mittlerweile habe ich einige CMS Systeme ausprobiert, und zur Zeit gehört phpwcms zu meinen Faves, da man wirklich sehr viele Freiheiten hat.<br />
Ich bin mächtig gespannt auf die Version2.<br />
<br />
Grüße Markus</td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
  
  <tr bgcolor="#F5F5F5">
    <td width="99%">390 | 12/29/2004 18:26</td>
  </tr>
  <tr>
    <td colspan="2"><strong>Malte Zugermeier</strong> <a href="http://www.zugermeier.de" target="_blank">visit
      website</a> <br />
      Echt klasse, dass es jetzt auch eine deutsche Anleitung zu phpwcms gibt!</td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
  
</table>

<table width="100%"  border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td colspan="2"><HR></td>
  </tr>
  <tr>
    <td width="50%">Article created: 2004/08/17</td>
    <td align="right" width="50%">Last Changes: 2006/06/06</td>
  </tr>
  <tr>
    <td colspan="2">&nbsp;</td>
  </tr>
  <tr>
    <td colspan="2" class="comment">In case you find any mistakes or have enhancments, please use this <a href="#" onClick="javascript:window.open('./content/pages/message.htm','frage','width=400, height=250, screenX=440,screenY=200,menubar=no,statusbar=yes,scrollbar=yes,resizable=no');" target="" style="max-width:148px; overflow:hidden;"><u>form</u></a> .<br /><br />
Have you found this website a helpful resource in understanding the Phpwcms content management system? If so, would you consider making a donation?  Please click here: <a href="#paypal">PayPal</a>. We welcome any donation amount. Your contribution helps make this website an even better resource and helps underwrite the associated server expenses of accomodating a growing number of visitors.<br />
This page use the version:</td>
  </tr>
  <tr>

    <td colspan="2"><img src="img/leer.gif" border="0" width="10" height="10" alt="" /></td>
  </tr>
</table>

</body>
</html>