<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<!--
	phpwcms | free open source content management system
	created by Oliver Georgi (oliver at phpwcms dot de) and licensed under GNU/GPL.
	phpwcms is copyright 2003-2006 of Oliver Georgi. Extensions are copyright of\
	their respective owners. Visit project page for details: http://www.phpwcms.org/
//-->
<title></title>
  <meta http-equiv="content-type" content="text/html; charset=iso-8859-1" />
  <meta http-equiv="content-style-type" content="text/css" />
  <script src="template/inc_js/frontend.js" type="text/javascript"></script>
  <style type="text/css" media="all">
  /* <![CDATA[ */
    body {
      margin: 0;
      padding-top: 0;
      padding-bottom: 0;
      padding-left: 0;
      padding-right: 0;

    }
  /* ]]> */
  </style>
  <style type="text/css">
  /* <![CDATA[ */
    @import url("template/inc_css/frontend.css");
    @import url("template/inc_css/nlu_navi1_docu.css");
    @import url("template/inc_css/print_layout.css");
  /* ]]> */
  </style>


<META NAME="Title" CONTENT="The phpWCMS Documentation">
<meta name="author" content="Oliver Frohnert">
<meta name="Publisher" content="Oliver Frohnert">
<meta name="Copyright" content="Oliver Frohnert">
<meta name="keywords" content="frohnert,documentation, dokumentation, phpwcms, cms. opensource, open source">
<meta name="description" content="A Documentation Project for the  Open Source CMS phpWCMS">
<meta name="Audience" content="Alle">
<meta name="Content-language" content="EN">
<META NAME="robots"      CONTENT="index,follow">
<META NAME="expires" CONTENT="0">
<meta name="revisit-after" content="7 days">
<meta name="resource-type" content="document">
<meta name="distribution" content="Global">
<meta name="generator" content="PHPWCMS">

  <!--[if lt IE 7]>
  <style type="text/css">
    body { behavior: url("template/inc_css/specific/csshover2.htc"); }
    img { behavior: url("template/inc_css/specific/pngbehavior.htc"); }
  </style>
  <![endif]-->
</head>
<body>
<img src="img/leer.gif" border="0" width="10" height="1" alt="" />
<br />
<a href="english_version.phtml">English</a> <span class="breadcrumb_spacer">&gt;</span> <a href="contact.phtml">Contact</a> <span class="breadcrumb_spacer">&gt;</span> Guestbook
<br />
<HR>
<br />
<a name="jump60"></a><h1>Guestbook</h1><div style="margin:25px 0 0 0; padding:0 0 0 0; clear:both;"></div>
   
<table width="100%"  border="0" cellspacing="0" cellpadding="0" style="margin-top:5px;">
  <tr>
    <td><strong><a href="105.60.1.1.1.0.phtml">&lt;&lt;</a> <a href="105.60.1.1.1.105.phtml">&lt;</a></strong> <a href="105.60.1.1.1.104.phtml">105</a>&nbsp;<a href="105.60.1.1.1.105.phtml">106</a>&nbsp;<strong>107</strong>&nbsp;<a href="105.60.1.1.1.107.phtml">108</a>&nbsp;<a href="105.60.1.1.1.108.phtml">109</a> <strong><a href="105.60.1.1.1.107.phtml">&gt;</a>
        <a href="105.60.1.1.1.109.phtml">&gt;&gt;</a></strong></td>
    <td align="right">&nbsp;<form name="guestbookjump" id="guestbookjump" method="post" action="index.php?id=105,60,1,1,1,106"><select name="showguestbookpage" id="showpage" onchange="document.guestbookjump.submit();"><option value="1">page
      1</option>
<option value="2">page
      2</option>
<option value="3">page
      3</option>
<option value="4">page
      4</option>
<option value="5">page
      5</option>
<option value="6">page
      6</option>
<option value="7">page
      7</option>
<option value="8">page
      8</option>
<option value="9">page
      9</option>
<option value="10">page
      10</option>
<option value="11">page
      11</option>
<option value="12">page
      12</option>
<option value="13">page
      13</option>
<option value="14">page
      14</option>
<option value="15">page
      15</option>
<option value="16">page
      16</option>
<option value="17">page
      17</option>
<option value="18">page
      18</option>
<option value="19">page
      19</option>
<option value="20">page
      20</option>
<option value="21">page
      21</option>
<option value="22">page
      22</option>
<option value="23">page
      23</option>
<option value="24">page
      24</option>
<option value="25">page
      25</option>
<option value="26">page
      26</option>
<option value="27">page
      27</option>
<option value="28">page
      28</option>
<option value="29">page
      29</option>
<option value="30">page
      30</option>
<option value="31">page
      31</option>
<option value="32">page
      32</option>
<option value="33">page
      33</option>
<option value="34">page
      34</option>
<option value="35">page
      35</option>
<option value="36">page
      36</option>
<option value="37">page
      37</option>
<option value="38">page
      38</option>
<option value="39">page
      39</option>
<option value="40">page
      40</option>
<option value="41">page
      41</option>
<option value="42">page
      42</option>
<option value="43">page
      43</option>
<option value="44">page
      44</option>
<option value="45">page
      45</option>
<option value="46">page
      46</option>
<option value="47">page
      47</option>
<option value="48">page
      48</option>
<option value="49">page
      49</option>
<option value="50">page
      50</option>
<option value="51">page
      51</option>
<option value="52">page
      52</option>
<option value="53">page
      53</option>
<option value="54">page
      54</option>
<option value="55">page
      55</option>
<option value="56">page
      56</option>
<option value="57">page
      57</option>
<option value="58">page
      58</option>
<option value="59">page
      59</option>
<option value="60">page
      60</option>
<option value="61">page
      61</option>
<option value="62">page
      62</option>
<option value="63">page
      63</option>
<option value="64">page
      64</option>
<option value="65">page
      65</option>
<option value="66">page
      66</option>
<option value="67">page
      67</option>
<option value="68">page
      68</option>
<option value="69">page
      69</option>
<option value="70">page
      70</option>
<option value="71">page
      71</option>
<option value="72">page
      72</option>
<option value="73">page
      73</option>
<option value="74">page
      74</option>
<option value="75">page
      75</option>
<option value="76">page
      76</option>
<option value="77">page
      77</option>
<option value="78">page
      78</option>
<option value="79">page
      79</option>
<option value="80">page
      80</option>
<option value="81">page
      81</option>
<option value="82">page
      82</option>
<option value="83">page
      83</option>
<option value="84">page
      84</option>
<option value="85">page
      85</option>
<option value="86">page
      86</option>
<option value="87">page
      87</option>
<option value="88">page
      88</option>
<option value="89">page
      89</option>
<option value="90">page
      90</option>
<option value="91">page
      91</option>
<option value="92">page
      92</option>
<option value="93">page
      93</option>
<option value="94">page
      94</option>
<option value="95">page
      95</option>
<option value="96">page
      96</option>
<option value="97">page
      97</option>
<option value="98">page
      98</option>
<option value="99">page
      99</option>
<option value="100">page
      100</option>
<option value="101">page
      101</option>
<option value="102">page
      102</option>
<option value="103">page
      103</option>
<option value="104">page
      104</option>
<option value="105">page
      105</option>
<option value="106">page
      106</option>
<option value="107" selected="selected">page
      107</option>
<option value="108">page
      108</option>
<option value="109">page
      109</option>
<option value="110">page
      110</option>
</select>&nbsp;<input name="jumpsubmit" class="guestbookJumpSubmit" type="submit" value="go" /></form></td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
</table>

<table width="100%"  border="0" cellspacing="0" cellpadding="2">
  
  <tr bgcolor="#F5F5F5">
    <td width="99%">531 | 09/22/2004 20:57</td>
  </tr>
  <tr>
    <td colspan="2"><a href="mailto:robert@headshake.nl"><strong>robert</strong></a> <a href="http://www.headshake.nl" target="_blank">visit
      website</a> robert@headshake.nl<br />
      Only wanna say GREAT job GREAT cms! <br />
(stimulating_comments) :)</td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
  
  <tr bgcolor="#F5F5F5">
    <td width="99%">532 | 09/17/2004 00:30</td>
  </tr>
  <tr>
    <td colspan="2"><strong>Kelley Law</strong> <a href="http://www.wireless-living.net" target="_blank">visit
      website</a> kelleylaw at mac  dot com<br />
      Great work! I am so glad to see such a well defind manual. The only down side is that you might see less of me on the support forum. :-)</td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
  
  <tr bgcolor="#F5F5F5">
    <td width="99%">533 | 09/15/2004 02:23</td>
  </tr>
  <tr>
    <td colspan="2"><strong>Torsten Goltz</strong> <a href="http://www.taog.de" target="_blank">visit
      website</a> info at taog  dot de<br />
      Jungens, gute Software :D Ich stelle gerade meine eigene Seite auf das CMS um und habe nach einigen Startschwierigkeiten nun doch den Faden gefunden.<br />
<br />
Es wäre toll, wenn bei der Installation eine Bsp. Seite voranden wäre. so kann man sich mal einlesen. Das die Daten in der MySQL Datenbank nicht vorhanden seinen können ist klar. Was ich meine ist eine Grundversion von den Templates etc.<br />
Das wird bestimmt schon in irgend einer Form gemacht, aber das war der Grund warum mein Start sich etwas herraus zögerte :)</td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
  
  <tr bgcolor="#F5F5F5">
    <td width="99%">534 | 09/14/2004 15:39</td>
  </tr>
  <tr>
    <td colspan="2"><strong>Isac</strong>  as1528734 at sapo  dot pt<br />
      Hi,<br />
<br />
A lot of work you guys have here and very usefull too. I would like to sugest a new section, tips &amp; tricks. Maybe there isn&#039;t to much tricks and tips at all... ;-)<br />
<br />
Best regards,<br />
Isac.<br />
<br />
<span style="color:#00CC00;">hello isac, thanks for your entry. and an tips and tricks section is planned. but at the monent there  the layout and templtes the more important thing! but as i say i will come. kind regards Oliver &quot;Pappnase&quot;</span></td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
  
  <tr bgcolor="#F5F5F5">
    <td width="99%">535 | 09/13/2004 11:54</td>
  </tr>
  <tr>
    <td colspan="2"><a href="mailto:jswnz@xtra.co.nz"><strong>John</strong></a>  jswnz@xtra.co.nz<br />
      I find myself coming here often....a great reference for a great cms. Thanks Pappnase and Thanks OliverG!</td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
  
</table>

<table width="100%"  border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td colspan="2"><HR></td>
  </tr>
  <tr>
    <td width="50%">Article created: 2004/08/17</td>
    <td align="right" width="50%">Last Changes: 2006/06/06</td>
  </tr>
  <tr>
    <td colspan="2">&nbsp;</td>
  </tr>
  <tr>
    <td colspan="2" class="comment">In case you find any mistakes or have enhancments, please use this <a href="#" onClick="javascript:window.open('./content/pages/message.htm','frage','width=400, height=250, screenX=440,screenY=200,menubar=no,statusbar=yes,scrollbar=yes,resizable=no');" target="" style="max-width:148px; overflow:hidden;"><u>form</u></a> .<br /><br />
Have you found this website a helpful resource in understanding the Phpwcms content management system? If so, would you consider making a donation?  Please click here: <a href="#paypal">PayPal</a>. We welcome any donation amount. Your contribution helps make this website an even better resource and helps underwrite the associated server expenses of accomodating a growing number of visitors.<br />
This page use the version:</td>
  </tr>
  <tr>

    <td colspan="2"><img src="img/leer.gif" border="0" width="10" height="10" alt="" /></td>
  </tr>
</table>

</body>
</html>