<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<!--
	phpwcms | free open source content management system
	created by Oliver Georgi (oliver at phpwcms dot de) and licensed under GNU/GPL.
	phpwcms is copyright 2003-2007 of Oliver Georgi. Extensions are copyright of
	their respective owners. Visit project page for details: http://www.phpwcms.org/
//-->
<title>phpwcms documentation | Guestbook | Guestbook</title>
  <meta http-equiv="content-type" content="text/html; charset=iso-8859-1" />
  <meta http-equiv="content-style-type" content="text/css" />
  <script src="template/inc_js/frontend.js" type="text/javascript"></script>
  <style type="text/css" media="all">
  <!-- 
    body {
      margin: 0;
      padding-top: 0;
      padding-bottom: 0;
      padding-left: 0;
      padding-right: 0;

      background-color: #FFFFFF;
      color: #000000;
    }
    a, a:link, a:active, a:visited, a:hover { color: #FF9900; }
    a:visited { color: #FF9900; }
    a:active { color: #FF9900; }
  //-->
  </style>
  <style type="text/css">
  <!-- 
    @import url("template/inc_css/frontend.css");
    @import url("template/inc_css/nlu_navi1_docu.css");
  //-->
  </style>


<META NAME="Title" CONTENT="The phpWCMS Documentation">
<meta name="author" content="Oliver Frohnert">
<meta name="Publisher" content="Oliver Frohnert">
<meta name="Copyright" content="Oliver Frohnert">
<meta name="keywords" content="frohnert,documentation, dokumentation, phpwcms, cms. opensource, open source">
<meta name="description" content="A Documentation Project for the  Open Source CMS phpWCMS">
<meta name="Audience" content="Alle">
<meta name="Content-language" content="EN">
<META NAME="robots"      CONTENT="index,follow">
<META NAME="expires" CONTENT="0">
<meta name="revisit-after" content="7 days">
<meta name="resource-type" content="document">
<meta name="distribution" content="Global">
<meta name="generator" content="PHPWCMS">

  <!--[if lt IE 7]>
  <style type="text/css">
    body { behavior: url("template/inc_css/specific/csshover2.htc"); }
    img { behavior: url("template/inc_css/specific/pngbehavior.htc"); }
  </style>
  <![endif]-->
</head>
<body>
<table border="0" cellspacing="0" cellpadding="0" width="760" bgcolor="#ffffff" class="maintable" align="center" summary="">
<tr>
<td colspan="2" style="height:60px;"  bgcolor="#ffffff"><a name="top"></a><table width="760" height="135" border="0" cellpadding="0" cellspacing="0">
  <tr valign="top">
    <td width="1334" height="122" colspan="6"><IMG src="/template/lang/en/header.jpg" alt="" border="0"></td>
  </tr>
  <tr>
	<td height="27" background="template/lang/all/top_menu.jpg"><table width="570" border="0" align="left" cellpadding="0" cellspacing="0">
      <tr>
        <td align="center" width="254"><a href="deutsche_version.phtml"><img src="picture/flags/de.gif" width="16" height="10" hspace="10" border="0"  alt="Deutsche Version" title="Deutsche Version"></a>
<a href="english_version.phtml"><img src="picture/flags/gb.gif" width="16" height="10" hspace="10" border="0"  alt="English Version" title="English Version"></a></td>
        <td valign="middle"><div align="center"><a href="replacement_tags_en.phtml"><img src="content/gt/8c10fcb16c44a7b9c26a5a932c5e4ae9.png" alt="Replacement Tags" title="Replacement Tags" width="115" height="13" border="0" /></a></div></td>
        <td width="30" valign="middle"><div align="center"><img src="template/lang/all/sep.gif" width="5" height="5" border="0"></div></td>
        <td valign="middle"><div align="center"><a href="content_parts_en.phtml"><img src="content/gt/02725c45a346fbf433a4c83e02d8dc5a.png" alt="Content Parts" title="Content Parts" width="94" height="13" border="0" /></a></div></td>
        <td width="30" valign="middle"><div align="center"><img src="template/lang/all/sep.gif" width="5" height="5" border="0"></div></td>
        <td valign="middle"><div align="center"><a href="links_de.phtml"><img src="content/gt/2c41bfb28d6dd3d4bbc8bb7688fd62ee.png" alt="Links" title="Links" width="36" height="13" border="0" /></a></div></td>
        <td width="30" valign="middle"><div align="center"><img src="template/lang/all/sep.gif" width="5 " height="5" border="0"></div></td>
        <td valign="middle"><div align="center"><a href="imprint.phtml"><img src="content/gt/8b40044a8de89d790c10c1671094a297.png" alt="Imprint" title="Imprint" width="48" height="13" border="0" /></a></div></td>
     </tr>
    </table>    </td>
  </tr>
</table></td>
</tr>
<tr>
<td valign="top" width="185" style="background-image:url(img/menu.gif)"><table width="180" border="0" cellpadding="0" cellspacing="0">
  <tr>
    <td width="180" height="20">&nbsp;</td>
  </tr>
  <tr>
    <td style="padding-left: 1px;"><div class="nlu_navi1_docu">
<ul>
	<li class="sub_no"><a href=".//index.php?english_version">Home</a></li>
	<li class="sub_no sub_ul_true"><a href="installation_en.phtml">Installation &amp; Upgrade<img src="picture/myRT1/newR.gif" alt="6/28/2007" border="0"></a></li>
	<li class="sub_no sub_ul_true"><a href="the_docu.phtml">The Docu</a></li>
	<li class="sub_no sub_ul_true"><a href="add_on_en.phtml">Add On&#039;s</a></li>
	<li class="sub_no sub_ul_true"><a href="error_messages.phtml">Error messages</a></li>
	<li class="sub_no"><a href="search.phtml">Search</a></li>
	<li class="sub_ul"><a href="contact.phtml">Contact</a>
	<ul>
		<li class="sub_no"><a href="imprint.phtml">Imprint</a></li>
		<li class="sub_no active"><a href="guestbook.phtml">Guestbook</a></li>
	</ul>
	</li>
	<li class="sub_no"><a href="faq_en.phtml">FAQ</a></li>
</ul>
</div></td>
  </tr>
 <tr>
    <td style="padding:10px; color:#000000;">
<img src="picture/seperate.gif" border="0" alt="" /><br /><br />
<img src="content/gt/c21c1becaf44b7db9eb0e69f9f62318f.png" alt="Latest Final Version:" title="Latest Final Version:" width="142" height="13" border="0" /><br /><br />
<img src="content/gt/e91a9fb3d2c66ffdf2b7ffd0222a1a9b.png" alt="phpwcms 1.3.3" title="phpwcms 1.3.3" width="83" height="13" border="0" /><br />
<img src="content/gt/16f7a9a420c286d140125832bebd962d.png" alt="RELEASED: 02.05.2007" title="RELEASED: 02.05.2007" width="131" height="13" border="0" /><br /><br />
<a href="http://www.phpwcms.de/forum/viewtopic.php?t=14617"><img src="content/gt/9661ea0c3a00342c05e40467dd5ec5e5.png" alt="more..." title="more..." width="40" height="13" border="0" /></a><br /><br />
<img src="picture/seperate.gif" border="0" alt="" /><br /><br />
</TD>
  </tr>
   <tr>
    <td align="center"><span>
</span><br />ADS<br /><br /><img src="picture/seperate.gif" border="0" alt="" /><P>
</td>
  </tr>
<tr>
    <td height="20">&nbsp;</td>
  </tr>
  <tr>
    <td align="center"></td>
  </tr>
  <tr>
    <td height="20">&nbsp;</td>
  </tr>
</table>


</body>
</html>
</td>
<td valign="top" width="555" bgcolor="#ffffff" class="maincontent"><img src="img/leer.gif" border="0" width="10" height="1" alt="" />
<br />
<a href="english_version.phtml">English</a> <span class="breadcrumb_spacer">&gt;</span> <a href="contact.phtml">Contact</a> <span class="breadcrumb_spacer">&gt;</span> Guestbook
<br />
<HR>
<br />
<a name="jump60"></a><div>
<h1 style="margin:0 0 5px 0;">Guestbook</h1>


</div>

<div style="margin:25px 0 0 0;padding:0;" class="spaceBeforeCP"></div>
   
<table width="100%"  border="0" cellspacing="0" cellpadding="0" style="margin-top:5px;">
  <tr>
    <td><strong><a href="105.60.0.1.1.0.phtml">&lt;&lt;</a> <a href="105.60.0.1.1.12.phtml">&lt;</a></strong> <a href="105.60.0.1.1.11.phtml">12</a>&nbsp;<a href="105.60.0.1.1.12.phtml">13</a>&nbsp;<strong>14</strong>&nbsp;<a href="105.60.0.1.1.14.phtml">15</a>&nbsp;<a href="105.60.0.1.1.15.phtml">16</a> <strong><a href="105.60.0.1.1.14.phtml">&gt;</a>
        <a href="105.60.0.1.1.15.phtml">&gt;&gt;</a></strong></td>
    <td align="right">&nbsp;<form name="guestbookjump" id="guestbookjump" method="post" action="index.php?id=105,60,0,1,1,13"><select name="showguestbookpage" id="showpage" onchange="document.guestbookjump.submit();"><option value="1">page
      1</option>
<option value="2">page
      2</option>
<option value="3">page
      3</option>
<option value="4">page
      4</option>
<option value="5">page
      5</option>
<option value="6">page
      6</option>
<option value="7">page
      7</option>
<option value="8">page
      8</option>
<option value="9">page
      9</option>
<option value="10">page
      10</option>
<option value="11">page
      11</option>
<option value="12">page
      12</option>
<option value="13">page
      13</option>
<option value="14" selected="selected">page
      14</option>
<option value="15">page
      15</option>
<option value="16">page
      16</option>
</select>&nbsp;<input name="jumpsubmit" class="guestbookJumpSubmit" type="submit" value="go" /></form></td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
</table>

<table width="100%"  border="0" cellspacing="0" cellpadding="2">
  
  <tr bgcolor="#F5F5F5">
    <td width="99%">66 | 09/11/2004 09:59</td>
  </tr>
  <tr>
    <td colspan="2"><a href="mailto:"><strong>webkidz</strong></a> {URL:visit
      website} <br />
      Mach weiter so mit Deiner Seite wie bisher! Du hast mir mit deiner Seite schon das eine oder andere mal geholfen!<br />
<br />
<span style="color:#00CC00;">hallo, danke. aber Bitte bedenke das ich das nicht alleine mache. Sondern das es hier mehr Flinke finger gibt*zwinker* Gruß Oliver &quot;Pappnase&quot;</span></td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
  
  <tr bgcolor="#F5F5F5">
    <td width="99%">67 | 09/06/2004 23:01</td>
  </tr>
  <tr>
    <td colspan="2"><a href="mailto:mseydel@achumer-wiese-40.de"><strong>Matthias Seydel</strong></a> {URL:visit
      website} mseydel@achumer-wiese-40.de<br />
      Hallo,<br />
ersteinmal herzlichen Glückwunsch zu dieser Seite. Endlich ein Anlaufpunkt (ausser  dem  guten Forum und der Seite von Herrn Pepperkorn ;-) ) Das CMS ist wirkliches das beste was ich bis jetzt gefunden habe und weitersuchen lohnt wohl auch nicht...<br />
<br />
Mir ist bei &quot;Content Parts &gt; Gästebuch&quot; aufgefallen  das das bei mir etwas anders aussieht . Nix mit Wortsperre etc. Habe ich etwas verpasst ? <br />
Meine Version 1.1 - RC4 22.06.2004.<br />
<br />
mfg<br />
Matthias<br />
<br />
<span style="color:#00CC00;">Hallo, erstmal danke für den netten Eintrag. Ja du hast was verpasst am 27.08 gab es ein kleines aber feines Update.<br />
<br />
Gruß Oliver &quot;Pappnase&quot;</span></td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
  
  <tr bgcolor="#F5F5F5">
    <td width="99%">68 | 09/04/2004 11:47</td>
  </tr>
  <tr>
    <td colspan="2"><a href="mailto:info@magicbit.de"><strong>nepo</strong></a> {URL:visit
      website} info@magicbit.de<br />
      Hallo Olli,<br />
ich kann mir nicht´s besseres vorstellen als diese {docu}. Bis jetzt kommt man überall supergut zurecht. Falls jedoch Unklarheiten auftauchen, lass ich es Dich wissen. Ansonsten mach weiter so. Absolut spitzenmäßige Site.<br />
Gruß nepo</td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
  
  <tr bgcolor="#F5F5F5">
    <td width="99%">69 | 09/01/2004 08:15</td>
  </tr>
  <tr>
    <td colspan="2"><a href="mailto:"><strong>Jason Benedict</strong></a> {URL:visit
      website} <br />
      Great work ! phpWCMS is one of the best system i ever used. I started with v1.1-RC1 and had been follow till now 1.1-RC4 -:)<br />
<br />
BTW, this site is very kool as well :).</td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
  
  <tr bgcolor="#F5F5F5">
    <td width="99%">70 | 08/29/2004 20:57</td>
  </tr>
  <tr>
    <td colspan="2"><a href="mailto:"><strong>Rolf Dahl</strong></a> {URL:visit
      website} <br />
      Nice work!</td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
  
</table>

<table width="100%"  border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td colspan="2"><HR></td>
  </tr>
  <tr>
    <td width="50%">Article created: 2004/08/17</td>
    <td align="right" width="50%">Last Changes: 2007/05/01</td>
  </tr>
  <tr>
    <td colspan="2">&nbsp;</td>
  </tr>
  <tr>
    <td colspan="2" class="comment">In case you find any mistakes or have enhancments, please use this <a href="#" onClick="javascript:window.open('./content/pages/message.htm','frage','width=400, height=250, screenX=440,screenY=200,menubar=no,statusbar=yes,scrollbar=yes,resizable=no');" target="" style="max-width:148px; overflow:hidden;"><u>form</u></a> .<br /><br />
Have you found this website a helpful resource in understanding the Phpwcms content management system? If so, would you consider making a donation?  Please click here: <a href="#paypal">PayPal</a>. We welcome any donation amount. Your contribution helps make this website an even better resource and helps underwrite the associated server expenses of accomodating a growing number of visitors.<br />
This page use the version:</td>
  </tr>
  <tr>

    <td colspan="2"><img src="img/leer.gif" border="0" width="10" height="10" alt="" /></td>
  </tr>
</table>
</td>
</tr>
<tr>
<td colspan="2" style="height:10px;"  bgcolor="#ffffff" class="footer"><table width="100%" height="20" background="img/footer.gif" cellpadding="0" cellspacing="0" border="0">
	<tr><td width="180" align="center" valign="middle">8 User online</td>
	<td>
	<table width="100%"cellpadding="0" cellspacing="0" border="0">
   <tr>
    <td align="center"><a href="#" target="_top" title="go back" onclick="history.back();return false;" class="phpwcmsBackLink"><img src="picture/back_.gif" border="0" alt="Back"><img src="content/gt/a8cf006b46d2d29bf7161aa985b04a42.png" alt="Back" title="Back" width="31" height="13" border="0" /></a></td>
	<td align="center"><a href="sitemap_en.phtml"><img src="picture/sitemap_.gif" border="0"  alt="Sitemap"><img src="content/gt/38062c01670c74843cc0b291d94966c6.png" alt="Sitemap" title="Sitemap" width="50" height="13" border="0" /></a></td>
	
	<td align="center"><a href="guestbook.phtml"><img src="picture/icon_gaestebuch.gif" border="0" align="top" alt="Guestbook"><img src="content/gt/a8891d2da470901a9086f978d5a7dc3d.png" alt="Guestbook" title="Guestbook" width="66" height="13" border="0" /></a></td>
	<td align="center"><a href="#" onclick="BookMark_Page();return false;" title="" class="phpwcmsBookmarkLink"><img src="picture/favoriten_.gif" border="0"  alt="Bookmark"><img src="content/gt/a8d175704cefbe0ee8222b9bde55b692.png" alt="Bookmark" title="Bookmark" width="59" height="13" border="0" /></a></td>
    </tr>
</table></td>
	</tr>
</table>
<img src="img/leer.gif" border="0" width="760" height="10" alt="" /><br />
</td>
</tr>
</table>

</body>
</html>