<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<!--
	phpwcms | free open source content management system
	created by Oliver Georgi (oliver at phpwcms dot de) and licensed under GNU/GPL.
	phpwcms is copyright 2003-2006 of Oliver Georgi. Extensions are copyright of\
	their respective owners. Visit project page for details: http://www.phpwcms.org/
//-->
<title></title>
  <meta http-equiv="content-type" content="text/html; charset=iso-8859-1" />
  <meta http-equiv="content-style-type" content="text/css" />
  <script src="template/inc_js/frontend.js" type="text/javascript"></script>
  <style type="text/css" media="all">
  /* <![CDATA[ */
    body {
      margin: 0;
      padding-top: 0;
      padding-bottom: 0;
      padding-left: 0;
      padding-right: 0;

    }
  /* ]]> */
  </style>
  <style type="text/css">
  /* <![CDATA[ */
    @import url("template/inc_css/frontend.css");
    @import url("template/inc_css/nlu_navi1_docu.css");
    @import url("template/inc_css/print_layout.css");
  /* ]]> */
  </style>


<META NAME="Title" CONTENT="The phpWCMS Documentation">
<meta name="author" content="Oliver Frohnert">
<meta name="Publisher" content="Oliver Frohnert">
<meta name="Copyright" content="Oliver Frohnert">
<meta name="keywords" content="frohnert,documentation, dokumentation, phpwcms, cms. opensource, open source">
<meta name="description" content="A Documentation Project for the  Open Source CMS phpWCMS">
<meta name="Audience" content="Alle">
<meta name="Content-language" content="EN">
<META NAME="robots"      CONTENT="index,follow">
<META NAME="expires" CONTENT="0">
<meta name="revisit-after" content="7 days">
<meta name="resource-type" content="document">
<meta name="distribution" content="Global">
<meta name="generator" content="PHPWCMS">

  <!--[if lt IE 7]>
  <style type="text/css">
    body { behavior: url("template/inc_css/specific/csshover2.htc"); }
    img { behavior: url("template/inc_css/specific/pngbehavior.htc"); }
  </style>
  <![endif]-->
</head>
<body>
<img src="img/leer.gif" border="0" width="10" height="1" alt="" />
<br />
<a href="english_version.phtml">English</a> <span class="breadcrumb_spacer">&gt;</span> <a href="contact.phtml">Contact</a> <span class="breadcrumb_spacer">&gt;</span> Guestbook
<br />
<HR>
<br />
<a name="jump60"></a><h1>Guestbook</h1><div style="margin:25px 0 0 0; padding:0 0 0 0; clear:both;"></div>
   
<table width="100%"  border="0" cellspacing="0" cellpadding="0" style="margin-top:5px;">
  <tr>
    <td><strong><a href="105.60.1.1.1.0.phtml">&lt;&lt;</a> <a href="105.60.1.1.1.116.phtml">&lt;</a></strong> <a href="105.60.1.1.1.115.phtml">116</a>&nbsp;<a href="105.60.1.1.1.116.phtml">117</a>&nbsp;<strong>118</strong>&nbsp;<a href="105.60.1.1.1.118.phtml">119</a>&nbsp;<a href="105.60.1.1.1.119.phtml">120</a> <strong><a href="105.60.1.1.1.118.phtml">&gt;</a>
        <a href="105.60.1.1.1.125.phtml">&gt;&gt;</a></strong></td>
    <td align="right">&nbsp;</td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
</table>

<table width="100%"  border="0" cellspacing="0" cellpadding="2">
  
  <tr bgcolor="#F5F5F5">
    <td width="99%">586 | 01/06/2005 16:20</td>
  </tr>
  <tr>
    <td colspan="2"><strong>bons</strong> <a href="http://bonstronics.com" target="_blank">visit
      website</a> <br />
      Very great resource. Very timely and informative.<br />
<br />
<span style="color:#00CC00;"> edit by Oliver &quot;Pappnase&quot; Frohnert, This is not the Support Forum! So please stop to post Questions. The forum is here http://www.phpwcms.de/forum</span></td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
  
  <tr bgcolor="#F5F5F5">
    <td width="99%">587 | 01/02/2005 23:29</td>
  </tr>
  <tr>
    <td colspan="2"><strong>Markus Kösters</strong> <a href="http://www.musicstar.de" target="_blank">visit
      website</a> Markus.koesters at web  dot de<br />
      Hallo,<br />
<br />
zuerst mal möchte ich euch allen ein frohes neues Jahr wünschen.<br />
Ich möchte einfach mal die Gelegenheit nutzen und allen die an der Entwicklung von phpwcms und dem ganzen drum herum (Doku, etc.) beteiligt sind, zu danken.<br />
Was Ihr hier mal wieder auf die Beine gestellt habt, ist echt großartig.<br />
Macht Bitte weiter so.<br />
<br />
Mittlerweile habe ich einige CMS Systeme ausprobiert, und zur Zeit gehört phpwcms zu meinen Faves, da man wirklich sehr viele Freiheiten hat.<br />
Ich bin mächtig gespannt auf die Version2.<br />
<br />
Grüße Markus</td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
  
  <tr bgcolor="#F5F5F5">
    <td width="99%">588 | 12/29/2004 18:26</td>
  </tr>
  <tr>
    <td colspan="2"><strong>Malte Zugermeier</strong> <a href="http://www.zugermeier.de" target="_blank">visit
      website</a> <br />
      Echt klasse, dass es jetzt auch eine deutsche Anleitung zu phpwcms gibt!</td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
  
  <tr bgcolor="#F5F5F5">
    <td width="99%">589 | 12/26/2004 19:14</td>
  </tr>
  <tr>
    <td colspan="2"><strong>Thomas Merz</strong>  <br />
      Hallo! Klasse-Seite und prima-Infos! <br />
Mit Hilfe Eurer Tipps und Erläuterungen gelingt es wirklich sehr einfach, mit PHPWCMS zu guten Ergebnissen zu kommen! <br />
Grüsse aus Herxheim</td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
  
  <tr bgcolor="#F5F5F5">
    <td width="99%">590 | 12/23/2004 11:28</td>
  </tr>
  <tr>
    <td colspan="2"><a href="mailto:Tommy.kurtze@nilgen.de"><strong>Tommy</strong></a>  Tommy.kurtze@nilgen.de<br />
      Kann mir jemad beim Einsatz von phpadsnew Adserver helfen? Versuche zwei Banner zu verknüpfen (TandemAds) und der Wahnsinn ist momentan näher als die Aussicht auf Erfolg...:-))<br />
Wäre seeehr net...<br />
<br />
<span style="color:#00CC00;">hallo bitte postet keine support anfragen im gästebuch. wendet euch bitte ans forum!<br />
<br />
hello please post no support questions into the guestbook. please use for that the forum<br />
<br />
cheers / gruß Oliver &quot;Pappnase&quot; Frohnert</span></td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
  
</table>

<table width="100%"  border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td colspan="2"><HR></td>
  </tr>
  <tr>
    <td width="50%">Article created: 2004/08/17</td>
    <td align="right" width="50%">Last Changes: 2006/06/06</td>
  </tr>
  <tr>
    <td colspan="2">&nbsp;</td>
  </tr>
  <tr>
    <td colspan="2" class="comment">In case you find any mistakes or have enhancments, please use this <a href="#" onClick="javascript:window.open('./content/pages/message.htm','frage','width=400, height=250, screenX=440,screenY=200,menubar=no,statusbar=yes,scrollbar=yes,resizable=no');" target="" style="max-width:148px; overflow:hidden;"><u>form</u></a> .<br /><br />
Have you found this website a helpful resource in understanding the Phpwcms content management system? If so, would you consider making a donation?  Please click here: <a href="#paypal">PayPal</a>. We welcome any donation amount. Your contribution helps make this website an even better resource and helps underwrite the associated server expenses of accomodating a growing number of visitors.<br />
This page use the version:</td>
  </tr>
  <tr>

    <td colspan="2"><img src="img/leer.gif" border="0" width="10" height="10" alt="" /></td>
  </tr>
</table>

</body>
</html>