<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<!--
	phpwcms | free open source content management system
	created by Oliver Georgi (oliver at phpwcms dot de) and licensed under GNU/GPL.
	phpwcms is copyright 2003-2007 of Oliver Georgi. Extensions are copyright of
	their respective owners. Visit project page for details: http://www.phpwcms.org/
//-->
<title>Guestbook | Guestbook</title>
  <meta http-equiv="content-type" content="text/html; charset=iso-8859-1" />
  <meta http-equiv="content-style-type" content="text/css" />
  <script src="template/inc_js/frontend.js" type="text/javascript"></script>
  <style type="text/css" media="all">
  <!-- 
    body {
      margin: 0;
      padding-top: 0;
      padding-bottom: 0;
      padding-left: 0;
      padding-right: 0;

    }
  //-->
  </style>
  <style type="text/css">
  <!-- 
    @import url("template/inc_css/frontend.css");
    @import url("template/inc_css/nlu_navi1_docu.css");
  //-->
  </style>
<script src="http://www.google-analytics.com/urchin.js" type="text/javascript">
</script>
<script type="text/javascript">
_uacct = "UA-361662-1";
urchinTracker();
</script>
<META NAME="Title" CONTENT="The phpWCMS Documentation">
<meta name="author" content="Oliver Frohnert">
<meta name="Publisher" content="Oliver Frohnert">
<meta name="Copyright" content="Oliver Frohnert">
<meta name="keywords" content="frohnert,documentation, dokumentation, phpwcms, cms. opensource, open source">
<meta name="description" content="A Documentation Project for the  Open Source CMS phpWCMS">
<meta name="Audience" content="Alle">
<meta name="Content-language" content="EN">
<META NAME="robots"      CONTENT="index,follow">
<META NAME="expires" CONTENT="0">
<meta name="revisit-after" content="7 days">
<meta name="resource-type" content="document">
<meta name="distribution" content="Global">
<meta name="generator" content="PHPWCMS">
<META name="verify-v1" content="1ZpxZ7AZsjm7PxjqXQVus0eiUYqOsp5URTJn9q4KNz8=" />
  <!--[if lt IE 7]>
  <style type="text/css">
    body { behavior: url("template/inc_css/specific/csshover2.htc"); }
    img { behavior: url("template/inc_css/specific/pngbehavior.htc"); }
  </style>
  <![endif]-->
</head>
<body>


<!--

	this is the default PDF template
	use it to add additional header or
	footer information or whatever you 
	like to be rendered 

//-->
URL: <a href="deutsche_version.phtml?id=105,60,1,1,1,14" target="_blank">deutsche_version.phtml?id=105,60,1,1,1,14</a>
<hr />
<img src="img/leer.gif" border="0" width="10" height="1" alt="" />
<br />
<a href="english_version.phtml">English</a> <span class="breadcrumb_spacer">&gt;</span> <a href="contact.phtml">Contact</a> <span class="breadcrumb_spacer">&gt;</span> Guestbook
<br />
<HR>
<br />
<a name="jump60"></a><div>
<h1 style="margin:0 0 5px 0;">Guestbook</h1>


</div>

<div style="margin:25px 0 0 0;padding:0;" class="spaceBeforeCP"></div>
  <form name="sign_guestbook" action="index.php?id=105,60,1,1,1,14" method="post">
<table border="0" align="center" cellpadding="1" cellspacing="0" bgcolor="#F5F5F5" style="margin-bottom:10px;">
  <tr bgcolor="#E1E1E1">
    <td colspan="2"><strong>&nbsp;&nbsp;sign my guestbook</strong> <span style="font-size:10px;color:#CC3300;">(fields
        marked * are obligatory)</span></td>
  </tr>
  <tr bgcolor="#E1E1E1">
    <td colspan="2"><img src="img/leer.gif" width="1" height="1" alt="" /></td>
  </tr>
  
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
  <tr>
    <td align="right" class="v10">email<span style="color:#CC3300;">*</span>:&nbsp;</td>
    <td><input name="guestbook_email" type="text" id="guestbook_email" style="width: 350px" class="v12" value="" size="50" maxlength="250" />&nbsp;</td>
  </tr>
  <tr>
    <td align="right" class="v10">name<span style="color:#CC3300;">*</span>:&nbsp;</td>
    <td><input name="guestbook_name" type="text" id="guestbook_name" style="width: 350px" class="v12" value=""  size="50" maxlength="500" /></td>
  </tr>
  <tr>
    <td align="right" class="v10">website:&nbsp;</td>
    <td><input name="guestbook_url" type="text" id="guestbook_url" style="width: 350px" class="v12" value="" size="50" maxlength="1000" /></td>
  </tr>
  <tr>
    <td align="right" valign="top" class="v10">&nbsp;&nbsp;message:&nbsp;</td>
    <td><textarea name="guestbook_msg" cols="50" rows="6" id="guestbook_msg" class="v12" style="width: 350px"></textarea></td>
  </tr>
  <tr>
    <td align="right" valign="top" class="v10">display:&nbsp;</td>
    <td><input name="guestbook_show" type="radio" value="0" checked>show email<br /><input name="guestbook_show" type="radio" value="1">hide email<br /><input type="radio" name="guestbook_show" value="2">show email as &quot;info at mail dot com&quot;</td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="4" alt="" /></td>
  </tr>
  <tr>
  	<td align="right" class="v10">code<span style="color:#CC3300;">*</span>:&nbsp;</td>
  	<td><table cellpadding="0" cellspacing="0" border="0">
		<tr>
			<td><input name="guestbook_captcha" type="text" id="guestbook_captcha" style="width: 100px" class="v12" value="" size="10" maxlength="10" />&nbsp;&nbsp;</td>
			<td><img src="img/captcha.php?regen=y&amp;length=5&amp;1183377609" alt="Captcha" border="0" id="gbCaptchaImage" /></td>
		</tr>
		</table></td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="10" alt="" /></td>
  </tr>
  <tr>
    <td align="right">&nbsp;</td>
    <td><input name="guestbook_send" type="submit" id="guestbook_send" value="sign guestbook" class="v11" /></td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="6" alt="" /></td>
  </tr>
</table>
<input type="hidden" name="e0c2f295f88b4d9d5339b57e7b4dccb9" value="3502" /></form> 
<table width="100%"  border="0" cellspacing="0" cellpadding="0" style="margin-top:5px;">
  <tr>
    <td><strong><a href="105.60.1.1.1.0.phtml">&lt;&lt;</a> <a href="105.60.1.1.1.13.phtml">&lt;</a></strong> <a href="105.60.1.1.1.11.phtml">12</a>&nbsp;<a href="105.60.1.1.1.12.phtml">13</a>&nbsp;<a href="105.60.1.1.1.13.phtml">14</a>&nbsp;<strong>15</strong>&nbsp;<a href="105.60.1.1.1.15.phtml">16</a> <strong><a href="105.60.1.1.1.15.phtml">&gt;</a>
        <a href="105.60.1.1.1.15.phtml">&gt;&gt;</a></strong></td>
    <td align="right"><form name="guestbookarchive" id="guestbookarchive" method="post" action="index.php?id=105,60,1,1,1,14"><select name="showarchive" id="showarchive" onchange="document.guestbookarchive.submit();"><option value="">all entries</option>
<option value="2007/06">2007/06</option>
<option value="2006/10">2006/10</option>
<option value="2006/03">2006/03</option>
<option value="2006/02">2006/02</option>
<option value="2006/01">2006/01</option>
<option value="2005/12">2005/12</option>
<option value="2005/11">2005/11</option>
<option value="2005/10">2005/10</option>
<option value="2005/09">2005/09</option>
<option value="2005/08">2005/08</option>
<option value="2005/07">2005/07</option>
<option value="2005/06">2005/06</option>
<option value="2005/05">2005/05</option>
<option value="2005/03">2005/03</option>
<option value="2005/02">2005/02</option>
<option value="2005/01">2005/01</option>
<option value="2004/12">2004/12</option>
<option value="2004/11">2004/11</option>
<option value="2004/10">2004/10</option>
<option value="2004/09">2004/09</option>
<option value="2004/08">2004/08</option>
</select><input type="hidden" name="archivedate" value="%Y/%m" />&nbsp;<input name="archivesubmit" class="guestbookArchiveSubmit" type="submit" value="go" /></form>&nbsp;<form name="guestbookjump" id="guestbookjump" method="post" action="index.php?id=105,60,1,1,1,14"><select name="showguestbookpage" id="showpage" onchange="document.guestbookjump.submit();"><option value="1">page
      1</option>
<option value="2">page
      2</option>
<option value="3">page
      3</option>
<option value="4">page
      4</option>
<option value="5">page
      5</option>
<option value="6">page
      6</option>
<option value="7">page
      7</option>
<option value="8">page
      8</option>
<option value="9">page
      9</option>
<option value="10">page
      10</option>
<option value="11">page
      11</option>
<option value="12">page
      12</option>
<option value="13">page
      13</option>
<option value="14">page
      14</option>
<option value="15" selected="selected">page
      15</option>
<option value="16">page
      16</option>
</select>&nbsp;<input name="jumpsubmit" class="guestbookJumpSubmit" type="submit" value="go" /></form></td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
</table>

<table width="100%"  border="0" cellspacing="0" cellpadding="2">
  
  <tr bgcolor="#F5F5F5">
    <td width="99%">71 | 08/16/2004 14:27</td>
  </tr>
  <tr>
    <td colspan="2"><a href="mailto:stephan at rackco dot com"><strong>Stephan Mackenzie</strong></a> {URL:visit
      website} stephan at rackco dot com<br />
      PHPWCMS is the greatest... keep up the good work, a centralized documentation is a fantastic idea... kudos to the ones responsible!</td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
  
  <tr bgcolor="#F5F5F5">
    <td width="99%">72 | 08/16/2004 02:19</td>
  </tr>
  <tr>
    <td colspan="2"><a href="mailto:cfoxgrover@foxpath.com"><strong>Chick Foxgrover</strong></a> {URL:visit
      website} cfoxgrover@foxpath.com<br />
      Great resource for a terrific CMS script. Thanks!</td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
  
  <tr bgcolor="#F5F5F5">
    <td width="99%">73 | 08/15/2004 19:30</td>
  </tr>
  <tr>
    <td colspan="2"><a href="mailto:uwe.twelker at eyelikeit dot de"><strong>Uwe Twelker</strong></a> {URL:visit
      website} uwe.twelker at eyelikeit dot de<br />
      I&#039;m using the PHPWCMS for about half a year. And I think it&#039;s dynamite. What makes it great is of course the PHPWCMS itself. Easy to install, easy to use (you feel like driving a Mac!). But that&#039;s far form being everything. There is an Oliver who talks and listens to his users and works and works and works... There is a great community assisting in the forum. They are fast, they are friendly, there are competencies for almost everything and this knowledge is generously shared. There is another Oliver, and Manfred and Achim and Jayenne who work there butts off to set up this documentation. And there a lot of more unknown people with a lot of unknown useful contributions.<br />
<br />
Thank you all. I&#039;m proud to be part of this community!<br />
<br />
<span style="color:#00CC00;">hello mac and thank you for the translation and the correction of some articles.<br />
Oliver &quot;Pappnase&quot;</span></td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
  
  <tr bgcolor="#F5F5F5">
    <td width="99%">74 | 08/14/2004 16:34</td>
  </tr>
  <tr>
    <td colspan="2"><a href="mailto:timdriever@hotmail.com"><strong>Tim Driever</strong></a> {URL:visit
      website} timdriever@hotmail.com<br />
      PHPWcms is a great CMS!! Good work Oliver and the crew from this site that you make a documenation for PHPWcms! Succes..!</td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
  
  <tr bgcolor="#F5F5F5">
    <td width="99%">75 | 08/14/2004 01:10</td>
  </tr>
  <tr>
    <td colspan="2"><a href="mailto:spam@jerome-gamez.de"><strong>Jérôme Gamez</strong></a> {URL:visit
      website} spam@jerome-gamez.de<br />
      Sehr gute Arbeit. Die Seite wird fortwährend umfangreicher und besser. Vielen Dank für euren unermüdlichen Einsatz, insb. Oliver (Pappnase), bei dem man sich fragen &quot;muss&quot;, ob er eigentlich irgendwann auch mal schläft oder etwas anderes macht :).<br />
<br />
Viele Grüße<br />
- Jérôme</td>
  </tr>
  <tr>
    <td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td>
  </tr>
  
</table>

<table width="100%"  border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td colspan="2"><HR></td>
  </tr>
  <tr>
    <td width="50%">Article created: 2004/08/17</td>
    <td align="right" width="50%">Last Changes: 2007/05/01</td>
  </tr>
  <tr>
    <td colspan="2">&nbsp;</td>
  </tr>
  <tr>
    <td colspan="2" class="comment">In case you find any mistakes or have enhancments, please use this <a href="#" onClick="javascript:window.open('./content/pages/message.htm','frage','width=400, height=250, screenX=440,screenY=200,menubar=no,statusbar=yes,scrollbar=yes,resizable=no');" target="" style="max-width:148px; overflow:hidden;"><u>form</u></a> .<br /><br />
Have you found this website a helpful resource in understanding the Phpwcms content management system? If so, would you consider making a donation?  Please click here: <a href="#paypal">PayPal</a>. We welcome any donation amount. Your contribution helps make this website an even better resource and helps underwrite the associated server expenses of accomodating a growing number of visitors.<br />
This page use the version:</td>
  </tr>
  <tr>

    <td colspan="2"><img src="img/leer.gif" border="0" width="10" height="10" alt="" /></td>
  </tr>
</table>


</body>
</html>