<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">

<!--

phpwcms | open source web content management system

          developed by Oliver Georgi (info@phpwcms.de)
          released under The GNU General Public License
          visit project page: http://www.phpwcms.de

          Release: 1.1-RC4 27-08-2004

//-->
<html>
<head>
<title>phpwcms documentation | Global Error messages</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<META NAME="Title" CONTENT="The phpWCMS Documentation">
<meta name="author" content="Oliver Frohnert">
<meta name="Publisher" content="Oliver Frohnert">
<meta name="Copyright" content="Oliver Frohnert">
<meta name="keywords" content="frohnert,documentation, dokumentation, phpwcms, cms. opensource, open source">
<meta name="description" content="A Documentation Project for the  Open Source CMS phpWCMS">
<meta name="Audience" content="Alle">
<meta name="Content-language" content="EN">
<META NAME="robots"      CONTENT="index,follow">
<META NAME="expires" CONTENT="0">
<meta name="revisit-after" content="7 days">
<meta name="resource-type" content="document">
<meta name="distribution" content="Global">
<meta name="generator" content="PHPWCMS">
<script language="JavaScript" type="text/javascript" src="pphlogger.js"></script>
<noscript><img alt="" src="./pphlogger/pphlogger.php?id=phpwcms&st=img"></noscript>
<meta name="keywords" content="*edit*
error message">
<script src="template/inc_js/frontend.js" type="text/javascript"></script>
<link rel="stylesheet" type="text/css" href="template/inc_css/frontend.css">
</head>

<body bgcolor="#FFFFFF" text="#000000" link="#FF9900" vlink="#FF9900" alink="#FF9900" topmargin="0" leftmargin="0" marginwidth="0" marginheight="0">
<table border="0" cellspacing="0" cellpadding="0" width="760" bgcolor="#ffffff" class="maintable" align="center">
<tr>
<td colspan="2" style="height:60px;"  bgcolor="#ffffff"><table width="760" height="135" border="0" cellpadding="0" cellspacing="0">
  <tr valign="top">
    <td width="1334" height="122" colspan="6" background="template/lang/en/header_newyear.jpg">&nbsp;</td>
  </tr>
  <tr>
	<td height="27" background="template/lang/all/top_menu.jpg"><table width="570" border="0" align="left" cellpadding="0" cellspacing="0">
      <tr>
        <td align="center" width="254"><a href="deutsche_version.phtml"><img src="picture/flags/de.gif" width="16" height="10" hspace="10" border="0"  alt="Deutsche Version" title="Deutsche Version"></a>
<a href="english_version.phtml"><img src="picture/flags/gb.gif" width="16" height="10" hspace="10" border="0"  alt="English Version" title="English Version"></a></td>
        <td valign="middle"><div align="center"><a href="replacement_tags_en.phtml"><img src="content/gt/9ad4c84df9fc6e20be504ff61a358128.png" alt="Replacement Tags" border="0" /></a></div></td>
        <td width="30" valign="middle"><div align="center"><img src="template/lang/all/sep.gif" width="5" height="5" border="0"></div></td>
        <td valign="middle"><div align="center"><a href="content_parts_en.phtml"><img src="content/gt/0ac72fda03e1537553c1f89e3f96ad75.png" alt="Content Parts" border="0" /></a></div></td>
        <td width="30" valign="middle"><div align="center"><img src="template/lang/all/sep.gif" width="5" height="5" border="0"></div></td>
        <td valign="middle"><div align="center"><a href="links_de.phtml"><img src="content/gt/c13491df26fc7ba71211ce67d0cd7cac.png" alt="Links" border="0" /></a></div></td>
        <td width="30" valign="middle"><div align="center"><img src="template/lang/all/sep.gif" width="5 " height="5" border="0"></div></td>
        <td valign="middle"><div align="center"><a href="imprint.phtml"><img src="content/gt/215793d443e1aa389280e64b8712f954.png" alt="Imprint" border="0" /></a></div></td>
     </tr>
    </table>    </td>
  </tr>
</table>
</td>
</tr>
<tr>
<td valign="top" width="185" background="img/menu.gif"><table width="180" border="0" cellpadding="0" cellspacing="0">
  <tr>
    <td width="180" height="20">&nbsp;</td>
  </tr>
  <tr>
    <td style="padding-left: 7px;"><table border="0" width="100%" cellspacing="0" cellpadding="0">
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='news_en.phtml';return false;" onMouseOver="MM_swapImage('linkidEReBs2','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td ><img src="img/leer.gif" width="1" height="1" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkidEReBs2" id="linkidEReBs2"></td>
<td valign="top" style="height:20px;"  width="100%" class="nav_table" colspan="2"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="news_en.phtml">News</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="0"><img src="img/leer.gif" width="8" height="20" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='205.0.0.1.0.0.phtml';return false;" onMouseOver="MM_swapImage('linkidMEedMu','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td ><img src="img/leer.gif" width="1" height="1" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkidMEedMu" id="linkidMEedMu"></td>
<td valign="top" style="height:20px;"  width="100%" class="nav_table" colspan="2"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="205.0.0.1.0.0.phtml">Administration</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="0"><img src="img/leer.gif" width="8" height="20" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='layout_en.phtml';return false;" onMouseOver="MM_swapImage('linkidERr82C','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td ><img src="img/leer.gif" width="1" height="1" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkidERr82C" id="linkidERr82C"></td>
<td valign="top" style="height:20px;"  width="100%" class="nav_table" colspan="2"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="layout_en.phtml">Layout</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="0"><img src="img/leer.gif" width="8" height="20" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='editorial.phtml';return false;" onMouseOver="MM_swapImage('linkidl8lHUo','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td ><img src="img/leer.gif" width="1" height="1" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkidl8lHUo" id="linkidl8lHUo"></td>
<td valign="top" style="height:20px;"  width="100%" class="nav_table" colspan="2"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="editorial.phtml">Editorial</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="0"><img src="img/leer.gif" width="8" height="20" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='error_messages.phtml';return false;">
<td ><img src="img/leer.gif" width="1" height="1" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_2" alt="" border="" name="linkidV471t9" id="linkidV471t9"></td>
<td valign="top" style="height:20px;"  width="100%" class="nav_table_active" colspan="2"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="error_messages.phtml">Error messages</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="0"><img src="img/leer.gif" width="8" height="20" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='errormessages_inst.phtml';return false;" onMouseOver="MM_swapImage('linkidH1XLUK','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td  colspan="2"><img src="img/leer.gif" width="1" height="1" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkidH1XLUK" id="linkidH1XLUK"></td>
<td valign="top" style="height:20px;"  width="100%" class="nav_table"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="errormessages_inst.phtml">Inst. Error Messages</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="0"><img src="img/leer.gif" width="8" height="20" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='search.phtml';return false;" onMouseOver="MM_swapImage('linkidMHi849','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td ><img src="img/leer.gif" width="1" height="1" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkidMHi849" id="linkidMHi849"></td>
<td valign="top" style="height:20px;"  width="100%" class="nav_table" colspan="2"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="search.phtml">Search</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="0"><img src="img/leer.gif" width="8" height="20" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='contact.phtml';return false;" onMouseOver="MM_swapImage('linkidblYOcb','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td ><img src="img/leer.gif" width="1" height="1" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkidblYOcb" id="linkidblYOcb"></td>
<td valign="top" style="height:20px;"  width="100%" class="nav_table" colspan="2"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="contact.phtml">Contact</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="0"><img src="img/leer.gif" width="8" height="20" alt="" /></td>
</tr>
</table></td>
  </tr>
 <tr>
    <td style="padding:10px; color:#000000;"><img src="picture/seperate.gif" border="0" alt="" /><P>
	<a href="deutsche_version.phtml?id=286,216,0,0,1,0">Latest Version:<br>
RC 1.1 - 27.08.2004a<br>
Release Date: 6.11.2004<P>
Last Patch:<BR>
26.11.2004</a><P>
<img src="picture/seperate.gif" border="0" alt="" /></TD>
  </tr>
<tr>
    <td height="20">&nbsp;</td>
  </tr>
  <tr>
    <td align="center"></td>
  </tr>
  <tr>
    <td height="20">&nbsp;</td>
  </tr>
</table>


</body>
</html>
</td>
<td valign="top" width="555" bgcolor="#ffffff" class="maincontent"><img src="img/leer.gif" border="0" width="10" height="1" alt="" />
<BR>
<a href="english_version.phtml">English</a> <span class="breadcrumb_spacer">&gt;</span> Error messages
<br>
<HR>
<br>
<a name="jump144"></a><span class="articleHead">Global Error messages</span><img src="img/leer.gif" width="1" height="8" alt=""><br /><img src="img/leer.gif" width="1" height="25" alt="" /><br /><TABLE width="100%" border=0>
<TBODY>
<TR>
<TD>error message:</TD></TR>
<TR>
<TD height=15>&nbsp;</TD></TR>
<TR>
<TD class=kasten>Login not possible. This is not exactly an error message but it's possible to appear. The login screen is shown again and you see your name in the "logged in list" at the left but actually you're not inside the backend.</TD></TR>
<TR>
<TD height=15>&nbsp;</TD></TR>
<TR>
<TD>solution:</TD></TR>
<TR>
<TD height=15>&nbsp;</TD></TR>
<TR>
<TD>Open your servers php.ini and set the following value to 1<BR><BR><!--StartFragment -->&nbsp;<EM><STRONG><SPAN class=postbody>session.use_trans_sid = 1</SPAN> </STRONG></EM><BR></TD></TR></TBODY></TABLE><div align="right"><a href="#top"><img src="img/article/top_link_0.gif" border="0" alt="" /></a></div><HR><br /><TABLE width="100%" border=0>
<TBODY>
<TR>
<TD>error message:</TD></TR>
<TR>
<TD height=15>&nbsp;</TD></TR>
<TR>
<TD class=kasten>Warning: Unknown(): write failed: No space left on device ( 28 ) in Unknown on line 0 Warning: Unknown(): Failed to write session data (files). Please verify that the current setting of session.save_path is correct (/tmp) in Unknown on line 0</TD></TR>
<TR>
<TD height=15>&nbsp;</TD></TR>
<TR>
<TD>solution:</TD></TR>
<TR>
<TD height=15>&nbsp;</TD></TR>
<TR>
<TD>This is error is not caused by phpWCMS. Please contact your host company.</TD></TR></TBODY></TABLE><div align="right"><a href="#top"><img src="img/article/top_link_0.gif" border="0" alt="" /></a></div><HR>
<table width="100%"  border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td colspan="2"><HR></td>
  </tr>
  <tr>
    <td width="50%">Article prepared: 30.August.2004</td>
    <td align="right" width="50%">Last Changes: 19. November 2004</td>
  </tr>
  <tr>
    <td colspan="2">&nbsp;</td>
  </tr>
  <tr>
    <td colspan="2" class="comment">In case you find any mistakes or have enhancments, please use this <a href="#" onClick="javascript:window.open('./content/pages/message.htm','frage','width=400, height=250, screenX=440,screenY=200,menubar=no,statusbar=yes,scrollbar=yes,resizable=no');" target="" style="max-width:148px; overflow:hidden;"><u>form</u></a> .<br><BR>
Have you found this website a helpful resource in understanding the Phpwcms content management system? If so, would you consider making a donation?  Please click here: <a href="#paypal">PayPal</a>. We welcome any donation amount. Your contributions help make this website a even better resource and help underwrite the associated server expenses of accomodating a growing number of visitors.</td>
  </tr>
  <tr>

    <td colspan="2"><img src="img/leer.gif" border="0" width="10" height="10" alt="" /></td>
  </tr>
</table>
</td>
</tr>
<tr>
<td colspan="2" style="height:10px;"  bgcolor="#ffffff" class="footer"><table width="100%" height="20" background="img/footer.gif" cellpadding="0" cellspacing="0" border="0">
	<tr><td width="180" align="center" valign="middle"><strong>Visitors Online: <script language="JavaScript" type="text/javascript" src="./pphlogger/showhits.php?id=phpwcms&st=js&type=onlineusr"></script>
      </strong>
	</td>
	<td>
	<table width="100%"cellpadding="0" cellspacing="0" border="0">
   <tr>
    <td align="center"><a href="javascript:history.back();" target="_top" title="go back"><img src="picture/back_.gif" border="0" alt="Back"><img src="content/gt/6f54c678069079e769023e7711a19f83.png" alt="Back" border="0" /></a></td>
	<td align="center"><a href="sitemap_en.phtml"><img src="picture/sitemap_.gif" border="0"  alt="Sitemap"><img src="content/gt/d6ee999c57eae0a9d98b837870d624f7.png" alt="Sitemap" border="0" /></a></td>
	<td align="center"><a href="106.144.1.0.1.0.phtml" target="_blank"><img src="picture/print_.gif" border="0" alt="Print"><img src="content/gt/62a58183f1a2ffea945cec1e1f6cf816.png" alt="Print" border="0" /></a></td>
	<td align="center"><a href="guestbook.phtml"><img src="picture/icon_gaestebuch.gif" border="0" align="top" alt="Guestbook"><img src="content/gt/dbef51efbc9de176f1c8c26d0975a46a.png" alt="Guestbook" border="0" /></a></td>
	<td align="center"><a href="#" onClick="BookMark_Page();return false;" alt="" title=""><img src="picture/favoriten_.gif" border="0"  alt="Bookmark"><img src="content/gt/96792869390d8debc683393263d2379e.png" alt="Bookmark" border="0" /></a></td>
    </tr>
</table></td>
	</tr>
</table>
<img src="img/leer.gif" border="0" width="760" height="10" alt="" />
</td>
</tr>
</table>
</body>
</html>