<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">

<!--

phpwcms | open source web content management system

          developed by Oliver Georgi (info@phpwcms.de)
          released under The GNU General Public License
          visit project page: http://www.phpwcms.de

          Release: 1.1-RC4 27-08-2004

//-->
<html>
<head>
<title></title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<META NAME="Title" CONTENT="The phpWCMS Documentation">
<meta name="author" content="Oliver Frohnert">
<meta name="Publisher" content="Oliver Frohnert">
<meta name="Copyright" content="Oliver Frohnert">
<meta name="keywords" content="frohnert,documentation, dokumentation, phpwcms, cms. opensource, open source">
<meta name="description" content="A Documentation Project for the  Open Source CMS phpWCMS">
<meta name="Audience" content="Alle">
<meta name="Content-language" content="EN">
<META NAME="robots"      CONTENT="index,follow">
<META NAME="expires" CONTENT="0">
<meta name="revisit-after" content="7 days">
<meta name="resource-type" content="document">
<meta name="distribution" content="Global">
<meta name="generator" content="PHPWCMS">
<script language="JavaScript" type="text/javascript" src="pphlogger.js"></script>
<noscript><img alt="" src="./pphlogger/pphlogger.php?id=phpwcms&st=img"></noscript>
<meta name="keywords" content="new">
<script src="template/inc_js/frontend.js" type="text/javascript"></script>
<link rel="stylesheet" type="text/css" href="template/inc_css/print_layout.css">
</head>

<body>
<img src="img/leer.gif" border="0" width="10" height="1" alt="" />
<BR>
<a href="english_version.phtml">English</a> <span class="breadcrumb_spacer">&gt;</span> <a href="311.0.0.1.0.0.phtml">The Docu</a> <span class="breadcrumb_spacer">&gt;</span> <a href="deutsche_version.phtml?the_article_center">Article</a> <span class="breadcrumb_spacer">&gt;</span> The Article Center
<br>
<HR>
<br>
<a name="jump65"></a><span class="articleHead">The article center</span><img src="img/leer.gif" width="1" height="8" alt=""><br /><img src="img/leer.gif" width="1" height="25" alt="" /><br /><div class="articleText">The primary navigation menu in he backend is the top bar, with addtional related items down the left. The first Item in the top menu is the "ARTICLE" area, you also will notice the two left menus, 'article center' &amp; 'new article'. Article center shows you an overview of the sites structure (in bold font) and its article content (normal font). The order and placent or articles with the article center is controled using the icons to the right of each article (itemised below). please note: the order &amp; placement of the site's structure may only be altered within the ADMIN section for management purposes.</div><table width="420" border="0" cellspacing="0" cellpadding="0" align="center" class="table_class">
<tr><td><img src="img/leer.gif" width="1" height="5" alt="" /></td></tr>
<tr><td class="image_td"><a href="zoom/MV8yMThfNnRGRkFtdVhCeC5wbmc.html" onClick="window.open('zoom/MV8yMThfNnRGRkFtdVhCeC5wbmc.html','previewpic','width=771,height=401');return false;.html"><img src="content/images/1_218_6tFFAmuXBx-420x.png" width="420" height="218" border="0" class="image_img" alt="" /></a></td></tr>
<tr><td><img src="img/leer.gif" width="1" height="3" alt="" /></td></tr>
<tr><td align="center" bgcolor="FCFCFC" class="image_caption"><img src="img/leer.gif" width="1" height="3" alt="" /><br><i>fig 2.1</i> Click to enlarge<br><img src="img/leer.gif" width="1" height="3" alt="" /></td></tr>
</table><img src="img/leer.gif" width="1" height="10" alt="" /><br />The following icons may be found to the right of each Category,Article, Content part and File center Item.
Please note: if the icon appears less defined (greyed out) it is inactive for the current context.
<P>
<TABLE style="WIDTH: 500px" cellSpacing=3 width=500 border=0>
<TBODY>
<TR>
<TD><img src="picture/./icon/image007.gif" border="0" alt="" /></TD>
<TD>Catergory: Open view (click to collapse view)</TD></TR>
<TR>
<TD><img src="picture/./icon/image008.gif" border="0" alt="" /></TD>
<TD>Category: Collapsed view (click to open view)</TD></TR>
<TR>
<TD><img src="picture/./icon/image009.gif" border="0" alt="" /></TD>
<TD>Category</TD></TR>
<TR>
<TD><img src="picture/./icon/image010.gif" border="0" alt="" /></TD>
<TD>New article within this category</TD></TR>
<TR>
<TD><img src="picture/./icon/image011.gif" border="0" alt="" /></TD>
<TD>An article</TD></TR>
<TR>
<TD><img src="picture/./icon/image012.gif" border="0" alt="" /></TD>
<TD>Edit article</TD></TR>
<TR>
<TD><img src="picture/./icon/image013.gif" border="0" alt="" /></TD>
<TD>Cut an article: click another category to paste this article elsewhere</TD></TR>
<TR>
<TD><img src="picture/./icon/image014.gif" border="0" alt="" /></TD>
<TD>Move article up by one position with the catergory.</TD></TR>
<TR>
<TD><img src="picture/./icon/image015.gif" border="0" alt="" /></TD>
<TD>Move article down by one position with the catergory.</TD></TR>
<TR valign="top">
<TD><img src="picture/./icon/image016.gif" border="0" alt="" /><img src="picture/./icon/image017.gif" border="0" alt="" /></TD>
<TD>indicates that the article is both "visible" and "public" (publicly available); the visibility of articles to visitors of the website can be toggled by clicking these. Note: Both indicators must remain green in order for the article to be visible to visitors of the<BR>Website.</TD></TR>
<TR valign="top">
<TD><img src="picture/icon/image018.gif" border="0" alt="" /><img src="picture/icon/image019.gif" border="0" alt="" /></TD>
<TD><img src="picture/icon/image018.gif" border="0" alt="" /> or <img src="picture/icon/image019.gif" border="0" alt="" />&nbsp;indicates that the article is invisible to visitors of the Website. Click<BR>on the red in each case, in order to switch the article to visible and public.</TD></TR>
<TR>
<TD><img src="picture/./icon/image020.gif" border="0" alt="" /></TD>
<TD>Delete article</TD></TR></TBODY></TABLE></P>
<table width="100%"  border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td colspan="2"><HR></td>
  </tr>
  <tr>
    <td width="50%">Article created: 13. August 2004</td>
    <td align="right" width="50%">Last Changes: 19. November 2004</td>
  </tr>
  <tr>
    <td colspan="2">&nbsp;</td>
  </tr>
  <tr>
    <td colspan="2" class="comment">In case you find any mistakes or have enhancments, please use this <a href="#" onClick="javascript:window.open('./content/pages/message.htm','frage','width=400, height=250, screenX=440,screenY=200,menubar=no,statusbar=yes,scrollbar=yes,resizable=no');" target="" style="max-width:148px; overflow:hidden;"><u>form</u></a> .<br><BR>
Have you found this website a helpful resource in understanding the Phpwcms content management system? If so, would you consider making a donation?  Please click here: <a href="#paypal">PayPal</a>. We welcome any donation amount. Your contribution helps make this website an even better resource and helps underwrite the associated server expenses of accomodating a growing number of visitors.</td>
  </tr>
  <tr>

    <td colspan="2"><img src="img/leer.gif" border="0" width="10" height="10" alt="" /></td>
  </tr>
</table></body>
</html>