<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">

<!--

phpwcms | open source web content management system

          developed by Oliver Georgi (info@phpwcms.de)
          released under The GNU General Public License
          visit project page: http://www.phpwcms.de

          Release: 1.1-RC4 27-08-2004

//-->
<html>
<head>
<title>phpwcms documentation | Content Part &quot;Linkliste&quot;</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<META NAME="Title" CONTENT="Die phpWCMS Dokumentation">
<meta name="author" content="Oliver Frohnert">
<meta name="Publisher" content="Oliver Frohnert">
<meta name="Copyright" content="Oliver Frohnert">
<meta name="keywords" content="frohnert,documentation, dokumentation, phpwcms, cms. opensource, open source">
<meta name="description" content="Das Dokumentations Projekt für das Open Source CMS phpWCMS">
<meta name="Audience" content="Alle">
<meta name="Content-language" content="DE">
<META NAME="robots"      CONTENT="index,follow">
<META NAME="expires" CONTENT="0">
<meta name="revisit-after" content="7 days">
<meta name="resource-type" content="document">
<meta name="distribution" content="Global">
<meta name="generator" content="PHPWCMS">
<script language="JavaScript" type="text/javascript" src="pphlogger.js"></script>
<noscript><img alt="" src="./pphlogger/pphlogger.php?id=phpwcms&st=img"></noscript>
<meta name="keywords" content="*bearbeitet*">
<script src="template/inc_js/frontend.js" type="text/javascript"></script>
<link rel="stylesheet" type="text/css" href="template/inc_css/frontend.css">
</head>

<body bgcolor="#FFFFFF" text="#000000" link="#FF9900" vlink="#FF9900" alink="#FF9900" topmargin="0" leftmargin="0" marginwidth="0" marginheight="0">
<table border="0" cellspacing="0" cellpadding="0" width="760" bgcolor="#ffffff" class="maintable" align="center">
<tr>
<td colspan="2" style="height:60px;"  bgcolor="#ffffff"><table width="760" height="135" border="0" cellpadding="0" cellspacing="0">
  <tr valign="top">
    <td width="1334" height="122" colspan="6" background="template/lang/de/header_neujahr.jpg">&nbsp;</td>
  </tr>
  <tr>
	<td height="27" background="template/lang/all/top_menu.jpg"><table width="570" border="0" align="left" cellpadding="0" cellspacing="0">
      <tr>
        <td align="center" width="254"><a href="deutsche_version.phtml"><img src="picture/flags/de.gif" width="16" height="10" hspace="10" border="0"  alt="Deutsche Version" title="Deutsche Version"></a>
<a href="english_version.phtml"><img src="picture/flags/gb.gif" width="16" height="10" hspace="10" border="0"  alt="English Version" title="English Version"></a></td>
        <td valign="middle"><div align="center"><a href="replacement_tags_de.phtml"><img src="content/gt/9ad4c84df9fc6e20be504ff61a358128.png" alt="Replacement Tags" border="0" /></a></div></td>
        <td width="30" valign="middle"><div align="center"><img src="template/lang/all/sep.gif" width="5" height="5" border="0"></div></td>
        <td valign="middle"><div align="center"><a href="content_parts_de.phtml"><img src="content/gt/0ac72fda03e1537553c1f89e3f96ad75.png" alt="Content Parts" border="0" /></a></div></td>
        <td width="30" valign="middle"><div align="center"><img src="template/lang/all/sep.gif" width="5" height="5" border="0"></div></td>
        <td valign="middle"><div align="center"><a href="links_de.phtml"><img src="content/gt/c13491df26fc7ba71211ce67d0cd7cac.png" alt="Links" border="0" /></a></div></td>
        <td width="30" valign="middle"><div align="center"><img src="template/lang/all/sep.gif" width="5 " height="5" border="0"></div></td>
        <td valign="middle"><div align="center"><a href="impressum.phtml"><img src="content/gt/304aadbbc5a74f91579640823fb3c8ab.png" alt="Impressum" border="0" /></a></div></td>
     </tr>
    </table>    </td>
  </tr>
</table>
</td>
</tr>
<tr>
<td valign="top" width="185" background="img/menu.gif"><table width="180" border="0" cellpadding="0" cellspacing="0">
  <tr>
    <td width="180" height="20">&nbsp;</td>
  </tr>
  <tr>
    <td style="padding-left: 7px;"><table border="0" width="100%" cellspacing="0" cellpadding="0">
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='news_de.phtml';return false;" onMouseOver="MM_swapImage('linkidp55sFD','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td ><img src="img/leer.gif" width="1" height="1" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkidp55sFD" id="linkidp55sFD"></td>
<td valign="top" style="height:20px;"  width="100%" class="nav_table" colspan="4"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="news_de.phtml">News</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="0"><img src="img/leer.gif" width="8" height="20" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='administration_de.phtml';return false;" onMouseOver="MM_swapImage('linkid2SpT7o','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td ><img src="img/leer.gif" width="1" height="1" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkid2SpT7o" id="linkid2SpT7o"></td>
<td valign="top" style="height:20px;"  width="100%" class="nav_table" colspan="4"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="administration_de.phtml">Administration</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="0"><img src="img/leer.gif" width="8" height="20" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='layout_de.phtml';return false;" onMouseOver="MM_swapImage('linkidZAFUB5','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td ><img src="img/leer.gif" width="1" height="1" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkidZAFUB5" id="linkidZAFUB5"></td>
<td valign="top" style="height:20px;"  width="100%" class="nav_table" colspan="4"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="layout_de.phtml">Layout</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="0"><img src="img/leer.gif" width="8" height="20" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='redaktion.phtml';return false;" onMouseOver="MM_swapImage('linkiddu4317','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td ><img src="img/leer.gif" width="1" height="1" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkiddu4317" id="linkiddu4317"></td>
<td valign="top" style="height:20px;"  width="100%" class="nav_table" colspan="4"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="redaktion.phtml">Redaktion</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="0"><img src="img/leer.gif" width="8" height="20" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='die_verwaltungsebene_backend.phtml';return false;" onMouseOver="MM_swapImage('linkidTVQ8ZC','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td  colspan="2"><img src="img/leer.gif" width="1" height="1" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkidTVQ8ZC" id="linkidTVQ8ZC"></td>
<td valign="top" style="height:20px;"  width="100%" class="nav_table" colspan="3"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="die_verwaltungsebene_backend.phtml">Verwaltung (Backend)</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="0"><img src="img/leer.gif" width="8" height="20" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='die_artikelzentrale.phtml';return false;" onMouseOver="MM_swapImage('linkiddC2LQf','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td  colspan="2"><img src="img/leer.gif" width="1" height="1" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkiddC2LQf" id="linkiddC2LQf"></td>
<td valign="top" style="height:20px;"  width="100%" class="nav_table" colspan="3"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="die_artikelzentrale.phtml">Artikel</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="0"><img src="img/leer.gif" width="8" height="20" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='die_artikelzentrale.phtml';return false;" onMouseOver="MM_swapImage('linkidfw0ntp','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td  colspan="3"><img src="img/leer.gif" width="1" height="1" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkidfw0ntp" id="linkidfw0ntp"></td>
<td valign="top" style="height:20px;"  width="100%" class="nav_table" colspan="2"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="die_artikelzentrale.phtml">Die Artikelzentrale</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="0"><img src="img/leer.gif" width="8" height="20" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='content_parts_de.phtml';return false;" onMouseOver="MM_swapImage('linkidzefrGY','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td  colspan="3"><img src="img/leer.gif" width="1" height="1" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkidzefrGY" id="linkidzefrGY"></td>
<td valign="top" style="height:20px;"  width="100%" class="nav_table" colspan="2"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="content_parts_de.phtml">Content Parts</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="0"><img src="img/leer.gif" width="8" height="20" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='einfacher_text.phtml';return false;" onMouseOver="MM_swapImage('linkid12Tkhr','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td  colspan="4"><img src="img/leer.gif" width="1" height="1" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkid12Tkhr" id="linkid12Tkhr"></td>
<td valign="top" style="height:20px;"  width="100%" class="nav_table"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="einfacher_text.phtml">Einfacher Text</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="0"><img src="img/leer.gif" width="8" height="20" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='html_.phtml';return false;" onMouseOver="MM_swapImage('linkidEFEgb5','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td  colspan="4"><img src="img/leer.gif" width="1" height="1" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkidEFEgb5" id="linkidEFEgb5"></td>
<td valign="top" style="height:20px;"  width="100%" class="nav_table"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="html_.phtml">HTML</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="0"><img src="img/leer.gif" width="8" height="20" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='code_.phtml';return false;" onMouseOver="MM_swapImage('linkidhWwoID','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td  colspan="4"><img src="img/leer.gif" width="1" height="1" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkidhWwoID" id="linkidhWwoID"></td>
<td valign="top" style="height:20px;"  width="100%" class="nav_table"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="code_.phtml">Code</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="0"><img src="img/leer.gif" width="8" height="20" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='text_mit_bild.phtml';return false;" onMouseOver="MM_swapImage('linkidkI9kUi','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td  colspan="4"><img src="img/leer.gif" width="1" height="1" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkidkI9kUi" id="linkidkI9kUi"></td>
<td valign="top" style="height:20px;"  width="100%" class="nav_table"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="text_mit_bild.phtml">Text mit Bild</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="0"><img src="img/leer.gif" width="8" height="20" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='bilder.phtml';return false;" onMouseOver="MM_swapImage('linkidQdLmCL','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td  colspan="4"><img src="img/leer.gif" width="1" height="1" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkidQdLmCL" id="linkidQdLmCL"></td>
<td valign="top" style="height:20px;"  width="100%" class="nav_table"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="bilder.phtml">Bilder</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="0"><img src="img/leer.gif" width="8" height="20" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='aufzahlung.phtml';return false;" onMouseOver="MM_swapImage('linkidYfMI2I','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td  colspan="4"><img src="img/leer.gif" width="1" height="1" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkidYfMI2I" id="linkidYfMI2I"></td>
<td valign="top" style="height:20px;"  width="100%" class="nav_table"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="aufzahlung.phtml">Aufzählung</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="0"><img src="img/leer.gif" width="8" height="20" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='link_e-mail_.phtml';return false;" onMouseOver="MM_swapImage('linkidjcLtfY','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td  colspan="4"><img src="img/leer.gif" width="1" height="1" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkidjcLtfY" id="linkidjcLtfY"></td>
<td valign="top" style="height:20px;"  width="100%" class="nav_table"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="link_e-mail_.phtml">Link &amp; E-Mail</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="0"><img src="img/leer.gif" width="8" height="20" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='linkliste.phtml';return false;">
<td  colspan="4"><img src="img/leer.gif" width="1" height="1" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_2" alt="" border="" name="linkidgpdwEf" id="linkidgpdwEf"></td>
<td valign="top" style="height:20px;"  width="100%" class="nav_table_active"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="linkliste.phtml">Linkliste</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="0"><img src="img/leer.gif" width="8" height="20" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='artikellink.phtml';return false;" onMouseOver="MM_swapImage('linkidejNLXD','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td  colspan="4"><img src="img/leer.gif" width="1" height="1" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkidejNLXD" id="linkidejNLXD"></td>
<td valign="top" style="height:20px;"  width="100%" class="nav_table"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="artikellink.phtml">Artikellink</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="0"><img src="img/leer.gif" width="8" height="20" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='artikelmenu.phtml';return false;" onMouseOver="MM_swapImage('linkid73aoCf','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td  colspan="4"><img src="img/leer.gif" width="1" height="1" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkid73aoCf" id="linkid73aoCf"></td>
<td valign="top" style="height:20px;"  width="100%" class="nav_table"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="artikelmenu.phtml">Artikelmenü</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="0"><img src="img/leer.gif" width="8" height="20" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='multimedia_.phtml';return false;" onMouseOver="MM_swapImage('linkidHJTPw4','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td  colspan="4"><img src="img/leer.gif" width="1" height="1" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkidHJTPw4" id="linkidHJTPw4"></td>
<td valign="top" style="height:20px;"  width="100%" class="nav_table"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="multimedia_.phtml">Multimedia</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="0"><img src="img/leer.gif" width="8" height="20" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='dateiliste.phtml';return false;" onMouseOver="MM_swapImage('linkid3FoPGz','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td  colspan="4"><img src="img/leer.gif" width="1" height="1" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkid3FoPGz" id="linkid3FoPGz"></td>
<td valign="top" style="height:20px;"  width="100%" class="nav_table"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="dateiliste.phtml">Dateiliste</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="0"><img src="img/leer.gif" width="8" height="20" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='e-mail_formular.phtml';return false;" onMouseOver="MM_swapImage('linkidp5YCoa','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td  colspan="4"><img src="img/leer.gif" width="1" height="1" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkidp5YCoa" id="linkidp5YCoa"></td>
<td valign="top" style="height:20px;"  width="100%" class="nav_table"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="e-mail_formular.phtml">E-Mail Formular</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="0"><img src="img/leer.gif" width="8" height="20" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='newsletter_de.phtml';return false;" onMouseOver="MM_swapImage('linkidVNIrgn','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td  colspan="4"><img src="img/leer.gif" width="1" height="1" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkidVNIrgn" id="linkidVNIrgn"></td>
<td valign="top" style="height:20px;"  width="100%" class="nav_table"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="newsletter_de.phtml">Newsletter<img src="picture/myRT1/neuR.gif" alt="12/13/2004" border="0"></a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="0"><img src="img/leer.gif" width="8" height="20" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='suche_.phtml';return false;" onMouseOver="MM_swapImage('linkiddXOogH','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td  colspan="4"><img src="img/leer.gif" width="1" height="1" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkiddXOogH" id="linkiddXOogH"></td>
<td valign="top" style="height:20px;"  width="100%" class="nav_table"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="suche_.phtml">Suche</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="0"><img src="img/leer.gif" width="8" height="20" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='gastebuch_komm.phtml';return false;" onMouseOver="MM_swapImage('linkidIeIlqm','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td  colspan="4"><img src="img/leer.gif" width="1" height="1" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkidIeIlqm" id="linkidIeIlqm"></td>
<td valign="top" style="height:20px;"  width="100%" class="nav_table"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="gastebuch_komm.phtml">Gästebuch / Komm.</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="0"><img src="img/leer.gif" width="8" height="20" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='angebot.phtml';return false;" onMouseOver="MM_swapImage('linkidjRwqm8','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td  colspan="4"><img src="img/leer.gif" width="1" height="1" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkidjRwqm8" id="linkidjRwqm8"></td>
<td valign="top" style="height:20px;"  width="100%" class="nav_table"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="angebot.phtml">Angebot<img src="picture/myRT1/neuR.gif" alt="12/28/2004" border="0"></a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="0"><img src="img/leer.gif" width="8" height="20" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='ext._content_.phtml';return false;" onMouseOver="MM_swapImage('linkidXn7U1u','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td  colspan="4"><img src="img/leer.gif" width="1" height="1" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkidXn7U1u" id="linkidXn7U1u"></td>
<td valign="top" style="height:20px;"  width="100%" class="nav_table"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="ext._content_.phtml">Ext. Content</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="0"><img src="img/leer.gif" width="8" height="20" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='verwaltung_module.phtml';return false;" onMouseOver="MM_swapImage('linkidBLQNYY','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td  colspan="2"><img src="img/leer.gif" width="1" height="1" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkidBLQNYY" id="linkidBLQNYY"></td>
<td valign="top" style="height:20px;"  width="100%" class="nav_table" colspan="3"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="verwaltung_module.phtml">Module</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="0"><img src="img/leer.gif" width="8" height="20" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='dateien_hinzufuegen.phtml';return false;" onMouseOver="MM_swapImage('linkidvm6DjU','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td  colspan="2"><img src="img/leer.gif" width="1" height="1" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkidvm6DjU" id="linkidvm6DjU"></td>
<td valign="top" style="height:20px;"  width="100%" class="nav_table" colspan="3"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="dateien_hinzufuegen.phtml">Datei</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="0"><img src="img/leer.gif" width="8" height="20" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='verwaltung_nachricht.phtml';return false;" onMouseOver="MM_swapImage('linkidxUBibM','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td  colspan="2"><img src="img/leer.gif" width="1" height="1" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkidxUBibM" id="linkidxUBibM"></td>
<td valign="top" style="height:20px;"  width="100%" class="nav_table" colspan="3"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="verwaltung_nachricht.phtml">Nachricht</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="0"><img src="img/leer.gif" width="8" height="20" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='verwaltung_chat.phtml';return false;" onMouseOver="MM_swapImage('linkidiIF9IH','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td  colspan="2"><img src="img/leer.gif" width="1" height="1" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkidiIF9IH" id="linkidiIF9IH"></td>
<td valign="top" style="height:20px;"  width="100%" class="nav_table" colspan="3"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="verwaltung_chat.phtml">Chat</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="0"><img src="img/leer.gif" width="8" height="20" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='verwaltung_profil.phtml';return false;" onMouseOver="MM_swapImage('linkideJZmcs','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td  colspan="2"><img src="img/leer.gif" width="1" height="1" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkideJZmcs" id="linkideJZmcs"></td>
<td valign="top" style="height:20px;"  width="100%" class="nav_table" colspan="3"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="verwaltung_profil.phtml">Profil</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="0"><img src="img/leer.gif" width="8" height="20" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='fehlermeldungen.phtml';return false;" onMouseOver="MM_swapImage('linkidYLtKjv','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td ><img src="img/leer.gif" width="1" height="1" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkidYLtKjv" id="linkidYLtKjv"></td>
<td valign="top" style="height:20px;"  width="100%" class="nav_table" colspan="4"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="fehlermeldungen.phtml">Fehlermeldungen</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="0"><img src="img/leer.gif" width="8" height="20" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='suche.phtml';return false;" onMouseOver="MM_swapImage('linkidKQbYoP','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td ><img src="img/leer.gif" width="1" height="1" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkidKQbYoP" id="linkidKQbYoP"></td>
<td valign="top" style="height:20px;"  width="100%" class="nav_table" colspan="4"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="suche.phtml">Suche</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="0"><img src="img/leer.gif" width="8" height="20" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='kontakt.phtml';return false;" onMouseOver="MM_swapImage('linkidR89GW9','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td ><img src="img/leer.gif" width="1" height="1" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkidR89GW9" id="linkidR89GW9"></td>
<td valign="top" style="height:20px;"  width="100%" class="nav_table" colspan="4"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="kontakt.phtml">Kontakt</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="0"><img src="img/leer.gif" width="8" height="20" alt="" /></td>
</tr>
</table></td>
  </tr>
   <tr>
    <td style="padding:10px; color:#000000;"><img src="picture/seperate.gif" border="0" alt="" /><P>
	<a href="deutsche_version.phtml?id=285,212,0,0,1,0">Letzte Version:<br>
RC 1.1 - 27.08.2004a<br>
Vö: 6.11.2004<P>
Letzter Patch:<BR>
26.11.2004</a><P>
<img src="picture/seperate.gif" border="0" alt="" /></TD>
  </tr>
  <tr>
    <td align="center"><a target='_blank' href='./ads/adclick.php?bannerid=12&amp;zoneid=0&amp;source=&amp;dest=http%3A%2F%2Fjames.adbutler.de%2Fclick.php%3Fpid%3D5242%26tid%3D111647%26bid%3D23388&amp;ismap=' ><img src='http://james.adbutler.de/view.php?pid=5242&bid=23388&tid=111647&b=120&h=600&inv=img' width='120' height='600' border='0'></a><BR>WERBUNG<BR><BR><img src="picture/seperate.gif" border="0" alt="" /><P>
</td>
  </tr>
<tr>
    <td height="20">&nbsp;</td>
  </tr>
  <tr>
    <td align="center"></td>
  </tr>
  <tr>
    <td height="20">&nbsp;</td>
  </tr>
</table>


</body>
</html>
</td>
<td valign="top" width="555" bgcolor="#ffffff" class="maincontent"><img src="img/leer.gif" border="0" width="10" height="1" alt="" />
<BR>
<a href="deutsche_version.phtml">Deutsch</a> <span class="breadcrumb_spacer">&gt;</span> <a href="redaktion.phtml">Redaktion</a> <span class="breadcrumb_spacer">&gt;</span> <a href="die_artikelzentrale.phtml">Artikel</a> <span class="breadcrumb_spacer">&gt;</span> <a href="content_parts_de.phtml">Content Parts</a> <span class="breadcrumb_spacer">&gt;</span> Linkliste
<br>
<HR>
<br>
<a name="jump121"></a><span class="articleHead">Content Part &quot;Linkliste&quot;</span><img src="img/leer.gif" width="1" height="8" alt=""><br /><img src="img/leer.gif" width="1" height="25" alt="" /><br /><table width="158" border="0" cellspacing="0" cellpadding="0" align="left" class="table_class">
<tr><td class="image_td"><a href="zoom/MV8zMDVfTWFqT1JKTTJIaC5wbmc.html" onClick="window.open('zoom/MV8zMDVfTWFqT1JKTTJIaC5wbmc.html','previewpic','width=538,height=438');return false;.html"><img src="content/images/1_305_MajORJM2Hh-150x.png" width="150" height="122" border="0" class="image_img" alt="" /></a></td><td><img src="img/leer.gif" width="8" height="1" alt="" /></td></tr>
<tr><td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td></tr>
<tr><td align="center" bgcolor="FCFCFC" class="image_caption"><img src="img/leer.gif" width="1" height="3" alt="" /><br><img src="picture/icon_lupe_.gif" border="0" alt="" /><img src="content/gt/fb4f6e4639b2d7e2b19b7ea01fe84770.png" alt="Zoom" border="0" /><br><img src="img/leer.gif" width="1" height="3" alt="" /></td><td><img src="img/leer.gif" width="8" height="1" alt="" /></td></tr>
</table><div class="articleText"><TABLE cellSpacing=0 cellPadding=0 width="75%" border=0>
<TBODY>
<TR>
<TD><STRONG>Linkliste (optional):</STRONG> Geben Sie hier nach dem folgenden Muster die gewünschten Links ein: <BR><BR>Bezeichnung|Adresse <BR><BR>Geben Sie für jeden Link eine neue Zeile ein. Wenn Sie auf eine Mailadresse verlinken wollen, geben Sie vorher „mailto:“ ein, also z.B. „mailto:Info@MeineDomain.de“.<BR><BR>Eine Linkliste könnte beispielsweise so aussehen: <BR><BR>Info@MeineDomain.de|mailto:Info@MeineDomain.de <BR>www.MeineDomain.de|http://www.MeineDomain.de <BR><BR>Die Ausgabe wäre in diesem Falle folgende: <BR><BR>Info@MeineDomain.de <BR>www.MeineDomain.de&nbsp;<BR><BR>Um einen Link in einem neuen Browserfenster zu öffnen sieht der Linkaufbau wie folgt aus.<BR><BR>www.MeineDomain.de|http://www.MeineDomain.de _blank</TD></TR></TBODY></TABLE></div><div align="right"><a href="#top"><img src="img/article/top_link_0.gif" border="0" alt="" /></a></div>
<table width="100%"  border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td colspan="2"><HR></td>
  </tr>
  <tr>
    <td width="50%">Artikel erstellt: 24.August.2004</td>
    <td align="right" width="50%">Letzte Änderung: 13. Dezember 2004</td>
  </tr>
  <tr>
    <td colspan="2">&nbsp;</td>
  </tr>
  <tr>
    <td colspan="2" class="comment">Wenn sie einen Fehler entdecken eine Ergänzung oder Frage haben benutzen Sie bitte folgendes <a href="#" onClick="javascript:window.open('./content/pages/nachricht.htm','frage','width=400, height=250, screenX=440,screenY=200,menubar=no,statusbar=yes,scrollbar=yes,resizable=no');" target="" style="max-width:148px; overflow:hidden;"><u>formular</u></a>.<br><BR>
Hat Ihnen oder Ihrem Kunden diese Docu weitergeholfen ? Dann würde ich mich freuen wenn Sie das Projekt unterstützen würden. Bitte nutzen Sie dafür <a href="#paypal">PayPal</a> Link. Jeder Betrag ist möglich und hilft der Weiterentwicklung und Aktualisierung dieser Dokumentation.</td>
  </tr>
  <tr>

    <td colspan="2"><img src="img/leer.gif" border="0" width="10" height="10" alt="" /></td>
  </tr>
</table>
</td>
</tr>
<tr>
<td colspan="2" style="height:10px;"  bgcolor="#ffffff" class="footer"><table width="100%" height="20" background="img/footer.gif" cellpadding="0" cellspacing="0" border="0">
	<tr><td width="180" align="center" valign="middle"><strong>Besucher Online: <script language="JavaScript" type="text/javascript" src="./pphlogger/showhits.php?id=phpwcms&st=js&type=onlineusr"></script>
      </strong>
	</td>
	<td>
	<table width="100%"cellpadding="0" cellspacing="0" border="0">
   <tr>
    <td align="center"><a href="javascript:history.back();" target="_top" title="go back"><img src="picture/back_.gif" border="0" alt="Zurueck"><img src="content/gt/c7e1c82f133fb52f9aaa47af41a97c8b.png" alt="Zur&uuml;ck" border="0" /></a></td>
	<td align="center"><a href="sitemap_de.phtml"><img src="picture/sitemap_.gif" border="0"  alt="Sitemap"><img src="content/gt/d6ee999c57eae0a9d98b837870d624f7.png" alt="Sitemap" border="0" /></a></td>
	<td align="center"><a href="137.121.1.0.1.0.phtml" target="_blank"><img src="picture/print_.gif" border="0" alt="Drucken"><img src="content/gt/28402664cea5418ca197006e038523ec.png" alt="Drucken" border="0" /></a></td>
	<td align="center"><a href="gaestebuch.phtml"><img src="picture/icon_gaestebuch.gif" border="0" align="top" alt="Gästebuch"><img src="content/gt/f3ff723d70dc1fe73564e4c024c57156.png" alt="G&auml;stebuch" border="0" /></a></td>
	<td align="center"><a href="#" onClick="BookMark_Page();return false;" alt="" title=""><img src="picture/favoriten_.gif" border="0"  alt="Lesezeichen"><img src="content/gt/5287027c220f6dcbdffdde8d863971e2.png" alt="Lesezeichen" border="0" /></a></td>
    </tr>
</table></td>
	</tr>
</table>
<img src="img/leer.gif" border="0" width="760" height="10" alt="" />
</td>
</tr>
</table>
</body>
</html>