<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">

<!--

phpwcms | open source web content management system

          developed by Oliver Georgi (info@phpwcms.de)
          released under The GNU General Public License
          visit project page: http://www.phpwcms.de

          Release: 1.1-RC4 27-08-2004

//-->
<html>
<head>
<title></title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<META NAME="Title" CONTENT="Die phpWCMS Dokumentation">
<meta name="author" content="Oliver Frohnert">
<meta name="Publisher" content="Oliver Frohnert">
<meta name="Copyright" content="Oliver Frohnert">
<meta name="keywords" content="frohnert,documentation, dokumentation, phpwcms, cms. opensource, open source">
<meta name="description" content="Das Dokumentations Projekt für das Open Source CMS phpWCMS">
<meta name="Audience" content="Alle">
<meta name="Content-language" content="DE">
<META NAME="robots"      CONTENT="index,follow">
<META NAME="expires" CONTENT="0">
<meta name="revisit-after" content="7 days">
<meta name="resource-type" content="document">
<meta name="distribution" content="Global">
<meta name="generator" content="PHPWCMS">
<script language="JavaScript" type="text/javascript" src="pphlogger.js"></script>
<noscript><img alt="" src="./pphlogger/pphlogger.php?id=phpwcms&st=img"></noscript>
<meta name="keywords" content="*bearbeitet*">
<script src="template/inc_js/frontend.js" type="text/javascript"></script>
<link rel="stylesheet" type="text/css" href="template/inc_css/print_layout.css">
</head>

<body>
<img src="img/leer.gif" border="0" width="10" height="1" alt="" />
<BR>
<a href="deutsche_version.phtml">Deutsch</a> <span class="breadcrumb_spacer">&gt;</span> <a href="verwaltung_login.phtml">Die Docu</a> <span class="breadcrumb_spacer">&gt;</span> <a href="die_artikelzentrale.phtml">Artikel</a> <span class="breadcrumb_spacer">&gt;</span> <a href="content_parts_de.phtml">Content Parts</a> <span class="breadcrumb_spacer">&gt;</span> Gästebuch / Komm.
<br>
<HR>
<br>
<a name="jump152"></a><span class="articleHead">Content Part &quot;Gästebuch / Komm.&quot;</span><img src="img/leer.gif" width="1" height="8" alt=""><br /><img src="img/leer.gif" width="1" height="25" alt="" /><br /><table width="158" border="0" cellspacing="0" cellpadding="0" align="left" class="table_class">
<tr><td class="image_td"><a href="zoom/MV8zMzBfOFM5aGFEVGx3VC5wbmc.html" onClick="window.open('zoom/MV8zMzBfOFM5aGFEVGx3VC5wbmc.html','previewpic','width=538,height=356');return false;.html"><img src="content/images/1_330_8S9haDTlwT-150x.png" width="150" height="99" border="0" class="image_img" alt="" /></a></td><td><img src="img/leer.gif" width="8" height="1" alt="" /></td></tr>
<tr><td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td></tr>
<tr><td align="center" bgcolor="FCFCFC" class="image_caption"><img src="img/leer.gif" width="1" height="3" alt="" /><br><img src="picture/icon_lupe_.gif" border="0" alt="" /><img src="content/gt/fb4f6e4639b2d7e2b19b7ea01fe84770.png" alt="Zoom" border="0" /><br><img src="img/leer.gif" width="1" height="3" alt="" /></td><td><img src="img/leer.gif" width="8" height="1" alt="" /></td></tr>
</table><div class="articleText"><TABLE height=115 cellSpacing=0 cellPadding=0 width="75%" border=0>
<TBODY>
<TR>
<TD vAlign=top>Mit diesem Content Part können Sie sowohl ein Gästebuch als auch eine Kommentarfunktion für Ihre Seite erstellen. Durch Erstellen von Templates ist es möglich, ein Gästebuch zu erstellen und es auch in anderen Sprachen zur Verfügung zu stellen, ohne für jede Sprache ein eigenes Gästebuch anzulegen.</TD></TR></TBODY></TABLE></div><img src="img/leer.gif" width="1" height="15" alt="" /><br /><P>Folgende Einstellungen können Sie vornehmen:</P>
<P><strong>Anzeige:</strong> Sie können zwischen folgenden Optionen wählen:</P>
<P><strong>Alle zeigen:</strong> Es werden alle Einträge angezeigt.<BR><strong>Zeige:</strong> Tragen Sie hier die Anzahl der Einträge ein, die Sie<BR>pro Seite anzeigen wollen.</P>
<P><strong>Vorlage:</strong> Hier können Sie die Vorlage auswählen, die Sie für<BR>diesen Contentpart verwenden wollen. Die Datei "default.html" finden<BR>Sie hier: <i>template/inc_cntpart/guestbook/</i>.</P>
<P><STRONG><U><FONT color=#ff0000>Hinweis:</FONT></U></STRONG> Der Alias ID wird nur benötigt wenn Sie den <EM>Gästebuch/Komm. content part</EM> an anderer stelle nochmal benutzen wollen. Wie z.b. bei Mehrsprachigen Seiten. Andernfalls bleibt das Feld leer.</P>
<P><strong>Alias ID:</strong>&nbsp;<BR><BR>Wenn Sie bereits ein <EM>Gästebuch/Komm. content part</EM> erstellt haben und es an anderer Stelle nochmals einsetzen wollen - z.b. in einer anderen<BR>Sprache - tragen Sie hier die Artikel-ID des bereits erstellten<BR>Gästebuches ein. Diese finden Sie,&nbsp;in der in der übersicht der erstellten content parts des jeweiligen artikels. (siehe Bild).</P>
<P><div align="center"><img src="picture/gb_id_de.png" border="0" alt="" /></div></P>
<P>Wenn Ihr Hauptgästebuch z. B. die Artikel-ID 257 hat, tragen Sie<BR>die Artikel-ID 257 in das Feld ein, um es in einer anderen Ebene<BR>anzeigen zu können. Die Administration des Gästebuches erfolgt<BR>immer über das Haupt-Gästebuch.</P>
<P><strong>Wortsperre:</strong> Hier können Sie ein sogenannte "Bad Word List"<BR>erstellen. Tragen Sie hier die Worte ein, die nicht im Text des<BR>Verfassers zugelassen sind. Diese werden dann mit <strong>Bad Word</strong><BR>überschrieben.</P>
<P><strong>Flooding:</strong> Damit Ihr Gästebuch oder Kommentar-Contentpart<BR>nicht mit Einträgen von einer Person überschüttet werden kann,<BR>können Sie hier einen Cookie setzen. Der Standardwert des<BR>Cookies beträgt 24 Stunden.</P><div align="right"><a href="#top"><img src="img/article/top_link_0.gif" border="0" alt="" /></a></div>
<table width="100%"  border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td colspan="2"><HR></td>
  </tr>
  <tr>
    <td width="50%">Artikel erstellt: 2. September 2004</td>
    <td align="right" width="50%">Letzte Änderung: 14. Dezember 2004</td>
  </tr>
  <tr>
    <td colspan="2">&nbsp;</td>
  </tr>
  <tr>
    <td colspan="2" class="comment">Wenn sie einen Fehler entdecken eine Ergänzung oder Frage haben benutzen Sie bitte folgendes <a href="#" onClick="javascript:window.open('./content/pages/nachricht.htm','frage','width=400, height=250, screenX=440,screenY=200,menubar=no,statusbar=yes,scrollbar=yes,resizable=no');" target="" style="max-width:148px; overflow:hidden;"><u>formular</u></a>.<br><BR>
Hat Ihnen oder Ihrem Kunden diese Docu weitergeholfen ? Dann würde ich mich freuen wenn Sie das Projekt unterstützen würden. Bitte nutzen Sie dafür <a href="#paypal">PayPal</a> Link. Jeder Betrag ist möglich und hilft der Weiterentwicklung und Aktualisierung dieser Dokumentation.</td>
  </tr>
  <tr>

    <td colspan="2"><img src="img/leer.gif" border="0" width="10" height="10" alt="" /></td>
  </tr>
</table></body>
</html>