<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<!--
	phpwcms | free open source content management system
	created by Oliver Georgi (oliver at phpwcms dot de) and licensed under GNU/GPL.
	phpwcms is copyright 2003-2006 of Oliver Georgi. Extensions are copyright of\
	their respective owners. Visit project page for details: http://www.phpwcms.org/
//-->
<title></title>
  <meta http-equiv="content-type" content="text/html; charset=iso-8859-1" />
  <meta http-equiv="content-style-type" content="text/css" />
  <script src="template/inc_js/frontend.js" type="text/javascript"></script>
  <style type="text/css" media="all">
  /* <![CDATA[ */
    body {
      margin: 0;
      padding-top: 0;
      padding-bottom: 0;
      padding-left: 0;
      padding-right: 0;

    }
  /* ]]> */
  </style>
  <style type="text/css">
  /* <![CDATA[ */
    @import url("template/inc_css/frontend.css");
    @import url("template/inc_css/nlu_navi1_docu.css");
    @import url("template/inc_css/print_layout.css");
  /* ]]> */
  </style>
<script src="http://www.google-analytics.com/urchin.js" type="text/javascript">
</script>
<script type="text/javascript">
_uacct = "UA-361662-1";
urchinTracker();
</script>
<META NAME="Title" CONTENT="Die phpWCMS Dokumentation">
<meta name="author" content="Oliver Frohnert">
<meta name="Publisher" content="Oliver Frohnert">
<meta name="Copyright" content="Oliver Frohnert">
<meta name="keywords" content="frohnert,documentation, dokumentation, phpwcms, cms, opensource, open source">
<meta name="description" content="Das Dokumentations Projekt für das Open Source CMS phpWCMS">
<meta name="Audience" content="Alle">
<meta name="Content-language" content="DE">
<META NAME="robots"      CONTENT="index,follow">
<META NAME="expires" CONTENT="0">
<meta name="revisit-after" content="7 days">
<meta name="resource-type" content="document">
<meta name="distribution" content="Global">
<meta name="generator" content="PHPWCMS">
<META name="verify-v1" content="1ZpxZ7AZsjm7PxjqXQVus0eiUYqOsp5URTJn9q4KNz8=" />
  <!--[if lt IE 7]>
  <style type="text/css">
    body { behavior: url("template/inc_css/specific/csshover2.htc"); }
    img { behavior: url("template/inc_css/specific/pngbehavior.htc"); }
  </style>
  <![endif]-->
</head>
<body>
<img src="img/leer.gif" border="0" width="10" height="1" alt="" />
<br />
<a href="deutsche_version.phtml">Deutsch</a> <span class="breadcrumb_spacer">&gt;</span> <a href="die_docu.phtml">Die Docu</a> <span class="breadcrumb_spacer">&gt;</span> <a href="verwaltung_artikel.phtml">Artikel</a> <span class="breadcrumb_spacer">&gt;</span> <a href="content_parts_de.phtml">Content Parts</a> <span class="breadcrumb_spacer">&gt;</span> Bildwechsel
<br />
<HR>
<br />
<a name="jump150"></a><h1>Content Part &quot;Bilderwechsel&quot;</h1><div style="margin:25px 0 0 0; padding:0 0 0 0; clear:both;"></div><table width="158" border="0" cellspacing="0" cellpadding="0" align="left">
<tr><td class="image_td"><a href="zoom/Y2E4YWQxNjNiZDI4MjUwYmY3YTI4ODY4NmI0YmMzYzIucG5nP3dpZHRoPSI0MDAiIGhlaWdodD0iMzAwIg.html" onclick="checkClickZoom();clickZoom('zoom/Y2E4YWQxNjNiZDI4MjUwYmY3YTI4ODY4NmI0YmMzYzIucG5nP3dpZHRoPSI0MDAiIGhlaWdodD0iMzAwIg.html','previewpic','width.html');return false;.html"><img src="content/images/9a60b430fcedbff694e89deda01cf288.png" width="150" height="187" border="0" class="image_img" alt="bildwechsel.png" /></a></td><td><img src="img/leer.gif" width="8" height="1" border="0" alt="" /></td></tr>
</table><div class="articleText"><table height="210" cellspacing="0" cellpadding="0" width="70%" border="0">
    <tbody>
        <tr>
            <td valign="top">
            <p align="justify">Dies ist die Beschreibung des Content Parts &quot;Bilderwechsel&quot;.</p>
            <p align="justify">Mit diesem Content Part ist es m&ouml;glich eine Liste kleiner Vorschaubilder zu erzeugen, diese werden, wenn man mit dem Mauszeiger dr&uuml;berf&auml;hrt, als gro&szlig;e&nbsp;Bilder dargestellt.</p>
            </td>
        </tr>
    </tbody>
</table></div><hr/><table cellspacing="1" cellpadding="0" border="0">
    <tbody>
        <tr>
            <td bgcolor="#cccccc">
            <table cellspacing="1" cellpadding="5" border="0">
                <tbody>
                    <tr valign="top">
                        <td width="60" bgcolor="#ffffff" colspan="2">Vorlage:</td>
                        <td bgcolor="#ffffff" colspan="2">Hier k&ouml;nnen Sie eine Vorlage ausw&auml;hlen. Standardm&auml;&szlig;ig ist die default.tmpl vorhanden. Im Verzeichnis <em><strong>template/inc_cntpart/reference/</strong></em> k&ouml;nnen Sie diese Datei Ihren W&uuml;nschen entsprechend anpassen&nbsp;oder auch neue Vorlagen erstellen.</td>
                    </tr>
                    <tr valign="top">
                        <td width="60" bgcolor="#ffffff" colspan="2">Einf.Text:</td>
                        <td bgcolor="#ffffff" colspan="2">Hier k&ouml;nnen Sie einen Text eingeben, der neben dem&nbsp;Bildblock mit den kleinen Referenzbildern erscheinen soll.</td>
                    </tr>
                    <tr valign="top">
                        <td bgcolor="#ffffff" colspan="2"><!--StartFragment --><!--StartFragment -->Bild: </td>
                        <td bgcolor="#ffffff" colspan="2">W&auml;hlen Sie hiermit Ihre kleinen Referenzbilder aus. Die Bilder m&uuml;ssen sich innerhalb des Verzeichnisses /picture&nbsp;befinden.</td>
                    </tr>
                    <tr valign="top">
                        <td bgcolor="#ffffff" colspan="2">
                        <p align="left">Bildunterzeile:</p>
                        </td>
                        <td bgcolor="#ffffff" colspan="2">Geben Sie hier Text ein, der unterhalb des gro&szlig;en Referenzbildes erscheinen soll.</td>
                    </tr>
                    <tr>
                        <td bgcolor="#ffffff" colspan="2">Vergr&ouml;&szlig;ern:</td>
                        <td bgcolor="#ffffff" colspan="2">Mit dieser Funktion kann ein kleines Referenzbild&nbsp;per Klick auf das Bild vergr&ouml;&szlig;ert angezeigt werden.</td>
                    </tr>
                    <tr valign="top">
                        <td bgcolor="#ffffff" colspan="2">max. Breite:</td>
                        <td bgcolor="#ffffff" colspan="2">
                        <div align="left">Geben Sie hier die maximale Breite des grossen Referenzbildes ein.</div>
                        </td>
                    </tr>
                    <tr>
                        <td valign="top" bgcolor="#ffffff" colspan="2">max. H&ouml;he:</td>
                        <td bgcolor="#ffffff" colspan="2">Geben Sie hier die maximale H&ouml;he des grossen Referenzbildes ein.</td>
                    </tr>
                    <tr valign="top">
                        <td bgcolor="#ffffff" colspan="2">Rand:</td>
                        <td bgcolor="#ffffff" colspan="2">
                        <div align="left">Hier k&ouml;nnen Sie einen Rand um das gro&szlig;e Referenzbild einstellen<em>.</em></div>
                        </td>
                    </tr>
                    <tr valign="top">
                        <td bgcolor="#ffffff" colspan="2">Anordnung:</td>
                        <td bgcolor="#ffffff" colspan="2">
                        <p>Stellen Sie hier die Anordnung der kleinen Referenzbilder ein. </p>
                        <p>Folgende Werte sind m&ouml;glich:</p>
                        - horizontal<br/>
                        - vertikal
                        <p>Mit dem&nbsp;Dropdown-Feld k&ouml;nnen Sie angeben, wie die Ausrichtung der Bilder im Block erfolgen soll. Dabei entspricht die erste Angabe der horizontalen und die zweite der vertikalen Position:</p>
                        - default (center, middle)<br/>
                        - left, top<br/>
                        - left, middle<br/>
                        - left, bottom<br/>
                        - center, top<br/>
                        - center, middle<br/>
                        - center, bottom<br/>
                        - right, top<br/>
                        - right, middle<br/>
                        - right, bottom</td>
                    </tr>
                    <tr valign="top">
                        <td bgcolor="#ffffff" colspan="2">Block BxH:&nbsp; </td>
                        <td bgcolor="#ffffff" colspan="2">
                        <div align="left">Geben Sie hier die Breite und die H&ouml;he des Blocks an, in dem die kleinen Referenzbilder zu sehen sein sollen.</div>
                        </td>
                    </tr>
                    <tr valign="top">
                        <td bgcolor="#ffffff" colspan="2">Bildabstand:</td>
                        <td bgcolor="#ffffff" colspan="2">
                        <div align="left">Hier k&ouml;nnen Sie angeben, ob und welcher Bildabstand zwischen den kleinen Referenzbildern sein soll.</div>
                        </td>
                    </tr>
                    <tr valign="top">
                        <td bgcolor="#ffffff" colspan="2">Rand:</td>
                        <td bgcolor="#ffffff" colspan="2">
                        <div align="left">
                        <div align="left">Wenn ein Rand um diesen Block angezeigt werden soll, geben Sie bitte hier den Wert an.</div>
                        </div>
                        </td>
                    </tr>
                </tbody>
            </table>
            </td>
        </tr>
    </tbody>
</table>
<table width="100%"  border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td colspan="2"><HR></td>
  </tr>
  <tr>
    <td width="50%">Artikel erstellt: 2004/09/02</td>
    <td align="right" width="50%">Letzte Änderung:2005/05/29</td>
  </tr>
  <tr>
    <td colspan="2">&nbsp;</td>
  </tr>
  <tr>
    <td colspan="2" class="comment">Wenn Sie einen Fehler entdecken eine Ergänzung oder Frage haben benutzen Sie bitte folgendes <a href="#" onClick="javascript:window.open('./content/pages/nachricht.htm','frage','width=400, height=250, screenX=440,screenY=200,menubar=no,statusbar=yes,scrollbar=yes,resizable=no');" target="" style="max-width:148px; overflow:hidden;"><u>Formular</u></a>.<br /><br />
Hat Ihnen oder Ihrem Kunden diese Docu weitergeholfen ? Dann würde ich mich freuen wenn Sie das Projekt unterstützen würden. Bitte nutzen Sie dafür diesen <a href="#paypal">PayPal</a> Link. Jeder Betrag ist möglich und hilft der Weiterentwicklung und Aktualisierung dieser Dokumentation.<br />
Diese Seite nutzt die version:</td>
  </tr>
  <tr>

    <td colspan="2"><img src="img/leer.gif" border="0" width="10" height="10" alt="" /></td>
  </tr>
</table>

</body>
</html>