<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">

<!--

phpwcms | open source web content management system

          developed by Oliver Georgi (info@phpwcms.de)
          released under The GNU General Public License
          visit project page: http://www.phpwcms.de

          Release: 1.1-RC4 27-08-2004

//-->
<html>
<head>
<title></title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<META NAME="Title" CONTENT="The phpWCMS Documentation">
<meta name="author" content="Oliver Frohnert">
<meta name="Publisher" content="Oliver Frohnert">
<meta name="Copyright" content="Oliver Frohnert">
<meta name="keywords" content="frohnert,documentation, dokumentation, phpwcms, cms. opensource, open source">
<meta name="description" content="A Documentation Project for the  Open Source CMS phpWCMS">
<meta name="Audience" content="Alle">
<meta name="Content-language" content="EN">
<META NAME="robots"      CONTENT="index,follow">
<META NAME="expires" CONTENT="0">
<meta name="revisit-after" content="7 days">
<meta name="resource-type" content="document">
<meta name="distribution" content="Global">
<meta name="generator" content="PHPWCMS">
<script language="JavaScript" type="text/javascript" src="pphlogger.js"></script>
<noscript><img alt="" src="./pphlogger/pphlogger.php?id=phpwcms&st=img"></noscript>
<meta name="keywords" content="*NEW*">
<script src="template/inc_js/frontend.js" type="text/javascript"></script>
<link rel="stylesheet" type="text/css" href="template/inc_css/print_layout.css">
</head>

<body>
<img src="img/leer.gif" border="0" width="10" height="1" alt="" />
<BR>
<a href="english_version.phtml">English</a> <span class="breadcrumb_spacer">&gt;</span> <a href="311.0.0.1.0.0.phtml">The Docu</a> <span class="breadcrumb_spacer">&gt;</span> Message 
<br>
<HR>
<br>
<a name="jump207"></a><span class="articleHead">Messages</span><img src="img/leer.gif" width="1" height="8" alt=""><br /><table width="158" border="0" cellspacing="0" cellpadding="0" align="left" class="table_class">
<tr><td class="image_td"><a href="zoom/MV80OTBfWlVseWg4WnNFQy5wbmc.html" onClick="window.open('zoom/MV80OTBfWlVseWg4WnNFQy5wbmc.html','previewpic','width=767,height=397');return false;.html"><img src="content/images/1_490_ZUlyh8ZsEC-150x.png" width="150" height="78" border="0" class="image_img" alt="" /></a></td><td><img src="img/leer.gif" width="8" height="1" alt="" /></td></tr>
<tr><td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td></tr>
<tr><td align="center" bgcolor="FCFCFC" class="image_caption"><img src="img/leer.gif" width="1" height="3" alt="" /><br>click to enlarge<br><img src="img/leer.gif" width="1" height="3" alt="" /></td><td><img src="img/leer.gif" width="8" height="1" alt="" /></td></tr>
</table><div class="articleText">You can send in the administration level messages to other users. The handling of this function is really easy and clear. When you select the massage function, you get immediately a overview of your new, already read, deleted or created massages. Click for that only on the links for “new”, “old”.”sent” or “deleted”. The number in front of the link shows the amount of messages in the folder.</div>
<table width="100%"  border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td colspan="2"><HR></td>
  </tr>
  <tr>
    <td width="50%">Article created: 10. November 2004</td>
    <td align="right" width="50%">Last Changes: 6. Dezember 2004</td>
  </tr>
  <tr>
    <td colspan="2">&nbsp;</td>
  </tr>
  <tr>
    <td colspan="2" class="comment">In case you find any mistakes or have enhancments, please use this <a href="#" onClick="javascript:window.open('./content/pages/message.htm','frage','width=400, height=250, screenX=440,screenY=200,menubar=no,statusbar=yes,scrollbar=yes,resizable=no');" target="" style="max-width:148px; overflow:hidden;"><u>form</u></a> .<br><BR>
Have you found this website a helpful resource in understanding the Phpwcms content management system? If so, would you consider making a donation?  Please click here: <a href="#paypal">PayPal</a>. We welcome any donation amount. Your contribution helps make this website an even better resource and helps underwrite the associated server expenses of accomodating a growing number of visitors.</td>
  </tr>
  <tr>

    <td colspan="2"><img src="img/leer.gif" border="0" width="10" height="10" alt="" /></td>
  </tr>
</table></body>
</html>