<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">

<!--

phpwcms | open source web content management system

          developed by Oliver Georgi (info@phpwcms.de)
          released under The GNU General Public License
          visit project page: http://www.phpwcms.de

          Release: 1.1-RC4 27-08-2004

//-->
<html>
<head>
<title></title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<META NAME="Title" CONTENT="The phpWCMS Documentation">
<meta name="author" content="Oliver Frohnert">
<meta name="Publisher" content="Oliver Frohnert">
<meta name="Copyright" content="Oliver Frohnert">
<meta name="keywords" content="frohnert,documentation, dokumentation, phpwcms, cms. opensource, open source">
<meta name="description" content="A Documentation Project for the  Open Source CMS phpWCMS">
<meta name="Audience" content="Alle">
<meta name="Content-language" content="EN">
<META NAME="robots"      CONTENT="index,follow">
<META NAME="expires" CONTENT="0">
<meta name="revisit-after" content="7 days">
<meta name="resource-type" content="document">
<meta name="distribution" content="Global">
<meta name="generator" content="PHPWCMS">
<script language="JavaScript" type="text/javascript" src="pphlogger.js"></script>
<noscript><img alt="" src="./pphlogger/pphlogger.php?id=phpwcms&st=img"></noscript>
<meta name="keywords" content="*NEW*">
<script src="template/inc_js/frontend.js" type="text/javascript"></script>
<link rel="stylesheet" type="text/css" href="template/inc_css/print_layout.css">
</head>

<body>
<img src="img/leer.gif" border="0" width="10" height="1" alt="" />
<BR>
<a href="english_version.phtml">English</a> <span class="breadcrumb_spacer">&gt;</span> <a href="311.0.0.1.0.0.phtml">The Docu</a> <span class="breadcrumb_spacer">&gt;</span> Chat
<br>
<HR>
<br>
<a name="jump208"></a><span class="articleHead">Chat</span><br><span class="articleSubHead">Chat for writers</span><img src="img/leer.gif" width="1" height="8" alt=""><br /><img src="img/leer.gif" width="1" height="25" alt="" /><br /><table width="158" border="0" cellspacing="0" cellpadding="0" align="left" class="table_class">
<tr><td class="image_td"><a href="zoom/MV80ODZfN1IxbXFPSmhmZS5wbmc.html" onClick="window.open('zoom/MV80ODZfN1IxbXFPSmhmZS5wbmc.html','previewpic','width=770,height=400');return false;.html"><img src="content/images/1_486_7R1mqOJhfe-150x.png" width="150" height="78" border="0" class="image_img" alt="" /></a></td><td><img src="img/leer.gif" width="8" height="1" alt="" /></td></tr>
<tr><td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td></tr>
<tr><td align="center" bgcolor="FCFCFC" class="image_caption"><img src="img/leer.gif" width="1" height="3" alt="" /><br>click to enlarge<br><img src="img/leer.gif" width="1" height="3" alt="" /></td><td><img src="img/leer.gif" width="8" height="1" alt="" /></td></tr>
</table><div class="articleText">The backend-chat is for chats with many writers or administrators. If you wanna leave a massage for someone online, you can use the MASSAGES -function. You can use the chat as well as a kind of forum and every writer can leave there massages, wich can be directly be answered. This is possible because the history of the massages is stored in a database.<BR><BR><BR></div><img src="img/leer.gif" width="1" height="10" alt="" /><br /><HR><br /><img src="img/leer.gif" width="1" height="10" alt="" /><br><span class="contentHead">The Main Chat Window</span><br><img src="img/leer.gif" width="1" height="3" alt=""><br /><table width="158" border="0" cellspacing="0" cellpadding="0" align="left" class="table_class">
<tr><td class="image_td"><a href="zoom/MV80ODdfWFkyUm9JODJERy5wbmc.html" onClick="window.open('zoom/MV80ODdfWFkyUm9JODJERy5wbmc.html','previewpic','width=769,height=400');return false;.html"><img src="content/images/1_487_XY2RoI82DG-150x.png" width="150" height="78" border="0" class="image_img" alt="" /></a></td><td><img src="img/leer.gif" width="8" height="1" alt="" /></td></tr>
<tr><td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td></tr>
<tr><td align="center" bgcolor="FCFCFC" class="image_caption"><img src="img/leer.gif" width="1" height="3" alt="" /><br>click to enlarge<br><img src="img/leer.gif" width="1" height="3" alt="" /></td><td><img src="img/leer.gif" width="8" height="1" alt="" /></td></tr>
</table><div class="articleText">Click on "Click here to start the main Chat", to come to the Chat window.<BR><BR>Type your Message in the Field before send, and by press Enter or Click the Button <img src="picture/../img/button/send_chat_message.gif" border="0" alt="" />.&nbsp;<BR><BR>In the right upper corner you can set hwo many chatlines should be shown in the chat window.</div>
<table width="100%"  border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td colspan="2"><HR></td>
  </tr>
  <tr>
    <td width="50%">Article created: 10. November 2004</td>
    <td align="right" width="50%">Last Changes: 26. November 2004</td>
  </tr>
  <tr>
    <td colspan="2">&nbsp;</td>
  </tr>
  <tr>
    <td colspan="2" class="comment">In case you find any mistakes or have enhancments, please use this <a href="#" onClick="javascript:window.open('./content/pages/message.htm','frage','width=400, height=250, screenX=440,screenY=200,menubar=no,statusbar=yes,scrollbar=yes,resizable=no');" target="" style="max-width:148px; overflow:hidden;"><u>form</u></a> .<br><BR>
Have you found this website a helpful resource in understanding the Phpwcms content management system? If so, would you consider making a donation?  Please click here: <a href="#paypal">PayPal</a>. We welcome any donation amount. Your contribution helps make this website an even better resource and helps underwrite the associated server expenses of accomodating a growing number of visitors.</td>
  </tr>
  <tr>

    <td colspan="2"><img src="img/leer.gif" border="0" width="10" height="10" alt="" /></td>
  </tr>
</table></body>
</html>