<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">

<!--

phpwcms | open source web content management system

          developed by Oliver Georgi (info@phpwcms.de)
          released under The GNU General Public License
          visit project page: http://www.phpwcms.de

          Release: 1.1-RC4 27-08-2004

//-->
<html>
<head>
<title>the phpWCMS documentation / die phpWCMS dokumentation | File Administration</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<META NAME="Title" CONTENT="The phpWCMS Documentation">
<meta name="author" content="Oliver Frohnert">
<meta name="Publisher" content="Oliver Frohnert">
<meta name="Copyright" content="Oliver Frohnert">
<meta name="keywords" content="frohnert,documentation, dokumentation, phpwcms, cms. opensource, open source">
<meta name="description" content="A Documentation Project for the  Open Source CMS phpWCMS">
<meta name="Audience" content="Alle">
<meta name="Content-language" content="EN">
<META NAME="robots"      CONTENT="index,follow">
<META NAME="expires" CONTENT="0">
<meta name="revisit-after" content="7 days">
<meta name="resource-type" content="document">
<meta name="distribution" content="Global">
<meta name="generator" content="PHPWCMS">
<script language="JavaScript" type="text/javascript" src="pphlogger.js"></script>
<noscript><img alt="" src="./pphlogger/pphlogger.php?id=phpwcms&st=img"></noscript>
<script src="template/inc_js/frontend.js" type="text/javascript"></script>
<link rel="stylesheet" type="text/css" href="template/inc_css/frontend.css">
</head>

<body bgcolor="#FFFFFF" background="img/mainHg.gif" text="#000000" link="#FF9900" vlink="#FF9900" alink="#FF9900" topmargin="15" leftmargin="0" marginwidth="0" marginheight="0">
<table border="0" cellspacing="0" cellpadding="0" width="757" bgcolor="#ffffff" class="maintable" align="center">
<tr>
<td colspan="5" style="height:125px;"  bgcolor="#ffffff"><table bgcolor="#ffffff" border="0" cellpadding="0" cellspacing="0" width="757">
 <tr><td><img src="template/head_neu.jpg" width="757" height="118" alt="{docu}phpwcms{/docu}" border="0"></td></tr>
</table>

<table width="757" background="img/navBarBg.gif" cellpadding="0" cellspacing="0" border="0">
	<tr>	<td width="200" align="center" valign="middle">
	<a href="deutsche_version.phtml"><img src="picture/flags/de.gif" width="16" height="10" hspace="10" border="0" align="absmiddle" alt="Deutsche Version" title="Deutsche Version"></a>
	<a href="english_version.phtml"><img src="picture/flags/gb.gif" width="16" height="10" hspace="10" border="0" align="absmiddle" alt="English Version" title="English Version"></a>
	<img src="picture/flags/nl.gif" width="16" height="10" hspace="10" border="0" align="absmiddle" alt="Nederlandse versie in voorbereiding" title="Nederlandse versie in voorbereiding">
	<img src="picture/flags/pt.gif" width="16" height="10" hspace="10" border="0" align="absmiddle" alt="Português na preparação" title="Português na preparação">
</td>
	<td>
	<table width="100%" cellpadding="0" cellspacing="0" border="0">
  <tr>
    <td width="15" rowspan="2" valign="middle">&nbsp;</td>
	<td colspan="5" valign="middle" height="5"></td>
    <td width="35" rowspan="2" align="right"><a href="login.php"><img src="img/key.gif" border="0" align="top"></a></td>
  </tr>
  <tr>
      <td valign="middle"><a href="replacement_tags_en.phtml"><img src="picture/icon_links.gif" border="0" align="top" alt="Replacement Tags"><img src="content/gt/507208527a4e46a74b05efece3712fe6.png" alt="Replacement Tags" border="0" /></a></td>
    <td valign="middle"><a href="content_parts_en.phtml">
<img src="picture/icon_links.gif" border="0" align="top" alt="Content Parts"><img src="content/gt/159966e3e0b9e4afd20325fcbb8d548b.png" alt="Content Parts" border="0" /></a></td>
<td valign="middle"><a href="links_en.phtml"><img src="picture/icon_links.gif" border="0" align="top" alt="Links"><img src="content/gt/6a8f98fdc43ca47ff95547f8c2903e3d.png" alt="Links" border="0" /></a></td>
    <td valign="middle"><a href="imprint.phtml"><img src="picture/icon_impressum.gif" border="0" align="top" alt="Imprint"><img src="content/gt/08fa7c689023859645b9a58f0246f025.png" alt="Imprint" border="0" /></a></td>
    <td valign="middle"><a href="guestbook.phtml"><img src="picture/icon_gaestebuch.gif" border="0" align="top" alt="Guestbook"><img src="content/gt/dbef51efbc9de176f1c8c26d0975a46a.png" alt="Guestbook" border="0" /></a></td>
  </tr>
</table>	
	</td>
	</tr>
</table></td>
</tr>
<tr>
<td colspan="5" style="height:10px;"  bgcolor="#ffffff"><img src="img/leer.gif" width="1" height="10" alt="" /></td>
</tr>
<tr>
<td valign="top" width="190" bgcolor="#ffffff" class="mainleft"><img src="img/leer.gif" border="0" width="180" height="1" alt="" />
<table border="0" width="100%" cellspacing="0" cellpadding="0">
<tr bgcolor="#FFFFFF" style="cursor:pointer;cursor:hand;" onClick="location.href='205.0.0.1.0.0.phtml';return false;" onMouseOver="MM_swapImage('linkid29s6w8','','img/pfeil20x20_2',1);this.bgColor='#D3ED7D';" onMouseOut="MM_swapImgRestore();this.bgColor='#FFFFFF';">
<td ><img src="img/leer.gif" width="1" height="1" alt="" /></td>
<td valign="top"><img src="img/pfeil20x20_1.gif" alt="" border="" name="linkid29s6w8" id="linkid29s6w8"></td>
<td valign="top" style="height:20px;"  width="100%" class="nav_table" colspan="3"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="205.0.0.1.0.0.phtml">Administration</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="0"><img src="img/leer.gif" width="8" height="20" alt="" /></td>
</tr>
<tr bgcolor="#FFFFFF" style="cursor:pointer;cursor:hand;" onClick="location.href='layout_en.phtml';return false;" onMouseOver="MM_swapImage('linkid4lOGbx','','img/pfeil20x20_2',1);this.bgColor='#D3ED7D';" onMouseOut="MM_swapImgRestore();this.bgColor='#FFFFFF';">
<td ><img src="img/leer.gif" width="1" height="1" alt="" /></td>
<td valign="top"><img src="img/pfeil20x20_1.gif" alt="" border="" name="linkid4lOGbx" id="linkid4lOGbx"></td>
<td valign="top" style="height:20px;"  width="100%" class="nav_table" colspan="3"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="layout_en.phtml">Layout</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="0"><img src="img/leer.gif" width="8" height="20" alt="" /></td>
</tr>
<tr bgcolor="#FFFFFF" style="cursor:pointer;cursor:hand;" onClick="location.href='editorial.phtml';return false;" onMouseOver="MM_swapImage('linkidYHJjHh','','img/pfeil20x20_2',1);this.bgColor='#D3ED7D';" onMouseOut="MM_swapImgRestore();this.bgColor='#FFFFFF';">
<td ><img src="img/leer.gif" width="1" height="1" alt="" /></td>
<td valign="top"><img src="img/pfeil20x20_1.gif" alt="" border="" name="linkidYHJjHh" id="linkidYHJjHh"></td>
<td valign="top" style="height:20px;"  width="100%" class="nav_table" colspan="3"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="editorial.phtml">Editorial</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="0"><img src="img/leer.gif" width="8" height="20" alt="" /></td>
</tr>
<tr bgcolor="#FFFFFF" style="cursor:pointer;cursor:hand;" onClick="location.href='adminbackend.phtml';return false;" onMouseOver="MM_swapImage('linkidszol85','','img/pfeil20x20_2',1);this.bgColor='#D3ED7D';" onMouseOut="MM_swapImgRestore();this.bgColor='#FFFFFF';">
<td  colspan="2"><img src="img/leer.gif" width="1" height="1" alt="" /></td>
<td valign="top"><img src="img/pfeil20x20_1.gif" alt="" border="" name="linkidszol85" id="linkidszol85"></td>
<td valign="top" style="height:20px;"  width="100%" class="nav_table" colspan="2"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="adminbackend.phtml">Administration (Backend)</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="0"><img src="img/leer.gif" width="8" height="20" alt="" /></td>
</tr>
<tr bgcolor="#FFFFFF" style="cursor:pointer;cursor:hand;" onClick="location.href='deutsche_version.phtml?the_article_center';return false;" onMouseOver="MM_swapImage('linkidDSM9r1','','img/pfeil20x20_2',1);this.bgColor='#D3ED7D';" onMouseOut="MM_swapImgRestore();this.bgColor='#FFFFFF';">
<td  colspan="2"><img src="img/leer.gif" width="1" height="1" alt="" /></td>
<td valign="top"><img src="img/pfeil20x20_1.gif" alt="" border="" name="linkidDSM9r1" id="linkidDSM9r1"></td>
<td valign="top" style="height:20px;"  width="100%" class="nav_table" colspan="2"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="deutsche_version.phtml?the_article_center">Article</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="0"><img src="img/leer.gif" width="8" height="20" alt="" /></td>
</tr>
<tr bgcolor="#FFFFFF" style="cursor:pointer;cursor:hand;" onClick="location.href='deutsche_version.phtml?File_Administration';return false;" onMouseOver="MM_swapImage('linkidFeEbBo','','img/pfeil20x20_2',1);this.bgColor='#D3ED7D';" onMouseOut="MM_swapImgRestore();this.bgColor='#FFFFFF';">
<td  colspan="2"><img src="img/leer.gif" width="1" height="1" alt="" /></td>
<td valign="top"><img src="img/pfeil20x20_1.gif" alt="" border="" name="linkidFeEbBo" id="linkidFeEbBo"></td>
<td valign="top" style="height:20px;"  width="100%" class="nav_table" colspan="2"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="deutsche_version.phtml?File_Administration">File</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="0"><img src="img/leer.gif" width="8" height="20" alt="" /></td>
</tr>
<tr bgcolor="#FFFFFF" style="cursor:pointer;cursor:hand;" onClick="location.href='file_administration.phtml';return false;">
<td  colspan="3"><img src="img/leer.gif" width="1" height="1" alt="" /></td>
<td valign="top"><img src="img/pfeil20x20_2" alt="" border="" name="linkidD90nqa" id="linkidD90nqa"></td>
<td valign="top" style="height:20px;"  width="100%" class="nav_table_active"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="file_administration.phtml">File Administration</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="0"><img src="img/leer.gif" width="8" height="20" alt="" /></td>
</tr>
<tr bgcolor="#FFFFFF" style="cursor:pointer;cursor:hand;" onClick="location.href='create_dir.phtml';return false;" onMouseOver="MM_swapImage('linkidAHNdWF','','img/pfeil20x20_2',1);this.bgColor='#D3ED7D';" onMouseOut="MM_swapImgRestore();this.bgColor='#FFFFFF';">
<td  colspan="3"><img src="img/leer.gif" width="1" height="1" alt="" /></td>
<td valign="top"><img src="img/pfeil20x20_1.gif" alt="" border="" name="linkidAHNdWF" id="linkidAHNdWF"></td>
<td valign="top" style="height:20px;"  width="100%" class="nav_table"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="create_dir.phtml">Create directory</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="0"><img src="img/leer.gif" width="8" height="20" alt="" /></td>
</tr>
<tr bgcolor="#FFFFFF" style="cursor:pointer;cursor:hand;" onClick="location.href='upload_files.phtml';return false;" onMouseOver="MM_swapImage('linkidyNxo5c','','img/pfeil20x20_2',1);this.bgColor='#D3ED7D';" onMouseOut="MM_swapImgRestore();this.bgColor='#FFFFFF';">
<td  colspan="3"><img src="img/leer.gif" width="1" height="1" alt="" /></td>
<td valign="top"><img src="img/pfeil20x20_1.gif" alt="" border="" name="linkidyNxo5c" id="linkidyNxo5c"></td>
<td valign="top" style="height:20px;"  width="100%" class="nav_table"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="upload_files.phtml">Upload files</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="0"><img src="img/leer.gif" width="8" height="20" alt="" /></td>
</tr>
<tr bgcolor="#FFFFFF" style="cursor:pointer;cursor:hand;" onClick="location.href='manage_files.phtml';return false;" onMouseOver="MM_swapImage('linkidqJifeh','','img/pfeil20x20_2',1);this.bgColor='#D3ED7D';" onMouseOut="MM_swapImgRestore();this.bgColor='#FFFFFF';">
<td  colspan="3"><img src="img/leer.gif" width="1" height="1" alt="" /></td>
<td valign="top"><img src="img/pfeil20x20_1.gif" alt="" border="" name="linkidqJifeh" id="linkidqJifeh"></td>
<td valign="top" style="height:20px;"  width="100%" class="nav_table"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="manage_files.phtml">Manage Files</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="0"><img src="img/leer.gif" width="8" height="20" alt="" /></td>
</tr>
<tr bgcolor="#FFFFFF" style="cursor:pointer;cursor:hand;" onClick="location.href='profile.phtml';return false;" onMouseOver="MM_swapImage('linkidsDmEjz','','img/pfeil20x20_2',1);this.bgColor='#D3ED7D';" onMouseOut="MM_swapImgRestore();this.bgColor='#FFFFFF';">
<td  colspan="2"><img src="img/leer.gif" width="1" height="1" alt="" /></td>
<td valign="top"><img src="img/pfeil20x20_1.gif" alt="" border="" name="linkidsDmEjz" id="linkidsDmEjz"></td>
<td valign="top" style="height:20px;"  width="100%" class="nav_table" colspan="2"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="profile.phtml">Profile</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="0"><img src="img/leer.gif" width="8" height="20" alt="" /></td>
</tr>
<tr bgcolor="#FFFFFF" style="cursor:pointer;cursor:hand;" onClick="location.href='error_messages.phtml';return false;" onMouseOver="MM_swapImage('linkidyhH7EL','','img/pfeil20x20_2',1);this.bgColor='#D3ED7D';" onMouseOut="MM_swapImgRestore();this.bgColor='#FFFFFF';">
<td ><img src="img/leer.gif" width="1" height="1" alt="" /></td>
<td valign="top"><img src="img/pfeil20x20_1.gif" alt="" border="" name="linkidyhH7EL" id="linkidyhH7EL"></td>
<td valign="top" style="height:20px;"  width="100%" class="nav_table" colspan="3"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="error_messages.phtml">Error messages</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="0"><img src="img/leer.gif" width="8" height="20" alt="" /></td>
</tr>
<tr bgcolor="#FFFFFF" style="cursor:pointer;cursor:hand;" onClick="location.href='search.phtml';return false;" onMouseOver="MM_swapImage('linkidDWjMBZ','','img/pfeil20x20_2',1);this.bgColor='#D3ED7D';" onMouseOut="MM_swapImgRestore();this.bgColor='#FFFFFF';">
<td ><img src="img/leer.gif" width="1" height="1" alt="" /></td>
<td valign="top"><img src="img/pfeil20x20_1.gif" alt="" border="" name="linkidDWjMBZ" id="linkidDWjMBZ"></td>
<td valign="top" style="height:20px;"  width="100%" class="nav_table" colspan="3"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="search.phtml">Search</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="0"><img src="img/leer.gif" width="8" height="20" alt="" /></td>
</tr>
<tr bgcolor="#FFFFFF" style="cursor:pointer;cursor:hand;" onClick="location.href='contact.phtml';return false;" onMouseOver="MM_swapImage('linkid5rfsRz','','img/pfeil20x20_2',1);this.bgColor='#D3ED7D';" onMouseOut="MM_swapImgRestore();this.bgColor='#FFFFFF';">
<td ><img src="img/leer.gif" width="1" height="1" alt="" /></td>
<td valign="top"><img src="img/pfeil20x20_1.gif" alt="" border="" name="linkid5rfsRz" id="linkid5rfsRz"></td>
<td valign="top" style="height:20px;"  width="100%" class="nav_table" colspan="3"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="contact.phtml">Contact</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="0"><img src="img/leer.gif" width="8" height="20" alt="" /></td>
</tr>
</table>
<img src="img/leer.gif" border="0" width="1" height="50" alt="" />
<table width="170"  border="0" align="center">
  <tr>
    <td class="kasten"><div align="center"><strong>New Articles</strong></div></td>
  </tr>
  <tr>
    <td></td>
  </tr>
  <tr>
    <td class="kasten"><div class="related"><a href="236.202.0.0.1.0.phtml">Search and delete files</a><div class=line></div><a href="235.201.0.0.1.0.phtml">Manage Files</a><div class=line></div><a href="233.199.0.0.1.0.phtml">Create Directory</a><div class=line></div><a href="209.196.0.0.1.0.phtml">Database Backup</a><div class=line></div><a href="222.197.0.0.1.0.phtml">Administration (Backend)</a></div></td>
  </tr>
  <tr>
    <td height=25></td>
  </tr>
  <tr>
    <td class="kasten"><div align="center"><strong>Edited Articles</strong></div></td>
  </tr>
  <tr>
    <td></td>
  </tr>
  <tr>
    <td class="kasten"><div align="left"><div class="related"><a href="207.48.0.0.1.0.phtml">phpWCMS Installation tutorial</a><div class=line></div><a href="106.144.0.0.1.0.phtml">Global Error messages</a><div class=line></div><a href="119.69.0.0.1.0.phtml">Creating New Articles</a><div class=line></div><a href="168.155.0.0.1.0.phtml">The Guestbook / Comments Content Part</a><div class=line></div><a href="216.173.0.0.1.0.phtml">Editing Entries</a></div></div></td>
  </tr>
</table></td>
<td valign="top" width="15" bgcolor="#ffffff"><img src="img/leer.gif" width="15" height="1" alt="" /></td>
<td valign="top" width="538" bgcolor="#ffffff"><a href="english_version.phtml">English</a> <span class="breadcrumb_spacer">&gt;</span> <a href="editorial.phtml">Editorial</a> <span class="breadcrumb_spacer">&gt;</span> <a href="deutsche_version.phtml?File_Administration">File</a> <span class="breadcrumb_spacer">&gt;</span> File Administration
<br />
<img src="picture/img/line-dotted-540.gif" border="0" alt="" />
<br>
<a name="jump184"></a><span class="articleHead">File Administration</span><br><span class="articleSubHead">Administer and add files</span><img src="img/leer.gif" width="1" height="8" alt=""><br /><img src="img/leer.gif" width="1" height="15" alt="" /><br /><table width="158" border="0" cellspacing="0" cellpadding="0" align="left" class="table_class">
<tr><td class="image_td"><a href="zoom/MV80NjJfcmV4a1RoSklNSy5wbmc.html" onClick="window.open('zoom/MV80NjJfcmV4a1RoSklNSy5wbmc.html','previewpic','width=538,height=312');return false;.html"><img src="content/images/1_462_rexkThJIMK-150x.png" width="150" height="87" border="0" class="image_img" alt="" /></a></td><td><img src="img/leer.gif" width="8" height="1" alt="" /></td></tr>
<tr><td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td></tr>
<tr><td align="left" bgcolor="FCFCFC" class="image_caption"><img src="img/leer.gif" width="1" height="3" alt="" /><br>click to enlarge<br><img src="img/leer.gif" width="1" height="3" alt="" /></td><td><img src="img/leer.gif" width="8" height="1" alt="" /></td></tr>
</table><div class="articleText"><P align=left>It is very easy to upload pictures, files and documents with the built-in data management of phpWCMS. These files can be used in different articles. The data management creates a windows-like folder structure. You can easily create folders and unblock them for all editors or just for yourself. It is easy to upload files from your hard drive.<BR><BR>Standard documents like Microsoft Word or PDF will be shown with the well known standard icons. Pictures in all current formats will be shown by a thumbnail. <BR>Try it; the data-manager is really easy to use. </P>
<P align=left>
<TABLE style="WIDTH: 100%" cellSpacing=1 cellPadding=1 border=0>
<TBODY>
<TR vAlign=top>
<TD><IMG alt="Upload Button" src="img/button/upload_13x13.gif" border=0><BR><img src="img/leer.gif" border="0" width="30" height="1" alt="" /></TD>
<TD>Click here to upload the file in the root-directory.</TD></TR>
<TR>
<TD><IMG alt="Verzeichniss anlegen" src="img/button/add_13x13.gif" border=0></TD>
<TD>Click here to create a new folder.</TD></TR>
<TR>
<TD><IMG alt="Englische Hilfe" src="img/button/help_22x13.gif" border=0></TD>
<TD>Click here to get a legend with all current icons</TD></TR>
<TR>
<TD><IMG alt="Alle Verzeichnisse aufklappen" src="img/button/alle_auf.gif" border=0></TD>
<TD>Click here to open all folders.</TD></TR>
<TR>
<TD><IMG alt="Alle Verzeichnisse zuklappen" src="img/button/alle_zu.gif" border=0></TD>
<TD>Click here to close all folders</TD></TR>
<TR>
<TD><IMG alt="Thumbnails ausblenden" src="img/button/thumbnail_13x13_0.gif" border=0></TD>
<TD>Click here to see the files as a list (without thumbnails)</TD></TR></TBODY></TABLE></P></div><HR>
<br />
29. Oktober 2004 - 09:11 by <a href="mailto:Jan@docu.fhss.de">Jan</a>
<br /><br /></td>
<td valign="top" width="4" bgcolor="#ffffff"><img src="img/leer.gif" width="4" height="1" alt="" /></td>
<td valign="top"></td>
</tr>
<tr>
<td colspan="5" style="height:10px;"  bgcolor="#ffffff"><img src="img/leer.gif" width="1" height="10" alt="" /></td>
</tr>
<tr>
<td colspan="5" style="height:10px;"  bgcolor="#ffffff" class="footer"><table width="757"height="20" background="img/navBarBg.gif" cellpadding="0" cellspacing="0" border="0">
	<tr><td width="200" align="center" valign="middle">
	<strong>User Online: <script language="JavaScript" type="text/javascript" src="./pphlogger/showhits.php?id=phpwcms&st=js&type=onlineusr"></script>
      </strong>
	</td>
	<td>
	<table width="100%" cellpadding="0" cellspacing="0" border="0">
  <tr>
    <td width="15" rowspan="2" valign="middle">&nbsp;</td>
	<td colspan="5" valign="middle" height="3"></td>
  </tr>
  <tr>
    <td valign="middle" align="left"><a href="#top"><img src="picture/top_link_.gif" border="0" alt="" /></a></td>
    <td valign="middle" align="left"><a href="javascript:history.back();" target="_top" title="go back"><img src="picture/back_link_en.gif" border="0" alt="" /></a></td>
    <td valign="middle" align="right"><a href="sitemap_en.phtml"><img src="picture/sitemap_link_.gif" border="0" alt="" /></td>
    <td valign="middle" align="right"><a href="232.184.1.0.1.0.phtml" target="_blank"><img src="picture/print_link_en.gif" border="0" alt="" /></a></td>
	<td valign="middle" align="right"><a href="#" onClick="BookMark_Page();return false;" alt="" title=""><img src="picture/favoriten_link_.gif" border="0" alt="" /></a></td>
    </tr>
</table>	
	</td>
	</tr>
</table>
<img src="img/leer.gif" border="0" width="757" height="10" alt="" /></td>
</tr>
</table>
</body>
</html>