<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<!--
	phpwcms | free open source content management system
	created by Oliver Georgi (oliver at phpwcms dot de) and licensed under GNU/GPL.
	phpwcms is copyright 2003-2007 of Oliver Georgi. Extensions are copyright of
	their respective owners. Visit project page for details: http://www.phpwcms.org/
//-->
<title>phpwcms-docu for  phpwcms :: web based content management system | News | phpWCMS docu News{D:7/28/2007,7,editR.gif}</title>
  <meta http-equiv="content-type" content="text/html; charset=iso-8859-1" />
  <meta http-equiv="content-style-type" content="text/css" />
  <script src="template/inc_js/frontend.js" type="text/javascript"></script>
  <style type="text/css">
  <!-- 
    @import url("template/inc_css/mpl_frontend.css");
    @import url("template/inc_css/mpl_menu.css");
    @import url("template/inc_css/mpl_objects.css");
    @import url("template/inc_css/mpl_docu_en.css");
  //-->
  </style>
<meta name="Title" content="The phpWCMS Documentation" />
<meta name="author" content="Oliver Frohnert, Mario Perez Leal" />
<meta name="Publisher" content="Oliver Frohnert, Mario Perez Leal, creacion" />
<meta name="Copyright" content="Oliver Frohnert, Mario Perez Leal, creacion" />
<meta name="keywords" content="frohnert, perez leal, creacion, documentation, dokumentation, phpwcms, cms, opensource, open source, docu" />
<meta name="description" content="A Documentation Project for the  Open Source CMS phpWCMS" />
<meta name="Audience" content="Alle" />
<meta name="Content-language" content="EN" />
<meta name="robots"      content="index,follow" />
<meta name="expires" content="0" />
<meta name="revisit-after" content="7 days" />
<meta name="resource-type" content="document" />
<meta name="distribution" content="Global" />
<meta name="generator" content="PHPWCMS" />

  <!--[if lt IE 7]>
  <style type="text/css">
    body { behavior: url("template/inc_css/specific/csshover2.htc"); }
    img { behavior: url("template/inc_css/specific/pngbehavior.htc"); }
  </style>
  <![endif]-->
</head>
<body id="myid_286">
<div id="container"><a name="top" id="top"></a>


	<div id="head">
		
	<div id="mainnavi">
		<div class="fleft"><a href="english_version.phtml">Home</a> | <span style="text-decoration:none;font-weight:bold;"><a href="news_en.phtml">News</a></span> | <a href="the_docu.phtml">The Docu</a> | <a href="Usefull_Links_and_Tools.phtml">Links &amp; Tools</a> | <a href="contact.phtml">Contact</a> | <a href="faq_en.phtml">FAQ</a> | <a href="http://forum.phpwcms.org/" target="_blank">Forum</a> | <a href="howto_en.phtml">HowTo</a></div>				
		<div class="sys">Tuesday, 13. October 2015<img src="img/leer.gif" border="0" width="5" height="1" alt="" />|<img src="img/leer.gif" border="0" width="5" height="1" alt="" />2 User online<img src="img/leer.gif" border="0" width="10" height="1" alt="" />
		<a href="deutsche_version.phtml" title="Deutsche Version"><img src="picture/../template/lang/all/flag_de.gif" border="0" alt="" /></a>
		<a href="english_version.phtml"  title="English version"><img src="picture/../template/lang/all/flag_en.gif" border="0" alt="" /></a>
		</div>
	</div>
	
	<a href="./" title="phpwcms-docu Startseite aufrufen" class="homelink">
	<span>&raquo; phpwcms-docu startpage</span></a>
	<h2>phpwcms-docu - Documentation for the Web Content Management System phpwcms</h2>
	<p>This website is targeted both to the beginner and the lateral entry following the goal to simplify the 
work with phpwcms and to focus on the essentials things.</p>
	</div>

	
	<div id="left">
	<div class="leftnav" style="margin-top:24px;">
	
		
	</div> 
	</div> 
	  
	<div id="right">
		<div style="margin-top:24px;">			
		<form action="#" method="post" name="searchFE" onsubmit="s=document.getElementById('customSearchInput');if(s.value=='Search')return false;">
			<table width="100%" border="0" cellpadding="0" cellspacing="0">
			<tr>
					<td><input type="text" name="search_input_field" size="20" maxlength="200" id="customSearchInput" class="customSearchInput" value="" onfocus="if(this.value=='Search')this.value='';" onblur="if(this.value=='')this.value='Search';"/></td>
					<td><input type="image" name="search_go" onfocus="this.blur();" title="Search" src="/template/lang/all/submit.gif" /></td>
				</tr>
			</table>
			</form>
			
			      <script type="text/javascript" language="javascript">
			  <!-- 
			        document.getElementById("customSearchInput").value="Search";
			  //-->
			      </script>
				  
<!-- <p style="margin-top:10px;">Change font size: <a href="[FontSize-]"><img src="template/lang/all/icons/reduce.gif" width="18" height="17" alt="" title="Small" border="0" /></a>
			<a href="[FontSize+]"><img src="template/lang/all/icons/extend.gif" width="18" height="17" alt="" title="Bigger" border="0" /></a>
			</p> -->
			
	


<!-- <a href="http://validator.w3.org/check?uri=http%3A%2F%2Fwww.phpwcms-docu.de%2Findex.php%3Fdeutsche_version" title="W3C Standard XHTML" target="_blank"><img src="picture/w3c/w3c_xhtml.gif" border="0" alt="" /></a>
<a href="http://jigsaw.w3.org/css-validator/validator?uri=http://www.phpwcms-docu.de" title="W3C Standard CSS" target="_blank"><img src="picture/w3c/w3c_css.gif" border="0" alt="" /></a><br />			
<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div> -->
		
<div style="margin-top:10px; margin-bottom:15px;"></div>
	
</div>

	</div> 
	
	<div id="content">
	<div id="bread">You are here: <a href="english_version.phtml">English</a> <span class="breadcrumb_spacer">&gt;</span> News</div>
		
		<a name="jump216"></a><!-- Livedate: 09.09.2004 12:01:54 / Killdate: 31.12.2030 23:59:59 -->
<h1>phpWCMS docu News</h1>


<h4>Wanna Help?</h4>

<p>Do you have fun to help at the docu page?<br />
<br />
At the moment we are looking for people who have fun to translate articles. <strike>Following articles wait for a translation into the english language. </strike><br />
<br />
thanks to jscholtysik <br />
<br />
<br />
<br />
If you want to help us send us a short mail via the following form with the article you want to translate. <br />
<br />
Thanks in advance.</p>
<div style="margin:10px 0 0 0;padding:0;" class="spaceBeforeCP"></div><div class="contact_form"><form name="phpwcmsForm1624" id="phpwcmsForm1624" action="deutsche_version.phtml?id=286,216,0,0,1,0" method="post" enctype="multipart/form-data">
<table cellspacing="0" cellpadding="3">
<tr><td colspan="2">
<div style="margin-bottom: 10px;">

<fieldset style="width: 505px; border: #cccccc 1px solid; margin: 0; padding: 0;" class="clearfix">
<legend> <b>General hint</b> </legend>
<div style="float: left; padding: 5px 0px 5px 5px;">
Please fill out all fields marked with a <strong>*</strong> !  Thank you.<br />
<font color="#cc3300">





</font>
</div>
</fieldset>
</div>
</td></tr>
<tr><td><b>First name *</b><br />
<input type="text" name="Vorname" id="Vorname" value="" size="30" style="width: 250px; margin: 2px 0px 2px 0px; padding-left: 3px;" />
</td><td>
<b>Last name *</b><br />
<input type="text" name="Nachname" id="Nachname" value="" size="30" style="width: 250px; margin: 2px 0px 2px 0px; padding-left: 3px;" />
</td></tr><tr><td>
<b>{LABEL:E-mail}</b><br />
{E-mail}
</td><td>
 
</td></tr><tr><td colspan="2">
<b>Your message</b><br />
<textarea name="Nachricht" id="Nachricht" cols="30" rows="3" style="width: 505px; margin: 2px 0px 10px 0px; padding-left: 3px;"></textarea>
</td></tr>
<tr><td colspan="2">

<fieldset style="width: 250px; border: #cccccc 1px solid; margin: 0; padding: 0;" class="clearfix">
<legend> <b>SPAM-Blocker *</b> </legend>
<div style="float: left; padding: 5px 0px 5px 5px;">
<img src="img/captcha.php?regen=y&amp;1444711025" alt="Captcha" border="0" /></div>
<div style="float: right; padding: 10px 5px 5px 10px;">
<input type="text" name="captcha" id="captcha" value="" /></div></fieldset>
<div style="margin: 10px 0pt 0pt 0pt; padding: 0pt; clear: both;"></div>
</td></tr><tr><td colspan="2">
<input type="submit" name="submitIt" id="submitIt" value="- send e-mail -" style="margin: 5px 0px 5px 0px;" />       <input type="reset" name="resetIt" id="resetIt" value="-  reset  -" style="margin: 5px 0px 5px 5px;" />
</td></tr><tr><td colspan="2">
<span id="schlusstext" style="margin: 5px 0px 0px 0px;">&gt;&gt;&gt; an <strong>webmaster (at) phpwcms-docu . de</strong></span>
</td></tr>
</table>
<input type="hidden" name="cpID1624" value="1624" /><input type="hidden" name="44bcd85571059cc3fb23f7fde414c6ec" value="870592" /></form></div><div style="margin:15px 0 0 0;padding:0;" class="spaceBeforeCP"></div><hr width="100%" size="2" />
<p>&nbsp;</p><div style="margin:0 0 15px 0;padding:0;" class="spaceAfterCP"></div>
<h4>Some news from the docu</h4>
<h5>23.07.2007</h5>
<p>We still work on an update of the docu. At the moment we have updated all content part images to version 1.3.3. so it can be that the content part description differs from the shown image. We try to update these parts as fast as we can.</p>

		 
		
		<br /><br />
		<div class="sub">
			
		</div>
				
	</div>
	
<div id="footer"><br /><br />
<br />





	<table width="97%" border="0" cellspacing="0" cellpadding="0">
		<tr>
			<td valign="bottom">	
			&copy; phpwcms-docu 2004-2015
			<img src="img/leer.gif" border="0" width="10" height="0" alt="" /><a href="imprint.phtml" class="phpwcmsIntLink"><img src="template/lang/all/icons/imprint.gif" width="9" height="15" alt="Impressum" title="Impressum" border="0" /></a>&nbsp; 
			<a href="sitemap_en.phtml" class="phpwcmsIntLink"><img src="template/lang/all/icons/sitemap.gif" width="19" height="15" alt="Sitemap" title="Sitemap" border="0" /></a>&nbsp; 
			 
			
			     
			</td>
			<td valign="bottom" style="padding-right:25px;">
			
			
			
			</td>		
			<td width="150">
			</td>
		</tr>
	</table>
</div><br/>

</div>
</body>
</html>