<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<!--
	phpwcms | free open source content management system
	created by Oliver Georgi (oliver at phpwcms dot de) and licensed under GNU/GPL.
	phpwcms is copyright 2003-2007 of Oliver Georgi. Extensions are copyright of
	their respective owners. Visit project page for details: http://www.phpwcms.org/
//-->
<title>phpwcms-docu for  phpwcms :: web based content management system | Newsletter | Content Part &quot;Newsletter&quot;</title>
  <meta http-equiv="content-type" content="text/html; charset=iso-8859-1" />
  <meta http-equiv="content-style-type" content="text/css" />
  <script src="template/inc_js/frontend.js" type="text/javascript"></script>
  <style type="text/css">
  <!-- 
    @import url("template/inc_css/mpl_frontend.css");
    @import url("template/inc_css/mpl_menu.css");
    @import url("template/inc_css/mpl_objects.css");
    @import url("template/inc_css/mpl_docu_en.css");
  //-->
  </style>
<meta name="Title" content="The phpWCMS Documentation" />
<meta name="author" content="Oliver Frohnert, Mario Perez Leal" />
<meta name="Publisher" content="Oliver Frohnert, Mario Perez Leal, creacion" />
<meta name="Copyright" content="Oliver Frohnert, Mario Perez Leal, creacion" />
<meta name="keywords" content="frohnert, perez leal, creacion, documentation, dokumentation, phpwcms, cms, opensource, open source, docu" />
<meta name="description" content="A Documentation Project for the  Open Source CMS phpWCMS" />
<meta name="Audience" content="Alle" />
<meta name="Content-language" content="EN" />
<meta name="robots"      content="index,follow" />
<meta name="expires" content="0" />
<meta name="revisit-after" content="7 days" />
<meta name="resource-type" content="document" />
<meta name="distribution" content="Global" />
<meta name="generator" content="PHPWCMS" />

  <link rel="stylesheet" href="template/slimbox/css/slimbox.css" type="text/css" media="screen" />
  <script src="template/inc_js/mootools/mootools.js" type="text/javascript"></script>
  <script src="template/slimbox/js/slimbox.js" type="text/javascript"></script>
  <!--[if lt IE 7]>
  <style type="text/css">
    body { behavior: url("template/inc_css/specific/csshover2.htc"); }
    img { behavior: url("template/inc_css/specific/pngbehavior.htc"); }
  </style>
  <![endif]-->
</head>
<body id="myid_293">
<div id="container"><a name="top" id="top"></a>


	<div id="head">
		
	<div id="mainnavi">
		<div class="fleft"><a href="english_version.phtml">Home</a> | <a href="news_en.phtml">News</a> | <span style="text-decoration:none;font-weight:bold;"><a href="the_docu.phtml">The Docu</a></span> | <a href="Usefull_Links_and_Tools.phtml">Links &amp; Tools</a> | <a href="contact.phtml">Contact</a> | <a href="faq_en.phtml">FAQ</a> | <a href="http://forum.phpwcms.org/" target="_blank">Forum</a> | <a href="howto_en.phtml">HowTo</a></div>				
		<div class="sys">Monday, 19. October 2009<img src="img/leer.gif" border="0" width="5" height="1" alt="" />|<img src="img/leer.gif" border="0" width="5" height="1" alt="" />3 User online<img src="img/leer.gif" border="0" width="10" height="1" alt="" />
		<a href="deutsche_version.phtml" title="Deutsche Version"><img src="picture/../template/lang/all/flag_de.gif" border="0" alt="" /></a>
		<a href="english_version.phtml"  title="English version"><img src="picture/../template/lang/all/flag_en.gif" border="0" alt="" /></a>
		</div>
	</div>
	
	<a href="./" title="phpwcms-docu Startseite aufrufen" class="homelink">
	<span>&raquo; phpwcms-docu startpage</span></a>
	<h2>phpwcms-docu - Documentation for the Web Content Management System phpwcms</h2>
	<p>This website is targeted both to the beginner and the lateral entry following the goal to simplify the 
work with phpwcms and to focus on the essentials things.</p>
	</div>

	
	<div id="left">
	<div class="leftnav" style="margin-top:24px;">
	
<div id="ul_div_311">
<ul>
	<li class="sub_no"><a href="download-dev-versions.phtml">Download Dev Versions</a></li>
	<li class="sub_no sub_ul_true"><a href="installation_en.phtml">Installation &amp; Upgrade</a></li>
	<li class="sub_ul"><a href="article.phtml">Articles</a>
	<div id="ul_div_116">
	<ul>
		<li class="sub_no"><a href="creating_articles.phtml">Creating Articles</a></li>
		<li class="sub_no"><a href="editing_articles.phtml">Editing Articles </a></li>
		<li class="sub_no sub_ul_true"><a href="article_organization.phtml">Article Organization</a></li>
		<li class="sub_ul"><a href="content_parts_en.phtml">Content Parts</a>
		<div id="ul_div_124">
		<ul>
			<li class="sub_no"><a href="content_part_plain_text.phtml">Plain Text</a></li>
			<li class="sub_no"><a href="content_part_html_en.phtml">Html</a></li>
			<li class="sub_no"><a href="content_part_wysiwyg_html_en.phtml">WYSIWYG HTML</a></li>
			<li class="sub_no"><a href="content_part_code_en.phtml">Code</a></li>
			<li class="sub_no"><a href="content_part_text_with_image.phtml">Text with image</a></li>
			<li class="sub_no"><a href="content_part_images.phtml">Images</a></li>
			<li class="sub_no"><a href="content_part_images_div.phtml"><span style="text-decoration:line-through;font-size:10px;">Images &lt;DIV&gt;</span></a></li>
			<li class="sub_no"><a href="content_part_list_table.phtml">List (Table)</a></li>
			<li class="sub_no"><a href="content_part_list.phtml">List</a></li>
			<li class="sub_no"><a href="content_part_link_and_e-mail.phtml">Link &amp; E-Mail</a></li>
			<li class="sub_no"><a href="content_part_link_list.phtml">Link list</a></li>
			<li class="sub_no"><a href="content_part_link_article.phtml">Link article</a></li>
			<li class="sub_no"><a href="content_part_teaser_articlelink.phtml"><span style="text-decoration:line-through;font-size:10px;">Teaser / Articlelink</span></a></li>
			<li class="sub_no"><a href="content_part_article_menue.phtml">Article Menu</a></li>
			<li class="sub_no"><a href="content_part_multimedia_en.phtml">Multimedia</a></li>
			<li class="sub_no"><a href="content_part_file_list.phtml">File List</a></li>
			<li class="sub_no"><a href="content_part_ecard_en.phtml">E-Card</a></li>
			<li class="sub_no"><a href="content_part_form.phtml">Form</a></li>
			<li class="sub_no"><a href="content_part_e-mail_contact_form.phtml">Email contact form</a></li>
			<li class="sub_no sub_ul_true"><a href="content_part_email_form_generator.phtml">Email form generator[OLD]</a></li>
			<li class="sub_no"><a href="content_part_email_form.phtml">Email form</a></li>
			<li class="sub_ul active"><a href="content_part_newsletter_en.phtml">Newsletter</a>
			<div id="ul_div_293">
			<ul>
				<li class="sub_no"><a href="newsletter_example.phtml">Newsletter example</a></li>
			</ul>
			</div>
			</li>
			<li class="sub_no"><a href="content_part_search.phtml">Search</a></li>
			<li class="sub_no sub_ul_true"><a href="content_part_guestbook_comment.phtml">Guestbook / Comm.</a></li>
			<li class="sub_no"><a href="content_part_sitemap_en.phtml">Sitemap</a></li>
			<li class="sub_no sub_ul_true"><a href="content_part_bid.phtml">Bid</a></li>
			<li class="sub_no"><a href="content_part_external_content.phtml">Ext. content</a></li>
			<li class="sub_no"><a href="content_part_rss_feed_en.phtml">RSS Feed</a></li>
			<li class="sub_no"><a href="content_part_rollover_images.phtml"><span style="text-decoration:line-through;font-size:10px;">Rollover images</span></a></li>
			<li class="sub_no"><a href="content_part_map.phtml"><span style="text-decoration:line-through;font-size:10px;">Map</span></a></li>
			<li class="sub_no"><a href="php_variables.phtml"><span style="text-decoration:line-through;font-size:10px;">PHP variables</span></a></li>
			<li class="sub_no"><a href="content_part_contentpart_alias_en.phtml">Contentpart Alias</a></li>
			<li class="sub_no"><a href="content_part_poll_en.phtml"><span style="text-decoration:line-through;font-size:10px;">Poll</span></a></li>
			<li class="sub_no"><a href="content_part_recipe.phtml"><span style="text-decoration:line-through;font-size:10px;">Recipe</span></a></li>
			<li class="sub_no"><a href="content_part_faq_en.phtml"><span style="text-decoration:line-through;font-size:10px;">FAQ</span></a></li>
			<li class="sub_no"><a href="content_part_frontend_login_en.phtml"><span style="text-decoration:line-through;font-size:10px;">Frontend Login</span></a></li>
			<li class="sub_no"><a href="content_part_glossary.phtml"><span style="text-decoration:line-through;font-size:10px;">Plug-in: Glossary</span></a></li>
		</ul>
		</div>
		</li>
	</ul>
	</div>
	</li>
	<li class="sub_no sub_ul_true"><a href="file.phtml">File</a></li>
	<li class="sub_no sub_ul_true"><a href="module_en.phtml">Modules</a></li>
	<li class="sub_no sub_ul_true"><a href="communication.phtml">Communication </a></li>
	<li class="sub_no"><a href="chat_en.phtml">Chat</a></li>
	<li class="sub_no"><a href="profile.phtml">Profile</a></li>
	<li class="sub_no sub_ul_true"><a href="admin_en_.phtml">Admin</a></li>
	<li class="sub_no sub_ul_true"><a href="add-ons-and-templates.phtml">Add On&#039;s and Templates</a></li>
	<li class="sub_no"><a href="deutsche_version.phtml?replacement_tags_en">Replacement Tags</a></li>
	<li class="sub_no"><a href="deutsche_version.phtml?content_parts_en">Content Parts</a></li>
</ul>
</div>

		
	</div> 
	</div> 
	  
	<div id="right">
		<div style="margin-top:24px;">			
		<form action="#" method="post" name="searchFE" onsubmit="s=document.getElementById('customSearchInput');if(s.value=='Search')return false;">
			<table width="100%" border="0" cellpadding="0" cellspacing="0">
			<tr>
					<td><input type="text" name="search_input_field" size="20" maxlength="200" id="customSearchInput" class="customSearchInput" value="" onfocus="if(this.value=='Search')this.value='';" onblur="if(this.value=='')this.value='Search';"/></td>
					<td><input type="image" name="search_go" onfocus="this.blur();" title="Search" src="/template/lang/all/submit.gif" /></td>
				</tr>
			</table>
			</form>
			
			      <script type="text/javascript" language="javascript">
			  <!-- 
			        document.getElementById("customSearchInput").value="Search";
			  //-->
			      </script>
				  
<!-- <p style="margin-top:10px;">Change font size: <a href="[FontSize-]"><img src="template/lang/all/icons/reduce.gif" width="18" height="17" alt="" title="Small" border="0" /></a>
			<a href="[FontSize+]"><img src="template/lang/all/icons/extend.gif" width="18" height="17" alt="" title="Bigger" border="0" /></a>
			</p> -->
			
	<p style="margin-top:10px;">Please choose: 
	
	 </p>

<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div>

<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div>
<!-- <a href="http://validator.w3.org/check?uri=http%3A%2F%2Fwww.phpwcms-docu.de%2Findex.php%3Fdeutsche_version" title="W3C Standard XHTML" target="_blank"><img src="picture/w3c/w3c_xhtml.gif" border="0" alt="" /></a>
<a href="http://jigsaw.w3.org/css-validator/validator?uri=http://www.phpwcms-docu.de" title="W3C Standard CSS" target="_blank"><img src="picture/w3c/w3c_css.gif" border="0" alt="" /></a><br />			
<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div> -->
		
<div style="margin-top:10px; margin-bottom:15px;"></div>
	
</div>

	</div> 
	
	<div id="content">
	<div id="bread">You are here: <a href="english_version.phtml">English</a> <span class="breadcrumb_spacer">&gt;</span> <a href="the_docu.phtml">The Docu</a> <span class="breadcrumb_spacer">&gt;</span> <a href="article.phtml">Articles</a> <span class="breadcrumb_spacer">&gt;</span> <a href="content_parts_en.phtml">Content Parts</a> <span class="breadcrumb_spacer">&gt;</span> Newsletter</div>
		
		<a name="jump229"></a><!-- Livedate: 08.09.2004 04:44:56 / Killdate: 31.12.2010 23:59:59 -->
<h1>Content Part &quot;Newsletter&quot;</h1>

<div style="margin:25px 0 0 0;padding:0;" class="spaceBeforeCP"></div><table width="132" border="0" cellspacing="0" cellpadding="0" align="left">
<tr><td class="image_td2"><a href="content/images/a262d46bd05dd960724befa9e977361e.png" rel="lightbox" target="_blank"><img src="content/images/032787f84036731cd6a59c4f20b89377.png" width="124" height="200" border="0" class="image_img" alt="newsletter.png" /></a></td><td><img src="img/leer.gif" width="8" height="1" border="0" alt="" /></td></tr>
</table><div class="articleText"><table width="70%" height="216" cellspacing="0" cellpadding="0" border="0">
    <tbody>
        <tr>
            <td>
            <p align="justify">The following are the steps to set up a newsletter subscription page on your phpwcms installation.<br />
            We begin with an overview of all the fields, describing their uses. Secondly you will find an example Newsletter Template which you can use to copy and paste entries into your form fields to quickly get set up. You will want to make changes to the wording of these entries to best reflect the content of your site.<br />
            <br />
            If you plan on creating more than one newsletter theme I.E. a newsletter for widget subscribers, and another newsletter for gadget subscribers; the first step is to create these in your backend from <a href="message.phtml" class="phpwcmsIntLink"><strong>Message</strong></a> -&gt; <a href="newsletter_subscription.phtml" class="phpwcmsIntLink"><strong>Newsletter Subscriptions</strong></a>. If you are only going to have one newsletter for both widgets and gadgets this step is not required. <br />
            <br />
            To begin create an article in your directory structure where you will want a subscription page to appear. Then Create a newsletter content part to append to that. In the newsletter content part you will see the following forms that need to be filled out.</p>
            </td>
        </tr>
    </tbody>
</table>
</div><div align="right"><a href="#top"><img src="img/article/top_link_0.gif" border="0" alt="" /></a></div><div style="border-bottom:1px dotted #d2e2f5; margin-top:10px; margin-bottom:15px;"></div><div style="margin:10px 0 0 0;padding:0;" class="spaceBeforeCP"></div><h3>Fielddescription</h3><table cellspacing="1" cellpadding="0" border="0">
    <tbody>
        <tr>
            <td bgcolor="#cccccc">
            <table cellspacing="1" cellpadding="5" border="0">
                <tbody>
                    <tr valign="top">
                        <td width="60" bgcolor="#ffffff" colspan="2">info text:</td>
                        <td bgcolor="#ffffff" colspan="2">Type in the description of the newsletter, as it appears to the public, i.e. &quot;A weekly newsletter about the benefits of widgets.&quot;</td>
                    </tr>
                    <tr valign="top">
                        <td bgcolor="#ffffff" colspan="2">subscription:</td>
                        <td bgcolor="#ffffff" colspan="2">If you have created more than one newsletter select which one this subscription form applies to.</td>
                    </tr>
                    <tr valign="top">
                        <td bgcolor="#ffffff" colspan="2">label email:</td>
                        <td bgcolor="#ffffff" colspan="2">Type the field description for &rsquo;email-address&rsquo;. This is where you ask the user to add their email , it might read &quot;your e-mail&quot; .</td>
                    </tr>
                    <tr>
                        <td bgcolor="#ffffff" colspan="2">table align:</td>
                        <td bgcolor="#ffffff" colspan="2">Decide the alignment of the fields, as they are to appear on the page. The default is left , right is also available.</td>
                    </tr>
                    <tr valign="top">
                        <td bgcolor="#ffffff" colspan="2">label name:</td>
                        <td bgcolor="#ffffff" colspan="2">
                        <div align="left">Type in here the field description for subscribers name i.e. first name, subscription nickname, username .</div>
                        </td>
                    </tr>
                    <tr>
                        <td bgcolor="#ffffff" colspan="2">button text:</td>
                        <td bgcolor="#ffffff" colspan="2">Compose the text for the submit button i.e. sign in, or subscribe now, or sign-up .</td>
                    </tr>
                    <tr valign="top">
                        <td bgcolor="#ffffff" colspan="2">label subscr.:</td>
                        <td bgcolor="#ffffff" colspan="2">If you are offering more than one newsletter compose the text that asks the user to choose which newsletter subscription they are signing up to, i.e. please choose, select a newsletter, your choice.</td>
                    </tr>
                    <tr>
                        <td bgcolor="#ffffff" colspan="2">all subscr.:</td>
                        <td bgcolor="#ffffff" colspan="2">This is the description text for the box that selects all available newsletters, i.e all, all of the above, subscribe to all.</td>
                    </tr>
                    <tr valign="top">
                        <td bgcolor="#ffffff" colspan="2">success text:</td>
                        <td bgcolor="#ffffff" colspan="2">Compose the text for the confirmation page that the visitor will be re-directed to after they have subscribed successfully.</td>
                    </tr>
                    <tr valign="top">
                        <td bgcolor="#ffffff" colspan="2">regist.email:</td>
                        <td bgcolor="#ffffff" colspan="2">Compose the text for the e-mail-confirmation the subscriber will receive after subscribing. To personalize the email you use following placeholders. <br/>
                        <strong>{NEWSLETTER_NAME}</strong> displays the name of the subscriber. <strong>{NEWSLETTER_EMAIL}</strong> shows their email address. This form must contain the following verification link placeholder: <strong>{NEWSLETTER_VERIFY}</strong> and the place holder to unsubscribe <strong>{NEWSLETTER_DELETE}</strong>.</td>
                    </tr>
                    <tr valign="top">
                        <td bgcolor="#ffffff" colspan="2">logoff.email:</td>
                        <td bgcolor="#ffffff" colspan="2">Compose the text for the unsubscribe-email. The previous placeholders can be used to personalize this email as well.</td>
                    </tr>
                    <tr valign="top">
                        <td bgcolor="#ffffff" colspan="2">change.email:</td>
                        <td bgcolor="#ffffff" colspan="2">
                        <div align="left">This form is used as text for an email sent to the user if they should make any changes to their subscription. The personalized placeholders can of course be used here too.</div>
                        </td>
                    </tr>
                </tbody>
            </table>
            </td>
        </tr>
    </tbody>
</table><div style="margin:10px 0 0 0;padding:0;" class="spaceBeforeCP"></div><P>Turning over to the </P>

<ul class="articleLinkInternal">

	<li><a href="aid=230.phtml">Newsletter example</a></li>

</ul>

<div align="right"><a href="#top"><img src="img/article/top_link_0.gif" border="0" alt="" /></a></div>
		 
		
		<br /><br />
		<div class="sub">
		Article created: Sunday, 5. December 2004 <br /> Last Changes: Tuesday, 30. October 2007	
		</div>
				
	</div>
	
<div id="footer">





	<table width="97%" border="0" cellspacing="0" cellpadding="0">
		<tr>
			<td valign="bottom">	
			&copy; phpwcms-docu 2004-2009
			<img src="img/leer.gif" border="0" width="10" height="0" alt="" /><a href="imprint.phtml" class="phpwcmsIntLink"><img src="template/lang/all/icons/imprint.gif" width="9" height="15" alt="Impressum" title="Impressum" border="0" /></a>&nbsp; 
			<a href="sitemap_en.phtml" class="phpwcmsIntLink"><img src="template/lang/all/icons/sitemap.gif" width="19" height="15" alt="Sitemap" title="Sitemap" border="0" /></a>&nbsp; 
			 
			
			     
			</td>
			<td valign="bottom" style="padding-right:25px;">
			
			
			
			</td>		
			<td width="150">
			</td>
		</tr>
	</table>
</div><br/>

</div>
</body>
</html>