<br />
<b>Warning</b>:  ob_start(): output handler 'ob_gzhandler' cannot be used after 'URL-Rewriter' in <b>/www/htdocs/docudocu/index.php</b> on line <b>84</b><br />
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<!--

phpwcms | open source web content management system

          developed by Oliver Georgi (info@phpwcms.de)
          released under The GNU General Public License
          visit project page: http://www.phpwcms.de

          Release: 1.1.9

//-->
<html>
<head>
<title>phpwcms documentation | Login to Backend</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<script src="template/inc_js/frontend.js" type="text/javascript"></script>
<link rel="stylesheet" type="text/css" href="template/inc_css/frontend.css">
<META NAME="Title" CONTENT="The phpWCMS Documentation">
<meta name="author" content="Oliver Frohnert">
<meta name="Publisher" content="Oliver Frohnert">
<meta name="Copyright" content="Oliver Frohnert">
<meta name="keywords" content="frohnert,documentation, dokumentation, phpwcms, cms. opensource, open source">
<meta name="description" content="A Documentation Project for the  Open Source CMS phpWCMS">
<meta name="Audience" content="Alle">
<meta name="Content-language" content="EN">
<META NAME="robots"      CONTENT="index,follow">
<META NAME="expires" CONTENT="0">
<meta name="revisit-after" content="7 days">
<meta name="resource-type" content="document">
<meta name="distribution" content="Global">
<meta name="generator" content="PHPWCMS">
<script language="JavaScript" type="text/javascript" src="pphlogger.js"></script>
<noscript><img alt="" src="./pphlogger/pphlogger.php?id=phpwcms&st=img"></noscript>

</head>

<body bgcolor="#FFFFFF" text="#000000" link="#FF9900" vlink="#FF9900" alink="#FF9900" topmargin="0" leftmargin="0" marginwidth="0" marginheight="0">
<table border="0" cellspacing="0" cellpadding="0" width="760" bgcolor="#ffffff" class="maintable" align="center">
<tr>
<td colspan="2" style="height:60px;"  bgcolor="#ffffff"><table width="760" height="135" border="0" cellpadding="0" cellspacing="0">
  <tr valign="top">
    <td width="1334" height="122" colspan="6" background="template/lang/en/header.jpg"></td>
  </tr>
  <tr>
	<td height="27" background="template/lang/all/top_menu.jpg"><table width="570" border="0" align="left" cellpadding="0" cellspacing="0">
      <tr>
        <td align="center" width="254"><a href="deutsche_version.phtml"><img src="picture/flags/de.gif" width="16" height="10" hspace="10" border="0"  alt="Deutsche Version" title="Deutsche Version"></a>
<a href="english_version.phtml"><img src="picture/flags/gb.gif" width="16" height="10" hspace="10" border="0"  alt="English Version" title="English Version"></a></td>
        <td valign="middle"><div align="center"><a href="replacement_tags_en.phtml"><img src="content/gt/9ad4c84df9fc6e20be504ff61a358128.png" alt="Replacement Tags" border="0" /></a></div></td>
        <td width="30" valign="middle"><div align="center"><img src="template/lang/all/sep.gif" width="5" height="5" border="0"></div></td>
        <td valign="middle"><div align="center"><a href="content_parts_en.phtml"><img src="content/gt/0ac72fda03e1537553c1f89e3f96ad75.png" alt="Content Parts" border="0" /></a></div></td>
        <td width="30" valign="middle"><div align="center"><img src="template/lang/all/sep.gif" width="5" height="5" border="0"></div></td>
        <td valign="middle"><div align="center"><a href="links_de.phtml"><img src="content/gt/c13491df26fc7ba71211ce67d0cd7cac.png" alt="Links" border="0" /></a></div></td>
        <td width="30" valign="middle"><div align="center"><img src="template/lang/all/sep.gif" width="5 " height="5" border="0"></div></td>
        <td valign="middle"><div align="center"><a href="imprint.phtml"><img src="content/gt/215793d443e1aa389280e64b8712f954.png" alt="Imprint" border="0" /></a></div></td>
     </tr>
    </table>    </td>
  </tr>
</table></td>
</tr>
<tr>
<td valign="top" width="185" background="img/menu.gif"><table width="180" border="0" cellpadding="0" cellspacing="0">
  <tr>
    <td width="180" height="20">&nbsp;</td>
  </tr>
  <tr>
    <td style="padding-left: 7px;"><table border="0" cellspacing="0" cellpadding="0" width="100%">
<tr>
<td colspan="2"><img src="img/leer.gif" width="1" height="1" alt="" /></td><td><img src="img/leer.gif" width="1" height="1" alt="" /></td><td colspan="2"><img src="img/leer.gif" width="1" height="1" alt="" /></td><td><img src="img/leer.gif" width="1" height="1" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='news_en.phtml';return false;" onMouseOver="MM_swapImage('linkidl32Hdj','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td width="7" colspan="2"><img src="img/leer.gif" width="7" height="15" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkidl32Hdj" id="linkidl32Hdj"></td>
<td valign="top" style="height:15px;"  width="100%" class="nav_table" colspan="2"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="news_en.phtml">News</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="7"><img src="img/leer.gif" width="10" height="15" alt="" /></td>
</tr>
<tr>
<td colspan="2"><img src="img/leer.gif" width="1" height="1" alt="" /></td><td><img src="img/leer.gif" width="1" height="1" alt="" /></td><td colspan="2"><img src="img/leer.gif" width="1" height="1" alt="" /></td><td><img src="img/leer.gif" width="1" height="1" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='installation_en.phtml';return false;" onMouseOver="MM_swapImage('linkidjbrcEp','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td width="7" colspan="2"><img src="img/leer.gif" width="7" height="15" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkidjbrcEp" id="linkidjbrcEp"></td>
<td valign="top" style="height:15px;"  width="100%" class="nav_table" colspan="2"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="installation_en.phtml">Installation<img src="picture/myRT1/newR.gif" alt="2/6/2005" border="0"></a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="7"><img src="img/leer.gif" width="10" height="15" alt="" /></td>
</tr>
<tr>
<td colspan="2"><img src="img/leer.gif" width="1" height="1" alt="" /></td><td><img src="img/leer.gif" width="1" height="1" alt="" /></td><td colspan="2"><img src="img/leer.gif" width="1" height="1" alt="" /></td><td><img src="img/leer.gif" width="1" height="1" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='311.0.0.1.0.0.phtml';return false;">
<td width="7" colspan="2"><img src="img/leer.gif" width="7" height="15" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_2" alt="" border="" name="linkidxppSps" id="linkidxppSps"></td>
<td valign="top" style="height:15px;"  width="100%" class="nav_table_active" colspan="2"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="311.0.0.1.0.0.phtml">The Docu</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="7"><img src="img/leer.gif" width="10" height="15" alt="" /></td>
</tr>
<tr>
<td colspan="3"><img src="img/leer.gif" width="1" height="1" alt="" /></td><td><img src="img/leer.gif" width="1" height="1" alt="" /></td><td><img src="img/leer.gif" width="1" height="1" alt="" /></td><td><img src="img/leer.gif" width="1" height="1" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='deutsche_version.phtml?the_article_center';return false;" onMouseOver="MM_swapImage('linkideMYyUd','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td width="7" colspan="3"><img src="img/leer.gif" width="7" height="15" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkideMYyUd" id="linkideMYyUd"></td>
<td valign="top" style="height:15px;"  width="100%" class="nav_table"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="deutsche_version.phtml?the_article_center">Article</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="7"><img src="img/leer.gif" width="10" height="15" alt="" /></td>
</tr>
<tr>
<td colspan="3"><img src="img/leer.gif" width="1" height="1" alt="" /></td><td><img src="img/leer.gif" width="1" height="1" alt="" /></td><td><img src="img/leer.gif" width="1" height="1" alt="" /></td><td><img src="img/leer.gif" width="1" height="1" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='deutsche_version.phtml?File_Administration';return false;" onMouseOver="MM_swapImage('linkidVngMFJ','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td width="7" colspan="3"><img src="img/leer.gif" width="7" height="15" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkidVngMFJ" id="linkidVngMFJ"></td>
<td valign="top" style="height:15px;"  width="100%" class="nav_table"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="deutsche_version.phtml?File_Administration">File</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="7"><img src="img/leer.gif" width="10" height="15" alt="" /></td>
</tr>
<tr>
<td colspan="3"><img src="img/leer.gif" width="1" height="1" alt="" /></td><td><img src="img/leer.gif" width="1" height="1" alt="" /></td><td><img src="img/leer.gif" width="1" height="1" alt="" /></td><td><img src="img/leer.gif" width="1" height="1" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='module_en.phtml';return false;" onMouseOver="MM_swapImage('linkidx7IWn8','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td width="7" colspan="3"><img src="img/leer.gif" width="7" height="15" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkidx7IWn8" id="linkidx7IWn8"></td>
<td valign="top" style="height:15px;"  width="100%" class="nav_table"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="module_en.phtml">Modules</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="7"><img src="img/leer.gif" width="10" height="15" alt="" /></td>
</tr>
<tr>
<td colspan="3"><img src="img/leer.gif" width="1" height="1" alt="" /></td><td><img src="img/leer.gif" width="1" height="1" alt="" /></td><td><img src="img/leer.gif" width="1" height="1" alt="" /></td><td><img src="img/leer.gif" width="1" height="1" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='message.phtml';return false;" onMouseOver="MM_swapImage('linkidJFHYJp','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td width="7" colspan="3"><img src="img/leer.gif" width="7" height="15" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkidJFHYJp" id="linkidJFHYJp"></td>
<td valign="top" style="height:15px;"  width="100%" class="nav_table"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="message.phtml">Message </a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="7"><img src="img/leer.gif" width="10" height="15" alt="" /></td>
</tr>
<tr>
<td colspan="3"><img src="img/leer.gif" width="1" height="1" alt="" /></td><td><img src="img/leer.gif" width="1" height="1" alt="" /></td><td><img src="img/leer.gif" width="1" height="1" alt="" /></td><td><img src="img/leer.gif" width="1" height="1" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='chat_en.phtml';return false;" onMouseOver="MM_swapImage('linkidZgHtBp','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td width="7" colspan="3"><img src="img/leer.gif" width="7" height="15" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkidZgHtBp" id="linkidZgHtBp"></td>
<td valign="top" style="height:15px;"  width="100%" class="nav_table"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="chat_en.phtml">Chat</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="7"><img src="img/leer.gif" width="10" height="15" alt="" /></td>
</tr>
<tr>
<td colspan="3"><img src="img/leer.gif" width="1" height="1" alt="" /></td><td><img src="img/leer.gif" width="1" height="1" alt="" /></td><td><img src="img/leer.gif" width="1" height="1" alt="" /></td><td><img src="img/leer.gif" width="1" height="1" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='profile.phtml';return false;" onMouseOver="MM_swapImage('linkidDuNmZX','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td width="7" colspan="3"><img src="img/leer.gif" width="7" height="15" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkidDuNmZX" id="linkidDuNmZX"></td>
<td valign="top" style="height:15px;"  width="100%" class="nav_table"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="profile.phtml">Profile</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="7"><img src="img/leer.gif" width="10" height="15" alt="" /></td>
</tr>
<tr>
<td colspan="3"><img src="img/leer.gif" width="1" height="1" alt="" /></td><td><img src="img/leer.gif" width="1" height="1" alt="" /></td><td><img src="img/leer.gif" width="1" height="1" alt="" /></td><td><img src="img/leer.gif" width="1" height="1" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='admin_en_wpj.phtml';return false;" onMouseOver="MM_swapImage('linkidd9cuWa','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td width="7" colspan="3"><img src="img/leer.gif" width="7" height="15" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkidd9cuWa" id="linkidd9cuWa"></td>
<td valign="top" style="height:15px;"  width="100%" class="nav_table"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="admin_en_wpj.phtml">Admin<img src="picture/myRT1/newR.gif" alt="1/18/2005" border="0"></a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="7"><img src="img/leer.gif" width="10" height="15" alt="" /></td>
</tr>
<tr>
<td colspan="2"><img src="img/leer.gif" width="1" height="1" alt="" /></td><td><img src="img/leer.gif" width="1" height="1" alt="" /></td><td colspan="2"><img src="img/leer.gif" width="1" height="1" alt="" /></td><td><img src="img/leer.gif" width="1" height="1" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='add_on_en.phtml';return false;" onMouseOver="MM_swapImage('linkid9XPiPg','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td width="7" colspan="2"><img src="img/leer.gif" width="7" height="15" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkid9XPiPg" id="linkid9XPiPg"></td>
<td valign="top" style="height:15px;"  width="100%" class="nav_table" colspan="2"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="add_on_en.phtml">Add On&#039;s</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="7"><img src="img/leer.gif" width="10" height="15" alt="" /></td>
</tr>
<tr>
<td colspan="2"><img src="img/leer.gif" width="1" height="1" alt="" /></td><td><img src="img/leer.gif" width="1" height="1" alt="" /></td><td colspan="2"><img src="img/leer.gif" width="1" height="1" alt="" /></td><td><img src="img/leer.gif" width="1" height="1" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='error_messages.phtml';return false;" onMouseOver="MM_swapImage('linkidNQxXjD','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td width="7" colspan="2"><img src="img/leer.gif" width="7" height="15" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkidNQxXjD" id="linkidNQxXjD"></td>
<td valign="top" style="height:15px;"  width="100%" class="nav_table" colspan="2"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="error_messages.phtml">Error messages</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="7"><img src="img/leer.gif" width="10" height="15" alt="" /></td>
</tr>
<tr>
<td colspan="2"><img src="img/leer.gif" width="1" height="1" alt="" /></td><td><img src="img/leer.gif" width="1" height="1" alt="" /></td><td colspan="2"><img src="img/leer.gif" width="1" height="1" alt="" /></td><td><img src="img/leer.gif" width="1" height="1" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='search.phtml';return false;" onMouseOver="MM_swapImage('linkidIiuMvP','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td width="7" colspan="2"><img src="img/leer.gif" width="7" height="15" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkidIiuMvP" id="linkidIiuMvP"></td>
<td valign="top" style="height:15px;"  width="100%" class="nav_table" colspan="2"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="search.phtml">Search</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="7"><img src="img/leer.gif" width="10" height="15" alt="" /></td>
</tr>
<tr>
<td colspan="2"><img src="img/leer.gif" width="1" height="1" alt="" /></td><td><img src="img/leer.gif" width="1" height="1" alt="" /></td><td colspan="2"><img src="img/leer.gif" width="1" height="1" alt="" /></td><td><img src="img/leer.gif" width="1" height="1" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='contact.phtml';return false;" onMouseOver="MM_swapImage('linkidhIRPwL','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td width="7" colspan="2"><img src="img/leer.gif" width="7" height="15" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkidhIRPwL" id="linkidhIRPwL"></td>
<td valign="top" style="height:15px;"  width="100%" class="nav_table" colspan="2"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="contact.phtml">Contact</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="7"><img src="img/leer.gif" width="10" height="15" alt="" /></td>
</tr>
</table></td>
  </tr>
 <tr>
    <td style="padding:10px; color:#000000;"><img src="picture/seperate.gif" border="0" alt="" /><P>
	<a href="deutsche_version.phtml?id=286,216,0,0,1,0">Latest Version:<br>
RC 1.1 - 27.08.2004a<br>
Release Date: 6.11.2004<P>
Last Patch:<BR>
26.11.2004</a><P>
<img src="picture/seperate.gif" border="0" alt="" /></TD>
  </tr>
<tr>
    <td height="20">&nbsp;</td>
  </tr>
  <tr>
    <td align="center"></td>
  </tr>
  <tr>
    <td height="20">&nbsp;</td>
  </tr>
</table>


</body>
</html>
</td>
<td valign="top" width="555" bgcolor="#ffffff" class="maincontent"><img src="img/leer.gif" border="0" width="10" height="1" alt="" />
<BR>
<a href="english_version.phtml">English</a> <span class="breadcrumb_spacer">&gt;</span> The Docu
<br>
<HR>
<br>
<a name="jump198"></a><span class="articleHead">Login to Backend</span><img src="img/leer.gif" width="1" height="8" alt=""><br /><img src="img/leer.gif" width="1" height="15" alt="" /><br><span class="contentHead">Overview and preparation</span><br><img src="img/leer.gif" width="1" height="3" alt=""><table width="158" border="0" cellspacing="0" cellpadding="0" align="left" class="image_table">
<tr><td class="image_td"><a href="zoom/OTQ4NTE4YjRkYWNlYjdiMmJlM2UzZjdmM2EwNDk3ZTIucG5nP3dpZHRoPSI1MzgiIGhlaWdodD0iMzExIg.html" onClick="window.open('zoom/OTQ4NTE4YjRkYWNlYjdiMmJlM2UzZjdmM2EwNDk3ZTIucG5nP3dpZHRoPSI1MzgiIGhlaWdodD0iMzExIg.html','previewpic','width=538,height=311');return false;.html" target="_blank"><img src="content/images/ee6405e2b753f6d73b389016d0dc9221.png" width="150" height="87" border="0" class="image_img" alt="login_en_01.png"></a></td><td><img src="img/leer.gif" width="8" height="1" alt="" /></td></tr>
<tr><td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td></tr>
<tr><td align="center" bgcolor="#efefef" class="image_caption"><img src="img/leer.gif" width="1" height="3" alt="" /><br>click to enlarge<br><img src="img/leer.gif" width="1" height="3" alt="" /></td><td><img src="img/leer.gif" width="8" height="1" alt="" /></td></tr>
</table><div class="articleText">PhpWCMS distinguishs oneself because of the easy handling, clear structure and the straight separation of administration and editorial office.<BR><BR>First, before you can add or edit contents, you have to login. Please type your adress like "http://mydomain.com/login.php" - <BR>or if phpWCMS is installed in a subfolder -,<BR>http://mydomain.com/subfolder/login.php in your browser. Now you should see this login-panel:&nbsp;<BR><BR>When you installed phpWCMS by your own, please use the datas of your first created account.</div><HR><table width="158" border="0" cellspacing="0" cellpadding="0" align="left" class="image_table">
<tr><td class="image_td"><a href="zoom/MGM3MjJjNjk4NWIzYWNkNjMyY2Q1MDliMjI1YTI4YTAucG5nP3dpZHRoPSI1MzgiIGhlaWdodD0iMzQ2Ig.html" onClick="window.open('zoom/MGM3MjJjNjk4NWIzYWNkNjMyY2Q1MDliMjI1YTI4YTAucG5nP3dpZHRoPSI1MzgiIGhlaWdodD0iMzQ2Ig.html','previewpic','width=538,height=346');return false;.html" target="_blank"><img src="content/images/4f4c8238a3b8ea7b891f2ff12ff1814a.png" width="150" height="96" border="0" class="image_img" alt="login_en_02.png"></a></td><td><img src="img/leer.gif" width="8" height="1" alt="" /></td></tr>
<tr><td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td></tr>
<tr><td align="center" bgcolor="#efefef" class="image_caption"><img src="img/leer.gif" width="1" height="3" alt="" /><br>click to enlarge<br><img src="img/leer.gif" width="1" height="3" alt="" /></td><td><img src="img/leer.gif" width="8" height="1" alt="" /></td></tr>
</table><div class="articleText">After the login you will see the administration-level:&nbsp;<BR><BR>On the left side you see the all loged in user who are working in this administration-level. ( in this case "editor") In the red strip you will see the main menue with the items " article", " file", "Message" "chat" and "profile". We will explain therse later. Furthermore you have with "logout" the option to leave the administration-level every time you want to.&nbsp;<BR><BR><BR>If you logged in with administration rights (f.i. directly after the installation) you will see in the item Admin where the structure and design of your website is fixed.</div>
<table width="100%"  border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td colspan="2"><HR></td>
  </tr>
  <tr>
    <td width="50%">Article created: 25.Oktober 2004</td>
    <td align="right" width="50%">Last Changes: 09.Januar 2005</td>
  </tr>
  <tr>
    <td colspan="2">&nbsp;</td>
  </tr>
  <tr>
    <td colspan="2" class="comment">In case you find any mistakes or have enhancments, please use this <a href="#" onClick="javascript:window.open('./content/pages/message.htm','frage','width=400, height=250, screenX=440,screenY=200,menubar=no,statusbar=yes,scrollbar=yes,resizable=no');" target="" style="max-width:148px; overflow:hidden;"><u>form</u></a> .<br><BR>
Have you found this website a helpful resource in understanding the Phpwcms content management system? If so, would you consider making a donation?  Please click here: <a href="#paypal">PayPal</a>. We welcome any donation amount. Your contribution helps make this website an even better resource and helps underwrite the associated server expenses of accomodating a growing number of visitors.</td>
  </tr>
  <tr>

    <td colspan="2"><img src="img/leer.gif" border="0" width="10" height="10" alt="" /></td>
  </tr>
</table></td>
</tr>
<tr>
<td colspan="2" style="height:10px;"  bgcolor="#ffffff" class="footer"><table width="100%" height="20" background="img/footer.gif" cellpadding="0" cellspacing="0" border="0">
	<tr><td width="180" align="center" valign="middle"><strong>Visitors Online: <script language="JavaScript" type="text/javascript" src="./pphlogger/showhits.php?id=phpwcms&st=js&type=onlineusr"></script>
      </strong>
	</td>
	<td>
	<table width="100%"cellpadding="0" cellspacing="0" border="0">
   <tr>
    <td align="center"><a href="javascript:history.back();" target="_top" title="go back"><img src="picture/back_.gif" border="0" alt="Back"><img src="content/gt/6f54c678069079e769023e7711a19f83.png" alt="Back" border="0" /></a></td>
	<td align="center"><a href="sitemap_en.phtml"><img src="picture/sitemap_.gif" border="0"  alt="Sitemap"><img src="content/gt/d6ee999c57eae0a9d98b837870d624f7.png" alt="Sitemap" border="0" /></a></td>
	<td align="center"><a href="311.198.1.1.1.0.phtml" target="_blank"><img src="picture/print_.gif" border="0" alt="Print"><img src="content/gt/62a58183f1a2ffea945cec1e1f6cf816.png" alt="Print" border="0" /></a></td>
	<td align="center"><a href="guestbook.phtml"><img src="picture/icon_gaestebuch.gif" border="0" align="top" alt="Guestbook"><img src="content/gt/dbef51efbc9de176f1c8c26d0975a46a.png" alt="Guestbook" border="0" /></a></td>
	<td align="center"><a href="#" onClick="BookMark_Page();return false;" title=""><img src="picture/favoriten_.gif" border="0"  alt="Bookmark"><img src="content/gt/96792869390d8debc683393263d2379e.png" alt="Bookmark" border="0" /></a></td>
    </tr>
</table></td>
	</tr>
</table>
<img src="img/leer.gif" border="0" width="760" height="10" alt="" />
</td>
</tr>
</table>
</body>
</html>