<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<!--
	phpwcms | free open source content management system
	created by Oliver Georgi (oliver at phpwcms dot de) and licensed under GNU/GPL.
	phpwcms is copyright 2003-2007 of Oliver Georgi. Extensions are copyright of
	their respective owners. Visit project page for details: http://www.phpwcms.org/
//-->
<title>phpwcms-docu for  phpwcms :: web based content management system | Ebene erstellen / bearbeiten{D:8/2/2007,30,neuR.gif} | Neue Seitenstruktur erstellen / bearbeiten</title>
  <meta http-equiv="content-type" content="text/html; charset=iso-8859-1" />
  <meta http-equiv="content-style-type" content="text/css" />
  <script src="template/inc_js/frontend.js" type="text/javascript"></script>
  <style type="text/css">
  <!-- 
    @import url("template/inc_css/mpl_docu.css");
    @import url("template/inc_css/mpl_frontend.css");
    @import url("template/inc_css/mpl_menu.css");
    @import url("template/inc_css/mpl_objects.css");
  //-->
  </style>
<script type="text/javascript" language="javascript">
<!--
function MM_jumpMenu(targ,selObj,restore){ //v3.0
  eval(targ+".location='"+selObj.options[selObj.selectedIndex].value+"'");
  if (restore) selObj.selectedIndex=0;
}

function MM_findObj(n, d) { //v4.01
  var p,i,x;  if(!d) d=document; if((p=n.indexOf("?"))>0&&parent.frames.length) {
    d=parent.frames[n.substring(p+1)].document; n=n.substring(0,p);}
  if(!(x=d[n])&&d.all) x=d.all[n]; for (i=0;!x&&i<d.forms.length;i++) x=d.forms[i][n];
  for(i=0;!x&&d.layers&&i<d.layers.length;i++) x=MM_findObj(n,d.layers[i].document);
  if(!x && d.getElementById) x=d.getElementById(n); return x;
}

function MM_jumpMenuGo(selName,targ,restore){ //v3.0
  var selObj = MM_findObj(selName); if (selObj) MM_jumpMenu(targ,selObj,restore);
}
//-->
</script>
<meta name="Title" content="Die phpWCMS Dokumentation" />
<meta name="author" content="Oliver Frohnert, Mario Perez Leal" />
<meta name="Publisher" content="Oliver Frohnert, Mario Perez Leal, creacion" />
<meta name="Copyright" content="Oliver Frohnert, Mario Perez Leal, creacion" />
<meta name="keywords" content="frohnert, perez leal, creacion, documentation, dokumentation, phpwcms, cms, opensource, open source, docu" />
<meta name="description" content="Das Dokumentations Projekt für das Open Source CMS phpWCMS" />
<meta name="Audience" content="Alle" />
<meta name="Content-language" content="DE" />
<meta name="robots" content="index,follow" />
<meta name="expires" content="0" />
<meta name="revisit-after" content="7 days" />
<meta name="resource-type" content="document" />
<meta name="distribution" content="Global" />
<meta name="generator" content="PHPWCMS" />

  <link rel="stylesheet" href="template/slimbox/css/slimbox.css" type="text/css" media="screen" />
  <script src="template/inc_js/mootools/mootools.js" type="text/javascript"></script>
  <script src="template/slimbox/js/slimbox.js" type="text/javascript"></script>
  <!--[if lt IE 7]>
  <style type="text/css">
    body { behavior: url("template/inc_css/specific/csshover2.htc"); }
    img { behavior: url("template/inc_css/specific/pngbehavior.htc"); }
  </style>
  <![endif]-->
</head>
<body id="myid_316">
<div id="container"><a name="top" id="top"></a>


	<div id="head">
		
	<div id="mainnavi">
		<div class="fleft"><a href="deutsche_version.phtml">Startseite</a> | <a href="news_de.phtml">News</a> | <span style="text-decoration:none;font-weight:bold;"><a href="die_docu.phtml">Die Docu</a></span> | <a href="Nuetzliche_Links_und_Tools.phtml">Links &amp; Tools</a> | <a href="downloads.phtml">Downloads</a> | <a href="kontakt.phtml">Kontakt</a> | <a href="faq_de.phtml">FAQ</a> | <a href="http://forum.phpwcms.org/" target="_blank">Forum</a> | <a href="howto_de.phtml">HowTo</a></div>				
		<div class="sys">Dienstag, 12. Mai 2015<img src="img/leer.gif" border="0" width="5" height="1" alt="" />|<img src="img/leer.gif" border="0" width="5" height="1" alt="" />2 User online<img src="img/leer.gif" border="0" width="10" height="1" alt="" />
		<a href="deutsche_version.phtml" title="Deutsche Version"><img src="picture/../template/lang/all/flag_de.gif" border="0" alt="" /></a>
		<a href="english_version.phtml"  title="English version"><img src="picture/../template/lang/all/flag_en.gif" border="0" alt="" /></a>
		</div>
	</div>
	
	<a href="./" title="phpwcms-docu Startseite aufrufen" class="homelink">
	<span>&raquo; Zur phpwcms-docu Startseite</span></a>
	<h2>phpwcms-docu - Die Dokumentation f&uuml;r f&uuml;r das CMS phpWCMS</h2>
	<p>phpwcms-docu ist eine Art Kompass, der Ihnen die M&ouml;glichkeiten von phpWcms aufzeigt und Sie erfolgreich, ohne gro&szlig;e Umwege, zu Ihrer fertigen Web-Anwendung f&uuml;hren soll.
	</p>
	</div>

	
	<div id="left">
	<div class="leftnav" style="margin-top:24px;">
	
<div id="ul_div_309">
<ul>
	<li class="sub_no"><a href="download-dev-versionen.phtml">Download Dev Versionen</a></li>
	<li class="sub_no sub_ul_true"><a href="installation_und_upgrade_von_phpwcms.phtml">Installation &amp; Upgrade</a></li>
	<li class="sub_no sub_ul_true"><a href="verwaltung_artikel.phtml">Artikel</a></li>
	<li class="sub_no sub_ul_true"><a href="dateizentrale.phtml">Datei</a></li>
	<li class="sub_no sub_ul_true"><a href="verwaltung_module.phtml">Module</a></li>
	<li class="sub_no sub_ul_true"><a href="Kommunikation.phtml">Kommunikation</a></li>
	<li class="sub_no"><a href="verwaltung_nachricht.phtml">Nachricht</a></li>
	<li class="sub_no"><a href="verwaltung_chat.phtml">Chat</a></li>
	<li class="sub_no"><a href="verwaltung_profil.phtml">Profil</a></li>
	<li class="sub_ul"><a href="verwaltung_admin.phtml">Admin</a>
	<div id="ul_div_81">
	<ul>
		<li class="sub_ul"><a href="seitenstruktur.phtml">Seitenstruktur</a>
		<div id="ul_div_297">
		<ul>
			<li class="sub_no active"><a href="ebene_erstellen_und_bearbeiten.phtml">Ebene erstellen / bearbeiten</a></li>
			<li class="sub_no"><a href="ebene_verschieben.phtml">Ebene verschieben</a></li>
			<li class="sub_no"><a href="ebene_kopieren.phtml">Ebene kopieren</a></li>
		</ul>
		</div>
		</li>
		<li class="sub_no"><a href="seitenlayout.phtml">Seitenlayout</a></li>
		<li class="sub_no"><a href="vorlagen_de.phtml">Vorlagen</a></li>
		<li class="sub_no"><a href="standard_css.phtml">Standard CSS</a></li>
		<li class="sub_no sub_ul_true"><a href="benutzerverwaltung.phtml">Benutzerverwaltung</a></li>
		<li class="sub_no"><a href="keywords_de.phtml"><span style="text-decoration:line-through;font-size:10px;">Keywords</span></a></li>
		<li class="sub_no"><a href="dateikategorien.phtml"><span style="text-decoration:line-through;font-size:10px;">Dateikategorien</span></a></li>
		<li class="sub_no"><a href="backend_standardtext.phtml">Backend Standardtext</a></li>
		<li class="sub_no"><a href="cache_zuruecksetzten.phtml">Cache zurücksetzten</a></li>
		<li class="sub_no"><a href="cache_loeschen.phtml">Cache löschen</a></li>
		<li class="sub_no"><a href="dateien_final_loeschen.phtml">Dateien final löschen</a></li>
		<li class="sub_no sub_ul_true"><a href="replacement_tags_de.phtml">Replacement-Tags</a></li>
	</ul>
	</div>
	</li>
	<li class="sub_no sub_ul_true"><a href="add-on-und-vorlagen.phtml">Add Ons und Vorlagen</a></li>
	<li class="sub_no"><a href="deutsche_version.phtml?replacement_tags_de">Replacement Tags</a></li>
	<li class="sub_no"><a href="deutsche_version.phtml?content_parts_de">Content Parts</a></li>
</ul>
</div>

		
		
		

	</div> 
	</div> 
	  
	<div id="right">
		<div style="margin-top:24px;">			
		<form action="#" method="post" name="searchFE" onsubmit="s=document.getElementById('customSearchInput');if(s.value=='Suchen')return false;">
			<table width="100%" border="0" cellpadding="0" cellspacing="0">
			<tr>
					<td><input type="text" name="search_input_field" size="20" maxlength="200" id="customSearchInput" class="customSearchInput" value="" onfocus="if(this.value=='Suchen')this.value='';" onblur="if(this.value=='')this.value='Suchen';" /></td>
					<td><input type="image" name="search_go" onfocus="this.blur();" title="Suchen" src="/template/lang/all/submit.gif" /></td>
				</tr>
			</table>
			</form>
			
			      <script type="text/javascript" language="javascript">
			  <!-- 
			        document.getElementById("customSearchInput").value="Suchen";
			  //-->
			      </script>
				  
			<!-- <p style="margin-top:10px;">Schriftgrad &auml;ndern: <a href="[FontSize-]"><img src="template/lang/all/icons/reduce.gif" width="18" height="17" alt="" title="Verkleinern" border="0" /></a>
			<a href="[FontSize+]"><img src="template/lang/all/icons/extend.gif" width="18" height="17" alt="" title="Vergr&ouml;&szlig;ern" border="0" /></a>
			</p> -->
			
	<p style="margin-top:10px;">Bitte w&auml;hlen Sie: 
	
	 </p>
<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div>


<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div>
<!-- <a href="http://validator.w3.org/check?uri=http%3A%2F%2Fwww.phpwcms-docu.de%2Findex.php%3Fdeutsche_version" title="W3C Standard XHTML" target="_blank"><img src="picture/w3c/w3c_xhtml.gif" border="0" alt="" /></a>
<a href="http://jigsaw.w3.org/css-validator/validator?uri=http://www.phpwcms-docu.de" title="W3C Standard CSS" target="_blank"><img src="picture/w3c/w3c_css.gif" border="0" alt="" /></a><br />			
<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div> -->
<h3>Partnersites</h3>






<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div>

<div style="margin-top:10px; margin-bottom:15px;"></div>


<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div>
</div>

	</div> 
	
	<div id="content">
	<div id="bread">Sie sind hier: <a href="deutsche_version.phtml">Deutsch</a> <span class="breadcrumb_spacer">&gt;</span> <a href="die_docu.phtml">Die Docu</a> <span class="breadcrumb_spacer">&gt;</span> <a href="verwaltung_admin.phtml">Admin</a> <span class="breadcrumb_spacer">&gt;</span> <a href="seitenstruktur.phtml">Seitenstruktur</a> <span class="breadcrumb_spacer">&gt;</span> Ebene erstellen / bearbeiten</div>
		
		<a name="jump251"></a><!-- Livedate: 16.01.2005 10:16:34 / Killdate: 31.12.2030 23:59:59 -->
<h1>Neue Seitenstruktur erstellen / bearbeiten</h1>

<div style="margin:25px 0 0 0;padding:0;" class="spaceBeforeCP"></div><table width="100%" cellpadding="0" cellspacing="0" border="0" class="imgTextRight">
<tr>
<td valign="top" width="10%" class="image_td2"><div class="imgDIVblockImgLeft"><div class="image_td2"><a href="content/images/dff0595e037f35a662fb9079cd30ad2e.png" rel="lightbox" title="Seitenstruktur optionen" target="_blank"><img src="content/images/6d6383d2e6d828c01201bce681e28525.png" width="150" height="183" border="0" class="image_img" alt="steinstruktur_2.png" /></a></div><p class="image_caption">Seitenstruktur optionen</p></div></td>
<td valign="top" class="articleText">Nachdem Sie auf <img src="picture/../img/button/add_11x11.gif" border="0" alt="" /> gedr&uuml;ckt haben, um eine neue Struktur zu erstellen,&nbsp;gelangen sie zu folgender Eingabemaske.</td>
</tr>
</table><fieldset> <legend> <img width="21" height="22" border="0" align="middle" alt="Info" title="Info" src="template/lang/all/info_s.gif" />  <strong> Feldbeschreibungen</strong></legend>
<table width="100%" cellspacing="0" cellpadding="6" border="0">
    <tbody>
        <tr class="tbfield">
            <td>Seitenebenen &Uuml;berschrift&nbsp;&nbsp;&nbsp;</td>
            <td>Bestimmen Sie hier den Titel der Ebene.</td>
        </tr>
        <tr>
            <td>Alias der Seitenebene</td>
            <td>
            <p>Hier bestimmen Sie den Alias der Strukturebene, dieser wird zum direktem Ansprechen der Ebene ben&ouml;tigt.<br />
            <br />
            Beispiel: www.ihre_domain.tld/index.php?<strong>alias<br />
            <br />
            </strong>Wenn Sie das Rewrite verwenden, wird aus dem Alias auch der Seitentitel erzeugt.<br />
            <br />
            Beispiel: www.ihre_domain.tld/<strong>alias.phtml</strong></p>
            </td>
        </tr>
        <tr class="tbfield">
            <td>Seitentitel&nbsp;</td>
            <td>Sie k&ouml;nnen noch separat einen anderen Seitentitel erzeugen. Dieser erscheint dann in der Titelleiste des Browsers (nur im Artikellistenmodus verf&uuml;gbar). Was in der Titelleiste angezeigt wird, bestimmen Sie in Ihrem Template unter &quot;Titel hinzuf&uuml;gen:&quot;</td>
        </tr>
        <tr>
            <td>Weiterleiten</td>
            <td>Hier besteht die M&ouml;glichkeit,&nbsp;in eine andere Struktur oder auch auf externen Inhalt weiterzuleiten.<br />
            <br />
            Wenn Sie seitenintern weiterleiten wollen, empfiehlt sich der <a href="system_tags_.phtml" class="phpwcmsIntLink">{<img src="img/leer.gif" border="0" width="0" height="0" alt="" />SITE}</a> Tag.<br />
            <br />
            Wenn Sie auf eine externe Seite weiterleiten wollen, geben sie hier einfach die URL der externen Seite ein, gefolgt von einem _blank.&nbsp;<br />
            <br />
            <strong>Hinweis:<br />
            </strong>Verwenden Sie f&uuml;r interne Weiterleitungen <strong>immer </strong>folgende Schreibweise <strong>index.php?ihr_alias</strong></td>
        </tr>
        <tr class="tbfield">
            <td>Beschreibung der Seitenebene:</td>
            <td><strike>Hier k&ouml;nnen Sie f&uuml;r andere Redakteure noch eine Beschreibung der Ebene eintragen. Dieser ist nicht f&uuml;r die Besucher der Seite sichtbar.<br />
            </strike>Der hier eingetragene Text wird in den Meta Descriptions eingesetzt, wenn unter &quot;Artikel Basisinformation&quot; kein alternativer Text im dortigen Feld &quot;Beschreibung:&quot; eingetragen wurde. <br />
            <b>             Priorit&auml;t:</b> 1. Artikel Basisinformation, 2. Seitenstruktur<br />
            <br />
            <b>Hinweis:<br />
            Arbeiten Artikel im Listenmodus (Mehrere Artikel in einer Kategorie) werden die Informationen aus der Seitenstruktur verwendet.</b></td>
        </tr>
        <tr>
            <td>Vorlage:</td>
            <td>W&auml;hlen Sie hier aus, welches Template f&uuml;r die neue Struktur verwendet werden soll.</td>
        </tr>
        <tr class="tbfield">
            <td>Einstellungen:</td>
            <td>Hier ist es m&ouml;glich, eine andere Vorlage f&uuml;r das Gesamte Aussehen der Seite zu w&auml;hlen. Dazu liegt unter &quot;<strong>template/inc_settings/template_default/</strong>&quot; die Datei &quot;<strong>custom_settings.php</strong>&quot; diese Datei enth&auml;lt die gleichen Werte wie die conf.template_default.php, die Sie im Config Verzeichnis von phpwcms finden.<br />
            <strong><br />
            Hinweis:<br />
            Bitte beachten Sie, wenn Sie &Auml;nderungen an der &quot;</strong><strong>custom_settings.php&quot; vornehmen, diese auch umzubenennen, da bei einem Update die Datei &uuml;berschrieben werden k&ouml;nnte.</strong></td>
        </tr>
        <tr>
            <td>Anzahl Top Artikel</td>
            <td>Hier bestimmen Sie, wie viele Artikel mit Schlagtext auf der Seite angezeigt werden sollen. Der Standard ist &quot;-1&quot; und bedeutet, dass alle Artikel mit&nbsp; Schlagtext in dieser Ebene angezeigt werden.<br />
            <br />
            Wenn Sie jedoch einen Artikel paginieren wollen m&uuml;ssen Sie hier die Anzahl der Artikel eintragen oder h&ouml;her. Wenn Sie &quot;-1&quot; dort stehen lassen funktioniert die Paginierung nicht.</td>
        </tr>
        <tr class="tbfield">
            <td>Paginierung:</td>
            <td>Es ist m&ouml;glich, einen oder mehrere Artikel auf&nbsp; mehrere Seiten aufzuteilen.<br />
            <br />
            Mit dem Wert, den Sie in das Feld &quot;<strong>Artikel je Seite</strong>&quot; eintragen bestimmen Sie, wieviele Artikel je Seite angezeigt werden.</td>
        </tr>
        <tr>
            <td>Anordnung zugeordneter Artikel:</td>
            <td>
            <p>Hier k&ouml;nnen Sie bestimmen, in welcher&nbsp;Sortierung&nbsp;die Artikel mit Schlagtext aufgef&uuml;hrt werden.<br />
            <br />
            Folgende Einstellungen sind m&ouml;glich:<br />
            <br />
            <strong>manuell (Pfeil auf/ab)<br />
            Erstellungsdatum<br />
            &Auml;nderungsdatum<br />
            Startdatum<br />
            Enddatum</strong><strong><br />
            Artikeltitel<br />
            </strong><br />
            Au&szlig;erdem k&ouml;nnen Sie durch Ausw&auml;hlen von<br />
            <br />
            <strong>aufsteigend<br />
            absteigend</strong>&nbsp;<br />
            <br />
            die Reihenfolge bestimmen.</p>
            </td>
        </tr>
        <tr class="tbfield">
            <td>Content Part Selektion:</td>
            <td>Hier haben Sie die M&ouml;glichkeit, als Administrator zu bestimmen welche Content Parts in dieser Ebene zur Verf&uuml;gung stehen. W&auml;hlen Sie keinen aus, werden alle angezeigt.<br />
            <br />
            W&auml;hlen Sie dazu den entsprechenden Content Part im linken Fenster aus und f&uuml;gen Sie ihn mit <img align="bottom" src="./img/button/put_left_a.gif" alt="" /> hinzu. Entfernen k&ouml;nnen Sie diesen wieder mit&nbsp;<img align="bottom" src="./img/button/put_right_a.gif" alt="" />.</td>
        </tr>
        <tr>
            <td>Frontend Men&uuml;status</td>
            <td>Sie haben hier zwei M&ouml;glichkeiten:&nbsp;<br />
            <br />
            <strong>versteckt:</strong> Wenn Sie hier den Haken setzen, wird diese Struktur f&uuml;r Besucher nicht in der Navigation&nbsp;angezeigt<br />
            <br />
            <strong>sichtbar, wenn aktiv:</strong> <br />
            <br />
            <strong>sichtbar nur f&uuml;r angemeldete Benutzer: </strong>Hat im Moment noch keine Funktion</td>
        </tr>
        <tr class="tbfield">
            <td>Cache</td>
            <td>Wenn Sie hier den Haken setzen, wird die Seite nicht vom Cache ber&uuml;cksichtigt. Ansonsten k&ouml;nnen Sie bestimmen, nach welcher Zeit die Seite neu in den Cache eingelesen wird. Es ist ein Zeitraum von 1min bis 1 Monat m&ouml;glich.</td>
        </tr>
        <tr>
            <td>Suche</td>
            <td>Hier k&ouml;nnen Sie bestimmen, ob der Artikelinhalt mit in die Suche einbezogen werden soll. <br />
            Standard ist, dass der Inhalt gefunden werden kann. Durch Setzen des Hakens wird der Inhalt bei der Suche ausgeschlossen.</td>
        </tr>
        <tr class="tbfield">
            <td>sichtbar / &ouml;ffentlich</td>
            <td>Um&nbsp;die Struktur&nbsp;f&uuml;r Besucher sichtbar zu machen, setzen Sie bitte bei <strong>sichtbar</strong> und <strong>&ouml;ffentlich</strong> einen Haken.</td>
        </tr>
        <tr>
            <td>SSL</td>
            <td>Um SSL nutzen zu k&ouml;nnen ben&ouml;tigen Sie ein SSL Zertifikat. Sollten Sie eines besitzen, &auml;ndern Sie bitte die n&ouml;tigen Eintr&auml;ge in der (config/phpwcms/)<strong>conf.inc.php</strong> unter dem Punkt &quot;/<strong>/ dynamic ssl encryption engine</strong>&quot;</td>
        </tr>
        <tr class="tbfield">
            <td>Sitemap</td>
            <td>Hier k&ouml;nnen Sie durch Setzen den Hakens bestimmen, ob der Artikel in der Sitemap angezeigt werden soll.</td>
        </tr>
    </tbody>
</table>
</fieldset><div style="margin:10px 0 0 0;padding:0;" class="spaceBeforeCP"></div>Weiter zu...<br /><a href="317.0.0.1.0.0.phtml">Ebene verschieben</a><div align="right"><a href="#top"><img src="img/article/top_link_0.gif" border="0" alt="" /></a></div>
		 
		
		<br /><br />
		<div class="sub">
		Artikel erstellt am: Sonntag, 16. Januar 2005 <br /> Letzte &Auml;nderung: Dienstag, 04. Januar 2011	
		</div>
				
	</div>
	
<div id="footer">





	<table width="97%" border="0" cellspacing="0" cellpadding="0">
		<tr>
			<td valign="bottom">	
			&copy; phpwcms-docu 2004-2015
			<img src="img/leer.gif" border="0" width="10" height="0" alt="" /><a href="impressum.phtml" class="phpwcmsIntLink"><img src="template/lang/all/icons/imprint.gif" width="9" height="15" alt="Impressum" title="Impressum" border="0" /></a>&nbsp; 
			<a href="sitemap_de.phtml" class="phpwcmsIntLink"><img src="template/lang/all/icons/sitemap.gif" width="19" height="15" alt="Sitemap" title="Sitemap" border="0" /></a>&nbsp; 
			<a href="gaestebuch.phtml" class="phpwcmsIntLink"><img src="template/lang/all/icons/gbook.gif" width="20" height="16" alt="Ins G&auml;stebuch eintragen" title="Ins G&auml;stebuch eintragen" border="0" /></a>&nbsp; 
			<a href="#" onclick="BookMark_Page();return false;" title="" class="phpwcmsBookmarkLink"><img src="template/lang/all/icons/favo.gif" width="12" height="15" alt="Seite als Bookmark speichern" title="Seite als Bookmark speichern" border="0" /></a>&nbsp; 
			     
			</td>
			<td valign="bottom" style="padding-right:25px;">
			
			
			
			</td>		
			<td width="150">
			</td>
		</tr>
	</table>
</div><br/>

</div>
</body>
</html>