<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<!--
	phpwcms | free open source content management system
	created by Oliver Georgi (oliver at phpwcms dot de) and licensed under GNU/GPL.
	phpwcms is copyright 2003-2006 of Oliver Georgi. Extensions are copyright of\
	their respective owners. Visit project page for details: http://www.phpwcms.org/
//-->
<title></title>
  <meta http-equiv="content-type" content="text/html; charset=iso-8859-1" />
  <meta http-equiv="content-style-type" content="text/css" />
  <script src="template/inc_js/frontend.js" type="text/javascript"></script>
  <style type="text/css" media="all">
  /* <![CDATA[ */
    body {
      margin: 0;
      padding-top: 0;
      padding-bottom: 0;
      padding-left: 0;
      padding-right: 0;

    }
  /* ]]> */
  </style>
  <style type="text/css">
  /* <![CDATA[ */
    @import url("template/inc_css/frontend.css");
    @import url("template/inc_css/nlu_navi1_docu.css");
    @import url("template/inc_css/print_layout.css");
  /* ]]> */
  </style>


<META NAME="Title" CONTENT="Die phpWCMS Dokumentation">
<meta name="author" content="Oliver Frohnert">
<meta name="Publisher" content="Oliver Frohnert">
<meta name="Copyright" content="Oliver Frohnert">
<meta name="keywords" content="frohnert,documentation, dokumentation, phpwcms, cms, opensource, open source">
<meta name="description" content="Das Dokumentations Projekt für das Open Source CMS phpWCMS">
<meta name="Audience" content="Alle">
<meta name="Content-language" content="DE">
<META NAME="robots"      CONTENT="index,follow">
<META NAME="expires" CONTENT="0">
<meta name="revisit-after" content="7 days">
<meta name="resource-type" content="document">
<meta name="distribution" content="Global">
<meta name="generator" content="PHPWCMS">

  <!--[if lt IE 7]>
  <style type="text/css">
    body { behavior: url("template/inc_css/specific/csshover2.htc"); }
    img { behavior: url("template/inc_css/specific/pngbehavior.htc"); }
  </style>
  <![endif]-->
</head>
<body>
<img src="img/leer.gif" border="0" width="10" height="1" alt="" />
<br />
<a href="deutsche_version.phtml">Deutsch</a> <span class="breadcrumb_spacer">&gt;</span> <a href="die_docu.phtml">Die Docu</a> <span class="breadcrumb_spacer">&gt;</span> <a href="verwaltung_artikel.phtml">Artikel</a> <span class="breadcrumb_spacer">&gt;</span> <a href="artikel_organisation.phtml">Artikel Organisation</a> <span class="breadcrumb_spacer">&gt;</span> Artikel verschieben
<br />
<HR>
<br />
<a name="jump318"></a><h1>Artikel verschieben</h1><div style="margin:10px 0 0 0; padding:0 0 0 0; clear:both;"></div><div class="articleText"><p align="justify">Wollen Sie einen Artikel in eine andere Strukturebene kopieren, gehen Sie wie folgt vor: <br /><br />1. Gehen Sie in die Artikelzentrale<br /><br />2. Klicken Sie auf das Symbol <img alt="" src="./img/button/cut_11x11_0.gif" align="absMiddle" />&nbsp;des zu verschiebenden Artikels. Das Symbol wechselt zu&nbsp;<img alt="" src="./img/button/cut_11x11_3.gif" align="absMiddle" /> und die Zeile wird mit einem gr&uuml;nen Balken markiert dargestellt, um anzuzeigen, das der gew&uuml;nschte Artikel&nbsp;ausgew&auml;hlt ist. <br /><br /><br /></p></div><table width="538" border="0" cellspacing="0" cellpadding="0" align="center">
<tr><td><img src="img/leer.gif" width="1" height="5" border="0" alt="" /></td></tr>
<tr><td class="image_td"><img src="content/images/79c1e8d6d7a224c860492b538cd52db3.png" width="538" height="136" border="0" class="image_img" alt="artikel_verschieben_126_a.png" /></td></tr>
</table><div class="articleText"><p align="justify">Sie sehen nun an jeder Strukturebene einen gr&uuml;nen Pfeil <img alt="" src="./img/button/cut_11x11_1.gif" align="absMiddle" />, dies zeigt Ihnen, dass dort ein Einf&uuml;gen des von Ihnen ausgew&auml;hlten Artikels m&ouml;glich ist. <br /><br />Durch Klicken auf den&nbsp;roten Pfeil <img alt="" src="./img/button/cut_11x11_1.gif" align="absMiddle" />&nbsp;f&uuml;gen Sie den Artikel in der von Ihnen gew&uuml;nschten Strukturebene ein. Zur Orientierungshile wird die Zeile hellgr&uuml;n hinterlegt.</p></div><table width="538" border="0" cellspacing="0" cellpadding="0" align="center">
<tr><td><img src="img/leer.gif" width="1" height="5" border="0" alt="" /></td></tr>
<tr><td class="image_td"><img src="content/images/102b482bda5089183ed43cab18ed3fdd.png" width="538" height="153" border="0" class="image_img" alt="artikel_verschieben_126_c.png" /></td></tr>
</table><div style="margin:10px 0 0 0; padding:0 0 0 0; clear:both;"></div><div class="articleText">Sie sehen nun, dass der Artikel in der von Ihnen gew&uuml;nschten Ebene eingef&uuml;gt ist.</div><table width="538" border="0" cellspacing="0" cellpadding="0" align="center">
<tr><td><img src="img/leer.gif" width="1" height="5" border="0" alt="" /></td></tr>
<tr><td class="image_td"><img src="content/images/5bfb3fb4607e02bab5557d8c696a777f.png" width="538" height="131" border="0" class="image_img" alt="artikel_verschieben_126_d.png" /></td></tr>
</table><div style="margin:10px 0 0 0; padding:0 0 0 0; clear:both;"></div><p align="justify">Dr&uuml;cken Sie nun zum Abschlu&szlig; nochmal auf das folgendes Symbol&nbsp;<img alt="" src="./img/button/cut_11x11_3.gif" align="absMiddle" />&nbsp;des Artikels, den Sie&nbsp;verschoben haben. Somit verlassen Sie den Verschiebemodus f&uuml;r diesen Artikel. Die&nbsp;gr&uuml;neMArkierung&nbsp;des Artikels wandelt sich wieder zu wei&szlig; und das Symbol wird wieder zu&nbsp;<img alt="" src="./img/button/cut_11x11_0.gif" align="absMiddle" />.</p><div align="right"><a href="#top"><img src="img/article/top_link_0.gif" border="0" alt="" /></a></div>
<table width="100%"  border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td colspan="2"><HR></td>
  </tr>
  <tr>
    <td width="50%">Artikel erstellt: 2005/12/18</td>
    <td align="right" width="50%">Letzte Änderung:2005/12/26</td>
  </tr>
  <tr>
    <td colspan="2">&nbsp;</td>
  </tr>
  <tr>
    <td colspan="2" class="comment">Wenn Sie einen Fehler entdecken eine Ergänzung oder Frage haben benutzen Sie bitte folgendes <a href="#" onClick="javascript:window.open('./content/pages/nachricht.htm','frage','width=400, height=250, screenX=440,screenY=200,menubar=no,statusbar=yes,scrollbar=yes,resizable=no');" target="" style="max-width:148px; overflow:hidden;"><u>Formular</u></a>.<br /><br />
Hat Ihnen oder Ihrem Kunden diese Docu weitergeholfen ? Dann würde ich mich freuen wenn Sie das Projekt unterstützen würden. Bitte nutzen Sie dafür diesen <a href="#paypal">PayPal</a> Link. Jeder Betrag ist möglich und hilft der Weiterentwicklung und Aktualisierung dieser Dokumentation.<br />
Diese Seite nutzt die version:</td>
  </tr>
  <tr>

    <td colspan="2"><img src="img/leer.gif" border="0" width="10" height="10" alt="" /></td>
  </tr>
</table>

</body>
</html>