<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<!--
     phpwcms | free open source content management system
     created by Oliver Georgi (oliver at phpwcms dot de) and licensed under GNU/GPL.
     phpwcms is copyright 2003-2005 of Oliver Georgi. Extensions are copyright of
     their respective owners. Visit project page http://www.phpwcms.org for details.
//-->
<html>
<head>
<title>phpwcms documentation | Copy Articles</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<script src="template/inc_js/frontend.js" type="text/javascript"></script>
<link rel="stylesheet" type="text/css" href="template/inc_css/frontend.css">
<META NAME="Title" CONTENT="The phpWCMS Documentation">
<meta name="author" content="Oliver Frohnert">
<meta name="Publisher" content="Oliver Frohnert">
<meta name="Copyright" content="Oliver Frohnert">
<meta name="keywords" content="frohnert,documentation, dokumentation, phpwcms, cms. opensource, open source">
<meta name="description" content="A Documentation Project for the  Open Source CMS phpWCMS">
<meta name="Audience" content="Alle">
<meta name="Content-language" content="EN">
<META NAME="robots"      CONTENT="index,follow">
<META NAME="expires" CONTENT="0">
<meta name="revisit-after" content="7 days">
<meta name="resource-type" content="document">
<meta name="distribution" content="Global">
<meta name="generator" content="PHPWCMS">
<script language="JavaScript" type="text/javascript" src="pphlogger.js"></script>
<noscript><img alt="" src="./pphlogger/pphlogger.php?id=phpwcms&st=img"></noscript>
<!-- Start of StatCounter Code -->
<script type="text/javascript" language="javascript">
var sc_project=644539;
var sc_partition=5;
var sc_security="2e37fa21";
</script>

</head>

<body bgcolor="#FFFFFF" text="#000000" link="#FF9900" vlink="#FF9900" alink="#FF9900" style="margin:0px 0px 0px 0px;">
<table border="0" cellspacing="0" cellpadding="0" width="760" bgcolor="#ffffff" class="maintable" align="center">
<tr>
<td colspan="2" style="height:60px;"  bgcolor="#ffffff"><table width="760" height="135" border="0" cellpadding="0" cellspacing="0">
  <tr valign="top">
    <td width="1334" height="122" colspan="6"><IMG src="/template/lang/en/header.jpg" alt="" border="0"></td>
  </tr>
  <tr>
	<td height="27" background="template/lang/all/top_menu.jpg"><table width="570" border="0" align="left" cellpadding="0" cellspacing="0">
      <tr>
        <td align="center" width="254"><a href="deutsche_version.phtml"><img src="picture/flags/de.gif" width="16" height="10" hspace="10" border="0"  alt="Deutsche Version" title="Deutsche Version"></a>
<a href="english_version.phtml"><img src="picture/flags/gb.gif" width="16" height="10" hspace="10" border="0"  alt="English Version" title="English Version"></a></td>
        <td valign="middle"><div align="center"><a href="replacement_tags_en.phtml"><img src="content/gt/8c10fcb16c44a7b9c26a5a932c5e4ae9.png" alt="Replacement Tags" title="Replacement Tags" border="0" /></a></div></td>
        <td width="30" valign="middle"><div align="center"><img src="template/lang/all/sep.gif" width="5" height="5" border="0"></div></td>
        <td valign="middle"><div align="center"><a href="content_parts_en.phtml"><img src="content/gt/02725c45a346fbf433a4c83e02d8dc5a.png" alt="Content Parts" title="Content Parts" border="0" /></a></div></td>
        <td width="30" valign="middle"><div align="center"><img src="template/lang/all/sep.gif" width="5" height="5" border="0"></div></td>
        <td valign="middle"><div align="center"><a href="links_de.phtml"><img src="content/gt/2c41bfb28d6dd3d4bbc8bb7688fd62ee.png" alt="Links" title="Links" border="0" /></a></div></td>
        <td width="30" valign="middle"><div align="center"><img src="template/lang/all/sep.gif" width="5 " height="5" border="0"></div></td>
        <td valign="middle"><div align="center"><a href="imprint.phtml"><img src="content/gt/8b40044a8de89d790c10c1671094a297.png" alt="Imprint" title="Imprint" border="0" /></a></div></td>
     </tr>
    </table>    </td>
  </tr>
</table></td>
</tr>
<tr>
<td valign="top" width="185" background="img/menu.gif"><table width="180" border="0" cellpadding="0" cellspacing="0">
  <tr>
    <td width="180" height="20">&nbsp;</td>
  </tr>
  <tr>
    <td style="padding-left: 7px;"><table border="0" cellspacing="0" cellpadding="0" width="100%">
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='deutsche_version.phtml?cvs_info_en';return false;" onMouseOver="MM_swapImage('linkidx8Qf0c','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td width="7" colspan="2"><img src="img/leer.gif" width="7" height="15" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkidx8Qf0c" id="linkidx8Qf0c"></td>
<td valign="top" style="height:15px;"  width="100%" class="nav_table" colspan="4"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="deutsche_version.phtml?cvs_info_en">News</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="7"><img src="img/leer.gif" width="10" height="15" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='installation_en.phtml';return false;" onMouseOver="MM_swapImage('linkidXf59bx','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td width="7" colspan="2"><img src="img/leer.gif" width="7" height="15" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkidXf59bx" id="linkidXf59bx"></td>
<td valign="top" style="height:15px;"  width="100%" class="nav_table" colspan="4"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="installation_en.phtml">Installation &amp; Upgrade</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="7"><img src="img/leer.gif" width="10" height="15" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='the_docu.phtml';return false;">
<td width="7" colspan="2"><img src="img/leer.gif" width="7" height="15" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_2" alt="" border="" name="linkiddaq99C" id="linkiddaq99C"></td>
<td valign="top" style="height:15px;"  width="100%" class="nav_table_active" colspan="4"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="the_docu.phtml">The Docu<img src="picture/myRT1/newR.gif" alt="2/13/2006" border="0"></a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="7"><img src="img/leer.gif" width="10" height="15" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='article.phtml';return false;">
<td width="7" colspan="3"><img src="img/leer.gif" width="7" height="15" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_2" alt="" border="" name="linkidRIXeSL" id="linkidRIXeSL"></td>
<td valign="top" style="height:15px;"  width="100%" class="nav_table_active" colspan="3"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="article.phtml">Articles</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="7"><img src="img/leer.gif" width="10" height="15" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='creating_articles.phtml';return false;" onMouseOver="MM_swapImage('linkid1Zn7ra','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td width="7" colspan="4"><img src="img/leer.gif" width="7" height="15" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkid1Zn7ra" id="linkid1Zn7ra"></td>
<td valign="top" style="height:15px;"  width="100%" class="nav_table" colspan="2"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="creating_articles.phtml">Creating Articles</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="7"><img src="img/leer.gif" width="10" height="15" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='editing_articles.phtml';return false;" onMouseOver="MM_swapImage('linkidlsYHM9','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td width="7" colspan="4"><img src="img/leer.gif" width="7" height="15" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkidlsYHM9" id="linkidlsYHM9"></td>
<td valign="top" style="height:15px;"  width="100%" class="nav_table" colspan="2"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="editing_articles.phtml">Editing Articles </a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="7"><img src="img/leer.gif" width="10" height="15" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='article_organization.phtml';return false;">
<td width="7" colspan="4"><img src="img/leer.gif" width="7" height="15" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_2" alt="" border="" name="linkidhdu8qw" id="linkidhdu8qw"></td>
<td valign="top" style="height:15px;"  width="100%" class="nav_table_active" colspan="2"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="article_organization.phtml">Article Organization</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="7"><img src="img/leer.gif" width="10" height="15" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='copy_article.phtml';return false;">
<td width="7" colspan="5"><img src="img/leer.gif" width="7" height="15" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_2" alt="" border="" name="linkidhFFpJc" id="linkidhFFpJc"></td>
<td valign="top" style="height:15px;"  width="100%" class="nav_table_active"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="copy_article.phtml">Copy Article</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="7"><img src="img/leer.gif" width="10" height="15" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='content_parts_en.phtml';return false;" onMouseOver="MM_swapImage('linkidD7tXOy','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td width="7" colspan="4"><img src="img/leer.gif" width="7" height="15" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkidD7tXOy" id="linkidD7tXOy"></td>
<td valign="top" style="height:15px;"  width="100%" class="nav_table" colspan="2"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="content_parts_en.phtml">Content Parts</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="7"><img src="img/leer.gif" width="10" height="15" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='deutsche_version.phtml?File_Administration';return false;" onMouseOver="MM_swapImage('linkidr2C9fd','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td width="7" colspan="3"><img src="img/leer.gif" width="7" height="15" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkidr2C9fd" id="linkidr2C9fd"></td>
<td valign="top" style="height:15px;"  width="100%" class="nav_table" colspan="3"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="deutsche_version.phtml?File_Administration">File</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="7"><img src="img/leer.gif" width="10" height="15" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='module_en.phtml';return false;" onMouseOver="MM_swapImage('linkidby7DYG','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td width="7" colspan="3"><img src="img/leer.gif" width="7" height="15" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkidby7DYG" id="linkidby7DYG"></td>
<td valign="top" style="height:15px;"  width="100%" class="nav_table" colspan="3"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="module_en.phtml">Modules</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="7"><img src="img/leer.gif" width="10" height="15" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='message.phtml';return false;" onMouseOver="MM_swapImage('linkidBQRx1z','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td width="7" colspan="3"><img src="img/leer.gif" width="7" height="15" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkidBQRx1z" id="linkidBQRx1z"></td>
<td valign="top" style="height:15px;"  width="100%" class="nav_table" colspan="3"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="message.phtml">Message </a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="7"><img src="img/leer.gif" width="10" height="15" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='chat_en.phtml';return false;" onMouseOver="MM_swapImage('linkidmRUuiG','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td width="7" colspan="3"><img src="img/leer.gif" width="7" height="15" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkidmRUuiG" id="linkidmRUuiG"></td>
<td valign="top" style="height:15px;"  width="100%" class="nav_table" colspan="3"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="chat_en.phtml">Chat</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="7"><img src="img/leer.gif" width="10" height="15" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='profile.phtml';return false;" onMouseOver="MM_swapImage('linkidEBR4JT','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td width="7" colspan="3"><img src="img/leer.gif" width="7" height="15" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkidEBR4JT" id="linkidEBR4JT"></td>
<td valign="top" style="height:15px;"  width="100%" class="nav_table" colspan="3"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="profile.phtml">Profile</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="7"><img src="img/leer.gif" width="10" height="15" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='admin_en_wpj.phtml';return false;" onMouseOver="MM_swapImage('linkidKkB8ST','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td width="7" colspan="3"><img src="img/leer.gif" width="7" height="15" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkidKkB8ST" id="linkidKkB8ST"></td>
<td valign="top" style="height:15px;"  width="100%" class="nav_table" colspan="3"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="admin_en_wpj.phtml">Admin<img src="picture/myRT1/newR.gif" alt="2/13/2006" border="0"></a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="7"><img src="img/leer.gif" width="10" height="15" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='add_on_en.phtml';return false;" onMouseOver="MM_swapImage('linkidlLTWAy','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td width="7" colspan="2"><img src="img/leer.gif" width="7" height="15" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkidlLTWAy" id="linkidlLTWAy"></td>
<td valign="top" style="height:15px;"  width="100%" class="nav_table" colspan="4"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="add_on_en.phtml">Add On&#039;s</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="7"><img src="img/leer.gif" width="10" height="15" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='error_messages.phtml';return false;" onMouseOver="MM_swapImage('linkid7OGy1H','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td width="7" colspan="2"><img src="img/leer.gif" width="7" height="15" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkid7OGy1H" id="linkid7OGy1H"></td>
<td valign="top" style="height:15px;"  width="100%" class="nav_table" colspan="4"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="error_messages.phtml">Error messages</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="7"><img src="img/leer.gif" width="10" height="15" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='search.phtml';return false;" onMouseOver="MM_swapImage('linkid1nSZrb','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td width="7" colspan="2"><img src="img/leer.gif" width="7" height="15" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkid1nSZrb" id="linkid1nSZrb"></td>
<td valign="top" style="height:15px;"  width="100%" class="nav_table" colspan="4"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="search.phtml">Search</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="7"><img src="img/leer.gif" width="10" height="15" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='contact.phtml';return false;" onMouseOver="MM_swapImage('linkidALddcP','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td width="7" colspan="2"><img src="img/leer.gif" width="7" height="15" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkidALddcP" id="linkidALddcP"></td>
<td valign="top" style="height:15px;"  width="100%" class="nav_table" colspan="4"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="contact.phtml">Contact</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="7"><img src="img/leer.gif" width="10" height="15" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="window.open('http://chat.phpwcms-docu.de', 'phpwcmnewwin');return false;" onMouseOver="MM_swapImage('linkidazdVfO','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td width="7" colspan="2"><img src="img/leer.gif" width="7" height="15" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkidazdVfO" id="linkidazdVfO"></td>
<td valign="top" style="height:15px;"  width="100%" class="nav_table" colspan="4"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="http://chat.phpwcms-docu.de" target="_blank">LIVE Chat</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="7"><img src="img/leer.gif" width="10" height="15" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='faq_en.phtml';return false;" onMouseOver="MM_swapImage('linkidtzoBuG','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td width="7" colspan="2"><img src="img/leer.gif" width="7" height="15" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkidtzoBuG" id="linkidtzoBuG"></td>
<td valign="top" style="height:15px;"  width="100%" class="nav_table" colspan="4"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="faq_en.phtml">FAQ<img src="picture/myRT1/newR.gif" alt="2/17/2006" border="0"></a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="7"><img src="img/leer.gif" width="10" height="15" alt="" /></td>
</tr>
</table></td>
  </tr>
 <tr>
    <td style="padding:10px; color:#000000;"><img src="picture/seperate.gif" border="0" alt="" /><BR><BR>
<a href="http://www.phpwcms.de/index.php?id=1,38,0,0,1,0" target="Blank">
<img src="content/gt/0bdf1abd9b924ef5db1c4d8b0ee60b57.png" alt="Important!!!" title="Important!!!" border="0" /><br>
<img src="content/gt/9053324adb81af310e436b5603bba41a.png" alt="Security fixes" title="Security fixes" border="0" /><br>
<img src="content/gt/8d03f106ba326cbce77da5e9d2a6fabe.png" alt="for the releases" title="for the releases" border="0" /><br>
<img src="content/gt/f6b3d6651de467e44cfdc1170eaba9d3.png" alt="1.1-RC4 / 1.1.9 / 1.2.3" title="1.1-RC4 / 1.1.9 / 1.2.3" border="0" /><br>
<img src="content/gt/9661ea0c3a00342c05e40467dd5ec5e5.png" alt="more..." title="more..." border="0" /></a><br><BR>
<img src="picture/seperate.gif" border="0" alt="" /><BR><BR>
<img src="content/gt/c71f316069deb34233025e9c4f057258.png" alt="Latest Version:" title="Latest Version:" border="0" /><br>
<img src="content/gt/e1fd75b3780539bb61dee5207be17344.png" alt="phpwcms 1.2.5-DEV" title="phpwcms 1.2.5-DEV" border="0" /><br><br>
<img src="content/gt/8dc723ca158601224d90ffc1e8ce1cf9.png" alt="Release Date:" title="Release Date:" border="0" /><img src="content/gt/03b1359638c5aa316e71c675a057924b.png" alt="14.08.2005" title="14.08.2005" border="0" /><BR>
<span style="align: right;"><a href="deutsche_version.phtml?id=286,216,0,0,1,0"><img src="content/gt/52a225872f962dd15d7991a1bb034024.png" alt="more..." title="more..." border="0" /></a></span><BR><BR>
<img src="picture/seperate.gif" border="0" alt="" /><BR><BR>
<a href="deutsche_version.phtml?cvs_info_en">
<img src="content/gt/f704f104d78353285df1da0d71934909.png" alt="Latest CVS Version:" title="Latest CVS Version:" border="0" /><br>
<img src="content/gt/146e33b31b78f1788072a33538f9b258.png" alt="phpwcms 1.2.6-DEV" title="phpwcms 1.2.6-DEV" border="0" /><BR>
<img src="content/gt/4af2b02fae456293d46da339f5a6ff76.png" alt="(patched)" title="(patched)" border="0" /><br><br>
<img src="content/gt/8dc723ca158601224d90ffc1e8ce1cf9.png" alt="Release Date:" title="Release Date:" border="0" /><BR>
<img src="content/gt/6667ead159ad3bb94a22870751be31a0.png" alt="14.12.2005" title="14.12.2005" border="0" /><BR>
<span style="align: right;"><img src="content/gt/11c0da7af1db5732850053c45a24a778.png" alt="DOWNLOAD" title="DOWNLOAD" border="0" /></a></span><BR><BR>
<img src="picture/seperate.gif" border="0" alt="" /></TD><BR>
  </tr>
<tr>
    <td height="20">&nbsp;</td>
  </tr>
  <tr>
    <td align="center"></td>
  </tr>
  <tr>
    <td height="20">&nbsp;</td>
  </tr>
</table>


</body>
</html>
</td>
<td valign="top" width="555" bgcolor="#ffffff" class="maincontent"><img src="img/leer.gif" border="0" width="10" height="1" alt="" />
<BR>
<a href="english_version.phtml">English</a> <span class="breadcrumb_spacer">&gt;</span> <a href="the_docu.phtml">The Docu<img src="picture/myRT1/newR.gif" alt="2/13/2006" border="0"></a> <span class="breadcrumb_spacer">&gt;</span> <a href="article.phtml">Articles</a> <span class="breadcrumb_spacer">&gt;</span> <a href="article_organization.phtml">Article Organization</a> <span class="breadcrumb_spacer">&gt;</span> Copy Article
<br>
<HR>
<br>
<a name="jump316"></a><h1>Copy Articles</h1><div style="margin:10px 0 0 0; padding:0 0 0 0; clear:both;"></div><div class="articleText"><p align="justify">When you want to copy an article into an other structure level, please proceed this way: <br /><br />1. Go to the article center<br /><br />2. Click on the icon <img src="picture/../img/button/copy_11x11_0.gif" border="0" alt="" /> of the article to move. The icon changes to <img src="picture/../img/button/copy_11x11_3.gif" border="0" alt="" /> and the line will be marked with a green bar to show that the desired article has been chosen. <br /><br /><br /></p></div><table width="538" border="0" cellspacing="0" cellpadding="0" align="center">
<tr><td><img src="img/leer.gif" width="1" height="5" alt="" /></td></tr>
<tr><td class="image_td"><a href="zoom/ODFjNzU4NjcwNDlkYTZlMjQxOWI3NDkwMmM0OGJhOWUucG5nP3dpZHRoPSI1NDkiIGhlaWdodD0iODki.html" onClick="checkClickZoom();clickZoom('zoom/ODFjNzU4NjcwNDlkYTZlMjQxOWI3NDkwMmM0OGJhOWUucG5nP3dpZHRoPSI1NDkiIGhlaWdodD0iODki','previewpic','width.html');return false;.html" target="_blank"><img src="content/images/ccf9806ec583dbc476a0fe47340ac553.png" width="538" height="87" border="0" class="image_img" alt="artikel_kopieren_126_de_b.png"></a></td></tr>
</table><div class="articleText"><p align="justify">Now you can see a green arrow at every structure level <img alt="" src="./img/button/copy_11x11_1.gif" align="absMiddle" />, this will show you that you can insert the chosen article at this place. <br /><br />With a click on the green arrow you can insert the article into the desired structure level. As an orientation guide the line will be marked bright green.</p></div><table width="538" border="0" cellspacing="0" cellpadding="0" align="center">
<tr><td><img src="img/leer.gif" width="1" height="5" alt="" /></td></tr>
<tr><td class="image_td"><img src="content/images/6bcb532474d30a1e1fb16a5ffeaf5fc9.png" width="538" height="88" border="0" class="image_img" alt="artikel_kopieren_126_de_c.png"></td></tr>
</table><div class="articleText">Now you can see that the article has been inserted into the desired level.</div><table width="538" border="0" cellspacing="0" cellpadding="0" align="center">
<tr><td><img src="img/leer.gif" width="1" height="5" alt="" /></td></tr>
<tr><td class="image_td"><img src="content/images/43bf6456b1fa433c80a9e5014f79cdba.png" width="538" height="103" border="0" class="image_img" alt="artikel_kopieren_126_de_d.png"></td></tr>
</table><p align="justify">At least you have once more to click onto the following icon&nbsp;<img alt="" src="./img/button/copy_11x11_3.gif" align="absMiddle" />&nbsp;of the copied article. Thus you leave the copy mode for this article. Die green mark of the article changes again to white and the icon will be again&nbsp;<img alt="" src="./img/button/copy_11x11_0.gif" align="absMiddle" />.</p><div align="right"><a href="#top"><img src="img/article/top_link_0.gif" border="0" alt="" /></a></div>
<table width="100%"  border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td colspan="2"><HR></td>
  </tr>
  <tr>
    <td width="50%">Article created: 2005/12/15</td>
    <td align="right" width="50%">Last Changes: 2005/12/15</td>
  </tr>
  <tr>
    <td colspan="2">&nbsp;</td>
  </tr>
  <tr>
    <td colspan="2" class="comment">In case you find any mistakes or have enhancments, please use this <a href="#" onClick="javascript:window.open('./content/pages/message.htm','frage','width=400, height=250, screenX=440,screenY=200,menubar=no,statusbar=yes,scrollbar=yes,resizable=no');" target="" style="max-width:148px; overflow:hidden;"><u>form</u></a> .<br><BR>
Have you found this website a helpful resource in understanding the Phpwcms content management system? If so, would you consider making a donation?  Please click here: <a href="#paypal">PayPal</a>. We welcome any donation amount. Your contribution helps make this website an even better resource and helps underwrite the associated server expenses of accomodating a growing number of visitors.<BR>
This page use the version:</td>
  </tr>
  <tr>

    <td colspan="2"><img src="img/leer.gif" border="0" width="10" height="10" alt="" /></td>
  </tr>
</table>
</td>
</tr>
<tr>
<td colspan="2" style="height:10px;"  bgcolor="#ffffff" class="footer"><table width="100%" height="20" background="img/footer.gif" cellpadding="0" cellspacing="0" border="0">
	<tr><td width="180" align="center" valign="middle">5 User online</td>
	<td>
	<table width="100%"cellpadding="0" cellspacing="0" border="0">
   <tr>
    <td align="center"><a href="javascript:history.back();" target="_top" title="go back"><img src="picture/back_.gif" border="0" alt="Back"><img src="content/gt/a8cf006b46d2d29bf7161aa985b04a42.png" alt="Back" title="Back" border="0" /></a></td>
	<td align="center"><a href="sitemap_en.phtml"><img src="picture/sitemap_.gif" border="0"  alt="Sitemap"><img src="content/gt/38062c01670c74843cc0b291d94966c6.png" alt="Sitemap" title="Sitemap" border="0" /></a></td>
	<td align="center"><a href="366.316.1.1.1.0.phtml" target="_blank"><img src="picture/print_.gif" border="0" alt="Print"><img src="content/gt/b4fe92ce3b96c84ca1ee38340fc2a4e6.png" alt="Print" title="Print" border="0" /></a></td>
	<td align="center"><a href="guestbook.phtml"><img src="picture/icon_gaestebuch.gif" border="0" align="top" alt="Guestbook"><img src="content/gt/a8891d2da470901a9086f978d5a7dc3d.png" alt="Guestbook" title="Guestbook" border="0" /></a></td>
	<td align="center"><a href="#" onClick="BookMark_Page();return false;" title=""><img src="picture/favoriten_.gif" border="0"  alt="Bookmark"><img src="content/gt/a8d175704cefbe0ee8222b9bde55b692.png" alt="Bookmark" title="Bookmark" border="0" /></a></td>
    </tr>
</table></td>
	</tr>
</table>
<img src="img/leer.gif" border="0" width="760" height="10" alt="" /></td>
</tr>
</table>
</body>
</html>