<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<!--
	phpwcms | free open source content management system
	created by Oliver Georgi (oliver at phpwcms dot de) and licensed under GNU/GPL.
	phpwcms is copyright 2003-2007 of Oliver Georgi. Extensions are copyright of
	their respective owners. Visit project page for details: http://www.phpwcms.org/
//-->
<title>phpwcms-docu for  phpwcms :: web based content management system | Kochrezept | Content Part &quot;Kochrezept&quot;</title>
  <meta http-equiv="content-type" content="text/html; charset=iso-8859-1" />
  <meta http-equiv="content-style-type" content="text/css" />
  <script src="template/inc_js/frontend.js" type="text/javascript"></script>
  <style type="text/css">
  <!-- 
    @import url("template/inc_css/mpl_docu.css");
    @import url("template/inc_css/mpl_frontend.css");
    @import url("template/inc_css/mpl_menu.css");
    @import url("template/inc_css/mpl_objects.css");
  //-->
  </style>
<script type="text/javascript" language="javascript">
<!--
function MM_jumpMenu(targ,selObj,restore){ //v3.0
  eval(targ+".location='"+selObj.options[selObj.selectedIndex].value+"'");
  if (restore) selObj.selectedIndex=0;
}

function MM_findObj(n, d) { //v4.01
  var p,i,x;  if(!d) d=document; if((p=n.indexOf("?"))>0&&parent.frames.length) {
    d=parent.frames[n.substring(p+1)].document; n=n.substring(0,p);}
  if(!(x=d[n])&&d.all) x=d.all[n]; for (i=0;!x&&i<d.forms.length;i++) x=d.forms[i][n];
  for(i=0;!x&&d.layers&&i<d.layers.length;i++) x=MM_findObj(n,d.layers[i].document);
  if(!x && d.getElementById) x=d.getElementById(n); return x;
}

function MM_jumpMenuGo(selName,targ,restore){ //v3.0
  var selObj = MM_findObj(selName); if (selObj) MM_jumpMenu(targ,selObj,restore);
}
//-->
</script>
<meta name="Title" content="Die phpWCMS Dokumentation" />
<meta name="author" content="Oliver Frohnert, Mario Perez Leal" />
<meta name="Publisher" content="Oliver Frohnert, Mario Perez Leal, creacion" />
<meta name="Copyright" content="Oliver Frohnert, Mario Perez Leal, creacion" />
<meta name="keywords" content="frohnert, perez leal, creacion, documentation, dokumentation, phpwcms, cms, opensource, open source, docu" />
<meta name="description" content="Das Dokumentations Projekt für das Open Source CMS phpWCMS" />
<meta name="Audience" content="Alle" />
<meta name="Content-language" content="DE" />
<meta name="robots" content="index,follow" />
<meta name="expires" content="0" />
<meta name="revisit-after" content="7 days" />
<meta name="resource-type" content="document" />
<meta name="distribution" content="Global" />
<meta name="generator" content="PHPWCMS" />
<meta name="verify-v1" content="1ZpxZ7AZsjm7PxjqXQVus0eiUYqOsp5URTJn9q4KNz8=" />
  <link rel="stylesheet" href="template/slimbox/css/slimbox.css" type="text/css" media="screen" />
  <script src="template/inc_js/mootools/mootools.js" type="text/javascript"></script>
  <script src="template/slimbox/js/slimbox.js" type="text/javascript"></script>
  <!--[if lt IE 7]>
  <style type="text/css">
    body { behavior: url("template/inc_css/specific/csshover2.htc"); }
    img { behavior: url("template/inc_css/specific/pngbehavior.htc"); }
  </style>
  <![endif]-->
</head>
<body id="myid_385">
<div id="container"><a name="top" id="top"></a>


	<div id="head">
		
	<div id="mainnavi">
		<div class="fleft"><a href="deutsche_version.phtml">Startseite</a> | <a href="news_de.phtml">News</a> | <span style="text-decoration:none;font-weight:bold;"><a href="die_docu.phtml">Die Docu</a></span> | <a href="Nuetzliche_Links_und_Tools.phtml">Links &amp; Tools</a> | <a href="downloads.phtml">Downloads</a> | <a href="kontakt.phtml">Kontakt</a> | <a href="faq_de.phtml">FAQ</a> | <a href="http://forum.phpwcms.org/" target="_blank">Forum</a> | <a href="howto_de.phtml">HowTo</a></div>				
		<div class="sys">Samstag, 20. Juni 2009<img src="img/leer.gif" border="0" width="5" height="1" alt="" />|<img src="img/leer.gif" border="0" width="5" height="1" alt="" />4 User online<img src="img/leer.gif" border="0" width="10" height="1" alt="" />
		<a href="deutsche_version.phtml" title="Deutsche Version"><img src="picture/../template/lang/all/flag_de.gif" border="0" alt="" /></a>
		<a href="english_version.phtml"  title="English version"><img src="picture/../template/lang/all/flag_en.gif" border="0" alt="" /></a>
		</div>
	</div>
	
	<a href="./" title="phpwcms-docu Startseite aufrufen" class="homelink">
	<span>&raquo; Zur phpwcms-docu Startseite</span></a>
	<h2>phpwcms-docu - Die Dokumentation f&uuml;r f&uuml;r das CMS phpWCMS</h2>
	<p>phpwcms-docu ist eine Art Kompass, der Ihnen die M&ouml;glichkeiten von phpWcms aufzeigt und Sie erfolgreich, ohne gro&szlig;e Umwege, zu Ihrer fertigen Web-Anwendung f&uuml;hren soll.
	</p>
	</div>

	
	<div id="left">
	<div class="leftnav" style="margin-top:24px;">
	
<div id="ul_div_309">
<ul>
	<li class="sub_no"><a href="download-dev-versionen.phtml">Download Dev Versionen</a></li>
	<li class="sub_no sub_ul_true"><a href="installation_und_upgrade_von_phpwcms.phtml">Installation &amp; Upgrade</a></li>
	<li class="sub_ul"><a href="verwaltung_artikel.phtml">Artikel</a>
	<div id="ul_div_82">
	<ul>
		<li class="sub_no"><a href="artikel_erstellen.phtml">Artikel erstellen</a></li>
		<li class="sub_no"><a href="artikel_editieren.phtml">Artikel bearbeiten</a></li>
		<li class="sub_no sub_ul_true"><a href="artikel_organisation.phtml">Artikel Organisation</a></li>
		<li class="sub_ul"><a href="content_parts_de.phtml">Content Parts</a>
		<div id="ul_div_100">
		<ul>
			<li class="sub_no"><a href="einfacher_text.phtml">Einfacher Text</a></li>
			<li class="sub_no"><a href="content_part_html_de.phtml">HTML</a></li>
			<li class="sub_no"><a href="content_part_wysiwyg_html_de.phtml">WYSIWYG HTML</a></li>
			<li class="sub_no"><a href="content_part_code_de.phtml">Code</a></li>
			<li class="sub_no"><a href="content_part_text_mit_bild.phtml">Text mit Bild</a></li>
			<li class="sub_no"><a href="content_part_bilder_div.phtml"><span style="text-decoration:line-through;font-size:10px;">Bilder &lt;DIV&gt;</span></a></li>
			<li class="sub_no"><a href="content_part_bilder.phtml">Bilder</a></li>
			<li class="sub_no"><a href="content_part_aufzaehlung.phtml">Aufzählung</a></li>
			<li class="sub_no"><a href="content_part_liste.phtml">Liste</a></li>
			<li class="sub_no"><a href="content_part_link_und_e-mail.phtml">Link &amp; E-Mail</a></li>
			<li class="sub_no"><a href="content_part_linkliste.phtml">Linkliste</a></li>
			<li class="sub_no"><a href="content_part_artikellink.phtml">Artikellink</a></li>
			<li class="sub_no"><a href="content_part_teaser_artikellink.phtml"><span style="text-decoration:line-through;font-size:10px;">Teaser / Artikellink</span></a></li>
			<li class="sub_no"><a href="content_part_artikelmenue.phtml">Artikelmenü</a></li>
			<li class="sub_no"><a href="content_part_multimedia_de.phtml">Multimedia</a></li>
			<li class="sub_no"><a href="content_part_dateiliste.phtml">Dateiliste</a></li>
			<li class="sub_no sub_ul_true"><a href="content_part_ecard_de.phtml">E-Card</a></li>
			<li class="sub_no"><a href="content_part_formular.phtml">Formular</a></li>
			<li class="sub_no sub_ul_true"><a href="content_part_e-mail_formulargenerator.phtml">E-Mail Form. [OLD]</a></li>
			<li class="sub_no"><a href="content_part_e-mail_formular.phtml">E-Mail Formular</a></li>
			<li class="sub_no sub_ul_true"><a href="content_part_newsletter_de.phtml">Newsletter</a></li>
			<li class="sub_no"><a href="content_part_suche.phtml">Suche</a></li>
			<li class="sub_no sub_ul_true"><a href="content_part_gaestebuch_kommentar.phtml">Gästebuch / Komm.</a></li>
			<li class="sub_no"><a href="content_part_sitemap_de.phtml">Sitemap</a></li>
			<li class="sub_no"><a href="content_part_externer_content.phtml">Ext. Content</a></li>
			<li class="sub_no"><a href="content_part_bildwechsel.phtml">Bildwechsel</a></li>
			<li class="sub_no"><a href="content_part_rss_feed_de.phtml">RSS Feed</a></li>
			<li class="sub_no"><a href="content_part_landkarte.phtml">Landkarte</a></li>
			<li class="sub_no"><a href="content_part_php_variablen.phtml">PHP Variablen</a></li>
			<li class="sub_no"><a href="content_part_contentpart_alias_de.phtml">Contentpart Alias</a></li>
			<li class="sub_no"><a href="content_part_poll_de.phtml"><span style="text-decoration:line-through;font-size:10px;">Poll</span></a></li>
			<li class="sub_no active"><a href="content_part_kochrezept.phtml">Kochrezept</a></li>
			<li class="sub_no"><a href="content_part_faq_de.phtml">FAQ</a></li>
			<li class="sub_no"><a href="content_part_frontend_login_de.phtml"><span style="text-decoration:line-through;font-size:10px;">Frontend Login</span></a></li>
			<li class="sub_no"><a href="content_part_glossar.phtml"><span style="text-decoration:line-through;font-size:10px;">Plug-in: Glossar</span></a></li>
		</ul>
		</div>
		</li>
	</ul>
	</div>
	</li>
	<li class="sub_no sub_ul_true"><a href="dateizentrale.phtml">Datei</a></li>
	<li class="sub_no sub_ul_true"><a href="verwaltung_module.phtml">Module</a></li>
	<li class="sub_no sub_ul_true"><a href="Kommunikation.phtml">Kommunikation</a></li>
	<li class="sub_no"><a href="verwaltung_nachricht.phtml">Nachricht</a></li>
	<li class="sub_no"><a href="verwaltung_chat.phtml">Chat</a></li>
	<li class="sub_no"><a href="verwaltung_profil.phtml">Profil</a></li>
	<li class="sub_no sub_ul_true"><a href="verwaltung_admin.phtml">Admin</a></li>
	<li class="sub_no sub_ul_true"><a href="add-on-und-vorlagen.phtml">Add Ons und Vorlagen</a></li>
	<li class="sub_no"><a href="deutsche_version.phtml?replacement_tags_de">Replacement Tags</a></li>
	<li class="sub_no"><a href="deutsche_version.phtml?content_parts_de">Content Parts</a></li>
</ul>
</div>

		
		
		

	</div> 
	</div> 
	  
	<div id="right">
		<div style="margin-top:24px;">			
		<form action="index.php?suche" method="post" name="searchFE" onsubmit="s=document.getElementById('customSearchInput');if(s.value=='Suchen')return false;">
			<table width="100%" border="0" cellpadding="0" cellspacing="0">
			<tr>
					<td><input type="text" name="search_input_field" size="20" maxlength="200" id="customSearchInput" class="customSearchInput" value="" onfocus="if(this.value=='Suchen')this.value='';" onblur="if(this.value=='')this.value='Suchen';" /></td>
					<td><input type="image" name="search_go" onfocus="this.blur();" title="Suchen" src="/template/lang/all/submit.gif" /></td>
				</tr>
			</table>
			</form>
			
			      <script type="text/javascript" language="javascript">
			  <!-- 
			        document.getElementById("customSearchInput").value="Suchen";
			  //-->
			      </script>
				  
			<!-- <p style="margin-top:10px;">Schriftgrad &auml;ndern: <a href="[FontSize-]"><img src="template/lang/all/icons/reduce.gif" width="18" height="17" alt="" title="Verkleinern" border="0" /></a>
			<a href="[FontSize+]"><img src="template/lang/all/icons/extend.gif" width="18" height="17" alt="" title="Vergr&ouml;&szlig;ern" border="0" /></a>
			</p> -->
			
	<p style="margin-top:10px;">Bitte w&auml;hlen Sie: 
	
	 </p>
<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div>


<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div>
<!-- <a href="http://validator.w3.org/check?uri=http%3A%2F%2Fwww.phpwcms-docu.de%2Findex.php%3Fdeutsche_version" title="W3C Standard XHTML" target="_blank"><img src="picture/w3c/w3c_xhtml.gif" border="0" alt="" /></a>
<a href="http://jigsaw.w3.org/css-validator/validator?uri=http://www.phpwcms-docu.de" title="W3C Standard CSS" target="_blank"><img src="picture/w3c/w3c_css.gif" border="0" alt="" /></a><br />			
<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div> -->
<h3>Partnersites</h3>






<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div>

<div style="margin-top:10px; margin-bottom:15px;"></div>


<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div>
</div>

	</div> 
	
	<div id="content">
	<div id="bread">Sie sind hier: <a href="deutsche_version.phtml">Deutsch</a> <span class="breadcrumb_spacer">&gt;</span> <a href="die_docu.phtml">Die Docu</a> <span class="breadcrumb_spacer">&gt;</span> <a href="verwaltung_artikel.phtml">Artikel</a> <span class="breadcrumb_spacer">&gt;</span> <a href="content_parts_de.phtml">Content Parts</a> <span class="breadcrumb_spacer">&gt;</span> Kochrezept</div>
		
		<a name="jump360"></a><!-- Livedate: 29.07.2007 11:08:53 / Killdate: 26.07.2017 23:59:59 -->
<h1>Content Part &quot;Kochrezept&quot;</h1>

<div class="imgDIVinTextLeft" align="left"><div class="image_td2"><a href="content/images/6bbc347871e58cf78d08016a767d6f4b.jpg" rel="lightbox" title="Eingabemaske für das CP Kochrezept" target="_blank"><img src="content/images/8e105f2a94b97c8a3dd4e088c6bacbeb.jpg" width="155" height="200" border="0" class="image_img" alt="cp_kochrezept.jpg" /></a></div><p class="image_caption">Eingabemaske für das CP Kochrezept</p></div><div class="articleText"><p>Das CP Kochrezept wurde f&uuml;r einen deutschen K&auml;sehersteller entwickelt, der  auf der Website Rezepte mit seinen Produkten anbietet.</p>
<p>Die Handhabung dieses CP  ist denkbar einfach. Die Ausgabe kann bequem anhand von Templates ver&auml;ndert  werden. Das Template finden Sie auf Ihrem Server/Domain im Verzeichnis  <i>/template/inc_cntpart/recipe</i>.</p>
<p>&nbsp;</p>
<p><strong>Inhaltstitel:</strong><br />
z.B. Rezept&uuml;berschrift</p>
<p>&nbsp;</p>
<p><strong>Untertitel: </strong><br />
z.B. Optionaler Text</p>
<p>&nbsp;</p>
<p><strong>Keywords:</strong><br />
Sie k&ouml;nnen Rezepte mit Schlagw&ouml;rtern versehen.  Einmal eingetragene Keywords werden in das dar&uuml;berliegende Auswahlmen&uuml;  (Selectfeld) &uuml;bernommen und stehen f&uuml;r sp&auml;tere Eingaben zur Verf&uuml;gung.</p>
<p>Die Vergabe von Keywords ergibt nur dann Sinn, wenn Sie auch eine speziell  daf&uuml;r vorgesehene Suchmaske verwenden. <strike>Die Suchfunktion (search.html im  Verzeichnis <i>template/inc_cntpart/recipe</i>) muss dabei in Ihr bestehendes  Seitenlayout via Externer Content eingebunden werden.</strike>&nbsp; Die Suchfunktion wird durch den RT <b>{RECIPE:} </b>aus einem HTML CP aufgerufen. Dazu ist es notwendig, vorher die Datei <i>recipes.php</i> aus <i>template/inc_script/frontend_render/disabled/*</i> nach <i>template/inc_script/frontend_render/*</i> zu kopieren. Funktionierende Version: <a target="_blank" href="http://forum.phpwcms.org/viewtopic.php?p=112655#p112655">Forum: Kochrezept</a></p>
<p><i><i><strong>Ein kleines  Bespiel:</strong><br />
Sie haben 100 Rezepte:</i></i></p>
<ul><i> <i>    </i>     </i>
    <li><i><i>50 Pastagerichte</i></i></li>
    <i>    <i>    </i>     </i>
    <li><i><i>20 Fleischgerichte</i></i></li>
    <i>    <i>    </i>     </i>
    <li><i><i>10 Suppen</i></i></li>
    <i>    <i>    </i>     </i>
    <li><i><i>10 Aufl&auml;ufe</i></i></li>
    <i>    <i>    </i>     </i>
    <li><i><i>10 Fischgerichte</i></i></li>
</ul>
<p><i><i><br />
Folglich w&uuml;rde es sich anbieten 5 Keywords zu  vergeben und den jeweiligen Rezepten zuzuordnen und so eine Sortierung zu  erm&ouml;glichen:</i></i></p>
<ul><i> <i>    </i>     </i>
    <li><i><i>Auflauf</i></i></li>
    <i>    <i>    </i>     </i>
    <li><i><i>Fleisch</i></i></li>
    <i>    <i>    </i>     </i>
    <li><i><i>Fisch</i></i></li>
    <i>    <i>    </i>     </i>
    <li><i><i>Pasta</i></i></li>
    <i>    <i>    </i>     </i>
    <li><i><i>Suppen</i></i></li>
</ul>
<p><i><i>Diese Keywords sollten demnach auch im Selectfeld innerhalb  der search.html &uuml;bernommen werden:</i></i></p>
<p><code><i><i>&lt;select name=&quot;recipecat&quot;&gt;<br />
&lt;option value=&quot;&quot; selected=&quot;selected&quot;&gt; Bitte ausw&auml;hlen &lt;/option&gt;<br />
&lt;option value=&quot;Auflauf&quot;&gt;Aufl&auml;ufe&lt;/option&gt;<br />
&lt;option value=&quot;Fisch&quot;&gt;Fisch&lt;/option&gt;<br />
&lt;option value=&quot;Fleisch&quot;&gt;Fleischgerichte&lt;/option&gt;<br />
&lt;option value=&quot;Pasta&quot;&gt;Pasta&lt;/option&gt;<br />
&lt;option value=&quot;Suppe&quot;&gt;Suppen&lt;/option&gt;<br />
&lt;/select&gt;</i></i></code></p>
<p><i><i>Schon k&ouml;nnen Sie Rezepte  nach Ihren Kriterien ausw&auml;hlen</i></i></p>
<p><i><i><br />
<strong class="error">Hinweis:<br />
Um die Suche nutzbar zu machen muss sich die Datei recipes.php im Verzeichnis <i>template/inc_script/frontend_render</i> befinden. Sie finden diese Datei im disabled Ordner innerhalb des oben genannten Ordners.</strong></i></i></p></div><div align="right"><a href="#top"><img src="img/article/top_link_0.gif" border="0" alt="" /></a></div><div style="border-bottom:1px dotted #d2e2f5; margin-top:10px; margin-bottom:15px;"></div><div class="articleText"><p><strong>Vorlage:</strong></p>
<p>Hier k&ouml;nnen Sie aus dem Verzeichnis <i>template/inc_cntpart/recipe </i>ein Template ausw&auml;hlen. Es empfiehlt sich, das Template als erstes in einem HTML Programm Ihrer Wahl zu gestalten und auf den Server upzuloaden. Erst danach sollten Sie mit dem erstellen der Rezepte beginnen.</p>
<p>&nbsp;</p>
<p><strong>Zutaten:</strong><br />
In diesem Feld erfolgt die Eingabe der Zutaten untereinander. Jede Zeile wird von diesem CP als Liste mit &lt;li&gt;&lt;/li&gt; interpretiert oder f&uuml;r die Ausgabe als Tabelle mit &lt;tr&gt;&lt;td&gt;&lt;/td&gt;&lt;/tr&gt;umschlossen. Diese Vorgabe k&ouml;nnen Sie im Template vornehmen, indem Sie entweder [INGREDIENTS]{INGREDIENTS} [/INGREDIENTS] f&uuml;r &lt;li&gt;&lt;/li&gt;oder [INGREDIENTSTABLE] {INGREDIENTSTABLE} [/INGREDIENTSTABLE] f&uuml;r &lt;tr&gt;&lt;td&gt;&lt;/td&gt;&lt;/tr&gt; vewenden. Nutzen Sie in einer Zeile ein*, wird diese Zeile als Headline H5 interpretiert.</p>
<p>&nbsp;</p>
<p><strong>z.B Eingabe im Feld Zutaten:<br />
</strong><br />
* Zutaten f&uuml;r 4  Personen<br />
4 Lammfilets &agrave; ca. 180 g <br />
2 EL Keim&ouml;l <br />
100 g Blattspinat <br />
1  TL Rosmarinnadeln <br />
100 g Schafsk&auml;se <br />
50 g Butter <br />
50 g Mascarpone  <br />
50 g Semmelbr&ouml;sel <br />
Salz, Pfeffer <br />
<br />
<br />
*F&uuml;r die Sauce:<br />
100 g  Zwiebeln <br />
1 Knoblauchzehe <br />
100 ml Rotwein <br />
100 ml roter Portwein <br />
1  EL Butter <br />
Salz, Pfeffer<br />
<br />
<br />
<strong>Ergibt als HTML  Code:</strong><br />
<code> &lt;h5&gt;Zutaten f&uuml;r 4 Personen&lt;/h5&gt;<br />
&lt;ul&gt;<br />
&nbsp;&nbsp; &nbsp;&lt;li&gt;4 Lammfilets &agrave; ca. 180 g&lt;/li&gt;<br />
&nbsp;&nbsp; &nbsp;&lt;li&gt;2 EL Keim&ouml;l&lt;/li&gt;<br />
&nbsp;&nbsp; &nbsp;&lt;li&gt;100 g Blattspinat&lt;/li&gt;<br />
&nbsp;&nbsp; &nbsp;&lt;li&gt;1 TL Rosmarinnadeln&lt;/li&gt;<br />
&nbsp;&nbsp; &nbsp;&lt;li&gt;100 g Schafsk&auml;se&lt;/li&gt;<br />
&nbsp;&nbsp; &nbsp;&lt;li&gt;50 g Butter&lt;/li&gt;<br />
&nbsp;&nbsp; &nbsp;&lt;li&gt;50 g Mascarpone&lt;/li&gt;<br />
&nbsp;&nbsp; &nbsp;&lt;li&gt;50 g Semmelbr&ouml;sel&lt;/li&gt;<br />
&nbsp;&nbsp; &nbsp;&lt;li&gt;Salz, Pfeffer&lt;/li&gt;<br />
&lt;/ul&gt;<br />
&lt;h5&gt; F&uuml;r die Sauce:&lt;/h5&gt;<br />
&lt;ul&gt;<br />
&nbsp;&nbsp; &nbsp;&lt;li&gt;100 g Zwiebeln&lt;/li&gt;<br />
&nbsp;&nbsp; &nbsp;&lt;li&gt;1 Knoblauchzehe&lt;/li&gt;<br />
&nbsp;&nbsp; &nbsp;&lt;li&gt;100 ml Rotwein&lt;/li&gt;<br />
&nbsp;&nbsp; &nbsp;&lt;li&gt;100 ml roter Portwein&lt;/li&gt;<br />
&nbsp;&nbsp; &nbsp;&lt;li&gt;1 EL Butter&lt;/li&gt;<br />
&nbsp;&nbsp; &nbsp;&lt;li&gt;Salz, Pfeffer&lt;/li&gt;<br />
&lt;/ul&gt;</code></p></div><div align="right"><a href="#top"><img src="img/article/top_link_0.gif" border="0" alt="" /></a></div><div style="border-bottom:1px dotted #d2e2f5; margin-top:10px; margin-bottom:15px;"></div><div class="articleText"><p><strong>Zuber. Zeit:</strong><br />
Wer es wei&szlig;, kann hier die gesch&auml;tzte  Zubereitungszeit eingeben. Es wird die Eingabe von Zahlen verlangt.</p>
<p>Diese Zuber. Zeit sollte demnach auch im Selectfeld innerhalb der search.html &uuml;bernommen werden. Andernfalls wird eine Sortierung nach Zeit nicht greifen.</p>
<p><strong>Beispiel:</strong><br />
<code> &lt;select name=&quot;recipetime&quot;&gt;<br />
&lt;option value=&quot;&quot; selected=&quot;selected&quot;&gt; Bitte ausw&auml;hlen &lt;/option&gt;<br />
&lt;option value=&quot;1&quot;&gt;bis 20 Min.&lt;/option&gt;<br />
&lt;option value=&quot;2&quot;&gt;20 bis 40 Min.&lt;/option&gt;<br />
&lt;option value=&quot;3&quot;&gt;&uuml;ber 40 Min.&lt;/option&gt;<br />
&lt;/select&gt;</code></p>
<p>&nbsp;</p>
<p><strong>Zusatz: </strong><br />
K&ouml;nnte z.B. sein &quot;+ 10 min. Backzeit&quot;</p></div><div style="border-bottom:1px dotted #d2e2f5; margin-top:10px; margin-bottom:15px;"></div><div class="articleText"><p><strong>N&auml;hrwert:</strong><br />
Wer es wei&szlig;, kann hier die N&auml;hrwerte eingeben.  Es wird die Eingabe von Zahlen verlangt.</p>
<p>Diese N&auml;hrwertangabe sollte demnach auch im Selectfeld innerhalb der search.html &uuml;bernommen werden. Andernfalls wird eine Sortierung nach N&auml;hrwertangaben nicht greifen.</p>
<p><strong>Beispiel:</strong><br />
<code> &lt;select name=&quot;recipecal&quot; class=&quot;size5&quot;&gt;<br />
&nbsp;&nbsp;&nbsp; &lt;option value=&quot;&quot; selected=&quot;selected&quot;&gt; Bitte ausw&auml;hlen &lt;/option&gt;<br />
&nbsp;&nbsp;&nbsp; &lt;option value=&quot;1&quot;&gt;bis 400 kcal&lt;/option&gt;<br />
&nbsp;&nbsp;&nbsp; &lt;option value=&quot;2&quot;&gt;400 bis 600 kcal&lt;/option&gt;<br />
&nbsp;&nbsp;&nbsp; &lt;option value=&quot;3&quot;&gt;&uuml;ber 600 kcal&lt;/option&gt;<br />
&lt;/select&gt; </code></p>
<p><strong>Zusatz:</strong><br />
K&ouml;nnte z.B. sein &quot;Ideal f&uuml;r Diabetiker!&quot;</p>
<p><strong class="error">Tipp:<br />
Die Zus&auml;tze k&ouml;nnen im Template individuell  platziert werden und selbstverst&auml;ndlich auch f&uuml;r andere Zwecke verwendet  werden.</strong></p>
<p><strong class="error">Die Suchkriterien f&uuml;r N&auml;hrwerte und Zubereitungszeit m&uuml;ssen zus&auml;tzlich in der recipes.php angepasst werden.</strong></p></div><div style="margin:20px 0 0 0;padding:0;" class="spaceBeforeCP"></div><div class="articleText"><p><strong>Schwierigkeit: </strong><br />
W&auml;hlen Sie zwischen Stufe 1-5. Im Frontend erscheinen demnach zwischen 1-5 Kochm&uuml;tzen je nach Vorgabe des Schwierigkeitsgrades.</p>
<p>&nbsp;</p>
<p><strong>Zubereitung:</strong><br />
Hier folgt die Beschreibung Ihres  Rezeptes. Guten Appetit!</p></div><div align="right"><a href="#top"><img src="img/article/top_link_0.gif" border="0" alt="" /></a></div><div style="border-bottom:1px dotted #d2e2f5; margin-top:10px; margin-bottom:15px;"></div><div style="margin:40px 0 0 0;padding:0;" class="spaceBeforeCP"></div><h3>Beispiel für Rezept Template</h3><p>An dieser Stelle ein kleines Bespiel f&uuml;r ein Template:</p>

<code>&lt;div&gt;<br />
[INGREDIENTS]Zutaten:&lt;br /&gt;{INGREDIENTS}[/INGREDIENTS]<br />
<br />[PREPARATION]<br />
&lt;div&gt; Zubereitung:&lt;br /&gt;{PREPARATION}&lt;/div&gt;<br />
[/PREPARATION]
<br />
&nbsp; &lt;table style=&quot;margin-top:8px;&quot; border=&quot;0&quot; cellspacing=&quot;0&quot; cellpadding=&quot;0&quot;&gt;<br />
&nbsp;&nbsp;&nbsp; &lt;tr&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lt;td valign=&quot;bottom&quot;&gt;Schwierigkeit:&lt;/td&gt; <br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lt;td valign=&quot;middle&quot;&gt;<img src="picture/{SEVERITY" border="0" alt="" />.gif}&lt;/td&gt;<br />
&nbsp;&nbsp;&nbsp; &lt;tr&gt;<br />
&nbsp;&nbsp;&nbsp; &lt;/table&gt;<br />
<br />
&nbsp;&nbsp;&nbsp; [TIME]<br />
&nbsp;&nbsp;&nbsp; &lt;p&gt;Zubereitungszeit:ca. {TIME} Minuten[TIMEADD]&lt;br /&gt;{TIMEADD}[/TIMEADD]&lt;/p&gt;[/TIME]<br />
[CALORIES]&lt;p&gt;N&auml;hrwerte:{CALORIES}<br />
[CALORIESADD]&lt;br /&gt;{CALORIESADD}[/CALORIESADD]&nbsp;&nbsp;&nbsp; &lt;/p&gt;[/CALORIES]<br />
&lt;/div&gt;</code><br /><div align="right"><a href="#top"><img src="img/article/top_link_0.gif" border="0" alt="" /></a></div>
		 
		
		<br /><br />
		<div class="sub">
		Artikel erstellt am: Sonntag, 29. Juli 2007 <br /> Letzte &Auml;nderung: Freitag, 16. Januar 2009	
		</div>
				
	</div>
	
<div id="footer"><br /><br />
<p style="height:30px;">&nbsp;</p>


 <script type="text/javascript" language="javascript">
<!--

var showDefaultValue =  0

function hideLayer(whichLayer) {
	if (document.getElementById) {
		// this is the way the standards work
		document.getElementById(whichLayer).style.display = "none";
	} else if (document.all) {
		// this is the way old msie versions work
		document.all[whichlayer].style.display = "none";
	} else if (document.layers) {
		// this is the way nn4 works
		document.layers[whichLayer].display = "none";
	}
}

function showLayer(whichLayer) {
		//	alert(whichLayer);
	if (document.getElementById) {
		// this is the way the standards work
		document.getElementById(whichLayer).style.display = "block";
	}
	else if (document.all) {
		// this is the way old msie versions work
		document.all[whichlayer].style.display = "block";
	}
	else if (document.layers) {
		// this is the way nn4 works
		document.layers[whichLayer].display = "block";
	}
}

function toggleLayer(whichLayer) {
	if(showDefaultValue == 0) {
		hideLayer(whichLayer);
		showDefaultValue = 1;
	} else {
		showLayer(whichLayer);
		showDefaultValue = 0;
	}
}
//-->
</script>


<div id="alles">
<div id="klapper" onclick="toggleLayer('formular');">
<table width="570" border="0" cellspacing="0" cellpadding="0">
<tr>
<td><em style="color:#275EA8;" onmouseover="this.style.color='#4F96F4';" onmouseout="this.style.color='#275EA8';">Sie haben Anregungen oder Kritik zu diesem Artikel? Schreiben Sie uns!</em></td>   
<td align="right" style="padding-right:2px;"><img src="template/lang/all/icons/write.gif" width="16" height="21" alt="" border="0" /></td>
</tr>
</table>

</div>
<div id="formular">

<form name="form" method="post" action="index.php?id=385,360,0,0,1,0" style="margin:0;padding:0;"><input type="hidden" name="customForm" value="1" /><input type="hidden" name="docucheck" value="1" />


<div style="float:left;">
<p><select name="Betreff" id="Betreff" class="size1">
<option value="" class="deepblue"> Bitte ausw&auml;hlen </option>
<option value="subject_1" class="inselect">Anregungen</option>
<option value="subject_2" class="inselect">Fehlermeldung/ Kritik</option>
<option value="subject_3" class="inselect">Sonstiges</option>

</select><br /></p>


<p>Vorname:<br />
<input type="text" name="Vorname" value="" class="size1" /></p>
<p>Name:*<br />
<input type="text" name="Name" value="" class="size1" /></p>
<p>E-Mail:*<br />
<input type="text" name="E-Mail" value="" class="size1" /></p>
</div>


<div style="float:right;">Mitteilung:*<br />
<textarea name="Nachricht" cols="40" rows="4"  class="size7"></textarea>
</div>

<p style="clear:both; text-align:right;"><input type="reset" name="reset" value="Zur&uuml;cksetzen" class="btstyle" style="width:100px;" />&nbsp;&nbsp;
<input type="submit" name="submit" value="Anfrage senden" class="btstyle" style="width:110px;" /></p>
<p style="margin:20px;" class="sub">* Pflichtangaben. Ihre Daten werden ausschlie&szlig;lich für diese Anfrage verwendet.</p>

</form>
</div>
</div>
 <script type="text/javascript" language="javascript">
<!--
	// Lösung ohne Onload
	toggleLayer('formular');
//-->
</script>
<br />





	<table width="97%" border="0" cellspacing="0" cellpadding="0">
		<tr>
			<td valign="bottom">	
			&copy; phpwcms-docu 2004-2009
			<img src="img/leer.gif" border="0" width="10" height="0" alt="" /><a href="impressum.phtml" class="phpwcmsIntLink"><img src="template/lang/all/icons/imprint.gif" width="9" height="15" alt="Impressum" title="Impressum" border="0" /></a>&nbsp; 
			<a href="sitemap_de.phtml" class="phpwcmsIntLink"><img src="template/lang/all/icons/sitemap.gif" width="19" height="15" alt="Sitemap" title="Sitemap" border="0" /></a>&nbsp; 
			<a href="gaestebuch.phtml" class="phpwcmsIntLink"><img src="template/lang/all/icons/gbook.gif" width="20" height="16" alt="Ins G&auml;stebuch eintragen" title="Ins G&auml;stebuch eintragen" border="0" /></a>&nbsp; 
			<a href="#" onclick="BookMark_Page();return false;" title="" class="phpwcmsBookmarkLink"><img src="template/lang/all/icons/favo.gif" width="12" height="15" alt="Seite als Bookmark speichern" title="Seite als Bookmark speichern" border="0" /></a>&nbsp; 
			     
			</td>
			<td valign="bottom" style="padding-right:25px;">
			
			
			
			</td>		
			<td width="150">
			</td>
		</tr>
	</table>
</div><br/>

</div>
</body>
</html>