<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<!--
	phpwcms | free open source content management system
	created by Oliver Georgi (oliver at phpwcms dot de) and licensed under GNU/GPL.
	phpwcms is copyright 2003-2007 of Oliver Georgi. Extensions are copyright of
	their respective owners. Visit project page for details: http://www.phpwcms.org/
//-->
<title>phpwcms-docu for  phpwcms :: web based content management system | Upgrade{D:07/31/2007,30,newR.gif} | Upgrade an existing phpWCMS installation</title>
  <meta http-equiv="content-type" content="text/html; charset=iso-8859-1" />
  <meta http-equiv="content-style-type" content="text/css" />
  <script src="template/inc_js/frontend.js" type="text/javascript"></script>
  <style type="text/css">
  <!-- 
    @import url("template/inc_css/mpl_frontend.css");
    @import url("template/inc_css/mpl_menu.css");
    @import url("template/inc_css/mpl_objects.css");
    @import url("template/inc_css/mpl_docu_en.css");
  //-->
  </style>
<meta name="Title" content="The phpWCMS Documentation" />
<meta name="author" content="Oliver Frohnert, Mario Perez Leal" />
<meta name="Publisher" content="Oliver Frohnert, Mario Perez Leal, creacion" />
<meta name="Copyright" content="Oliver Frohnert, Mario Perez Leal, creacion" />
<meta name="keywords" content="frohnert, perez leal, creacion, documentation, dokumentation, phpwcms, cms, opensource, open source, docu" />
<meta name="description" content="A Documentation Project for the  Open Source CMS phpWCMS" />
<meta name="Audience" content="Alle" />
<meta name="Content-language" content="EN" />
<meta name="robots"      content="index,follow" />
<meta name="expires" content="0" />
<meta name="revisit-after" content="7 days" />
<meta name="resource-type" content="document" />
<meta name="distribution" content="Global" />
<meta name="generator" content="PHPWCMS" />
<meta name="verify-v1" content="1ZpxZ7AZsjm7PxjqXQVus0eiUYqOsp5URTJn9q4KNz8=" />
  <!--[if lt IE 7]>
  <style type="text/css">
    body { behavior: url("template/inc_css/specific/csshover2.htc"); }
    img { behavior: url("template/inc_css/specific/pngbehavior.htc"); }
  </style>
  <![endif]-->
</head>
<body id="myid_391">
<div id="container"><a name="top" id="top"></a>


	<div id="head">
		
	<div id="mainnavi">
		<div class="fleft"><a href="english_version.phtml">Home</a> | <a href="news_en.phtml">News</a> | <span style="text-decoration:none;font-weight:bold;"><a href="the_docu.phtml">The Docu</a></span> | <a href="Usefull_Links_and_Tools.phtml">Links &amp; Tools</a> | <a href="contact.phtml">Contact</a> | <a href="faq_en.phtml">FAQ</a> | <a href="http://forum.phpwcms.org/" target="_blank">Forum</a> | <a href="howto_en.phtml">HowTo</a></div>				
		<div class="sys">Tuesday, 13. October 2015<img src="img/leer.gif" border="0" width="5" height="1" alt="" />|<img src="img/leer.gif" border="0" width="5" height="1" alt="" />2 User online<img src="img/leer.gif" border="0" width="10" height="1" alt="" />
		<a href="deutsche_version.phtml" title="Deutsche Version"><img src="picture/../template/lang/all/flag_de.gif" border="0" alt="" /></a>
		<a href="english_version.phtml"  title="English version"><img src="picture/../template/lang/all/flag_en.gif" border="0" alt="" /></a>
		</div>
	</div>
	
	<a href="./" title="phpwcms-docu Startseite aufrufen" class="homelink">
	<span>&raquo; phpwcms-docu startpage</span></a>
	<h2>phpwcms-docu - Documentation for the Web Content Management System phpwcms</h2>
	<p>This website is targeted both to the beginner and the lateral entry following the goal to simplify the 
work with phpwcms and to focus on the essentials things.</p>
	</div>

	
	<div id="left">
	<div class="leftnav" style="margin-top:24px;">
	
<div id="ul_div_311">
<ul>
	<li class="sub_no"><a href="download-dev-versions.phtml">Download Dev Versions</a></li>
	<li class="sub_ul"><a href="installation_en.phtml">Installation &amp; Upgrade</a>
	<div id="ul_div_207">
	<ul>
		<li class="sub_ul active"><a href="upgrade_phpwcms_english.phtml">Upgrade</a>
		<div id="ul_div_391">
		<ul>
			<li class="sub_no"><a href="upgrade_RC11_till_129_to_13x.phtml">RC 1.1 till 1.2.9 to 1.3.x</a></li>
		</ul>
		</div>
		</li>
		<li class="sub_no"><a href="dbbackup_en.phtml">Database backup</a></li>
		<li class="sub_no"><a href="dbrestore_en.phtml">Restoring the database</a></li>
		<li class="sub_no sub_ul_true"><a href="config_files.phtml">Config Files</a></li>
	</ul>
	</div>
	</li>
	<li class="sub_no sub_ul_true"><a href="article.phtml">Articles</a></li>
	<li class="sub_no sub_ul_true"><a href="file.phtml">File</a></li>
	<li class="sub_no sub_ul_true"><a href="module_en.phtml">Modules</a></li>
	<li class="sub_no sub_ul_true"><a href="communication.phtml">Communication </a></li>
	<li class="sub_no"><a href="chat_en.phtml">Chat</a></li>
	<li class="sub_no"><a href="profile.phtml">Profile</a></li>
	<li class="sub_no sub_ul_true"><a href="admin_en_.phtml">Admin</a></li>
	<li class="sub_no sub_ul_true"><a href="add-ons-and-templates.phtml">Add On&#039;s and Templates</a></li>
	<li class="sub_no"><a href="deutsche_version.phtml?replacement_tags_en">Replacement Tags</a></li>
	<li class="sub_no"><a href="deutsche_version.phtml?content_parts_en">Content Parts</a></li>
</ul>
</div>

		
	</div> 
	</div> 
	  
	<div id="right">
		<div style="margin-top:24px;">			
		<form action="index.php?search" method="post" name="searchFE" onsubmit="s=document.getElementById('customSearchInput');if(s.value=='Search')return false;">
			<table width="100%" border="0" cellpadding="0" cellspacing="0">
			<tr>
					<td><input type="text" name="search_input_field" size="20" maxlength="200" id="customSearchInput" class="customSearchInput" value="" onfocus="if(this.value=='Search')this.value='';" onblur="if(this.value=='')this.value='Search';"/></td>
					<td><input type="image" name="search_go" onfocus="this.blur();" title="Search" src="/template/lang/all/submit.gif" /></td>
				</tr>
			</table>
			</form>
			
			      <script type="text/javascript" language="javascript">
			  <!-- 
			        document.getElementById("customSearchInput").value="Search";
			  //-->
			      </script>
				  
<!-- <p style="margin-top:10px;">Change font size: <a href="[FontSize-]"><img src="template/lang/all/icons/reduce.gif" width="18" height="17" alt="" title="Small" border="0" /></a>
			<a href="[FontSize+]"><img src="template/lang/all/icons/extend.gif" width="18" height="17" alt="" title="Bigger" border="0" /></a>
			</p> -->
			
	<p style="margin-top:10px;">Please choose: 
	
	 </p>


<!-- <a href="http://validator.w3.org/check?uri=http%3A%2F%2Fwww.phpwcms-docu.de%2Findex.php%3Fdeutsche_version" title="W3C Standard XHTML" target="_blank"><img src="picture/w3c/w3c_xhtml.gif" border="0" alt="" /></a>
<a href="http://jigsaw.w3.org/css-validator/validator?uri=http://www.phpwcms-docu.de" title="W3C Standard CSS" target="_blank"><img src="picture/w3c/w3c_css.gif" border="0" alt="" /></a><br />			
<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div> -->
		
<div style="margin-top:10px; margin-bottom:15px;"></div>
	
</div>

	</div> 
	
	<div id="content">
	<div id="bread">You are here: <a href="english_version.phtml">English</a> <span class="breadcrumb_spacer">&gt;</span> <a href="the_docu.phtml">The Docu</a> <span class="breadcrumb_spacer">&gt;</span> <a href="installation_en.phtml">Installation &amp; Upgrade</a> <span class="breadcrumb_spacer">&gt;</span> Upgrade</div>
		
		<a name="jump353"></a><!-- Livedate: 26.07.2007 09:36:28 / Killdate: 23.07.2017 23:59:59 -->
<h1>Upgrade an existing phpWCMS installation</h1>

<p>Because there were so many changes changes with phpwcms, here are now the upgrade / update descriptions.<br />
<br />
The effort differs. The older the installed version is, the more effort is necessary for the upgrade to the actual version. But if you stay with the order of the upgrade description, you shouldn't have big problems.<br />
<br />
In &quot;<a href="./upgrade_RC11_bis_129_nach_13x.phtml" target="_self">Update from RC 1.1 till 1.2.9 to 1.3.x</a>&quot; a universal upgrade description has been written that should make it possible to succeed with an upgrade to the actual phpwcms version 1.3.3.<br />
<br />
An upgrade description f&uuml;r the versions beginning from 1.2.9 will follow shortly.<br />
</p>
<hr />Download: - Latest Version (<a href="download-dev-versions.phtml" class="postlink">./download-dev-versions.phtml</a>)<br />
Docu: - Installation &amp; Update (not yet, german only)<br />
List of changes: - <span style="font-weight: bold">Ongoing improvements / changes</span> (Dec. 18.-2011)<br />
<br />
For  non-experienced users, we recommend a parallel installation. (Also  you  will have the advantage that you are completely at rest as a new design  build or merge changes / improvements can not come under stress, <span style="font-weight: bold">as the old site will remain untouched</span>).<br />
<br />
<span style="color: #FF0000">01. The current version of push in a subdirectory. (FTP download and reupload into the new folder)<br />
</span> <strong><a name="a_find_my_current_version" id="a_find_my_current_version">01.a Find my current version</a></strong>
<p>In old versions you have an entry in include/inc_lib/default.inc.php at the end of the file called:</p>
<pre class="file">
$phpwcms[&quot;version&quot;] = Version No.</pre>
<p>In newer versions there is an entry in include/inc_lib/default.inc.php around line 135 called:</p>
<pre class="file">
$phpwcms[&quot;release&quot;] = Release No.
$phpwcms[&quot;release_date&quot;] = Release date
</pre>
<p>In brand new versions there is an entry in include/inc_lib/default.inc.php around line 245 called:</p>
<pre class="file">
$phpwcms[&quot;release&quot;] = Release No.
$phpwcms[&quot;release_date&quot;] = Release date
$phpwcms[&quot;revision&quot;] = Revision
</pre>
<br />
<span style="color: #FF0000">02. The existing DB backup DB and bringing in a second DB - the working DB, then copy.</span> (PhpMyAdmin - <a href="http://de.wikipedia.org/wiki/PhpMyAdmin" class="postlink">http://de.wikipedia.org/wiki/PhpMyAdmin</a>&gt;).<br />
- Before you export the contents of <span style="font-weight: bold">the following tables perhaps might be  be emptied to reduce the DB size</span>:<br />
First phpwcms_bad_behavior empty<br />
Second: phpwcms_cache empty<br />
third : phpwcms_formtracking empty if available<br />
(Left  the table phpwcms_bad_behavior select -&gt; select top view -&gt;  select all down -.&gt; Delete selected (run several times, depending on  the number of display pages (the same for phpwcms_cache,  phpwcms_formtracking).<br />
<br />
fourth: Check tables for errors and optimize if necessary / repair.<br />
<br />
- The newer phpMyAdmin basically export in UTF-8 format.<br />
- The new DB is created with the appropriate collation phpMyAdmin for the MySQL connection.<br />
(For earlier DB is swedish_latin1_ci to 99%)<br />
- In the new DB is now exported with the default character encoding UTF-8 import.<br />
If  you're using an ISO charset, it may be necessary to convert before  importing the SQL file to ISO. It goes quite well with the below  mentioned editor.<br />
-&gt; Load SQL text file into the editor, under  &quot;Format&quot; ISO8859-2 to select and save with a new name. The ISO file is  now encoded before.<br />
(But please first try a simple export / import with identical settings (character encoding) !!!).<br />
<br />
<span style="color: #FF0000">03. The existing conf.inc.php in the new installation copy and compare them with the existing dist.conf.inc.php there.<br />
</span>This  course is also registered with the new DB collation and the charset and  the subdirectory in which the new system is running.<br />
-&gt; It would  be better if you could set up specifically to a subdomain instead of the  installation with a subdirectory name to speak.<br />
<br />
<span style="color: #FF0000">04th File and directory permissions set as stated in the Docu. <a href="download-dev-versions.phtml" class="postlink">./download-dev-versions.phtml</a> (Adjusting the file and folder rights)<br />
</span><br />
<span style="color: #FF0000">05th Call setup -&gt; Update</span><br />
- Note Depending on the version level, the first points and run.<br />
- DB updates can be run sequentially and check for error: (Always the entire output field to scroll down!)<br />
&gt;  (This of course is the entry point to be noted that as the version  1.2.8 is the update begins with &quot;15__1.2.7-DEV_to_1.2.9.sql&quot;!)<br />
-------------------------------------------------- ---<br />
- 13__1.2.5-DEV_to_1.2.6-DEV.sql (from v1.2.5)<br />
- 14__1.2.6-DEV_to_1.2.7-DEV.sql<br />
- 15__1.2.7-DEV_to_1.2.9.sql<br />
- 16__1.2.9-DEV_to_1.3.0.sql<br />
- 17__1.3.0_to_1.3.2.sql<br />
- 18__1.3.2_to_1.3.3.sql<br />
<br />
- 19__1.3.3_to_1.3.4.sql (from V1.3.3)<br />
- 19__1.3.4_to_1.3.5.sql<br />
- 20__1.3.5_to_1.3.5.1.sql<br />
- 21__1.3.5_to_1.5.sql<br />
- 22__1.4_to_1.5.sql (from V1.4.x)<br />
-------------------------------------------------- ---<br />
-&gt; The last update, it will likely lead to errors:<br />
- Error: The table does not exist phpwcms_categories - ignoring&gt; as a shop update, but the shop still exists when you do not<br />
- Error: The table already exists phpwcms_log - ignoring&gt; as this table is not used in the new form<br />
<br />
<span style="color: #BF0000">05.1 Duplicate indexes in several DB tables</span><br />
<br />
- It may happen that there are duplicate indexes in the tables.<br />
<br />
- PhpMyAdmin&gt; call<br />
-&gt; Select DB<br />
-&gt; Select Table<br />
- Delete roles&gt; down to the indexes (all indexes, where you can have a &quot;_1 _2 _3 etc.&quot; at the end.<br />
(PhpMyAdmin should you when you call the table also indicate that duplicate indexes are available)<br />
! Look through All tables!<br />
<br />
<span style="color: #FF0000">06th If the shop is not needed then please delete the entire path / include / inc_module / mod_shop /</span><br />
<br />
<span style="color: #FF0000">07th  The contents of the folder / file archive (phpwcms_filestorage) / the  old version in the folder / file archive / copy the new version (with  the same data in / picture / * if used)</span><br />
- Changed directory name<br />
OLD. . . . . . . . . . . . . . . . . NEW. . . . .<br />
phpwcms_filestorage -&gt;. . . . filearchive<br />
phpwcms_ftp -&gt;. . . . . . . . . upload<br />
phpwcms_template -&gt;. . . . . template<br />
<br />
<span style="color: #FF0000">08th The existing file / config / phpwcms / conf.template_default.inc.php the old version with the new Syndicate<br />
</span><br />
<span style="color: #FF0000">09th If you've called home differently, then please also synchronize the file / config / phpwcms / conf.indexpage.inc.php</span><br />
<br />
10th  The existing modified CSS file under / template / inc_css / from the  old version compare with the corresponding new css files<br />
<br />
<span style="color: #BF0000">11th Changing the existing template files</span> / template inc_cntpart / / * from the old version compare with the corresponding new files<br />
(When I say match, I always think that the new files will be supplemented with entries from the old one)<br />
<br />
<span style="color: #FF0000">12th Browser cache -</span>&gt;  call back log, can not access the site!! (Because if you Google or  tracker stuff've installed this should be disabled before calling first  page in this development, installation (If later re-activated upon  completion of the page)).<br />
<br />
<span style="color: #FF0000">13th Disable in the existing template the tracking code!!</span><br />
<br />
<span style="color: #FF0000">14th If the backend will work, then please delete the / setup / * or rename a meaningless string.</span><br />
<br />
<span style="color: #FF0000">15th The system should now be running</span>.  The rebuilding of the images can lead to a quasi-standstill of the  system, not frighten. (Multiple call one after the file center, if the  message comes as a timeout).<br />
(You can also copy the contents of the  folder / content / images / * from the old system, but is usually not  necessary as the system builds an index of thumbs / smaller pictures /  new files).<br />
<br />
---------------<br />
There are of course still some adjustments to accomplish such the &lt;META ...&gt; XHTM tags fixed to make:<br />
&lt;Meta .... /&gt; If so, however, odds and ends and has to do with the update basically nothing.<br />
<br />
The  procedure for this scheme has the advantage that the old page remains  untouched, and you with the new system, eg the layout and other changes  can develop in peace.<br />
After completion of the work, the old system  will be deleted and the new version is pushed to this site or the domain  bent on it.<br />
<br />
Important: The updated stress is largely caused by a careless handling of the CSS and template files.<br />
Principle 1: Always own name for use in CSS and template files that are in use, they are not affected by an upgrade.<br />
Principle 2: If possible, for the base system, the layout and navigation separate CSS files.<br />
e.g. frontend01.css, layout01.css, navi01.css<br />
<br />
----------------<br />
For **** or for the editing of all files can eg The editor PSPad and its FTP mode. Be used (direct access from the editor).<br />
This editor is combined with total commander (free for non-commercial sites) really useful.<br />
As an alternative to total commander can also e.g. <a href="http://www.filezilla.de/" class="postlink">http://www.filezilla.de/</a> be used. (If the FTP area clearly superior).<br />
-----<br />
Suggestion: A DIFF. Create with total commander
		 
		
		<br /><br />
		<div class="sub">
		Article created: Sunday, 29. July 2007 <br /> Last Changes: Monday, 19. December 2011	
		</div>
				
	</div>
	
<div id="footer"><br /><br />
<p style="height:30px;">&nbsp;</p>


 <script type="text/javascript" language="javascript">
<!--

var showDefaultValue =  0

function hideLayer(whichLayer) {
	if (document.getElementById) {
		// this is the way the standards work
		document.getElementById(whichLayer).style.display = "none";
	} else if (document.all) {
		// this is the way old msie versions work
		document.all[whichlayer].style.display = "none";
	} else if (document.layers) {
		// this is the way nn4 works
		document.layers[whichLayer].display = "none";
	}
}

function showLayer(whichLayer) {
		//	alert(whichLayer);
	if (document.getElementById) {
		// this is the way the standards work
		document.getElementById(whichLayer).style.display = "block";
	}
	else if (document.all) {
		// this is the way old msie versions work
		document.all[whichlayer].style.display = "block";
	}
	else if (document.layers) {
		// this is the way nn4 works
		document.layers[whichLayer].display = "block";
	}
}

function toggleLayer(whichLayer) {
	if(showDefaultValue == 0) {
		hideLayer(whichLayer);
		showDefaultValue = 1;
	} else {
		showLayer(whichLayer);
		showDefaultValue = 0;
	}
}
//-->
</script>


<div id="alles">
<div id="klapper" onclick="toggleLayer('formular');">
<table width="570" border="0" cellspacing="0" cellpadding="0">
<tr>
<td><em style="color:#275EA8;" onmouseover="this.style.color='#4F96F4';" onmouseout="this.style.color='#275EA8';">You have suggestions or criticism to this article? Write us!</em></td>   
<td align="right" style="padding-right:2px;"><img src="template/lang/all/icons/write.gif" width="16" height="21" alt="" border="0" /></td>
</tr>
</table>

</div>
<div id="formular">

<form name="form" method="post" action="index.php?id=391,353,0,0,1,0" style="margin:0;padding:0;"><input type="hidden" name="customForm" value="1" /><input type="hidden" name="docucheck" value="1" />


<div style="float:left;">
<p><select name="Betreff" id="Betreff" class="size1">
<option value="" class="deepblue"> Select </option>

</select><br /></p>


<p>Firstname:<br />
<input type="text" name="Vorname" value="" class="size1" /></p>
<p>Surname:*<br />
<input type="text" name="Name" value="" class="size1" /></p>
<p>E-Mail:*<br />
<input type="text" name="E-Mail" value="" class="size1" /></p>
</div>


<div style="float:right;">Message:*<br />
<textarea name="Nachricht" cols="40" rows="4"  class="size7"></textarea>
</div>

<p style="clear:both; text-align:right;"><input type="reset" name="reset" value="Reset" class="btstyle" style="width:100px;" />&nbsp;&nbsp;
<input type="submit" name="submit" value="Send email" class="btstyle" style="width:110px;" /></p>
<p style="margin:20px;" class="sub">* Required fields.<br />Your data is used exclusively for this inquiry.</p>

</form>
</div>
</div>
 <script type="text/javascript" language="javascript">
<!--
	// Lösung ohne Onload
	toggleLayer('formular');
//-->
</script>
<br />





	<table width="97%" border="0" cellspacing="0" cellpadding="0">
		<tr>
			<td valign="bottom">	
			&copy; phpwcms-docu 2004-2015
			<img src="img/leer.gif" border="0" width="10" height="0" alt="" /><a href="imprint.phtml" class="phpwcmsIntLink"><img src="template/lang/all/icons/imprint.gif" width="9" height="15" alt="Impressum" title="Impressum" border="0" /></a>&nbsp; 
			<a href="sitemap_en.phtml" class="phpwcmsIntLink"><img src="template/lang/all/icons/sitemap.gif" width="19" height="15" alt="Sitemap" title="Sitemap" border="0" /></a>&nbsp; 
			 
			
			     
			</td>
			<td valign="bottom" style="padding-right:25px;">
			
			
			
			</td>		
			<td width="150">
			</td>
		</tr>
	</table>
</div><br/>

</div>
</body>
</html>