<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<!--
	phpwcms | free open source content management system
	created by Oliver Georgi (oliver at phpwcms dot de) and licensed under GNU/GPL.
	phpwcms is copyright 2003-2007 of Oliver Georgi. Extensions are copyright of
	their respective owners. Visit project page for details: http://www.phpwcms.org/
//-->
<title>phpwcms-docu for  phpwcms :: web based content management system | Guestbook{D:9/20/2007,30,newR.gif} | Guestbook Template</title>
  <meta http-equiv="content-type" content="text/html; charset=iso-8859-1" />
  <meta http-equiv="content-style-type" content="text/css" />
  <script src="template/inc_js/frontend.js" type="text/javascript"></script>
  <style type="text/css">
  <!-- 
    @import url("template/inc_css/mpl_frontend.css");
    @import url("template/inc_css/mpl_menu.css");
    @import url("template/inc_css/mpl_objects.css");
    @import url("template/inc_css/mpl_docu_en.css");
  //-->
  </style>
<meta name="Title" content="The phpWCMS Documentation" />
<meta name="author" content="Oliver Frohnert, Mario Perez Leal" />
<meta name="Publisher" content="Oliver Frohnert, Mario Perez Leal, creacion" />
<meta name="Copyright" content="Oliver Frohnert, Mario Perez Leal, creacion" />
<meta name="keywords" content="frohnert, perez leal, creacion, documentation, dokumentation, phpwcms, cms, opensource, open source, docu" />
<meta name="description" content="A Documentation Project for the  Open Source CMS phpWCMS" />
<meta name="Audience" content="Alle" />
<meta name="Content-language" content="EN" />
<meta name="robots"      content="index,follow" />
<meta name="expires" content="0" />
<meta name="revisit-after" content="7 days" />
<meta name="resource-type" content="document" />
<meta name="distribution" content="Global" />
<meta name="generator" content="PHPWCMS" />

  <link rel="stylesheet" href="template/slimbox/css/slimbox.css" type="text/css" media="screen" />
  <script src="template/inc_js/mootools/mootools.js" type="text/javascript"></script>
  <script src="template/slimbox/js/slimbox.js" type="text/javascript"></script>
  <!--[if lt IE 7]>
  <style type="text/css">
    body { behavior: url("template/inc_css/specific/csshover2.htc"); }
    img { behavior: url("template/inc_css/specific/pngbehavior.htc"); }
  </style>
  <![endif]-->
</head>
<body id="myid_432">
<div id="container"><a name="top" id="top"></a>


	<div id="head">
		
	<div id="mainnavi">
		<div class="fleft"><a href="english_version.phtml">Home</a> | <a href="news_en.phtml">News</a> | <span style="text-decoration:none;font-weight:bold;"><a href="the_docu.phtml">The Docu</a></span> | <a href="Usefull_Links_and_Tools.phtml">Links &amp; Tools</a> | <a href="contact.phtml">Contact</a> | <a href="faq_en.phtml">FAQ</a> | <a href="http://forum.phpwcms.org/" target="_blank">Forum</a> | <a href="howto_en.phtml">HowTo</a></div>				
		<div class="sys">Sunday, 4. July 2010<img src="img/leer.gif" border="0" width="5" height="1" alt="" />|<img src="img/leer.gif" border="0" width="5" height="1" alt="" />4 User online<img src="img/leer.gif" border="0" width="10" height="1" alt="" />
		<a href="deutsche_version.phtml" title="Deutsche Version"><img src="picture/../template/lang/all/flag_de.gif" border="0" alt="" /></a>
		<a href="english_version.phtml"  title="English version"><img src="picture/../template/lang/all/flag_en.gif" border="0" alt="" /></a>
		</div>
	</div>
	
	<a href="./" title="phpwcms-docu Startseite aufrufen" class="homelink">
	<span>&raquo; phpwcms-docu startpage</span></a>
	<h2>phpwcms-docu - Documentation for the Web Content Management System phpwcms</h2>
	<p>This website is targeted both to the beginner and the lateral entry following the goal to simplify the 
work with phpwcms and to focus on the essentials things.</p>
	</div>

	
	<div id="left">
	<div class="leftnav" style="margin-top:24px;">
	
<div id="ul_div_311">
<ul>
	<li class="sub_no"><a href="download-dev-versions.phtml">Download Dev Versions</a></li>
	<li class="sub_no sub_ul_true"><a href="installation_en.phtml">Installation &amp; Upgrade</a></li>
	<li class="sub_no sub_ul_true"><a href="article.phtml">Articles</a></li>
	<li class="sub_no sub_ul_true"><a href="file.phtml">File</a></li>
	<li class="sub_no sub_ul_true"><a href="module_en.phtml">Modules</a></li>
	<li class="sub_no sub_ul_true"><a href="communication.phtml">Communication </a></li>
	<li class="sub_no"><a href="chat_en.phtml">Chat</a></li>
	<li class="sub_no"><a href="profile.phtml">Profile</a></li>
	<li class="sub_no sub_ul_true"><a href="admin_en_.phtml">Admin</a></li>
	<li class="sub_ul"><a href="add-ons-and-templates.phtml">Add On&#039;s and Templates</a>
	<div id="ul_div_314">
	<ul>
		<li class="sub_no"><a href="add_on_replacementtags_en.phtml">Replacement Tags</a></li>
		<li class="sub_ul"><a href="Share-Your-Templates.phtml">Share Your Templates</a>
		<div id="ul_div_427">
		<ul>
			<li class="sub_ul"><a href="templates-for-content-parts.phtml">For Content Parts</a>
			<div id="ul_div_430">
			<ul>
				<li class="sub_no active"><a href="cp_template_guestbook.phtml">Guestbook</a></li>
			</ul>
			</div>
			</li>
		</ul>
		</div>
		</li>
	</ul>
	</div>
	</li>
	<li class="sub_no"><a href="deutsche_version.phtml?replacement_tags_en">Replacement Tags</a></li>
	<li class="sub_no"><a href="deutsche_version.phtml?content_parts_en">Content Parts</a></li>
</ul>
</div>

		
	</div> 
	</div> 
	  
	<div id="right">
		<div style="margin-top:24px;">			
		<form action="#" method="post" name="searchFE" onsubmit="s=document.getElementById('customSearchInput');if(s.value=='Search')return false;">
			<table width="100%" border="0" cellpadding="0" cellspacing="0">
			<tr>
					<td><input type="text" name="search_input_field" size="20" maxlength="200" id="customSearchInput" class="customSearchInput" value="" onfocus="if(this.value=='Search')this.value='';" onblur="if(this.value=='')this.value='Search';"/></td>
					<td><input type="image" name="search_go" onfocus="this.blur();" title="Search" src="/template/lang/all/submit.gif" /></td>
				</tr>
			</table>
			</form>
			
			      <script type="text/javascript" language="javascript">
			  <!-- 
			        document.getElementById("customSearchInput").value="Search";
			  //-->
			      </script>
				  
<!-- <p style="margin-top:10px;">Change font size: <a href="[FontSize-]"><img src="template/lang/all/icons/reduce.gif" width="18" height="17" alt="" title="Small" border="0" /></a>
			<a href="[FontSize+]"><img src="template/lang/all/icons/extend.gif" width="18" height="17" alt="" title="Bigger" border="0" /></a>
			</p> -->
			
	<p style="margin-top:10px;">Please choose: 
	
	 </p>

<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div>

<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div>
<!-- <a href="http://validator.w3.org/check?uri=http%3A%2F%2Fwww.phpwcms-docu.de%2Findex.php%3Fdeutsche_version" title="W3C Standard XHTML" target="_blank"><img src="picture/w3c/w3c_xhtml.gif" border="0" alt="" /></a>
<a href="http://jigsaw.w3.org/css-validator/validator?uri=http://www.phpwcms-docu.de" title="W3C Standard CSS" target="_blank"><img src="picture/w3c/w3c_css.gif" border="0" alt="" /></a><br />			
<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div> -->
		
<div style="margin-top:10px; margin-bottom:15px;"></div>
	
</div>

	</div> 
	
	<div id="content">
	<div id="bread">You are here: <a href="english_version.phtml">English</a> <span class="breadcrumb_spacer">&gt;</span> <a href="the_docu.phtml">The Docu</a> <span class="breadcrumb_spacer">&gt;</span> <a href="add-ons-and-templates.phtml">Add On&#039;s and Templates</a> <span class="breadcrumb_spacer">&gt;</span> <a href="Share-Your-Templates.phtml">Share Your Templates</a> <span class="breadcrumb_spacer">&gt;</span> <a href="templates-for-content-parts.phtml">For Content Parts</a> <span class="breadcrumb_spacer">&gt;</span> Guestbook</div>
		
		<a name="jump408"></a><!-- Livedate: 18.09.2007 05:09:30 / Killdate: 15.09.2017 23:59:59 -->
<h1>Guestbook Template</h1>
<h3>with separate input mask</h3>

<div style="margin:15px 0 0 0;padding:0;" class="spaceBeforeCP"></div><p>First please download the following file and unpack it on your computer. Then upload the files onto your webspace /server.</p><div style="border-bottom:1px dotted #d2e2f5; margin-top:10px; margin-bottom:15px;"></div>
<h4>Download</h4>

<p>The zip file contains the following files:<br />
<br />
Template for the article:<br />
template/inc_cntpart/Articlesummary/article/guestbook_split_at_en.tmpl<br />
<br />
Templates for the content part guestbook:<br />
<br />
Template of the input mask for new guestbook entries:<br />
template/inc_cntpart/guestbook/guestbook_split_entry_en.html<br />
<br />
Template of the overview of the guestbook entries:<br />
template/inc_cntpart/guestbook/guestbook_split_view_en.html<br />
<br />
Every of the templates is also available as GERMAN in the zip file. You can detect the file looking for the suffix DE.</p>
<div style="margin-top: 15px; padding-top: 10px; border-top: 1px dotted #CCCCCC;">

	<div class="fileEntry" style="margin-bottom:10px; padding-bottom: 10px; border-bottom: 1px dotted #CCCCCC;">
		<h2>
			<img src="img/icons/small_icon_zip.gif" alt="" border="0" />
			
			<a href="download/e45d1b99aaf758a8c7c4e1d31b19ff7a.zip" target="_blank">gb_template_v1.zip</a>
		</h2>
		<p>
		Guestbook Template<br />
		zip, 8,4 KB, 09/23/09, 1945 downloads
		</p>

	</div>


</div>
<h3>Einrichtung</h3>
<table border="0" cellspacing="0" width="10%" cellpadding="0" align="left" class=" imgListTableLeft" summary="">
<tr>
	<td class="imagelisttd2"><a href="content/images/83ad6aae15507465011b82fe74337d38.png" rel="lightbox[pNdVg]" title="Image 1 - Article Template" target="_blank"><img src="content/images/968ea0ad0fb3babe00a3640cef478026.png" width="150" height="111" border="0" class="imagelistimg" alt="gb_temp_ss_1.png" /></a></td>
</tr>
<tr>
	<td class="imglistcaption">Image 1 - Article Template</td>
</tr>

<tr>
	<td class="imagelistSpacerRow"><img src="img/leer.gif" width="1" height="1" border="0" alt="" /></td>
</tr>
<tr>
	<td class="imagelisttd2"><a href="content/images/7a6e5a1ef22c7cb0b601c9fe1c49bfee.png" rel="lightbox[pNdVg]" title="Image 2 - Content Part 1" target="_blank"><img src="content/images/145d02849ea4eb72683495ec43043760.png" width="150" height="23" border="0" class="imagelistimg" alt="gb_temp_ss_2.png" /></a></td>
</tr>
<tr>
	<td class="imglistcaption">Image 2 - Content Part 1</td>
</tr>

<tr>
	<td class="imagelistSpacerRow"><img src="img/leer.gif" width="1" height="1" border="0" alt="" /></td>
</tr>
<tr>
	<td class="imagelisttd2"><a href="content/images/02ea729d1f2383000795de54d2b42de4.png" rel="lightbox[pNdVg]" title="Image 3 - Content Part 2" target="_blank"><img src="content/images/a94c7740c13642f7c0f3e2784be46786.png" width="150" height="23" border="0" class="imagelistimg" alt="gb_temp_ss_3.png" /></a></td>
</tr>
<tr>
	<td class="imglistcaption">Image 3 - Content Part 2</td>
</tr>

<tr>
	<td class="imagelistSpacerRow"><img src="img/leer.gif" width="1" height="1" border="0" alt="" /></td>
</tr>
<tr>
	<td class="imagelisttd2"><a href="content/images/cd85834031fe485f608ad3d72f0e07aa.png" rel="lightbox[pNdVg]" title="Image 4 - Content Part Overview" target="_blank"><img src="content/images/d14c95909a502f4d4772266503e64034.png" width="150" height="75" border="0" class="imagelistimg" alt="gb_temp_ss_4.png" /></a></td>
</tr>
<tr>
	<td class="imglistcaption">Image 4 - Content Part Overview</td>
</tr>
</table>
<p>Proceed as follows to include the templates in an existing guestbook: <br />
<br />
1. Go to article base information of the guestbook article and choose the template under &quot;article detail&quot; (in this case for English) <strong>guestbook_split_at_en.tmpl</strong>. Then check &quot;<strong>Paginate Content Parts</strong>&quot;. Click then &quot;Save&quot; to overtake the changes (Image 1).<br />
<br />
2. Edit the existing content part &quot;Guestbook&quot;. Insert &quot;<strong>1</strong>&quot; at Section and choose &quot;<strong>guestbook_split_view_en</strong>&quot; at Templates. Click then &quot;Save&quot; to overtake the changes (Image 2).<br />
<br />
3. Create a second content part &quot;Guestbook&quot;. Insert &quot;<strong>2</strong>&quot; at Section and choose &quot;g<strong>uestbook_split_entry_en</strong>&quot; at Templates. Furthermore insert the ID of the main guestbook at &quot;<strong>Alias ID</strong>&quot;, in this case it is &quot;2&quot;. Click then &quot;Save&quot; to overtake the changes (Image 3).<br />
<br />
After saving the changes you should see an overview like on Image 4.<br />
<br />
Notice: After writing an entry a cookie will be set. Therefore you will not see an input mask anymore after your first entry because it will be hidden because of the cookie. <br />
<br />
If you have questions or need some help please use the <a href="./kontakt.phtml" target="_blank">Contact form</a> of the website.</p>
		 
		
		<br /><br />
		<div class="sub">
		Article created: Thursday, 20. September 2007 <br /> Last Changes: Tuesday, 30. October 2007	
		</div>
				
	</div>
	
<div id="footer">





	<table width="97%" border="0" cellspacing="0" cellpadding="0">
		<tr>
			<td valign="bottom">	
			&copy; phpwcms-docu 2004-2010
			<img src="img/leer.gif" border="0" width="10" height="0" alt="" /><a href="imprint.phtml" class="phpwcmsIntLink"><img src="template/lang/all/icons/imprint.gif" width="9" height="15" alt="Impressum" title="Impressum" border="0" /></a>&nbsp; 
			<a href="sitemap_en.phtml" class="phpwcmsIntLink"><img src="template/lang/all/icons/sitemap.gif" width="19" height="15" alt="Sitemap" title="Sitemap" border="0" /></a>&nbsp; 
			 
			
			     
			</td>
			<td valign="bottom" style="padding-right:25px;">
			
			
			
			</td>		
			<td width="150">
			</td>
		</tr>
	</table>
</div><br/>

</div>
</body>
</html>