<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<!--
	phpwcms | free open source content management system
	created by Oliver Georgi (oliver at phpwcms dot de) and licensed under GNU/GPL.
	phpwcms is copyright 2003-2007 of Oliver Georgi. Extensions are copyright of
	their respective owners. Visit project page for details: http://www.phpwcms.org/
//-->
<title>phpwcms-docu for  phpwcms :: web based content management system | Link us | Link us</title>
  <meta http-equiv="content-type" content="text/html; charset=iso-8859-1" />
  <meta http-equiv="content-style-type" content="text/css" />
  <script src="template/inc_js/frontend.js" type="text/javascript"></script>
  <style type="text/css">
  <!-- 
    @import url("template/inc_css/mpl_docu.css");
    @import url("template/inc_css/mpl_frontend.css");
    @import url("template/inc_css/mpl_menu.css");
    @import url("template/inc_css/mpl_objects.css");
  //-->
  </style>
<script type="text/javascript" language="javascript">
<!--
function MM_jumpMenu(targ,selObj,restore){ //v3.0
  eval(targ+".location='"+selObj.options[selObj.selectedIndex].value+"'");
  if (restore) selObj.selectedIndex=0;
}

function MM_findObj(n, d) { //v4.01
  var p,i,x;  if(!d) d=document; if((p=n.indexOf("?"))>0&&parent.frames.length) {
    d=parent.frames[n.substring(p+1)].document; n=n.substring(0,p);}
  if(!(x=d[n])&&d.all) x=d.all[n]; for (i=0;!x&&i<d.forms.length;i++) x=d.forms[i][n];
  for(i=0;!x&&d.layers&&i<d.layers.length;i++) x=MM_findObj(n,d.layers[i].document);
  if(!x && d.getElementById) x=d.getElementById(n); return x;
}

function MM_jumpMenuGo(selName,targ,restore){ //v3.0
  var selObj = MM_findObj(selName); if (selObj) MM_jumpMenu(targ,selObj,restore);
}
//-->
</script>
<meta name="Title" content="Die phpWCMS Dokumentation" />
<meta name="author" content="Oliver Frohnert, Mario Perez Leal" />
<meta name="Publisher" content="Oliver Frohnert, Mario Perez Leal, creacion" />
<meta name="Copyright" content="Oliver Frohnert, Mario Perez Leal, creacion" />
<meta name="keywords" content="frohnert, perez leal, creacion, documentation, dokumentation, phpwcms, cms, opensource, open source, docu" />
<meta name="description" content="Das Dokumentations Projekt für das Open Source CMS phpWCMS" />
<meta name="Audience" content="Alle" />
<meta name="Content-language" content="DE" />
<meta name="robots" content="index,follow" />
<meta name="expires" content="0" />
<meta name="revisit-after" content="7 days" />
<meta name="resource-type" content="document" />
<meta name="distribution" content="Global" />
<meta name="generator" content="PHPWCMS" />
<meta name="verify-v1" content="1ZpxZ7AZsjm7PxjqXQVus0eiUYqOsp5URTJn9q4KNz8=" />
  <!--[if lt IE 7]>
  <style type="text/css">
    body { behavior: url("template/inc_css/specific/csshover2.htc"); }
    img { behavior: url("template/inc_css/specific/pngbehavior.htc"); }
  </style>
  <![endif]-->
</head>
<body id="myid_442">
<div id="container"><a name="top" id="top"></a>


	<div id="head">
		
	<div id="mainnavi">
		<div class="fleft"><a href="deutsche_version.phtml">Startseite</a> | <a href="news_de.phtml">News</a> | <a href="die_docu.phtml">Die Docu</a> | <a href="Nuetzliche_Links_und_Tools.phtml">Links &amp; Tools</a> | <a href="downloads.phtml">Downloads</a> | <span style="text-decoration:none;font-weight:bold;"><a href="kontakt.phtml">Kontakt</a></span> | <a href="faq_de.phtml">FAQ</a> | <a href="http://forum.phpwcms.org/" target="_blank">Forum</a> | <a href="howto_de.phtml">HowTo</a></div>				
		<div class="sys">Dienstag, 23. November 2010<img src="img/leer.gif" border="0" width="5" height="1" alt="" />|<img src="img/leer.gif" border="0" width="5" height="1" alt="" />8 User online<img src="img/leer.gif" border="0" width="10" height="1" alt="" />
		<a href="deutsche_version.phtml" title="Deutsche Version"><img src="picture/../template/lang/all/flag_de.gif" border="0" alt="" /></a>
		<a href="english_version.phtml"  title="English version"><img src="picture/../template/lang/all/flag_en.gif" border="0" alt="" /></a>
		</div>
	</div>
	
	<a href="./" title="phpwcms-docu Startseite aufrufen" class="homelink">
	<span>&raquo; Zur phpwcms-docu Startseite</span></a>
	<h2>phpwcms-docu - Die Dokumentation f&uuml;r f&uuml;r das CMS phpWCMS</h2>
	<p>phpwcms-docu ist eine Art Kompass, der Ihnen die M&ouml;glichkeiten von phpWcms aufzeigt und Sie erfolgreich, ohne gro&szlig;e Umwege, zu Ihrer fertigen Web-Anwendung f&uuml;hren soll.
	</p>
	</div>

	
	<div id="left">
	<div class="leftnav" style="margin-top:24px;">
	
<div id="ul_div_71">
<ul>
	<li class="sub_no"><a href="impressum.phtml">Impressum</a></li>
	<li class="sub_no"><a href="nutzung.phtml">Nutzungsbedingungen</a></li>
	<li class="sub_no active"><a href="linkus.phtml">Link us</a></li>
	<li class="sub_no"><a href="newsletter_de.phtml">Newsletter</a></li>
	<li class="sub_no"><a href="gaestebuch.phtml">Gästebuch</a></li>
</ul>
</div>

		
		
		

	</div> 
	</div> 
	  
	<div id="right">
		<div style="margin-top:24px;">			
		<form action="index.php?suche" method="post" name="searchFE" onsubmit="s=document.getElementById('customSearchInput');if(s.value=='Suchen')return false;">
			<table width="100%" border="0" cellpadding="0" cellspacing="0">
			<tr>
					<td><input type="text" name="search_input_field" size="20" maxlength="200" id="customSearchInput" class="customSearchInput" value="" onfocus="if(this.value=='Suchen')this.value='';" onblur="if(this.value=='')this.value='Suchen';" /></td>
					<td><input type="image" name="search_go" onfocus="this.blur();" title="Suchen" src="/template/lang/all/submit.gif" /></td>
				</tr>
			</table>
			</form>
			
			      <script type="text/javascript" language="javascript">
			  <!-- 
			        document.getElementById("customSearchInput").value="Suchen";
			  //-->
			      </script>
				  
			<!-- <p style="margin-top:10px;">Schriftgrad &auml;ndern: <a href="[FontSize-]"><img src="template/lang/all/icons/reduce.gif" width="18" height="17" alt="" title="Verkleinern" border="0" /></a>
			<a href="[FontSize+]"><img src="template/lang/all/icons/extend.gif" width="18" height="17" alt="" title="Vergr&ouml;&szlig;ern" border="0" /></a>
			</p> -->
			
	
<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div>


<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div>
<!-- <a href="http://validator.w3.org/check?uri=http%3A%2F%2Fwww.phpwcms-docu.de%2Findex.php%3Fdeutsche_version" title="W3C Standard XHTML" target="_blank"><img src="picture/w3c/w3c_xhtml.gif" border="0" alt="" /></a>
<a href="http://jigsaw.w3.org/css-validator/validator?uri=http://www.phpwcms-docu.de" title="W3C Standard CSS" target="_blank"><img src="picture/w3c/w3c_css.gif" border="0" alt="" /></a><br />			
<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div> -->
<h3>Partnersites</h3>






<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div>

<div style="margin-top:10px; margin-bottom:15px;"></div>


<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div>
</div>

	</div> 
	
	<div id="content">
	<div id="bread">Sie sind hier: <a href="deutsche_version.phtml">Deutsch</a> <span class="breadcrumb_spacer">&gt;</span> <a href="kontakt.phtml">Kontakt</a> <span class="breadcrumb_spacer">&gt;</span> Link us</div>
		
		<a name="jump423"></a><!-- Livedate: 23.10.2007 12:03:28 / Killdate: 20.10.2017 23:59:59 -->
<h1>Link us</h1>

<div class="articleText"><p><b>Sie m&ouml;chten phpwcms-docu unterst&uuml;tzen und ihren Besuchern einen optisch ansprechenden Link zu phpwcms-docu anbieten? Das freut uns nat&uuml;rlich sehr...</b><br />
<br />
<b>Und so gehts:</b><br />
Einfach den HTML-Quellcode f&uuml;r das gew&uuml;nschte Banner markieren, kopieren (z.B. Strg+C) und schon  k&ouml;nnen Sie diesen in ihre HTML-Seite oder Artikel einf&uuml;gen. <br />
<br />
Das Banner wird von unserem Server abgerufen, verifiziert und verursacht keinen zus&auml;tzlichen Traffic f&uuml;r ihre Website. Die Pfad- und Dateiangaben sind absolut gesetzt (./...).</p></div><div style="margin:0 0 50px 0;padding:0;" class="spaceAfterCP"></div><p><strong>White gear Banner (PNG-Format)</strong></p>
<p><img width="134" height="28" alt="" src="picture/upload/image/banner/png1.png" /></p><br />
<form action="" name="phpwcmsdocu1" id="phpwcmsdocu1">
    <textarea onclick="javascript:this.form.phpwcmsdocu1.focus();this.form.phpwcmsdocu1.select();" rows="3" cols="55" class="linkarea" name="phpwcmsdocu1">&lt;a href=&quot;http://www.phpwcms-docu.de&quot; title=&quot;The official documentation&quot; target=&quot;_blank&quot;&gt;&lt;img src=&quot;./banner/docu1.png&quot; width=&quot;134&quot; height=&quot;28&quot; alt=&quot;Jump to phpwcms-docu&quot; border=&quot;0&quot;&gt;&lt;/a&gt; </textarea><br />
    <input type="button" onclick="javascript:this.form.phpwcmsdocu1.focus();this.form.phpwcmsdocu1.select();" value="markieren" class="globalbtstyle" />
</form><div style="border-bottom:1px dotted #d2e2f5; margin-top:10px; margin-bottom:15px;"></div><p><strong>Blue gear Banner (PNG-Format)</strong></p>
<p><img width="134" height="28" alt="" src="picture/upload/image/banner/png2.png" /></p><br />
<form action="" name="phpwcmsdocu2" id="phpwcmsdocu2">

    <textarea onclick="javascript:this.form.phpwcmsdocu2.focus();this.form.phpwcmsdocu2.select();" rows="3" cols="55" class="linkarea" name="phpwcmsdocu2">&lt;a href=&quot;http://www.phpwcms-docu.de&quot; title=&quot;The official documentation&quot; target=&quot;_blank&quot;&gt;&lt;img src=&quot;./banner/docu2.png&quot; width=&quot;134&quot; height=&quot;28&quot; alt=&quot;Jump to phpwcms-docu&quot; border=&quot;0&quot;&gt;&lt;/a&gt; </textarea><br />
    <input type="button" onclick="javascript:this.form.phpwcmsdocu2.focus();this.form.phpwcmsdocu2.select();" value="markieren" class="globalbtstyle" />
</form><div style="border-bottom:1px dotted #d2e2f5; margin-top:10px; margin-bottom:15px;"></div><p><strong>Micro Banner (Gif-Format)</strong></p>
<p><img width="88" height="18" alt="" src="picture/upload/image/banner/micro.gif" /></p><br />
<form action="" name="phpwcmsdocu3" id="phpwcmsdocu3">

    <textarea onclick="javascript:this.form.phpwcmsdocu3.focus();this.form.phpwcmsdocu3.select();" rows="3" cols="55" class="linkarea" name="phpwcmsdocu3">&lt;a href=&quot;http://www.phpwcms-docu.de&quot; title=&quot;The official documentation&quot; target=&quot;_blank&quot;&gt;&lt;img src=&quot;./banner/micro.gif&quot; width=&quot;88&quot; height=&quot;18&quot; alt=&quot;Jump to phpwcms-docu&quot; border=&quot;0&quot;&gt;&lt;/a&gt; </textarea><br />
    <input type="button" onclick="javascript:this.form.phpwcmsdocu3.focus();this.form.phpwcmsdocu3.select();" value="markieren" class="globalbtstyle" />
</form><div style="border-bottom:1px dotted #d2e2f5; margin-top:10px; margin-bottom:15px;"></div><p><strong>Micro Banner (Gif-Format)</strong></p>
<p><img width="109" height="18" alt="" src="picture/upload/image/banner/mini.gif" /></p><br />
<form action="" name="phpwcmsdocu4" id="phpwcmsdocu4">

    <textarea onclick="javascript:this.form.phpwcmsdocu4.focus();this.form.phpwcmsdocu4.select();" rows="3" cols="55" class="linkarea" name="phpwcmsdocu4">&lt;a href=&quot;http://www.phpwcms-docu.de&quot; title=&quot;The official documentation&quot; target=&quot;_blank&quot;&gt;&lt;img src=&quot;./banner/mini.gif&quot; width=&quot;109&quot; height=&quot;18&quot; alt=&quot;Jump to phpwcms-docu&quot; border=&quot;0&quot;&gt;&lt;/a&gt; </textarea><br />
    <input type="button" onclick="javascript:this.form.phpwcmsdocu4.focus();this.form.phpwcmsdocu4.select();" value="markieren" class="globalbtstyle" />
</form><div style="border-bottom:1px dotted #d2e2f5; margin-top:10px; margin-bottom:15px;"></div><p><strong>Half Size Banner (PNG-Format)</strong></p>
<p><img width="213" height="48" alt="" src="picture/upload/image/banner/png3.png" /></p><br />
<form action="" name="phpwcmsdocu5" id="phpwcmsdocu5">

    <textarea onclick="javascript:this.form.phpwcmsdocu5.focus();this.form.phpwcmsdocu5.select();" rows="3" cols="55" class="linkarea" name="phpwcmsdocu5">&lt;a href=&quot;http://www.phpwcms-docu.de&quot; title=&quot;The official documentation&quot; target=&quot;_blank&quot;&gt;&lt;img src=&quot;./banner/docu3.png&quot; width=&quot;213&quot; height=&quot;48&quot; alt=&quot;Jump to phpwcms-docu&quot; border=&quot;0&quot;&gt;&lt;/a&gt; </textarea><br />
    <input type="button" onclick="javascript:this.form.phpwcmsdocu5.focus();this.form.phpwcmsdocu5.select();" value="markieren" class="globalbtstyle" />
</form><div style="border-bottom:1px dotted #d2e2f5; margin-top:10px; margin-bottom:15px;"></div><p><strong>Full Size Banner (Gif-Format)</strong></p>
<p><img width="468" height="61" alt="" src="picture/upload/image/banner/fullbanner.gif" /></p><br />
<form action="" name="phpwcmsdocu6" id="phpwcmsdocu6">

    <textarea onclick="javascript:this.form.phpwcmsdocu6.focus();this.form.phpwcmsdocu6.select();" rows="3" cols="55" class="linkarea" name="phpwcmsdocu6">&lt;a href=&quot;http://www.phpwcms-docu.de&quot; title=&quot;The official documentation&quot; target=&quot;_blank&quot;&gt;&lt;img src=&quot;./banner/fullbanner.gif&quot; width=&quot;468&quot; height=&quot;61&quot; alt=&quot;Jump to phpwcms-docu&quot; border=&quot;0&quot;&gt;&lt;/a&gt; </textarea><br />
    <input type="button" onclick="javascript:this.form.phpwcmsdocu6.focus();this.form.phpwcmsdocu6.select();" value="markieren" class="globalbtstyle" />
</form>
		 
		
		<br /><br />
		<div class="sub">
			
		</div>
				
	</div>
	
<div id="footer"><br /><br />
<br />





	<table width="97%" border="0" cellspacing="0" cellpadding="0">
		<tr>
			<td valign="bottom">	
			&copy; phpwcms-docu 2004-2010
			<img src="img/leer.gif" border="0" width="10" height="0" alt="" /><a href="impressum.phtml" class="phpwcmsIntLink"><img src="template/lang/all/icons/imprint.gif" width="9" height="15" alt="Impressum" title="Impressum" border="0" /></a>&nbsp; 
			<a href="sitemap_de.phtml" class="phpwcmsIntLink"><img src="template/lang/all/icons/sitemap.gif" width="19" height="15" alt="Sitemap" title="Sitemap" border="0" /></a>&nbsp; 
			<a href="gaestebuch.phtml" class="phpwcmsIntLink"><img src="template/lang/all/icons/gbook.gif" width="20" height="16" alt="Ins G&auml;stebuch eintragen" title="Ins G&auml;stebuch eintragen" border="0" /></a>&nbsp; 
			<a href="#" onclick="BookMark_Page();return false;" title="" class="phpwcmsBookmarkLink"><img src="template/lang/all/icons/favo.gif" width="12" height="15" alt="Seite als Bookmark speichern" title="Seite als Bookmark speichern" border="0" /></a>&nbsp; 
			     
			</td>
			<td valign="bottom" style="padding-right:25px;">
			
			
			
			</td>		
			<td width="150">
			</td>
		</tr>
	</table>
</div><br/>

</div>
</body>
</html>