<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">

<!--

phpwcms | open source web content management system

          developed by Oliver Georgi (info@phpwcms.de)
          released under The GNU General Public License
          visit project page: http://www.phpwcms.de

          Release: 1.1-RC4 27-08-2004

//-->
<html>
<head>
<title>phpwcms documentation | Login in das Backend</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<META NAME="Title" CONTENT="Die phpWCMS Dokumentation">
<meta name="author" content="Oliver Frohnert">
<meta name="Publisher" content="Oliver Frohnert">
<meta name="Copyright" content="Oliver Frohnert">
<meta name="keywords" content="frohnert,documentation, dokumentation, phpwcms, cms. opensource, open source">
<meta name="description" content="Das Dokumentations Projekt für das Open Source CMS phpWCMS">
<meta name="Audience" content="Alle">
<meta name="Content-language" content="DE">
<META NAME="robots"      CONTENT="index,follow">
<META NAME="expires" CONTENT="0">
<meta name="revisit-after" content="7 days">
<meta name="resource-type" content="document">
<meta name="distribution" content="Global">
<meta name="generator" content="PHPWCMS">
<script language="JavaScript" type="text/javascript" src="pphlogger.js"></script>
<noscript><img alt="" src="./pphlogger/pphlogger.php?id=phpwcms&st=img"></noscript>
<script src="template/inc_js/frontend.js" type="text/javascript"></script>
<link rel="stylesheet" type="text/css" href="template/inc_css/frontend.css">
</head>

<body bgcolor="#FFFFFF" text="#000000" link="#FF9900" vlink="#FF9900" alink="#FF9900" topmargin="0" leftmargin="0" marginwidth="0" marginheight="0">
<table border="0" cellspacing="0" cellpadding="0" width="760" bgcolor="#ffffff" class="maintable" align="center">
<tr>
<td colspan="2" style="height:60px;"  bgcolor="#ffffff"><table width="760" height="135" border="0" cellpadding="0" cellspacing="0">
  <tr valign="top">
    <td width="1334" height="122" colspan="6" background="template/lang/de/header.jpg">&nbsp;</td>
  </tr>
  <tr>
	<td height="27" background="template/lang/all/top_menu.jpg"><table width="570" border="0" align="left" cellpadding="0" cellspacing="0">
      <tr>
        <td align="center" width="254"><a href="deutsche_version.phtml"><img src="picture/flags/de.gif" width="16" height="10" hspace="10" border="0"  alt="Deutsche Version" title="Deutsche Version"></a>
<a href="english_version.phtml"><img src="picture/flags/gb.gif" width="16" height="10" hspace="10" border="0"  alt="English Version" title="English Version"></a></td>
        <td valign="middle"><div align="center"><a href="replacement_tags_de.phtml"><img src="content/gt/9ad4c84df9fc6e20be504ff61a358128.png" alt="Replacement Tags" border="0" /></a></div></td>
        <td width="30" valign="middle"><div align="center"><img src="template/lang/all/sep.gif" width="5" height="5" border="0"></div></td>
        <td valign="middle"><div align="center"><a href="content_parts_de.phtml"><img src="content/gt/0ac72fda03e1537553c1f89e3f96ad75.png" alt="Content Parts" border="0" /></a></div></td>
        <td width="30" valign="middle"><div align="center"><img src="template/lang/all/sep.gif" width="5" height="5" border="0"></div></td>
        <td valign="middle"><div align="center"><a href="links_de.phtml"><img src="content/gt/c13491df26fc7ba71211ce67d0cd7cac.png" alt="Links" border="0" /></a></div></td>
        <td width="30" valign="middle"><div align="center"><img src="template/lang/all/sep.gif" width="5 " height="5" border="0"></div></td>
        <td valign="middle"><div align="center"><a href="impressum.phtml"><img src="content/gt/304aadbbc5a74f91579640823fb3c8ab.png" alt="Impressum" border="0" /></a></div></td>
     </tr>
    </table>    </td>
  </tr>
</table></td>
</tr>
<tr>
<td valign="top" width="185" background="img/menu.gif"><table width="180" border="0" cellpadding="0" cellspacing="0">
  <tr>
    <td width="180" height="20">&nbsp;</td>
  </tr>
  <tr>
    <td style="padding-left: 7px;"><table border="0" width="100%" cellspacing="0" cellpadding="0">
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='news_de.phtml';return false;" onMouseOver="MM_swapImage('linkidMlqLIL','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td ><img src="img/leer.gif" width="1" height="1" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkidMlqLIL" id="linkidMlqLIL"></td>
<td valign="top" style="height:20px;"  width="100%" class="nav_table" colspan="2"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="news_de.phtml">News</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="0"><img src="img/leer.gif" width="8" height="20" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='inst_de.phtml';return false;" onMouseOver="MM_swapImage('linkid16kyM3','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td ><img src="img/leer.gif" width="1" height="1" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkid16kyM3" id="linkid16kyM3"></td>
<td valign="top" style="height:20px;"  width="100%" class="nav_table" colspan="2"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="inst_de.phtml">Installation</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="0"><img src="img/leer.gif" width="8" height="20" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='verwaltung_login.phtml';return false;">
<td ><img src="img/leer.gif" width="1" height="1" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_2" alt="" border="" name="linkiduNZo2c" id="linkiduNZo2c"></td>
<td valign="top" style="height:20px;"  width="100%" class="nav_table_active" colspan="2"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="verwaltung_login.phtml">Die Docu</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="0"><img src="img/leer.gif" width="8" height="20" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='die_artikelzentrale.phtml';return false;" onMouseOver="MM_swapImage('linkid9IdqfC','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td  colspan="2"><img src="img/leer.gif" width="1" height="1" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkid9IdqfC" id="linkid9IdqfC"></td>
<td valign="top" style="height:20px;"  width="100%" class="nav_table"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="die_artikelzentrale.phtml">Artikel</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="0"><img src="img/leer.gif" width="8" height="20" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='dateien_hinzufuegen.phtml';return false;" onMouseOver="MM_swapImage('linkidLateJZ','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td  colspan="2"><img src="img/leer.gif" width="1" height="1" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkidLateJZ" id="linkidLateJZ"></td>
<td valign="top" style="height:20px;"  width="100%" class="nav_table"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="dateien_hinzufuegen.phtml">Datei</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="0"><img src="img/leer.gif" width="8" height="20" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='verwaltung_module.phtml';return false;" onMouseOver="MM_swapImage('linkidP4MsB6','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td  colspan="2"><img src="img/leer.gif" width="1" height="1" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkidP4MsB6" id="linkidP4MsB6"></td>
<td valign="top" style="height:20px;"  width="100%" class="nav_table"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="verwaltung_module.phtml">Module</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="0"><img src="img/leer.gif" width="8" height="20" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='verwaltung_nachricht.phtml';return false;" onMouseOver="MM_swapImage('linkidUp51ly','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td  colspan="2"><img src="img/leer.gif" width="1" height="1" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkidUp51ly" id="linkidUp51ly"></td>
<td valign="top" style="height:20px;"  width="100%" class="nav_table"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="verwaltung_nachricht.phtml">Nachricht</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="0"><img src="img/leer.gif" width="8" height="20" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='verwaltung_chat.phtml';return false;" onMouseOver="MM_swapImage('linkidA4pb88','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td  colspan="2"><img src="img/leer.gif" width="1" height="1" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkidA4pb88" id="linkidA4pb88"></td>
<td valign="top" style="height:20px;"  width="100%" class="nav_table"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="verwaltung_chat.phtml">Chat</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="0"><img src="img/leer.gif" width="8" height="20" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='verwaltung_profil.phtml';return false;" onMouseOver="MM_swapImage('linkidcKuffa','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td  colspan="2"><img src="img/leer.gif" width="1" height="1" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkidcKuffa" id="linkidcKuffa"></td>
<td valign="top" style="height:20px;"  width="100%" class="nav_table"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="verwaltung_profil.phtml">Profil</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="0"><img src="img/leer.gif" width="8" height="20" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='verwaltung_admin.phtml';return false;" onMouseOver="MM_swapImage('linkidcI7EL4','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td  colspan="2"><img src="img/leer.gif" width="1" height="1" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkidcI7EL4" id="linkidcI7EL4"></td>
<td valign="top" style="height:20px;"  width="100%" class="nav_table"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="verwaltung_admin.phtml">Admin<img src="picture/myRT1/neuR.gif" alt="1/16/2005" border="0"></a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="0"><img src="img/leer.gif" width="8" height="20" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='add_on.phtml';return false;" onMouseOver="MM_swapImage('linkidJVwUd1','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td ><img src="img/leer.gif" width="1" height="1" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkidJVwUd1" id="linkidJVwUd1"></td>
<td valign="top" style="height:20px;"  width="100%" class="nav_table" colspan="2"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="add_on.phtml">Add Ons<img src="picture/myRT1/neuR.gif" alt="1/9/2005" border="0"></a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="0"><img src="img/leer.gif" width="8" height="20" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='fehlermeldungen.phtml';return false;" onMouseOver="MM_swapImage('linkidiYcVaS','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td ><img src="img/leer.gif" width="1" height="1" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkidiYcVaS" id="linkidiYcVaS"></td>
<td valign="top" style="height:20px;"  width="100%" class="nav_table" colspan="2"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="fehlermeldungen.phtml">Fehlermeldungen</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="0"><img src="img/leer.gif" width="8" height="20" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='suche.phtml';return false;" onMouseOver="MM_swapImage('linkidgr6kvn','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td ><img src="img/leer.gif" width="1" height="1" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkidgr6kvn" id="linkidgr6kvn"></td>
<td valign="top" style="height:20px;"  width="100%" class="nav_table" colspan="2"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="suche.phtml">Suche</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="0"><img src="img/leer.gif" width="8" height="20" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='kontakt.phtml';return false;" onMouseOver="MM_swapImage('linkid7yGzJi','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td ><img src="img/leer.gif" width="1" height="1" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkid7yGzJi" id="linkid7yGzJi"></td>
<td valign="top" style="height:20px;"  width="100%" class="nav_table" colspan="2"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="kontakt.phtml">Kontakt</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="0"><img src="img/leer.gif" width="8" height="20" alt="" /></td>
</tr>
</table></td>
  </tr>
   <tr>
    <td style="padding:10px; color:#000000;"><img src="picture/seperate.gif" border="0" alt="" /><P>
	<a href="deutsche_version.phtml?id=285,212,0,0,1,0">Letzte Version:<br>
RC 1.1 - 27.08.2004a<br>
Vö: 6.11.2004<P>
Letzter Patch:<BR>
26.11.2004</a><P>
<img src="picture/seperate.gif" border="0" alt="" /></TD>
  </tr>
  <tr>
    <td align="center"><a target='_blank' href='./ads/adclick.php?bannerid=13&amp;zoneid=0&amp;source=&amp;dest=http%3A%2F%2Fjames.adbutler.de%2Fclick.php%3Fpid%3D4511%26tid%3D111647%26bid%3D15338&amp;ismap=' ><img src='http://james.adbutler.de/view.php?pid=4511&bid=15338&tid=111647&b=120&h=600&inv=img' width='120' height='600' border='0'></a><div id="beacon_13" style="position: absolute; left: 0px; top: 0px; visibility: hidden;"><img src='./ads/adlog.php?bannerid=13&amp;clientid=16&amp;zoneid=0&amp;source=&amp;block=0&amp;capping=0&amp;cb=469cc815a825b1f8c306f993f8eef109' width='0' height='0' alt='' style='width: 0px; height: 0px;'></div><BR>WERBUNG<BR><BR><img src="picture/seperate.gif" border="0" alt="" /><P>
</td>
  </tr>
<tr>
    <td height="20">&nbsp;</td>
  </tr>
  <tr>
    <td align="center"></td>
  </tr>
  <tr>
    <td height="20">&nbsp;</td>
  </tr>
</table>


</body>
</html>
</td>
<td valign="top" width="555" bgcolor="#ffffff" class="maincontent"><img src="img/leer.gif" border="0" width="10" height="1" alt="" />
<BR>
<a href="deutsche_version.phtml">Deutsch</a> <span class="breadcrumb_spacer">&gt;</span> Die Docu
<br>
<HR>
<br>
<a name="jump14"></a><span class="articleHead">Login in das Backend</span><img src="img/leer.gif" width="1" height="8" alt=""><br /><img src="img/leer.gif" width="1" height="15" alt="" /><br><span class="contentHead">Übersicht und Vorbereitung</span><br><img src="img/leer.gif" width="1" height="3" alt=""><br /><table width="158" border="0" cellspacing="0" cellpadding="0" align="left" class="table_class">
<tr><td class="image_td"><a href="zoom/NF8yMDdfQWZoU3d6OVo4Ti5naWY.html" onClick="window.open('zoom/NF8yMDdfQWZoU3d6OVo4Ti5naWY.html','previewpic','width=538,height=316');return false;.html"><img src="content/images/4_207_AfhSwz9Z8N-150x.gif" width="150" height="88" border="0" class="image_img" alt="" /></a></td><td><img src="img/leer.gif" width="8" height="1" alt="" /></td></tr>
<tr><td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td></tr>
<tr><td align="center" bgcolor="FCFCFC" class="image_caption"><img src="img/leer.gif" width="1" height="3" alt="" /><br><img src="picture/icon_lupe_.gif" border="0" alt="" /><img src="content/gt/fb4f6e4639b2d7e2b19b7ea01fe84770.png" alt="Zoom" border="0" /><br><img src="img/leer.gif" width="1" height="3" alt="" /></td><td><img src="img/leer.gif" width="8" height="1" alt="" /></td></tr>
</table><div class="articleText"><TABLE class="" cellSpacing=0 cellPadding=0 width="75%" border=0>
<TBODY>
<TR>
<TD>phpWCMS zeichnet sich durch seine einfache Handhabung, übersichtliche Struktur und die klare Trennung von Administration und Redaktion aus. 
<P>Bevor Sie Webinhalte hinzufügen oder ändern können, müssen Sie sich einloggen. Geben Sie dazu im Browser Ihrer Wahl die Adresse www.meinedomain.de/login.php ein. Sie sollten daraufhin diesen Anmelde-Bildschirm sehen:</P>
<P>Wenn Sie phpWCMS selbst installiert haben, dann benutzen Sie bitte die Daten des erstellten Kontos.<BR></P></TD></TR></TBODY></TABLE></div><div align="right"><a href="#top"><img src="img/article/top_link_0.gif" border="0" alt="" /></a></div><hr><br /><table width="158" border="0" cellspacing="0" cellpadding="0" align="left" class="table_class">
<tr><td class="image_td"><a href="zoom/NF8yMTJfeFJBRUpLT1E1UC5wbmc.html" onClick="window.open('zoom/NF8yMTJfeFJBRUpLT1E1UC5wbmc.html','previewpic','width=768,height=500');return false;.html"><img src="content/images/4_212_xRAEJKOQ5P-150x.png" width="150" height="98" border="0" class="image_img" alt="" /></a></td><td><img src="img/leer.gif" width="8" height="1" alt="" /></td></tr>
<tr><td colspan="2"><img src="img/leer.gif" width="1" height="3" alt="" /></td></tr>
<tr><td align="center" bgcolor="FCFCFC" class="image_caption"><img src="img/leer.gif" width="1" height="3" alt="" /><br><img src="picture/icon_lupe_.gif" border="0" alt="" /><img src="content/gt/fb4f6e4639b2d7e2b19b7ea01fe84770.png" alt="Zoom" border="0" /><br><img src="img/leer.gif" width="1" height="3" alt="" /></td><td><img src="img/leer.gif" width="8" height="1" alt="" /></td></tr>
</table><div class="articleText"><TABLE cellSpacing=0 cellPadding=0 width="75%" border=0>
<TBODY>
<TR>
<TD>Nach dem Anmelden werden Sie zur Verwaltungsebene begrüßt: 
<P>In der linken Spalte sehen sie alle derzeit in die Verwaltungsebene eingeloggten Nutzer (in diesem Fall „redakteur“). In der roten Leiste im oberen Bereich sehen Sie die Hauptnavigation mit den Bereichen „Artikel“, „Datei“, „Nachricht“, „Chat“ und „Profil“, die im Folgenden erklärt werden. Außerdem haben Sie mit „Logout“ die Möglichkeit, die Verwaltungsebene jederzeit zu verlassen.</P>
<P>Wenn Sie sich mit einem Konto mit Administrationsrechten angemeldet haben (z.B. direkt nach der Installation) sehen Sie noch den Bereich&nbsp;<STRONG>Admin</STRONG>, in dem die Struktur&nbsp;und das Design&nbsp;Ihrer Webseite festgelegt wird.</P></TD></TR></TBODY></TABLE></div><div align="right"><a href="#top"><img src="img/article/top_link_0.gif" border="0" alt="" /></a></div><hr><br /><P>Sollten Sie sich nach einer Neuinstallation nicht anmelden können, haben Sie sehr wahrscheinlich vergessen, das Häkchen bei <EM>Create Admin Account</EM> zu setzen. Beachten Sie bitte daher den Punkt <a href="inst_de.phtml" target="_top"><STRONG>Seiteninformationen und Admin Account</STRONG></a> in der Installationsanleitung.</P>
<P>&nbsp;</P>
<table width="100%"  border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td colspan="2"><HR></td>
  </tr>
  <tr>
    <td width="50%">Artikel erstellt: 26. August 2004</td>
    <td align="right" width="50%">Letzte Änderung: 25. Januar 2005</td>
  </tr>
  <tr>
    <td colspan="2">&nbsp;</td>
  </tr>
  <tr>
    <td colspan="2" class="comment">Wenn sie einen Fehler entdecken eine Ergänzung oder Frage haben benutzen Sie bitte folgendes <a href="#" onClick="javascript:window.open('./content/pages/nachricht.htm','frage','width=400, height=250, screenX=440,screenY=200,menubar=no,statusbar=yes,scrollbar=yes,resizable=no');" target="" style="max-width:148px; overflow:hidden;"><u>formular</u></a>.<br><BR>
Hat Ihnen oder Ihrem Kunden diese Docu weitergeholfen ? Dann würde ich mich freuen wenn Sie das Projekt unterstützen würden. Bitte nutzen Sie dafür <a href="#paypal">PayPal</a> Link. Jeder Betrag ist möglich und hilft der Weiterentwicklung und Aktualisierung dieser Dokumentation.</td>
  </tr>
  <tr>

    <td colspan="2"><img src="img/leer.gif" border="0" width="10" height="10" alt="" /></td>
  </tr>
</table></td>
</tr>
<tr>
<td colspan="2" style="height:10px;"  bgcolor="#ffffff" class="footer"><table width="100%" height="20" background="img/footer.gif" cellpadding="0" cellspacing="0" border="0">
	<tr><td width="180" align="center" valign="middle"><strong>Besucher Online: <script language="JavaScript" type="text/javascript" src="./pphlogger/showhits.php?id=phpwcms&st=js&type=onlineusr"></script>
      </strong>
	</td>
	<td>
	<table width="100%"cellpadding="0" cellspacing="0" border="0">
   <tr>
    <td align="center"><a href="javascript:history.back();" target="_top" title="go back"><img src="picture/back_.gif" border="0" alt="Zurueck"><img src="content/gt/c7e1c82f133fb52f9aaa47af41a97c8b.png" alt="Zur&uuml;ck" border="0" /></a></td>
	<td align="center"><a href="sitemap_de.phtml"><img src="picture/sitemap_.gif" border="0"  alt="Sitemap"><img src="content/gt/d6ee999c57eae0a9d98b837870d624f7.png" alt="Sitemap" border="0" /></a></td>
	<td align="center"><a href="309.14.1.0.1.0.phtml" target="_blank"><img src="picture/print_.gif" border="0" alt="Drucken"><img src="content/gt/28402664cea5418ca197006e038523ec.png" alt="Drucken" border="0" /></a></td>
	<td align="center"><a href="gaestebuch.phtml"><img src="picture/icon_gaestebuch.gif" border="0" align="top" alt="Gästebuch"><img src="content/gt/f3ff723d70dc1fe73564e4c024c57156.png" alt="G&auml;stebuch" border="0" /></a></td>
	<td align="center"><a href="#" onClick="BookMark_Page();return false;" alt="" title=""><img src="picture/favoriten_.gif" border="0"  alt="Lesezeichen"><img src="content/gt/5287027c220f6dcbdffdde8d863971e2.png" alt="Lesezeichen" border="0" /></a></td>
    </tr>
</table></td>
	</tr>
</table>
<img src="img/leer.gif" border="0" width="760" height="10" alt="" />
</td>
</tr>
</table>
</body>
</html>