<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<!--

phpwcms | open source web content management system

          developed by Oliver Georgi (info@phpwcms.de)
          released under The GNU General Public License
          visit project page: http://www.phpwcms.de

          Release: 1.1.9

//-->
<html>
<head>
<title>phpwcms documentation | Replacement Tags für Grafiken</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<script src="template/inc_js/frontend.js" type="text/javascript"></script>
<link rel="stylesheet" type="text/css" href="template/inc_css/frontend.css">
<META NAME="Title" CONTENT="Die phpWCMS Dokumentation">
<meta name="author" content="Oliver Frohnert">
<meta name="Publisher" content="Oliver Frohnert">
<meta name="Copyright" content="Oliver Frohnert">
<meta name="keywords" content="frohnert,documentation, dokumentation, phpwcms, cms. opensource, open source">
<meta name="description" content="Das Dokumentations Projekt für das Open Source CMS phpWCMS">
<meta name="Audience" content="Alle">
<meta name="Content-language" content="DE">
<META NAME="robots"      CONTENT="index,follow">
<META NAME="expires" CONTENT="0">
<meta name="revisit-after" content="7 days">
<meta name="resource-type" content="document">
<meta name="distribution" content="Global">
<meta name="generator" content="PHPWCMS">
<script language="JavaScript" type="text/javascript" src="pphlogger.js"></script>
<noscript><img alt="" src="./pphlogger/pphlogger.php?id=phpwcms&st=img"></noscript>

</head>

<body bgcolor="#FFFFFF" text="#000000" link="#FF9900" vlink="#FF9900" alink="#FF9900" topmargin="0" leftmargin="0" marginwidth="0" marginheight="0">
<table border="0" cellspacing="0" cellpadding="0" width="760" bgcolor="#ffffff" class="maintable" align="center">
<tr>
<td colspan="2" style="height:60px;"  bgcolor="#ffffff"><table width="760" height="135" border="0" cellpadding="0" cellspacing="0">
  <tr valign="top">
    <td width="1334" height="122" colspan="6" background="template/lang/de/header.jpg">&nbsp;</td>
  </tr>
  <tr>
	<td height="27" background="template/lang/all/top_menu.jpg"><table width="570" border="0" align="left" cellpadding="0" cellspacing="0">
      <tr>
        <td align="center" width="254"><a href="deutsche_version.phtml"><img src="picture/flags/de.gif" width="16" height="10" hspace="10" border="0"  alt="Deutsche Version" title="Deutsche Version"></a>
<a href="english_version.phtml"><img src="picture/flags/gb.gif" width="16" height="10" hspace="10" border="0"  alt="English Version" title="English Version"></a></td>
        <td valign="middle"><div align="center"><a href="replacement_tags_de.phtml"><img src="content/gt/9ad4c84df9fc6e20be504ff61a358128.png" alt="Replacement Tags" border="0" /></a></div></td>
        <td width="30" valign="middle"><div align="center"><img src="template/lang/all/sep.gif" width="5" height="5" border="0"></div></td>
        <td valign="middle"><div align="center"><a href="content_parts_de.phtml"><img src="content/gt/0ac72fda03e1537553c1f89e3f96ad75.png" alt="Content Parts" border="0" /></a></div></td>
        <td width="30" valign="middle"><div align="center"><img src="template/lang/all/sep.gif" width="5" height="5" border="0"></div></td>
        <td valign="middle"><div align="center"><a href="links_de.phtml"><img src="content/gt/c13491df26fc7ba71211ce67d0cd7cac.png" alt="Links" border="0" /></a></div></td>
        <td width="30" valign="middle"><div align="center"><img src="template/lang/all/sep.gif" width="5 " height="5" border="0"></div></td>
        <td valign="middle"><div align="center"><a href="impressum.phtml"><img src="content/gt/304aadbbc5a74f91579640823fb3c8ab.png" alt="Impressum" border="0" /></a></div></td>
     </tr>
    </table>    </td>
  </tr>
</table></td>
</tr>
<tr>
<td valign="top" width="185" background="img/menu.gif"><table width="180" border="0" cellpadding="0" cellspacing="0">
  <tr>
    <td width="180" height="20">&nbsp;</td>
  </tr>
  <tr>
    <td style="padding-left: 7px;"><table border="0" cellspacing="0" cellpadding="0" width="100%">
<tr>
<td colspan="2"><img src="img/leer.gif" width="1" height="1" alt="" /></td><td><img src="img/leer.gif" width="1" height="1" alt="" /></td><td colspan="4"><img src="img/leer.gif" width="1" height="1" alt="" /></td><td><img src="img/leer.gif" width="1" height="1" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='news_de.phtml';return false;" onMouseOver="MM_swapImage('linkid5nl2jL','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td width="7" colspan="2"><img src="img/leer.gif" width="7" height="15" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkid5nl2jL" id="linkid5nl2jL"></td>
<td valign="top" style="height:15px;"  width="100%" class="nav_table" colspan="4"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="news_de.phtml">News</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="7"><img src="img/leer.gif" width="10" height="15" alt="" /></td>
</tr>
<tr>
<td colspan="2"><img src="img/leer.gif" width="1" height="1" alt="" /></td><td><img src="img/leer.gif" width="1" height="1" alt="" /></td><td colspan="4"><img src="img/leer.gif" width="1" height="1" alt="" /></td><td><img src="img/leer.gif" width="1" height="1" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='inst_de.phtml';return false;" onMouseOver="MM_swapImage('linkidBmY9n7','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td width="7" colspan="2"><img src="img/leer.gif" width="7" height="15" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkidBmY9n7" id="linkidBmY9n7"></td>
<td valign="top" style="height:15px;"  width="100%" class="nav_table" colspan="4"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="inst_de.phtml">Installation<img src="picture/myRT1/neuR.gif" alt="2/6/2005" border="0"></a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="7"><img src="img/leer.gif" width="10" height="15" alt="" /></td>
</tr>
<tr>
<td colspan="2"><img src="img/leer.gif" width="1" height="1" alt="" /></td><td><img src="img/leer.gif" width="1" height="1" alt="" /></td><td colspan="4"><img src="img/leer.gif" width="1" height="1" alt="" /></td><td><img src="img/leer.gif" width="1" height="1" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='verwaltung_login.phtml';return false;" onMouseOver="MM_swapImage('linkidE78sft','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td width="7" colspan="2"><img src="img/leer.gif" width="7" height="15" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkidE78sft" id="linkidE78sft"></td>
<td valign="top" style="height:15px;"  width="100%" class="nav_table" colspan="4"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="verwaltung_login.phtml">Die Docu</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="7"><img src="img/leer.gif" width="10" height="15" alt="" /></td>
</tr>
<tr>
<td colspan="3"><img src="img/leer.gif" width="1" height="1" alt="" /></td><td><img src="img/leer.gif" width="1" height="1" alt="" /></td><td colspan="3"><img src="img/leer.gif" width="1" height="1" alt="" /></td><td><img src="img/leer.gif" width="1" height="1" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='die_artikelzentrale.phtml';return false;" onMouseOver="MM_swapImage('linkidwea8nX','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td width="7" colspan="3"><img src="img/leer.gif" width="7" height="15" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkidwea8nX" id="linkidwea8nX"></td>
<td valign="top" style="height:15px;"  width="100%" class="nav_table" colspan="3"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="die_artikelzentrale.phtml">Artikel</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="7"><img src="img/leer.gif" width="10" height="15" alt="" /></td>
</tr>
<tr>
<td colspan="3"><img src="img/leer.gif" width="1" height="1" alt="" /></td><td><img src="img/leer.gif" width="1" height="1" alt="" /></td><td colspan="3"><img src="img/leer.gif" width="1" height="1" alt="" /></td><td><img src="img/leer.gif" width="1" height="1" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='dateien_hinzufuegen.phtml';return false;" onMouseOver="MM_swapImage('linkid7RiMdO','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td width="7" colspan="3"><img src="img/leer.gif" width="7" height="15" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkid7RiMdO" id="linkid7RiMdO"></td>
<td valign="top" style="height:15px;"  width="100%" class="nav_table" colspan="3"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="dateien_hinzufuegen.phtml">Datei</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="7"><img src="img/leer.gif" width="10" height="15" alt="" /></td>
</tr>
<tr>
<td colspan="3"><img src="img/leer.gif" width="1" height="1" alt="" /></td><td><img src="img/leer.gif" width="1" height="1" alt="" /></td><td colspan="3"><img src="img/leer.gif" width="1" height="1" alt="" /></td><td><img src="img/leer.gif" width="1" height="1" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='verwaltung_module.phtml';return false;" onMouseOver="MM_swapImage('linkidIV2VVB','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td width="7" colspan="3"><img src="img/leer.gif" width="7" height="15" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkidIV2VVB" id="linkidIV2VVB"></td>
<td valign="top" style="height:15px;"  width="100%" class="nav_table" colspan="3"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="verwaltung_module.phtml">Module</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="7"><img src="img/leer.gif" width="10" height="15" alt="" /></td>
</tr>
<tr>
<td colspan="3"><img src="img/leer.gif" width="1" height="1" alt="" /></td><td><img src="img/leer.gif" width="1" height="1" alt="" /></td><td colspan="3"><img src="img/leer.gif" width="1" height="1" alt="" /></td><td><img src="img/leer.gif" width="1" height="1" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='verwaltung_nachricht.phtml';return false;" onMouseOver="MM_swapImage('linkidr6bvr5','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td width="7" colspan="3"><img src="img/leer.gif" width="7" height="15" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkidr6bvr5" id="linkidr6bvr5"></td>
<td valign="top" style="height:15px;"  width="100%" class="nav_table" colspan="3"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="verwaltung_nachricht.phtml">Nachricht</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="7"><img src="img/leer.gif" width="10" height="15" alt="" /></td>
</tr>
<tr>
<td colspan="3"><img src="img/leer.gif" width="1" height="1" alt="" /></td><td><img src="img/leer.gif" width="1" height="1" alt="" /></td><td colspan="3"><img src="img/leer.gif" width="1" height="1" alt="" /></td><td><img src="img/leer.gif" width="1" height="1" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='verwaltung_chat.phtml';return false;" onMouseOver="MM_swapImage('linkidgS0zUd','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td width="7" colspan="3"><img src="img/leer.gif" width="7" height="15" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkidgS0zUd" id="linkidgS0zUd"></td>
<td valign="top" style="height:15px;"  width="100%" class="nav_table" colspan="3"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="verwaltung_chat.phtml">Chat</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="7"><img src="img/leer.gif" width="10" height="15" alt="" /></td>
</tr>
<tr>
<td colspan="3"><img src="img/leer.gif" width="1" height="1" alt="" /></td><td><img src="img/leer.gif" width="1" height="1" alt="" /></td><td colspan="3"><img src="img/leer.gif" width="1" height="1" alt="" /></td><td><img src="img/leer.gif" width="1" height="1" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='verwaltung_profil.phtml';return false;" onMouseOver="MM_swapImage('linkidMmZnkM','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td width="7" colspan="3"><img src="img/leer.gif" width="7" height="15" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkidMmZnkM" id="linkidMmZnkM"></td>
<td valign="top" style="height:15px;"  width="100%" class="nav_table" colspan="3"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="verwaltung_profil.phtml">Profil</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="7"><img src="img/leer.gif" width="10" height="15" alt="" /></td>
</tr>
<tr>
<td colspan="3"><img src="img/leer.gif" width="1" height="1" alt="" /></td><td><img src="img/leer.gif" width="1" height="1" alt="" /></td><td colspan="3"><img src="img/leer.gif" width="1" height="1" alt="" /></td><td><img src="img/leer.gif" width="1" height="1" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='verwaltung_admin.phtml';return false;" onMouseOver="MM_swapImage('linkidNfOeG6','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td width="7" colspan="3"><img src="img/leer.gif" width="7" height="15" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkidNfOeG6" id="linkidNfOeG6"></td>
<td valign="top" style="height:15px;"  width="100%" class="nav_table" colspan="3"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="verwaltung_admin.phtml">Admin<img src="picture/myRT1/neuR.gif" alt="1/16/2005" border="0"></a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="7"><img src="img/leer.gif" width="10" height="15" alt="" /></td>
</tr>
<tr>
<td colspan="4"><img src="img/leer.gif" width="1" height="1" alt="" /></td><td><img src="img/leer.gif" width="1" height="1" alt="" /></td><td colspan="2"><img src="img/leer.gif" width="1" height="1" alt="" /></td><td><img src="img/leer.gif" width="1" height="1" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='seitenstruktur.phtml';return false;" onMouseOver="MM_swapImage('linkidJflCHC','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td width="7" colspan="4"><img src="img/leer.gif" width="7" height="15" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkidJflCHC" id="linkidJflCHC"></td>
<td valign="top" style="height:15px;"  width="100%" class="nav_table" colspan="2"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="seitenstruktur.phtml">Seitenstruktur<img src="picture/myRT1/neuR.gif" alt="1/16/2005" border="0"></a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="7"><img src="img/leer.gif" width="10" height="15" alt="" /></td>
</tr>
<tr>
<td colspan="4"><img src="img/leer.gif" width="1" height="1" alt="" /></td><td><img src="img/leer.gif" width="1" height="1" alt="" /></td><td colspan="2"><img src="img/leer.gif" width="1" height="1" alt="" /></td><td><img src="img/leer.gif" width="1" height="1" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='benutzerverwaltung.phtml';return false;" onMouseOver="MM_swapImage('linkidTmRLwq','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td width="7" colspan="4"><img src="img/leer.gif" width="7" height="15" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkidTmRLwq" id="linkidTmRLwq"></td>
<td valign="top" style="height:15px;"  width="100%" class="nav_table" colspan="2"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="benutzerverwaltung.phtml">Benutzerverwaltung<img src="picture/myRT1/neuR.gif" alt="1/16/2005" border="0"></a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="7"><img src="img/leer.gif" width="10" height="15" alt="" /></td>
</tr>
<tr>
<td colspan="4"><img src="img/leer.gif" width="1" height="1" alt="" /></td><td><img src="img/leer.gif" width="1" height="1" alt="" /></td><td colspan="2"><img src="img/leer.gif" width="1" height="1" alt="" /></td><td><img src="img/leer.gif" width="1" height="1" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='replacement_tags_de.phtml';return false;" onMouseOver="MM_swapImage('linkidLFMNqb','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td width="7" colspan="4"><img src="img/leer.gif" width="7" height="15" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkidLFMNqb" id="linkidLFMNqb"></td>
<td valign="top" style="height:15px;"  width="100%" class="nav_table" colspan="2"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="replacement_tags_de.phtml">Replacement-Tags</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="7"><img src="img/leer.gif" width="10" height="15" alt="" /></td>
</tr>
<tr>
<td colspan="5"><img src="img/leer.gif" width="1" height="1" alt="" /></td><td><img src="img/leer.gif" width="1" height="1" alt="" /></td><td><img src="img/leer.gif" width="1" height="1" alt="" /></td><td><img src="img/leer.gif" width="1" height="1" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='system_tags_.phtml';return false;" onMouseOver="MM_swapImage('linkidhnXXiX','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td width="7" colspan="5"><img src="img/leer.gif" width="7" height="15" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkidhnXXiX" id="linkidhnXXiX"></td>
<td valign="top" style="height:15px;"  width="100%" class="nav_table"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="system_tags_.phtml">System Tags</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="7"><img src="img/leer.gif" width="10" height="15" alt="" /></td>
</tr>
<tr>
<td colspan="5"><img src="img/leer.gif" width="1" height="1" alt="" /></td><td><img src="img/leer.gif" width="1" height="1" alt="" /></td><td><img src="img/leer.gif" width="1" height="1" alt="" /></td><td><img src="img/leer.gif" width="1" height="1" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='navigations_tags_.phtml';return false;" onMouseOver="MM_swapImage('linkidMl8RSG','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td width="7" colspan="5"><img src="img/leer.gif" width="7" height="15" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkidMl8RSG" id="linkidMl8RSG"></td>
<td valign="top" style="height:15px;"  width="100%" class="nav_table"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="navigations_tags_.phtml">Navigations Tags</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="7"><img src="img/leer.gif" width="10" height="15" alt="" /></td>
</tr>
<tr>
<td colspan="5"><img src="img/leer.gif" width="1" height="1" alt="" /></td><td><img src="img/leer.gif" width="1" height="1" alt="" /></td><td><img src="img/leer.gif" width="1" height="1" alt="" /></td><td><img src="img/leer.gif" width="1" height="1" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='link_tags_.phtml';return false;" onMouseOver="MM_swapImage('linkidjNTveU','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td width="7" colspan="5"><img src="img/leer.gif" width="7" height="15" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkidjNTveU" id="linkidjNTveU"></td>
<td valign="top" style="height:15px;"  width="100%" class="nav_table"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="link_tags_.phtml">Link Tags</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="7"><img src="img/leer.gif" width="10" height="15" alt="" /></td>
</tr>
<tr>
<td colspan="5"><img src="img/leer.gif" width="1" height="1" alt="" /></td><td><img src="img/leer.gif" width="1" height="1" alt="" /></td><td><img src="img/leer.gif" width="1" height="1" alt="" /></td><td><img src="img/leer.gif" width="1" height="1" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='grafik_tags.phtml';return false;">
<td width="7" colspan="5"><img src="img/leer.gif" width="7" height="15" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_2" alt="" border="" name="linkidUADi7X" id="linkidUADi7X"></td>
<td valign="top" style="height:15px;"  width="100%" class="nav_table_active"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="grafik_tags.phtml">Grafik Tags</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="7"><img src="img/leer.gif" width="10" height="15" alt="" /></td>
</tr>
<tr>
<td colspan="5"><img src="img/leer.gif" width="1" height="1" alt="" /></td><td><img src="img/leer.gif" width="1" height="1" alt="" /></td><td><img src="img/leer.gif" width="1" height="1" alt="" /></td><td><img src="img/leer.gif" width="1" height="1" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='artikel_tags.phtml';return false;" onMouseOver="MM_swapImage('linkidAH73RQ','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td width="7" colspan="5"><img src="img/leer.gif" width="7" height="15" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkidAH73RQ" id="linkidAH73RQ"></td>
<td valign="top" style="height:15px;"  width="100%" class="nav_table"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="artikel_tags.phtml">Artikel Tags</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="7"><img src="img/leer.gif" width="10" height="15" alt="" /></td>
</tr>
<tr>
<td colspan="5"><img src="img/leer.gif" width="1" height="1" alt="" /></td><td><img src="img/leer.gif" width="1" height="1" alt="" /></td><td><img src="img/leer.gif" width="1" height="1" alt="" /></td><td><img src="img/leer.gif" width="1" height="1" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='spracheinstellungen.phtml';return false;" onMouseOver="MM_swapImage('linkidDrqGeL','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td width="7" colspan="5"><img src="img/leer.gif" width="7" height="15" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkidDrqGeL" id="linkidDrqGeL"></td>
<td valign="top" style="height:15px;"  width="100%" class="nav_table"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="spracheinstellungen.phtml">Spracheinstellungen</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="7"><img src="img/leer.gif" width="10" height="15" alt="" /></td>
</tr>
<tr>
<td colspan="2"><img src="img/leer.gif" width="1" height="1" alt="" /></td><td><img src="img/leer.gif" width="1" height="1" alt="" /></td><td colspan="4"><img src="img/leer.gif" width="1" height="1" alt="" /></td><td><img src="img/leer.gif" width="1" height="1" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='add_on.phtml';return false;" onMouseOver="MM_swapImage('linkideJVrHh','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td width="7" colspan="2"><img src="img/leer.gif" width="7" height="15" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkideJVrHh" id="linkideJVrHh"></td>
<td valign="top" style="height:15px;"  width="100%" class="nav_table" colspan="4"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="add_on.phtml">Add Ons</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="7"><img src="img/leer.gif" width="10" height="15" alt="" /></td>
</tr>
<tr>
<td colspan="2"><img src="img/leer.gif" width="1" height="1" alt="" /></td><td><img src="img/leer.gif" width="1" height="1" alt="" /></td><td colspan="4"><img src="img/leer.gif" width="1" height="1" alt="" /></td><td><img src="img/leer.gif" width="1" height="1" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='fehlermeldungen.phtml';return false;" onMouseOver="MM_swapImage('linkido12uYI','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td width="7" colspan="2"><img src="img/leer.gif" width="7" height="15" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkido12uYI" id="linkido12uYI"></td>
<td valign="top" style="height:15px;"  width="100%" class="nav_table" colspan="4"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="fehlermeldungen.phtml">Fehlermeldungen</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="7"><img src="img/leer.gif" width="10" height="15" alt="" /></td>
</tr>
<tr>
<td colspan="2"><img src="img/leer.gif" width="1" height="1" alt="" /></td><td><img src="img/leer.gif" width="1" height="1" alt="" /></td><td colspan="4"><img src="img/leer.gif" width="1" height="1" alt="" /></td><td><img src="img/leer.gif" width="1" height="1" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='suche.phtml';return false;" onMouseOver="MM_swapImage('linkidsLwDqQ','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td width="7" colspan="2"><img src="img/leer.gif" width="7" height="15" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkidsLwDqQ" id="linkidsLwDqQ"></td>
<td valign="top" style="height:15px;"  width="100%" class="nav_table" colspan="4"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="suche.phtml">Suche</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="7"><img src="img/leer.gif" width="10" height="15" alt="" /></td>
</tr>
<tr>
<td colspan="2"><img src="img/leer.gif" width="1" height="1" alt="" /></td><td><img src="img/leer.gif" width="1" height="1" alt="" /></td><td colspan="4"><img src="img/leer.gif" width="1" height="1" alt="" /></td><td><img src="img/leer.gif" width="1" height="1" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='kontakt.phtml';return false;" onMouseOver="MM_swapImage('linkidaMmgCO','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td width="7" colspan="2"><img src="img/leer.gif" width="7" height="15" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkidaMmgCO" id="linkidaMmgCO"></td>
<td valign="top" style="height:15px;"  width="100%" class="nav_table" colspan="4"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="kontakt.phtml">Kontakt</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="7"><img src="img/leer.gif" width="10" height="15" alt="" /></td>
</tr>
</table></td>
  </tr>
   <tr>
    <td style="padding:10px; color:#000000;"><img src="picture/seperate.gif" border="0" alt="" /><P>
	<a href="deutsche_version.phtml?id=285,212,0,0,1,0">Letzte Version:<br>
RC 1.1 - 27.08.2004a<br>
Vö: 6.11.2004<P>
Letzter Patch:<BR>
26.11.2004</a><P>
<img src="picture/seperate.gif" border="0" alt="" /></TD>
  </tr>
  <tr>
    <td align="center">&nbsp;<BR>WERBUNG<BR><BR><img src="picture/seperate.gif" border="0" alt="" /><P>
</td>
  </tr>
<tr>
    <td height="20">&nbsp;</td>
  </tr>
  <tr>
    <td align="center"></td>
  </tr>
  <tr>
    <td height="20">&nbsp;</td>
  </tr>
</table>


</body>
</html>
</td>
<td valign="top" width="555" bgcolor="#ffffff" class="maincontent"><img src="img/leer.gif" border="0" width="10" height="1" alt="" />
<BR>
<a href="deutsche_version.phtml">Deutsch</a> <span class="breadcrumb_spacer">&gt;</span> <a href="verwaltung_login.phtml">Die Docu</a> <span class="breadcrumb_spacer">&gt;</span> <a href="verwaltung_admin.phtml">Admin<img src="picture/myRT1/neuR.gif" alt="1/16/2005" border="0"></a> <span class="breadcrumb_spacer">&gt;</span> <a href="replacement_tags_de.phtml">Replacement-Tags</a> <span class="breadcrumb_spacer">&gt;</span> Grafik Tags
<br>
<HR>
<br>
<a name="jump44"></a><span class="articleHead">Replacement Tags für Grafiken</span><img src="img/leer.gif" width="1" height="8" alt=""><br /><img src="img/leer.gif" width="1" height="25" alt="" /><br><span class="contentHead">HINWEIS</span><br><img src="img/leer.gif" width="1" height="3" alt="">Alle Image Tags beziehen sich auf das Verzeichnis "Picture". Wenn Sie aus einem anderen Ordner Bilder mit dem Image Tag aufrufen wollen muß der Link z.b. so aussehen {<img src="img/leer.gif" border="0" width="1" height="1" alt="" />IMAGE:../content/images/image.jpg}<div align="right"><a href="#top"><img src="img/article/top_link_0.gif" border="0" alt="" /></a></div><br><span class="contentSubHead">{<img src="img/leer.gif" border="0" width="1" height="1" alt="" />IMAGE:Imagename}</span><br><img src="img/leer.gif" width="1" height="2" alt=""><TABLE cellSpacing=0 cellPadding=5 width="100%" border=0>
<TBODY bgColor=#efefef>
<TR>
<TD vAlign=top align=right width=100><FONT class=v10 color=#666666><STRONG>Verwendung:</STRONG></FONT></TD>
<TD width=5 rowSpan=5></TD>
<TD vAlign=top>Erzeugt ein <EM>&lt;img&gt;-Tag</EM> mit der angegebenen Bilddatei.</TD></TR>
<TR>
<TD vAlign=top align=right width=100><FONT class=v10 color=#666666><STRONG>Schreibweise:</STRONG></FONT></TD>
<TD vAlign=top><STRONG>{<img src="img/leer.gif" border="0" width="1" height="1" alt="" />IMAGE:icon/DateiDownload.jpg}</STRONG></TD></TR>
<TR>
<TD vAlign=top align=right width=100><STRONG><FONT color=#666666 size=1>Anzeige:</FONT></STRONG></TD>
<TD vAlign=top><img src="picture/icon/DateiDownload.jpg" border="0" alt="" /></TD></TR>
<TR>
<TD vAlign=top align=right width=100><FONT class=v10 color=#666666><STRONG>Bemerkung:</STRONG></FONT></TD>
<TD vAlign=top>
<P dir=ltr style="MARGIN-RIGHT: 0px">Das Verzeichnis <STRONG>icon</STRONG> liegt unmittelbar unterhalb&nbsp;von <STRONG>picture.</STRONG><BR>Der komplette Pfadname zur Bilddatei ist in diesem Fall:<BR><BR><EM>www.meine-domain.de/picture/icon/DateiDownload.jpg</EM></P></TD></TR>
<TR>
<TD vAlign=top align=right width=100><FONT class=v10 color=#666666><STRONG><EM></EM></STRONG></FONT></TD>
<TD vAlign=top><EM></EM></TD></TR></TBODY></TABLE>&nbsp;<BR><div align="right"><a href="#top"><img src="img/article/top_link_0.gif" border="0" alt="" /></a></div><br><span class="contentSubHead">{<img src="img/leer.gif" border="0" width="1" height="1" alt="" />IMAGE_LEFT:imagename}</span><br><img src="img/leer.gif" width="1" height="2" alt=""><TABLE cellSpacing=0 cellPadding=5 width="100%" border=0>
<TBODY bgColor=#efefef>
<TR>
<TD vAlign=top align=right width=100><FONT class=v10 color=#666666><STRONG>Verwendung:</STRONG></FONT></TD>
<TD width=5 rowSpan=5></TD>
<TD vAlign=top>Erzeugt ein <EM>&lt;img&gt;-Tag</EM> mit der angegebenen Bilddatei.<BR>Das Bild wird <EM>linksbündig</EM> ausgerichtet.</TD></TR>
<TR>
<TD vAlign=top align=right width=100><FONT class=v10 color=#666666><STRONG>Schreibweise:</STRONG></FONT></TD>
<TD vAlign=top><STRONG>{<img src="img/leer.gif" border="0" width="1" height="1" alt="" />IMAGE_LEFT:Jaguar.jpg}</STRONG></TD></TR>
<TR>
<TD vAlign=top align=right width=100><STRONG><FONT color=#666666 size=1>Anzeige:</FONT></STRONG></TD>
<TD vAlign=top><img src="picture/Jaguar.jpg" border="0" align="left" alt="" /></TD></TR>
<TR>
<TD vAlign=top align=right width=100><FONT class=v10 color=#666666><STRONG>Bemerkung:</STRONG></FONT></TD>
<TD vAlign=top>
<P dir=ltr style="MARGIN-RIGHT: 0px">Das Bild <STRONG>Jaguar.jpg</STRONG> liegt&nbsp;im Verzeichnis <STRONG>picture.</STRONG><BR>Der komplette Pfadname zur Bilddatei ist in diesem Fall:<BR><BR><EM>www.meine-domain.de/picture/Jaguar.jpg</EM></P></TD></TR>
<TR>
<TD vAlign=top align=right width=100><FONT class=v10 color=#666666><STRONG></STRONG></FONT></TD>
<TD vAlign=top></TD></TR></TBODY></TABLE>&nbsp;<BR><div align="right"><a href="#top"><img src="img/article/top_link_0.gif" border="0" alt="" /></a></div><br><span class="contentSubHead">{<img src="img/leer.gif" border="0" width="1" height="1" alt="" />IMAGE_RIGHT:Imagename}</span><br><img src="img/leer.gif" width="1" height="2" alt=""><TABLE cellSpacing=0 cellPadding=5 width="100%" border=0>
<TBODY bgColor=#efefef>
<TR>
<TD vAlign=top align=right width=100><FONT class=v10 color=#666666><STRONG>Verwendung:</STRONG></FONT></TD>
<TD width=5 rowSpan=5></TD>
<TD vAlign=top>Erzeugt ein <EM>&lt;img&gt;-Tag</EM> mit der angegebenen Bilddatei.<BR>Das Bild wird <EM>rechtsbündig </EM>ausgerichtet.</TD></TR>
<TR>
<TD vAlign=top align=right width=100><FONT class=v10 color=#666666><STRONG>Schreibweise:</STRONG></FONT></TD>
<TD vAlign=top><STRONG>{<img src="img/leer.gif" border="0" width="1" height="1" alt="" />IMAGE_RIGHT:Blatt.jpg}</STRONG></TD></TR>
<TR>
<TD vAlign=top align=right width=100><STRONG><FONT color=#666666 size=1>Anzeige:</FONT></STRONG></TD>
<TD vAlign=top><img src="picture/Blatt.jpg" border="0" align="right" alt="" /></TD></TR>
<TR>
<TD vAlign=top align=right width=100><FONT class=v10 color=#666666><STRONG>Bemerkung:</STRONG></FONT></TD>
<TD vAlign=top>
<P dir=ltr style="MARGIN-RIGHT: 0px">Das Bild <STRONG>Blatt.jpg</STRONG> liegt&nbsp;im Verzeichnis <STRONG>picture.</STRONG><BR>Der komplette Pfadname zur Bilddatei ist in diesem Fall:<BR><BR><EM>www.meine-domain.de/picture/Blatt.jpg</EM></P></TD></TR>
<TR>
<TD vAlign=top align=right width=100><FONT class=v10 color=#666666><STRONG></STRONG></FONT></TD>
<TD vAlign=top></TD></TR></TBODY></TABLE>&nbsp;<BR><div align="right"><a href="#top"><img src="img/article/top_link_0.gif" border="0" alt="" /></a></div><br><span class="contentSubHead">{<img src="img/leer.gif" border="0" width="1" height="1" alt="" />RANDOM:Image_Pfad}</span><br><img src="img/leer.gif" width="1" height="2" alt=""><TABLE cellSpacing=0 cellPadding=5 width="100%" border=0>
<TBODY bgColor=#efefef>
<TR>
<TD vAlign=top align=right width=100><FONT class=v10 color=#666666><STRONG>Verwendung:</STRONG></FONT></TD>
<TD width=5 rowSpan=5></TD>
<TD vAlign=top>Erzeugt ein <EM>&lt;img&gt;-Tag</EM> für Zufallsbilder aus dem angegebenen Verzeichnis.&nbsp;<BR>Bei jedem&nbsp;Seitenaufruf wird ein anders Zufallsbild angezeigt.</TD></TR>
<TR>
<TD vAlign=top align=right width=100><FONT class=v10 color=#666666><STRONG>Schreibweise:</STRONG></FONT></TD>
<TD vAlign=top><STRONG>{<img src="img/leer.gif" border="0" width="1" height="1" alt="" />RANDOM:picture/random_175}</STRONG></TD></TR>
<TR>
<TD vAlign=top align=right width=100><STRONG><FONT color=#666666 size=1>Anzeige:</FONT></STRONG></TD>
<TD vAlign=top><img src="picture/random_175/Wien3305-phpwcms-175.JPG" width="175" height="131" border="0" alt="Wien3305-phpwcms-175.JPG" /></TD></TR>
<TR>
<TD vAlign=top align=right width=100><FONT class=v10 color=#666666><STRONG>Bemerkung:</STRONG></FONT></TD>
<TD vAlign=top>
<P dir=ltr style="MARGIN-RIGHT: 0px">Das Verzeichnis <STRONG>random_175</STRONG> ist ein Unterverzeichnis von <STRONG>picture.</STRONG><BR>Der komplette Pfadname&nbsp;zu den Random-Bildern ist:<BR><BR><EM>www.meine-domain.de/picture/random_175/</EM></P></TD></TR>
<TR>
<TD vAlign=top align=right width=100><FONT class=v10 color=#666666><STRONG></STRONG></FONT></TD>
<TD vAlign=top>Der Bildvorrat des Random-Ordners sollte nur Bilder mit der gleichen Abmessung beinhalten!&nbsp;<BR>Die Bilder werden unmittelbar aus dem Verzeichnis geladen und nicht neu vom Programm berechnet.</TD></TR></TBODY></TABLE>&nbsp;<BR><div align="right"><a href="#top"><img src="img/article/top_link_0.gif" border="0" alt="" /></a></div><br><span class="contentSubHead">{<img src="img/leer.gif" border="0" width="1" height="1" alt="" />SPACER:px-Breite x px-Hoehe}</span><br><img src="img/leer.gif" width="1" height="2" alt=""><TABLE cellSpacing=0 cellPadding=5 width="100%" border=0>
<TBODY bgColor=#efefef>
<TR>
<TD vAlign=top align=right width=100><FONT class=v10 color=#666666><STRONG>Verwendung:</STRONG></FONT></TD>
<TD width=5 rowSpan=5></TD>
<TD vAlign=top>Ausgabe eines grafischen Abstandselements zum Erzeugen einer "freien Fläche". Eingabe von Breite und Höhe in Pixeln.</TD></TR>
<TR>
<TD vAlign=top align=right width=100><FONT class=v10 color=#666666><STRONG>Schreibweise:</STRONG></FONT></TD>
<TD vAlign=top><STRONG>{<img src="img/leer.gif" border="0" width="1" height="1" alt="" />SPACER:250x5}<BR></STRONG><BR><BR><STRONG>Beispiel:<BR></STRONG><BR>ANFANG <STRONG>-|</STRONG>{<img src="img/leer.gif" border="0" width="1" height="1" alt="" />SPACER:250x5}<STRONG>|-</STRONG> ENDE</TD></TR>
<TR>
<TD vAlign=top align=right width=100><STRONG><FONT color=#666666 size=1>Anzeige:</FONT></STRONG></TD>
<TD vAlign=top>ANFANG <STRONG>-|</STRONG><img src="img/leer.gif" border="0" width="250" height="5" alt="" /><STRONG>|-</STRONG> ENDE&nbsp;</TD></TR>
<TR>
<TD vAlign=top align=right width=100><FONT class=v10 color=#666666><STRONG>Bemerkung:</STRONG></FONT></TD>
<TD vAlign=top>Der Zwischenraum zwischen den beiden Marken <STRONG>-|</STRONG> und <STRONG>|-</STRONG>&nbsp;wurde&nbsp;hier mit <STRONG>exakt 250 Pixeln</STRONG> festgelegt.</TD></TR>
<TR>
<TD vAlign=top align=right width=100><FONT class=v10 color=#666666><STRONG></STRONG></FONT></TD>
<TD vAlign=top></TD></TR></TBODY></TABLE>&nbsp;<BR><div align="right"><a href="#top"><img src="img/article/top_link_0.gif" border="0" alt="" /></a></div>
<table width="100%"  border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td colspan="2"><HR></td>
  </tr>
  <tr>
    <td width="50%">Artikel erstellt: 18.August 2004</td>
    <td align="right" width="50%">Letzte Änderung: 25.Januar 2005</td>
  </tr>
  <tr>
    <td colspan="2">&nbsp;</td>
  </tr>
  <tr>
    <td colspan="2" class="comment">Wenn sie einen Fehler entdecken eine Ergänzung oder Frage haben benutzen Sie bitte folgendes <a href="#" onClick="javascript:window.open('./content/pages/nachricht.htm','frage','width=400, height=250, screenX=440,screenY=200,menubar=no,statusbar=yes,scrollbar=yes,resizable=no');" target="" style="max-width:148px; overflow:hidden;"><u>formular</u></a>.<br><BR>
Hat Ihnen oder Ihrem Kunden diese Docu weitergeholfen ? Dann würde ich mich freuen wenn Sie das Projekt unterstützen würden. Bitte nutzen Sie dafür <a href="#paypal">PayPal</a> Link. Jeder Betrag ist möglich und hilft der Weiterentwicklung und Aktualisierung dieser Dokumentation.</td>
  </tr>
  <tr>

    <td colspan="2"><img src="img/leer.gif" border="0" width="10" height="10" alt="" /></td>
  </tr>
</table></td>
</tr>
<tr>
<td colspan="2" style="height:10px;"  bgcolor="#ffffff" class="footer"><table width="100%" height="20" background="img/footer.gif" cellpadding="0" cellspacing="0" border="0">
	<tr><td width="180" align="center" valign="middle"><strong>Besucher Online: <script language="JavaScript" type="text/javascript" src="./pphlogger/showhits.php?id=phpwcms&st=js&type=onlineusr"></script>
      </strong>
	</td>
	<td>
	<table width="100%"cellpadding="0" cellspacing="0" border="0">
   <tr>
    <td align="center"><a href="javascript:history.back();" target="_top" title="go back"><img src="picture/back_.gif" border="0" alt="Zurueck"><img src="content/gt/c7e1c82f133fb52f9aaa47af41a97c8b.png" alt="Zur&uuml;ck" border="0" /></a></td>
	<td align="center"><a href="sitemap_de.phtml"><img src="picture/sitemap_.gif" border="0"  alt="Sitemap"><img src="content/gt/d6ee999c57eae0a9d98b837870d624f7.png" alt="Sitemap" border="0" /></a></td>
	<td align="center"><a href="96.44.1.0.1.0.phtml" target="_blank"><img src="picture/print_.gif" border="0" alt="Drucken"><img src="content/gt/28402664cea5418ca197006e038523ec.png" alt="Drucken" border="0" /></a></td>
	<td align="center"><a href="gaestebuch.phtml"><img src="picture/icon_gaestebuch.gif" border="0" align="top" alt="Gästebuch"><img src="content/gt/f3ff723d70dc1fe73564e4c024c57156.png" alt="G&auml;stebuch" border="0" /></a></td>
	<td align="center"><a href="#" onClick="BookMark_Page();return false;" title=""><img src="picture/favoriten_.gif" border="0"  alt="Lesezeichen"><img src="content/gt/5287027c220f6dcbdffdde8d863971e2.png" alt="Lesezeichen" border="0" /></a></td>
    </tr>
</table></td>
	</tr>
</table>
<img src="img/leer.gif" border="0" width="760" height="10" alt="" />
</td>
</tr>
</table>
</body>
</html>