<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<!--
	phpwcms | free open source content management system
	created by Oliver Georgi (oliver at phpwcms dot de) and licensed under GNU/GPL.
	phpwcms is copyright 2003-2007 of Oliver Georgi. Extensions are copyright of
	their respective owners. Visit project page for details: http://www.phpwcms.org/
//-->
<title>phpwcms-docu for  phpwcms :: web based content management system | Grafik Tags | Replacement Tags für Grafiken</title>
  <meta http-equiv="content-type" content="text/html; charset=iso-8859-1" />
  <meta http-equiv="content-style-type" content="text/css" />
  <script src="template/inc_js/frontend.js" type="text/javascript"></script>
  <style type="text/css">
  <!-- 
    @import url("template/inc_css/mpl_docu.css");
    @import url("template/inc_css/mpl_frontend.css");
    @import url("template/inc_css/mpl_menu.css");
    @import url("template/inc_css/mpl_objects.css");
  //-->
  </style>
<script type="text/javascript" language="javascript">
<!--
function MM_jumpMenu(targ,selObj,restore){ //v3.0
  eval(targ+".location='"+selObj.options[selObj.selectedIndex].value+"'");
  if (restore) selObj.selectedIndex=0;
}

function MM_findObj(n, d) { //v4.01
  var p,i,x;  if(!d) d=document; if((p=n.indexOf("?"))>0&&parent.frames.length) {
    d=parent.frames[n.substring(p+1)].document; n=n.substring(0,p);}
  if(!(x=d[n])&&d.all) x=d.all[n]; for (i=0;!x&&i<d.forms.length;i++) x=d.forms[i][n];
  for(i=0;!x&&d.layers&&i<d.layers.length;i++) x=MM_findObj(n,d.layers[i].document);
  if(!x && d.getElementById) x=d.getElementById(n); return x;
}

function MM_jumpMenuGo(selName,targ,restore){ //v3.0
  var selObj = MM_findObj(selName); if (selObj) MM_jumpMenu(targ,selObj,restore);
}
//-->
</script>
<meta name="Title" content="Die phpWCMS Dokumentation" />
<meta name="author" content="Oliver Frohnert, Mario Perez Leal" />
<meta name="Publisher" content="Oliver Frohnert, Mario Perez Leal, creacion" />
<meta name="Copyright" content="Oliver Frohnert, Mario Perez Leal, creacion" />
<meta name="keywords" content="frohnert, perez leal, creacion, documentation, dokumentation, phpwcms, cms, opensource, open source, docu" />
<meta name="description" content="Das Dokumentations Projekt für das Open Source CMS phpWCMS" />
<meta name="Audience" content="Alle" />
<meta name="Content-language" content="DE" />
<meta name="robots" content="index,follow" />
<meta name="expires" content="0" />
<meta name="revisit-after" content="7 days" />
<meta name="resource-type" content="document" />
<meta name="distribution" content="Global" />
<meta name="generator" content="PHPWCMS" />
<meta name="verify-v1" content="1ZpxZ7AZsjm7PxjqXQVus0eiUYqOsp5URTJn9q4KNz8=" />
  <!--[if lt IE 7]>
  <style type="text/css">
    body { behavior: url("template/inc_css/specific/csshover2.htc"); }
    img { behavior: url("template/inc_css/specific/pngbehavior.htc"); }
  </style>
  <![endif]-->
</head>
<body id="myid_96">
<div id="container"><a name="top" id="top"></a>


	<div id="head">
		
	<div id="mainnavi">
		<div class="fleft"><a href="deutsche_version.phtml">Startseite</a> | <a href="news_de.phtml">News</a> | <span style="text-decoration:none;font-weight:bold;"><a href="die_docu.phtml">Die Docu</a></span> | <a href="Nuetzliche_Links_und_Tools.phtml">Links &amp; Tools</a> | <a href="downloads.phtml">Downloads</a> | <a href="kontakt.phtml">Kontakt</a> | <a href="faq_de.phtml">FAQ</a> | <a href="http://forum.phpwcms.org/" target="_blank">Forum</a> | <a href="howto_de.phtml">HowTo</a></div>				
		<div class="sys">Sonntag, 17. November 2013<img src="img/leer.gif" border="0" width="5" height="1" alt="" />|<img src="img/leer.gif" border="0" width="5" height="1" alt="" />2 User online<img src="img/leer.gif" border="0" width="10" height="1" alt="" />
		<a href="deutsche_version.phtml" title="Deutsche Version"><img src="picture/../template/lang/all/flag_de.gif" border="0" alt="" /></a>
		<a href="english_version.phtml"  title="English version"><img src="picture/../template/lang/all/flag_en.gif" border="0" alt="" /></a>
		</div>
	</div>
	
	<a href="./" title="phpwcms-docu Startseite aufrufen" class="homelink">
	<span>&raquo; Zur phpwcms-docu Startseite</span></a>
	<h2>phpwcms-docu - Die Dokumentation f&uuml;r f&uuml;r das CMS phpWCMS</h2>
	<p>phpwcms-docu ist eine Art Kompass, der Ihnen die M&ouml;glichkeiten von phpWcms aufzeigt und Sie erfolgreich, ohne gro&szlig;e Umwege, zu Ihrer fertigen Web-Anwendung f&uuml;hren soll.
	</p>
	</div>

	
	<div id="left">
	<div class="leftnav" style="margin-top:24px;">
	
<div id="ul_div_309">
<ul>
	<li class="sub_no"><a href="download-dev-versionen.phtml">Download Dev Versionen</a></li>
	<li class="sub_no sub_ul_true"><a href="installation_und_upgrade_von_phpwcms.phtml">Installation &amp; Upgrade</a></li>
	<li class="sub_no sub_ul_true"><a href="verwaltung_artikel.phtml">Artikel</a></li>
	<li class="sub_no sub_ul_true"><a href="dateizentrale.phtml">Datei</a></li>
	<li class="sub_no sub_ul_true"><a href="verwaltung_module.phtml">Module</a></li>
	<li class="sub_no sub_ul_true"><a href="Kommunikation.phtml">Kommunikation</a></li>
	<li class="sub_no"><a href="verwaltung_nachricht.phtml">Nachricht</a></li>
	<li class="sub_no"><a href="verwaltung_chat.phtml">Chat</a></li>
	<li class="sub_no"><a href="verwaltung_profil.phtml">Profil</a></li>
	<li class="sub_ul"><a href="verwaltung_admin.phtml">Admin</a>
	<div id="ul_div_81">
	<ul>
		<li class="sub_no sub_ul_true"><a href="seitenstruktur.phtml">Seitenstruktur</a></li>
		<li class="sub_no"><a href="seitenlayout.phtml">Seitenlayout</a></li>
		<li class="sub_no"><a href="vorlagen_de.phtml">Vorlagen</a></li>
		<li class="sub_no"><a href="standard_css.phtml">Standard CSS</a></li>
		<li class="sub_no sub_ul_true"><a href="benutzerverwaltung.phtml">Benutzerverwaltung</a></li>
		<li class="sub_no"><a href="keywords_de.phtml"><span style="text-decoration:line-through;font-size:10px;">Keywords</span></a></li>
		<li class="sub_no"><a href="dateikategorien.phtml"><span style="text-decoration:line-through;font-size:10px;">Dateikategorien</span></a></li>
		<li class="sub_no"><a href="backend_standardtext.phtml">Backend Standardtext</a></li>
		<li class="sub_no"><a href="cache_zuruecksetzten.phtml">Cache zurücksetzten</a></li>
		<li class="sub_no"><a href="cache_loeschen.phtml">Cache löschen</a></li>
		<li class="sub_no"><a href="dateien_final_loeschen.phtml">Dateien final löschen</a></li>
		<li class="sub_ul"><a href="replacement_tags_de.phtml">Replacement-Tags</a>
		<div id="ul_div_69">
		<ul>
			<li class="sub_no"><a href="system_tags_.phtml">System Tags</a></li>
			<li class="sub_no"><a href="navigations_tags_.phtml">Navigations Tags</a></li>
			<li class="sub_no"><a href="link_tags_.phtml">Link Tags</a></li>
			<li class="sub_no active"><a href="grafik_tags.phtml">Grafik Tags</a></li>
			<li class="sub_no"><a href="artikel_tags.phtml">Artikel Tags</a></li>
			<li class="sub_no"><a href="spracheinstellungen.phtml">Spracheinstellungen<br /></a></li>
		</ul>
		</div>
		</li>
	</ul>
	</div>
	</li>
	<li class="sub_no sub_ul_true"><a href="add-on-und-vorlagen.phtml">Add Ons und Vorlagen</a></li>
	<li class="sub_no"><a href="deutsche_version.phtml?replacement_tags_de">Replacement Tags</a></li>
	<li class="sub_no"><a href="deutsche_version.phtml?content_parts_de">Content Parts</a></li>
</ul>
</div>

		
		
		

	</div> 
	</div> 
	  
	<div id="right">
		<div style="margin-top:24px;">			
		<form action="index.php?suche" method="post" name="searchFE" onsubmit="s=document.getElementById('customSearchInput');if(s.value=='Suchen')return false;">
			<table width="100%" border="0" cellpadding="0" cellspacing="0">
			<tr>
					<td><input type="text" name="search_input_field" size="20" maxlength="200" id="customSearchInput" class="customSearchInput" value="" onfocus="if(this.value=='Suchen')this.value='';" onblur="if(this.value=='')this.value='Suchen';" /></td>
					<td><input type="image" name="search_go" onfocus="this.blur();" title="Suchen" src="/template/lang/all/submit.gif" /></td>
				</tr>
			</table>
			</form>
			
			      <script type="text/javascript" language="javascript">
			  <!-- 
			        document.getElementById("customSearchInput").value="Suchen";
			  //-->
			      </script>
				  
			<!-- <p style="margin-top:10px;">Schriftgrad &auml;ndern: <a href="[FontSize-]"><img src="template/lang/all/icons/reduce.gif" width="18" height="17" alt="" title="Verkleinern" border="0" /></a>
			<a href="[FontSize+]"><img src="template/lang/all/icons/extend.gif" width="18" height="17" alt="" title="Vergr&ouml;&szlig;ern" border="0" /></a>
			</p> -->
			
	<p style="margin-top:10px;">Bitte w&auml;hlen Sie: 
	
	 </p>
<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div>


<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div>
<!-- <a href="http://validator.w3.org/check?uri=http%3A%2F%2Fwww.phpwcms-docu.de%2Findex.php%3Fdeutsche_version" title="W3C Standard XHTML" target="_blank"><img src="picture/w3c/w3c_xhtml.gif" border="0" alt="" /></a>
<a href="http://jigsaw.w3.org/css-validator/validator?uri=http://www.phpwcms-docu.de" title="W3C Standard CSS" target="_blank"><img src="picture/w3c/w3c_css.gif" border="0" alt="" /></a><br />			
<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div> -->
<h3>Partnersites</h3>






<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div>

<div style="margin-top:10px; margin-bottom:15px;"></div>


<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div>
</div>

	</div> 
	
	<div id="content">
	<div id="bread">Sie sind hier: <a href="deutsche_version.phtml">Deutsch</a> <span class="breadcrumb_spacer">&gt;</span> <a href="die_docu.phtml">Die Docu</a> <span class="breadcrumb_spacer">&gt;</span> <a href="verwaltung_admin.phtml">Admin</a> <span class="breadcrumb_spacer">&gt;</span> <a href="replacement_tags_de.phtml">Replacement-Tags</a> <span class="breadcrumb_spacer">&gt;</span> Grafik Tags</div>
		
		<a name="jump44"></a><!-- Livedate: 06.08.2004 10:14:49 / Killdate: 31.12.2030 23:59:59 -->
<h1>Replacement Tags für Grafiken</h1>

<div style="margin:25px 0 0 0;padding:0;" class="spaceBeforeCP"></div><h3>HINWEIS</h3><p>Alle Image Tags beziehen sich auf das Verzeichnis &quot;Picture&quot;. Wenn Sie aus einem anderen Ordner Bilder mit dem Image Tag aufrufen m&ouml;chten, mu&szlig; der Link angepasst werden wie z.B.:<br />
{<img src="img/leer.gif" border="0" width="0" height="0" alt="" />IMAGE:../content/images/image.jpg}</p><div align="right"><a href="#top"><img src="img/article/top_link_0.gif" border="0" alt="" /></a></div><div style="margin-top:10px;">
<table width="100%" cellspacing="0" cellpadding="5" border="0">
    <tbody class="reptab">
        <tr class="reptab_head">
            <td colspan="2">RT: [<img src="img/leer.gif" border="0" width="0" height="0" alt="" />img=ID.FORMATxWxHxCROPxQUALITY ALT-Text]TITEL-Text[/img] </td>
		</tr>
        <tr>
            <td width="100" valign="top"><strong>Verwendung:</strong></td>
            <td valign="top">
	Ausgabe eines Bildes aus der Dateizentrale mit entsprechenden Angaben zur Größe, Zuschnitt, Qualität und Alternativ Text. (Ab V1.3.9).

</td>
        </tr>
        <tr>
            <td width="100" valign="top"><strong>Schreibweise:</strong></td>
            <td valign="top">[<img src="img/leer.gif" border="0" width="0" height="0" alt="" />img=ID.FORMATxWxHxCROPxQUALITY ALT-Text]TITEL-Text[/img]<br />oder die Kurzform: [<img src="img/leer.gif" border="0" width="0" height="0" alt="" />img=ID.FORMATxWxHxCROPxQUALITY]
<br /><br />


<strong>Beispiel:</strong><br />

[<img src="img/leer.gif" border="0" width="0" height="0" alt="" />img=1367.gifx200x200x0x80 Europakarte]Europa[/img]
<br />
Zeige das Bild mit der ID 1367 als GIF und verkleinere proportional auf max. 200 Pixel Breite bzw. 200 Pixel Höhe, kein Zuschnitt mit der Qualität 80, dem Alt-Text Europakarte und dem Titeltext &quot;Europa&quot;.</td>
        </tr>
        <tr>
            <td width="100" valign="top"><strong>Ausgabe-Format:</strong></td>
            <td valign="top"></td>
        </tr>
        <tr>
            <td width="100" valign="top"><strong>Bemerkung:</strong></td>
            <td valign="top"><p>Der Tag kann auch in der Kurzform angewendet werden:&nbsp;<br />
<code>[<img src="img/leer.gif" border="0" width="0" height="0" alt="" /><span class="posthilit">img</span>=10x100x100]</code><br />
<br />
Zeige Bild mit ID 10 als JPG und verkleinere proportional auf max. 100 Pixel Breite bzw. 100 Pixel H&ouml;he.</p></td>
        </tr>
    </tbody>
</table>
</div><div style="margin-top:10px;">
<table width="100%" cellspacing="0" cellpadding="5" border="0">
    <tbody class="reptab">
        <tr class="reptab_head">
            <td colspan="2">RT: {<img src="img/leer.gif" border="0" width="0" height="0" alt="" />IMAGE:Imagename} </td>
		</tr>
        <tr>
            <td width="100" valign="top"><strong>Verwendung:</strong></td>
            <td valign="top">
	Erzeugt ein -Tag mit der angegebenen Bilddatei.

</td>
        </tr>
        <tr>
            <td width="100" valign="top"><strong>Schreibweise:</strong></td>
            <td valign="top">{<img src="img/leer.gif" border="0" width="0" height="0" alt="" />IMAGE:icons/download.gif}</td>
        </tr>
        <tr>
            <td width="100" valign="top"><strong>Ausgabe-Format:</strong></td>
            <td valign="top"> <img src="picture/icons/download.gif" border="0" alt="" /></td>
        </tr>
        <tr>
            <td width="100" valign="top"><strong>Bemerkung:</strong></td>
            <td valign="top"><p>Das Verzeichnis <strong>icon</strong> liegt unmittelbar unterhalb&nbsp;von <strong>picture. </strong>Der komplette Pfadname zur Bilddatei ist in diesem Fall:<br />
<br />
<em>www.meine-domain.de/picture/icons/download.gif</em></p></td>
        </tr>
    </tbody>
</table>
</div><div style="margin-top:10px;">
<table width="100%" cellspacing="0" cellpadding="5" border="0">
    <tbody class="reptab">
        <tr class="reptab_head">
            <td colspan="2">RT: {<img src="img/leer.gif" border="0" width="0" height="0" alt="" />IMAGE_LEFT:imagename} </td>
		</tr>
        <tr>
            <td width="100" valign="top"><strong>Verwendung:</strong></td>
            <td valign="top">
	Erzeugt ein -Tag mit der angegebenen Bilddatei.
	Das Bild wird linksbündig ausgerichtet.

</td>
        </tr>
        <tr>
            <td width="100" valign="top"><strong>Schreibweise:</strong></td>
            <td valign="top">{<img src="img/leer.gif" border="0" width="0" height="0" alt="" />IMAGE_LEFT:web.gif}</td>
        </tr>
        <tr>
            <td width="100" valign="top"><strong>Ausgabe-Format:</strong></td>
            <td valign="top"> <img src="picture/web.gif" border="0" align="left" alt="" /></td>
        </tr>
        <tr>
            <td width="100" valign="top"><strong>Bemerkung:</strong></td>
            <td valign="top"><p>Das Bild <strong>web.gif</strong> liegt&nbsp;im Verzeichnis <strong>picture.</strong><br />
Der komplette Pfadname zur Bilddatei ist in diesem Fall:<br />
<br />
<em>www.meine-domain.de/picture/</em><em>web.gif</em></p></td>
        </tr>
    </tbody>
</table>
</div><div style="margin-top:10px;">
<table width="100%" cellspacing="0" cellpadding="5" border="0">
    <tbody class="reptab">
        <tr class="reptab_head">
            <td colspan="2">RT: {<img src="img/leer.gif" border="0" width="0" height="0" alt="" />IMAGE_RIGHT:Imagename} </td>
		</tr>
        <tr>
            <td width="100" valign="top"><strong>Verwendung:</strong></td>
            <td valign="top">
	Erzeugt ein -Tag mit der angegebenen Bilddatei.
	Das Bild wird rechtsbündig ausgerichtet.

</td>
        </tr>
        <tr>
            <td width="100" valign="top"><strong>Schreibweise:</strong></td>
            <td valign="top">{<img src="img/leer.gif" border="0" width="0" height="0" alt="" />IMAGE_RIGHT:web.gif}</td>
        </tr>
        <tr>
            <td width="100" valign="top"><strong>Ausgabe-Format:</strong></td>
            <td valign="top"> <img src="picture/web.gif" border="0" align="right" alt="" /></td>
        </tr>
        <tr>
            <td width="100" valign="top"><strong>Bemerkung:</strong></td>
            <td valign="top"><p>Das Bild <strong>web.gif</strong> liegt&nbsp;im Verzeichnis <strong>picture. </strong>Der komplette Pfadname zur Bilddatei ist in diesem Fall:<br />
<br />
<em>www.meine-domain.de/picture/web.gif</em></p></td>
        </tr>
    </tbody>
</table>
</div><div style="margin-top:10px;">
<table width="100%" cellspacing="0" cellpadding="5" border="0">
    <tbody class="reptab">
        <tr class="reptab_head">
            <td colspan="2">RT: {<img src="img/leer.gif" border="0" width="0" height="0" alt="" />RANDOM:Image_Pfad} </td>
		</tr>
        <tr>
            <td width="100" valign="top"><strong>Verwendung:</strong></td>
            <td valign="top">
	Erzeugt ein -Tag für Zufallsbilder aus dem angegebenen Verzeichnis.
	Bei jedem Seitenaufruf wird ein anders Zufallsbild angezeigt.

</td>
        </tr>
        <tr>
            <td width="100" valign="top"><strong>Schreibweise:</strong></td>
            <td valign="top">{<img src="img/leer.gif" border="0" width="0" height="0" alt="" />RANDOM:picture/random_175}</td>
        </tr>
        <tr>
            <td width="100" valign="top"><strong>Ausgabe-Format:</strong></td>
            <td valign="top"> <img src="picture/random_175/a4.gif" width="200" height="150" border="0" alt="a4.gif" /></td>
        </tr>
        <tr>
            <td width="100" valign="top"><strong>Bemerkung:</strong></td>
            <td valign="top"><p>Das Verzeichnis <strong>random_175</strong> ist ein Unterverzeichnis von <strong>picture.</strong><br />
Der komplette Pfadname&nbsp;zu den Random-Bildern ist:<br />
<br />
<em>www.meine-domain.de/picture/random_175/</em></p>
<p>Der Bildvorrat des Random-Ordners sollte nur Bilder mit der gleichen Abmessung beinhalten!&nbsp;<br />
Die Bilder werden unmittelbar aus dem Verzeichnis geladen und nicht neu vom Programm berechnet.</p></td>
        </tr>
    </tbody>
</table>
</div><div style="margin-top:10px;">
<table width="100%" cellspacing="0" cellpadding="5" border="0">
    <tbody class="reptab">
        <tr class="reptab_head">
            <td colspan="2">RT: {<img src="img/leer.gif" border="0" width="0" height="0" alt="" />SPACER:px-Breite x px-Hoehe} </td>
		</tr>
        <tr>
            <td width="100" valign="top"><strong>Verwendung:</strong></td>
            <td valign="top">
	Ausgabe eines grafischen Abstandselements zum Erzeugen einer &quot;freien Fläche&quot;. Eingabe von Breite und Höhe in Pixeln.

</td>
        </tr>
        <tr>
            <td width="100" valign="top"><strong>Schreibweise:</strong></td>
            <td valign="top">{<img src="img/leer.gif" border="0" width="0" height="0" alt="" />SPACER:250x5}<br /><br />


<strong>Beispiel:</strong><br />

ANFANG -|{<img src="img/leer.gif" border="0" width="0" height="0" alt="" />SPACER:250x5}|- ENDE</td>
        </tr>
        <tr>
            <td width="100" valign="top"><strong>Ausgabe-Format:</strong></td>
            <td valign="top"> ANFANG -|<img src="img/leer.gif" border="0" width="250" height="5" alt="" />|- ENDE</td>
        </tr>
        <tr>
            <td width="100" valign="top"><strong>Bemerkung:</strong></td>
            <td valign="top"><p>Der Zwischenraum zwischen den beiden Marken <strong>-|</strong> und <strong>|-</strong>&nbsp;wurde&nbsp;hier mit <strong>exakt 250 Pixeln</strong> festgelegt.</p></td>
        </tr>
    </tbody>
</table>
</div>
		 
		
		<br /><br />
		<div class="sub">
		Artikel erstellt am: Mittwoch, 18. August 2004 <br /> Letzte &Auml;nderung: Dienstag, 04. Januar 2011	
		</div>
				
	</div>
	
<div id="footer"><br /><br />
<p style="height:30px;">&nbsp;</p>


 <script type="text/javascript" language="javascript">
<!--

var showDefaultValue =  0

function hideLayer(whichLayer) {
	if (document.getElementById) {
		// this is the way the standards work
		document.getElementById(whichLayer).style.display = "none";
	} else if (document.all) {
		// this is the way old msie versions work
		document.all[whichlayer].style.display = "none";
	} else if (document.layers) {
		// this is the way nn4 works
		document.layers[whichLayer].display = "none";
	}
}

function showLayer(whichLayer) {
		//	alert(whichLayer);
	if (document.getElementById) {
		// this is the way the standards work
		document.getElementById(whichLayer).style.display = "block";
	}
	else if (document.all) {
		// this is the way old msie versions work
		document.all[whichlayer].style.display = "block";
	}
	else if (document.layers) {
		// this is the way nn4 works
		document.layers[whichLayer].display = "block";
	}
}

function toggleLayer(whichLayer) {
	if(showDefaultValue == 0) {
		hideLayer(whichLayer);
		showDefaultValue = 1;
	} else {
		showLayer(whichLayer);
		showDefaultValue = 0;
	}
}
//-->
</script>


<div id="alles">
<div id="klapper" onclick="toggleLayer('formular');">
<table width="570" border="0" cellspacing="0" cellpadding="0">
<tr>
<td><em style="color:#275EA8;" onmouseover="this.style.color='#4F96F4';" onmouseout="this.style.color='#275EA8';">Sie haben Anregungen oder Kritik zu diesem Artikel? Schreiben Sie uns!</em></td>   
<td align="right" style="padding-right:2px;"><img src="template/lang/all/icons/write.gif" width="16" height="21" alt="" border="0" /></td>
</tr>
</table>

</div>
<div id="formular">

<form name="form" method="post" action="index.php?id=96,44,0,0,1,0" style="margin:0;padding:0;"><input type="hidden" name="customForm" value="1" /><input type="hidden" name="docucheck" value="1" />


<div style="float:left;">
<p><select name="Betreff" id="Betreff" class="size1">
<option value="" class="deepblue"> Bitte ausw&auml;hlen </option>
<option value="subject_1" class="inselect">Anregungen</option>
<option value="subject_2" class="inselect">Fehlermeldung/ Kritik</option>
<option value="subject_3" class="inselect">Sonstiges</option>

</select><br /></p>


<p>Vorname:<br />
<input type="text" name="Vorname" value="" class="size1" /></p>
<p>Name:*<br />
<input type="text" name="Name" value="" class="size1" /></p>
<p>E-Mail:*<br />
<input type="text" name="E-Mail" value="" class="size1" /></p>
</div>


<div style="float:right;">Mitteilung:*<br />
<textarea name="Nachricht" cols="40" rows="4"  class="size7"></textarea>
</div>

<p style="clear:both; text-align:right;"><input type="reset" name="reset" value="Zur&uuml;cksetzen" class="btstyle" style="width:100px;" />&nbsp;&nbsp;
<input type="submit" name="submit" value="Anfrage senden" class="btstyle" style="width:110px;" /></p>
<p style="margin:20px;" class="sub">* Pflichtangaben. Ihre Daten werden ausschlie&szlig;lich für diese Anfrage verwendet.</p>

</form>
</div>
</div>
 <script type="text/javascript" language="javascript">
<!--
	// Lösung ohne Onload
	toggleLayer('formular');
//-->
</script>
<br />





	<table width="97%" border="0" cellspacing="0" cellpadding="0">
		<tr>
			<td valign="bottom">	
			&copy; phpwcms-docu 2004-2013
			<img src="img/leer.gif" border="0" width="10" height="0" alt="" /><a href="impressum.phtml" class="phpwcmsIntLink"><img src="template/lang/all/icons/imprint.gif" width="9" height="15" alt="Impressum" title="Impressum" border="0" /></a>&nbsp; 
			<a href="sitemap_de.phtml" class="phpwcmsIntLink"><img src="template/lang/all/icons/sitemap.gif" width="19" height="15" alt="Sitemap" title="Sitemap" border="0" /></a>&nbsp; 
			<a href="gaestebuch.phtml" class="phpwcmsIntLink"><img src="template/lang/all/icons/gbook.gif" width="20" height="16" alt="Ins G&auml;stebuch eintragen" title="Ins G&auml;stebuch eintragen" border="0" /></a>&nbsp; 
			<a href="#" onclick="BookMark_Page();return false;" title="" class="phpwcmsBookmarkLink"><img src="template/lang/all/icons/favo.gif" width="12" height="15" alt="Seite als Bookmark speichern" title="Seite als Bookmark speichern" border="0" /></a>&nbsp; 
			     
			</td>
			<td valign="bottom" style="padding-right:25px;">
			
			
			
			</td>		
			<td width="150">
			</td>
		</tr>
	</table>
</div><br/>

</div>
</body>
</html>