<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<!--
	phpwcms | free open source content management system
	created by Oliver Georgi (oliver at phpwcms dot de) and licensed under GNU/GPL.
	phpwcms is copyright 2003-2007 of Oliver Georgi. Extensions are copyright of
	their respective owners. Visit project page for details: http://www.phpwcms.org/
//-->
<title>phpwcms-docu for  phpwcms :: web based content management system | Article Tags{D:7/29/2007,30,newR.gif} | Replacement Tags for Articles{D:7/29/2007,30,newR.gif}</title>
  <meta http-equiv="content-type" content="text/html; charset=iso-8859-1" />
  <meta http-equiv="content-style-type" content="text/css" />
  <script src="template/inc_js/frontend.js" type="text/javascript"></script>
  <style type="text/css">
  <!-- 
    @import url("template/inc_css/mpl_frontend.css");
    @import url("template/inc_css/mpl_menu.css");
    @import url("template/inc_css/mpl_objects.css");
    @import url("template/inc_css/mpl_docu_en.css");
  //-->
  </style>
<meta name="Title" content="The phpWCMS Documentation" />
<meta name="author" content="Oliver Frohnert, Mario Perez Leal" />
<meta name="Publisher" content="Oliver Frohnert, Mario Perez Leal, creacion" />
<meta name="Copyright" content="Oliver Frohnert, Mario Perez Leal, creacion" />
<meta name="keywords" content="frohnert, perez leal, creacion, documentation, dokumentation, phpwcms, cms, opensource, open source, docu" />
<meta name="description" content="A Documentation Project for the  Open Source CMS phpWCMS" />
<meta name="Audience" content="Alle" />
<meta name="Content-language" content="EN" />
<meta name="robots"      content="index,follow" />
<meta name="expires" content="0" />
<meta name="revisit-after" content="7 days" />
<meta name="resource-type" content="document" />
<meta name="distribution" content="Global" />
<meta name="generator" content="PHPWCMS" />

  <!--[if lt IE 7]>
  <style type="text/css">
    body { behavior: url("template/inc_css/specific/csshover2.htc"); }
    img { behavior: url("template/inc_css/specific/pngbehavior.htc"); }
  </style>
  <![endif]-->
</head>
<body id="myid_80">
<div id="container"><a name="top" id="top"></a>


	<div id="head">
		
	<div id="mainnavi">
		<div class="fleft"><a href="english_version.phtml">Home</a> | <a href="news_en.phtml">News</a> | <span style="text-decoration:none;font-weight:bold;"><a href="the_docu.phtml">The Docu</a></span> | <a href="Usefull_Links_and_Tools.phtml">Links &amp; Tools</a> | <a href="contact.phtml">Contact</a> | <a href="faq_en.phtml">FAQ</a> | <a href="http://forum.phpwcms.org/" target="_blank">Forum</a> | <a href="howto_en.phtml">HowTo</a></div>				
		<div class="sys">Monday, 6. July 2015<img src="img/leer.gif" border="0" width="5" height="1" alt="" />|<img src="img/leer.gif" border="0" width="5" height="1" alt="" />6 User online<img src="img/leer.gif" border="0" width="10" height="1" alt="" />
		<a href="deutsche_version.phtml" title="Deutsche Version"><img src="picture/../template/lang/all/flag_de.gif" border="0" alt="" /></a>
		<a href="english_version.phtml"  title="English version"><img src="picture/../template/lang/all/flag_en.gif" border="0" alt="" /></a>
		</div>
	</div>
	
	<a href="./" title="phpwcms-docu Startseite aufrufen" class="homelink">
	<span>&raquo; phpwcms-docu startpage</span></a>
	<h2>phpwcms-docu - Documentation for the Web Content Management System phpwcms</h2>
	<p>This website is targeted both to the beginner and the lateral entry following the goal to simplify the 
work with phpwcms and to focus on the essentials things.</p>
	</div>

	
	<div id="left">
	<div class="leftnav" style="margin-top:24px;">
	
<div id="ul_div_311">
<ul>
	<li class="sub_no"><a href="download-dev-versions.phtml">Download Dev Versions</a></li>
	<li class="sub_no sub_ul_true"><a href="installation_en.phtml">Installation &amp; Upgrade</a></li>
	<li class="sub_no sub_ul_true"><a href="article.phtml">Articles</a></li>
	<li class="sub_no sub_ul_true"><a href="file.phtml">File</a></li>
	<li class="sub_no sub_ul_true"><a href="module_en.phtml">Modules</a></li>
	<li class="sub_no sub_ul_true"><a href="communication.phtml">Communication </a></li>
	<li class="sub_no"><a href="chat_en.phtml">Chat</a></li>
	<li class="sub_no"><a href="profile.phtml">Profile</a></li>
	<li class="sub_ul"><a href="admin_en_.phtml">Admin</a>
	<div id="ul_div_312">
	<ul>
		<li class="sub_no sub_ul_true"><a href="sitestructure.phtml">Sitestructure</a></li>
		<li class="sub_no sub_ul_true"><a href="user_administration.phtml">User administration</a></li>
		<li class="sub_no"><a href="remove_delete_files.phtml">Remove delete files</a></li>
		<li class="sub_no"><a href="templating.phtml">Templating </a></li>
		<li class="sub_ul"><a href="replacement_tags_en.phtml">Replacement Tags</a>
		<div id="ul_div_75">
		<ul>
			<li class="sub_no"><a href="system_tags.phtml">System Tags</a></li>
			<li class="sub_no sub_ul_true"><a href="navigation_tags.phtml">Navigation Tags</a></li>
			<li class="sub_no"><a href="link_tags.phtml">Link Tags</a></li>
			<li class="sub_no"><a href="image_tags.phtml">Image Tags</a></li>
			<li class="sub_no active"><a href="article_tags.phtml">Article Tags</a></li>
			<li class="sub_no"><a href="language.phtml">Language</a></li>
		</ul>
		</div>
		</li>
	</ul>
	</div>
	</li>
	<li class="sub_no sub_ul_true"><a href="add-ons-and-templates.phtml">Add On&#039;s and Templates</a></li>
	<li class="sub_no"><a href="deutsche_version.phtml?replacement_tags_en">Replacement Tags</a></li>
	<li class="sub_no"><a href="deutsche_version.phtml?content_parts_en">Content Parts</a></li>
</ul>
</div>

		
	</div> 
	</div> 
	  
	<div id="right">
		<div style="margin-top:24px;">			
		<form action="#" method="post" name="searchFE" onsubmit="s=document.getElementById('customSearchInput');if(s.value=='Search')return false;">
			<table width="100%" border="0" cellpadding="0" cellspacing="0">
			<tr>
					<td><input type="text" name="search_input_field" size="20" maxlength="200" id="customSearchInput" class="customSearchInput" value="" onfocus="if(this.value=='Search')this.value='';" onblur="if(this.value=='')this.value='Search';"/></td>
					<td><input type="image" name="search_go" onfocus="this.blur();" title="Search" src="/template/lang/all/submit.gif" /></td>
				</tr>
			</table>
			</form>
			
			      <script type="text/javascript" language="javascript">
			  <!-- 
			        document.getElementById("customSearchInput").value="Search";
			  //-->
			      </script>
				  
<!-- <p style="margin-top:10px;">Change font size: <a href="[FontSize-]"><img src="template/lang/all/icons/reduce.gif" width="18" height="17" alt="" title="Small" border="0" /></a>
			<a href="[FontSize+]"><img src="template/lang/all/icons/extend.gif" width="18" height="17" alt="" title="Bigger" border="0" /></a>
			</p> -->
			
	<p style="margin-top:10px;">Please choose: 
	
	 </p>


<!-- <a href="http://validator.w3.org/check?uri=http%3A%2F%2Fwww.phpwcms-docu.de%2Findex.php%3Fdeutsche_version" title="W3C Standard XHTML" target="_blank"><img src="picture/w3c/w3c_xhtml.gif" border="0" alt="" /></a>
<a href="http://jigsaw.w3.org/css-validator/validator?uri=http://www.phpwcms-docu.de" title="W3C Standard CSS" target="_blank"><img src="picture/w3c/w3c_css.gif" border="0" alt="" /></a><br />			
<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div> -->
		
<div style="margin-top:10px; margin-bottom:15px;"></div>
	
</div>

	</div> 
	
	<div id="content">
	<div id="bread">You are here: <a href="english_version.phtml">English</a> <span class="breadcrumb_spacer">&gt;</span> <a href="the_docu.phtml">The Docu</a> <span class="breadcrumb_spacer">&gt;</span> <a href="admin_en_.phtml">Admin</a> <span class="breadcrumb_spacer">&gt;</span> <a href="replacement_tags_en.phtml">Replacement Tags</a> <span class="breadcrumb_spacer">&gt;</span> Article Tags</div>
		
		<a name="jump36"></a><!-- Livedate: 05.08.2004 19:02:00 / Killdate: 31.12.2030 23:59:59 -->
<h1>Replacement Tags for Articles</h1>

<div style="margin:25px 0 0 0;padding:0;" class="spaceBeforeCP"></div><h4>{<img src="img/leer.gif" border="0" width="0" height="0" alt="" />AUTHOR}</h4><TABLE cellSpacing=0 cellPadding=5 width="100%" border=0>
<TBODY bgColor=#efefef>
<TR>
<TD vAlign=top align=right width=100><FONT class=v10 color=#666666><STRONG>Use:</STRONG></FONT></TD>
<TD width=5 rowSpan=5></TD>
<TD vAlign=top>Distributes the Author of the article</TD></TR>
<TR>
<TD vAlign=top align=right width=100><FONT class=v10 color=#666666><STRONG>Notation:</STRONG></FONT></TD>
<TD vAlign=top><STRONG>{<img src="img/leer.gif" border="0" width="0" height="0" alt="" />AUTHOR}</STRONG></TD></TR>
<TR>
<TD vAlign=top align=right width=100><FONT class=v10 color=#666666><STRONG>Result:</STRONG></FONT></TD>
<TD vAlign=top>Oliver</TD></TR>
<TR>
<TD vAlign=top align=right width=100><FONT class=v10 color=#666666><STRONG>Remark:</STRONG></FONT></TD>
<TD vAlign=top></TD></TR>
<TR>
<TD vAlign=top align=right width=100><FONT class=v10 color=#666666><STRONG></STRONG></FONT></TD>
<TD vAlign=top></TD></TR></TBODY></TABLE><div align="right"><a href="#top"><img src="img/article/top_link_0.gif" border="0" alt="" /></a></div><h4>{<img src="img/leer.gif" border="0" width="0" height="0" alt="" />DATE_ARTICLE}</h4><TABLE cellSpacing=0 cellPadding=5 width="100%" border=0>
<TBODY bgColor=#efefef>
<TR>
<TD vAlign=top align=right width=100><FONT class=v10 color=#666666><STRONG>Use:</STRONG></FONT></TD>
<TD width=5 rowSpan=5></TD>
<TD vAlign=top>Distributes the construction date of the article</TD></TR>
<TR>
<TD vAlign=top align=right width=100><FONT class=v10 color=#666666><STRONG>Notation:</STRONG></FONT></TD>
<TD vAlign=top><STRONG>{<img src="img/leer.gif" border="0" width="0" height="0" alt="" />DATE_ARTICLE}</STRONG></TD></TR>
<TR>
<TD vAlign=top align=right width=100><FONT class=v10 color=#666666><STRONG>Result:</STRONG></FONT></TD>
<TD vAlign=top>Tuesday, 21. January 2014</TD></TR>
<TR>
<TD vAlign=top align=right width=100><FONT class=v10 color=#666666><STRONG>Remark:</STRONG></FONT></TD>
<TD vAlign=top><FONT size=1>To display date in&nbsp;other&nbsp;languages&nbsp;you must edit: config/phpwcms/conf.template_default.inc.php<br />$template_default["date"]["language"]="EN";</FONT></TD></TR>
<TR>
<TD vAlign=top align=right width=100><FONT class=v10 color=#666666><STRONG></STRONG></FONT></TD>
<TD vAlign=top></TD></TR></TBODY></TABLE><div align="right"><a href="#top"><img src="img/article/top_link_0.gif" border="0" alt="" /></a></div><h4>{<img src="img/leer.gif" border="0" width="0" height="0" alt="" />TIME_ARTICLE}</h4><TABLE cellSpacing=0 cellPadding=5 width="100%" border=0>
<TBODY bgColor=#efefef>
<TR>
<TD vAlign=top align=right width=100><FONT class=v10 color=#666666><STRONG>Use:</STRONG></FONT></TD>
<TD width=5 rowSpan=5></TD>
<TD vAlign=top>Distributes the construction time of the article</TD></TR>
<TR>
<TD vAlign=top align=right width=100><FONT class=v10 color=#666666><STRONG>Notation:</STRONG></FONT></TD>
<TD vAlign=top><STRONG>{<img src="img/leer.gif" border="0" width="0" height="0" alt="" />TIME_ARTICLE}</STRONG></TD></TR>
<TR>
<TD vAlign=top align=right width=100><STRONG><FONT color=#666666 size=1>Result:</FONT></STRONG></TD>
<TD vAlign=top>12:41</TD></TR>
<TR>
<TD vAlign=top align=right width=100><FONT class=v10 color=#666666><STRONG>Remark:</STRONG></FONT></TD>
<TD vAlign=top><FONT size=1>The&nbsp;Time format can be changed in&nbsp;<br />config/phpwcms/conf.template_default.inc.php beginning from line 159</FONT></TD></TR>
<TR>
<TD vAlign=top align=right width=100><FONT class=v10 color=#666666><STRONG></STRONG></FONT></TD>
<TD vAlign=top></TD></TR></TBODY></TABLE><div align="right"><a href="#top"><img src="img/article/top_link_0.gif" border="0" alt="" /></a></div><h4>[<img src="img/leer.gif" border="0" width="0" height="0" alt="" />b]Text[<img src="img/leer.gif" border="0" width="0" height="0" alt="" />/b]</h4><TABLE cellSpacing=0 cellPadding=5 width="100%" border=0>
<TBODY bgColor=#efefef>
<TR>
<TD vAlign=top align=right width=100><FONT class=v10 color=#666666><STRONG>Use:</STRONG></FONT></TD>
<TD width=5 rowSpan=5></TD>
<TD vAlign=top>With this tag you can format text to <STRONG>bold</STRONG></TD></TR>
<TR>
<TD vAlign=top align=right width=100><FONT class=v10 color=#666666><STRONG>Notation:</STRONG></FONT></TD>
<TD vAlign=top><STRONG>[<img src="img/leer.gif" border="0" width="0" height="0" alt="" />b}Text[/b]</STRONG></TD></TR>
<TR>
<TD vAlign=top align=right width=100><FONT class=v10 color=#666666><STRONG>Result:</STRONG></FONT></TD>
<TD vAlign=top><STRONG><strong>Text</strong></STRONG></TD></TR>
<TR>
<TD vAlign=top align=right width=100><FONT class=v10 color=#666666><STRONG>Remark:</STRONG></FONT></TD>
<TD vAlign=top>This tag is made for plain text content parts. But it can used as well in templates, headlines, captions ...</TD></TR>
<TR>
<TD vAlign=top align=right width=100><FONT class=v10 color=#666666><STRONG></STRONG></FONT></TD>
<TD vAlign=top></TD></TR></TBODY></TABLE><div align="right"><a href="#top"><img src="img/article/top_link_0.gif" border="0" alt="" /></a></div><h4>[<img src="img/leer.gif" border="0" width="0" height="0" alt="" />i]Text[<img src="img/leer.gif" border="0" width="0" height="0" alt="" />/i]</h4><TABLE cellSpacing=0 cellPadding=5 width="100%" border=0>
<TBODY bgColor=#efefef>
<TR>
<TD vAlign=top align=right width=100><FONT class=v10 color=#666666><STRONG>Use:</STRONG></FONT></TD>
<TD width=5 rowSpan=5></TD>
<TD vAlign=top>With this tag you can format text to <EM>italic</EM></TD></TR>
<TR>
<TD vAlign=top align=right width=100><FONT class=v10 color=#666666><STRONG>Notation:</STRONG></FONT></TD>
<TD vAlign=top><STRONG>[<img src="img/leer.gif" border="0" width="0" height="0" alt="" />i]Text[<img src="img/leer.gif" border="0" width="0" height="0" alt="" />/i]</STRONG></TD></TR>
<TR>
<TD vAlign=top align=right width=100><FONT class=v10 color=#666666><STRONG>Result:</STRONG></FONT></TD>
<TD vAlign=top><i>Text</i></TD></TR>
<TR>
<TD vAlign=top align=right width=100><FONT class=v10 color=#666666><STRONG>Remark:</STRONG></FONT></TD>
<TD vAlign=top>This tag is made for plain text content parts. But it can used as well in templates, headlines, captions ...</TD></TR>
<TR>
<TD vAlign=top align=right width=100><FONT class=v10 color=#666666><STRONG></STRONG></FONT></TD>
<TD vAlign=top></TD></TR></TBODY></TABLE><div align="right"><a href="#top"><img src="img/article/top_link_0.gif" border="0" alt="" /></a></div><h4>[<img src="img/leer.gif" border="0" width="0" height="0" alt="" />u]Text[<img src="img/leer.gif" border="0" width="0" height="0" alt="" />/u]</h4><TABLE cellSpacing=0 cellPadding=5 width="100%" border=0>
<TBODY bgColor=#efefef>
<TR>
<TD vAlign=top align=right width=100><FONT class=v10 color=#666666><STRONG>Use:</STRONG></FONT></TD>
<TD width=5 rowSpan=5></TD>
<TD vAlign=top>With this tag you can decorate text <U>underline</U></TD></TR>
<TR>
<TD vAlign=top align=right width=100><FONT class=v10 color=#666666><STRONG>Notation:</STRONG></FONT></TD>
<TD vAlign=top><STRONG>[<img src="img/leer.gif" border="0" width="0" height="0" alt="" />u]Text[<img src="img/leer.gif" border="0" width="0" height="0" alt="" />/u]</STRONG></TD></TR>
<TR>
<TD vAlign=top align=right width=100><FONT class=v10 color=#666666><STRONG>Result:</STRONG></FONT></TD>
<TD vAlign=top><u>Text</u></TD></TR>
<TR>
<TD vAlign=top align=right width=100><FONT class=v10 color=#666666><STRONG>Remark:</STRONG></FONT></TD>
<TD vAlign=top>This tag is made for plain text content parts. But it can used as well in templates, headlines, captions ...</TD></TR>
<TR>
<TD vAlign=top align=right width=100><FONT class=v10 color=#666666><STRONG></STRONG></FONT></TD>
<TD vAlign=top></TD></TR></TBODY></TABLE><div align="right"><a href="#top"><img src="img/article/top_link_0.gif" border="0" alt="" /></a></div><h4>[<img src="img/leer.gif" border="0" width="0" height="0" alt="" />s]Text[<img src="img/leer.gif" border="0" width="0" height="0" alt="" />/s]</h4><table width="100%" cellspacing="0" cellpadding="5" border="0">
    <tbody bgcolor="#efefef">
        <tr>
            <td width="100" valign="top" align="right"><font color="#666666" class="v10"><strong>Use:</strong></font></td>
            <td width="5" rowspan="5">&nbsp;</td>
            <td valign="top">With this tag you can decorate text <strike>strikeout</strike></td>
        </tr>
        <tr>
            <td width="100" valign="top" align="right"><font color="#666666" class="v10"><strong>Notation:</strong></font></td>
            <td valign="top"><strong>[<img src="img/leer.gif" border="0" width="0" height="0" alt="" />s]Text[<img src="img/leer.gif" border="0" width="0" height="0" alt="" />/s]</strong></td>
        </tr>
        <tr>
            <td width="100" valign="top" align="right"><font color="#666666" class="v10"><strong>Result:</strong></font></td>
            <td valign="top"><strike>Text</strike></td>
        </tr>
        <tr>
            <td width="100" valign="top" align="right"><font color="#666666" class="v10"><strong>Remark:</strong></font></td>
            <td valign="top">This tag is made for plain text content parts. But it can used as well in templates, headlines, captions ...</td>
        </tr>
        <tr>
            <td width="100" valign="top" align="right">&nbsp;</td>
            <td valign="top">&nbsp;</td>
        </tr>
    </tbody>
</table><div align="right"><a href="#top"><img src="img/article/top_link_0.gif" border="0" alt="" /></a></div><h4>[<img src="img/leer.gif" border="0" width="0" height="0" alt="" />BR]</h4><TABLE cellSpacing=0 cellPadding=5 width="100%" border=0>
<TBODY bgColor=#efefef>
<TR>
<TD vAlign=top align=right width=100><FONT class=v10 color=#666666><STRONG>Use:</STRONG></FONT></TD>
<TD width=5 rowSpan=5></TD>
<TD vAlign=top>With this tag you can force a linebreak</TD></TR>
<TR>
<TD vAlign=top align=right width=100><FONT class=v10 color=#666666><STRONG>Notation:</STRONG></FONT></TD>
<TD vAlign=top><STRONG>the forced line break is &gt;[<img src="img/leer.gif" border="0" width="0" height="0" alt="" />BR]&lt; here</STRONG></TD></TR>
<TR>
<TD vAlign=top align=right width=100><FONT class=v10 color=#666666><STRONG>Result:</STRONG></FONT></TD>
<TD vAlign=top>the forced line break is &gt;<br />&lt; here</TD></TR>
<TR>
<TD vAlign=top align=right width=100><FONT class=v10 color=#666666><STRONG>Remark:</STRONG></FONT></TD>
<TD vAlign=top>This tag is can used in all content parts&nbsp;and in templates, headlines, captions ...</TD></TR>
<TR>
<TD vAlign=top align=right width=100><FONT class=v10 color=#666666><STRONG></STRONG></FONT></TD>
<TD vAlign=top></TD></TR></TBODY></TABLE><div align="right"><a href="#top"><img src="img/article/top_link_0.gif" border="0" alt="" /></a></div><h3>{<img src="img/leer.gif" border="0" width="0" height="0" alt="" />SHOW_CONTENT:MODE,id,id,id}</h3><table width="100%" cellspacing="0" cellpadding="5" border="0">
    <tbody bgcolor="#efefef">
        <tr>
            <td width="100" valign="top" align="right"><font color="#666666" class="v10"><strong>Use:</strong></font></td>
            <td width="5" rowspan="5">&nbsp;</td>
            <td valign="top"><span class="postbody">Shows one ore more content parts (&gt;=V1.2.8)<br />
            </span></td>
        </tr>
        <tr>
            <td width="100" valign="top" align="right"><font color="#666666" class="v10"><strong>Notation:</strong></font></td>
            <td valign="top"><strong>{<img src="img/leer.gif" border="0" width="0" height="0" alt="" />SHOW_CONTENT:MODE,id,id,id}</strong></td>
        </tr>
        <tr>
            <td width="100" valign="top" align="right"><font color="#666666" class="v10"><strong>Result:</strong></font></td>
            <td valign="top">{<img src="img/leer.gif" border="0" width="0" height="0" alt="" />SHOW_CONTENT:CP,1,2,3}<br />
            the CPs with the CP-ID 1,2 und 3 was spent here.</td>
        </tr>
        <tr>
            <td width="100" valign="top" align="right"><font color="#666666" class="v10"><strong>Remark</strong></font><font color="#666666" class="v10"><strong>:</strong></font></td>
            <td valign="top">There are 3 different MODE'S<br />
            <br />
            1. {<img src="img/leer.gif" border="0" width="0" height="0" alt="" />SHOW_CONTENT:<strong>CP</strong>, cp-id, cp-id, cp-id} <br />
            &nbsp;&nbsp;&nbsp; List of Content Parts but based on selected cp | id = <span style="color: red;">id</span> of <span style="color: red;">cp</span>, <br />
            &nbsp;&nbsp;&nbsp; comma seperated.<br />
            <br />
            2. {<img src="img/leer.gif" border="0" width="0" height="0" alt="" />SHOW_CONTENT:<strong>CPA</strong>, art-id, art-id, art-id} <br />
            &nbsp;&nbsp;&nbsp; ascending list of Content Parts but based on <br />
            &nbsp;&nbsp;&nbsp; selected article | id = <span style="color: red;">id</span> of <span style="color: red;">article</span>, comma seperated.<br />
            <br />
            3. {<img src="img/leer.gif" border="0" width="0" height="0" alt="" />SHOW_CONTENT:<strong>CPAD</strong>, art-id, art-id, art-id} <br />
            &nbsp;&nbsp;&nbsp; same as CPA, but descending (this slows rendering) <br />
            <p>4. {<img src="img/leer.gif" border="0" width="0" height="0" alt="" />SHOW_CONTENT:<strong>AS</strong>, art-id, art-id, art-id} <br />
            &nbsp;&nbsp;&nbsp; List of Article Summaries | id = id of articles, comma separated.<br />
            &nbsp;&nbsp;&nbsp; - <b>Sort order: </b><br />
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - <b>AS:</b> Sorted as given<br />
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - <b>ASL:</b> Sorted by &quot;lifedate ASC&quot; (&quot;begins date&quot; ascending)<br />
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - <b>ASLD:</b> Sorted by  &quot;lifedate DESC&quot; (&quot;vbegins date&quot; descending)<br />
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - <b>ASK:</b> Sorted by  &quot;killdate ASC&quot; (&quot;ends date&quot; ascending)<br />
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - <b>ASKD:</b> Sorted by  &quot;killdate DESC&quot; (&quot;ends date&quot; descending)<br />
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - <b>ASC:</b> Sorted by  &quot;changedate ASC&quot; (&quot;change date&quot; ascending)<br />
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - <b>ASCD:</b> Sorted by  &quot;changedate DESC&quot; (&quot;change date&quot; descending)<br />
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - <b>ASR:</b> Sorted by  &quot;random&quot;</p>
            <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - <b>AxxxP:</b> Include priorize article value too. <br />
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; (e.g. ASP oder ASLDP ....)</p>
            <p>&nbsp;&nbsp;&nbsp; - <b>Mode expansion: </b><br />
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - <b>Mode|Limit|Template:</b> Output article maximum number or <br />
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; list template&nbsp; (e.g.. ASL|3, ... , ASL|MyTemplate.tmpl, ...)<br />
            &nbsp;&nbsp;&nbsp; &nbsp; &nbsp; E.g.: <br />
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;  {<img src="img/leer.gif" border="0" width="0" height="0" alt="" />SHOW_CONTENT:<b>AS|OwnTemplate.tmpl</b>, art-id, art-id, art-id}<br />
            &nbsp;&nbsp;&nbsp; &nbsp; &nbsp; <span lang="en" class="short_text" id="result_box"><span class="hps">outputs the</span> <span class="hps">contents of the specified articles</span></span>. <br />
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; {<img src="img/leer.gif" border="0" width="0" height="0" alt="" />SHOW_CONTENT:<b>AS|OwnTemplate.tmpl</b>,{CURRENT_ARTICLEID}}<br />
            &nbsp;&nbsp;&nbsp; &nbsp; &nbsp; <span lang="en" id="result_box"><span class="hps">returns the contents</span> <span class="hps">of the current article</span> <span class="hps">(Detail</span> <span class="hps">mode).</span></span><br />
            &nbsp;&nbsp;&nbsp; &nbsp; &nbsp; <span lang="en" class="short_text" id="result_box"><span class="hps">The template</span> <span class="hps">is located in </span></span><br />
            &nbsp;&nbsp;&nbsp; &nbsp; &nbsp; /template/inc_cntpart/articlesummary/list/..</p>
            <p><strike>5. {<img src="img/leer.gif" border="0" width="0" height="0" alt="" />SHOW_CONTENT:<b>CAS</b>, cat-id, cat-id, cat-id}<br />
            &nbsp;&nbsp;&nbsp; List of Article Summaries | id = id of structure level, comma separated.</strike></p>
            </td>
        </tr>
        <tr>
            <td width="100" valign="top" align="right"></td>
            <td valign="top">&nbsp;</td>
        </tr>
    </tbody>
</table><div align="right"><a href="#top"><img src="img/article/top_link_0.gif" border="0" alt="" /></a></div>
		 
		
		<br /><br />
		<div class="sub">
		Article created: Friday, 6. August 2004 <br /> Last Changes: Tuesday, 21. January 2014	
		</div>
				
	</div>
	
<div id="footer">





	<table width="97%" border="0" cellspacing="0" cellpadding="0">
		<tr>
			<td valign="bottom">	
			&copy; phpwcms-docu 2004-2015
			<img src="img/leer.gif" border="0" width="10" height="0" alt="" /><a href="imprint.phtml" class="phpwcmsIntLink"><img src="template/lang/all/icons/imprint.gif" width="9" height="15" alt="Impressum" title="Impressum" border="0" /></a>&nbsp; 
			<a href="sitemap_en.phtml" class="phpwcmsIntLink"><img src="template/lang/all/icons/sitemap.gif" width="19" height="15" alt="Sitemap" title="Sitemap" border="0" /></a>&nbsp; 
			 
			
			     
			</td>
			<td valign="bottom" style="padding-right:25px;">
			
			
			
			</td>		
			<td width="150">
			</td>
		</tr>
	</table>
</div><br/>

</div>
</body>
</html>