<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<!--
	phpwcms | free open source content management system
	created by Oliver Georgi (oliver at phpwcms dot de) and licensed under GNU/GPL.
	phpwcms is copyright 2003-2007 of Oliver Georgi. Extensions are copyright of
	their respective owners. Visit project page for details: http://www.phpwcms.org/
//-->
<title>phpwcms-docu for  phpwcms :: web based content management system | Artikel Tags{D:7/30/2007,30,neuR.gif}{D:07/29/2007,30,editR.gif} | Replacement Tags für Artikel{D:7/29/2007,30,neuR.gif}</title>
  <meta http-equiv="content-type" content="text/html; charset=iso-8859-1" />
  <meta http-equiv="content-style-type" content="text/css" />
  <script src="template/inc_js/frontend.js" type="text/javascript"></script>
  <style type="text/css">
  <!-- 
    @import url("template/inc_css/mpl_docu.css");
    @import url("template/inc_css/mpl_frontend.css");
    @import url("template/inc_css/mpl_menu.css");
    @import url("template/inc_css/mpl_objects.css");
  //-->
  </style>
<script type="text/javascript" language="javascript">
<!--
function MM_jumpMenu(targ,selObj,restore){ //v3.0
  eval(targ+".location='"+selObj.options[selObj.selectedIndex].value+"'");
  if (restore) selObj.selectedIndex=0;
}

function MM_findObj(n, d) { //v4.01
  var p,i,x;  if(!d) d=document; if((p=n.indexOf("?"))>0&&parent.frames.length) {
    d=parent.frames[n.substring(p+1)].document; n=n.substring(0,p);}
  if(!(x=d[n])&&d.all) x=d.all[n]; for (i=0;!x&&i<d.forms.length;i++) x=d.forms[i][n];
  for(i=0;!x&&d.layers&&i<d.layers.length;i++) x=MM_findObj(n,d.layers[i].document);
  if(!x && d.getElementById) x=d.getElementById(n); return x;
}

function MM_jumpMenuGo(selName,targ,restore){ //v3.0
  var selObj = MM_findObj(selName); if (selObj) MM_jumpMenu(targ,selObj,restore);
}
//-->
</script>
<meta name="Title" content="Die phpWCMS Dokumentation" />
<meta name="author" content="Oliver Frohnert, Mario Perez Leal" />
<meta name="Publisher" content="Oliver Frohnert, Mario Perez Leal, creacion" />
<meta name="Copyright" content="Oliver Frohnert, Mario Perez Leal, creacion" />
<meta name="keywords" content="frohnert, perez leal, creacion, documentation, dokumentation, phpwcms, cms, opensource, open source, docu" />
<meta name="description" content="Das Dokumentations Projekt für das Open Source CMS phpWCMS" />
<meta name="Audience" content="Alle" />
<meta name="Content-language" content="DE" />
<meta name="robots" content="index,follow" />
<meta name="expires" content="0" />
<meta name="revisit-after" content="7 days" />
<meta name="resource-type" content="document" />
<meta name="distribution" content="Global" />
<meta name="generator" content="PHPWCMS" />

  <!--[if lt IE 7]>
  <style type="text/css">
    body { behavior: url("template/inc_css/specific/csshover2.htc"); }
    img { behavior: url("template/inc_css/specific/pngbehavior.htc"); }
  </style>
  <![endif]-->
</head>
<body id="myid_97">
<div id="container"><a name="top" id="top"></a>


	<div id="head">
		
	<div id="mainnavi">
		<div class="fleft"><a href="deutsche_version.phtml">Startseite</a> | <a href="news_de.phtml">News</a> | <span style="text-decoration:none;font-weight:bold;"><a href="die_docu.phtml">Die Docu</a></span> | <a href="Nuetzliche_Links_und_Tools.phtml">Links &amp; Tools</a> | <a href="downloads.phtml">Downloads</a> | <a href="kontakt.phtml">Kontakt</a> | <a href="faq_de.phtml">FAQ</a> | <a href="http://forum.phpwcms.org/" target="_blank">Forum</a> | <a href="howto_de.phtml">HowTo</a></div>				
		<div class="sys">Samstag, 17. Oktober 2015<img src="img/leer.gif" border="0" width="5" height="1" alt="" />|<img src="img/leer.gif" border="0" width="5" height="1" alt="" />2 User online<img src="img/leer.gif" border="0" width="10" height="1" alt="" />
		<a href="deutsche_version.phtml" title="Deutsche Version"><img src="picture/../template/lang/all/flag_de.gif" border="0" alt="" /></a>
		<a href="english_version.phtml"  title="English version"><img src="picture/../template/lang/all/flag_en.gif" border="0" alt="" /></a>
		</div>
	</div>
	
	<a href="./" title="phpwcms-docu Startseite aufrufen" class="homelink">
	<span>&raquo; Zur phpwcms-docu Startseite</span></a>
	<h2>phpwcms-docu - Die Dokumentation f&uuml;r f&uuml;r das CMS phpWCMS</h2>
	<p>phpwcms-docu ist eine Art Kompass, der Ihnen die M&ouml;glichkeiten von phpWcms aufzeigt und Sie erfolgreich, ohne gro&szlig;e Umwege, zu Ihrer fertigen Web-Anwendung f&uuml;hren soll.
	</p>
	</div>

	
	<div id="left">
	<div class="leftnav" style="margin-top:24px;">
	
<div id="ul_div_309">
<ul>
	<li class="sub_no"><a href="download-dev-versionen.phtml">Download Dev Versionen</a></li>
	<li class="sub_no sub_ul_true"><a href="installation_und_upgrade_von_phpwcms.phtml">Installation &amp; Upgrade</a></li>
	<li class="sub_no sub_ul_true"><a href="verwaltung_artikel.phtml">Artikel</a></li>
	<li class="sub_no sub_ul_true"><a href="dateizentrale.phtml">Datei</a></li>
	<li class="sub_no sub_ul_true"><a href="verwaltung_module.phtml">Module</a></li>
	<li class="sub_no sub_ul_true"><a href="Kommunikation.phtml">Kommunikation</a></li>
	<li class="sub_no"><a href="verwaltung_nachricht.phtml">Nachricht</a></li>
	<li class="sub_no"><a href="verwaltung_chat.phtml">Chat</a></li>
	<li class="sub_no"><a href="verwaltung_profil.phtml">Profil</a></li>
	<li class="sub_ul"><a href="verwaltung_admin.phtml">Admin</a>
	<div id="ul_div_81">
	<ul>
		<li class="sub_no sub_ul_true"><a href="seitenstruktur.phtml">Seitenstruktur</a></li>
		<li class="sub_no"><a href="seitenlayout.phtml">Seitenlayout</a></li>
		<li class="sub_no"><a href="vorlagen_de.phtml">Vorlagen</a></li>
		<li class="sub_no"><a href="standard_css.phtml">Standard CSS</a></li>
		<li class="sub_no sub_ul_true"><a href="benutzerverwaltung.phtml">Benutzerverwaltung</a></li>
		<li class="sub_no"><a href="keywords_de.phtml"><span style="text-decoration:line-through;font-size:10px;">Keywords</span></a></li>
		<li class="sub_no"><a href="dateikategorien.phtml"><span style="text-decoration:line-through;font-size:10px;">Dateikategorien</span></a></li>
		<li class="sub_no"><a href="backend_standardtext.phtml">Backend Standardtext</a></li>
		<li class="sub_no"><a href="cache_zuruecksetzten.phtml">Cache zurücksetzten</a></li>
		<li class="sub_no"><a href="cache_loeschen.phtml">Cache löschen</a></li>
		<li class="sub_no"><a href="dateien_final_loeschen.phtml">Dateien final löschen</a></li>
		<li class="sub_ul"><a href="replacement_tags_de.phtml">Replacement-Tags</a>
		<div id="ul_div_69">
		<ul>
			<li class="sub_no"><a href="system_tags_.phtml">System Tags</a></li>
			<li class="sub_no"><a href="navigations_tags_.phtml">Navigations Tags</a></li>
			<li class="sub_no"><a href="link_tags_.phtml">Link Tags</a></li>
			<li class="sub_no"><a href="grafik_tags.phtml">Grafik Tags</a></li>
			<li class="sub_no active"><a href="artikel_tags.phtml">Artikel Tags</a></li>
			<li class="sub_no"><a href="spracheinstellungen.phtml">Spracheinstellungen<br /></a></li>
		</ul>
		</div>
		</li>
	</ul>
	</div>
	</li>
	<li class="sub_no sub_ul_true"><a href="add-on-und-vorlagen.phtml">Add Ons und Vorlagen</a></li>
	<li class="sub_no"><a href="deutsche_version.phtml?replacement_tags_de">Replacement Tags</a></li>
	<li class="sub_no"><a href="deutsche_version.phtml?content_parts_de">Content Parts</a></li>
</ul>
</div>

		
		
		

	</div> 
	</div> 
	  
	<div id="right">
		<div style="margin-top:24px;">			
		<form action="#" method="post" name="searchFE" onsubmit="s=document.getElementById('customSearchInput');if(s.value=='Suchen')return false;">
			<table width="100%" border="0" cellpadding="0" cellspacing="0">
			<tr>
					<td><input type="text" name="search_input_field" size="20" maxlength="200" id="customSearchInput" class="customSearchInput" value="" onfocus="if(this.value=='Suchen')this.value='';" onblur="if(this.value=='')this.value='Suchen';" /></td>
					<td><input type="image" name="search_go" onfocus="this.blur();" title="Suchen" src="/template/lang/all/submit.gif" /></td>
				</tr>
			</table>
			</form>
			
			      <script type="text/javascript" language="javascript">
			  <!-- 
			        document.getElementById("customSearchInput").value="Suchen";
			  //-->
			      </script>
				  
			<!-- <p style="margin-top:10px;">Schriftgrad &auml;ndern: <a href="[FontSize-]"><img src="template/lang/all/icons/reduce.gif" width="18" height="17" alt="" title="Verkleinern" border="0" /></a>
			<a href="[FontSize+]"><img src="template/lang/all/icons/extend.gif" width="18" height="17" alt="" title="Vergr&ouml;&szlig;ern" border="0" /></a>
			</p> -->
			
	<p style="margin-top:10px;">Bitte w&auml;hlen Sie: 
	
	 </p>
<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div>


<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div>
<!-- <a href="http://validator.w3.org/check?uri=http%3A%2F%2Fwww.phpwcms-docu.de%2Findex.php%3Fdeutsche_version" title="W3C Standard XHTML" target="_blank"><img src="picture/w3c/w3c_xhtml.gif" border="0" alt="" /></a>
<a href="http://jigsaw.w3.org/css-validator/validator?uri=http://www.phpwcms-docu.de" title="W3C Standard CSS" target="_blank"><img src="picture/w3c/w3c_css.gif" border="0" alt="" /></a><br />			
<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div> -->
<h3>Partnersites</h3>






<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div>

<div style="margin-top:10px; margin-bottom:15px;"></div>


<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div>
</div>

	</div> 
	
	<div id="content">
	<div id="bread">Sie sind hier: <a href="deutsche_version.phtml">Deutsch</a> <span class="breadcrumb_spacer">&gt;</span> <a href="die_docu.phtml">Die Docu</a> <span class="breadcrumb_spacer">&gt;</span> <a href="verwaltung_admin.phtml">Admin</a> <span class="breadcrumb_spacer">&gt;</span> <a href="replacement_tags_de.phtml">Replacement-Tags</a> <span class="breadcrumb_spacer">&gt;</span> Artikel Tags</div>
		
		<a name="jump45"></a><!-- Livedate: 06.08.2004 10:19:03 / Killdate: 31.12.2030 23:59:59 -->
<h1>Replacement Tags für Artikel</h1>
&nbsp;
<div style="margin-top:10px;">
<table width="100%" cellspacing="0" cellpadding="5" border="0">
    <tbody class="reptab">
        <tr class="reptab_head">
            <td colspan="2">RT: {<img src="img/leer.gif" border="0" width="0" height="0" alt="" />AUTHOR} </td>
		</tr>
        <tr>
            <td width="100" valign="top"><strong>Verwendung:</strong></td>
            <td valign="top">
	Gibt den Autor des Artikels aus

</td>
        </tr>
        <tr>
            <td width="100" valign="top"><strong>Schreibweise:</strong></td>
            <td valign="top">{<img src="img/leer.gif" border="0" width="0" height="0" alt="" />AUTHOR}</td>
        </tr>
        <tr>
            <td width="100" valign="top"><strong>Ausgabe-Format:</strong></td>
            <td valign="top"> Oliver</td>
        </tr>
        <tr>
            <td width="100" valign="top"><strong>Bemerkung:</strong></td>
            <td valign="top"><p>--</p></td>
        </tr>
    </tbody>
</table>
</div><div style="margin-top:10px;">
<table width="100%" cellspacing="0" cellpadding="5" border="0">
    <tbody class="reptab">
        <tr class="reptab_head">
            <td colspan="2">RT: {<img src="img/leer.gif" border="0" width="0" height="0" alt="" />DATE_ARTICLE} </td>
		</tr>
        <tr>
            <td width="100" valign="top"><strong>Verwendung:</strong></td>
            <td valign="top">
	Gibt das Erstellungsdatum des Artikels aus

</td>
        </tr>
        <tr>
            <td width="100" valign="top"><strong>Schreibweise:</strong></td>
            <td valign="top">{<img src="img/leer.gif" border="0" width="0" height="0" alt="" />DATE_ARTICLE}</td>
        </tr>
        <tr>
            <td width="100" valign="top"><strong>Ausgabe-Format:</strong></td>
            <td valign="top"> Dienstag, 28. Januar 2014</td>
        </tr>
        <tr>
            <td width="100" valign="top"><strong>Bemerkung:</strong></td>
            <td valign="top"><p>--</p></td>
        </tr>
    </tbody>
</table>
</div><div style="margin-top:10px;">
<table width="100%" cellspacing="0" cellpadding="5" border="0">
    <tbody class="reptab">
        <tr class="reptab_head">
            <td colspan="2">RT: {<img src="img/leer.gif" border="0" width="0" height="0" alt="" />TIME_ARTICLE} </td>
		</tr>
        <tr>
            <td width="100" valign="top"><strong>Verwendung:</strong></td>
            <td valign="top">
	Gibt die Erstellungszeit des Artikels aus.

</td>
        </tr>
        <tr>
            <td width="100" valign="top"><strong>Schreibweise:</strong></td>
            <td valign="top">{<img src="img/leer.gif" border="0" width="0" height="0" alt="" />TIME_ARTICLE}</td>
        </tr>
        <tr>
            <td width="100" valign="top"><strong>Ausgabe-Format:</strong></td>
            <td valign="top"> 10:19</td>
        </tr>
        <tr>
            <td width="100" valign="top"><strong>Bemerkung:</strong></td>
            <td valign="top"><p>--</p></td>
        </tr>
    </tbody>
</table>
</div><div style="margin-top:10px;">
<table width="100%" cellspacing="0" cellpadding="5" border="0">
    <tbody class="reptab">
        <tr class="reptab_head">
            <td colspan="2">RT: [<img src="img/leer.gif" border="0" width="0" height="0" alt="" />B] Text [/B] </td>
		</tr>
        <tr>
            <td width="100" valign="top"><strong>Verwendung:</strong></td>
            <td valign="top">
	Hiermit läßt sich ein Text <strong>fett</strong> auszeichnen.

</td>
        </tr>
        <tr>
            <td width="100" valign="top"><strong>Schreibweise:</strong></td>
            <td valign="top">[<img src="img/leer.gif" border="0" width="0" height="0" alt="" />B]Text in FETTER Auszeichnung[/B] und wieder normal</td>
        </tr>
        <tr>
            <td width="100" valign="top"><strong>Ausgabe-Format:</strong></td>
            <td valign="top"> <strong>Text in FETTER Auszeichnung</strong> und wieder normal</td>
        </tr>
        <tr>
            <td width="100" valign="top"><strong>Bemerkung:</strong></td>
            <td valign="top"><p>L&auml;&szlig;t sich nicht nur innerhalb von Vorlagen verwenden, sondern <em>auch in &Uuml;berschriften, Bildunterschrift</em> etc. </p></td>
        </tr>
    </tbody>
</table>
</div><div style="margin-top:10px;">
<table width="100%" cellspacing="0" cellpadding="5" border="0">
    <tbody class="reptab">
        <tr class="reptab_head">
            <td colspan="2">RT: [<img src="img/leer.gif" border="0" width="0" height="0" alt="" />i] Text [/i] </td>
		</tr>
        <tr>
            <td width="100" valign="top"><strong>Verwendung:</strong></td>
            <td valign="top">
	Hiermit läßt sich ein Text <i>kursiv</i> auszeichnen.

</td>
        </tr>
        <tr>
            <td width="100" valign="top"><strong>Schreibweise:</strong></td>
            <td valign="top">[<img src="img/leer.gif" border="0" width="0" height="0" alt="" />i] Text [/i]</td>
        </tr>
        <tr>
            <td width="100" valign="top"><strong>Ausgabe-Format:</strong></td>
            <td valign="top"> <i>Text in KURSIVER Auszeichnung</i> und wieder normal</td>
        </tr>
        <tr>
            <td width="100" valign="top"><strong>Bemerkung:</strong></td>
            <td valign="top"><p>L&auml;&szlig;t sich nicht nur innerhalb von Vorlagen verwenden, sondern <em>auch in &Uuml;berschriften, Bildunterschrift</em> etc.</p></td>
        </tr>
    </tbody>
</table>
</div><div style="margin-top:10px;">
<table width="100%" cellspacing="0" cellpadding="5" border="0">
    <tbody class="reptab">
        <tr class="reptab_head">
            <td colspan="2">RT: [<img src="img/leer.gif" border="0" width="0" height="0" alt="" />u] Text [/u] </td>
		</tr>
        <tr>
            <td width="100" valign="top"><strong>Verwendung:</strong></td>
            <td valign="top">
	Hiermit läßt sich ein Text <u>unterstrichen</u> auszeichnen

</td>
        </tr>
        <tr>
            <td width="100" valign="top"><strong>Schreibweise:</strong></td>
            <td valign="top">[<img src="img/leer.gif" border="0" width="0" height="0" alt="" />u]Text in UNTERSTRICHENER Auszeichnung[/u] und wieder normal</td>
        </tr>
        <tr>
            <td width="100" valign="top"><strong>Ausgabe-Format:</strong></td>
            <td valign="top"> <u>Text in UNTERSTRICHENER Auszeichnung</u> und wieder normal</td>
        </tr>
        <tr>
            <td width="100" valign="top"><strong>Bemerkung:</strong></td>
            <td valign="top"><p>L&auml;&szlig;t sich nicht nur innerhalb von Vorlagen verwenden, sondern <em>auch in &Uuml;berschriften, Bildunterschrift</em> etc.</p></td>
        </tr>
    </tbody>
</table>
</div><div style="margin-top:10px;">
<table width="100%" cellspacing="0" cellpadding="5" border="0">
    <tbody class="reptab">
        <tr class="reptab_head">
            <td colspan="2">RT: [<img src="img/leer.gif" border="0" width="0" height="0" alt="" />s] Text [/s] </td>
		</tr>
        <tr>
            <td width="100" valign="top"><strong>Verwendung:</strong></td>
            <td valign="top">
	Hiermit läßt sich ein Text <strike>durchgestrichen</strike> auszeichnen

</td>
        </tr>
        <tr>
            <td width="100" valign="top"><strong>Schreibweise:</strong></td>
            <td valign="top">[<img src="img/leer.gif" border="0" width="0" height="0" alt="" />s]Text in DURCHGESTRICHENER Auszeichnung[/s] und wieder normal</td>
        </tr>
        <tr>
            <td width="100" valign="top"><strong>Ausgabe-Format:</strong></td>
            <td valign="top"> <strike>Text in DURCHGESTRICHENER Auszeichnung</strike> und wieder normal</td>
        </tr>
        <tr>
            <td width="100" valign="top"><strong>Bemerkung:</strong></td>
            <td valign="top"><p>L&auml;&szlig;t sich nicht nur innerhalb von Vorlagen verwenden, sondern <em>auch in &Uuml;berschriften, Bildunterschrift</em> etc.</p></td>
        </tr>
    </tbody>
</table>
</div><div style="margin-top:10px;">
<table width="100%" cellspacing="0" cellpadding="5" border="0">
    <tbody class="reptab">
        <tr class="reptab_head">
            <td colspan="2">RT: [<img src="img/leer.gif" border="0" width="0" height="0" alt="" />BR] </td>
		</tr>
        <tr>
            <td width="100" valign="top"><strong>Verwendung:</strong></td>
            <td valign="top">
	An der Verwendungsstelle wird ein Zeilensprung erzwungen.

</td>
        </tr>
        <tr>
            <td width="100" valign="top"><strong>Schreibweise:</strong></td>
            <td valign="top">Erzwungener Zeilensprung &gt;[<img src="img/leer.gif" border="0" width="0" height="0" alt="" />BR]&lt; genau hier</td>
        </tr>
        <tr>
            <td width="100" valign="top"><strong>Ausgabe-Format:</strong></td>
            <td valign="top"> Erzwungener Zeilensprung &gt;<br />&lt; genau hier</td>
        </tr>
        <tr>
            <td width="100" valign="top"><strong>Bemerkung:</strong></td>
            <td valign="top"><p>L&auml;&szlig;t sich nicht nur innerhalb von Vorlagen verwenden, sondern auch in Artikeltiteln, Bildunterschrift etc. Selbst bei Verwendung des GT-Mod's innerhalb des Textes.</p></td>
        </tr>
    </tbody>
</table>
</div><div style="margin-top:10px;">
<table width="100%" cellspacing="0" cellpadding="5" border="0">
    <tbody class="reptab">
        <tr class="reptab_head">
            <td colspan="2">RT: {<img src="img/leer.gif" border="0" width="0" height="0" alt="" />SHOW_CONTENT:MODE,id,id,id} </td>
		</tr>
        <tr>
            <td width="100" valign="top"><strong>Verwendung:</strong></td>
            <td valign="top">
	Dient zum Anzeigen mehrer Contentparts (&gt;=V1.2.8)

</td>
        </tr>
        <tr>
            <td width="100" valign="top"><strong>Schreibweise:</strong></td>
            <td valign="top">{<img src="img/leer.gif" border="0" width="0" height="0" alt="" />SHOW_CONTENT:MODE,id,id,id}</td>
        </tr>
        <tr>
            <td width="100" valign="top"><strong>Ausgabe-Format:</strong></td>
            <td valign="top"> {<img src="img/leer.gif" border="0" width="0" height="0" alt="" />SHOW_CONTENT:CP,1,2,3}<br /><br />
Die ContentParts mit der CP-ID 1,2 und 3 würden an dieser Stelle ausgegeben.</td>
        </tr>
        <tr>
            <td width="100" valign="top"><strong>Bemerkung:</strong></td>
            <td valign="top">aufsteigenddes MODE's:<br />
<br />
1. {<img src="img/leer.gif" border="0" width="0" height="0" alt="" />SHOW_CONTENT:<strong>CP</strong>, cp-id, cp-id, cp-id} <br />
&nbsp;&nbsp;&nbsp; Ausgabe der ContentParts, die IDs sind die CP-IDs.<br />
<br />
2. {<img src="img/leer.gif" border="0" width="0" height="0" alt="" />SHOW_CONTENT:<strong>CPA</strong>, art-id, art-id, art-id} <br />
&nbsp;&nbsp;&nbsp; Aufsteigende Ausgabe der CPs, jedoch sind die IDs die Artikel-IDs.<br />
<br />
3. {<img src="img/leer.gif" border="0" width="0" height="0" alt="" />SHOW_CONTENT:<strong>CPAD</strong>, art-id, art-id, art-id} <br />
&nbsp;&nbsp;&nbsp; Absteigende Auagabe der CPs. IDs sind Artikel-IDs. <br />
&nbsp;&nbsp;&nbsp; (Die Seitenausgabe verlangsamt sich etwas).
<p></p>
<p>4. {<img src="img/leer.gif" border="0" width="0" height="0" alt="" />SHOW_CONTENT:<strong>AS</strong>, art-id, art-id, art-id} <br />
&nbsp;&nbsp;&nbsp; Ausgabe der Artikel-Schlagtexte. IDs sind Artikel-IDs.<br />
&nbsp;&nbsp;&nbsp; - <b>Sortierung: </b><br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - <b>AS:</b> Sortiert nach vorhandener Reihenfolge<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - <b>ASL:</b> Sortiert nach &quot;lifedate ASC&quot; (&quot;von Datum&quot; aufsteigend)<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - <b>ASLD:</b> Sortiert nach &quot;lifedate DESC&quot; (&quot;von Datum&quot; absteigend)<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - <b>ASK:</b> Sortiert nach &quot;killdate ASC&quot; (&quot;bis Datum&quot; aufsteigend)<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - <b>ASKD:</b> Sortiert nach &quot;killdate DESC&quot; (&quot;bis Datum&quot; absteigend)<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - <b>ASC:</b> Sortiert nach &quot;changedate ASC&quot; (&quot;Editierdatum&quot; aufsteigend)<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - <b>ASCD:</b> Sortiert nach &quot;changedate DESC&quot; (&quot;Editierdatum&quot; absteigend)<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - <b>ASR:</b> Sortiert nach &quot;random&quot; (zuf&auml;llig)</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - <b>AxxxP:</b> Die Artikel-Priorisierung wird ber&uuml;cksichtigt <br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp; (Z.B. ASP oder ASLDP ....)</p>
<p>&nbsp; &nbsp; - <b>Moduserweiterung: </b><br />
&nbsp; &nbsp;&nbsp; &nbsp; - <b>Mode|Limit|Template:</b> Angabe Artikel-Listentemplate oder Anzahl <br />
&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp; auszugebender Artikel (Z.B. ASL|3, ... , ASL|MeinTemplate.tmpl, ...)<br />
&nbsp;&nbsp;&nbsp;&nbsp; &nbsp; &nbsp; Z.B.: <br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;  {<img src="img/leer.gif" border="0" width="0" height="0" alt="" />SHOW_CONTENT:<b>AS|MeinTemplate.tmpl</b>, art-id, art-id, art-id}<br />
&nbsp;&nbsp;&nbsp;&nbsp; &nbsp; &nbsp; gibt die Inhalte der angegebenen Artikel aus. <br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; {<img src="img/leer.gif" border="0" width="0" height="0" alt="" />SHOW_CONTENT:<b>AS|MeinTemplate.tmpl</b>, {CURRENT_ARTICLEID}}<br />
&nbsp;&nbsp;&nbsp;&nbsp; &nbsp; &nbsp; gibt den Inhalt des aktuellen Artikels (Detailmodus) aus. <br />
&nbsp;&nbsp;&nbsp;&nbsp; &nbsp; &nbsp; Das Template befindet sich im Verzeichnis  <br />
&nbsp;&nbsp;&nbsp;&nbsp; &nbsp; &nbsp; /template/inc_cntpart/articlesummary/list/..</p>
<p><strike>5. <img src="img/leer.gif" border="0" width="0" height="0" alt="" />SHOW_CONTENT:<b>CAS</b>, cat-id, cat-id, cat-id}<br />
&nbsp;&nbsp;&nbsp; Ausgabe der Artikel-Schlagtexte. IDs sind Kategorie-IDs.</strike></p></td>
        </tr>
    </tbody>
</table>
</div>
		 
		
		<br /><br />
		<div class="sub">
		Artikel erstellt am: Freitag, 13. August 2004 <br /> Letzte &Auml;nderung: Dienstag, 28. Januar 2014	
		</div>
				
	</div>
	
<div id="footer">





	<table width="97%" border="0" cellspacing="0" cellpadding="0">
		<tr>
			<td valign="bottom">	
			&copy; phpwcms-docu 2004-2015
			<img src="img/leer.gif" border="0" width="10" height="0" alt="" /><a href="impressum.phtml" class="phpwcmsIntLink"><img src="template/lang/all/icons/imprint.gif" width="9" height="15" alt="Impressum" title="Impressum" border="0" /></a>&nbsp; 
			<a href="sitemap_de.phtml" class="phpwcmsIntLink"><img src="template/lang/all/icons/sitemap.gif" width="19" height="15" alt="Sitemap" title="Sitemap" border="0" /></a>&nbsp; 
			<a href="gaestebuch.phtml" class="phpwcmsIntLink"><img src="template/lang/all/icons/gbook.gif" width="20" height="16" alt="Ins G&auml;stebuch eintragen" title="Ins G&auml;stebuch eintragen" border="0" /></a>&nbsp; 
			<a href="#" onclick="BookMark_Page();return false;" title="" class="phpwcmsBookmarkLink"><img src="template/lang/all/icons/favo.gif" width="12" height="15" alt="Seite als Bookmark speichern" title="Seite als Bookmark speichern" border="0" /></a>&nbsp; 
			     
			</td>
			<td valign="bottom" style="padding-right:25px;">
			
			
			
			</td>		
			<td width="150">
			</td>
		</tr>
	</table>
</div><br/>

</div>
</body>
</html>