<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<!--
	phpwcms | free open source content management system
	created by Oliver Georgi (oliver at phpwcms dot de) and licensed under GNU/GPL.
	phpwcms is copyright 2003-2006 of Oliver Georgi. Extensions are copyright of\
	their respective owners. Visit project page for details: http://www.phpwcms.org/
//-->
<title>phpwcms documentation | Content Part &quot;Artikellink&quot;</title>
  <meta http-equiv="content-type" content="text/html; charset=iso-8859-1" />
  <meta http-equiv="content-style-type" content="text/css" />
  <script src="template/inc_js/frontend.js" type="text/javascript"></script>
  <style type="text/css" media="all">
  /* <![CDATA[ */
    body {
      margin: 0;
      padding-top: 0;
      padding-bottom: 0;
      padding-left: 0;
      padding-right: 0;

      background-color: #FFFFFF;
      color: #000000;
    }
    a, a:link, a:active, a:visited, a:hover { color: #FF9900; }
    a:visited { color: #FF9900; }
    a:active { color: #FF9900; }
  /* ]]> */
  </style>
  <style type="text/css">
  /* <![CDATA[ */
    @import url("template/inc_css/frontend.css");
    @import url("template/inc_css/nlu_navi1_docu.css");
  /* ]]> */
  </style>


<META NAME="Title" CONTENT="Die phpWCMS Dokumentation">
<meta name="author" content="Oliver Frohnert">
<meta name="Publisher" content="Oliver Frohnert">
<meta name="Copyright" content="Oliver Frohnert">
<meta name="keywords" content="frohnert,documentation, dokumentation, phpwcms, cms, opensource, open source">
<meta name="description" content="Das Dokumentations Projekt für das Open Source CMS phpWCMS">
<meta name="Audience" content="Alle">
<meta name="Content-language" content="DE">
<META NAME="robots"      CONTENT="index,follow">
<META NAME="expires" CONTENT="0">
<meta name="revisit-after" content="7 days">
<meta name="resource-type" content="document">
<meta name="distribution" content="Global">
<meta name="generator" content="PHPWCMS">

  <!--[if lt IE 7]>
  <style type="text/css">
    body { behavior: url("template/inc_css/specific/csshover2.htc"); }
    img { behavior: url("template/inc_css/specific/pngbehavior.htc"); }
  </style>
  <![endif]-->
</head>
<body>
<table border="0" cellspacing="0" cellpadding="0" width="760" bgcolor="#ffffff" class="maintable" align="center">
<tr>
<td colspan="2" style="height:60px;"  bgcolor="#ffffff"><a name="top"></a><table width="760" height="135" border="0" cellpadding="0" cellspacing="0">
  <tr valign="top">
    <td width="1334" height="122" colspan="6"><IMG src="/template/lang/de/header.jpg" alt="" border="0">
</td>
  </tr>
  <tr>
	<td height="27" background="template/lang/all/top_menu.jpg"><table width="570" border="0" align="left" cellpadding="0" cellspacing="0">
      <tr>
        <td align="center" width="254"><a href="deutsche_version.phtml"><img src="picture/flags/de.gif" width="16" height="10" hspace="10" border="0"  alt="Deutsche Version" title="Deutsche Version"></a>
<a href="english_version.phtml"><img src="picture/flags/gb.gif" width="16" height="10" hspace="10" border="0"  alt="English Version" title="English Version"></a></td>
        <td valign="middle"><div align="center"><a href="replacement_tags_de.phtml"><img src="content/gt/8c10fcb16c44a7b9c26a5a932c5e4ae9.png" alt="Replacement Tags" title="Replacement Tags" width="115" height="13" border="0" /></a></div></td>
        <td width="30" valign="middle"><div align="center"><img src="template/lang/all/sep.gif" width="5" height="5" border="0"></div></td>
        <td valign="middle"><div align="center"><a href="content_parts_de.phtml"><img src="content/gt/02725c45a346fbf433a4c83e02d8dc5a.png" alt="Content Parts" title="Content Parts" width="94" height="13" border="0" /></a></div></td>
        <td width="30" valign="middle"><div align="center"><img src="template/lang/all/sep.gif" width="5" height="5" border="0"></div></td>
        <td valign="middle"><div align="center"><a href="links_de.phtml"><img src="content/gt/2c41bfb28d6dd3d4bbc8bb7688fd62ee.png" alt="Links" title="Links" width="36" height="13" border="0" /></a></div></td>
        <td width="30" valign="middle"><div align="center"><img src="template/lang/all/sep.gif" width="5 " height="5" border="0"></div></td>
        <td valign="middle"><div align="center"><a href="impressum.phtml"><img src="content/gt/d7380cf01602233e53be03b55123cf90.png" alt="Impressum" title="Impressum" width="64" height="13" border="0" /></a></div></td>
     </tr>
    </table>    </td>
  </tr>
</table>
</td>
</tr>
<tr>
<td valign="top" width="185" background="img/menu.gif"><table width="180" border="0" cellpadding="0" cellspacing="0">
  <tr>
    <td width="180" height="20">&nbsp;</td>
  </tr>
  <tr>
    <td style="padding-left: 1px;"><div class="nlu_navi1_docu">
<ul>
	<li class="sub_no"><a href="news_de.phtml">News</a></li>
	<li class="sub_no"><a href="inst_de.phtml">Installation &amp; Upgrade</a></li>
	<li class="sub_ul active"><a href="die_docu.phtml">Die Docu</a>
	<ul>
		<li class="sub_ul active"><a href="verwaltung_artikel.phtml">Artikel</a>
		<ul>
			<li class="sub_no"><a href="artikel_erstellen.phtml">Artikel erstellen</a></li>
			<li class="sub_no"><a href="artikel_editieren.phtml">Artikel bearbeiten</a></li>
			<li class="sub_no"><a href="artikel_organisation.phtml">Artikel Organisation</a></li>
			<li class="sub_ul active"><a href="content_parts_de.phtml">Content Parts</a>
			<ul>
				<li class="sub_no"><a href="einfacher_text.phtml">Einfacher Text</a></li>
				<li class="sub_no"><a href="html_.phtml">HTML</a></li>
				<li class="sub_no"><a href="wysiwyg_html_.phtml">WYSIWYG HTML</a></li>
				<li class="sub_no"><a href="code_.phtml">Code</a></li>
				<li class="sub_no"><a href="text_mit_bild.phtml">Text mit Bild</a></li>
				<li class="sub_no"><a href="bilder.phtml">Bilder</a></li>
				<li class="sub_no"><a href="aufzahlung.phtml">Aufzählung</a></li>
				<li class="sub_no"><a href="liste.phtml">Liste</a></li>
				<li class="sub_no"><a href="link_e-mail_.phtml">Link &amp; E-Mail</a></li>
				<li class="sub_no"><a href="linkliste.phtml">Linkliste</a></li>
				<li class="sub_no active"><a href="artikellink.phtml">Artikellink</a></li>
				<li class="sub_no"><a href="artikelmenu.phtml">Artikelmenü</a></li>
				<li class="sub_no"><a href="multimedia_.phtml">Multimedia</a></li>
				<li class="sub_no"><a href="dateiliste.phtml">Dateiliste</a></li>
				<li class="sub_no"><a href="ecard_de.phtml">E-Card</a></li>
				<li class="sub_no"><a href="e-mail_kontaktformular.phtml">E-Mail Kontaktformular</a></li>
				<li class="sub_no"><a href="e-mail_formular.phtml">E-Mail Formulargenerator</a></li>
				<li class="sub_no"><a href="newsletter_de.phtml">Newsletter</a></li>
				<li class="sub_no"><a href="suche_.phtml">Suche</a></li>
				<li class="sub_no"><a href="gastebuch_komm.phtml">Gästebuch / Komm.</a></li>
				<li class="sub_no"><a href="sitemap_.phtml">Sitemap</a></li>
				<li class="sub_no"><a href="angebot.phtml">Angebot</a></li>
				<li class="sub_no"><a href="ext._content_.phtml">Ext. Content</a></li>
				<li class="sub_no"><a href="rss_feed_de.phtml">RSS Feed</a></li>
				<li class="sub_no"><a href="bildwechsel.phtml">Bildwechsel</a></li>
				<li class="sub_no"><a href="contentpart_alias_de.phtml">Contentpart Alias</a></li>
			</ul>
			</li>
		</ul>
		</li>
		<li class="sub_no"><a href="dateien_hinzufuegen.phtml">Datei</a></li>
		<li class="sub_no"><a href="verwaltung_module.phtml">Module</a></li>
		<li class="sub_no"><a href="verwaltung_nachricht.phtml">Nachricht</a></li>
		<li class="sub_no"><a href="verwaltung_chat.phtml">Chat</a></li>
		<li class="sub_no"><a href="verwaltung_profil.phtml">Profil</a></li>
		<li class="sub_no"><a href="verwaltung_admin.phtml">Admin</a></li>
	</ul>
	</li>
	<li class="sub_no"><a href="add_on.phtml">Add Ons</a></li>
	<li class="sub_no"><a href="fehlermeldungen.phtml">Fehlermeldungen</a></li>
	<li class="sub_no"><a href="suche.phtml">Suche</a></li>
	<li class="sub_no"><a href="kontakt.phtml">Kontakt</a></li>
	<li class="sub_no"><a href="faq_de.phtml">FAQ</a></li>
</ul>
</div></td>
  </tr>
   <tr>
    <td style="padding:10px; color:#000000;">
<img src="picture/seperate.gif" border="0" alt="" /><br /><br />
<img src="content/gt/4ed113c59a3746cabc12bacb98382a26.png" alt="Letzte Finale Version:" title="Letzte Finale Version:" width="149" height="13" border="0" /><br /><br />
<img src="content/gt/8da415b6626786310c726135c1d9ce1a.png" alt="phpwcms 1.3.0" title="phpwcms 1.3.0" width="83" height="13" border="0" /><br />
<img src="content/gt/bec27e6d56965cbe357a54097865c5f0.png" alt="Vö: 07.03.2007" title="Vö: 07.03.2007" width="89" height="13" border="0" /><br /><br />
<a href="http://www.phpwcms.de/forum/viewtopic.php?t=14006"><img src="content/gt/17ec582052b0d3ac3eddfbb9e5ff97f1.png" alt="weiter..." title="weiter..." width="52" height="13" border="0" /></a><br /><br />
<img src="picture/seperate.gif" border="0" alt="" /><br /><br />
</TD>
  </tr>
  <tr>
    <td align="center"><span>
</span><br />WERBUNG<br /><br /><img src="picture/seperate.gif" border="0" alt="" /><P>
</td>
  </tr>
<tr>
    <td height="20">&nbsp;</td>
  </tr>
  <tr>
    <td align="center"></td>
  </tr>
  <tr>
    <td align="center" height="20">&nbsp</td>
  </tr>
</table>


</body>
</html>
</td>
<td valign="top" width="555" bgcolor="#ffffff" class="maincontent"><img src="img/leer.gif" border="0" width="10" height="1" alt="" />
<br />
<a href="deutsche_version.phtml">Deutsch</a> <span class="breadcrumb_spacer">&gt;</span> <a href="die_docu.phtml">Die Docu</a> <span class="breadcrumb_spacer">&gt;</span> <a href="verwaltung_artikel.phtml">Artikel</a> <span class="breadcrumb_spacer">&gt;</span> <a href="content_parts_de.phtml">Content Parts</a> <span class="breadcrumb_spacer">&gt;</span> Artikellink
<br />
<HR>
<br />
<a name="jump122"></a><h1>Content Part &quot;Artikellink&quot;</h1><div style="margin:25px 0 0 0; padding:0 0 0 0; clear:both;"></div><table width="158" border="0" cellspacing="0" cellpadding="0" align="left">
<tr><td class="image_td"><a href="zoom/MTc0ZjI4ZDY3ZDZiYTRjYWU3MjQyMzk2YzhmZmYzYzIucG5nP3dpZHRoPSI0MDAiIGhlaWdodD0iMzAwIg.html" onclick="checkClickZoom();clickZoom('zoom/MTc0ZjI4ZDY3ZDZiYTRjYWU3MjQyMzk2YzhmZmYzYzIucG5nP3dpZHRoPSI0MDAiIGhlaWdodD0iMzAwIg.html','previewpic','width.html');return false;.html"><img src="content/images/ec3be143e158120e1649916b668e5699.png" width="150" height="141" border="0" class="image_img" alt="artikellink.png" /></a></td><td><img src="img/leer.gif" width="8" height="1" border="0" alt="" /></td></tr>
</table><div class="articleText"><table height="158" cellspacing="0" cellpadding="0" width="70%" border="0">
    <tbody>
        <tr>
            <td>
            <p align="justify"><strong>Artikellink (optional):</strong> Hier erscheinen alle gew&auml;hlten Artikel, die dem Besucher der Website angeboten werden.<br/>
            <br/>
            <strong>Artikel:</strong> Hier sind alle Artikel aufgelistet, die die Website enth&auml;lt. <font color="#cc0033"><strong>TIPP</strong></font>: Leider wird in einigen Browsern die Liste nicht automatisch sortiert. Klicken Sie einmal auf das Symbol <img src="picture/../img/button/list_remove.gif" border="0" alt="" />&nbsp;, um die Liste alphabetisch zu sortieren. <br/>
            <br/>
            <img src="picture/../img/button/list_copy.gif" border="0" alt="" />&nbsp;Mit diesem Knopf k&ouml;nnen Sie in der Liste &bdquo;Artikel&ldquo; gew&auml;hlte Artikel der Liste &bdquo;Artikellink&ldquo; hinzuf&uuml;gen. <font color="#cc0033"><strong>TIPP</strong></font>: Sie k&ouml;nnen mehrere Artikel mit gehaltener [Strg]-Taste (Windows) bzw. [&#65533;]-Taste (Macintosh) ausw&auml;hlen.</p>
            </td>
        </tr>
    </tbody>
</table>
<p align="justify">&nbsp;<br/>
<img src="picture/../img/button/list_remove.gif" border="0" alt="" />&nbsp;Mit diesem Knopf k&ouml;nnen Sie in der Liste &bdquo;Artikellink&ldquo; gew&auml;hlte Artikel entfernen.<br/>
<em>&nbsp;<br/>
</em><img src="picture/../img/button/list_pos_up.gif" border="0" alt="" />&nbsp;Mit diesem Knopf k&ouml;nnen Sie in der Liste &bdquo;Artikellink&ldquo; gew&auml;hlte Artikel um eine Position nach oben verschieben.<br/>
&nbsp;<br/>
<img src="picture/../img/button/list_pos_down.gif" border="0" alt="" />&nbsp;Mit diesem Knopf k&ouml;nnen Sie in der Liste &bdquo;Artikellink&ldquo; gew&auml;hlte Artikel um eine Position nach unten verschieben</p></div><div align="right"><a href="#top"><img src="img/article/top_link_0.gif" border="0" alt="" /></a></div>
<table width="100%"  border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td colspan="2"><HR></td>
  </tr>
  <tr>
    <td width="50%">Artikel erstellt: 2004/08/25</td>
    <td align="right" width="50%">Letzte Änderung:2005/06/13</td>
  </tr>
  <tr>
    <td colspan="2">&nbsp;</td>
  </tr>
  <tr>
    <td colspan="2" class="comment">Wenn Sie einen Fehler entdecken eine Ergänzung oder Frage haben benutzen Sie bitte folgendes <a href="#" onClick="javascript:window.open('./content/pages/nachricht.htm','frage','width=400, height=250, screenX=440,screenY=200,menubar=no,statusbar=yes,scrollbar=yes,resizable=no');" target="" style="max-width:148px; overflow:hidden;"><u>Formular</u></a>.<br /><br />
Hat Ihnen oder Ihrem Kunden diese Docu weitergeholfen ? Dann würde ich mich freuen wenn Sie das Projekt unterstützen würden. Bitte nutzen Sie dafür diesen <a href="#paypal">PayPal</a> Link. Jeder Betrag ist möglich und hilft der Weiterentwicklung und Aktualisierung dieser Dokumentation.<br />
Diese Seite nutzt die version:</td>
  </tr>
  <tr>

    <td colspan="2"><img src="img/leer.gif" border="0" width="10" height="10" alt="" /></td>
  </tr>
</table>
</td>
</tr>
<tr>
<td colspan="2" style="height:10px;"  bgcolor="#ffffff" class="footer"><table width="100%" height="20" background="img/footer.gif" cellpadding="0" cellspacing="0" border="0">
	<tr><td width="180" align="center" valign="middle">11 User online</td>
	<td>
	<table width="100%"cellpadding="0" cellspacing="0" border="0">
   <tr>
    <td align="center"><a href="javascript:history.back();" target="_top" title="go back"><img src="picture/back_.gif" border="0" alt="Zurueck"><img src="content/gt/13c1f733e9ee7693bf810fd5f035d0b7.png" alt="Zurück" title="Zurück" width="45" height="13" border="0" /></a></td>
	<td align="center"><a href="sitemap_de.phtml"><img src="picture/sitemap_.gif" border="0"  alt="Sitemap"><img src="content/gt/38062c01670c74843cc0b291d94966c6.png" alt="Sitemap" title="Sitemap" width="50" height="13" border="0" /></a></td>
	<td align="center"><a href="138.122.1.1.1.0.phtml" target="_blank"><img src="picture/print_.gif" border="0" alt="Drucken"><img src="content/gt/811a35c6cb2c5555a2f32d85b1bb5deb.png" alt="Drucken" title="Drucken" width="52" height="13" border="0" /></a></td>
	<td align="center"><a href="gaestebuch.phtml"><img src="picture/icon_gaestebuch.gif" border="0" align="top" alt="Gästebuch"><img src="content/gt/1257c79a2b085b5641453b0f6e0fe1fd.png" alt="Gästebuch" title="Gästebuch" width="66" height="13" border="0" /></a></td>
	<td align="center"><a href="#" onclick="BookMark_Page();return false;" title=""><img src="picture/favoriten_.gif" border="0"  alt="Lesezeichen"><img src="content/gt/7ce0fe74ab60b3da559a77c54fb85a80.png" alt="Lesezeichen" title="Lesezeichen" width="78" height="13" border="0" /></a></td>
    </tr>
</table></td>
	</tr>
</table>
<img src="img/leer.gif" border="0" width="760" height="10" alt="" /><br />
</td>
</tr>
</table>

</body>
</html>