<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<!--
	phpwcms | free open source content management system
	created by Oliver Georgi (oliver at phpwcms dot de) and licensed under GNU/GPL.
	phpwcms is copyright 2003-2007 of Oliver Georgi. Extensions are copyright of
	their respective owners. Visit project page for details: http://www.phpwcms.org/
//-->
<title>phpwcms-docu for  phpwcms :: web based content management system | E-Card Beispiel{D:8/15/2005,30,neuR.gif} | E-Card Beispieltexte</title>
  <meta http-equiv="content-type" content="text/html; charset=iso-8859-1" />
  <meta http-equiv="content-style-type" content="text/css" />
  <script src="template/inc_js/frontend.js" type="text/javascript"></script>
  <style type="text/css">
  <!-- 
    @import url("template/inc_css/mpl_docu.css");
    @import url("template/inc_css/mpl_frontend.css");
    @import url("template/inc_css/mpl_menu.css");
    @import url("template/inc_css/mpl_objects.css");
  //-->
  </style>
<script type="text/javascript" language="javascript">
<!--
function MM_jumpMenu(targ,selObj,restore){ //v3.0
  eval(targ+".location='"+selObj.options[selObj.selectedIndex].value+"'");
  if (restore) selObj.selectedIndex=0;
}

function MM_findObj(n, d) { //v4.01
  var p,i,x;  if(!d) d=document; if((p=n.indexOf("?"))>0&&parent.frames.length) {
    d=parent.frames[n.substring(p+1)].document; n=n.substring(0,p);}
  if(!(x=d[n])&&d.all) x=d.all[n]; for (i=0;!x&&i<d.forms.length;i++) x=d.forms[i][n];
  for(i=0;!x&&d.layers&&i<d.layers.length;i++) x=MM_findObj(n,d.layers[i].document);
  if(!x && d.getElementById) x=d.getElementById(n); return x;
}

function MM_jumpMenuGo(selName,targ,restore){ //v3.0
  var selObj = MM_findObj(selName); if (selObj) MM_jumpMenu(targ,selObj,restore);
}
//-->
</script>
<meta name="Title" content="Die phpWCMS Dokumentation" />
<meta name="author" content="Oliver Frohnert, Mario Perez Leal" />
<meta name="Publisher" content="Oliver Frohnert, Mario Perez Leal, creacion" />
<meta name="Copyright" content="Oliver Frohnert, Mario Perez Leal, creacion" />
<meta name="keywords" content="frohnert, perez leal, creacion, documentation, dokumentation, phpwcms, cms, opensource, open source, docu" />
<meta name="description" content="Das Dokumentations Projekt für das Open Source CMS phpWCMS" />
<meta name="Audience" content="Alle" />
<meta name="Content-language" content="DE" />
<meta name="robots" content="index,follow" />
<meta name="expires" content="0" />
<meta name="revisit-after" content="7 days" />
<meta name="resource-type" content="document" />
<meta name="distribution" content="Global" />
<meta name="generator" content="PHPWCMS" />
<meta name="verify-v1" content="1ZpxZ7AZsjm7PxjqXQVus0eiUYqOsp5URTJn9q4KNz8=" />
  <!--[if lt IE 7]>
  <style type="text/css">
    body { behavior: url("template/inc_css/specific/csshover2.htc"); }
    img { behavior: url("template/inc_css/specific/pngbehavior.htc"); }
  </style>
  <![endif]-->
</head>
<body id="myid_355">
<div id="container"><a name="top" id="top"></a>


	<div id="head">
		
	<div id="mainnavi">
		<div class="fleft"><a href="deutsche_version.phtml">Startseite</a> | <a href="news_de.phtml">News</a> | <span style="text-decoration:none;font-weight:bold;"><a href="die_docu.phtml">Die Docu</a></span> | <a href="Nuetzliche_Links_und_Tools.phtml">Links &amp; Tools</a> | <a href="downloads.phtml">Downloads</a> | <a href="kontakt.phtml">Kontakt</a> | <a href="faq_de.phtml">FAQ</a> | <a href="http://forum.phpwcms.org/" target="_blank">Forum</a> | <a href="howto_de.phtml">HowTo</a></div>				
		<div class="sys">Donnerstag, 7. März 2013<img src="img/leer.gif" border="0" width="5" height="1" alt="" />|<img src="img/leer.gif" border="0" width="5" height="1" alt="" />4 User online<img src="img/leer.gif" border="0" width="10" height="1" alt="" />
		<a href="deutsche_version.phtml" title="Deutsche Version"><img src="picture/../template/lang/all/flag_de.gif" border="0" alt="" /></a>
		<a href="english_version.phtml"  title="English version"><img src="picture/../template/lang/all/flag_en.gif" border="0" alt="" /></a>
		</div>
	</div>
	
	<a href="./" title="phpwcms-docu Startseite aufrufen" class="homelink">
	<span>&raquo; Zur phpwcms-docu Startseite</span></a>
	<h2>phpwcms-docu - Die Dokumentation f&uuml;r f&uuml;r das CMS phpWCMS</h2>
	<p>phpwcms-docu ist eine Art Kompass, der Ihnen die M&ouml;glichkeiten von phpWcms aufzeigt und Sie erfolgreich, ohne gro&szlig;e Umwege, zu Ihrer fertigen Web-Anwendung f&uuml;hren soll.
	</p>
	</div>

	
	<div id="left">
	<div class="leftnav" style="margin-top:24px;">
	
<div id="ul_div_309">
<ul>
	<li class="sub_no"><a href="download-dev-versionen.phtml">Download Dev Versionen</a></li>
	<li class="sub_no sub_ul_true"><a href="installation_und_upgrade_von_phpwcms.phtml">Installation &amp; Upgrade</a></li>
	<li class="sub_ul"><a href="verwaltung_artikel.phtml">Artikel</a>
	<div id="ul_div_82">
	<ul>
		<li class="sub_no"><a href="artikel_erstellen.phtml">Artikel erstellen</a></li>
		<li class="sub_no"><a href="artikel_editieren.phtml">Artikel bearbeiten</a></li>
		<li class="sub_no sub_ul_true"><a href="artikel_organisation.phtml">Artikel Organisation</a></li>
		<li class="sub_ul"><a href="content_parts_de.phtml">Content Parts</a>
		<div id="ul_div_100">
		<ul>
			<li class="sub_no"><a href="einfacher_text.phtml">Einfacher Text</a></li>
			<li class="sub_no"><a href="content_part_html_de.phtml">HTML</a></li>
			<li class="sub_no"><a href="content_part_wysiwyg_html_de.phtml">WYSIWYG HTML</a></li>
			<li class="sub_no"><a href="content_part_code_de.phtml">Code</a></li>
			<li class="sub_no"><a href="content_part_text_mit_bild.phtml">Text mit Bild</a></li>
			<li class="sub_no"><a href="content_part_bilder_div.phtml"><span style="text-decoration:line-through;font-size:10px;">Bilder &lt;DIV&gt;</span></a></li>
			<li class="sub_no"><a href="content_part_bilder.phtml">Bilder</a></li>
			<li class="sub_no"><a href="content_part_aufzaehlung.phtml">Aufzählung</a></li>
			<li class="sub_no"><a href="content_part_liste.phtml">Liste</a></li>
			<li class="sub_no"><a href="content_part_link_und_e-mail.phtml">Link &amp; E-Mail</a></li>
			<li class="sub_no"><a href="content_part_linkliste.phtml">Linkliste</a></li>
			<li class="sub_no"><a href="content_part_artikellink.phtml">Artikellink</a></li>
			<li class="sub_no"><a href="content_part_teaser_artikellink.phtml"><span style="text-decoration:line-through;font-size:10px;">Teaser / Artikellink</span></a></li>
			<li class="sub_no"><a href="content_part_artikelmenue.phtml">Artikelmenü</a></li>
			<li class="sub_no"><a href="content_part_multimedia_de.phtml">Multimedia</a></li>
			<li class="sub_no"><a href="content_part_dateiliste.phtml">Dateiliste</a></li>
			<li class="sub_ul"><a href="content_part_ecard_de.phtml">E-Card</a>
			<div id="ul_div_143">
			<ul>
				<li class="sub_no active"><a href="beispiel_content_part_ecard.phtml">E-Card Beispiel</a></li>
			</ul>
			</div>
			</li>
			<li class="sub_no"><a href="content_part_formular.phtml">Formular</a></li>
			<li class="sub_no sub_ul_true"><a href="content_part_e-mail_formulargenerator.phtml">E-Mail Form. [OLD]</a></li>
			<li class="sub_no"><a href="content_part_e-mail_formular.phtml">E-Mail Formular</a></li>
			<li class="sub_no sub_ul_true"><a href="content_part_newsletter_de.phtml">Newsletter</a></li>
			<li class="sub_no"><a href="content_part_suche.phtml">Suche</a></li>
			<li class="sub_no sub_ul_true"><a href="content_part_gaestebuch_kommentar.phtml">Gästebuch / Komm.</a></li>
			<li class="sub_no"><a href="content_part_sitemap_de.phtml">Sitemap</a></li>
			<li class="sub_no"><a href="content_part_externer_content.phtml">Ext. Content</a></li>
			<li class="sub_no"><a href="content_part_bildwechsel.phtml">Bildwechsel</a></li>
			<li class="sub_no"><a href="content_part_rss_feed_de.phtml">RSS Feed</a></li>
			<li class="sub_no"><a href="content_part_landkarte.phtml">Landkarte</a></li>
			<li class="sub_no"><a href="content_part_php_variablen.phtml">PHP Variablen</a></li>
			<li class="sub_no"><a href="content_part_contentpart_alias_de.phtml">Contentpart Alias</a></li>
			<li class="sub_no"><a href="content_part_poll_de.phtml"><span style="text-decoration:line-through;font-size:10px;">Poll</span></a></li>
			<li class="sub_no"><a href="content_part_kochrezept.phtml">Kochrezept</a></li>
			<li class="sub_no"><a href="content_part_faq_de.phtml">FAQ</a></li>
			<li class="sub_no"><a href="content_part_frontend_login_de.phtml"><span style="text-decoration:line-through;font-size:10px;">Frontend Login</span></a></li>
			<li class="sub_no"><a href="content_part_glossar.phtml"><span style="text-decoration:line-through;font-size:10px;">Plug-in: Glossar</span></a></li>
		</ul>
		</div>
		</li>
	</ul>
	</div>
	</li>
	<li class="sub_no sub_ul_true"><a href="dateizentrale.phtml">Datei</a></li>
	<li class="sub_no sub_ul_true"><a href="verwaltung_module.phtml">Module</a></li>
	<li class="sub_no sub_ul_true"><a href="Kommunikation.phtml">Kommunikation</a></li>
	<li class="sub_no"><a href="verwaltung_nachricht.phtml">Nachricht</a></li>
	<li class="sub_no"><a href="verwaltung_chat.phtml">Chat</a></li>
	<li class="sub_no"><a href="verwaltung_profil.phtml">Profil</a></li>
	<li class="sub_no sub_ul_true"><a href="verwaltung_admin.phtml">Admin</a></li>
	<li class="sub_no sub_ul_true"><a href="add-on-und-vorlagen.phtml">Add Ons und Vorlagen</a></li>
	<li class="sub_no"><a href="deutsche_version.phtml?replacement_tags_de">Replacement Tags</a></li>
	<li class="sub_no"><a href="deutsche_version.phtml?content_parts_de">Content Parts</a></li>
</ul>
</div>

		
		
		

	</div> 
	</div> 
	  
	<div id="right">
		<div style="margin-top:24px;">			
		<form action="index.php?suche" method="post" name="searchFE" onsubmit="s=document.getElementById('customSearchInput');if(s.value=='Suchen')return false;">
			<table width="100%" border="0" cellpadding="0" cellspacing="0">
			<tr>
					<td><input type="text" name="search_input_field" size="20" maxlength="200" id="customSearchInput" class="customSearchInput" value="" onfocus="if(this.value=='Suchen')this.value='';" onblur="if(this.value=='')this.value='Suchen';" /></td>
					<td><input type="image" name="search_go" onfocus="this.blur();" title="Suchen" src="/template/lang/all/submit.gif" /></td>
				</tr>
			</table>
			</form>
			
			      <script type="text/javascript" language="javascript">
			  <!-- 
			        document.getElementById("customSearchInput").value="Suchen";
			  //-->
			      </script>
				  
			<!-- <p style="margin-top:10px;">Schriftgrad &auml;ndern: <a href="[FontSize-]"><img src="template/lang/all/icons/reduce.gif" width="18" height="17" alt="" title="Verkleinern" border="0" /></a>
			<a href="[FontSize+]"><img src="template/lang/all/icons/extend.gif" width="18" height="17" alt="" title="Vergr&ouml;&szlig;ern" border="0" /></a>
			</p> -->
			
	<p style="margin-top:10px;">Bitte w&auml;hlen Sie: 
	
	 </p>
<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div>


<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div>
<!-- <a href="http://validator.w3.org/check?uri=http%3A%2F%2Fwww.phpwcms-docu.de%2Findex.php%3Fdeutsche_version" title="W3C Standard XHTML" target="_blank"><img src="picture/w3c/w3c_xhtml.gif" border="0" alt="" /></a>
<a href="http://jigsaw.w3.org/css-validator/validator?uri=http://www.phpwcms-docu.de" title="W3C Standard CSS" target="_blank"><img src="picture/w3c/w3c_css.gif" border="0" alt="" /></a><br />			
<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div> -->
<h3>Partnersites</h3>






<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div>

<div style="margin-top:10px; margin-bottom:15px;"></div>


<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div>
</div>

	</div> 
	
	<div id="content">
	<div id="bread">Sie sind hier: <a href="deutsche_version.phtml">Deutsch</a> <span class="breadcrumb_spacer">&gt;</span> <a href="die_docu.phtml">Die Docu</a> <span class="breadcrumb_spacer">&gt;</span> <a href="verwaltung_artikel.phtml">Artikel</a> <span class="breadcrumb_spacer">&gt;</span> <a href="content_parts_de.phtml">Content Parts</a> <span class="breadcrumb_spacer">&gt;</span> <a href="content_part_ecard_de.phtml">E-Card</a> <span class="breadcrumb_spacer">&gt;</span> E-Card Beispiel</div>
		
		<a name="jump301"></a><!-- Livedate: 05.12.2004 12:12:55 / Killdate: 31.12.2030 23:59:59 -->
<h1>E-Card Beispieltexte</h1>

<div style="margin:25px 0 0 0;padding:0;" class="spaceBeforeCP"></div><p>Hier sehen Sie E-Card Beispieltexte. Sie k&ouml;nnen diese einfach via copy / paste in Ihre E-Card-Vorlage einf&uuml;gen.</p><div style="border-bottom:1px dotted #d2e2f5; margin-top:10px; margin-bottom:15px;"></div><div style="margin:10px 0 0 0;padding:0;" class="spaceBeforeCP"></div><h3>Formular:</h3><code style="width:480px;"> 
&lt;p&gt;&lt;!--FORM_ERROR_START--&gt;&lt;/p&gt;<br />
&lt;p&gt;&lt;strong&gt;Alle mit * markierten Felder m&amp;uuml;ssen korrekt ausgef&amp;uuml;llt werden!&lt;/strong&gt;&lt;/p&gt;<br />
&lt;!--FORM_ERROR_END--&gt;<br />
&lt;div style=&quot;width: 450px;&quot;&gt;<br />
&lt;div align=&quot;center&quot;&gt;###ECARD_CHOOSER###&lt;/div&gt;<br />
&lt;br /&gt;<br />
&lt;label&gt;Absendername: &lt;/label&gt;&lt;br /&gt;<br />
&lt;input type=&quot;text&quot; size=&quot;25&quot; value=&quot;###SENDER_NAME###&quot; style=&quot;font-size: 12px; width: 150px; margin-right: 3px;&quot; name=&quot;###SENDER_NAME###&quot; /&gt;<br />
&lt;br /&gt;<br />
&lt;br /&gt;<br />
&lt;label&gt;Empf&amp;auml;ngername: &lt;/label&gt;&lt;br /&gt;<br />
&lt;input type=&quot;text&quot; size=&quot;25&quot; value=&quot;###RECIPIENT_NAME###&quot; style=&quot;font-size: 12px; width: 150px; margin-right: 3px;&quot; name=&quot;###RECIPIENT_NAME###&quot; /&gt;<br />
&lt;br /&gt;&lt;br /&gt;<br />
&lt;label&gt;Absender E-Mail*: &lt;/label&gt;&lt;br /&gt;<br />
&lt;input type=&quot;text&quot; size=&quot;25&quot; value=&quot;###SENDER_EMAIL###&quot; style=&quot;font-size: 12px; width: 150px;&quot; name=&quot;###SENDER_EMAIL###&quot; /&gt;<br />
&lt;br /&gt;<br />
&lt;br /&gt;<br />
&lt;label&gt;Empf&amp;auml;nger E-Mail*: &lt;/label&gt;&lt;br /&gt;<br />
&lt;input type=&quot;text&quot; size=&quot;25&quot; value=&quot;###RECIPIENT_EMAIL###&quot; style=&quot;font-size: 12px; width: 150px;&quot; name=&quot;###RECIPIENT_EMAIL###&quot; /&gt;<br />
&lt;br /&gt;&lt;br /&gt;<br />
&lt;label&gt;Ihre Mitteilung an den Empf&amp;auml;nger&lt;/label&gt; &nbsp;&nbsp; &nbsp;<br />
&lt;textarea style=&quot;width: 98%; font-family: Verdana,Arial,Helvetica,sans-serif; font-size: 12px;&quot; id=&quot;ecard_sender_msg&quot; rows=&quot;6&quot; cols=&quot;50&quot; name=&quot;###SENDER_MESSAGE###&quot;&gt;###SENDER_MESSAGE###&lt;/textarea&gt; &nbsp;&nbsp; &nbsp; <br />
&lt;br /&gt;&lt;br /&gt;<br />
&lt;input type=&quot;submit&quot; style=&quot;font-size: 12px;&quot; value=&quot;E-Card versenden&quot; name=&quot;###BUTTON###&quot; /&gt;<br />
&lt;/div&gt;
</code>
<br /><br />
<h3>Ergibt:</h3>

<p><!--FORM_ERROR_START--></p>
<p><strong>Alle mit * markierten Felder m&uuml;ssen korrekt ausgef&uuml;llt werden!</strong></p>
<!--FORM_ERROR_END-->
<div style="width: 450px;">
<div align="center">###ECARD_CHOOSER###</div>
<br />
<label>Absendername: </label><br />
<input type="text" size="25" value="###SENDER_NAME###" style="font-size: 12px; width: 150px; margin-right: 3px;" name="###SENDER_NAME###" />
<br />
<br />
<label>Empf&auml;ngername: </label><br />
<input type="text" size="25" value="###RECIPIENT_NAME###" style="font-size: 12px; width: 150px; margin-right: 3px;" name="###RECIPIENT_NAME###" />
<br /><br />
<label>Absender E-Mail*: </label><br />
<input type="text" size="25" value="###SENDER_EMAIL###" style="font-size: 12px; width: 150px;" name="###SENDER_EMAIL###" />
<br />
<br />
<label>Empf&auml;nger E-Mail*: </label><br />
<input type="text" size="25" value="###RECIPIENT_EMAIL###" style="font-size: 12px; width: 150px;" name="###RECIPIENT_EMAIL###" />
<br /><br />
<label>Ihre Mitteilung an den Empf&auml;nger</label> 	
<textarea style="width: 98%; font-family: Verdana,Arial,Helvetica,sans-serif; font-size: 12px;" id="ecard_sender_msg" rows="6" cols="50" name="###SENDER_MESSAGE###">###SENDER_MESSAGE###</textarea> 	 
<br /><br />
<input type="submit" style="font-size: 12px;" value="E-Card versenden" name="###BUTTON###" />
</div><div align="right"><a href="#top"><img src="img/article/top_link_0.gif" border="0" alt="" /></a></div><div style="border-bottom:1px dotted #d2e2f5; margin-top:10px; margin-bottom:15px;"></div><div style="margin:10px 0 0 0;padding:0;" class="spaceBeforeCP"></div><h3>Gesendet:</h3><code style="width:480px;"> 
&lt;h3&gt;&nbsp; Die E-Card wurde erfolgreich versendet! &lt;/h3&gt;<br />
<br />
&lt;strong&gt;Folgende Angaben wurden von Ihnen gemacht:&lt;/strong&gt;&lt;br/&gt;&lt;br/&gt;<br />
&nbsp;<br />
&lt;fieldset&gt;<br />
&nbsp;&nbsp; &nbsp;&lt;legend&gt;&lt;strong&gt;Empf&auml;nger&lt;/strong&gt;&lt;/legend&gt; <br />
&nbsp;&nbsp; &nbsp;Name: ###RECIPIENT_NAME###&lt;br/&gt;<br />
&nbsp;&nbsp; &nbsp;Email: ###RECIPIENT_EMAIL### <br />
&nbsp;&lt;/fieldset&gt;<br />
&nbsp;<br />
&nbsp;&lt;br /&gt;<br />
&lt;fieldset&gt;<br />
&nbsp;&nbsp; &nbsp;&lt;legend&gt;&lt;strong&gt;Ihr gew&auml;hltes Motiv&lt;/strong&gt;&lt;/legend&gt; <br />
&nbsp;&nbsp; &nbsp;###ECARD_TITLE###&lt;br/&gt;&lt;br/&gt;<br />
&nbsp;&nbsp; &nbsp;###ECARD_IMAGE### <br />
&nbsp;&lt;/fieldset&gt;<br />
&nbsp;<br />
&nbsp; &lt;br /&gt;<br />
&lt;fieldset&gt;<br />
&nbsp;&nbsp; &nbsp;&lt;legend&gt;&lt;strong&gt; Ihre Mitteilung an den Empf&auml;nger&lt;/strong&gt;&lt;/legend&gt;<br />
&nbsp;&nbsp; &nbsp; ###SENDER_MESSAGE### <br />
&nbsp;&lt;/fieldset&gt;
</code>
<br /><br />
<h3>Ergibt:</h3>

<div style="width: 450px;"><h3>  Die E-Card wurde erfolgreich versendet! </h3>

<strong>Folgende Angaben wurden von Ihnen gemacht:</strong><br/><br/>
 
<fieldset>
	<legend><strong>Empfänger</strong></legend> 
	Name: ###RECIPIENT_NAME###<br/>
	Email: ###RECIPIENT_EMAIL### 
 </fieldset>
 
 <br />
<fieldset>
	<legend><strong>Ihr gewähltes Motiv</strong></legend> 
	###ECARD_TITLE###<br/><br/>
	###ECARD_IMAGE### 
 </fieldset>
 
  <br />
<fieldset>
	<legend><strong> Ihre Mitteilung an den Empfänger</strong></legend>
	 ###SENDER_MESSAGE### 
 </fieldset>

</div><div align="right"><a href="#top"><img src="img/article/top_link_0.gif" border="0" alt="" /></a></div><div style="border-bottom:1px dotted #d2e2f5; margin-top:10px; margin-bottom:15px;"></div><div style="margin:10px 0 0 0;padding:0;" class="spaceBeforeCP"></div><h3>Email:</h3><code style="width:480px;">
&lt;table width=&quot;500&quot; border=&quot;0&quot; cellspacing=&quot;0&quot; cellpadding=&quot;0&quot;&gt;<br />
&lt;tr&gt;<br />
&lt;td width=&quot;500&quot; valign=&quot;top&quot;&gt;<br />
&lt;font face=&quot;Arial,Helvetica,sans-serif&quot; size=&quot;2&quot; color=&quot;#122b77&quot;&gt;<br />
Hallo ###RECIPIENT_NAME###, &lt;br/&gt;<br />
Sie haben eine elektronische Postkarte von ###SENDER_NAME### (###SENDER_EMAIL###) mit <br />
folgendem Inhalt auf (###RECIPIENT_EMAIL###)erhalten:&lt;br/&gt;&lt;br/&gt;<br />
E-Card &quot;###ECARD_TITLE###&quot; &lt;br/&gt;<br />
###ECARD_IMAGE### &lt;br/&gt;<br />
###SENDER_MESSAGE###<br />
&lt;/font&gt;&nbsp;<br />
&nbsp;&lt;br/&gt;&lt;br/&gt;<br />
---------------------------------------------------&lt;br/&gt;<br />
&lt;font face=&quot;Arial,Helvetica,sans-serif&quot; size=&quot;1&quot; color=&quot;#000000&quot;&gt;<br />
&lt;strong&gt;Hinweis: &lt;/strong&gt;&lt;br/&gt;<br />
Die hier gezeigten Daten werden nicht f&uuml;r andere Zwecke verwendet oder gespeichert. <br />
F&uuml;r den Inhalt der E-Mail ist ausschliesslich der Absender verantwortlich! Sollte das Bild nicht angezeigt werden, liegt die Ursache wom&ouml;glich bei Ihrem Spamfilter oder Firewall, welcher externe Bildverweise blockiert. <br />
&lt;/font&gt;<br />
&lt;/td&gt;<br />
&lt;/tr&gt;<br />
&lt;/table&gt;></code>
<br /><br />
<h3>Ergibt:</h3>

<table width="500" border="0" cellspacing="0" cellpadding="0">
<tr>
<td width="500" valign="top">
<font face="Arial,Helvetica,sans-serif" size="2" color="#122b77">
Hallo ###RECIPIENT_NAME###, <br/>
Sie haben eine elektronische Postkarte von ###SENDER_NAME### (###SENDER_EMAIL###) mit 
folgendem Inhalt auf (###RECIPIENT_EMAIL###)erhalten:<br/><br/>
 
E-Card "###ECARD_TITLE###" <br/>
###ECARD_IMAGE### <br/>
###SENDER_MESSAGE###
</font>
 
 
 <br/><br/>
-----------------------------------------------------------------------------<br/>
<font face="Arial,Helvetica,sans-serif" size="1" color="#000000">
<strong>Hinweis: </strong><br/>
Die hier gezeigten Daten werden nicht für andere Zwecke verwendet oder gespeichert. 
Für den Inhalt der E-Mail ist ausschliesslich der Absender verantwortlich!

Sollte das Bild nicht angezeigt werden, liegt die Ursache womöglich bei Ihrem Spamfilter oder Firewall, 
welcher externe Bildverweise blockiert. <br/><br/><br/>
</font>
</td>
</tr>
</table><div align="right"><a href="#top"><img src="img/article/top_link_0.gif" border="0" alt="" /></a></div>
		 
		
		<br /><br />
		<div class="sub">
		Artikel erstellt am: Montag, 15. August 2005 <br /> Letzte &Auml;nderung: Dienstag, 04. Januar 2011	
		</div>
				
	</div>
	
<div id="footer"><br /><br />
<p style="height:30px;">&nbsp;</p>


 <script type="text/javascript" language="javascript">
<!--

var showDefaultValue =  0

function hideLayer(whichLayer) {
	if (document.getElementById) {
		// this is the way the standards work
		document.getElementById(whichLayer).style.display = "none";
	} else if (document.all) {
		// this is the way old msie versions work
		document.all[whichlayer].style.display = "none";
	} else if (document.layers) {
		// this is the way nn4 works
		document.layers[whichLayer].display = "none";
	}
}

function showLayer(whichLayer) {
		//	alert(whichLayer);
	if (document.getElementById) {
		// this is the way the standards work
		document.getElementById(whichLayer).style.display = "block";
	}
	else if (document.all) {
		// this is the way old msie versions work
		document.all[whichlayer].style.display = "block";
	}
	else if (document.layers) {
		// this is the way nn4 works
		document.layers[whichLayer].display = "block";
	}
}

function toggleLayer(whichLayer) {
	if(showDefaultValue == 0) {
		hideLayer(whichLayer);
		showDefaultValue = 1;
	} else {
		showLayer(whichLayer);
		showDefaultValue = 0;
	}
}
//-->
</script>


<div id="alles">
<div id="klapper" onclick="toggleLayer('formular');">
<table width="570" border="0" cellspacing="0" cellpadding="0">
<tr>
<td><em style="color:#275EA8;" onmouseover="this.style.color='#4F96F4';" onmouseout="this.style.color='#275EA8';">Sie haben Anregungen oder Kritik zu diesem Artikel? Schreiben Sie uns!</em></td>   
<td align="right" style="padding-right:2px;"><img src="template/lang/all/icons/write.gif" width="16" height="21" alt="" border="0" /></td>
</tr>
</table>

</div>
<div id="formular">

<form name="form" method="post" action="index.php?id=355,301,0,1,1,0" style="margin:0;padding:0;"><input type="hidden" name="customForm" value="1" /><input type="hidden" name="docucheck" value="1" />


<div style="float:left;">
<p><select name="Betreff" id="Betreff" class="size1">
<option value="" class="deepblue"> Bitte ausw&auml;hlen </option>
<option value="subject_1" class="inselect">Anregungen</option>
<option value="subject_2" class="inselect">Fehlermeldung/ Kritik</option>
<option value="subject_3" class="inselect">Sonstiges</option>

</select><br /></p>


<p>Vorname:<br />
<input type="text" name="Vorname" value="" class="size1" /></p>
<p>Name:*<br />
<input type="text" name="Name" value="" class="size1" /></p>
<p>E-Mail:*<br />
<input type="text" name="E-Mail" value="" class="size1" /></p>
</div>


<div style="float:right;">Mitteilung:*<br />
<textarea name="Nachricht" cols="40" rows="4"  class="size7"></textarea>
</div>

<p style="clear:both; text-align:right;"><input type="reset" name="reset" value="Zur&uuml;cksetzen" class="btstyle" style="width:100px;" />&nbsp;&nbsp;
<input type="submit" name="submit" value="Anfrage senden" class="btstyle" style="width:110px;" /></p>
<p style="margin:20px;" class="sub">* Pflichtangaben. Ihre Daten werden ausschlie&szlig;lich für diese Anfrage verwendet.</p>

</form>
</div>
</div>
 <script type="text/javascript" language="javascript">
<!--
	// Lösung ohne Onload
	toggleLayer('formular');
//-->
</script>
<br />





	<table width="97%" border="0" cellspacing="0" cellpadding="0">
		<tr>
			<td valign="bottom">	
			&copy; phpwcms-docu 2004-2013
			<img src="img/leer.gif" border="0" width="10" height="0" alt="" /><a href="impressum.phtml" class="phpwcmsIntLink"><img src="template/lang/all/icons/imprint.gif" width="9" height="15" alt="Impressum" title="Impressum" border="0" /></a>&nbsp; 
			<a href="sitemap_de.phtml" class="phpwcmsIntLink"><img src="template/lang/all/icons/sitemap.gif" width="19" height="15" alt="Sitemap" title="Sitemap" border="0" /></a>&nbsp; 
			<a href="gaestebuch.phtml" class="phpwcmsIntLink"><img src="template/lang/all/icons/gbook.gif" width="20" height="16" alt="Ins G&auml;stebuch eintragen" title="Ins G&auml;stebuch eintragen" border="0" /></a>&nbsp; 
			<a href="#" onclick="BookMark_Page();return false;" title="" class="phpwcmsBookmarkLink"><img src="template/lang/all/icons/favo.gif" width="12" height="15" alt="Seite als Bookmark speichern" title="Seite als Bookmark speichern" border="0" /></a>&nbsp; 
			     
			</td>
			<td valign="bottom" style="padding-right:25px;">
			
			
			
			</td>		
			<td width="150">
			</td>
		</tr>
	</table>
</div><br/>

</div>
</body>
</html>