<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<!--
	phpwcms | free open source content management system
	created by Oliver Georgi (oliver at phpwcms dot de) and licensed under GNU/GPL.
	phpwcms is copyright 2003-2007 of Oliver Georgi. Extensions are copyright of
	their respective owners. Visit project page for details: http://www.phpwcms.org/
//-->
<title>phpwcms-docu for  phpwcms :: web based content management system | GB. / Kom. Beispiel{D:8/15/2005,30,neuR.gif} | Gästebuch-/Kommentar Beispieltexte</title>
  <meta http-equiv="content-type" content="text/html; charset=iso-8859-1" />
  <meta http-equiv="content-style-type" content="text/css" />
  <script src="template/inc_js/frontend.js" type="text/javascript"></script>
  <style type="text/css">
  <!-- 
    @import url("template/inc_css/mpl_docu.css");
    @import url("template/inc_css/mpl_frontend.css");
    @import url("template/inc_css/mpl_menu.css");
    @import url("template/inc_css/mpl_objects.css");
  //-->
  </style>
<script type="text/javascript" language="javascript">
<!--
function MM_jumpMenu(targ,selObj,restore){ //v3.0
  eval(targ+".location='"+selObj.options[selObj.selectedIndex].value+"'");
  if (restore) selObj.selectedIndex=0;
}

function MM_findObj(n, d) { //v4.01
  var p,i,x;  if(!d) d=document; if((p=n.indexOf("?"))>0&&parent.frames.length) {
    d=parent.frames[n.substring(p+1)].document; n=n.substring(0,p);}
  if(!(x=d[n])&&d.all) x=d.all[n]; for (i=0;!x&&i<d.forms.length;i++) x=d.forms[i][n];
  for(i=0;!x&&d.layers&&i<d.layers.length;i++) x=MM_findObj(n,d.layers[i].document);
  if(!x && d.getElementById) x=d.getElementById(n); return x;
}

function MM_jumpMenuGo(selName,targ,restore){ //v3.0
  var selObj = MM_findObj(selName); if (selObj) MM_jumpMenu(targ,selObj,restore);
}
//-->
</script>
<meta name="Title" content="Die phpWCMS Dokumentation" />
<meta name="author" content="Oliver Frohnert, Mario Perez Leal" />
<meta name="Publisher" content="Oliver Frohnert, Mario Perez Leal, creacion" />
<meta name="Copyright" content="Oliver Frohnert, Mario Perez Leal, creacion" />
<meta name="keywords" content="frohnert, perez leal, creacion, documentation, dokumentation, phpwcms, cms, opensource, open source, docu" />
<meta name="description" content="Das Dokumentations Projekt für das Open Source CMS phpWCMS" />
<meta name="Audience" content="Alle" />
<meta name="Content-language" content="DE" />
<meta name="robots" content="index,follow" />
<meta name="expires" content="0" />
<meta name="revisit-after" content="7 days" />
<meta name="resource-type" content="document" />
<meta name="distribution" content="Global" />
<meta name="generator" content="PHPWCMS" />
<meta name="verify-v1" content="1ZpxZ7AZsjm7PxjqXQVus0eiUYqOsp5URTJn9q4KNz8=" />
  <!--[if lt IE 7]>
  <style type="text/css">
    body { behavior: url("template/inc_css/specific/csshover2.htc"); }
    img { behavior: url("template/inc_css/specific/pngbehavior.htc"); }
  </style>
  <![endif]-->
</head>
<body id="myid_195">
<div id="container"><a name="top" id="top"></a>


	<div id="head">
		
	<div id="mainnavi">
		<div class="fleft"><a href="deutsche_version.phtml">Startseite</a> | <a href="news_de.phtml">News</a> | <span style="text-decoration:none;font-weight:bold;"><a href="die_docu.phtml">Die Docu</a></span> | <a href="Nuetzliche_Links_und_Tools.phtml">Links &amp; Tools</a> | <a href="downloads.phtml">Downloads</a> | <a href="kontakt.phtml">Kontakt</a> | <a href="faq_de.phtml">FAQ</a> | <a href="http://forum.phpwcms.org/" target="_blank">Forum</a> | <a href="howto_de.phtml">HowTo</a></div>				
		<div class="sys">Donnerstag, 7. März 2013<img src="img/leer.gif" border="0" width="5" height="1" alt="" />|<img src="img/leer.gif" border="0" width="5" height="1" alt="" />3 User online<img src="img/leer.gif" border="0" width="10" height="1" alt="" />
		<a href="deutsche_version.phtml" title="Deutsche Version"><img src="picture/../template/lang/all/flag_de.gif" border="0" alt="" /></a>
		<a href="english_version.phtml"  title="English version"><img src="picture/../template/lang/all/flag_en.gif" border="0" alt="" /></a>
		</div>
	</div>
	
	<a href="./" title="phpwcms-docu Startseite aufrufen" class="homelink">
	<span>&raquo; Zur phpwcms-docu Startseite</span></a>
	<h2>phpwcms-docu - Die Dokumentation f&uuml;r f&uuml;r das CMS phpWCMS</h2>
	<p>phpwcms-docu ist eine Art Kompass, der Ihnen die M&ouml;glichkeiten von phpWcms aufzeigt und Sie erfolgreich, ohne gro&szlig;e Umwege, zu Ihrer fertigen Web-Anwendung f&uuml;hren soll.
	</p>
	</div>

	
	<div id="left">
	<div class="leftnav" style="margin-top:24px;">
	
<div id="ul_div_309">
<ul>
	<li class="sub_no"><a href="download-dev-versionen.phtml">Download Dev Versionen</a></li>
	<li class="sub_no sub_ul_true"><a href="installation_und_upgrade_von_phpwcms.phtml">Installation &amp; Upgrade</a></li>
	<li class="sub_ul"><a href="verwaltung_artikel.phtml">Artikel</a>
	<div id="ul_div_82">
	<ul>
		<li class="sub_no"><a href="artikel_erstellen.phtml">Artikel erstellen</a></li>
		<li class="sub_no"><a href="artikel_editieren.phtml">Artikel bearbeiten</a></li>
		<li class="sub_no sub_ul_true"><a href="artikel_organisation.phtml">Artikel Organisation</a></li>
		<li class="sub_ul"><a href="content_parts_de.phtml">Content Parts</a>
		<div id="ul_div_100">
		<ul>
			<li class="sub_no"><a href="einfacher_text.phtml">Einfacher Text</a></li>
			<li class="sub_no"><a href="content_part_html_de.phtml">HTML</a></li>
			<li class="sub_no"><a href="content_part_wysiwyg_html_de.phtml">WYSIWYG HTML</a></li>
			<li class="sub_no"><a href="content_part_code_de.phtml">Code</a></li>
			<li class="sub_no"><a href="content_part_text_mit_bild.phtml">Text mit Bild</a></li>
			<li class="sub_no"><a href="content_part_bilder_div.phtml"><span style="text-decoration:line-through;font-size:10px;">Bilder &lt;DIV&gt;</span></a></li>
			<li class="sub_no"><a href="content_part_bilder.phtml">Bilder</a></li>
			<li class="sub_no"><a href="content_part_aufzaehlung.phtml">Aufzählung</a></li>
			<li class="sub_no"><a href="content_part_liste.phtml">Liste</a></li>
			<li class="sub_no"><a href="content_part_link_und_e-mail.phtml">Link &amp; E-Mail</a></li>
			<li class="sub_no"><a href="content_part_linkliste.phtml">Linkliste</a></li>
			<li class="sub_no"><a href="content_part_artikellink.phtml">Artikellink</a></li>
			<li class="sub_no"><a href="content_part_teaser_artikellink.phtml"><span style="text-decoration:line-through;font-size:10px;">Teaser / Artikellink</span></a></li>
			<li class="sub_no"><a href="content_part_artikelmenue.phtml">Artikelmenü</a></li>
			<li class="sub_no"><a href="content_part_multimedia_de.phtml">Multimedia</a></li>
			<li class="sub_no"><a href="content_part_dateiliste.phtml">Dateiliste</a></li>
			<li class="sub_no sub_ul_true"><a href="content_part_ecard_de.phtml">E-Card</a></li>
			<li class="sub_no"><a href="content_part_formular.phtml">Formular</a></li>
			<li class="sub_no sub_ul_true"><a href="content_part_e-mail_formulargenerator.phtml">E-Mail Form. [OLD]</a></li>
			<li class="sub_no"><a href="content_part_e-mail_formular.phtml">E-Mail Formular</a></li>
			<li class="sub_no sub_ul_true"><a href="content_part_newsletter_de.phtml">Newsletter</a></li>
			<li class="sub_no"><a href="content_part_suche.phtml">Suche</a></li>
			<li class="sub_ul"><a href="content_part_gaestebuch_kommentar.phtml">Gästebuch / Komm.</a>
			<div id="ul_div_147">
			<ul>
				<li class="sub_no active"><a href="beispiel_content_part_gaestebuch_kommentar.phtml">GB. / Kom. Beispiel</a></li>
			</ul>
			</div>
			</li>
			<li class="sub_no"><a href="content_part_sitemap_de.phtml">Sitemap</a></li>
			<li class="sub_no"><a href="content_part_externer_content.phtml">Ext. Content</a></li>
			<li class="sub_no"><a href="content_part_bildwechsel.phtml">Bildwechsel</a></li>
			<li class="sub_no"><a href="content_part_rss_feed_de.phtml">RSS Feed</a></li>
			<li class="sub_no"><a href="content_part_landkarte.phtml">Landkarte</a></li>
			<li class="sub_no"><a href="content_part_php_variablen.phtml">PHP Variablen</a></li>
			<li class="sub_no"><a href="content_part_contentpart_alias_de.phtml">Contentpart Alias</a></li>
			<li class="sub_no"><a href="content_part_poll_de.phtml"><span style="text-decoration:line-through;font-size:10px;">Poll</span></a></li>
			<li class="sub_no"><a href="content_part_kochrezept.phtml">Kochrezept</a></li>
			<li class="sub_no"><a href="content_part_faq_de.phtml">FAQ</a></li>
			<li class="sub_no"><a href="content_part_frontend_login_de.phtml"><span style="text-decoration:line-through;font-size:10px;">Frontend Login</span></a></li>
			<li class="sub_no"><a href="content_part_glossar.phtml"><span style="text-decoration:line-through;font-size:10px;">Plug-in: Glossar</span></a></li>
		</ul>
		</div>
		</li>
	</ul>
	</div>
	</li>
	<li class="sub_no sub_ul_true"><a href="dateizentrale.phtml">Datei</a></li>
	<li class="sub_no sub_ul_true"><a href="verwaltung_module.phtml">Module</a></li>
	<li class="sub_no sub_ul_true"><a href="Kommunikation.phtml">Kommunikation</a></li>
	<li class="sub_no"><a href="verwaltung_nachricht.phtml">Nachricht</a></li>
	<li class="sub_no"><a href="verwaltung_chat.phtml">Chat</a></li>
	<li class="sub_no"><a href="verwaltung_profil.phtml">Profil</a></li>
	<li class="sub_no sub_ul_true"><a href="verwaltung_admin.phtml">Admin</a></li>
	<li class="sub_no sub_ul_true"><a href="add-on-und-vorlagen.phtml">Add Ons und Vorlagen</a></li>
	<li class="sub_no"><a href="deutsche_version.phtml?replacement_tags_de">Replacement Tags</a></li>
	<li class="sub_no"><a href="deutsche_version.phtml?content_parts_de">Content Parts</a></li>
</ul>
</div>

		
		
		

	</div> 
	</div> 
	  
	<div id="right">
		<div style="margin-top:24px;">			
		<form action="index.php?suche" method="post" name="searchFE" onsubmit="s=document.getElementById('customSearchInput');if(s.value=='Suchen')return false;">
			<table width="100%" border="0" cellpadding="0" cellspacing="0">
			<tr>
					<td><input type="text" name="search_input_field" size="20" maxlength="200" id="customSearchInput" class="customSearchInput" value="" onfocus="if(this.value=='Suchen')this.value='';" onblur="if(this.value=='')this.value='Suchen';" /></td>
					<td><input type="image" name="search_go" onfocus="this.blur();" title="Suchen" src="/template/lang/all/submit.gif" /></td>
				</tr>
			</table>
			</form>
			
			      <script type="text/javascript" language="javascript">
			  <!-- 
			        document.getElementById("customSearchInput").value="Suchen";
			  //-->
			      </script>
				  
			<!-- <p style="margin-top:10px;">Schriftgrad &auml;ndern: <a href="[FontSize-]"><img src="template/lang/all/icons/reduce.gif" width="18" height="17" alt="" title="Verkleinern" border="0" /></a>
			<a href="[FontSize+]"><img src="template/lang/all/icons/extend.gif" width="18" height="17" alt="" title="Vergr&ouml;&szlig;ern" border="0" /></a>
			</p> -->
			
	<p style="margin-top:10px;">Bitte w&auml;hlen Sie: 
	
	 </p>
<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div>


<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div>
<!-- <a href="http://validator.w3.org/check?uri=http%3A%2F%2Fwww.phpwcms-docu.de%2Findex.php%3Fdeutsche_version" title="W3C Standard XHTML" target="_blank"><img src="picture/w3c/w3c_xhtml.gif" border="0" alt="" /></a>
<a href="http://jigsaw.w3.org/css-validator/validator?uri=http://www.phpwcms-docu.de" title="W3C Standard CSS" target="_blank"><img src="picture/w3c/w3c_css.gif" border="0" alt="" /></a><br />			
<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div> -->
<h3>Partnersites</h3>






<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div>

<div style="margin-top:10px; margin-bottom:15px;"></div>


<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div>
</div>

	</div> 
	
	<div id="content">
	<div id="bread">Sie sind hier: <a href="deutsche_version.phtml">Deutsch</a> <span class="breadcrumb_spacer">&gt;</span> <a href="die_docu.phtml">Die Docu</a> <span class="breadcrumb_spacer">&gt;</span> <a href="verwaltung_artikel.phtml">Artikel</a> <span class="breadcrumb_spacer">&gt;</span> <a href="content_parts_de.phtml">Content Parts</a> <span class="breadcrumb_spacer">&gt;</span> <a href="content_part_gaestebuch_kommentar.phtml">Gästebuch / Komm.</a> <span class="breadcrumb_spacer">&gt;</span> GB. / Kom. Beispiel</div>
		
		<a name="jump303"></a><!-- Livedate: 05.12.2004 12:12:55 / Killdate: 31.12.2030 23:59:59 -->
<h1>Gästebuch-/Kommentar Beispieltexte</h1>

<div style="margin:25px 0 0 0;padding:0;" class="spaceBeforeCP"></div><p>Hier sehen Sie G&auml;stebuch-/Kommentar-Beispieltexte. Sie k&ouml;nnen diese einfach via copy / paste in Ihre&nbsp;G&auml;stebuch-/Kommentar-Vorlage einf&uuml;gen.</p><div style="border-bottom:1px dotted #d2e2f5; margin-top:10px; margin-bottom:15px;"></div><div style="margin:10px 0 0 0;padding:0;" class="spaceBeforeCP"></div><h3>Formular:</h3><strong>Dieses G&auml;stebuch-/Kommentar-Template ist als default.html unter /template/inc_cntpart/guestbook abzuspeichern: </strong><p>&nbsp;</p><p>&nbsp;</p>
<code>&lt;p style=&quot;background-color: rgb(215, 227, 226);&quot;&gt;&lt;strong&gt;List of banned words - make a listing divided by simple space &quot; &quot;. &lt;/strong&gt;if possible try to insert no HTML chars.&lt;strong&gt;&lt;br /&gt;<br />
&lt;/strong&gt;shit porno fuck and so on&lt;/p&gt;<br />
&lt;p&gt;&lt;!--BAN_START//--&gt;shit fuck porno sex &lt;!--BAN_END//--&gt;&lt;/p&gt;<br />
&lt;p style=&quot;background-color: rgb(215, 227, 226);&quot;&gt;&lt;strong&gt;Replace banned words by this HTML code. &lt;/strong&gt;&lt;strong&gt;&lt;br /&gt;<br />
&lt;/strong&gt;banned OR &amp;lt;img src=&quot;...&quot;&amp;gt;&lt;/p&gt;<br />
&lt;p&gt;&lt;!--BAN_REPLACE_START//--&gt;&lt;strong&gt;banned word&lt;/strong&gt; &lt;!--BAN_REPLACE_END//--&gt;&lt;/p&gt;<br />
&lt;p style=&quot;background-color: rgb(215, 227, 226);&quot;&gt;&lt;strong&gt;Guestbook HTML form and form error message &lt;br /&gt;<br />
&lt;/strong&gt;{<img src="img/leer.gif" border="0" width="0" height="0" alt="" />EMAIL}, {<img src="img/leer.gif" border="0" width="0" height="0" alt="" />NAME}, {<img src="img/leer.gif" border="0" width="0" height="0" alt="" />URL}, {<img src="img/leer.gif" border="0" width="0" height="0" alt="" />MSG}&lt;/p&gt;<br />
&lt;!--FORM_START//--&gt;<br />
&lt;table cellspacing=&quot;0&quot; cellpadding=&quot;1&quot; border=&quot;0&quot; bgcolor=&quot;#cfe7f7&quot; align=&quot;center&quot; style=&quot;margin-bottom: 10px;&quot;&gt;<br />
&nbsp;&nbsp;&nbsp; &lt;tbody&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lt;tr bgcolor=&quot;#e1e1e1&quot;&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lt;td colspan=&quot;2&quot;&gt;&lt;strong&gt;&amp;nbsp;&amp;nbsp;Tragen Sie sich in mein G&amp;auml;stebuch ein!&lt;/strong&gt; &lt;span style=&quot;font-size: 10px; color: rgb(204, 51, 0);&quot;&gt;(Markierte Felder (*) sind zwingend erforderlich!&lt;/span&gt;&lt;/td&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lt;/tr&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lt;tr bgcolor=&quot;#e1e1e1&quot;&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lt;td colspan=&quot;2&quot;&gt;&lt;img width=&quot;1&quot; height=&quot;1&quot; src=&quot;img/leer.gif&quot; alt=&quot;&quot; /&gt;&lt;/td&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lt;/tr&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lt;!--FORM_ERROR_START//--&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lt;tr&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lt;td colspan=&quot;2&quot;&gt;&lt;img width=&quot;1&quot; height=&quot;3&quot; src=&quot;img/leer.gif&quot; alt=&quot;&quot; /&gt;&lt;/td&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lt;/tr&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lt;tr&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lt;td colspan=&quot;2&quot;&gt;&amp;nbsp;&amp;nbsp;&lt;span style=&quot;color: rgb(204, 51, 0);&quot;&gt;Nichts eingetragen - Bitte f&amp;uuml;llen Sie alle Felder aus!&lt;/span&gt;&lt;/td&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lt;/tr&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lt;tr&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lt;td colspan=&quot;2&quot;&gt;&lt;img width=&quot;1&quot; height=&quot;3&quot; src=&quot;img/leer.gif&quot; alt=&quot;&quot; /&gt;&lt;/td&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lt;/tr&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lt;!--FORM_ERROR_END//--&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lt;tr&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lt;td colspan=&quot;2&quot;&gt;&lt;img width=&quot;1&quot; height=&quot;3&quot; src=&quot;img/leer.gif&quot; alt=&quot;&quot; /&gt;&lt;/td&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lt;/tr&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lt;tr&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lt;td align=&quot;right&quot; class=&quot;v10&quot;&gt;Email-Adresse:&lt;span style=&quot;color: rgb(204, 51, 0);&quot;&gt;*&lt;/span&gt;:&amp;nbsp;&lt;/td&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lt;td&gt;&lt;input value=&quot;{EMAIL}&quot; name=&quot;guestbook_email&quot; size=&quot;50&quot; maxlength=&quot;250&quot; style=&quot;width: 350px;&quot; id=&quot;guestbook_email&quot; class=&quot;v12&quot; /&gt; &amp;nbsp;&lt;/td&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lt;/tr&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lt;tr&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lt;td align=&quot;right&quot; class=&quot;v10&quot;&gt;Vor- und Nachname:&lt;span style=&quot;color: rgb(204, 51, 0);&quot;&gt;*&lt;/span&gt;:&amp;nbsp;&lt;/td&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lt;td&gt;&lt;input value=&quot;{NAME}&quot; name=&quot;guestbook_name&quot; size=&quot;50&quot; maxlength=&quot;500&quot; style=&quot;width: 350px;&quot; id=&quot;guestbook_name&quot; class=&quot;v12&quot; /&gt;&lt;/td&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lt;/tr&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lt;tr&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lt;td align=&quot;right&quot; class=&quot;v10&quot;&gt;Website:&amp;nbsp;&lt;/td&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lt;td&gt;&lt;input value=&quot;{URL}&quot; name=&quot;guestbook_url&quot; size=&quot;50&quot; maxlength=&quot;1000&quot; style=&quot;width: 350px;&quot; id=&quot;guestbook_url&quot; class=&quot;v12&quot; /&gt;&lt;/td&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lt;/tr&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lt;tr&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lt;td valign=&quot;top&quot; align=&quot;right&quot; class=&quot;v10&quot;&gt;&amp;nbsp;&amp;nbsp;Nachricht:&amp;nbsp;&lt;/td&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lt;td&gt;&lt;textarea name=&quot;guestbook_msg&quot; cols=&quot;50&quot; rows=&quot;6&quot; style=&quot;width: 350px;&quot; id=&quot;guestbook_msg&quot; class=&quot;v12&quot;&gt;{MSG}&lt;/textarea&gt;&lt;/td&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lt;/tr&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lt;tr&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lt;td valign=&quot;top&quot; align=&quot;right&quot; class=&quot;v10&quot;&gt;Anzeige:&amp;nbsp;&lt;/td&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lt;td&gt;&lt;input type=&quot;radio&quot; value=&quot;0&quot; name=&quot;guestbook_show&quot; checked=&quot;checked&quot; /&gt;Email-Adresse anzeigen&lt;br /&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lt;input type=&quot;radio&quot; value=&quot;1&quot; name=&quot;guestbook_show&quot; /&gt;Email-Adresse verstecken&lt;br /&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lt;input type=&quot;radio&quot; value=&quot;2&quot; name=&quot;guestbook_show&quot; /&gt;Email-Adresse als &quot;info at mail dot com&quot; anzeigen&lt;/td&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lt;/tr&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lt;tr&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lt;td colspan=&quot;2&quot;&gt;&lt;img width=&quot;1&quot; height=&quot;4&quot; src=&quot;img/leer.gif&quot; alt=&quot;&quot; /&gt;&lt;/td&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lt;/tr&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lt;tr&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lt;td align=&quot;right&quot;&gt;&amp;nbsp;&lt;/td&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lt;td&gt;&lt;input type=&quot;submit&quot; value=&quot;Eintrag abschicken&quot; name=&quot;guestbook_send&quot; id=&quot;guestbook_send&quot; class=&quot;v11&quot; /&gt;&lt;/td&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lt;/tr&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lt;tr&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lt;td colspan=&quot;2&quot;&gt;&lt;img width=&quot;1&quot; height=&quot;6&quot; src=&quot;img/leer.gif&quot; alt=&quot;&quot; /&gt;&lt;/td&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lt;/tr&gt;<br />
&nbsp;&nbsp;&nbsp; &lt;/tbody&gt;<br />
&lt;/table&gt;<br />
&lt;!--FORM_END//--&gt;<br />
&lt;p style=&quot;background-color: rgb(207, 231, 247);&quot;&gt;&lt;strong&gt;Erfolgsmeldung - wird angezeigt, wenn der G&amp;auml;stebuch-Eintrag erstellt wurde&lt;br /&gt;<br />
&lt;/strong&gt;{NAME}&lt;/p&gt;<br />
&lt;p&gt;&lt;!--FORM_SUCCESS_START//--&gt;&lt;/p&gt;<br />
&lt;div style=&quot;margin-top: 5px; margin-bottom: 5px;&quot;&gt;Vielen Dank, {<img src="img/leer.gif" border="0" width="0" height="0" alt="" />NAME}! Sie haben sich erfolgreich in unser G&amp;auml;stebuch eingetragen.&lt;/div&gt;<br />
&lt;!--FORM_SUCCESS_END//--&gt;<br />
&lt;p&gt;&amp;nbsp;&lt;/p&gt;<br />
&lt;p style=&quot;background-color: rgb(207, 231, 247);&quot;&gt;&lt;strong&gt;G&amp;auml;stebuch-Navigation&lt;br /&gt;<br />
&lt;/strong&gt;&lt;span class=&quot;chatlist&quot;&gt;{<img src="img/leer.gif" border="0" width="0" height="0" alt="" />FIRST:HTML}, {<img src="img/leer.gif" border="0" width="0" height="0" alt="" />LAST:HTML}, {<img src="img/leer.gif" border="0" width="0" height="0" alt="" />BACK:HTML}, {<img src="img/leer.gif" border="0" width="0" height="0" alt="" />NEXT:HTML}, {<img src="img/leer.gif" border="0" width="0" height="0" alt="" />JUMP:LISTTEXT|BUTTON|SPACER}, {<img src="img/leer.gif" border="0" width="0" height="0" alt="" />PAGE:COUNT:SPACER|WRAP_ACTIVE_BEFORE|AFTER}&lt;br /&gt;<br />
(<img src="img/leer.gif" border="0" width="0" height="0" alt="" />HTML = link text or image tag, like &amp;lt;img src=&quot;back.gif&quot; border=&quot;0&quot; /&amp;gt;)&lt;/span&gt;&lt;/p&gt;<br />
&lt;!--NAV_START//--&gt;<br />
&lt;table width=&quot;100%&quot; cellspacing=&quot;0&quot; cellpadding=&quot;0&quot; border=&quot;0&quot; style=&quot;margin-top: 5px;&quot;&gt;<br />
&nbsp;&nbsp;&nbsp; &lt;tbody&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lt;tr&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lt;td&gt;&lt;strong&gt;{&lt;/strong&gt;<img src="img/leer.gif" border="0" width="0" height="0" alt="" />&lt;strong&gt;FIRST:&amp;lt;&amp;lt;} {&lt;/strong&gt;<img src="img/leer.gif" border="0" width="0" height="0" alt="" />&lt;strong&gt;BACK:&amp;lt;}&lt;/strong&gt; {PAGE:5:&amp;nbsp;|&lt;strong&gt;|&lt;/strong&gt;} &lt;strong&gt;{&lt;/strong&gt;<img src="img/leer.gif" border="0" width="0" height="0" alt="" />&lt;strong&gt;NEXT:&amp;gt;} {&lt;/strong&gt;<img src="img/leer.gif" border="0" width="0" height="0" alt="" />&lt;strong&gt;LAST:&amp;gt;&amp;gt;}&lt;/strong&gt;&lt;/td&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lt;td align=&quot;right&quot;&gt;{<img src="img/leer.gif" border="0" width="0" height="0" alt="" />ARCHIVE:%Y/%m|alle Eintr&amp;auml;ge|go|&amp;nbsp;}&amp;nbsp;{<img src="img/leer.gif" border="0" width="0" height="0" alt="" />JUMP:page |go|&amp;nbsp;}&lt;/td&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lt;/tr&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lt;tr&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lt;td colspan=&quot;2&quot;&gt;&lt;img width=&quot;1&quot; height=&quot;3&quot; src=&quot;img/leer.gif&quot; alt=&quot;&quot; /&gt;&lt;/td&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lt;/tr&gt;<br />
&nbsp;&nbsp;&nbsp; &lt;/tbody&gt;<br />
&lt;/table&gt;&lt;br /&gt;&lt;br /&gt;<br />
&lt;!--NAV_END//--&gt;<br />
&lt;p style=&quot;background-color: rgb(207, 231, 247);&quot;&gt;&lt;strong&gt;G&amp;auml;stebuch-Eintr&amp;auml;ge&lt;br /&gt;<br />
&lt;/strong&gt;{<img src="img/leer.gif" border="0" width="0" height="0" alt="" />EMAIL}, {<img src="img/leer.gif" border="0" width="0" height="0" alt="" />NAME}, {<img src="img/leer.gif" border="0" width="0" height="0" alt="" />URL:HTML}, {<img src="img/leer.gif" border="0" width="0" height="0" alt="" />MSG}, {<img src="img/leer.gif" border="0" width="0" height="0" alt="" />URL}, {<img src="img/leer.gif" border="0" width="0" height="0" alt="" />ID}, {<img src="img/leer.gif" border="0" width="0" height="0" alt="" />DBID}, {<img src="img/leer.gif" border="0" width="0" height="0" alt="" />TIMESTAMP:FORMAT} (&lt;a target=&quot;_blank&quot; href=&quot;http://www.php.net/manual/en/function.date.php&quot; style=&quot;text-decoration: underline;&quot;&gt;FORMAT&amp;nbsp;=&amp;nbsp;d.m.Y&amp;nbsp;or&amp;nbsp;H:i:s&lt;/a&gt;)&lt;/p&gt;<br />
&lt;!--GUESTBOOK_START//--&gt;{<img src="img/leer.gif" border="0" width="0" height="0" alt="" />FORM} {<img src="img/leer.gif" border="0" width="0" height="0" alt="" />NAV}<br />
&lt;table width=&quot;100%&quot; cellspacing=&quot;0&quot; cellpadding=&quot;2&quot; border=&quot;0&quot;&gt;<br />
&nbsp;&nbsp;&nbsp; &lt;!--GUESTBOOK_ENTRY_START//--&gt;<br />
&nbsp;&nbsp;&nbsp; &lt;tbody&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lt;tr bgcolor=&quot;#cfe7f7&quot;&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lt;td width=&quot;1%&quot; align=&quot;right&quot;&gt;&lt;strong&gt;{&lt;/strong&gt;<img src="img/leer.gif" border="0" width="0" height="0" alt="" />&lt;strong&gt;ID}&amp;nbsp;&amp;nbsp;&lt;/strong&gt;&lt;/td&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lt;td width=&quot;99%&quot;&gt;{<img src="img/leer.gif" border="0" width="0" height="0" alt="" />DBID} | {<img src="img/leer.gif" border="0" width="0" height="0" alt="" />TIMESTAMP:d.m.Y H:i:s}&lt;/td&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lt;/tr&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lt;tr&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lt;td colspan=&quot;2&quot;&gt;&lt;a href=&quot;mailto:{EMAIL}&quot;&gt;&lt;strong&gt;{&lt;/strong&gt;&lt;font color=&quot;#000000&quot;&gt;<img src="img/leer.gif" border="0" width="0" height="0" alt="" />&lt;/font&gt;&lt;strong&gt;NAME}&lt;/strong&gt;&lt;/a&gt; &lt;strong&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;{&lt;/strong&gt;<img src="img/leer.gif" border="0" width="0" height="0" alt="" />&lt;strong&gt;URL:Website besuchen}&lt;/strong&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;Email: {<img src="img/leer.gif" border="0" width="0" height="0" alt="" />EMAIL}&lt;br /&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; {<img src="img/leer.gif" border="0" width="0" height="0" alt="" />MSG}&lt;/td&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lt;/tr&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lt;tr&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lt;td colspan=&quot;2&quot;&gt;&lt;img width=&quot;1&quot; height=&quot;3&quot; src=&quot;img/leer.gif&quot; alt=&quot;&quot; /&gt;&lt;/td&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lt;/tr&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lt;!--GUESTBOOK_ENTRY_END//--&gt;<br />
&nbsp;&nbsp;&nbsp; &lt;/tbody&gt;<br />
&lt;/table&gt;<br />
&lt;!--GUESTBOOK_END//--&gt;&lt;br /&gt;&lt;br /&gt;<br />
&lt;p style=&quot;background-color: rgb(207, 231, 247);&quot;&gt;&lt;strong&gt;Kommentar f&amp;uuml;r bearbeitete Artikel&lt;/strong&gt;&lt;strong&gt; &lt;/strong&gt;[c]...[/c]&lt;br /&gt;<br />
normal HTML code like &amp;lt;span style=&quot;color:#FF3300&quot;&amp;gt;|&amp;lt;/span&amp;gt;&lt;!--COMMENT_END//--&gt;&lt;/p&gt;</code><br />

<h3>Ergibt folgendes G&auml;stebuch-Formular:</h3>

<p style="background-color: rgb(215, 227, 226);"><strong>List of banned words - make a listing divided by simple space &quot; &quot;. </strong>if possible try to insert no HTML chars.<strong><br />
</strong>shit porno fuck and so on</p>
<p><!--BAN_START//-->shit fuck porno sex <!--BAN_END//--></p>
<p style="background-color: rgb(215, 227, 226);"><strong>Replace banned words by this HTML code. </strong><strong><br />
</strong>banned OR &lt;img src=&quot;...&quot;&gt;</p>
<p><!--BAN_REPLACE_START//--><strong>banned word</strong> <!--BAN_REPLACE_END//--></p>
<p style="background-color: rgb(215, 227, 226);"><strong>Guestbook HTML form and form error message <br />
</strong>{<img src="img/leer.gif" border="0" width="0" height="0" alt="" />EMAIL}, {<img src="img/leer.gif" border="0" width="0" height="0" alt="" />NAME}, {<img src="img/leer.gif" border="0" width="0" height="0" alt="" />URL}, {<img src="img/leer.gif" border="0" width="0" height="0" alt="" />MSG}</p>
<!--FORM_START//-->
<table cellspacing="0" cellpadding="1" border="0" bgcolor="#cfe7f7" align="center" style="margin-bottom: 10px;">
    <tbody>
        <tr bgcolor="#e1e1e1">
            <td colspan="2"><strong>&nbsp;&nbsp;Tragen Sie sich in mein G&auml;stebuch ein!</strong> <span style="font-size: 10px; color: rgb(204, 51, 0);">(Markierte Felder (*) sind zwingend erforderlich!</span></td>
        </tr>
        <tr bgcolor="#e1e1e1">
            <td colspan="2"><img width="1" height="1" src="img/leer.gif" alt="" /></td>
        </tr>
        <!--FORM_ERROR_START//-->
        <tr>
            <td colspan="2"><img width="1" height="3" src="img/leer.gif" alt="" /></td>
        </tr>
        <tr>
            <td colspan="2">&nbsp;&nbsp;<span style="color: rgb(204, 51, 0);">Nichts eingetragen - Bitte f&uuml;llen Sie alle Felder aus!</span></td>
        </tr>
        <tr>
            <td colspan="2"><img width="1" height="3" src="img/leer.gif" alt="" /></td>
        </tr>
        <!--FORM_ERROR_END//-->
        <tr>
            <td colspan="2"><img width="1" height="3" src="img/leer.gif" alt="" /></td>
        </tr>
        <tr>
            <td align="right" class="v10">Email-Adresse:<span style="color: rgb(204, 51, 0);">*</span>:&nbsp;</td>
            <td><input value="{EMAIL}" name="guestbook_email" size="50" maxlength="250" style="width: 350px;" id="guestbook_email" class="v12" /> &nbsp;</td>
        </tr>
        <tr>
            <td align="right" class="v10">Vor- und Nachname:<span style="color: rgb(204, 51, 0);">*</span>:&nbsp;</td>
            <td><input value="{NAME}" name="guestbook_name" size="50" maxlength="500" style="width: 350px;" id="guestbook_name" class="v12" /></td>
        </tr>
        <tr>
            <td align="right" class="v10">Website:&nbsp;</td>
            <td><input value="{URL}" name="guestbook_url" size="50" maxlength="1000" style="width: 350px;" id="guestbook_url" class="v12" /></td>
        </tr>
        <tr>
            <td valign="top" align="right" class="v10">&nbsp;&nbsp;Nachricht:&nbsp;</td>
            <td><textarea name="guestbook_msg" cols="50" rows="6" style="width: 350px;" id="guestbook_msg" class="v12">{MSG}</textarea></td>
        </tr>
        <tr>
            <td valign="top" align="right" class="v10">Anzeige:&nbsp;</td>
            <td><input type="radio" value="0" name="guestbook_show" checked="checked" />Email-Adresse anzeigen<br />
            <input type="radio" value="1" name="guestbook_show" />Email-Adresse verstecken<br />
            <input type="radio" value="2" name="guestbook_show" />Email-Adresse als &quot;info at mail dot com&quot; anzeigen</td>
        </tr>
        <tr>
            <td colspan="2"><img width="1" height="4" src="img/leer.gif" alt="" /></td>
        </tr>
        <tr>
            <td align="right">&nbsp;</td>
            <td><input type="submit" value="Eintrag abschicken" name="guestbook_send" id="guestbook_send" class="v11" /></td>
        </tr>
        <tr>
            <td colspan="2"><img width="1" height="6" src="img/leer.gif" alt="" /></td>
        </tr>
    </tbody>
</table>
<!--FORM_END//-->
<p style="background-color: rgb(207, 231, 247);"><strong>Erfolgsmeldung - wird angezeigt, wenn der G&auml;stebuch-Eintrag erstellt wurde<br />
</strong>{NAME}</p>
<p><!--FORM_SUCCESS_START//--></p>
<div style="margin-top: 5px; margin-bottom: 5px;">Vielen Dank, {<img src="img/leer.gif" border="0" width="0" height="0" alt="" />NAME}! Sie haben sich erfolgreich in unser G&auml;stebuch eingetragen.</div>
<!--FORM_SUCCESS_END//-->
<p>&nbsp;</p>
<p style="background-color: rgb(207, 231, 247);"><strong>G&auml;stebuch-Navigation<br />
</strong><span class="chatlist">{<img src="img/leer.gif" border="0" width="0" height="0" alt="" />FIRST:HTML}, {<img src="img/leer.gif" border="0" width="0" height="0" alt="" />LAST:HTML}, {<img src="img/leer.gif" border="0" width="0" height="0" alt="" />BACK:HTML}, {<img src="img/leer.gif" border="0" width="0" height="0" alt="" />NEXT:HTML}, {<img src="img/leer.gif" border="0" width="0" height="0" alt="" />JUMP:LISTTEXT|BUTTON|SPACER}, {<img src="img/leer.gif" border="0" width="0" height="0" alt="" />PAGE:COUNT:SPACER|WRAP_ACTIVE_BEFORE|AFTER}<br />
(<img src="img/leer.gif" border="0" width="0" height="0" alt="" />HTML = link text or image tag, like &lt;img src=&quot;back.gif&quot; border=&quot;0&quot; /&gt;)</span></p>
<!--NAV_START//-->
<table width="100%" cellspacing="0" cellpadding="0" border="0" style="margin-top: 5px;">
    <tbody>
        <tr>
            <td><strong>{</strong><img src="img/leer.gif" border="0" width="0" height="0" alt="" /><strong>FIRST:&lt;&lt;} {</strong><img src="img/leer.gif" border="0" width="0" height="0" alt="" /><strong>BACK:&lt;}</strong> {PAGE:5:&nbsp;|<strong>|</strong>} <strong>{</strong><img src="img/leer.gif" border="0" width="0" height="0" alt="" /><strong>NEXT:&gt;} {</strong><img src="img/leer.gif" border="0" width="0" height="0" alt="" /><strong>LAST:&gt;&gt;}</strong></td>
            <td align="right">{<img src="img/leer.gif" border="0" width="0" height="0" alt="" />ARCHIVE:%Y/%m|alle Eintr&auml;ge|go|&nbsp;}&nbsp;{<img src="img/leer.gif" border="0" width="0" height="0" alt="" />JUMP:page |go|&nbsp;}</td>
        </tr>
        <tr>
            <td colspan="2"><img width="1" height="3" src="img/leer.gif" alt="" /></td>
        </tr>
    </tbody>
</table><br /><br />
<!--NAV_END//-->
<p style="background-color: rgb(207, 231, 247);"><strong>G&auml;stebuch-Eintr&auml;ge<br />
</strong>{<img src="img/leer.gif" border="0" width="0" height="0" alt="" />EMAIL}, {<img src="img/leer.gif" border="0" width="0" height="0" alt="" />NAME}, {<img src="img/leer.gif" border="0" width="0" height="0" alt="" />URL:HTML}, {<img src="img/leer.gif" border="0" width="0" height="0" alt="" />MSG}, {<img src="img/leer.gif" border="0" width="0" height="0" alt="" />URL}, {<img src="img/leer.gif" border="0" width="0" height="0" alt="" />ID}, {<img src="img/leer.gif" border="0" width="0" height="0" alt="" />DBID}, {<img src="img/leer.gif" border="0" width="0" height="0" alt="" />TIMESTAMP:FORMAT} (<a target="_blank" href="http://www.php.net/manual/en/function.date.php" style="text-decoration: underline;">FORMAT&nbsp;=&nbsp;d.m.Y&nbsp;or&nbsp;H:i:s</a>)</p>
<!--GUESTBOOK_START//-->{<img src="img/leer.gif" border="0" width="0" height="0" alt="" />FORM} {<img src="img/leer.gif" border="0" width="0" height="0" alt="" />NAV}
<table width="100%" cellspacing="0" cellpadding="2" border="0">
    <!--GUESTBOOK_ENTRY_START//-->
    <tbody>
        <tr bgcolor="#cfe7f7">
            <td width="1%" align="right"><strong>{</strong><img src="img/leer.gif" border="0" width="0" height="0" alt="" /><strong>ID}&nbsp;&nbsp;</strong></td>
            <td width="99%">{<img src="img/leer.gif" border="0" width="0" height="0" alt="" />DBID} | {<img src="img/leer.gif" border="0" width="0" height="0" alt="" />TIMESTAMP:d.m.Y H:i:s}</td>
        </tr>
        <tr>
            <td colspan="2"><a href="mailto:{EMAIL}"><strong>{</strong><font color="#000000"><img src="img/leer.gif" border="0" width="0" height="0" alt="" /></font><strong>NAME}</strong></a> <strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{</strong><img src="img/leer.gif" border="0" width="0" height="0" alt="" /><strong>URL:Website besuchen}</strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Email: {<img src="img/leer.gif" border="0" width="0" height="0" alt="" />EMAIL}<br />
            {<img src="img/leer.gif" border="0" width="0" height="0" alt="" />MSG}</td>
        </tr>
        <tr>
            <td colspan="2"><img width="1" height="3" src="img/leer.gif" alt="" /></td>
        </tr>
        <!--GUESTBOOK_ENTRY_END//-->
    </tbody>
</table>
<!--GUESTBOOK_END//--><br /><br />
<p style="background-color: rgb(207, 231, 247);"><strong>Kommentar f&uuml;r bearbeitete Artikel</strong>[c]...[/c]<br />
normal HTML code like &lt;span style=&quot;color:#FF3300&quot;&gt;|&lt;/span&gt;<!--COMMENT_END//--></p><div align="right"><a href="#top"><img src="img/article/top_link_0.gif" border="0" alt="" /></a></div>
		 
		
		<br /><br />
		<div class="sub">
		Artikel erstellt am: Montag, 15. August 2005 <br /> Letzte &Auml;nderung: Dienstag, 04. Januar 2011	
		</div>
				
	</div>
	
<div id="footer"><br /><br />
<p style="height:30px;">&nbsp;</p>


 <script type="text/javascript" language="javascript">
<!--

var showDefaultValue =  0

function hideLayer(whichLayer) {
	if (document.getElementById) {
		// this is the way the standards work
		document.getElementById(whichLayer).style.display = "none";
	} else if (document.all) {
		// this is the way old msie versions work
		document.all[whichlayer].style.display = "none";
	} else if (document.layers) {
		// this is the way nn4 works
		document.layers[whichLayer].display = "none";
	}
}

function showLayer(whichLayer) {
		//	alert(whichLayer);
	if (document.getElementById) {
		// this is the way the standards work
		document.getElementById(whichLayer).style.display = "block";
	}
	else if (document.all) {
		// this is the way old msie versions work
		document.all[whichlayer].style.display = "block";
	}
	else if (document.layers) {
		// this is the way nn4 works
		document.layers[whichLayer].display = "block";
	}
}

function toggleLayer(whichLayer) {
	if(showDefaultValue == 0) {
		hideLayer(whichLayer);
		showDefaultValue = 1;
	} else {
		showLayer(whichLayer);
		showDefaultValue = 0;
	}
}
//-->
</script>


<div id="alles">
<div id="klapper" onclick="toggleLayer('formular');">
<table width="570" border="0" cellspacing="0" cellpadding="0">
<tr>
<td><em style="color:#275EA8;" onmouseover="this.style.color='#4F96F4';" onmouseout="this.style.color='#275EA8';">Sie haben Anregungen oder Kritik zu diesem Artikel? Schreiben Sie uns!</em></td>   
<td align="right" style="padding-right:2px;"><img src="template/lang/all/icons/write.gif" width="16" height="21" alt="" border="0" /></td>
</tr>
</table>

</div>
<div id="formular">

<form name="form" method="post" action="index.php?id=195,303,0,1,1,0" style="margin:0;padding:0;"><input type="hidden" name="customForm" value="1" /><input type="hidden" name="docucheck" value="1" />


<div style="float:left;">
<p><select name="Betreff" id="Betreff" class="size1">
<option value="" class="deepblue"> Bitte ausw&auml;hlen </option>
<option value="subject_1" class="inselect">Anregungen</option>
<option value="subject_2" class="inselect">Fehlermeldung/ Kritik</option>
<option value="subject_3" class="inselect">Sonstiges</option>

</select><br /></p>


<p>Vorname:<br />
<input type="text" name="Vorname" value="" class="size1" /></p>
<p>Name:*<br />
<input type="text" name="Name" value="" class="size1" /></p>
<p>E-Mail:*<br />
<input type="text" name="E-Mail" value="" class="size1" /></p>
</div>


<div style="float:right;">Mitteilung:*<br />
<textarea name="Nachricht" cols="40" rows="4"  class="size7"></textarea>
</div>

<p style="clear:both; text-align:right;"><input type="reset" name="reset" value="Zur&uuml;cksetzen" class="btstyle" style="width:100px;" />&nbsp;&nbsp;
<input type="submit" name="submit" value="Anfrage senden" class="btstyle" style="width:110px;" /></p>
<p style="margin:20px;" class="sub">* Pflichtangaben. Ihre Daten werden ausschlie&szlig;lich für diese Anfrage verwendet.</p>

</form>
</div>
</div>
 <script type="text/javascript" language="javascript">
<!--
	// Lösung ohne Onload
	toggleLayer('formular');
//-->
</script>
<br />





	<table width="97%" border="0" cellspacing="0" cellpadding="0">
		<tr>
			<td valign="bottom">	
			&copy; phpwcms-docu 2004-2013
			<img src="img/leer.gif" border="0" width="10" height="0" alt="" /><a href="impressum.phtml" class="phpwcmsIntLink"><img src="template/lang/all/icons/imprint.gif" width="9" height="15" alt="Impressum" title="Impressum" border="0" /></a>&nbsp; 
			<a href="sitemap_de.phtml" class="phpwcmsIntLink"><img src="template/lang/all/icons/sitemap.gif" width="19" height="15" alt="Sitemap" title="Sitemap" border="0" /></a>&nbsp; 
			<a href="gaestebuch.phtml" class="phpwcmsIntLink"><img src="template/lang/all/icons/gbook.gif" width="20" height="16" alt="Ins G&auml;stebuch eintragen" title="Ins G&auml;stebuch eintragen" border="0" /></a>&nbsp; 
			<a href="#" onclick="BookMark_Page();return false;" title="" class="phpwcmsBookmarkLink"><img src="template/lang/all/icons/favo.gif" width="12" height="15" alt="Seite als Bookmark speichern" title="Seite als Bookmark speichern" border="0" /></a>&nbsp; 
			     
			</td>
			<td valign="bottom" style="padding-right:25px;">
			
			
			
			</td>		
			<td width="150">
			</td>
		</tr>
	</table>
</div><br/>

</div>
</body>
</html>