<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<!--
	phpwcms | free open source content management system
	created by Oliver Georgi (oliver at phpwcms dot de) and licensed under GNU/GPL.
	phpwcms is copyright 2003-2007 of Oliver Georgi. Extensions are copyright of
	their respective owners. Visit project page for details: http://www.phpwcms.org/
//-->
<title>phpwcms-docu for  phpwcms :: web based content management system | Message center | Read Message</title>
  <meta http-equiv="content-type" content="text/html; charset=iso-8859-1" />
  <meta http-equiv="content-style-type" content="text/css" />
  <script src="template/inc_js/frontend.js" type="text/javascript"></script>
  <style type="text/css">
  <!-- 
    @import url("template/inc_css/mpl_frontend.css");
    @import url("template/inc_css/mpl_menu.css");
    @import url("template/inc_css/mpl_objects.css");
    @import url("template/inc_css/mpl_docu_en.css");
  //-->
  </style>
<meta name="Title" content="The phpWCMS Documentation" />
<meta name="author" content="Oliver Frohnert, Mario Perez Leal" />
<meta name="Publisher" content="Oliver Frohnert, Mario Perez Leal, creacion" />
<meta name="Copyright" content="Oliver Frohnert, Mario Perez Leal, creacion" />
<meta name="keywords" content="frohnert, perez leal, creacion, documentation, dokumentation, phpwcms, cms, opensource, open source, docu" />
<meta name="description" content="A Documentation Project for the  Open Source CMS phpWCMS" />
<meta name="Audience" content="Alle" />
<meta name="Content-language" content="EN" />
<meta name="robots"      content="index,follow" />
<meta name="expires" content="0" />
<meta name="revisit-after" content="7 days" />
<meta name="resource-type" content="document" />
<meta name="distribution" content="Global" />
<meta name="generator" content="PHPWCMS" />

  <!--[if lt IE 7]>
  <style type="text/css">
    body { behavior: url("template/inc_css/specific/csshover2.htc"); }
    img { behavior: url("template/inc_css/specific/pngbehavior.htc"); }
  </style>
  <![endif]-->
</head>
<body id="myid_421">
<div id="container"><a name="top" id="top"></a>


	<div id="head">
		
	<div id="mainnavi">
		<div class="fleft"><a href="english_version.phtml">Home</a> | <a href="news_en.phtml">News</a> | <span style="text-decoration:none;font-weight:bold;"><a href="the_docu.phtml">The Docu</a></span> | <a href="Usefull_Links_and_Tools.phtml">Links &amp; Tools</a> | <a href="contact.phtml">Contact</a> | <a href="faq_en.phtml">FAQ</a> | <a href="http://forum.phpwcms.org/" target="_blank">Forum</a> | <a href="howto_en.phtml">HowTo</a></div>				
		<div class="sys">Saturday, 27. July 2013<img src="img/leer.gif" border="0" width="5" height="1" alt="" />|<img src="img/leer.gif" border="0" width="5" height="1" alt="" />5 User online<img src="img/leer.gif" border="0" width="10" height="1" alt="" />
		<a href="deutsche_version.phtml" title="Deutsche Version"><img src="picture/../template/lang/all/flag_de.gif" border="0" alt="" /></a>
		<a href="english_version.phtml"  title="English version"><img src="picture/../template/lang/all/flag_en.gif" border="0" alt="" /></a>
		</div>
	</div>
	
	<a href="./" title="phpwcms-docu Startseite aufrufen" class="homelink">
	<span>&raquo; phpwcms-docu startpage</span></a>
	<h2>phpwcms-docu - Documentation for the Web Content Management System phpwcms</h2>
	<p>This website is targeted both to the beginner and the lateral entry following the goal to simplify the 
work with phpwcms and to focus on the essentials things.</p>
	</div>

	
	<div id="left">
	<div class="leftnav" style="margin-top:24px;">
	
<div id="ul_div_311">
<ul>
	<li class="sub_no"><a href="download-dev-versions.phtml">Download Dev Versions</a></li>
	<li class="sub_no sub_ul_true"><a href="installation_en.phtml">Installation &amp; Upgrade</a></li>
	<li class="sub_no sub_ul_true"><a href="article.phtml">Articles</a></li>
	<li class="sub_no sub_ul_true"><a href="file.phtml">File</a></li>
	<li class="sub_no sub_ul_true"><a href="module_en.phtml">Modules</a></li>
	<li class="sub_ul"><a href="communication.phtml">Communication </a>
	<div id="ul_div_219">
	<ul>
		<li class="sub_no"><a href="ommunication_newsletter.phtml"><span style="text-decoration:line-through;font-size:10px;">Newsletter</span></a></li>
		<li class="sub_no"><a href="communication_newsletter_subscriptions.phtml">Newsletter subscriptions</a></li>
		<li class="sub_no active"><a href="communication_message_center.phtml">Message center</a></li>
		<li class="sub_no"><a href="communication_write_message.phtml">New Message </a></li>
	</ul>
	</div>
	</li>
	<li class="sub_no"><a href="chat_en.phtml">Chat</a></li>
	<li class="sub_no"><a href="profile.phtml">Profile</a></li>
	<li class="sub_no sub_ul_true"><a href="admin_en_.phtml">Admin</a></li>
	<li class="sub_no sub_ul_true"><a href="add-ons-and-templates.phtml">Add On&#039;s and Templates</a></li>
	<li class="sub_no"><a href="deutsche_version.phtml?replacement_tags_en">Replacement Tags</a></li>
	<li class="sub_no"><a href="deutsche_version.phtml?content_parts_en">Content Parts</a></li>
</ul>
</div>

		
	</div> 
	</div> 
	  
	<div id="right">
		<div style="margin-top:24px;">			
		<form action="#" method="post" name="searchFE" onsubmit="s=document.getElementById('customSearchInput');if(s.value=='Search')return false;">
			<table width="100%" border="0" cellpadding="0" cellspacing="0">
			<tr>
					<td><input type="text" name="search_input_field" size="20" maxlength="200" id="customSearchInput" class="customSearchInput" value="" onfocus="if(this.value=='Search')this.value='';" onblur="if(this.value=='')this.value='Search';"/></td>
					<td><input type="image" name="search_go" onfocus="this.blur();" title="Search" src="/template/lang/all/submit.gif" /></td>
				</tr>
			</table>
			</form>
			
			      <script type="text/javascript" language="javascript">
			  <!-- 
			        document.getElementById("customSearchInput").value="Search";
			  //-->
			      </script>
				  
<!-- <p style="margin-top:10px;">Change font size: <a href="[FontSize-]"><img src="template/lang/all/icons/reduce.gif" width="18" height="17" alt="" title="Small" border="0" /></a>
			<a href="[FontSize+]"><img src="template/lang/all/icons/extend.gif" width="18" height="17" alt="" title="Bigger" border="0" /></a>
			</p> -->
			
	<p style="margin-top:10px;">Please choose: 
	
	 </p>

<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div>

<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div>
<!-- <a href="http://validator.w3.org/check?uri=http%3A%2F%2Fwww.phpwcms-docu.de%2Findex.php%3Fdeutsche_version" title="W3C Standard XHTML" target="_blank"><img src="picture/w3c/w3c_xhtml.gif" border="0" alt="" /></a>
<a href="http://jigsaw.w3.org/css-validator/validator?uri=http://www.phpwcms-docu.de" title="W3C Standard CSS" target="_blank"><img src="picture/w3c/w3c_css.gif" border="0" alt="" /></a><br />			
<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div> -->
		
<div style="margin-top:10px; margin-bottom:15px;"></div>
	
</div>

	</div> 
	
	<div id="content">
	<div id="bread">You are here: <a href="english_version.phtml">English</a> <span class="breadcrumb_spacer">&gt;</span> <a href="the_docu.phtml">The Docu</a> <span class="breadcrumb_spacer">&gt;</span> <a href="communication.phtml">Communication </a> <span class="breadcrumb_spacer">&gt;</span> Message center</div>
		
		<a name="jump225"></a><!-- Livedate: 27.11.2004 11:00:40 / Killdate: 31.12.2030 23:59:59 -->
<h1>Read Message</h1>
<h3>and answer</h3>

<table width="158" border="0" cellspacing="0" cellpadding="0" align="left">
<tr><td class="image_td2"><a href="zoom/MzY1YmYzZDdjOGJhNGM2ZTVhNGUxMTdmNzc3N2NjN2UucG5nP3dpZHRoPSI3NjciIGhlaWdodD0iNDk2Ig.html" onclick="checkClickZoom();clickZoom('zoom/MzY1YmYzZDdjOGJhNGM2ZTVhNGUxMTdmNzc3N2NjN2UucG5nP3dpZHRoPSI3NjciIGhlaWdodD0iNDk2Ig.html','previewpic','width.html');return false;.html"><img src="content/images/a6affbd3ebd1df583d33d4696cd6cd47.png" width="150" height="97" border="0" class="image_img" alt="nachricht_lesen_01.png" /></a></td><td><img src="img/leer.gif" width="8" height="1" border="0" alt="" /></td></tr>
<tr><td align="center" class="image_caption"><img src="picture/icon_lupe_.gif" border="0" alt="" /><img src="content/gt/be1db930b6ac6f64e566b4590d6afb5a.png" alt="Zoom" title="Zoom" width="31" height="13" border="0" /></td><td><img src="img/leer.gif" width="8" height="1" border="0" alt="" /></td></tr>
</table><div class="articleText"><TABLE height=113 cellSpacing=0 cellPadding=0 width="70%" border=0>
<TBODY>
<TR>
<TD vAlign=top>When you receive a internal message, you see after you logged in the system this symbol <br />
<TABLE height=10 cellSpacing=0 cellPadding=0 width=12 align=center border=0>
<TBODY>
<TR>
<TD style="BACKGROUND: red" align=middle><img src="picture/../img/symbole/new_mail.gif" border="0" alt="" /></TD></TR></TBODY></TABLE><br />in the upper red line. Now you have two possibilities to read the massage. Either you click on the symbol or you click in the same line on "<STRONG>Message"</STRONG>.<br /></TD></TR></TBODY></TABLE></div><div style="margin:20px 0 0 0;padding:0;" class="spaceBeforeCP"></div><h3>Message overview</h3><table width="160" border="0" cellspacing="0" cellpadding="0" align="right">
<tr><td><img src="img/leer.gif" width="10" height="1" border="0" alt="" /></td><td class="image_td2"><a href="zoom/NWU2NGEzMzlmNTg0YmJjZmFiNDJjYzhiOGY5MWZiMDgucG5nP3dpZHRoPSI3NjciIGhlaWdodD0iMzk3Ig.html" onclick="checkClickZoom();clickZoom('zoom/NWU2NGEzMzlmNTg0YmJjZmFiNDJjYzhiOGY5MWZiMDgucG5nP3dpZHRoPSI3NjciIGhlaWdodD0iMzk3Ig.html','previewpic','width.html');return false;.html"><img src="content/images/6f7c564e3616fd75ae9ce17a572a7141.png" width="150" height="77" border="0" class="image_img" alt="nachricht_lesen_02.png" /></a></td></tr>
<tr><td><img src="img/leer.gif" width="10" height="1" border="0" alt="" /></td><td align="center" class="image_caption"><img src="picture/icon_lupe_.gif" border="0" alt="" /><img src="content/gt/be1db930b6ac6f64e566b4590d6afb5a.png" alt="Zoom" title="Zoom" width="31" height="13" border="0" /></td></tr>
</table><div class="articleText">After you clicked on one of these possibilities you get to the message overview. There you can see who send you a message and what the subject is. At the right you see two icons.<br /><br />The first icon <img src="picture/../img/button/reply_mini.gif" border="0" alt="" />&nbsp;pass you throught to the reply-page. <br />The second icon <img src="picture/../img/icons/trash.gif" border="0" alt="" /> deletes the message. Deleted messages won´t be deleted irrecoverable, but transferred to the folder “deleted”.<br /><br />If you click either on the sender of the message or the subject you can read the message.</div><div style="margin:20px 0 0 0;padding:0;" class="spaceBeforeCP"></div><h3>Read message</h3><table width="158" border="0" cellspacing="0" cellpadding="0" align="left">
<tr><td class="image_td2"><a href="zoom/NWY3OTQzZjU3NGNmMGRkNDA5N2RjMmJhYjAyNGI5OWQucG5nP3dpZHRoPSI3NjciIGhlaWdodD0iMzk4Ig.html" onclick="checkClickZoom();clickZoom('zoom/NWY3OTQzZjU3NGNmMGRkNDA5N2RjMmJhYjAyNGI5OWQucG5nP3dpZHRoPSI3NjciIGhlaWdodD0iMzk4Ig.html','previewpic','width.html');return false;.html"><img src="content/images/546eb0388a3decd816f6934ec05e4164.png" width="150" height="77" border="0" class="image_img" alt="nachricht_lesen_04.png" /></a></td><td><img src="img/leer.gif" width="8" height="1" border="0" alt="" /></td></tr>
<tr><td align="center" class="image_caption"><img src="picture/icon_lupe_.gif" border="0" alt="" /><img src="content/gt/be1db930b6ac6f64e566b4590d6afb5a.png" alt="Zoom" title="Zoom" width="31" height="13" border="0" /></td><td><img src="img/leer.gif" width="8" height="1" border="0" alt="" /></td></tr>
</table><div class="articleText">Here you can read noow the massages. Beneath the massages you find 4 icons.&nbsp;<br /><br />These are the meanings or the single icons.&nbsp;<br />&nbsp;<br />
<TABLE cellSpacing=1 cellPadding=1 width="100%" border=0>
<TBODY>
<TR>
<TD><img src="picture/../img/button/close_message.gif" border="0" alt="" /></TD>
<TD></TD>
<TD>close the massage</TD></TR>
<TR>
<TD><img src="picture/../img/button/new_message1.gif" border="0" alt="" /></TD>
<TD></TD>
<TD>Create a new message without reference to the message you are just now reading.</TD></TR>
<TR>
<TD><img src="picture/../img/button/reply_to_message1.gif" border="0" alt="" /></TD>
<TD></TD>
<TD>attant to the answeringpage</TD></TR>
<TR>
<TD><img src="picture/../img/button/message_to_trash.gif" border="0" alt="" /></TD>
<TD>&nbsp;&nbsp;&nbsp; </TD>
<TD>deletes your message</TD></TR></TBODY></TABLE></div><div style="margin:20px 0 0 0;padding:0;" class="spaceBeforeCP"></div><h3>Answer a message</h3><table width="160" border="0" cellspacing="0" cellpadding="0" align="right">
<tr><td><img src="img/leer.gif" width="10" height="1" border="0" alt="" /></td><td class="image_td2"><a href="zoom/ZGVmMTc4YjE1ZjczYThiOTNkNDZiYjM0M2U3NjgzMzUucG5nP3dpZHRoPSI3NjciIGhlaWdodD0iNTQyIg.html" onclick="checkClickZoom();clickZoom('zoom/ZGVmMTc4YjE1ZjczYThiOTNkNDZiYjM0M2U3NjgzMzUucG5nP3dpZHRoPSI3NjciIGhlaWdodD0iNTQyIg.html','previewpic','width.html');return false;.html"><img src="content/images/e67b955599a58b5fcbdd16ba2a068db5.png" width="150" height="105" border="0" class="image_img" alt="nachricht_lesen_03.png" /></a></td></tr>
<tr><td><img src="img/leer.gif" width="10" height="1" border="0" alt="" /></td><td align="center" class="image_caption"><img src="picture/icon_lupe_.gif" border="0" alt="" /><img src="content/gt/be1db930b6ac6f64e566b4590d6afb5a.png" alt="Zoom" title="Zoom" width="31" height="13" border="0" /></td></tr>
</table><div class="articleText">here you can answer to a message.It woks the same way as&nbsp;<a href="write_message.phtml" class="phpwcmsIntLink">write message</a>. The only difference is, that you don´t have to choose a reciever.<br /><br /><br /><br /><br /></div><div align="right"><a href="#top"><img src="img/article/top_link_0.gif" border="0" alt="" /></a></div>
		 
		
		<br /><br />
		<div class="sub">
		Article created: Saturday, 27. November 2004 <br /> Last Changes: Tuesday, 4. January 2011	
		</div>
				
	</div>
	
<div id="footer">





	<table width="97%" border="0" cellspacing="0" cellpadding="0">
		<tr>
			<td valign="bottom">	
			&copy; phpwcms-docu 2004-2013
			<img src="img/leer.gif" border="0" width="10" height="0" alt="" /><a href="imprint.phtml" class="phpwcmsIntLink"><img src="template/lang/all/icons/imprint.gif" width="9" height="15" alt="Impressum" title="Impressum" border="0" /></a>&nbsp; 
			<a href="sitemap_en.phtml" class="phpwcmsIntLink"><img src="template/lang/all/icons/sitemap.gif" width="19" height="15" alt="Sitemap" title="Sitemap" border="0" /></a>&nbsp; 
			 
			
			     
			</td>
			<td valign="bottom" style="padding-right:25px;">
			
			
			
			</td>		
			<td width="150">
			</td>
		</tr>
	</table>
</div><br/>

</div>
</body>
</html>