<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<!--
	phpwcms | free open source content management system
	created by Oliver Georgi (oliver at phpwcms dot de) and licensed under GNU/GPL.
	phpwcms is copyright 2003-2007 of Oliver Georgi. Extensions are copyright of
	their respective owners. Visit project page for details: http://www.phpwcms.org/
//-->
<title>phpwcms-docu for  phpwcms :: web based content management system | Formular | Content Part &quot;Formular&quot;{D:9/30/2005,30,editR.gif}</title>
  <meta http-equiv="content-type" content="text/html; charset=iso-8859-1" />
  <meta http-equiv="content-style-type" content="text/css" />
  <script src="template/inc_js/frontend.js" type="text/javascript"></script>
  <style type="text/css">
  <!-- 
    @import url("template/inc_css/mpl_docu.css");
    @import url("template/inc_css/mpl_frontend.css");
    @import url("template/inc_css/mpl_menu.css");
    @import url("template/inc_css/mpl_objects.css");
  //-->
  </style>
<script type="text/javascript" language="javascript">
<!--
function MM_jumpMenu(targ,selObj,restore){ //v3.0
  eval(targ+".location='"+selObj.options[selObj.selectedIndex].value+"'");
  if (restore) selObj.selectedIndex=0;
}

function MM_findObj(n, d) { //v4.01
  var p,i,x;  if(!d) d=document; if((p=n.indexOf("?"))>0&&parent.frames.length) {
    d=parent.frames[n.substring(p+1)].document; n=n.substring(0,p);}
  if(!(x=d[n])&&d.all) x=d.all[n]; for (i=0;!x&&i<d.forms.length;i++) x=d.forms[i][n];
  for(i=0;!x&&d.layers&&i<d.layers.length;i++) x=MM_findObj(n,d.layers[i].document);
  if(!x && d.getElementById) x=d.getElementById(n); return x;
}

function MM_jumpMenuGo(selName,targ,restore){ //v3.0
  var selObj = MM_findObj(selName); if (selObj) MM_jumpMenu(targ,selObj,restore);
}
//-->
</script>
<meta name="Title" content="Die phpWCMS Dokumentation" />
<meta name="author" content="Oliver Frohnert, Mario Perez Leal" />
<meta name="Publisher" content="Oliver Frohnert, Mario Perez Leal, creacion" />
<meta name="Copyright" content="Oliver Frohnert, Mario Perez Leal, creacion" />
<meta name="keywords" content="frohnert, perez leal, creacion, documentation, dokumentation, phpwcms, cms, opensource, open source, docu" />
<meta name="description" content="Das Dokumentations Projekt für das Open Source CMS phpWCMS" />
<meta name="Audience" content="Alle" />
<meta name="Content-language" content="DE" />
<meta name="robots" content="index,follow" />
<meta name="expires" content="0" />
<meta name="revisit-after" content="7 days" />
<meta name="resource-type" content="document" />
<meta name="distribution" content="Global" />
<meta name="generator" content="PHPWCMS" />
<meta name="verify-v1" content="1ZpxZ7AZsjm7PxjqXQVus0eiUYqOsp5URTJn9q4KNz8=" />
  <link rel="stylesheet" href="template/slimbox/css/slimbox.css" type="text/css" media="screen" />
  <script src="template/inc_js/mootools/mootools.js" type="text/javascript"></script>
  <script src="template/slimbox/js/slimbox.js" type="text/javascript"></script>
  <!--[if lt IE 7]>
  <style type="text/css">
    body { behavior: url("template/inc_css/specific/csshover2.htc"); }
    img { behavior: url("template/inc_css/specific/pngbehavior.htc"); }
  </style>
  <![endif]-->
</head>
<body id="myid_379">
<div id="container"><a name="top" id="top"></a>


	<div id="head">
		
	<div id="mainnavi">
		<div class="fleft"><a href="deutsche_version.phtml">Startseite</a> | <a href="news_de.phtml">News</a> | <span style="text-decoration:none;font-weight:bold;"><a href="die_docu.phtml">Die Docu</a></span> | <a href="Nuetzliche_Links_und_Tools.phtml">Links &amp; Tools</a> | <a href="downloads.phtml">Downloads</a> | <a href="kontakt.phtml">Kontakt</a> | <a href="faq_de.phtml">FAQ</a> | <a href="http://forum.phpwcms.org/" target="_blank">Forum</a> | <a href="howto_de.phtml">HowTo</a></div>				
		<div class="sys">Donnerstag, 9. Juli 2015<img src="img/leer.gif" border="0" width="5" height="1" alt="" />|<img src="img/leer.gif" border="0" width="5" height="1" alt="" />1 User online<img src="img/leer.gif" border="0" width="10" height="1" alt="" />
		<a href="deutsche_version.phtml" title="Deutsche Version"><img src="picture/../template/lang/all/flag_de.gif" border="0" alt="" /></a>
		<a href="english_version.phtml"  title="English version"><img src="picture/../template/lang/all/flag_en.gif" border="0" alt="" /></a>
		</div>
	</div>
	
	<a href="./" title="phpwcms-docu Startseite aufrufen" class="homelink">
	<span>&raquo; Zur phpwcms-docu Startseite</span></a>
	<h2>phpwcms-docu - Die Dokumentation f&uuml;r f&uuml;r das CMS phpWCMS</h2>
	<p>phpwcms-docu ist eine Art Kompass, der Ihnen die M&ouml;glichkeiten von phpWcms aufzeigt und Sie erfolgreich, ohne gro&szlig;e Umwege, zu Ihrer fertigen Web-Anwendung f&uuml;hren soll.
	</p>
	</div>

	
	<div id="left">
	<div class="leftnav" style="margin-top:24px;">
	
<div id="ul_div_309">
<ul>
	<li class="sub_no"><a href="download-dev-versionen.phtml">Download Dev Versionen</a></li>
	<li class="sub_no sub_ul_true"><a href="installation_und_upgrade_von_phpwcms.phtml">Installation &amp; Upgrade</a></li>
	<li class="sub_ul"><a href="verwaltung_artikel.phtml">Artikel</a>
	<div id="ul_div_82">
	<ul>
		<li class="sub_no"><a href="artikel_erstellen.phtml">Artikel erstellen</a></li>
		<li class="sub_no"><a href="artikel_editieren.phtml">Artikel bearbeiten</a></li>
		<li class="sub_no sub_ul_true"><a href="artikel_organisation.phtml">Artikel Organisation</a></li>
		<li class="sub_ul"><a href="content_parts_de.phtml">Content Parts</a>
		<div id="ul_div_100">
		<ul>
			<li class="sub_no"><a href="einfacher_text.phtml">Einfacher Text</a></li>
			<li class="sub_no"><a href="content_part_html_de.phtml">HTML</a></li>
			<li class="sub_no"><a href="content_part_wysiwyg_html_de.phtml">WYSIWYG HTML</a></li>
			<li class="sub_no"><a href="content_part_code_de.phtml">Code</a></li>
			<li class="sub_no"><a href="content_part_text_mit_bild.phtml">Text mit Bild</a></li>
			<li class="sub_no"><a href="content_part_bilder_div.phtml"><span style="text-decoration:line-through;font-size:10px;">Bilder &lt;DIV&gt;</span></a></li>
			<li class="sub_no"><a href="content_part_bilder.phtml">Bilder</a></li>
			<li class="sub_no"><a href="content_part_aufzaehlung.phtml">Aufzählung</a></li>
			<li class="sub_no"><a href="content_part_liste.phtml">Liste</a></li>
			<li class="sub_no"><a href="content_part_link_und_e-mail.phtml">Link &amp; E-Mail</a></li>
			<li class="sub_no"><a href="content_part_linkliste.phtml">Linkliste</a></li>
			<li class="sub_no"><a href="content_part_artikellink.phtml">Artikellink</a></li>
			<li class="sub_no"><a href="content_part_teaser_artikellink.phtml"><span style="text-decoration:line-through;font-size:10px;">Teaser / Artikellink</span></a></li>
			<li class="sub_no"><a href="content_part_artikelmenue.phtml">Artikelmenü</a></li>
			<li class="sub_no"><a href="content_part_multimedia_de.phtml">Multimedia</a></li>
			<li class="sub_no"><a href="content_part_dateiliste.phtml">Dateiliste</a></li>
			<li class="sub_no sub_ul_true"><a href="content_part_ecard_de.phtml">E-Card</a></li>
			<li class="sub_no active"><a href="content_part_formular.phtml">Formular</a></li>
			<li class="sub_no sub_ul_true"><a href="content_part_e-mail_formulargenerator.phtml">E-Mail Form. [OLD]</a></li>
			<li class="sub_no"><a href="content_part_e-mail_formular.phtml">E-Mail Formular</a></li>
			<li class="sub_no sub_ul_true"><a href="content_part_newsletter_de.phtml">Newsletter</a></li>
			<li class="sub_no"><a href="content_part_suche.phtml">Suche</a></li>
			<li class="sub_no sub_ul_true"><a href="content_part_gaestebuch_kommentar.phtml">Gästebuch / Komm.</a></li>
			<li class="sub_no"><a href="content_part_sitemap_de.phtml">Sitemap</a></li>
			<li class="sub_no"><a href="content_part_externer_content.phtml">Ext. Content</a></li>
			<li class="sub_no"><a href="content_part_bildwechsel.phtml">Bildwechsel</a></li>
			<li class="sub_no"><a href="content_part_rss_feed_de.phtml">RSS Feed</a></li>
			<li class="sub_no"><a href="content_part_landkarte.phtml">Landkarte</a></li>
			<li class="sub_no"><a href="content_part_php_variablen.phtml">PHP Variablen</a></li>
			<li class="sub_no"><a href="content_part_contentpart_alias_de.phtml">Contentpart Alias</a></li>
			<li class="sub_no"><a href="content_part_poll_de.phtml"><span style="text-decoration:line-through;font-size:10px;">Poll</span></a></li>
			<li class="sub_no"><a href="content_part_kochrezept.phtml">Kochrezept</a></li>
			<li class="sub_no"><a href="content_part_faq_de.phtml">FAQ</a></li>
			<li class="sub_no"><a href="content_part_frontend_login_de.phtml"><span style="text-decoration:line-through;font-size:10px;">Frontend Login</span></a></li>
			<li class="sub_no"><a href="content_part_glossar.phtml"><span style="text-decoration:line-through;font-size:10px;">Plug-in: Glossar</span></a></li>
		</ul>
		</div>
		</li>
	</ul>
	</div>
	</li>
	<li class="sub_no sub_ul_true"><a href="dateizentrale.phtml">Datei</a></li>
	<li class="sub_no sub_ul_true"><a href="verwaltung_module.phtml">Module</a></li>
	<li class="sub_no sub_ul_true"><a href="Kommunikation.phtml">Kommunikation</a></li>
	<li class="sub_no"><a href="verwaltung_nachricht.phtml">Nachricht</a></li>
	<li class="sub_no"><a href="verwaltung_chat.phtml">Chat</a></li>
	<li class="sub_no"><a href="verwaltung_profil.phtml">Profil</a></li>
	<li class="sub_no sub_ul_true"><a href="verwaltung_admin.phtml">Admin</a></li>
	<li class="sub_no sub_ul_true"><a href="add-on-und-vorlagen.phtml">Add Ons und Vorlagen</a></li>
	<li class="sub_no"><a href="deutsche_version.phtml?replacement_tags_de">Replacement Tags</a></li>
	<li class="sub_no"><a href="deutsche_version.phtml?content_parts_de">Content Parts</a></li>
</ul>
</div>

		
		
		

	</div> 
	</div> 
	  
	<div id="right">
		<div style="margin-top:24px;">			
		<form action="index.php?suche" method="post" name="searchFE" onsubmit="s=document.getElementById('customSearchInput');if(s.value=='Suchen')return false;">
			<table width="100%" border="0" cellpadding="0" cellspacing="0">
			<tr>
					<td><input type="text" name="search_input_field" size="20" maxlength="200" id="customSearchInput" class="customSearchInput" value="" onfocus="if(this.value=='Suchen')this.value='';" onblur="if(this.value=='')this.value='Suchen';" /></td>
					<td><input type="image" name="search_go" onfocus="this.blur();" title="Suchen" src="/template/lang/all/submit.gif" /></td>
				</tr>
			</table>
			</form>
			
			      <script type="text/javascript" language="javascript">
			  <!-- 
			        document.getElementById("customSearchInput").value="Suchen";
			  //-->
			      </script>
				  
			<!-- <p style="margin-top:10px;">Schriftgrad &auml;ndern: <a href="[FontSize-]"><img src="template/lang/all/icons/reduce.gif" width="18" height="17" alt="" title="Verkleinern" border="0" /></a>
			<a href="[FontSize+]"><img src="template/lang/all/icons/extend.gif" width="18" height="17" alt="" title="Vergr&ouml;&szlig;ern" border="0" /></a>
			</p> -->
			
	<p style="margin-top:10px;">Bitte w&auml;hlen Sie: 
	
	 </p>
<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div>


<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div>
<!-- <a href="http://validator.w3.org/check?uri=http%3A%2F%2Fwww.phpwcms-docu.de%2Findex.php%3Fdeutsche_version" title="W3C Standard XHTML" target="_blank"><img src="picture/w3c/w3c_xhtml.gif" border="0" alt="" /></a>
<a href="http://jigsaw.w3.org/css-validator/validator?uri=http://www.phpwcms-docu.de" title="W3C Standard CSS" target="_blank"><img src="picture/w3c/w3c_css.gif" border="0" alt="" /></a><br />			
<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div> -->
<h3>Partnersites</h3>






<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div>

<div style="margin-top:10px; margin-bottom:15px;"></div>


<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div>
</div>

	</div> 
	
	<div id="content">
	<div id="bread">Sie sind hier: <a href="deutsche_version.phtml">Deutsch</a> <span class="breadcrumb_spacer">&gt;</span> <a href="die_docu.phtml">Die Docu</a> <span class="breadcrumb_spacer">&gt;</span> <a href="verwaltung_artikel.phtml">Artikel</a> <span class="breadcrumb_spacer">&gt;</span> <a href="content_parts_de.phtml">Content Parts</a> <span class="breadcrumb_spacer">&gt;</span> Formular</div>
		
		<a name="jump283"></a><!-- Livedate: 12.04.2005 10:33:13 / Killdate: 31.12.2030 23:59:59 -->
<h1>Content Part &quot;Formular&quot;</h1>
<h3>früher &quot;E-Mail Kontaktformular&quot;</h3>

<p><strong class="error">Hinweis:<br />
Dieser Content Part &quot;E-Mail Kontaktformular&quot; kam mit der Version 1.2.<br />
Mit der Version 1.2.9. wurde er umbenannt in &quot;Formular&quot;</strong></p><div style="border-bottom:1px dotted #d2e2f5; margin-top:10px; margin-bottom:15px;"></div><div style="margin:25px 0 0 0;padding:0;" class="spaceBeforeCP"></div><table width="100%" cellpadding="0" cellspacing="0" border="0" class="imgTextRight">
<tr>
<td valign="top" width="10%" class="image_td2"><div class="imgDIVblockImgLeft"><div class="image_td2"><a href="content/images/b07ecbda9343ed889eefa93bef716858.png" rel="lightbox" title="Content Part &quot;Formular&quot;" target="_blank"><img src="content/images/a4f6b05e37cda6dc50b7e93ac8fcf209.png" width="130" height="250" border="0" class="image_img" alt="Formular.png" /></a></div><p class="image_caption">Content Part &quot;Formular&quot;</p></div></td>
<td valign="top" class="articleText"><p>Hier finden Sie die Beschreibung wie Sie <br />
ein E-Mail Kontaktformular einrichten k&ouml;nnen.</p>
<p>In &auml;lteren Versionen von phpwcms wurde dieser content Part<br />
als E-Mail Kontaktformular bezeichnet.</p>
<p><br />
Nachfolgend&nbsp; eine &Uuml;bersicht der zur Verf&uuml;gung stehenden<br />
Eingabe-Felder.</p></td>
</tr>
</table><div style="border-bottom:1px dotted #d2e2f5; margin-top:10px; margin-bottom:15px;"></div><fieldset><legend><img width="21" height="22" border="0" align="middle" src="template/lang/all/info_s.gif" title="Info" alt="Info" /><strong> Feldbeschreibungen</strong></legend>
<table width="100%" cellspacing="0" cellpadding="6" border="0">
    <tbody>
        <tr>
            <td width="90">Betreff:</td>
            <td>Geben Sie hier den Betreff ein, der in der E-Mail an&nbsp;den Empf&auml;nger (Ziel)&nbsp;und eventuell den Absender (Kopie an) &uuml;bermittelt werden soll.</td>
        </tr>
        <tr class="tbfield">
            <td><!--StartFragment -->Ziel:<br />
            <!--StartFragment --></td>
            <td>Hier geben Sie den Empf&auml;nger der Email an.</td>
        </tr>
        <tr>
            <td>Kopie an:</td>
            <td>Soll der Absender auch eine Kopie erhalten, w&auml;hlen Sie bitte hier das Formularfeld aus, in dem die Absender-Email-Adresse steht.</td>
        </tr>
        <tr class="tbfield">
            <td>bei Erfolg:</td>
            <td>Soll der Absender bei einer erfolgreich &uuml;bermittelten Email&nbsp;eine Meldung erhalten, geben Sie bitte hier den Alias der Seite ein, die die Meldung enth&auml;lt.</td>
        </tr>
        <tr>
            <td>bei Fehler:</td>
            <td>Soll der Absender bei einer fehlerhaft &uuml;bermittelten Email&nbsp;eine Meldung erhalten, geben Sie&nbsp;bitte hier den Alias der Seite ein, die die Meldung enth&auml;lt.</td>
        </tr>
        <tr class="tbfield">
            <td>Formular:</td>
            <td>In den folgenden Feldern k&ouml;nnen Sie das Aussehen des Email-Kontaktformulars definieren.</td>
        </tr>
        <tr>
            <td>Anordnung:</td>
            <td>Hier k&ouml;nnen Sie die Anordnung von Label und Feld definieren. Folgende M&ouml;glichkeiten stehen&nbsp;zur Auswahl: 	                        1.&nbsp;Label links vom Eingabefeld<br />
            2. Label oberhalb des Eingabefeldes&nbsp;</td>
        </tr>
        <tr class="tbfield">
            <td>Formular class:</td>
            <td>Soll das Formular mit einer speziellen CSS-Klasse angezeigt werden, f&uuml;gen Sie den Namen der Klasse bitte hier ein.</td>
        </tr>
        <tr>
            <td>Label wrap:</td>
            <td>Soll das Label speziell gewrappt werden, geben Sie bitte die Daten hier ein. Das Zeichen &quot;|&quot; dient als Labeltextplatzhalter.<br />
            Bsp.: |&amp;nbsp;&amp;nbsp;<br />
            (F&uuml;gt einen Abstand von zwei Zeerzeichen zwischen dem l&auml;ngsten Label und dem Eingabefeld ein, bei horizontaler Ausrichtung).</td>
        </tr>
        <tr class="tbfield">
            <td>Pflichtzeichen:&nbsp;</td>
            <td>Pflichtfelder k&ouml;nnen besonders gekennzeichnet werden. Die Standardkennzeichnung ist *.</td>
        </tr>
        <tr>
            <td>Fehler class:</td>
            <td>Soll die Fehlermeldung&nbsp;mit einer speziellen CSS-Klasse angezeigt werden, f&uuml;gen Sie den Namen der Klasse bitte hier ein.</td>
        </tr>
        <tr class="tbfield">
            <td valign="top">Typ:</td>
            <td>
            <p>Es k&ouml;nnen unterschiedliche Feldtypen in das E-Mail Kontaktformular eingepflegt werden. Die Bef&uuml;llung der Feldtypen erfolgt &uuml;ber das Eingabefeld &quot;Wert&quot;.</p>
            <p><b>Folgende Feldtypen sind m&ouml;glich:</b>&nbsp;</p>
            <p><strong>Text (einzeilig)</strong>                         <br />
            Ein einzeiliges Textfeld wird eingeblendet.                         &nbsp;</p>
            <p><strong>Text ( mehrzeilig)</strong>                         <br />
            Eine Textarea wird eingeblendet.                         &nbsp;</p>
            <p><strong>Text (spezial)</strong>                         <br />
            Ein einzeiliges Textfeld mit z.B. einer Formel oder einer Variablendefinition wird eingeblendet.                         &nbsp;</p>
            <p><strong>Versteckt</strong>                         <br />
            Verwendung eines versteckten Feldes.                         &nbsp;</p>
            <p><strong>Passwort</strong>                         <br />
            Anzeige eines Passwortfeldes, in dem die Passworteingabe verschl&uuml;sselt anzeigt wird.                         &nbsp;</p>
            <p><strong>Email</strong>                         <br />
            Anzeige eines Email-Eingabefeldes.                         &nbsp;</p>
            <p><strong>Ausklappmen&uuml;</strong>                         <br />
            Anzeige eines DropDown-Men&uuml;s.                         &nbsp;</p>
            <p><strong>Liste</strong>                         Anzeige einer Auswahlliste.                         &nbsp;&nbsp;</p>
            <p><strong> Kontrollk&auml;stchen</strong>                         <br />
            Anzeige von einer oder mehreren Checkboxen. Wenn Sie einen Wert vorbelegen m&ouml;chten, schreiben Sie bitte direkt hinter den betreffenden Wert ein Leerzeichen sowie das Wort &quot;checked&quot;, d.h. &quot; checked&quot;.                         &nbsp;</p>
            <p><strong>Optionsschalter</strong>                         <br />
            Anzeige eines oder mehrerer Radiobuttons. Wenn Sie einen Wert vorbelegen m&ouml;chten, schreiben Sie bitte direkt hinter den betreffenden Wert ein Leerzeichen sowie das Wort &quot;checked&quot;, d.h. &quot; checked&quot; .                         &nbsp;</p>
            <p><strong>Datei</strong>                         <br />
            Hier besteht die M&ouml;glichkeit, den Benutzer eine Datei aus seinem Dateisystem ausw&auml;hlen zu lassen. Es erscheint ein Feld f&uuml;r den Dateinamen sowie ein Durchsuchen-Schaltknopf.&nbsp;</p>
            <p><strong>Senden-Taste</strong>                         <br />
            Anzeige eines Senden-Schaltknopf. Die Beschriftung des Schaltknopfes kann beliebig eingegeben werden.                         &nbsp;</p>
            <p><strong>Zur&uuml;cksetzen</strong>                                                  <br />
            Anzeige eines Reset-Schaltknopf. Die Beschriftung des Schaltknopfes kann beliebig eingegeben werden.                                                  &nbsp;</p>
            <p><strong>Trenner</strong>                         <br />
            Anzeige von Bereichstrennern. Eingabe beliebig.&nbsp;</p>
            <p><strong> Zwischentext</strong>                         <br />
            Eingabe eines Zwischentextes.</p>
            </td>
        </tr>
        <tr>
            <td>Name:</td>
            <td>Tragen Sie hier einen eindeutigen Feldnamen ein.</td>
        </tr>
        <tr class="tbfield">
            <td>Label:</td>
            <td>Hier m&uuml;ssen Sie den Labelnamen eingeben, der dem Benutzer links neben dem&nbsp;Eingabefeld oder oberhalb des&nbsp;Eingabefeldes angezeigt wird (s.a. Feld &quot;Anordnung&quot;).</td>
        </tr>
        <tr>
            <td>S/C:</td>
            <td>In diesem Feld k&ouml;nnen Sie f&uuml;r 	                        - einzeilige Textfelder die Gr&ouml;&szlig;e und f&uuml;r 	                        - mehrzeilige Textfelder die Zeilenanzahl 	                        eingeben.</td>
        </tr>
        <tr class="tbfield">
            <td>M/R:</td>
            <td>In diesem Feld k&ouml;nnen Sie f&uuml;r 	                        - einzeilige Textfelder die maximale L&auml;nge und f&uuml;r 	                        - mehrzeilige Textfelder und Listen die Spaltenanzahl 	                        eingeben. 	                        Bei Listen bewirkt eine Eingabe des Wertes &quot;1&quot; in dieses Feld, dass Sie mehrere Listeneintr&auml;ge auf einmal ausw&auml;hlen k&ouml;nnen (Mehrfachselektion). Die Mehrfachselektion k&ouml;nnen Sie mit der STRG-Taste durchf&uuml;hren.</td>
        </tr>
        <tr>
            <td>! (Ausrufezeichen):</td>
            <td>Dieses Feld kennzeichnet den linksstehenden Feldtypen als zwingend erforderlich.</td>
        </tr>
        <tr class="tbfield">
            <td>Papierkorb:</td>
            <td>Mit dem Papierkorb k&ouml;nnen Sie den linksstehenden Feldtypen l&ouml;schen.</td>
        </tr>
        <tr>
            <td valign="top">Wert:</td>
            <td valign="top">
            <p>Hier k&ouml;nnen Sie Werte f&uuml;r die Feldtypen eingegeben:</p>
            <p><strong>Text (einzeilig)</strong>                         <br />
            &quot;Das ist ein einzeiliger Text&quot;&nbsp;</p>
            <p><strong>Text ( mehrzeilig)</strong>                         <br />
            &quot;Das ist ein mehrzeiliger Text&quot;                         &quot;Das ist ein mehrzeiliger Text&quot;&nbsp;</p>
            <p><strong>Text (spezial)</strong>                         <br />
            type=INT - nur Ganzzahlwerte zul&auml;ssig<br />
            type=DEC oder FLOAT - nur Dezimal bzw. Float zul&auml;ssig<br />
            type=IDENT - Vergleichspr&uuml;fung, nur wenn Eingabe identisch mit dem default Wert<br />
            type=STRING oder MIX<br />
            type=DATE - pr&uuml;ft ob g&uuml;ltiges Datum<br />
            type= A-Z (nur Gro&szlig;buchstaben)<br />
            type=a-z (nur Kleinbuchstaben)<br />
            type=a-Z (nur Buchstaben)<br />
            type=0-9 (nur Ziffern)<br />
            type=PHONE (Telefonnummer)<br />
            type=WORD (Wortbuchstaben)<br />
            type=LETTER+SPACE (a-Z, space, hyphens)<br />
            type=REGEX (patterns - new value: pattern<br />
            =&quot;/...regex-pattern.../&quot;)<br />
            </p>
            <p>default=&quot;100&quot;<br />
            dateformat=&quot;m/d/Y&quot;                         &nbsp;                         <strong>- </strong><strong><br />
            <br />
            </strong></p>
            <p><strong>Versteckt</strong>                         Eine Eingabe in diesem Feld wird nicht angezeigt.</p>
            <p><strong>Passwort</strong>                         Keine Eingabe erforderlich.&nbsp;</p>
            <p><strong>Email</strong>                         <br />
            Keine Eingabe erforderlich.&nbsp;                         &nbsp;                         &nbsp;</p>
            <p><strong>Ausklappmen&uuml;</strong>                         <br />
            &quot;Apfel&quot;<br />
            &quot;Birne&quot;<br />
            &quot;Melone&quot;                         &nbsp;</p>
            <p><strong>Liste</strong><br />
            &quot;Apfel&quot;<br />
            &quot;Birne&quot;<br />
            &quot;Melone&quot;                         &nbsp;</p>
            <p><strong>Kontrollk&auml;stchen</strong>                         <br />
            &quot;Apfel&quot;<br />
            &quot;Birne&quot;<br />
            &quot;Melone&quot;                         &nbsp;</p>
            <p><strong>Optionsschalter</strong>                         <br />
            &quot;Apfel&quot;<br />
            &quot;Birne&quot;<br />
            &quot;Melone&quot;                         &nbsp;                         &nbsp;</p>
            <p><strong>Datei</strong>                         <strong>max. Dateigr&ouml;&szlig;e:</strong> <br />
            maxlength=&quot;10000000&quot;</p>
            <p><strong>als Dateianhang:</strong> <br />
            attachment=&quot;1&quot;</p>
            <p><strong>welcher Anhang:</strong> <br />
            accept=&quot;text/*&quot;</p>
            <p><strong>aus welchem Ordner:</strong> <br />
            folder=&quot;content/form&quot;</p>
            <p><strong>Dateien ausschliessen:</strong>                         exclude=&quot;php,asp,php3,php4,php5,aspx,cfm,js&quot;                         &nbsp;</p>
            <p><strong>Senden-Taste</strong>                         <br />
            &quot;Anfrage absenden!&quot;                         &nbsp;</p>
            <p><strong>Zur&uuml;cksetzen</strong>                         <br />
            &quot;Eingabefelder zur&uuml;cksetzen!&quot;</p>
            <p><strong>Trenner</strong>                         <br />
            &quot;******************************************************&quot;</p>
            <p><strong>Zwischentext</strong>                         <br />
            &quot;Das ist ein Zwischentext&quot;</p>
            </td>
        </tr>
        <tr class="tbfield">
            <td>Fehlertext:</td>
            <td>Geben Sie hier einen Fehlertext ein, wenn der Benutzer ein Feld nicht ausgef&uuml;llt hat. 	                        Bsp: &quot;Fehler: Folgendes Feld wurde nicht ausgef&uuml;llt:&quot;</td>
        </tr>
        <tr>
            <td>CSS-Stil:</td>
            <td>Auch f&uuml;r diese Fehlermeldung k&ouml;nnen Sie eine individuelles CSS-Klasse verwenden.</td>
        </tr>
        <tr class="tbfield">
            <td>Vorlage:</td>
            <td>Hier&nbsp;mu&szlig; ein Template eingegeben werden, sonst erhalten Sie eine&nbsp;leere Email zugesendet. Dieses Template kann als Text-Template oder als HTML-Template erstellt werden. In den Templates k&ouml;nnen Sie alle Namensfelder des Formulars verwenden.</td>
        </tr>
    </tbody>
</table>
</fieldset>
		 
		
		<br /><br />
		<div class="sub">
		Artikel erstellt am: Dienstag, 12. April 2005 <br /> Letzte &Auml;nderung: Dienstag, 04. Januar 2011	
		</div>
				
	</div>
	
<div id="footer"><br /><br />
<p style="height:30px;">&nbsp;</p>


 <script type="text/javascript" language="javascript">
<!--

var showDefaultValue =  0

function hideLayer(whichLayer) {
	if (document.getElementById) {
		// this is the way the standards work
		document.getElementById(whichLayer).style.display = "none";
	} else if (document.all) {
		// this is the way old msie versions work
		document.all[whichlayer].style.display = "none";
	} else if (document.layers) {
		// this is the way nn4 works
		document.layers[whichLayer].display = "none";
	}
}

function showLayer(whichLayer) {
		//	alert(whichLayer);
	if (document.getElementById) {
		// this is the way the standards work
		document.getElementById(whichLayer).style.display = "block";
	}
	else if (document.all) {
		// this is the way old msie versions work
		document.all[whichlayer].style.display = "block";
	}
	else if (document.layers) {
		// this is the way nn4 works
		document.layers[whichLayer].display = "block";
	}
}

function toggleLayer(whichLayer) {
	if(showDefaultValue == 0) {
		hideLayer(whichLayer);
		showDefaultValue = 1;
	} else {
		showLayer(whichLayer);
		showDefaultValue = 0;
	}
}
//-->
</script>


<div id="alles">
<div id="klapper" onclick="toggleLayer('formular');">
<table width="570" border="0" cellspacing="0" cellpadding="0">
<tr>
<td><em style="color:#275EA8;" onmouseover="this.style.color='#4F96F4';" onmouseout="this.style.color='#275EA8';">Sie haben Anregungen oder Kritik zu diesem Artikel? Schreiben Sie uns!</em></td>   
<td align="right" style="padding-right:2px;"><img src="template/lang/all/icons/write.gif" width="16" height="21" alt="" border="0" /></td>
</tr>
</table>

</div>
<div id="formular">

<form name="form" method="post" action="index.php?id=379,283,0,1,1,0" style="margin:0;padding:0;"><input type="hidden" name="customForm" value="1" /><input type="hidden" name="docucheck" value="1" />


<div style="float:left;">
<p><select name="Betreff" id="Betreff" class="size1">
<option value="" class="deepblue"> Bitte ausw&auml;hlen </option>
<option value="subject_1" class="inselect">Anregungen</option>
<option value="subject_2" class="inselect">Fehlermeldung/ Kritik</option>
<option value="subject_3" class="inselect">Sonstiges</option>

</select><br /></p>


<p>Vorname:<br />
<input type="text" name="Vorname" value="" class="size1" /></p>
<p>Name:*<br />
<input type="text" name="Name" value="" class="size1" /></p>
<p>E-Mail:*<br />
<input type="text" name="E-Mail" value="" class="size1" /></p>
</div>


<div style="float:right;">Mitteilung:*<br />
<textarea name="Nachricht" cols="40" rows="4"  class="size7"></textarea>
</div>

<p style="clear:both; text-align:right;"><input type="reset" name="reset" value="Zur&uuml;cksetzen" class="btstyle" style="width:100px;" />&nbsp;&nbsp;
<input type="submit" name="submit" value="Anfrage senden" class="btstyle" style="width:110px;" /></p>
<p style="margin:20px;" class="sub">* Pflichtangaben. Ihre Daten werden ausschlie&szlig;lich für diese Anfrage verwendet.</p>

</form>
</div>
</div>
 <script type="text/javascript" language="javascript">
<!--
	// Lösung ohne Onload
	toggleLayer('formular');
//-->
</script>
<br />





	<table width="97%" border="0" cellspacing="0" cellpadding="0">
		<tr>
			<td valign="bottom">	
			&copy; phpwcms-docu 2004-2015
			<img src="img/leer.gif" border="0" width="10" height="0" alt="" /><a href="impressum.phtml" class="phpwcmsIntLink"><img src="template/lang/all/icons/imprint.gif" width="9" height="15" alt="Impressum" title="Impressum" border="0" /></a>&nbsp; 
			<a href="sitemap_de.phtml" class="phpwcmsIntLink"><img src="template/lang/all/icons/sitemap.gif" width="19" height="15" alt="Sitemap" title="Sitemap" border="0" /></a>&nbsp; 
			<a href="gaestebuch.phtml" class="phpwcmsIntLink"><img src="template/lang/all/icons/gbook.gif" width="20" height="16" alt="Ins G&auml;stebuch eintragen" title="Ins G&auml;stebuch eintragen" border="0" /></a>&nbsp; 
			<a href="#" onclick="BookMark_Page();return false;" title="" class="phpwcmsBookmarkLink"><img src="template/lang/all/icons/favo.gif" width="12" height="15" alt="Seite als Bookmark speichern" title="Seite als Bookmark speichern" border="0" /></a>&nbsp; 
			     
			</td>
			<td valign="bottom" style="padding-right:25px;">
			
			
			
			</td>		
			<td width="150">
			</td>
		</tr>
	</table>
</div><br/>

</div>
</body>
</html>