<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<!--
	phpwcms | free open source content management system
	created by Oliver Georgi (oliver at phpwcms dot de) and licensed under GNU/GPL.
	phpwcms is copyright 2003-2007 of Oliver Georgi. Extensions are copyright of
	their respective owners. Visit project page for details: http://www.phpwcms.org/
//-->
<title>phpwcms-docu for  phpwcms :: web based content management system | Multimedia{D:7/30/2007,30,newR.gif} | Content Part &quot;Multimedia&quot;</title>
  <meta http-equiv="content-type" content="text/html; charset=iso-8859-1" />
  <meta http-equiv="content-style-type" content="text/css" />
  <script src="template/inc_js/frontend.js" type="text/javascript"></script>
  <style type="text/css">
  <!-- 
    @import url("template/inc_css/mpl_frontend.css");
    @import url("template/inc_css/mpl_menu.css");
    @import url("template/inc_css/mpl_objects.css");
    @import url("template/inc_css/mpl_docu_en.css");
  //-->
  </style>
<meta name="Title" content="The phpWCMS Documentation" />
<meta name="author" content="Oliver Frohnert, Mario Perez Leal" />
<meta name="Publisher" content="Oliver Frohnert, Mario Perez Leal, creacion" />
<meta name="Copyright" content="Oliver Frohnert, Mario Perez Leal, creacion" />
<meta name="keywords" content="frohnert, perez leal, creacion, documentation, dokumentation, phpwcms, cms, opensource, open source, docu" />
<meta name="description" content="A Documentation Project for the  Open Source CMS phpWCMS" />
<meta name="Audience" content="Alle" />
<meta name="Content-language" content="EN" />
<meta name="robots"      content="index,follow" />
<meta name="expires" content="0" />
<meta name="revisit-after" content="7 days" />
<meta name="resource-type" content="document" />
<meta name="distribution" content="Global" />
<meta name="generator" content="PHPWCMS" />

  <link rel="stylesheet" href="template/slimbox/css/slimbox.css" type="text/css" media="screen" />
  <script src="template/inc_js/mootools/mootools.js" type="text/javascript"></script>
  <script src="template/slimbox/js/slimbox.js" type="text/javascript"></script>
  <script src="template/inc_js/AC_RunActiveContent.js" type="text/javascript"></script>
  <!--[if lt IE 7]>
  <style type="text/css">
    body { behavior: url("template/inc_css/specific/csshover2.htc"); }
    img { behavior: url("template/inc_css/specific/pngbehavior.htc"); }
  </style>
  <![endif]-->
</head>
<body id="myid_162">
<div id="container"><a name="top" id="top"></a>


	<div id="head">
		
	<div id="mainnavi">
		<div class="fleft"><a href="english_version.phtml">Home</a> | <a href="news_en.phtml">News</a> | <span style="text-decoration:none;font-weight:bold;"><a href="the_docu.phtml">The Docu</a></span> | <a href="Usefull_Links_and_Tools.phtml">Links &amp; Tools</a> | <a href="contact.phtml">Contact</a> | <a href="faq_en.phtml">FAQ</a> | <a href="http://forum.phpwcms.org/" target="_blank">Forum</a> | <a href="howto_en.phtml">HowTo</a></div>				
		<div class="sys">Saturday, 27. July 2013<img src="img/leer.gif" border="0" width="5" height="1" alt="" />|<img src="img/leer.gif" border="0" width="5" height="1" alt="" />4 User online<img src="img/leer.gif" border="0" width="10" height="1" alt="" />
		<a href="deutsche_version.phtml" title="Deutsche Version"><img src="picture/../template/lang/all/flag_de.gif" border="0" alt="" /></a>
		<a href="english_version.phtml"  title="English version"><img src="picture/../template/lang/all/flag_en.gif" border="0" alt="" /></a>
		</div>
	</div>
	
	<a href="./" title="phpwcms-docu Startseite aufrufen" class="homelink">
	<span>&raquo; phpwcms-docu startpage</span></a>
	<h2>phpwcms-docu - Documentation for the Web Content Management System phpwcms</h2>
	<p>This website is targeted both to the beginner and the lateral entry following the goal to simplify the 
work with phpwcms and to focus on the essentials things.</p>
	</div>

	
	<div id="left">
	<div class="leftnav" style="margin-top:24px;">
	
<div id="ul_div_311">
<ul>
	<li class="sub_no"><a href="download-dev-versions.phtml">Download Dev Versions</a></li>
	<li class="sub_no sub_ul_true"><a href="installation_en.phtml">Installation &amp; Upgrade</a></li>
	<li class="sub_ul"><a href="article.phtml">Articles</a>
	<div id="ul_div_116">
	<ul>
		<li class="sub_no"><a href="creating_articles.phtml">Creating Articles</a></li>
		<li class="sub_no"><a href="editing_articles.phtml">Editing Articles </a></li>
		<li class="sub_no sub_ul_true"><a href="article_organization.phtml">Article Organization</a></li>
		<li class="sub_ul"><a href="content_parts_en.phtml">Content Parts</a>
		<div id="ul_div_124">
		<ul>
			<li class="sub_no"><a href="content_part_plain_text.phtml">Plain Text</a></li>
			<li class="sub_no"><a href="content_part_html_en.phtml">Html</a></li>
			<li class="sub_no"><a href="content_part_wysiwyg_html_en.phtml">WYSIWYG HTML</a></li>
			<li class="sub_no"><a href="content_part_code_en.phtml">Code</a></li>
			<li class="sub_no"><a href="content_part_text_with_image.phtml">Text with image</a></li>
			<li class="sub_no"><a href="content_part_images.phtml">Images</a></li>
			<li class="sub_no"><a href="content_part_images_div.phtml"><span style="text-decoration:line-through;font-size:10px;">Images &lt;DIV&gt;</span></a></li>
			<li class="sub_no"><a href="content_part_list_table.phtml">List (Table)</a></li>
			<li class="sub_no"><a href="content_part_list.phtml">List</a></li>
			<li class="sub_no"><a href="content_part_link_and_e-mail.phtml">Link &amp; E-Mail</a></li>
			<li class="sub_no"><a href="content_part_link_list.phtml">Link list</a></li>
			<li class="sub_no"><a href="content_part_link_article.phtml">Link article</a></li>
			<li class="sub_no"><a href="content_part_teaser_articlelink.phtml"><span style="text-decoration:line-through;font-size:10px;">Teaser / Articlelink</span></a></li>
			<li class="sub_no"><a href="content_part_article_menue.phtml">Article Menu</a></li>
			<li class="sub_no active"><a href="content_part_multimedia_en.phtml">Multimedia</a></li>
			<li class="sub_no"><a href="content_part_file_list.phtml">File List</a></li>
			<li class="sub_no"><a href="content_part_ecard_en.phtml">E-Card</a></li>
			<li class="sub_no"><a href="content_part_form.phtml">Form</a></li>
			<li class="sub_no"><a href="content_part_e-mail_contact_form.phtml">Email contact form</a></li>
			<li class="sub_no sub_ul_true"><a href="content_part_email_form_generator.phtml">Email form generator[OLD]</a></li>
			<li class="sub_no"><a href="content_part_email_form.phtml">Email form</a></li>
			<li class="sub_no sub_ul_true"><a href="content_part_newsletter_en.phtml">Newsletter</a></li>
			<li class="sub_no"><a href="content_part_search.phtml">Search</a></li>
			<li class="sub_no sub_ul_true"><a href="content_part_guestbook_comment.phtml">Guestbook / Comm.</a></li>
			<li class="sub_no"><a href="content_part_sitemap_en.phtml">Sitemap</a></li>
			<li class="sub_no sub_ul_true"><a href="content_part_bid.phtml">Bid</a></li>
			<li class="sub_no"><a href="content_part_external_content.phtml">Ext. content</a></li>
			<li class="sub_no"><a href="content_part_rss_feed_en.phtml">RSS Feed</a></li>
			<li class="sub_no"><a href="content_part_rollover_images.phtml"><span style="text-decoration:line-through;font-size:10px;">Rollover images</span></a></li>
			<li class="sub_no"><a href="content_part_map.phtml"><span style="text-decoration:line-through;font-size:10px;">Map</span></a></li>
			<li class="sub_no"><a href="php_variables.phtml"><span style="text-decoration:line-through;font-size:10px;">PHP variables</span></a></li>
			<li class="sub_no"><a href="content_part_contentpart_alias_en.phtml">Contentpart Alias</a></li>
			<li class="sub_no"><a href="content_part_poll_en.phtml"><span style="text-decoration:line-through;font-size:10px;">Poll</span></a></li>
			<li class="sub_no"><a href="content_part_recipe.phtml"><span style="text-decoration:line-through;font-size:10px;">Recipe</span></a></li>
			<li class="sub_no"><a href="content_part_faq_en.phtml"><span style="text-decoration:line-through;font-size:10px;">FAQ</span></a></li>
			<li class="sub_no"><a href="content_part_frontend_login_en.phtml"><span style="text-decoration:line-through;font-size:10px;">Frontend Login</span></a></li>
			<li class="sub_no"><a href="content_part_glossary.phtml"><span style="text-decoration:line-through;font-size:10px;">Plug-in: Glossary</span></a></li>
		</ul>
		</div>
		</li>
	</ul>
	</div>
	</li>
	<li class="sub_no sub_ul_true"><a href="file.phtml">File</a></li>
	<li class="sub_no sub_ul_true"><a href="module_en.phtml">Modules</a></li>
	<li class="sub_no sub_ul_true"><a href="communication.phtml">Communication </a></li>
	<li class="sub_no"><a href="chat_en.phtml">Chat</a></li>
	<li class="sub_no"><a href="profile.phtml">Profile</a></li>
	<li class="sub_no sub_ul_true"><a href="admin_en_.phtml">Admin</a></li>
	<li class="sub_no sub_ul_true"><a href="add-ons-and-templates.phtml">Add On&#039;s and Templates</a></li>
	<li class="sub_no"><a href="deutsche_version.phtml?replacement_tags_en">Replacement Tags</a></li>
	<li class="sub_no"><a href="deutsche_version.phtml?content_parts_en">Content Parts</a></li>
</ul>
</div>

		
	</div> 
	</div> 
	  
	<div id="right">
		<div style="margin-top:24px;">			
		<form action="#" method="post" name="searchFE" onsubmit="s=document.getElementById('customSearchInput');if(s.value=='Search')return false;">
			<table width="100%" border="0" cellpadding="0" cellspacing="0">
			<tr>
					<td><input type="text" name="search_input_field" size="20" maxlength="200" id="customSearchInput" class="customSearchInput" value="" onfocus="if(this.value=='Search')this.value='';" onblur="if(this.value=='')this.value='Search';"/></td>
					<td><input type="image" name="search_go" onfocus="this.blur();" title="Search" src="/template/lang/all/submit.gif" /></td>
				</tr>
			</table>
			</form>
			
			      <script type="text/javascript" language="javascript">
			  <!-- 
			        document.getElementById("customSearchInput").value="Search";
			  //-->
			      </script>
				  
<!-- <p style="margin-top:10px;">Change font size: <a href="[FontSize-]"><img src="template/lang/all/icons/reduce.gif" width="18" height="17" alt="" title="Small" border="0" /></a>
			<a href="[FontSize+]"><img src="template/lang/all/icons/extend.gif" width="18" height="17" alt="" title="Bigger" border="0" /></a>
			</p> -->
			
	<p style="margin-top:10px;">Please choose: 
	
	 </p>

<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div>

<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div>
<!-- <a href="http://validator.w3.org/check?uri=http%3A%2F%2Fwww.phpwcms-docu.de%2Findex.php%3Fdeutsche_version" title="W3C Standard XHTML" target="_blank"><img src="picture/w3c/w3c_xhtml.gif" border="0" alt="" /></a>
<a href="http://jigsaw.w3.org/css-validator/validator?uri=http://www.phpwcms-docu.de" title="W3C Standard CSS" target="_blank"><img src="picture/w3c/w3c_css.gif" border="0" alt="" /></a><br />			
<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div> -->
		
<div style="margin-top:10px; margin-bottom:15px;"></div>
	
</div>

	</div> 
	
	<div id="content">
	<div id="bread">You are here: <a href="english_version.phtml">English</a> <span class="breadcrumb_spacer">&gt;</span> <a href="the_docu.phtml">The Docu</a> <span class="breadcrumb_spacer">&gt;</span> <a href="article.phtml">Articles</a> <span class="breadcrumb_spacer">&gt;</span> <a href="content_parts_en.phtml">Content Parts</a> <span class="breadcrumb_spacer">&gt;</span> Multimedia</div>
		
		<a name="jump349"></a><!-- Livedate: 25.08.2004 17:04:28 / Killdate: 31.12.2030 23:59:59 -->
<h1>Content Part &quot;Multimedia&quot;</h1>

<div style="margin:25px 0 0 0;padding:0;" class="spaceBeforeCP"></div><table width="100%" cellpadding="0" cellspacing="0" border="0" class="imgTextRight">
<tr>
<td valign="top" width="10%" class="image_td2"><table width="150" border="0" cellspacing="0" cellpadding="0" >
<tr><td class="image_td2"><a href="content/images/606d8dee31b08928ceba65db8c4f4fcb.png" rel="lightbox" title="content part &quot;multimedia&quot;" target="_blank"><img src="content/images/d43c6f1a38a38238007270d11617c882.png" width="150" height="122" border="0" class="image_img" alt="multimedia.png" /></a></td></tr>
<tr><td align="center" class="image_caption">content part &quot;multimedia&quot;</td></tr>
</table></td>
<td valign="top" class="articleText"><p><strong>media type:</strong> Here you indicate the type of media file. <br />
<br />
<strong>player/plugin:</strong> Here you can indicate which player should be used to display this file. <br />
<br />
<strong>show control bar:</strong> Here you can select whether the controls are to be displayed, e.g. for Play/Pause. <br />
<br />
<strong>autoplay:</strong> Here you can select whether the file will play automatically. <br />
<strong><br />
flash transparent: </strong>Can only be used for the start or end of flash films. When the image stands the background will be shown in a transparent way.<strong><br />
<br />
source:</strong> Here you can select between an internal or external source for the multimedia <br />
file. Select an internal source using the phpWCMS Media browser by clicking on the <img src="picture/../img/button/open_image_button.gif" border="0" alt="" /> symbol. You specify an external source by providing the web address, for example &quot;http://www.mydomain.com/myfilm.mpg&quot;.&nbsp;To delete the Source click on ths symbol <img src="picture/../img/button/del_image_button.gif" border="0" alt="" />.<br />
<br />
<strong>position:</strong> Here you can determine the position on the page. You can select between the following options:<br />
<br />
<img src="picture/../img/button/image_pos0.gif" border="0" alt="" /> Media contents positioned above the paragraph, aligned left. <br />
<img src="picture/../img/button/image_pos1.gif" border="0" alt="" /> Media contents centered over the paragraph. <br />
<img src="picture/../img/button/image_pos2.gif" border="0" alt="" /> Media contents positioned above the paragraph, aligned right. <br />
<img src="picture/../img/button/image_pos6.gif" border="0" alt="" /> Media contents positioned within the paragraph, aligned left.<br />
<img src="picture/../img/button/image_pos7.gif" border="0" alt="" /> Media contents positioned within the paragraph, aligned right.&nbsp;<br />
<br />
<font color="#ff0000">For what a positioning or alignment of text if I can't insert text into this content part? For this reason we made an example for you at the end of this page.</font><br />
<br />
<strong>width/height (optional):</strong> Here you can specify a size. You can also quickly select from several standard formats, by clicking on the appropriate button:&nbsp;<br />
<br />
<img src="picture/../img/button/video_160x120.gif" border="0" alt="" /> for 160 pixels width and 120 pixels height <br />
<img src="picture/../img/button/video_240x180.gif" border="0" alt="" /> for 240 pixels width and 240 pixels height <br />
<img src="picture/../img/button/video_320x240.gif" border="0" alt="" /> for 320 pixels width and 240 pixels height <br />
<img src="picture/../img/button/video_480x360.gif" border="0" alt="" /> for 480 pixels width and 360 pixels height&nbsp;<br />
<br />
<img src="picture/../img/button/del_image_button.gif" border="0" alt="" /> to clear media width and height entries.</p></td>
</tr>
</table><div align="right"><a href="#top"><img src="img/article/top_link_0.gif" border="0" alt="" /></a></div><div style="margin:15px 0 0 0;padding:0;" class="spaceBeforeCP"></div><hr width="100%" size="2" />
<p>&nbsp;</p><div style="margin:0 0 15px 0;padding:0;" class="spaceAfterCP"></div><a name="cpid1577" id="cpid1577" class="cpidClass"></a><h3>Why an Alignment in the Text when I can&#039;t insert Text?</h3><p>Surely you saw that there is a text alignment in this content part, although you can't insert a text into the content part.<br />
<br />
First create a content part &quot;Multimedia&quot;, then&nbsp; a CP &quot;WYSIWYG HTML&quot; or &quot;Plain Text&quot;. The CP with the text goes automatically to the position that you selected.<br />
<br />
Here is an example:<br />
First the CP &quot;Multimedia&quot; has been created with the following alignment <img alt="" src="./img/button/image_pos6.gif" />. Then comes a CP &quot;WYSIWYG HTML&quot;. Please have a look at the result.</p><div style="margin:15px 0 0 0;padding:0;" class="spaceBeforeCP"></div><table border="0" cellspacing="0" cellpadding="0" align="left">
<tr><td colspan="2"><img src="img/leer.gif" width="1" height="3" border="0" alt="" /></td></tr>
<tr><td>
<noscript><object id="mediaID1578" name="mediaID1578" width="240" height="180" data="phpwcms_filestorage/a2b1b345bfa23a65818e067c0ed2b876.swf" type="application/x-shockwave-flash">
	<param name="movie" value="phpwcms_filestorage/a2b1b345bfa23a65818e067c0ed2b876.swf" />
	<param name="quality" value="high" />
	<param name="scale" value="noborder" />
	<param name="loop" value="false" />
	<param name="play" value="false" />
</object></noscript>
<script type="text/javascript" language="javascript">
  <!-- 
  AC_FL_RunContent('codebase','http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,29,0','id','mediaID1578','width','240','height','180','src','phpwcms_filestorage/a2b1b345bfa23a65818e067c0ed2b876','quality','high','scale','noborder','pluginspage','http://www.macromedia.com/shockwave/download/index.cgi?P1_Prod_Version=ShockwaveFlash','movie','phpwcms_filestorage/a2b1b345bfa23a65818e067c0ed2b876' );
  //-->
</script></td><td><img src="img/leer.gif" width="5" height="1" border="0" alt="" /></td></tr>
<tr><td colspan="2"><img src="img/leer.gif" width="1" height="3" border="0" alt="" /></td></tr>
</table>
<h3>A great Video with Blindtext</h3><p>Redior, sui cautor Concito, far, Comitatus mus Ambiguus palma via Degenero pio ala Imputo. Pudeo teneo triticeus, iam conjuratio, regno re oro Aveho curiositas cicuta, dis Occulte, deprecativus typus caterva pauci, his re supermitto. Ruo in divortium ita sesquimellesimus Oppono plus celo sceptrum, res ingustatus hi Ango prae tum quatenus/quatinus Sumptus per Avoco nos Indulgens mei heu cur Baiulus attonitus. Via subterfugio radio hac castra, tui Seorsum tam Byssus ex infirmitas. Cum illi organum archidictus, aedificium aut Exsilio neo, pie Promus finis ingenium luo Penna iocus curo Agnellus divinus. Ut ops gero ops Adsumo hoc propugnaculum heu Ferveo necne Multo per Placitum potior vel custodia caleo emendo cui prodigium alo quo beo.</p>
		 
		
		<br /><br />
		<div class="sub">
		Article created: Wednesday, 25. July 2007 <br /> Last Changes: Tuesday, 4. January 2011	
		</div>
				
	</div>
	
<div id="footer">





	<table width="97%" border="0" cellspacing="0" cellpadding="0">
		<tr>
			<td valign="bottom">	
			&copy; phpwcms-docu 2004-2013
			<img src="img/leer.gif" border="0" width="10" height="0" alt="" /><a href="imprint.phtml" class="phpwcmsIntLink"><img src="template/lang/all/icons/imprint.gif" width="9" height="15" alt="Impressum" title="Impressum" border="0" /></a>&nbsp; 
			<a href="sitemap_en.phtml" class="phpwcmsIntLink"><img src="template/lang/all/icons/sitemap.gif" width="19" height="15" alt="Sitemap" title="Sitemap" border="0" /></a>&nbsp; 
			 
			
			     
			</td>
			<td valign="bottom" style="padding-right:25px;">
			
			
			
			</td>		
			<td width="150">
			</td>
		</tr>
	</table>
</div><br/>

</div>
</body>
</html>