<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<!--
	phpwcms | free open source content management system
	created by Oliver Georgi (oliver at phpwcms dot de) and licensed under GNU/GPL.
	phpwcms is copyright 2003-2007 of Oliver Georgi. Extensions are copyright of
	their respective owners. Visit project page for details: http://www.phpwcms.org/
//-->
<title>phpwcms-docu for  phpwcms :: web based content management system | Form | Content Part &quot;Form&quot;{D:9/30/2005,30,editR.gif}</title>
  <meta http-equiv="content-type" content="text/html; charset=iso-8859-1" />
  <meta http-equiv="content-style-type" content="text/css" />
  <script src="template/inc_js/frontend.js" type="text/javascript"></script>
  <style type="text/css">
  <!-- 
    @import url("template/inc_css/mpl_frontend.css");
    @import url("template/inc_css/mpl_menu.css");
    @import url("template/inc_css/mpl_objects.css");
    @import url("template/inc_css/mpl_docu_en.css");
  //-->
  </style>
<meta name="Title" content="The phpWCMS Documentation" />
<meta name="author" content="Oliver Frohnert, Mario Perez Leal" />
<meta name="Publisher" content="Oliver Frohnert, Mario Perez Leal, creacion" />
<meta name="Copyright" content="Oliver Frohnert, Mario Perez Leal, creacion" />
<meta name="keywords" content="frohnert, perez leal, creacion, documentation, dokumentation, phpwcms, cms, opensource, open source, docu" />
<meta name="description" content="A Documentation Project for the  Open Source CMS phpWCMS" />
<meta name="Audience" content="Alle" />
<meta name="Content-language" content="EN" />
<meta name="robots"      content="index,follow" />
<meta name="expires" content="0" />
<meta name="revisit-after" content="7 days" />
<meta name="resource-type" content="document" />
<meta name="distribution" content="Global" />
<meta name="generator" content="PHPWCMS" />
<meta name="verify-v1" content="1ZpxZ7AZsjm7PxjqXQVus0eiUYqOsp5URTJn9q4KNz8=" />
  <link rel="stylesheet" href="template/slimbox/css/slimbox.css" type="text/css" media="screen" />
  <script src="template/inc_js/mootools/mootools.js" type="text/javascript"></script>
  <script src="template/slimbox/js/slimbox.js" type="text/javascript"></script>
  <!--[if lt IE 7]>
  <style type="text/css">
    body { behavior: url("template/inc_css/specific/csshover2.htc"); }
    img { behavior: url("template/inc_css/specific/pngbehavior.htc"); }
  </style>
  <![endif]-->
</head>
<body id="myid_377">
<div id="container"><a name="top" id="top"></a>


	<div id="head">
		
	<div id="mainnavi">
		<div class="fleft"><a href="english_version.phtml">Home</a> | <a href="news_en.phtml">News</a> | <span style="text-decoration:none;font-weight:bold;"><a href="the_docu.phtml">The Docu</a></span> | <a href="Usefull_Links_and_Tools.phtml">Links &amp; Tools</a> | <a href="contact.phtml">Contact</a> | <a href="faq_en.phtml">FAQ</a> | <a href="http://forum.phpwcms.org/" target="_blank">Forum</a> | <a href="howto_en.phtml">HowTo</a></div>				
		<div class="sys">Saturday, 27. July 2013<img src="img/leer.gif" border="0" width="5" height="1" alt="" />|<img src="img/leer.gif" border="0" width="5" height="1" alt="" />6 User online<img src="img/leer.gif" border="0" width="10" height="1" alt="" />
		<a href="deutsche_version.phtml" title="Deutsche Version"><img src="picture/../template/lang/all/flag_de.gif" border="0" alt="" /></a>
		<a href="english_version.phtml"  title="English version"><img src="picture/../template/lang/all/flag_en.gif" border="0" alt="" /></a>
		</div>
	</div>
	
	<a href="./" title="phpwcms-docu Startseite aufrufen" class="homelink">
	<span>&raquo; phpwcms-docu startpage</span></a>
	<h2>phpwcms-docu - Documentation for the Web Content Management System phpwcms</h2>
	<p>This website is targeted both to the beginner and the lateral entry following the goal to simplify the 
work with phpwcms and to focus on the essentials things.</p>
	</div>

	
	<div id="left">
	<div class="leftnav" style="margin-top:24px;">
	
<div id="ul_div_311">
<ul>
	<li class="sub_no"><a href="download-dev-versions.phtml">Download Dev Versions</a></li>
	<li class="sub_no sub_ul_true"><a href="installation_en.phtml">Installation &amp; Upgrade</a></li>
	<li class="sub_ul"><a href="article.phtml">Articles</a>
	<div id="ul_div_116">
	<ul>
		<li class="sub_no"><a href="creating_articles.phtml">Creating Articles</a></li>
		<li class="sub_no"><a href="editing_articles.phtml">Editing Articles </a></li>
		<li class="sub_no sub_ul_true"><a href="article_organization.phtml">Article Organization</a></li>
		<li class="sub_ul"><a href="content_parts_en.phtml">Content Parts</a>
		<div id="ul_div_124">
		<ul>
			<li class="sub_no"><a href="content_part_plain_text.phtml">Plain Text</a></li>
			<li class="sub_no"><a href="content_part_html_en.phtml">Html</a></li>
			<li class="sub_no"><a href="content_part_wysiwyg_html_en.phtml">WYSIWYG HTML</a></li>
			<li class="sub_no"><a href="content_part_code_en.phtml">Code</a></li>
			<li class="sub_no"><a href="content_part_text_with_image.phtml">Text with image</a></li>
			<li class="sub_no"><a href="content_part_images.phtml">Images</a></li>
			<li class="sub_no"><a href="content_part_images_div.phtml"><span style="text-decoration:line-through;font-size:10px;">Images &lt;DIV&gt;</span></a></li>
			<li class="sub_no"><a href="content_part_list_table.phtml">List (Table)</a></li>
			<li class="sub_no"><a href="content_part_list.phtml">List</a></li>
			<li class="sub_no"><a href="content_part_link_and_e-mail.phtml">Link &amp; E-Mail</a></li>
			<li class="sub_no"><a href="content_part_link_list.phtml">Link list</a></li>
			<li class="sub_no"><a href="content_part_link_article.phtml">Link article</a></li>
			<li class="sub_no"><a href="content_part_teaser_articlelink.phtml"><span style="text-decoration:line-through;font-size:10px;">Teaser / Articlelink</span></a></li>
			<li class="sub_no"><a href="content_part_article_menue.phtml">Article Menu</a></li>
			<li class="sub_no"><a href="content_part_multimedia_en.phtml">Multimedia</a></li>
			<li class="sub_no"><a href="content_part_file_list.phtml">File List</a></li>
			<li class="sub_no"><a href="content_part_ecard_en.phtml">E-Card</a></li>
			<li class="sub_no active"><a href="content_part_form.phtml">Form</a></li>
			<li class="sub_no"><a href="content_part_e-mail_contact_form.phtml">Email contact form</a></li>
			<li class="sub_no sub_ul_true"><a href="content_part_email_form_generator.phtml">Email form generator[OLD]</a></li>
			<li class="sub_no"><a href="content_part_email_form.phtml">Email form</a></li>
			<li class="sub_no sub_ul_true"><a href="content_part_newsletter_en.phtml">Newsletter</a></li>
			<li class="sub_no"><a href="content_part_search.phtml">Search</a></li>
			<li class="sub_no sub_ul_true"><a href="content_part_guestbook_comment.phtml">Guestbook / Comm.</a></li>
			<li class="sub_no"><a href="content_part_sitemap_en.phtml">Sitemap</a></li>
			<li class="sub_no sub_ul_true"><a href="content_part_bid.phtml">Bid</a></li>
			<li class="sub_no"><a href="content_part_external_content.phtml">Ext. content</a></li>
			<li class="sub_no"><a href="content_part_rss_feed_en.phtml">RSS Feed</a></li>
			<li class="sub_no"><a href="content_part_rollover_images.phtml"><span style="text-decoration:line-through;font-size:10px;">Rollover images</span></a></li>
			<li class="sub_no"><a href="content_part_map.phtml"><span style="text-decoration:line-through;font-size:10px;">Map</span></a></li>
			<li class="sub_no"><a href="php_variables.phtml"><span style="text-decoration:line-through;font-size:10px;">PHP variables</span></a></li>
			<li class="sub_no"><a href="content_part_contentpart_alias_en.phtml">Contentpart Alias</a></li>
			<li class="sub_no"><a href="content_part_poll_en.phtml"><span style="text-decoration:line-through;font-size:10px;">Poll</span></a></li>
			<li class="sub_no"><a href="content_part_recipe.phtml"><span style="text-decoration:line-through;font-size:10px;">Recipe</span></a></li>
			<li class="sub_no"><a href="content_part_faq_en.phtml"><span style="text-decoration:line-through;font-size:10px;">FAQ</span></a></li>
			<li class="sub_no"><a href="content_part_frontend_login_en.phtml"><span style="text-decoration:line-through;font-size:10px;">Frontend Login</span></a></li>
			<li class="sub_no"><a href="content_part_glossary.phtml"><span style="text-decoration:line-through;font-size:10px;">Plug-in: Glossary</span></a></li>
		</ul>
		</div>
		</li>
	</ul>
	</div>
	</li>
	<li class="sub_no sub_ul_true"><a href="file.phtml">File</a></li>
	<li class="sub_no sub_ul_true"><a href="module_en.phtml">Modules</a></li>
	<li class="sub_no sub_ul_true"><a href="communication.phtml">Communication </a></li>
	<li class="sub_no"><a href="chat_en.phtml">Chat</a></li>
	<li class="sub_no"><a href="profile.phtml">Profile</a></li>
	<li class="sub_no sub_ul_true"><a href="admin_en_.phtml">Admin</a></li>
	<li class="sub_no sub_ul_true"><a href="add-ons-and-templates.phtml">Add On&#039;s and Templates</a></li>
	<li class="sub_no"><a href="deutsche_version.phtml?replacement_tags_en">Replacement Tags</a></li>
	<li class="sub_no"><a href="deutsche_version.phtml?content_parts_en">Content Parts</a></li>
</ul>
</div>

		
	</div> 
	</div> 
	  
	<div id="right">
		<div style="margin-top:24px;">			
		<form action="index.php?search" method="post" name="searchFE" onsubmit="s=document.getElementById('customSearchInput');if(s.value=='Search')return false;">
			<table width="100%" border="0" cellpadding="0" cellspacing="0">
			<tr>
					<td><input type="text" name="search_input_field" size="20" maxlength="200" id="customSearchInput" class="customSearchInput" value="" onfocus="if(this.value=='Search')this.value='';" onblur="if(this.value=='')this.value='Search';"/></td>
					<td><input type="image" name="search_go" onfocus="this.blur();" title="Search" src="/template/lang/all/submit.gif" /></td>
				</tr>
			</table>
			</form>
			
			      <script type="text/javascript" language="javascript">
			  <!-- 
			        document.getElementById("customSearchInput").value="Search";
			  //-->
			      </script>
				  
<!-- <p style="margin-top:10px;">Change font size: <a href="[FontSize-]"><img src="template/lang/all/icons/reduce.gif" width="18" height="17" alt="" title="Small" border="0" /></a>
			<a href="[FontSize+]"><img src="template/lang/all/icons/extend.gif" width="18" height="17" alt="" title="Bigger" border="0" /></a>
			</p> -->
			
	<p style="margin-top:10px;">Please choose: 
	
	 </p>

<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div>
<form action="https://www.paypal.com/cgi-bin/webscr" method="post">
<input type="hidden" name="cmd" value="_xclick" />
<input type="hidden" name="business" value="support@docu.fhss.de" />
<input type="hidden" name="item_name" value="phpwcms-docu.de" />
<input type="hidden" name="buyer_credit_promo_code" value="" />
<input type="hidden" name="buyer_credit_product_category" value="" />
<input type="hidden" name="buyer_credit_shipping_method" value="" />
<input type="hidden" name="buyer_credit_user_address_change" value="" />
<input type="hidden" name="no_shipping" value="0" />
<input type="hidden" name="no_note" value="1" />
<input type="hidden" name="currency_code" value="EUR" />
<input type="hidden" name="tax" value="0" />
<input type="hidden" name="lc" value="DE" />
<input type="hidden" name="bn" value="PP-DonationsBF" />
<input type="image" src="template/img/paypal.gif" name="submit" title="Make a donation ..." alt="Make a donation ..." />
<img alt="" border="0" src="https://www.paypal.com/de_DE/i/scr/pixel.gif" width="1" height="1" />
</form>
<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div>
<!-- <a href="http://validator.w3.org/check?uri=http%3A%2F%2Fwww.phpwcms-docu.de%2Findex.php%3Fdeutsche_version" title="W3C Standard XHTML" target="_blank"><img src="picture/w3c/w3c_xhtml.gif" border="0" alt="" /></a>
<a href="http://jigsaw.w3.org/css-validator/validator?uri=http://www.phpwcms-docu.de" title="W3C Standard CSS" target="_blank"><img src="picture/w3c/w3c_css.gif" border="0" alt="" /></a><br />			
<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div> -->
		
<div style="margin-top:10px; margin-bottom:15px;"></div>
	
</div>

	</div> 
	
	<div id="content">
	<div id="bread">You are here: <a href="english_version.phtml">English</a> <span class="breadcrumb_spacer">&gt;</span> <a href="the_docu.phtml">The Docu</a> <span class="breadcrumb_spacer">&gt;</span> <a href="article.phtml">Articles</a> <span class="breadcrumb_spacer">&gt;</span> <a href="content_parts_en.phtml">Content Parts</a> <span class="breadcrumb_spacer">&gt;</span> Form</div>
		
		<a name="jump285"></a><!-- Livedate: 12.04.2005 10:33:13 / Killdate: 31.12.2030 23:59:59 -->
<h1>Content Part &quot;Form&quot;</h1>
<h3>earlier &quot;email contact form&quot;</h3>

<p><strong><font color="#ff0000">Notice:<br />
This Content Part &quot;Email contact form&quot; was added with the version 1.2.<br />
Since the Release 1.2.9 this content part is renamed to &quot;form&quot;</font></strong></p><div style="border-bottom:1px dotted #d2e2f5; margin-top:10px; margin-bottom:15px;"></div><div style="margin:25px 0 0 0;padding:0;" class="spaceBeforeCP"></div><table width="112" border="0" cellspacing="0" cellpadding="0" align="left">
<tr><td class="image_td2"><a href="content/images/3e83030966f5d7e1e5c4a8179436f4e7.png" rel="lightbox" target="_blank"><img src="content/images/bbb04051e74271c3f9c02f8a33c25bc6.png" width="104" height="200" border="0" class="image_img" alt="form.png" /></a></td><td><img src="img/leer.gif" width="8" height="1" border="0" alt="" /></td></tr>
</table><div class="articleText"><table width="70%" height="200" cellspacing="0" cellpadding="0" border="0">
    <tbody>
        <tr>
            <td valign="top">Here you can&nbsp;find a description how to create an email contact form. You will see a summary of all fields.</td>
        </tr>
    </tbody>
</table></div><div style="border-bottom:1px dotted #d2e2f5; margin-top:10px; margin-bottom:15px;"></div><h3>Field descriptions</h3><table cellspacing="1" cellpadding="0" border="0">
    <tbody>
        <tr>
            <td bgcolor="#cccccc">
            <table cellspacing="1" cellpadding="5" border="0">
                <tbody>
                    <tr valign="top">
                        <td width="60" bgcolor="#ffffff" colspan="2">subject:</td>
                        <td bgcolor="#ffffff" colspan="2">Insert here the subject that shall be transmitted in the email to the recipient (target) and eventually to the sender (copy to).</td>
                    </tr>
                    <tr valign="top">
                        <td bgcolor="#ffffff" colspan="2"><!--StartFragment -->target:<br />
                        <!--StartFragment --></td>
                        <td bgcolor="#ffffff" colspan="2">Insert here the recipient of the email.</td>
                    </tr>
                    <tr valign="top">
                        <td bgcolor="#ffffff" colspan="2">
                        <p align="left">copy to:</p>
                        </td>
                        <td bgcolor="#ffffff" colspan="2">Shall the sender also get a copy of the email, please choose here the form field that contains the sender email address.</td>
                    </tr>
                    <tr>
                        <td bgcolor="#ffffff" colspan="2">on success:</td>
                        <td bgcolor="#ffffff" colspan="2">Shall the sender get a&nbsp;message on a successfully transmitted email, please insert here the alias of the page that contains the message text.</td>
                    </tr>
                    <tr valign="top">
                        <td bgcolor="#ffffff" colspan="2">on error:</td>
                        <td bgcolor="#ffffff" colspan="2">
                        <div align="left">Shall the sender get a&nbsp;message on an incorrect transmitted email, please insert here the alias of the page that contains the message text.</div>
                        </td>
                    </tr>
                    <tr>
                        <td valign="top" bgcolor="#ffffff" colspan="2">form tmpl:</td>
                        <td bgcolor="#ffffff" colspan="2">In the following fields you can define the appearance of the email contact form.</td>
                    </tr>
                    <tr>
                        <td valign="top" bgcolor="#ffffff" colspan="2">alignment:</td>
                        <td bgcolor="#ffffff" colspan="2">
                        <p>Here you can define the alignment of label and field You have the following possibilities:</p>
                        1.&nbsp;Label to the left of a input field<br />
                        2. Label above a input field</td>
                    </tr>
                    <tr valign="top">
                        <td bgcolor="#ffffff" colspan="2">form&nbsp;class:</td>
                        <td bgcolor="#ffffff" colspan="2">
                        <div align="left">If you want to show the form with a special css class, insert&nbsp;the name of this class here.</div>
                        </td>
                    </tr>
                    <tr>
                        <td bgcolor="#ffffff" colspan="2">label wrap:</td>
                        <td bgcolor="#ffffff" colspan="2">If the label shall be wrapped in a special way, insert the data here.</td>
                    </tr>
                    <tr valign="top">
                        <td bgcolor="#ffffff" colspan="2">required mark:&nbsp;</td>
                        <td bgcolor="#ffffff" colspan="2">
                        <div align="left">Required fields can be indicated with a mark. The&nbsp;default mark is *.</div>
                        </td>
                    </tr>
                    <tr valign="top">
                        <td bgcolor="#ffffff" colspan="2">error&nbsp;class:</td>
                        <td bgcolor="#ffffff" colspan="2">
                        <div align="left">
                        <div align="left">If you want to show the error message with a special css class, insert the name of this class here.</div>
                        </div>
                        </td>
                    </tr>
                    <tr valign="top">
                        <td bgcolor="#ffffff" colspan="2">type:</td>
                        <td bgcolor="#ffffff" colspan="2">
                        <div align="left">There are many different field types that can be inserted into the email contact form. The insertion of the field types is possible via the field &quot;value&quot;.</div>
                        <div align="left">The following field types are possible::</div>
                        <div align="left">&nbsp;</div>
                        <div align="left"><strong>- text (single-line)</strong></div>
                        <div align="left">A single line text field will be displayed.</div>
                        <div align="left">&nbsp;</div>
                        <div align="left"><strong>- text (multi-line)</strong></div>
                        <div align="left">A textarea with multiple lines will be displayed.</div>
                        <div align="left">&nbsp;</div>
                        <div align="left"><strong>- text (special)</strong></div>
                        <div align="left">A single line text field with, for example, a formula or a definition of a variable will be displayed.</div>
                        <div align="left">&nbsp;</div>
                        <div align="left"><strong>- hidden</strong></div>
                        <div align="left">Here you can use a hidden field.</div>
                        <div align="left">&nbsp;</div>
                        <div align="left"><strong>- password</strong></div>
                        <div align="left">Display of a password field that is showing the password insertion in a crypted way.</div>
                        <div align="left">&nbsp;</div>
                        <div align="left"><strong>- email</strong></div>
                        <div align="left">Display of a email insertion field.</div>
                        <div align="left">&nbsp;</div>
                        <div align="left"><strong>- select menu</strong></div>
                        <div align="left">Display of a drop down menu.</div>
                        <div align="left">&nbsp;</div>
                        <div align="left"><strong>- list menu</strong></div>
                        <div align="left">Display of a list menu.</div>
                        <div align="left">&nbsp;</div>
                        <div align="left"><strong>- checkbox</strong></div>
                        <div align="left">Display of one ore more checkboxes.</div>
                        <div align="left">&nbsp;</div>
                        <div align="left"><strong>- radio button</strong></div>
                        <div align="left">Display of one or more radio buttons.</div>
                        <div align="left">&nbsp;</div>
                        <div align="left"><strong>- file</strong></div>
                        <div align="left">Here you can give&nbsp;the user&nbsp;the possibility to choose a file out of his/her file system. A field for the file name and a browse button will be displayed.</div>
                        <div align="left">&nbsp;</div>
                        <div align="left"><strong>- send button</strong></div>
                        <div align="left">Display of a send button. The caption of the button can be inserted individually.</div>
                        <div align="left">&nbsp;</div>
                        <div align="left">&nbsp;</div>
                        <div align="left"><strong>- reset button</strong></div>
                        <div align="left">
                        <div align="left">Display of a reset button. The caption of the button can be inserted individually.</div>
                        </div>
                        <div align="left">&nbsp;</div>
                        <div align="left"><strong>- break</strong></div>
                        <div align="left">Display of dividers. The insertion is individually possible.</div>
                        <div align="left">&nbsp;</div>
                        <div align="left"><strong>- break text</strong></div>
                        <div align="left">Display of break text. The insertion is individually possible.</div>
                        </td>
                    </tr>
                    <tr valign="top">
                        <td bgcolor="#ffffff" colspan="2">name:</td>
                        <td bgcolor="#ffffff" colspan="2">
                        <div align="left">Insert here a unique field name for every field.</div>
                        </td>
                    </tr>
                    <tr valign="top">
                        <td bgcolor="#ffffff" colspan="2">label:</td>
                        <td bgcolor="#ffffff" colspan="2">
                        <div align="left">Here you have to insert the label name that will be displayed to the left or above the field (see also the field &quot;alignment&quot;).</div>
                        </td>
                    </tr>
                    <tr valign="top">
                        <td bgcolor="#ffffff" colspan="2">S/C:</td>
                        <td bgcolor="#ffffff" colspan="2">
                        <div align="left">In this filed you can insert for</div>
                        <div align="left">- single line text fields the size of the field and for</div>
                        <div align="left">-&nbsp;text areas&nbsp;the number of columns.</div>
                        </td>
                    </tr>
                    <tr valign="top">
                        <td bgcolor="#ffffff" colspan="2">M/R:</td>
                        <td bgcolor="#ffffff" colspan="2">
                        <div align="left">In this field you can insert for</div>
                        <div align="left">- single line text fields the maximum length of the field and for</div>
                        <div align="left">- text areas the number of rows.</div>
                        <div align="left">
                        <div align="left">With lists&nbsp;the insertion of the value &quot;1&quot; has the effect that you can select multiple&nbsp;list entries at once (multiselection). You can execute the&nbsp; multiple selection with the STRG key.</div>
                        </div>
                        </td>
                    </tr>
                    <tr valign="top">
                        <td bgcolor="#ffffff" colspan="2">! (exclamation mark):</td>
                        <td bgcolor="#ffffff" colspan="2">This field flags the field type to the left as required.</td>
                    </tr>
                    <tr valign="top">
                        <td bgcolor="#ffffff" colspan="2">trash can:</td>
                        <td bgcolor="#ffffff" colspan="2">With the trash can field you can delete the field type to the left.</td>
                    </tr>
                    <tr valign="top">
                        <td bgcolor="#ffffff" colspan="2">value:</td>
                        <td bgcolor="#ffffff" colspan="2">
                        <p>Here you can insert values for the different field types.</p>
                        <p>Beispiele:</p>
                        <div align="left"><strong>- text (single-line)</strong></div>
                        <div align="left">&quot;This is single line text&quot;</div>
                        <div align="left">&nbsp;</div>
                        <div align="left"><strong>- text (multi-line)</strong></div>
                        <div align="left">&quot;This is a multi line text&quot;</div>
                        <div align="left">
                        <div align="left">&quot;This is a multi line text&quot;</div>
                        </div>
                        <div align="left">&nbsp;</div>
                        <div align="left"><strong>- text (special)</strong></div>
                        <div align="left">type=INT - only integer values permissible<br />
                        type=DEC oder FLOAT - only decimal and/or float permissible<br />
                        type=IDENT - Comparison test, only if input identically to the default value<br />
                        type=STRING or MIX<br />
                        type=DATE - examines whether valid date<br />
                        type= A-Z (only upper chars)<br />
                        type=a-z (only lower chars)<br />
                        type=a-Z (only chars)<br />
                        type=0-9 (only digits)<br />
                        type=PHONE (Phonenumber)<br />
                        type=WORD (Word chars)<br />
                        type=LETTER+SPACE (a-Z, space, hyphens)<br />
                        type=REGEX (patterns - new value: pattern<br />
                        =&quot;/...regex-pattern.../&quot;)<br />
                        <br />
                        default=&quot;100&quot;<br />
                        dateformat=&quot;m/d/Y&quot;                         &nbsp;                         <strong>- </strong><strong><br />
                        </strong></div>
                        <div align="left">&nbsp;</div>
                        <div align="left"><strong>- hidden</strong></div>
                        <div align="left">A insertion into this field will not be displayed</div>
                        <div align="left">&nbsp;</div>
                        <div align="left"></div>
                        <div align="left"><strong>- password</strong></div>
                        <div align="left">No insertion necessary.</div>
                        <div align="left">&nbsp;</div>
                        <div align="left"><strong>- email</strong></div>
                        <div align="left">No insertion necessary.</div>
                        <div align="left">&nbsp;</div>
                        <div align="left"></div>
                        <div align="left"></div>
                        <div align="left"><strong>- select menu</strong></div>
                        <div align="left">&quot;Apple&quot;<br />
                        &quot;Cantaloupe&quot;<br />
                        &quot;Pear&quot;</div>
                        <div align="left">&nbsp;</div>
                        <div align="left"><strong>- list menu</strong></div>
                        <div align="left">&quot;Apple&quot;<br />
                        &quot;Cantaloupe&quot;<br />
                        &quot;Pear&quot;</div>
                        <div align="left">&nbsp;</div>
                        <div align="left"><strong>- checkbox</strong></div>
                        <div align="left">&quot;Apple&quot;<br />
                        &quot;Cantaloupe&quot;<br />
                        &quot;Pear&quot;</div>
                        <div align="left">&nbsp;</div>
                        <div align="left"><strong>- radio button</strong></div>
                        <div align="left">&quot;Apple&quot;<br />
                        &quot;Cantaloupe&quot;<br />
                        &quot;Pear&quot;</div>
                        <div align="left"></div>
                        <div align="left"></div>
                        <div align="left"></div>
                        <div align="left"><strong>- file</strong></div>
                        <div align="left"><strong>max. file size:</strong> maxlength=&quot;10000000&quot;<br />
                        <strong>as attachment:</strong> attachment=&quot;1&quot;</div>
                        <div align="left"><strong>what kind of attachment:</strong> accept=&quot;text/*&quot;<br />
                        <strong>out of which folder:</strong> folder=&quot;content/form&quot;<br />
                        <strong>exclude files:</strong></div>
                        <div align="left">exclude=&quot;php,asp,php3,php4,php5,aspx,cfm,js&quot;</div>
                        <div align="left">&nbsp;</div>
                        <div align="left"><strong>- send button</strong></div>
                        <div align="left">&quot;Send request!&quot;</div>
                        <div align="left">&nbsp;</div>
                        <div align="left"><strong>- reset button</strong></div>
                        <div align="left">&quot;Reset fields!&quot;</div>
                        <div align="left">&nbsp;</div>
                        <div align="left"><strong>- break</strong></div>
                        <div align="left">&quot;******************************************************&quot;</div>
                        <div align="left">&nbsp;</div>
                        <div align="left"><strong>- break text</strong></div>
                        <div align="left">&quot;This is a break text&quot;</div>
                        </td>
                    </tr>
                    <tr valign="top">
                        <td bgcolor="#ffffff" colspan="2">error text:</td>
                        <td bgcolor="#ffffff" colspan="2">
                        <p>Insert here an error text, when the user did not fill out a field.</p>
                        <p>Bsp: &quot;Error: The following field is empty:&quot;</p>
                        </td>
                    </tr>
                    <tr valign="top">
                        <td bgcolor="#ffffff" colspan="2">CSS style:</td>
                        <td bgcolor="#ffffff" colspan="2">You can also use an individual css class for this error message.</td>
                    </tr>
                    <tr valign="top">
                        <td bgcolor="#ffffff" colspan="2">template:</td>
                        <td bgcolor="#ffffff" colspan="2">
                        <p>Here you&nbsp;have to insert a template, otherwise you will be sent a blank email.&nbsp;This template can be created as a text template or as an html template. In the templates you can use all&nbsp;field names&nbsp;of the form.</p>
                        </td>
                    </tr>
                </tbody>
            </table>
            </td>
        </tr>
    </tbody>
</table>
		 
		
		<br /><br />
		<div class="sub">
		Article created: Wednesday, 13. April 2005 <br /> Last Changes: Tuesday, 4. January 2011	
		</div>
				
	</div>
	
<div id="footer"><br /><br />
<p style="height:30px;">&nbsp;</p>


 <script type="text/javascript" language="javascript">
<!--

var showDefaultValue =  0

function hideLayer(whichLayer) {
	if (document.getElementById) {
		// this is the way the standards work
		document.getElementById(whichLayer).style.display = "none";
	} else if (document.all) {
		// this is the way old msie versions work
		document.all[whichlayer].style.display = "none";
	} else if (document.layers) {
		// this is the way nn4 works
		document.layers[whichLayer].display = "none";
	}
}

function showLayer(whichLayer) {
		//	alert(whichLayer);
	if (document.getElementById) {
		// this is the way the standards work
		document.getElementById(whichLayer).style.display = "block";
	}
	else if (document.all) {
		// this is the way old msie versions work
		document.all[whichlayer].style.display = "block";
	}
	else if (document.layers) {
		// this is the way nn4 works
		document.layers[whichLayer].display = "block";
	}
}

function toggleLayer(whichLayer) {
	if(showDefaultValue == 0) {
		hideLayer(whichLayer);
		showDefaultValue = 1;
	} else {
		showLayer(whichLayer);
		showDefaultValue = 0;
	}
}
//-->
</script>


<div id="alles">
<div id="klapper" onclick="toggleLayer('formular');">
<table width="570" border="0" cellspacing="0" cellpadding="0">
<tr>
<td><em style="color:#275EA8;" onmouseover="this.style.color='#4F96F4';" onmouseout="this.style.color='#275EA8';">You have suggestions or criticism to this article? Write us!</em></td>   
<td align="right" style="padding-right:2px;"><img src="template/lang/all/icons/write.gif" width="16" height="21" alt="" border="0" /></td>
</tr>
</table>

</div>
<div id="formular">

<form name="form" method="post" action="index.php?id=377,285,0,1,1,0" style="margin:0;padding:0;"><input type="hidden" name="customForm" value="1" /><input type="hidden" name="docucheck" value="1" />


<div style="float:left;">
<p><select name="Betreff" id="Betreff" class="size1">
<option value="" class="deepblue"> Select </option>

</select><br /></p>


<p>Firstname:<br />
<input type="text" name="Vorname" value="" class="size1" /></p>
<p>Surname:*<br />
<input type="text" name="Name" value="" class="size1" /></p>
<p>E-Mail:*<br />
<input type="text" name="E-Mail" value="" class="size1" /></p>
</div>


<div style="float:right;">Message:*<br />
<textarea name="Nachricht" cols="40" rows="4"  class="size7"></textarea>
</div>

<p style="clear:both; text-align:right;"><input type="reset" name="reset" value="Reset" class="btstyle" style="width:100px;" />&nbsp;&nbsp;
<input type="submit" name="submit" value="Send email" class="btstyle" style="width:110px;" /></p>
<p style="margin:20px;" class="sub">* Required fields.<br />Your data is used exclusively for this inquiry.</p>

</form>
</div>
</div>
 <script type="text/javascript" language="javascript">
<!--
	// Lösung ohne Onload
	toggleLayer('formular');
//-->
</script>
<br />





	<table width="97%" border="0" cellspacing="0" cellpadding="0">
		<tr>
			<td valign="bottom">	
			&copy; phpwcms-docu 2004-2013
			<img src="img/leer.gif" border="0" width="10" height="0" alt="" /><a href="imprint.phtml" class="phpwcmsIntLink"><img src="template/lang/all/icons/imprint.gif" width="9" height="15" alt="Impressum" title="Impressum" border="0" /></a>&nbsp; 
			<a href="sitemap_en.phtml" class="phpwcmsIntLink"><img src="template/lang/all/icons/sitemap.gif" width="19" height="15" alt="Sitemap" title="Sitemap" border="0" /></a>&nbsp; 
			 
			
			     
			</td>
			<td valign="bottom" style="padding-right:25px;">
			
			
			
			</td>		
			<td width="150">
			</td>
		</tr>
	</table>
</div><br/>

</div>
</body>
</html>