<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<!--
	phpwcms | free open source content management system
	created by Oliver Georgi (oliver at phpwcms dot de) and licensed under GNU/GPL.
	phpwcms is copyright 2003-2007 of Oliver Georgi. Extensions are copyright of
	their respective owners. Visit project page for details: http://www.phpwcms.org/
//-->
<title>phpwcms-docu for  phpwcms :: web based content management system | Text mit Bild{D:07/24/2007,30,neuR.gif} | Content Part &quot;Text mit Bild&quot;</title>
  <meta http-equiv="content-type" content="text/html; charset=iso-8859-1" />
  <meta http-equiv="content-style-type" content="text/css" />
  <script src="template/inc_js/frontend.js" type="text/javascript"></script>
  <style type="text/css">
  <!-- 
    @import url("template/inc_css/mpl_docu.css");
    @import url("template/inc_css/mpl_frontend.css");
    @import url("template/inc_css/mpl_menu.css");
    @import url("template/inc_css/mpl_objects.css");
  //-->
  </style>
<script type="text/javascript" language="javascript">
<!--
function MM_jumpMenu(targ,selObj,restore){ //v3.0
  eval(targ+".location='"+selObj.options[selObj.selectedIndex].value+"'");
  if (restore) selObj.selectedIndex=0;
}

function MM_findObj(n, d) { //v4.01
  var p,i,x;  if(!d) d=document; if((p=n.indexOf("?"))>0&&parent.frames.length) {
    d=parent.frames[n.substring(p+1)].document; n=n.substring(0,p);}
  if(!(x=d[n])&&d.all) x=d.all[n]; for (i=0;!x&&i<d.forms.length;i++) x=d.forms[i][n];
  for(i=0;!x&&d.layers&&i<d.layers.length;i++) x=MM_findObj(n,d.layers[i].document);
  if(!x && d.getElementById) x=d.getElementById(n); return x;
}

function MM_jumpMenuGo(selName,targ,restore){ //v3.0
  var selObj = MM_findObj(selName); if (selObj) MM_jumpMenu(targ,selObj,restore);
}
//-->
</script>
<meta name="Title" content="Die phpWCMS Dokumentation" />
<meta name="author" content="Oliver Frohnert, Mario Perez Leal" />
<meta name="Publisher" content="Oliver Frohnert, Mario Perez Leal, creacion" />
<meta name="Copyright" content="Oliver Frohnert, Mario Perez Leal, creacion" />
<meta name="keywords" content="frohnert, perez leal, creacion, documentation, dokumentation, phpwcms, cms, opensource, open source, docu" />
<meta name="description" content="Das Dokumentations Projekt für das Open Source CMS phpWCMS" />
<meta name="Audience" content="Alle" />
<meta name="Content-language" content="DE" />
<meta name="robots" content="index,follow" />
<meta name="expires" content="0" />
<meta name="revisit-after" content="7 days" />
<meta name="resource-type" content="document" />
<meta name="distribution" content="Global" />
<meta name="generator" content="PHPWCMS" />

  <link rel="stylesheet" href="template/slimbox/css/slimbox.css" type="text/css" media="screen" />
  <script src="template/inc_js/mootools/mootools.js" type="text/javascript"></script>
  <script src="template/slimbox/js/slimbox.js" type="text/javascript"></script>
  <!--[if lt IE 7]>
  <style type="text/css">
    body { behavior: url("template/inc_css/specific/csshover2.htc"); }
    img { behavior: url("template/inc_css/specific/pngbehavior.htc"); }
  </style>
  <![endif]-->
</head>
<body id="myid_133">
<div id="container"><a name="top" id="top"></a>


	<div id="head">
		
	<div id="mainnavi">
		<div class="fleft"><a href="deutsche_version.phtml">Startseite</a> | <a href="news_de.phtml">News</a> | <span style="text-decoration:none;font-weight:bold;"><a href="die_docu.phtml">Die Docu</a></span> | <a href="Nuetzliche_Links_und_Tools.phtml">Links &amp; Tools</a> | <a href="downloads.phtml">Downloads</a> | <a href="kontakt.phtml">Kontakt</a> | <a href="faq_de.phtml">FAQ</a> | <a href="http://forum.phpwcms.org/" target="_blank">Forum</a> | <a href="howto_de.phtml">HowTo</a></div>				
		<div class="sys">Donnerstag, 9. Juli 2015<img src="img/leer.gif" border="0" width="5" height="1" alt="" />|<img src="img/leer.gif" border="0" width="5" height="1" alt="" />1 User online<img src="img/leer.gif" border="0" width="10" height="1" alt="" />
		<a href="deutsche_version.phtml" title="Deutsche Version"><img src="picture/../template/lang/all/flag_de.gif" border="0" alt="" /></a>
		<a href="english_version.phtml"  title="English version"><img src="picture/../template/lang/all/flag_en.gif" border="0" alt="" /></a>
		</div>
	</div>
	
	<a href="./" title="phpwcms-docu Startseite aufrufen" class="homelink">
	<span>&raquo; Zur phpwcms-docu Startseite</span></a>
	<h2>phpwcms-docu - Die Dokumentation f&uuml;r f&uuml;r das CMS phpWCMS</h2>
	<p>phpwcms-docu ist eine Art Kompass, der Ihnen die M&ouml;glichkeiten von phpWcms aufzeigt und Sie erfolgreich, ohne gro&szlig;e Umwege, zu Ihrer fertigen Web-Anwendung f&uuml;hren soll.
	</p>
	</div>

	
	<div id="left">
	<div class="leftnav" style="margin-top:24px;">
	
<div id="ul_div_309">
<ul>
	<li class="sub_no"><a href="download-dev-versionen.phtml">Download Dev Versionen</a></li>
	<li class="sub_no sub_ul_true"><a href="installation_und_upgrade_von_phpwcms.phtml">Installation &amp; Upgrade</a></li>
	<li class="sub_ul"><a href="verwaltung_artikel.phtml">Artikel</a>
	<div id="ul_div_82">
	<ul>
		<li class="sub_no"><a href="artikel_erstellen.phtml">Artikel erstellen</a></li>
		<li class="sub_no"><a href="artikel_editieren.phtml">Artikel bearbeiten</a></li>
		<li class="sub_no sub_ul_true"><a href="artikel_organisation.phtml">Artikel Organisation</a></li>
		<li class="sub_ul"><a href="content_parts_de.phtml">Content Parts</a>
		<div id="ul_div_100">
		<ul>
			<li class="sub_no"><a href="einfacher_text.phtml">Einfacher Text</a></li>
			<li class="sub_no"><a href="content_part_html_de.phtml">HTML</a></li>
			<li class="sub_no"><a href="content_part_wysiwyg_html_de.phtml">WYSIWYG HTML</a></li>
			<li class="sub_no"><a href="content_part_code_de.phtml">Code</a></li>
			<li class="sub_no active"><a href="content_part_text_mit_bild.phtml">Text mit Bild</a></li>
			<li class="sub_no"><a href="content_part_bilder_div.phtml"><span style="text-decoration:line-through;font-size:10px;">Bilder &lt;DIV&gt;</span></a></li>
			<li class="sub_no"><a href="content_part_bilder.phtml">Bilder</a></li>
			<li class="sub_no"><a href="content_part_aufzaehlung.phtml">Aufzählung</a></li>
			<li class="sub_no"><a href="content_part_liste.phtml">Liste</a></li>
			<li class="sub_no"><a href="content_part_link_und_e-mail.phtml">Link &amp; E-Mail</a></li>
			<li class="sub_no"><a href="content_part_linkliste.phtml">Linkliste</a></li>
			<li class="sub_no"><a href="content_part_artikellink.phtml">Artikellink</a></li>
			<li class="sub_no"><a href="content_part_teaser_artikellink.phtml"><span style="text-decoration:line-through;font-size:10px;">Teaser / Artikellink</span></a></li>
			<li class="sub_no"><a href="content_part_artikelmenue.phtml">Artikelmenü</a></li>
			<li class="sub_no"><a href="content_part_multimedia_de.phtml">Multimedia</a></li>
			<li class="sub_no"><a href="content_part_dateiliste.phtml">Dateiliste</a></li>
			<li class="sub_no sub_ul_true"><a href="content_part_ecard_de.phtml">E-Card</a></li>
			<li class="sub_no"><a href="content_part_formular.phtml">Formular</a></li>
			<li class="sub_no sub_ul_true"><a href="content_part_e-mail_formulargenerator.phtml">E-Mail Form. [OLD]</a></li>
			<li class="sub_no"><a href="content_part_e-mail_formular.phtml">E-Mail Formular</a></li>
			<li class="sub_no sub_ul_true"><a href="content_part_newsletter_de.phtml">Newsletter</a></li>
			<li class="sub_no"><a href="content_part_suche.phtml">Suche</a></li>
			<li class="sub_no sub_ul_true"><a href="content_part_gaestebuch_kommentar.phtml">Gästebuch / Komm.</a></li>
			<li class="sub_no"><a href="content_part_sitemap_de.phtml">Sitemap</a></li>
			<li class="sub_no"><a href="content_part_externer_content.phtml">Ext. Content</a></li>
			<li class="sub_no"><a href="content_part_bildwechsel.phtml">Bildwechsel</a></li>
			<li class="sub_no"><a href="content_part_rss_feed_de.phtml">RSS Feed</a></li>
			<li class="sub_no"><a href="content_part_landkarte.phtml">Landkarte</a></li>
			<li class="sub_no"><a href="content_part_php_variablen.phtml">PHP Variablen</a></li>
			<li class="sub_no"><a href="content_part_contentpart_alias_de.phtml">Contentpart Alias</a></li>
			<li class="sub_no"><a href="content_part_poll_de.phtml"><span style="text-decoration:line-through;font-size:10px;">Poll</span></a></li>
			<li class="sub_no"><a href="content_part_kochrezept.phtml">Kochrezept</a></li>
			<li class="sub_no"><a href="content_part_faq_de.phtml">FAQ</a></li>
			<li class="sub_no"><a href="content_part_frontend_login_de.phtml"><span style="text-decoration:line-through;font-size:10px;">Frontend Login</span></a></li>
			<li class="sub_no"><a href="content_part_glossar.phtml"><span style="text-decoration:line-through;font-size:10px;">Plug-in: Glossar</span></a></li>
		</ul>
		</div>
		</li>
	</ul>
	</div>
	</li>
	<li class="sub_no sub_ul_true"><a href="dateizentrale.phtml">Datei</a></li>
	<li class="sub_no sub_ul_true"><a href="verwaltung_module.phtml">Module</a></li>
	<li class="sub_no sub_ul_true"><a href="Kommunikation.phtml">Kommunikation</a></li>
	<li class="sub_no"><a href="verwaltung_nachricht.phtml">Nachricht</a></li>
	<li class="sub_no"><a href="verwaltung_chat.phtml">Chat</a></li>
	<li class="sub_no"><a href="verwaltung_profil.phtml">Profil</a></li>
	<li class="sub_no sub_ul_true"><a href="verwaltung_admin.phtml">Admin</a></li>
	<li class="sub_no sub_ul_true"><a href="add-on-und-vorlagen.phtml">Add Ons und Vorlagen</a></li>
	<li class="sub_no"><a href="deutsche_version.phtml?replacement_tags_de">Replacement Tags</a></li>
	<li class="sub_no"><a href="deutsche_version.phtml?content_parts_de">Content Parts</a></li>
</ul>
</div>

		
		
		

	</div> 
	</div> 
	  
	<div id="right">
		<div style="margin-top:24px;">			
		<form action="#" method="post" name="searchFE" onsubmit="s=document.getElementById('customSearchInput');if(s.value=='Suchen')return false;">
			<table width="100%" border="0" cellpadding="0" cellspacing="0">
			<tr>
					<td><input type="text" name="search_input_field" size="20" maxlength="200" id="customSearchInput" class="customSearchInput" value="" onfocus="if(this.value=='Suchen')this.value='';" onblur="if(this.value=='')this.value='Suchen';" /></td>
					<td><input type="image" name="search_go" onfocus="this.blur();" title="Suchen" src="/template/lang/all/submit.gif" /></td>
				</tr>
			</table>
			</form>
			
			      <script type="text/javascript" language="javascript">
			  <!-- 
			        document.getElementById("customSearchInput").value="Suchen";
			  //-->
			      </script>
				  
			<!-- <p style="margin-top:10px;">Schriftgrad &auml;ndern: <a href="[FontSize-]"><img src="template/lang/all/icons/reduce.gif" width="18" height="17" alt="" title="Verkleinern" border="0" /></a>
			<a href="[FontSize+]"><img src="template/lang/all/icons/extend.gif" width="18" height="17" alt="" title="Vergr&ouml;&szlig;ern" border="0" /></a>
			</p> -->
			
	<p style="margin-top:10px;">Bitte w&auml;hlen Sie: 
	
	 </p>
<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div>


<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div>
<!-- <a href="http://validator.w3.org/check?uri=http%3A%2F%2Fwww.phpwcms-docu.de%2Findex.php%3Fdeutsche_version" title="W3C Standard XHTML" target="_blank"><img src="picture/w3c/w3c_xhtml.gif" border="0" alt="" /></a>
<a href="http://jigsaw.w3.org/css-validator/validator?uri=http://www.phpwcms-docu.de" title="W3C Standard CSS" target="_blank"><img src="picture/w3c/w3c_css.gif" border="0" alt="" /></a><br />			
<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div> -->
<h3>Partnersites</h3>






<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div>

<div style="margin-top:10px; margin-bottom:15px;"></div>


<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div>
</div>

	</div> 
	
	<div id="content">
	<div id="bread">Sie sind hier: <a href="deutsche_version.phtml">Deutsch</a> <span class="breadcrumb_spacer">&gt;</span> <a href="die_docu.phtml">Die Docu</a> <span class="breadcrumb_spacer">&gt;</span> <a href="verwaltung_artikel.phtml">Artikel</a> <span class="breadcrumb_spacer">&gt;</span> <a href="content_parts_de.phtml">Content Parts</a> <span class="breadcrumb_spacer">&gt;</span> Text mit Bild</div>
		
		<a name="jump109"></a><!-- Livedate: 24.08.2004 07:04:16 / Killdate: 31.12.2030 23:59:59 -->
<h1>Content Part &quot;Text mit Bild&quot;</h1>

<div style="margin:25px 0 0 0;padding:0;" class="spaceBeforeCP"></div><table width="100%" cellpadding="0" cellspacing="0" border="0" class="imgTextRight">
<tr>
<td valign="top" width="10%" class="image_td2"><div class="imgDIVblockImgLeft"><div class="image_td2"><a href="content/images/734c9d68211a5b1edff812b3e5aa7dfe.png" rel="lightbox" title="Content Part &quot;Text mit Bild&quot;" target="_blank"><img src="content/images/e38fad734e65076d626a9fd0b31cba42.png" width="118" height="200" border="0" class="image_img" alt="Text_mit_Bild.png" /></a></div><p class="image_caption">Content Part &quot;Text mit Bild&quot;</p></div></td>
<td valign="top" class="articleText"><p align="left"><strong>HTML Text:</strong> <br />
Hier k&ouml;nnen Sie genau wie mit &bdquo;WYSIWYG HTML&ldquo; Text mit Hilfe der Browser-internen Funktionen &auml;hnlich einer Textverarbeitung eingeben. In den meisten F&auml;llen k&ouml;nnen Sie mit der Kombination der Inhaltstypen &bdquo;Bilder&ldquo; und &bdquo;Text&ldquo; das gleiche Ergebnis erzielen. Die Einstellungen f&uuml;r den Editor den Sie hier sehen sind die gleichen wie bei &quot;WYSIWYG HTML&quot;. N&auml;heres zu den Editoren finden Sie unter <a target="_blank" href="./verwaltung_profil.phtml"><strong>Verwaltung des eigenen Profils</strong></a><br />
<br />
<strong>Bild:</strong> <br />
Hier wird der Name des gew&auml;hlten Bildes angezeigt. Sie k&ouml;nnen das Bild mit folgenden Symbolen w&auml;hlen bzw. austauschen: <br />
<br />
<img src="picture/../img/button/open_image_button.gif" border="0" alt="" /> Klicken Sie, um den phpwcms Bildbrowser (weitere Informationen finden Sie im Abschnitt &bdquo;Die phpwcms Browser&ldquo; weiter unten) zu &ouml;ffnen und ein Bild zu w&auml;hlen.&nbsp;<br />
<br />
<img src="picture/../img/button/del_image_button.gif" border="0" alt="" /> Klicken Sie, um das aktuell gew&auml;hlte Bild zu entfernen.</p></td>
</tr>
</table><div align="right"><a href="#top"><img src="img/article/top_link_0.gif" border="0" alt="" /></a></div><a name="cpid1935" id="cpid1935" class="cpidClass"></a><div style="margin:15px 0 0 0;padding:0;" class="spaceBeforeCP"></div><div class="articleText"><p><strong>Position:</strong> <br />
Hiermit bestimmen Sie, wie das Bild in Bezug auf den Textblock platziert werden soll. Sie k&ouml;nnen das Men&uuml; verwenden oder alternativ die nebenstehenden Symbole:</p>
<fieldset> <legend> <img width="21" height="22" border="0" src="template/lang/all/info_s.gif" title="Info" alt="Info" />&nbsp;</legend>
<table width="100%" cellspacing="0" cellpadding="6" border="0">
    <tbody>
        <tr class="tbfield">
            <td width="90"><img src="picture/../img/button/image_pos0.gif" border="0" alt="" /></td>
            <td>Bild links &uuml;ber dem Textblock anordnen</td>
        </tr>
        <tr>
            <td><img src="picture/../img/button/image_pos1.gif" border="0" alt="" /></td>
            <td>Bild zentriert &uuml;ber dem Textblock anordnen</td>
        </tr>
        <tr class="tbfield">
            <td><img src="picture/../img/button/image_pos2.gif" border="0" alt="" /></td>
            <td>Bild rechts &uuml;ber dem Textblock anordnen</td>
        </tr>
        <tr>
            <td><img src="picture/../img/button/image_pos3.gif" border="0" alt="" /></td>
            <td>Bild links unter dem Textblock anordnen</td>
        </tr>
        <tr class="tbfield">
            <td><img src="picture/../img/button/image_pos4.gif" border="0" alt="" /></td>
            <td>Bild zentriert unter dem Textblock anordnen</td>
        </tr>
        <tr>
            <td><img src="picture/../img/button/image_pos5.gif" border="0" alt="" /></td>
            <td>Bild rechts unter dem Textblock anordnen</td>
        </tr>
        <tr class="tbfield">
            <td><img src="picture/../img/button/image_pos6.gif" border="0" alt="" /></td>
            <td>Bild innerhalb des Textblocks links anordnen</td>
        </tr>
        <tr>
            <td><img src="picture/../img/button/image_pos7.gif" border="0" alt="" /></td>
            <td>Bild innerhalb des Textblocks rechts anordnen</td>
        </tr>
        <tr class="tbfield">
            <td><img src="picture/../img/button/image_pos8.gif" border="0" alt="" /></td>
            <td>Bild in Tabelle links anordnen (seit Version 1.3.3.)</td>
        </tr>
        <tr>
            <td><img src="picture/../img/button/image_pos9.gif" border="0" alt="" /></td>
            <td>Bild in Tabelle rechts anordnen (seit Version 1.3.3)</td>
        </tr>
    </tbody>
</table>
</fieldset>
<p><br />
<strong>max. Breite/max. H&ouml;he:</strong> <br />
Hiermit k&ouml;nnen Sie eine maximale Breite und/oder H&ouml;he des Bildes festlegen. Die Abbildung wird dann dementsprechend dynamisch berechnet, wobei die Proportionen erhalten bleiben. Wenn Sie diese Felder leer lassen, berechnet phpwcms die m&ouml;gliche Maximalgr&ouml;&szlig;e.<br />
<br />
<strong>Klick vergr&ouml;&szlig;eren:</strong> <br />
Hiermit k&ouml;nnen Sie angeben, ob der Besucher durch einen Klick auf das Bild eine vergr&ouml;&szlig;erte Voransicht &ouml;ffnen kann.<br />
<b><br />
Lightbo (ab Version 1.3.3):</b> Durch Setzen des Hakens hier &ouml;ffnet sich das Bild nicht in einem neuen Fenster, sondern in einem Layer. Ein Beispiel daf&uuml;r finden Sie weiter unten.<br />
<br />
<b>Vorschaubilder ohne Bildunterzeile (ab Version 1.3.3): </b><br />
Diese Einstellung bezieht sich nur auf die Lightbox. Das bedeutet, dass unter dem Vorschaubild im Artikel keine Bildunterzeile ausgegeben wird. Wenn Sie das Bild jedoch anklicken erscheint die Bildunterschrift unter der gro&szlig;en Bildansicht. Auch hierzu finden Sie ein Beispiel weiter unten.<br />
<br />
<strong class="error">Hinweis: Um die Funktion Lightbox zu nutzen muss auch bei &quot;Klick vergr&ouml;&szlig;ern&quot; der Haken gesetzt sein.<br />
<br />
</strong><strong>Bildunterzeile:</strong> <br />
Hier k&ouml;nnen Sie eine Textzeile (z.B. eine Beschreibung des Bildes) eingeben, die unterhalb des Bildes angezeigt wird.</p></div><div style="margin:5px 0 0 0;padding:0;" class="spaceBeforeCP"></div><div class="articleText"><!-- BILDUNTERZEILE //-->
<p>Es k&ouml;nnen folgende Eintr&auml;ge gemacht werden:</p>
<fieldset> <legend> <img width="21" height="22" border="0" src="template/lang/all/info_s.gif" title="Info" alt="Info" /> </legend>F&uuml;r eine <strong>Bildbezeichnung</strong>: <br />
&nbsp; Bild-Text <br />
<br />
F&uuml;r eine <strong>Bildbezeichnung</strong> und den <strong>Alt-Text</strong>: <br />
&nbsp; Bild-Text<span style="color: red;"><span style="font-weight: bold;">|</span></span>Alt-Text des Bildes<br />
<br />
F&uuml;r eine <strong>Bildbezeichnung</strong> + <strong>Alt-Text</strong> + <span style="font-weight: bold;">Link zu einem Ziel </span>innerhalb der Site, im selben Fenster: <br />
&nbsp; Bild-Text<span style="color: red;"><span style="font-weight: bold;">|</span></span>Alt-Text des Bildes<span style="font-weight: bold;"><span style="color: red;">|</span></span>index.php?ALIASNAME <br />
<br />
F&uuml;r eine <strong>Bildbezeichnung</strong> + <strong>Alt-Text</strong> + <span style="font-weight: bold;">Link zu einem Ziel </span>au&szlig;erhalb der Site, im selben Fenster: <br />
&nbsp; Bild-Text<span style="color: red;"><span style="font-weight: bold;">|</span></span>Alt-Text des Bildes<span style="color: red;"><span style="font-weight: bold;">|</span></span>http://url.de <br />
<br />
F&uuml;r eine <strong>Bildbezeichnung</strong> + <strong>Alt-Text</strong> + <span style="font-weight: bold;">Link zu einem Ziel </span>au&szlig;erhalb der Site, in einem neuen Fenster: <br />
&nbsp; Bild-Text<span style="color: red;"><span style="font-weight: bold;">|</span></span>Alt-Text des Bildes<span style="color: red;"><span style="font-weight: bold;">|</span></span>http://url.de _blank <br />
<br />
------&nbsp; Seit V1.3.4: <br />
F&uuml;r eine <strong>Bildbezeichnung</strong>, den <strong>Alt-Text</strong> und den <strong>Titel des Bildes</strong>: <br />
Bild-Text<span style="color: red;"><span style="font-weight: bold;">|</span></span>Alt-Text des Bildes<span style="color: red;"><span style="font-weight: bold;">|</span></span><span style="color: red;"><span style="font-weight: bold;">|</span></span>Titel des Bildes<br />
------<br />
<br />
Wenn Du nur einen <span style="font-weight: bold;">Alt-Text </span>brauchst: <br />
&nbsp; <span style="color: red;"><span style="font-weight: bold;">|</span></span>Alt-Text <br />
<br />
Wenn Du einen <strong>internen Link</strong> brauchst:<br />
&nbsp; <span style="color: red;"><span style="font-weight: bold;">||</span></span>index.php?ALIASNAME <br />
<br />
</fieldset></div><div align="right"><a href="#top"><img src="img/article/top_link_0.gif" border="0" alt="" /></a></div><div style="border-bottom:1px dotted #d2e2f5; margin-top:10px; margin-bottom:15px;"></div><div style="margin:25px 0 0 0;padding:0;" class="spaceBeforeCP"></div><h3>Lightbox vs. normales Fenster</h3><table width="100%" cellpadding="0" cellspacing="0" border="0" class="imgTextRight">
<tr>
<td valign="top" width="10%" class="image_td2"><div class="imgDIVblockImgLeft"><div class="image_td2"><a href="zoom/Mzg1OTU0ZTE5MzdiN2IyMjQzNmMxNmQ4MjVkZDgxNDguanBnP3dpZHRoPSIzNjAiIGhlaWdodD0iNDU5Ig.html" onclick="checkClickZoom();clickZoom('zoom/Mzg1OTU0ZTE5MzdiN2IyMjQzNmMxNmQ4MjVkZDgxNDguanBnP3dpZHRoPSIzNjAiIGhlaWdodD0iNDU5Ig.html','previewpic','width.html');return false;.html"><img src="content/images/196ed832e5153aea7fbe21d895380ed5.jpg" width="150" height="191" border="0" class="image_img" alt="Alt-Text: Bild ohne Lightbox" title="Titel: Bild ohne Lightbox" /></a></div><p class="image_caption">Bild ohne Lightbox</p></div></td>
<td valign="top" class="articleText"><p>Der Unterschied zwischen beiden Ansichten ist mehr oder weniger eine grafische Spielerei.<br />
<br />
Bei dem Bild in der Content Part Beschreibung ist der Haken bei Lightbox gesetzt. <br />
Das Bild hier wird ohne Lightbox angezeigt.</p></td>
</tr>
</table><div align="right"><a href="#top"><img src="img/article/top_link_0.gif" border="0" alt="" /></a></div><div style="border-bottom:1px dotted #d2e2f5; margin-top:10px; margin-bottom:15px;"></div><h3>Beispiel: Vorschaubilder ohne Bildunterzeile</h3><table width="100%" cellpadding="0" cellspacing="0" border="0" class="imgTextRight">
<tr>
<td valign="top" width="10%" class="image_td2"><div class="imgDIVblockImgLeft"><div class="image_td2"><a href="content/images/385954e1937b7b22436c16d825dd8148.jpg" rel="lightbox" title="Haken bei &quot;Vorschaubilder ohne Bildunterzeile&quot; gesetzt." target="_blank"><img src="content/images/99eb66e247daf1c3357da5be60f842cc.jpg" width="156" height="200" border="0" class="image_img" alt="Alt-Text" title="Titel zum Bild" /></a></div></div></td>
<td valign="top" class="articleText"><p>Hier sehen Sie nun das Beispiel wenn Sie bei Lightbox und Vorschaubilder ohne Bildunterzeile den Haken gesetzt haben.<br />
<br />
Unter der kleinen Voransicht links sehen sie <u>keine</u> Bildunterschrift. Wenn Sie jedoch das Bild anklicken und in der vergr&ouml;&szlig;erten Ansicht betrachten sehen Sie unter der Grafik folgenden Text &quot;<strong>Haken bei &quot;Vorschaubilder ohne Bildunterzeile&quot; gesetzt</strong>&quot;</p></td>
</tr>
</table>
		 
		
		<br /><br />
		<div class="sub">
		Artikel erstellt am: Dienstag, 24. August 2004 <br /> Letzte &Auml;nderung: Dienstag, 04. Januar 2011	
		</div>
				
	</div>
	
<div id="footer">





	<table width="97%" border="0" cellspacing="0" cellpadding="0">
		<tr>
			<td valign="bottom">	
			&copy; phpwcms-docu 2004-2015
			<img src="img/leer.gif" border="0" width="10" height="0" alt="" /><a href="impressum.phtml" class="phpwcmsIntLink"><img src="template/lang/all/icons/imprint.gif" width="9" height="15" alt="Impressum" title="Impressum" border="0" /></a>&nbsp; 
			<a href="sitemap_de.phtml" class="phpwcmsIntLink"><img src="template/lang/all/icons/sitemap.gif" width="19" height="15" alt="Sitemap" title="Sitemap" border="0" /></a>&nbsp; 
			<a href="gaestebuch.phtml" class="phpwcmsIntLink"><img src="template/lang/all/icons/gbook.gif" width="20" height="16" alt="Ins G&auml;stebuch eintragen" title="Ins G&auml;stebuch eintragen" border="0" /></a>&nbsp; 
			<a href="#" onclick="BookMark_Page();return false;" title="" class="phpwcmsBookmarkLink"><img src="template/lang/all/icons/favo.gif" width="12" height="15" alt="Seite als Bookmark speichern" title="Seite als Bookmark speichern" border="0" /></a>&nbsp; 
			     
			</td>
			<td valign="bottom" style="padding-right:25px;">
			
			
			
			</td>		
			<td width="150">
			</td>
		</tr>
	</table>
</div><br/>

</div>
</body>
</html>