<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<!--
	phpwcms | free open source content management system
	created by Oliver Georgi (oliver at phpwcms dot de) and licensed under GNU/GPL.
	phpwcms is copyright 2003-2007 of Oliver Georgi. Extensions are copyright of
	their respective owners. Visit project page for details: http://www.phpwcms.org/
//-->
<title>phpwcms-docu for  phpwcms :: web based content management system | Multimedia{D:07/25/2007,30,neuR.gif} | Content Part &quot;Multimedia&quot;</title>
  <meta http-equiv="content-type" content="text/html; charset=iso-8859-1" />
  <meta http-equiv="content-style-type" content="text/css" />
  <script src="template/inc_js/frontend.js" type="text/javascript"></script>
  <style type="text/css">
  <!-- 
    @import url("template/inc_css/mpl_docu.css");
    @import url("template/inc_css/mpl_frontend.css");
    @import url("template/inc_css/mpl_menu.css");
    @import url("template/inc_css/mpl_objects.css");
  //-->
  </style>
<script type="text/javascript" language="javascript">
<!--
function MM_jumpMenu(targ,selObj,restore){ //v3.0
  eval(targ+".location='"+selObj.options[selObj.selectedIndex].value+"'");
  if (restore) selObj.selectedIndex=0;
}

function MM_findObj(n, d) { //v4.01
  var p,i,x;  if(!d) d=document; if((p=n.indexOf("?"))>0&&parent.frames.length) {
    d=parent.frames[n.substring(p+1)].document; n=n.substring(0,p);}
  if(!(x=d[n])&&d.all) x=d.all[n]; for (i=0;!x&&i<d.forms.length;i++) x=d.forms[i][n];
  for(i=0;!x&&d.layers&&i<d.layers.length;i++) x=MM_findObj(n,d.layers[i].document);
  if(!x && d.getElementById) x=d.getElementById(n); return x;
}

function MM_jumpMenuGo(selName,targ,restore){ //v3.0
  var selObj = MM_findObj(selName); if (selObj) MM_jumpMenu(targ,selObj,restore);
}
//-->
</script>
<meta name="Title" content="Die phpWCMS Dokumentation" />
<meta name="author" content="Oliver Frohnert, Mario Perez Leal" />
<meta name="Publisher" content="Oliver Frohnert, Mario Perez Leal, creacion" />
<meta name="Copyright" content="Oliver Frohnert, Mario Perez Leal, creacion" />
<meta name="keywords" content="frohnert, perez leal, creacion, documentation, dokumentation, phpwcms, cms, opensource, open source, docu" />
<meta name="description" content="Das Dokumentations Projekt für das Open Source CMS phpWCMS" />
<meta name="Audience" content="Alle" />
<meta name="Content-language" content="DE" />
<meta name="robots" content="index,follow" />
<meta name="expires" content="0" />
<meta name="revisit-after" content="7 days" />
<meta name="resource-type" content="document" />
<meta name="distribution" content="Global" />
<meta name="generator" content="PHPWCMS" />
<meta name="verify-v1" content="1ZpxZ7AZsjm7PxjqXQVus0eiUYqOsp5URTJn9q4KNz8=" />
  <link rel="stylesheet" href="template/slimbox/css/slimbox.css" type="text/css" media="screen" />
  <script src="template/inc_js/mootools/mootools.js" type="text/javascript"></script>
  <script src="template/slimbox/js/slimbox.js" type="text/javascript"></script>
  <script src="template/inc_js/AC_RunActiveContent.js" type="text/javascript"></script>
  <!--[if lt IE 7]>
  <style type="text/css">
    body { behavior: url("template/inc_css/specific/csshover2.htc"); }
    img { behavior: url("template/inc_css/specific/pngbehavior.htc"); }
  </style>
  <![endif]-->
</head>
<body id="myid_140">
<div id="container"><a name="top" id="top"></a>


	<div id="head">
		
	<div id="mainnavi">
		<div class="fleft"><a href="deutsche_version.phtml">Startseite</a> | <a href="news_de.phtml">News</a> | <span style="text-decoration:none;font-weight:bold;"><a href="die_docu.phtml">Die Docu</a></span> | <a href="Nuetzliche_Links_und_Tools.phtml">Links &amp; Tools</a> | <a href="downloads.phtml">Downloads</a> | <a href="kontakt.phtml">Kontakt</a> | <a href="faq_de.phtml">FAQ</a> | <a href="http://forum.phpwcms.org/" target="_blank">Forum</a> | <a href="howto_de.phtml">HowTo</a></div>				
		<div class="sys">Donnerstag, 9. Juli 2015<img src="img/leer.gif" border="0" width="5" height="1" alt="" />|<img src="img/leer.gif" border="0" width="5" height="1" alt="" />2 User online<img src="img/leer.gif" border="0" width="10" height="1" alt="" />
		<a href="deutsche_version.phtml" title="Deutsche Version"><img src="picture/../template/lang/all/flag_de.gif" border="0" alt="" /></a>
		<a href="english_version.phtml"  title="English version"><img src="picture/../template/lang/all/flag_en.gif" border="0" alt="" /></a>
		</div>
	</div>
	
	<a href="./" title="phpwcms-docu Startseite aufrufen" class="homelink">
	<span>&raquo; Zur phpwcms-docu Startseite</span></a>
	<h2>phpwcms-docu - Die Dokumentation f&uuml;r f&uuml;r das CMS phpWCMS</h2>
	<p>phpwcms-docu ist eine Art Kompass, der Ihnen die M&ouml;glichkeiten von phpWcms aufzeigt und Sie erfolgreich, ohne gro&szlig;e Umwege, zu Ihrer fertigen Web-Anwendung f&uuml;hren soll.
	</p>
	</div>

	
	<div id="left">
	<div class="leftnav" style="margin-top:24px;">
	
<div id="ul_div_309">
<ul>
	<li class="sub_no"><a href="download-dev-versionen.phtml">Download Dev Versionen</a></li>
	<li class="sub_no sub_ul_true"><a href="installation_und_upgrade_von_phpwcms.phtml">Installation &amp; Upgrade</a></li>
	<li class="sub_ul"><a href="verwaltung_artikel.phtml">Artikel</a>
	<div id="ul_div_82">
	<ul>
		<li class="sub_no"><a href="artikel_erstellen.phtml">Artikel erstellen</a></li>
		<li class="sub_no"><a href="artikel_editieren.phtml">Artikel bearbeiten</a></li>
		<li class="sub_no sub_ul_true"><a href="artikel_organisation.phtml">Artikel Organisation</a></li>
		<li class="sub_ul"><a href="content_parts_de.phtml">Content Parts</a>
		<div id="ul_div_100">
		<ul>
			<li class="sub_no"><a href="einfacher_text.phtml">Einfacher Text</a></li>
			<li class="sub_no"><a href="content_part_html_de.phtml">HTML</a></li>
			<li class="sub_no"><a href="content_part_wysiwyg_html_de.phtml">WYSIWYG HTML</a></li>
			<li class="sub_no"><a href="content_part_code_de.phtml">Code</a></li>
			<li class="sub_no"><a href="content_part_text_mit_bild.phtml">Text mit Bild</a></li>
			<li class="sub_no"><a href="content_part_bilder_div.phtml"><span style="text-decoration:line-through;font-size:10px;">Bilder &lt;DIV&gt;</span></a></li>
			<li class="sub_no"><a href="content_part_bilder.phtml">Bilder</a></li>
			<li class="sub_no"><a href="content_part_aufzaehlung.phtml">Aufzählung</a></li>
			<li class="sub_no"><a href="content_part_liste.phtml">Liste</a></li>
			<li class="sub_no"><a href="content_part_link_und_e-mail.phtml">Link &amp; E-Mail</a></li>
			<li class="sub_no"><a href="content_part_linkliste.phtml">Linkliste</a></li>
			<li class="sub_no"><a href="content_part_artikellink.phtml">Artikellink</a></li>
			<li class="sub_no"><a href="content_part_teaser_artikellink.phtml"><span style="text-decoration:line-through;font-size:10px;">Teaser / Artikellink</span></a></li>
			<li class="sub_no"><a href="content_part_artikelmenue.phtml">Artikelmenü</a></li>
			<li class="sub_no active"><a href="content_part_multimedia_de.phtml">Multimedia</a></li>
			<li class="sub_no"><a href="content_part_dateiliste.phtml">Dateiliste</a></li>
			<li class="sub_no sub_ul_true"><a href="content_part_ecard_de.phtml">E-Card</a></li>
			<li class="sub_no"><a href="content_part_formular.phtml">Formular</a></li>
			<li class="sub_no sub_ul_true"><a href="content_part_e-mail_formulargenerator.phtml">E-Mail Form. [OLD]</a></li>
			<li class="sub_no"><a href="content_part_e-mail_formular.phtml">E-Mail Formular</a></li>
			<li class="sub_no sub_ul_true"><a href="content_part_newsletter_de.phtml">Newsletter</a></li>
			<li class="sub_no"><a href="content_part_suche.phtml">Suche</a></li>
			<li class="sub_no sub_ul_true"><a href="content_part_gaestebuch_kommentar.phtml">Gästebuch / Komm.</a></li>
			<li class="sub_no"><a href="content_part_sitemap_de.phtml">Sitemap</a></li>
			<li class="sub_no"><a href="content_part_externer_content.phtml">Ext. Content</a></li>
			<li class="sub_no"><a href="content_part_bildwechsel.phtml">Bildwechsel</a></li>
			<li class="sub_no"><a href="content_part_rss_feed_de.phtml">RSS Feed</a></li>
			<li class="sub_no"><a href="content_part_landkarte.phtml">Landkarte</a></li>
			<li class="sub_no"><a href="content_part_php_variablen.phtml">PHP Variablen</a></li>
			<li class="sub_no"><a href="content_part_contentpart_alias_de.phtml">Contentpart Alias</a></li>
			<li class="sub_no"><a href="content_part_poll_de.phtml"><span style="text-decoration:line-through;font-size:10px;">Poll</span></a></li>
			<li class="sub_no"><a href="content_part_kochrezept.phtml">Kochrezept</a></li>
			<li class="sub_no"><a href="content_part_faq_de.phtml">FAQ</a></li>
			<li class="sub_no"><a href="content_part_frontend_login_de.phtml"><span style="text-decoration:line-through;font-size:10px;">Frontend Login</span></a></li>
			<li class="sub_no"><a href="content_part_glossar.phtml"><span style="text-decoration:line-through;font-size:10px;">Plug-in: Glossar</span></a></li>
		</ul>
		</div>
		</li>
	</ul>
	</div>
	</li>
	<li class="sub_no sub_ul_true"><a href="dateizentrale.phtml">Datei</a></li>
	<li class="sub_no sub_ul_true"><a href="verwaltung_module.phtml">Module</a></li>
	<li class="sub_no sub_ul_true"><a href="Kommunikation.phtml">Kommunikation</a></li>
	<li class="sub_no"><a href="verwaltung_nachricht.phtml">Nachricht</a></li>
	<li class="sub_no"><a href="verwaltung_chat.phtml">Chat</a></li>
	<li class="sub_no"><a href="verwaltung_profil.phtml">Profil</a></li>
	<li class="sub_no sub_ul_true"><a href="verwaltung_admin.phtml">Admin</a></li>
	<li class="sub_no sub_ul_true"><a href="add-on-und-vorlagen.phtml">Add Ons und Vorlagen</a></li>
	<li class="sub_no"><a href="deutsche_version.phtml?replacement_tags_de">Replacement Tags</a></li>
	<li class="sub_no"><a href="deutsche_version.phtml?content_parts_de">Content Parts</a></li>
</ul>
</div>

		
		
		

	</div> 
	</div> 
	  
	<div id="right">
		<div style="margin-top:24px;">			
		<form action="index.php?suche" method="post" name="searchFE" onsubmit="s=document.getElementById('customSearchInput');if(s.value=='Suchen')return false;">
			<table width="100%" border="0" cellpadding="0" cellspacing="0">
			<tr>
					<td><input type="text" name="search_input_field" size="20" maxlength="200" id="customSearchInput" class="customSearchInput" value="" onfocus="if(this.value=='Suchen')this.value='';" onblur="if(this.value=='')this.value='Suchen';" /></td>
					<td><input type="image" name="search_go" onfocus="this.blur();" title="Suchen" src="/template/lang/all/submit.gif" /></td>
				</tr>
			</table>
			</form>
			
			      <script type="text/javascript" language="javascript">
			  <!-- 
			        document.getElementById("customSearchInput").value="Suchen";
			  //-->
			      </script>
				  
			<!-- <p style="margin-top:10px;">Schriftgrad &auml;ndern: <a href="[FontSize-]"><img src="template/lang/all/icons/reduce.gif" width="18" height="17" alt="" title="Verkleinern" border="0" /></a>
			<a href="[FontSize+]"><img src="template/lang/all/icons/extend.gif" width="18" height="17" alt="" title="Vergr&ouml;&szlig;ern" border="0" /></a>
			</p> -->
			
	<p style="margin-top:10px;">Bitte w&auml;hlen Sie: 
	
	 </p>
<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div>


<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div>
<!-- <a href="http://validator.w3.org/check?uri=http%3A%2F%2Fwww.phpwcms-docu.de%2Findex.php%3Fdeutsche_version" title="W3C Standard XHTML" target="_blank"><img src="picture/w3c/w3c_xhtml.gif" border="0" alt="" /></a>
<a href="http://jigsaw.w3.org/css-validator/validator?uri=http://www.phpwcms-docu.de" title="W3C Standard CSS" target="_blank"><img src="picture/w3c/w3c_css.gif" border="0" alt="" /></a><br />			
<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div> -->
<h3>Partnersites</h3>






<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div>

<div style="margin-top:10px; margin-bottom:15px;"></div>


<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div>
</div>

	</div> 
	
	<div id="content">
	<div id="bread">Sie sind hier: <a href="deutsche_version.phtml">Deutsch</a> <span class="breadcrumb_spacer">&gt;</span> <a href="die_docu.phtml">Die Docu</a> <span class="breadcrumb_spacer">&gt;</span> <a href="verwaltung_artikel.phtml">Artikel</a> <span class="breadcrumb_spacer">&gt;</span> <a href="content_parts_de.phtml">Content Parts</a> <span class="breadcrumb_spacer">&gt;</span> Multimedia</div>
		
		<a name="jump127"></a><!-- Livedate: 25.08.2004 11:04:46 / Killdate: 31.12.2030 23:59:59 -->
<h1>Content Part &quot;Multimedia&quot;</h1>

<div style="margin:25px 0 0 0;padding:0;" class="spaceBeforeCP"></div><table width="100%" cellpadding="0" cellspacing="0" border="0" class="imgTextRight">
<tr>
<td valign="top" width="10%" class="image_td2"><div class="imgDIVblockImgLeft"><div class="image_td2"><a href="content/images/5ac14f47fd14cd7850f42daca7b9ee8c.png" rel="lightbox" title="Content Part &quot;Multimedia&quot;" target="_blank"><img src="content/images/9ab98e50244cc9ebb7a2e38d96f753a0.png" width="150" height="122" border="0" class="image_img" alt="Multimedia.png" /></a></div><p class="image_caption">Content Part &quot;Multimedia&quot;</p></div></td>
<td valign="top" class="articleText"><p align="left"><strong>Medientyp:</strong> <br />
Hier k&ouml;nnn Sie angeben, um welchen Medientyp sich die Datei handelt.&nbsp;<br />
<br />
<strong>player/plugin:</strong> <br />
Hier k&ouml;nnen Sie angeben, welcher Player zur Darstellung der Datei verwendet werden soll.&nbsp;<br />
<br />
<strong>Steuerung zeigen:</strong> <br />
Hiermit k&ouml;nnen Sie w&auml;hlen, ob die Steuerung, z.B. f&uuml;r Play/Pause angezeigt werden soll. <strong><br />
</strong></p></td>
</tr>
</table><div align="right"><a href="#top"><img src="img/article/top_link_0.gif" border="0" alt="" /></a></div><div style="border-bottom:1px dotted #d2e2f5; margin-top:10px; margin-bottom:15px;"></div><div class="articleText"><p><strong>AutoPlay:</strong> <br />
Hiermit k&ouml;nnen Sie w&auml;hlen, ob die Datei nach dem Laden automatisch wiedergegeben werden soll.<br />
<br />
<strong>Flash transparent:</strong> <br />
Bezieht sich nur auf Flashfilme am Anfang bzw. am Ende wenn das Bild steht wird der Hintergrund transparent angezeigt.<br />
<br />
<strong>Quelle:</strong> <br />
Hier k&ouml;nnen Sie zwischen einer internen und einer externen Quelle w&auml;hlen. Eine interne Quelle w&auml;hlen Sie &uuml;ber den phpwcms Mediabrowser indem Sie auf <img src="picture/../img/button/open_image_button.gif" border="0" alt="" />&nbsp;klicken. Eine etxerne Quelle geben Sie als Webadresse, z.B. &bdquo;http://www.meine-domain.de/meinfilm.mpg&ldquo; an.&nbsp;Um die Eintr&auml;ge in diesen Feldern zu l&ouml;schen dr&uuml;cken Sie <img src="picture/../img/button/del_image_button.gif" border="0" alt="" /> <br />
&nbsp;</p>
<fieldset> <legend> <img width="21" height="22" border="0" align="middle" title="Info" alt="Info" src="template/lang/all/info_s.gif" /> <strong>Position</strong></legend> Hier k&ouml;nnen Sie die Position auf der Seite bestimmen. Sie k&ouml;nnen zwischen folgenden Optionen w&auml;hlen:<br />
<br />
<table width="100%" cellspacing="0" cellpadding="6" border="0">
    <tbody>
        <tr>
            <td><img src="picture/../img/button/image_pos0.gif" border="0" alt="" /></td>
            <td>Mediainhalt links &uuml;ber dem Absatz anordnen</td>
        </tr>
        <tr class="tbfield">
            <td><img src="picture/../img/button/image_pos1.gif" border="0" alt="" /></td>
            <td>Mediainhalt zentriert &uuml;ber dem Absatz anordnen</td>
        </tr>
        <tr>
            <td><img src="picture/../img/button/image_pos2.gif" border="0" alt="" /></td>
            <td>Mediainhalt rechts &uuml;ber dem Absatz anordnen</td>
        </tr>
        <tr class="tbfield">
            <td><img src="picture/../img/button/image_pos6.gif" border="0" alt="" /></td>
            <td>Mediainhalt innerhalb des Absatzes links anordnen</td>
        </tr>
        <tr>
            <td><img src="picture/../img/button/image_pos7.gif" border="0" alt="" /></td>
            <td>Mediainhalt innerhalb des Absatzes rechts anordnen</td>
        </tr>
    </tbody>
</table>
</fieldset>
<p>&nbsp;</p>
<p><strong class="error">Wozu eine Position bzw. Ausrichtung im Text wenn ich keinen Text in diesem Content Part eingeben kann? Dazu haben wir am Ende der Seite ein Beispiel f&uuml;r Sie zusammengestellt.</strong></p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<fieldset> <legend> <img width="21" height="22" border="0" align="middle" src="template/lang/all/info_s.gif" alt="Info" title="Info" /> <strong>Breite / H&ouml;he (optional)</strong></legend> Hier k&ouml;nnen Sie eine Gr&ouml;&szlig;e vorgeben. Sie k&ouml;nnen zum schnellen Einstellen auch zwischen folgenden Standardformaten w&auml;hlen, indem Sie auf den entsprechenden Knopf klicken:<br />
<br />
<table width="100%" cellspacing="0" cellpadding="6" border="0">
    <tbody>
        <tr>
            <td><img src="picture/../img/button/video_160x120.gif" border="0" alt="" /></td>
            <td>f&uuml;r 160 Pixel Breite und 120 Pixel H&ouml;he</td>
        </tr>
        <tr class="tbfield">
            <td><img src="picture/../img/button/video_240x180.gif" border="0" alt="" /></td>
            <td>f&uuml;r 240 Pixel Breite und 240 Pixel H&ouml;he</td>
        </tr>
        <tr>
            <td><img src="picture/../img/button/video_320x240.gif" border="0" alt="" /></td>
            <td>f&uuml;r 320 Pixel Breite und 240 Pixel H&ouml;he</td>
        </tr>
        <tr class="tbfield">
            <td><img src="picture/../img/button/video_480x360.gif" border="0" alt="" /></td>
            <td>f&uuml;r 480 Pixel Breite und 360 Pixel H&ouml;he</td>
        </tr>
        <tr>
            <td><img src="picture/../img/button/del_image_button.gif" border="0" alt="" /></td>
            <td>um die Mediama&szlig;e zu entfernen</td>
        </tr>
    </tbody>
</table>
</fieldset></div><div style="border-bottom:1px dotted #d2e2f5; margin-top:10px; margin-bottom:15px;"></div><a name="cpid1572" id="cpid1572" class="cpidClass"></a><div style="margin:10px 0 0 0;padding:0;" class="spaceBeforeCP"></div><h3>Wozu Ausrichtung im Text wenn ich keinen Text eingeben kann?</h3><p>Sicher ist Ihnen aufgefallen, das es in dem Content Part eine Textausrichtung gibt, obwohl man ja selber keinen Text in dem Content Part eingeben kann.<br />
<br />
Erstellen sie zuerst einen &quot;Multimedia&quot; Content Part, danach z.b. einen WYSIWYG HTML oder Einfacher Text. Der Content Part mit dem Text rutscht dann automatisch in die von uns ausgew&auml;hlte Position.<br />
<br />
Nachfolgend ein Beispiel:<br />
Als Erstes wurde der Content Part &quot;Multimedia&quot; erstellt mit folgender Ausrichtung <img alt="" src="./img/button/image_pos6.gif" />. Danach ein &quot;WYSIWYG HTML&quot; Content Part. Das Ergebnis k&ouml;nnen Sie nun betrachten.</p><div style="margin:15px 0 0 0;padding:0;" class="spaceBeforeCP"></div><table border="0" cellspacing="0" cellpadding="0" align="left">
<tr><td colspan="2"><img src="img/leer.gif" width="1" height="3" border="0" alt="" /></td></tr>
<tr><td>
<noscript><object id="mediaID1573" name="mediaID1573" width="240" height="180" data="phpwcms_filestorage/a2b1b345bfa23a65818e067c0ed2b876.swf" type="application/x-shockwave-flash">
	<param name="movie" value="phpwcms_filestorage/a2b1b345bfa23a65818e067c0ed2b876.swf" />
	<param name="quality" value="high" />
	<param name="scale" value="noborder" />
	<param name="loop" value="false" />
	<param name="play" value="false" />
</object></noscript>
<script type="text/javascript" language="javascript">
  <!-- 
  AC_FL_RunContent('codebase','http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,29,0','id','mediaID1573','width','240','height','180','src','phpwcms_filestorage/a2b1b345bfa23a65818e067c0ed2b876','quality','high','scale','noborder','pluginspage','http://www.macromedia.com/shockwave/download/index.cgi?P1_Prod_Version=ShockwaveFlash','movie','phpwcms_filestorage/a2b1b345bfa23a65818e067c0ed2b876' );
  //-->
</script></td><td><img src="img/leer.gif" width="5" height="1" border="0" alt="" /></td></tr>
<tr><td colspan="2"><img src="img/leer.gif" width="1" height="3" border="0" alt="" /></td></tr>
</table>
<h3>Ein tolles Video mit Blindtext</h3><p>Redior, sui cautor Concito, far, Comitatus mus Ambiguus palma via Degenero pio ala Imputo. Pudeo teneo triticeus, iam conjuratio, regno re oro Aveho curiositas cicuta, dis Occulte, deprecativus typus caterva pauci, his re supermitto.</p>
<p>Ruo in divortium ita sesquimellesimus Oppono plus celo sceptrum, res ingustatus hi Ango prae tum quatenus/quatinus Sumptus per Avoco nos Indulgens mei heu cur Baiulus attonitus.&nbsp;</p><div style="clear:both;"></div>
		 
		
		<br /><br />
		<div class="sub">
		Artikel erstellt am: Mittwoch, 25. August 2004 <br /> Letzte &Auml;nderung: Dienstag, 04. Januar 2011	
		</div>
				
	</div>
	
<div id="footer"><br /><br />
<p style="height:30px;">&nbsp;</p>


 <script type="text/javascript" language="javascript">
<!--

var showDefaultValue =  0

function hideLayer(whichLayer) {
	if (document.getElementById) {
		// this is the way the standards work
		document.getElementById(whichLayer).style.display = "none";
	} else if (document.all) {
		// this is the way old msie versions work
		document.all[whichlayer].style.display = "none";
	} else if (document.layers) {
		// this is the way nn4 works
		document.layers[whichLayer].display = "none";
	}
}

function showLayer(whichLayer) {
		//	alert(whichLayer);
	if (document.getElementById) {
		// this is the way the standards work
		document.getElementById(whichLayer).style.display = "block";
	}
	else if (document.all) {
		// this is the way old msie versions work
		document.all[whichlayer].style.display = "block";
	}
	else if (document.layers) {
		// this is the way nn4 works
		document.layers[whichLayer].display = "block";
	}
}

function toggleLayer(whichLayer) {
	if(showDefaultValue == 0) {
		hideLayer(whichLayer);
		showDefaultValue = 1;
	} else {
		showLayer(whichLayer);
		showDefaultValue = 0;
	}
}
//-->
</script>


<div id="alles">
<div id="klapper" onclick="toggleLayer('formular');">
<table width="570" border="0" cellspacing="0" cellpadding="0">
<tr>
<td><em style="color:#275EA8;" onmouseover="this.style.color='#4F96F4';" onmouseout="this.style.color='#275EA8';">Sie haben Anregungen oder Kritik zu diesem Artikel? Schreiben Sie uns!</em></td>   
<td align="right" style="padding-right:2px;"><img src="template/lang/all/icons/write.gif" width="16" height="21" alt="" border="0" /></td>
</tr>
</table>

</div>
<div id="formular">

<form name="form" method="post" action="index.php?id=140,127,0,1,1,0" style="margin:0;padding:0;"><input type="hidden" name="customForm" value="1" /><input type="hidden" name="docucheck" value="1" />


<div style="float:left;">
<p><select name="Betreff" id="Betreff" class="size1">
<option value="" class="deepblue"> Bitte ausw&auml;hlen </option>
<option value="subject_1" class="inselect">Anregungen</option>
<option value="subject_2" class="inselect">Fehlermeldung/ Kritik</option>
<option value="subject_3" class="inselect">Sonstiges</option>

</select><br /></p>


<p>Vorname:<br />
<input type="text" name="Vorname" value="" class="size1" /></p>
<p>Name:*<br />
<input type="text" name="Name" value="" class="size1" /></p>
<p>E-Mail:*<br />
<input type="text" name="E-Mail" value="" class="size1" /></p>
</div>


<div style="float:right;">Mitteilung:*<br />
<textarea name="Nachricht" cols="40" rows="4"  class="size7"></textarea>
</div>

<p style="clear:both; text-align:right;"><input type="reset" name="reset" value="Zur&uuml;cksetzen" class="btstyle" style="width:100px;" />&nbsp;&nbsp;
<input type="submit" name="submit" value="Anfrage senden" class="btstyle" style="width:110px;" /></p>
<p style="margin:20px;" class="sub">* Pflichtangaben. Ihre Daten werden ausschlie&szlig;lich für diese Anfrage verwendet.</p>

</form>
</div>
</div>
 <script type="text/javascript" language="javascript">
<!--
	// Lösung ohne Onload
	toggleLayer('formular');
//-->
</script>
<br />





	<table width="97%" border="0" cellspacing="0" cellpadding="0">
		<tr>
			<td valign="bottom">	
			&copy; phpwcms-docu 2004-2015
			<img src="img/leer.gif" border="0" width="10" height="0" alt="" /><a href="impressum.phtml" class="phpwcmsIntLink"><img src="template/lang/all/icons/imprint.gif" width="9" height="15" alt="Impressum" title="Impressum" border="0" /></a>&nbsp; 
			<a href="sitemap_de.phtml" class="phpwcmsIntLink"><img src="template/lang/all/icons/sitemap.gif" width="19" height="15" alt="Sitemap" title="Sitemap" border="0" /></a>&nbsp; 
			<a href="gaestebuch.phtml" class="phpwcmsIntLink"><img src="template/lang/all/icons/gbook.gif" width="20" height="16" alt="Ins G&auml;stebuch eintragen" title="Ins G&auml;stebuch eintragen" border="0" /></a>&nbsp; 
			<a href="#" onclick="BookMark_Page();return false;" title="" class="phpwcmsBookmarkLink"><img src="template/lang/all/icons/favo.gif" width="12" height="15" alt="Seite als Bookmark speichern" title="Seite als Bookmark speichern" border="0" /></a>&nbsp; 
			     
			</td>
			<td valign="bottom" style="padding-right:25px;">
			
			
			
			</td>		
			<td width="150">
			</td>
		</tr>
	</table>
</div><br/>

</div>
</body>
</html>