<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<!--
	phpwcms | free open source content management system
	created by Oliver Georgi (oliver at phpwcms dot de) and licensed under GNU/GPL.
	phpwcms is copyright 2003-2007 of Oliver Georgi. Extensions are copyright of
	their respective owners. Visit project page for details: http://www.phpwcms.org/
//-->
<title>phpwcms-docu for  phpwcms :: web based content management system | Images{D:7/30/2007,30,newR.gif} | Content Part &quot;Images&quot;</title>
  <meta http-equiv="content-type" content="text/html; charset=iso-8859-1" />
  <meta http-equiv="content-style-type" content="text/css" />
  <script src="template/inc_js/frontend.js" type="text/javascript"></script>
  <style type="text/css">
  <!-- 
    @import url("template/inc_css/mpl_frontend.css");
    @import url("template/inc_css/mpl_menu.css");
    @import url("template/inc_css/mpl_objects.css");
    @import url("template/inc_css/mpl_docu_en.css");
  //-->
  </style>
<meta name="Title" content="The phpWCMS Documentation" />
<meta name="author" content="Oliver Frohnert, Mario Perez Leal" />
<meta name="Publisher" content="Oliver Frohnert, Mario Perez Leal, creacion" />
<meta name="Copyright" content="Oliver Frohnert, Mario Perez Leal, creacion" />
<meta name="keywords" content="frohnert, perez leal, creacion, documentation, dokumentation, phpwcms, cms, opensource, open source, docu" />
<meta name="description" content="A Documentation Project for the  Open Source CMS phpWCMS" />
<meta name="Audience" content="Alle" />
<meta name="Content-language" content="EN" />
<meta name="robots"      content="index,follow" />
<meta name="expires" content="0" />
<meta name="revisit-after" content="7 days" />
<meta name="resource-type" content="document" />
<meta name="distribution" content="Global" />
<meta name="generator" content="PHPWCMS" />
<meta name="verify-v1" content="1ZpxZ7AZsjm7PxjqXQVus0eiUYqOsp5URTJn9q4KNz8=" />
  <link rel="stylesheet" href="template/slimbox/css/slimbox.css" type="text/css" media="screen" />
  <script src="template/inc_js/mootools/mootools.js" type="text/javascript"></script>
  <script src="template/slimbox/js/slimbox.js" type="text/javascript"></script>
  <!--[if lt IE 7]>
  <style type="text/css">
    body { behavior: url("template/inc_css/specific/csshover2.htc"); }
    img { behavior: url("template/inc_css/specific/pngbehavior.htc"); }
  </style>
  <![endif]-->
</head>
<body id="myid_155">
<div id="container"><a name="top" id="top"></a>


	<div id="head">
		
	<div id="mainnavi">
		<div class="fleft"><a href="english_version.phtml">Home</a> | <a href="news_en.phtml">News</a> | <span style="text-decoration:none;font-weight:bold;"><a href="the_docu.phtml">The Docu</a></span> | <a href="Usefull_Links_and_Tools.phtml">Links &amp; Tools</a> | <a href="contact.phtml">Contact</a> | <a href="faq_en.phtml">FAQ</a> | <a href="http://forum.phpwcms.org/" target="_blank">Forum</a> | <a href="howto_en.phtml">HowTo</a></div>				
		<div class="sys">Saturday, 27. July 2013<img src="img/leer.gif" border="0" width="5" height="1" alt="" />|<img src="img/leer.gif" border="0" width="5" height="1" alt="" />4 User online<img src="img/leer.gif" border="0" width="10" height="1" alt="" />
		<a href="deutsche_version.phtml" title="Deutsche Version"><img src="picture/../template/lang/all/flag_de.gif" border="0" alt="" /></a>
		<a href="english_version.phtml"  title="English version"><img src="picture/../template/lang/all/flag_en.gif" border="0" alt="" /></a>
		</div>
	</div>
	
	<a href="./" title="phpwcms-docu Startseite aufrufen" class="homelink">
	<span>&raquo; phpwcms-docu startpage</span></a>
	<h2>phpwcms-docu - Documentation for the Web Content Management System phpwcms</h2>
	<p>This website is targeted both to the beginner and the lateral entry following the goal to simplify the 
work with phpwcms and to focus on the essentials things.</p>
	</div>

	
	<div id="left">
	<div class="leftnav" style="margin-top:24px;">
	
<div id="ul_div_311">
<ul>
	<li class="sub_no"><a href="download-dev-versions.phtml">Download Dev Versions</a></li>
	<li class="sub_no sub_ul_true"><a href="installation_en.phtml">Installation &amp; Upgrade</a></li>
	<li class="sub_ul"><a href="article.phtml">Articles</a>
	<div id="ul_div_116">
	<ul>
		<li class="sub_no"><a href="creating_articles.phtml">Creating Articles</a></li>
		<li class="sub_no"><a href="editing_articles.phtml">Editing Articles </a></li>
		<li class="sub_no sub_ul_true"><a href="article_organization.phtml">Article Organization</a></li>
		<li class="sub_ul"><a href="content_parts_en.phtml">Content Parts</a>
		<div id="ul_div_124">
		<ul>
			<li class="sub_no"><a href="content_part_plain_text.phtml">Plain Text</a></li>
			<li class="sub_no"><a href="content_part_html_en.phtml">Html</a></li>
			<li class="sub_no"><a href="content_part_wysiwyg_html_en.phtml">WYSIWYG HTML</a></li>
			<li class="sub_no"><a href="content_part_code_en.phtml">Code</a></li>
			<li class="sub_no"><a href="content_part_text_with_image.phtml">Text with image</a></li>
			<li class="sub_no active"><a href="content_part_images.phtml">Images</a></li>
			<li class="sub_no"><a href="content_part_images_div.phtml"><span style="text-decoration:line-through;font-size:10px;">Images &lt;DIV&gt;</span></a></li>
			<li class="sub_no"><a href="content_part_list_table.phtml">List (Table)</a></li>
			<li class="sub_no"><a href="content_part_list.phtml">List</a></li>
			<li class="sub_no"><a href="content_part_link_and_e-mail.phtml">Link &amp; E-Mail</a></li>
			<li class="sub_no"><a href="content_part_link_list.phtml">Link list</a></li>
			<li class="sub_no"><a href="content_part_link_article.phtml">Link article</a></li>
			<li class="sub_no"><a href="content_part_teaser_articlelink.phtml"><span style="text-decoration:line-through;font-size:10px;">Teaser / Articlelink</span></a></li>
			<li class="sub_no"><a href="content_part_article_menue.phtml">Article Menu</a></li>
			<li class="sub_no"><a href="content_part_multimedia_en.phtml">Multimedia</a></li>
			<li class="sub_no"><a href="content_part_file_list.phtml">File List</a></li>
			<li class="sub_no"><a href="content_part_ecard_en.phtml">E-Card</a></li>
			<li class="sub_no"><a href="content_part_form.phtml">Form</a></li>
			<li class="sub_no"><a href="content_part_e-mail_contact_form.phtml">Email contact form</a></li>
			<li class="sub_no sub_ul_true"><a href="content_part_email_form_generator.phtml">Email form generator[OLD]</a></li>
			<li class="sub_no"><a href="content_part_email_form.phtml">Email form</a></li>
			<li class="sub_no sub_ul_true"><a href="content_part_newsletter_en.phtml">Newsletter</a></li>
			<li class="sub_no"><a href="content_part_search.phtml">Search</a></li>
			<li class="sub_no sub_ul_true"><a href="content_part_guestbook_comment.phtml">Guestbook / Comm.</a></li>
			<li class="sub_no"><a href="content_part_sitemap_en.phtml">Sitemap</a></li>
			<li class="sub_no sub_ul_true"><a href="content_part_bid.phtml">Bid</a></li>
			<li class="sub_no"><a href="content_part_external_content.phtml">Ext. content</a></li>
			<li class="sub_no"><a href="content_part_rss_feed_en.phtml">RSS Feed</a></li>
			<li class="sub_no"><a href="content_part_rollover_images.phtml"><span style="text-decoration:line-through;font-size:10px;">Rollover images</span></a></li>
			<li class="sub_no"><a href="content_part_map.phtml"><span style="text-decoration:line-through;font-size:10px;">Map</span></a></li>
			<li class="sub_no"><a href="php_variables.phtml"><span style="text-decoration:line-through;font-size:10px;">PHP variables</span></a></li>
			<li class="sub_no"><a href="content_part_contentpart_alias_en.phtml">Contentpart Alias</a></li>
			<li class="sub_no"><a href="content_part_poll_en.phtml"><span style="text-decoration:line-through;font-size:10px;">Poll</span></a></li>
			<li class="sub_no"><a href="content_part_recipe.phtml"><span style="text-decoration:line-through;font-size:10px;">Recipe</span></a></li>
			<li class="sub_no"><a href="content_part_faq_en.phtml"><span style="text-decoration:line-through;font-size:10px;">FAQ</span></a></li>
			<li class="sub_no"><a href="content_part_frontend_login_en.phtml"><span style="text-decoration:line-through;font-size:10px;">Frontend Login</span></a></li>
			<li class="sub_no"><a href="content_part_glossary.phtml"><span style="text-decoration:line-through;font-size:10px;">Plug-in: Glossary</span></a></li>
		</ul>
		</div>
		</li>
	</ul>
	</div>
	</li>
	<li class="sub_no sub_ul_true"><a href="file.phtml">File</a></li>
	<li class="sub_no sub_ul_true"><a href="module_en.phtml">Modules</a></li>
	<li class="sub_no sub_ul_true"><a href="communication.phtml">Communication </a></li>
	<li class="sub_no"><a href="chat_en.phtml">Chat</a></li>
	<li class="sub_no"><a href="profile.phtml">Profile</a></li>
	<li class="sub_no sub_ul_true"><a href="admin_en_.phtml">Admin</a></li>
	<li class="sub_no sub_ul_true"><a href="add-ons-and-templates.phtml">Add On&#039;s and Templates</a></li>
	<li class="sub_no"><a href="deutsche_version.phtml?replacement_tags_en">Replacement Tags</a></li>
	<li class="sub_no"><a href="deutsche_version.phtml?content_parts_en">Content Parts</a></li>
</ul>
</div>

		
	</div> 
	</div> 
	  
	<div id="right">
		<div style="margin-top:24px;">			
		<form action="index.php?search" method="post" name="searchFE" onsubmit="s=document.getElementById('customSearchInput');if(s.value=='Search')return false;">
			<table width="100%" border="0" cellpadding="0" cellspacing="0">
			<tr>
					<td><input type="text" name="search_input_field" size="20" maxlength="200" id="customSearchInput" class="customSearchInput" value="" onfocus="if(this.value=='Search')this.value='';" onblur="if(this.value=='')this.value='Search';"/></td>
					<td><input type="image" name="search_go" onfocus="this.blur();" title="Search" src="/template/lang/all/submit.gif" /></td>
				</tr>
			</table>
			</form>
			
			      <script type="text/javascript" language="javascript">
			  <!-- 
			        document.getElementById("customSearchInput").value="Search";
			  //-->
			      </script>
				  
<!-- <p style="margin-top:10px;">Change font size: <a href="[FontSize-]"><img src="template/lang/all/icons/reduce.gif" width="18" height="17" alt="" title="Small" border="0" /></a>
			<a href="[FontSize+]"><img src="template/lang/all/icons/extend.gif" width="18" height="17" alt="" title="Bigger" border="0" /></a>
			</p> -->
			
	<p style="margin-top:10px;">Please choose: 
	
	 </p>

<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div>
<form action="https://www.paypal.com/cgi-bin/webscr" method="post">
<input type="hidden" name="cmd" value="_xclick" />
<input type="hidden" name="business" value="support@docu.fhss.de" />
<input type="hidden" name="item_name" value="phpwcms-docu.de" />
<input type="hidden" name="buyer_credit_promo_code" value="" />
<input type="hidden" name="buyer_credit_product_category" value="" />
<input type="hidden" name="buyer_credit_shipping_method" value="" />
<input type="hidden" name="buyer_credit_user_address_change" value="" />
<input type="hidden" name="no_shipping" value="0" />
<input type="hidden" name="no_note" value="1" />
<input type="hidden" name="currency_code" value="EUR" />
<input type="hidden" name="tax" value="0" />
<input type="hidden" name="lc" value="DE" />
<input type="hidden" name="bn" value="PP-DonationsBF" />
<input type="image" src="template/img/paypal.gif" name="submit" title="Make a donation ..." alt="Make a donation ..." />
<img alt="" border="0" src="https://www.paypal.com/de_DE/i/scr/pixel.gif" width="1" height="1" />
</form>
<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div>
<!-- <a href="http://validator.w3.org/check?uri=http%3A%2F%2Fwww.phpwcms-docu.de%2Findex.php%3Fdeutsche_version" title="W3C Standard XHTML" target="_blank"><img src="picture/w3c/w3c_xhtml.gif" border="0" alt="" /></a>
<a href="http://jigsaw.w3.org/css-validator/validator?uri=http://www.phpwcms-docu.de" title="W3C Standard CSS" target="_blank"><img src="picture/w3c/w3c_css.gif" border="0" alt="" /></a><br />			
<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div> -->
		
<div style="margin-top:10px; margin-bottom:15px;"></div>
	
</div>

	</div> 
	
	<div id="content">
	<div id="bread">You are here: <a href="english_version.phtml">English</a> <span class="breadcrumb_spacer">&gt;</span> <a href="the_docu.phtml">The Docu</a> <span class="breadcrumb_spacer">&gt;</span> <a href="article.phtml">Articles</a> <span class="breadcrumb_spacer">&gt;</span> <a href="content_parts_en.phtml">Content Parts</a> <span class="breadcrumb_spacer">&gt;</span> Images</div>
		
		<a name="jump347"></a><!-- Livedate: 24.08.2004 18:19:48 / Killdate: 31.12.2030 23:59:59 -->
<h1>Content Part &quot;Images&quot;</h1>

<div style="margin:25px 0 0 0;padding:0;" class="spaceBeforeCP"></div><table width="100%" cellpadding="0" cellspacing="0" border="0" class="imgTextRight">
<tr>
<td valign="top" width="10%" class="image_td2"><table width="150" border="0" cellspacing="0" cellpadding="0" >
<tr><td class="image_td2"><a href="content/images/0ce4b2626a0ebafba289f0f0e5f5eb49.png" rel="lightbox" title="Content Part &quot;images&quot;" target="_blank"><img src="content/images/222b152e95efaca67063ab81964a654d.png" width="150" height="168" border="0" class="image_img" alt="images.png" /></a></td></tr>
<tr><td align="center" class="image_caption">Content Part &quot;images&quot;</td></tr>
</table></td>
<td valign="top" class="articleText"><div align="left"><strong>image:</strong> Here the names of the selected images are listed. With the adjacent symbols, you can select new images for the list, delete from the list, and change the order within the list:&nbsp;<br />
<br />
<img src="picture/../img/button/open_image_button.gif" border="0" alt="" /> Click, in order to open the phpWCMS image browser (you can find more information on this in &quot;the phpwcms Browser&quot; section, further down) and select an image.&nbsp;<br />
<br />
<img src="picture/../img/button/image_pos_up.gif" border="0" alt="" /><img src="picture/../img/button/image_pos_down.gif" border="0" alt="" />&nbsp;Select in &quot;image&quot; the name of the image to be shifted and then click on one these symbols, in order to shift it&rsquo;s position upward and/or downward in the list of images.&nbsp;<br />
<br />
<img src="picture/../img/button/del_image_button.gif" border="0" alt="" /> Click, in order to remove the currently selected image.&nbsp;<br />
<br />
<strong>Position:</strong> With this option you determine how the image is to be placed with regards to the text block. You can either use the menu or the accompanying symbols:<br />
<br />
<img src="picture/../img/button/image_pos0.gif" border="0" alt="" /> Place image above the text block, aligned left. <br />
<img src="picture/../img/button/image_pos1.gif" border="0" alt="" /> Place image above the text block, centered. <br />
<img src="picture/../img/button/image_pos2.gif" border="0" alt="" /> Place image above the text block, aligned right. <br />
<img src="picture/../img/button/image_pos3.gif" border="0" alt="" /> Place image below the text block, aligned left. <br />
<img src="picture/../img/button/image_pos4.gif" border="0" alt="" /> Place image below the text block, centered. <br />
<img src="picture/../img/button/image_pos5.gif" border="0" alt="" /> Place image below the text block, aligned right. <br />
<img src="picture/../img/button/image_pos6.gif" border="0" alt="" /> Place image within the text block, aligned left. <br />
<img src="picture/../img/button/image_pos7.gif" border="0" alt="" /> Place image within the text block, aligned right.<br />
<br />
<strong>max. width/max. height:</strong> Here you can specify maximum width and/orheight of the image. If the actual image is larger than the maximum dimensions youspecify, then the image is automatically resized accordingly, whereby the proportionsremain intact. If you leave either or both of these fields empty, phpwcms uses themaximum dimension(/s) of the image, while maintaining proportionality. <br />
<br />
<strong>columns:</strong> Here you can indicate how many columns there shall be per row of images.&nbsp;<br />
<p align="left"><strong>image space:</strong> Here you can select how much space there should be <br />
between adjacent columns of images.</p>
<strong>click enlarge:</strong> With this option you can indicate whether the visitor can click on the image to open a view of the full-size image in a pop-up window.</div>
<div align="left"><strong><br />
</strong><strong>Lightbox</strong> (since version 1.3.3): With this option the image will not be opened in a new window, it will be opened in a layer. Please look for an example in <a href="./text_with_image.phtml" target="_blank">content part &quot; text with image&quot;</a>.<br />
<br />
<strong>Thumbnails without Caption</strong> (since Version 1.3.3): This setting does only work with the lightbox. It means that undeer the thumbnail image there will not shown a caption. But when you click on the image a caption will will shown under the big image view. You can also find an example in <a href="./text_with_image.phtml" target="_blank">content part &quot; text with image&quot;</a>.<br />
<br />
<strong><font color="#ff0000">Notice: For using this function Lightbox, check &quot;Click enlarge&quot;.</font></strong><br />
<strong><br />
</strong><strong>caption:</strong> Here you can enter a caption (a description of the image, for example), for each image, which will appear below each respective image. Please besure to consider the order of the images under &quot;image&quot; and enter each caption on a new line.</div></td>
</tr>
</table><div align="right"><a href="#top"><img src="img/article/top_link_0.gif" border="0" alt="" /></a></div>
		 
		
		<br /><br />
		<div class="sub">
		Article created: Tuesday, 24. July 2007 <br /> Last Changes: Tuesday, 4. January 2011	
		</div>
				
	</div>
	
<div id="footer"><br /><br />
<p style="height:30px;">&nbsp;</p>


 <script type="text/javascript" language="javascript">
<!--

var showDefaultValue =  0

function hideLayer(whichLayer) {
	if (document.getElementById) {
		// this is the way the standards work
		document.getElementById(whichLayer).style.display = "none";
	} else if (document.all) {
		// this is the way old msie versions work
		document.all[whichlayer].style.display = "none";
	} else if (document.layers) {
		// this is the way nn4 works
		document.layers[whichLayer].display = "none";
	}
}

function showLayer(whichLayer) {
		//	alert(whichLayer);
	if (document.getElementById) {
		// this is the way the standards work
		document.getElementById(whichLayer).style.display = "block";
	}
	else if (document.all) {
		// this is the way old msie versions work
		document.all[whichlayer].style.display = "block";
	}
	else if (document.layers) {
		// this is the way nn4 works
		document.layers[whichLayer].display = "block";
	}
}

function toggleLayer(whichLayer) {
	if(showDefaultValue == 0) {
		hideLayer(whichLayer);
		showDefaultValue = 1;
	} else {
		showLayer(whichLayer);
		showDefaultValue = 0;
	}
}
//-->
</script>


<div id="alles">
<div id="klapper" onclick="toggleLayer('formular');">
<table width="570" border="0" cellspacing="0" cellpadding="0">
<tr>
<td><em style="color:#275EA8;" onmouseover="this.style.color='#4F96F4';" onmouseout="this.style.color='#275EA8';">You have suggestions or criticism to this article? Write us!</em></td>   
<td align="right" style="padding-right:2px;"><img src="template/lang/all/icons/write.gif" width="16" height="21" alt="" border="0" /></td>
</tr>
</table>

</div>
<div id="formular">

<form name="form" method="post" action="index.php?id=155,347,0,1,1,0" style="margin:0;padding:0;"><input type="hidden" name="customForm" value="1" /><input type="hidden" name="docucheck" value="1" />


<div style="float:left;">
<p><select name="Betreff" id="Betreff" class="size1">
<option value="" class="deepblue"> Select </option>

</select><br /></p>


<p>Firstname:<br />
<input type="text" name="Vorname" value="" class="size1" /></p>
<p>Surname:*<br />
<input type="text" name="Name" value="" class="size1" /></p>
<p>E-Mail:*<br />
<input type="text" name="E-Mail" value="" class="size1" /></p>
</div>


<div style="float:right;">Message:*<br />
<textarea name="Nachricht" cols="40" rows="4"  class="size7"></textarea>
</div>

<p style="clear:both; text-align:right;"><input type="reset" name="reset" value="Reset" class="btstyle" style="width:100px;" />&nbsp;&nbsp;
<input type="submit" name="submit" value="Send email" class="btstyle" style="width:110px;" /></p>
<p style="margin:20px;" class="sub">* Required fields.<br />Your data is used exclusively for this inquiry.</p>

</form>
</div>
</div>
 <script type="text/javascript" language="javascript">
<!--
	// Lösung ohne Onload
	toggleLayer('formular');
//-->
</script>
<br />





	<table width="97%" border="0" cellspacing="0" cellpadding="0">
		<tr>
			<td valign="bottom">	
			&copy; phpwcms-docu 2004-2013
			<img src="img/leer.gif" border="0" width="10" height="0" alt="" /><a href="imprint.phtml" class="phpwcmsIntLink"><img src="template/lang/all/icons/imprint.gif" width="9" height="15" alt="Impressum" title="Impressum" border="0" /></a>&nbsp; 
			<a href="sitemap_en.phtml" class="phpwcmsIntLink"><img src="template/lang/all/icons/sitemap.gif" width="19" height="15" alt="Sitemap" title="Sitemap" border="0" /></a>&nbsp; 
			 
			
			     
			</td>
			<td valign="bottom" style="padding-right:25px;">
			
			
			
			</td>		
			<td width="150">
			</td>
		</tr>
	</table>
</div><br/>

</div>
</body>
</html>