<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<!--
	phpwcms | free open source content management system
	created by Oliver Georgi (oliver at phpwcms dot de) and licensed under GNU/GPL.
	phpwcms is copyright 2003-2007 of Oliver Georgi. Extensions are copyright of
	their respective owners. Visit project page for details: http://www.phpwcms.org/
//-->
<title>phpwcms-docu for  phpwcms :: web based content management system | Copy Content Part{D:7/30/2007,30,newR.gif} | Copy Content Part</title>
  <meta http-equiv="content-type" content="text/html; charset=iso-8859-1" />
  <meta http-equiv="content-style-type" content="text/css" />
  <script src="template/inc_js/frontend.js" type="text/javascript"></script>
  <style type="text/css">
  <!-- 
    @import url("template/inc_css/mpl_frontend.css");
    @import url("template/inc_css/mpl_menu.css");
    @import url("template/inc_css/mpl_objects.css");
    @import url("template/inc_css/mpl_docu_en.css");
  //-->
  </style>
<meta name="Title" content="The phpWCMS Documentation" />
<meta name="author" content="Oliver Frohnert, Mario Perez Leal" />
<meta name="Publisher" content="Oliver Frohnert, Mario Perez Leal, creacion" />
<meta name="Copyright" content="Oliver Frohnert, Mario Perez Leal, creacion" />
<meta name="keywords" content="frohnert, perez leal, creacion, documentation, dokumentation, phpwcms, cms, opensource, open source, docu" />
<meta name="description" content="A Documentation Project for the  Open Source CMS phpWCMS" />
<meta name="Audience" content="Alle" />
<meta name="Content-language" content="EN" />
<meta name="robots"      content="index,follow" />
<meta name="expires" content="0" />
<meta name="revisit-after" content="7 days" />
<meta name="resource-type" content="document" />
<meta name="distribution" content="Global" />
<meta name="generator" content="PHPWCMS" />
<meta name="verify-v1" content="1ZpxZ7AZsjm7PxjqXQVus0eiUYqOsp5URTJn9q4KNz8=" />
  <!--[if lt IE 7]>
  <style type="text/css">
    body { behavior: url("template/inc_css/specific/csshover2.htc"); }
    img { behavior: url("template/inc_css/specific/pngbehavior.htc"); }
  </style>
  <![endif]-->
</head>
<body id="myid_374">
<div id="container"><a name="top" id="top"></a>


	<div id="head">
		
	<div id="mainnavi">
		<div class="fleft"><a href="english_version.phtml">Home</a> | <a href="news_en.phtml">News</a> | <span style="text-decoration:none;font-weight:bold;"><a href="the_docu.phtml">The Docu</a></span> | <a href="Usefull_Links_and_Tools.phtml">Links &amp; Tools</a> | <a href="contact.phtml">Contact</a> | <a href="faq_en.phtml">FAQ</a> | <a href="http://forum.phpwcms.org/" target="_blank">Forum</a> | <a href="howto_en.phtml">HowTo</a></div>				
		<div class="sys">Saturday, 27. July 2013<img src="img/leer.gif" border="0" width="5" height="1" alt="" />|<img src="img/leer.gif" border="0" width="5" height="1" alt="" />3 User online<img src="img/leer.gif" border="0" width="10" height="1" alt="" />
		<a href="deutsche_version.phtml" title="Deutsche Version"><img src="picture/../template/lang/all/flag_de.gif" border="0" alt="" /></a>
		<a href="english_version.phtml"  title="English version"><img src="picture/../template/lang/all/flag_en.gif" border="0" alt="" /></a>
		</div>
	</div>
	
	<a href="./" title="phpwcms-docu Startseite aufrufen" class="homelink">
	<span>&raquo; phpwcms-docu startpage</span></a>
	<h2>phpwcms-docu - Documentation for the Web Content Management System phpwcms</h2>
	<p>This website is targeted both to the beginner and the lateral entry following the goal to simplify the 
work with phpwcms and to focus on the essentials things.</p>
	</div>

	
	<div id="left">
	<div class="leftnav" style="margin-top:24px;">
	
<div id="ul_div_311">
<ul>
	<li class="sub_no"><a href="download-dev-versions.phtml">Download Dev Versions</a></li>
	<li class="sub_no sub_ul_true"><a href="installation_en.phtml">Installation &amp; Upgrade</a></li>
	<li class="sub_ul"><a href="article.phtml">Articles</a>
	<div id="ul_div_116">
	<ul>
		<li class="sub_no"><a href="creating_articles.phtml">Creating Articles</a></li>
		<li class="sub_no"><a href="editing_articles.phtml">Editing Articles </a></li>
		<li class="sub_ul"><a href="article_organization.phtml">Article Organization</a>
		<div id="ul_div_118">
		<ul>
			<li class="sub_no"><a href="copy_article.phtml">Copy Article</a></li>
			<li class="sub_no"><a href="move_article.phtml">Move Article</a></li>
			<li class="sub_no active"><a href="copy_content_part.phtml">Copy Content Part</a></li>
			<li class="sub_no"><a href="Move_Content_Part.phtml">Move Content Part</a></li>
		</ul>
		</div>
		</li>
		<li class="sub_no sub_ul_true"><a href="content_parts_en.phtml">Content Parts</a></li>
	</ul>
	</div>
	</li>
	<li class="sub_no sub_ul_true"><a href="file.phtml">File</a></li>
	<li class="sub_no sub_ul_true"><a href="module_en.phtml">Modules</a></li>
	<li class="sub_no sub_ul_true"><a href="communication.phtml">Communication </a></li>
	<li class="sub_no"><a href="chat_en.phtml">Chat</a></li>
	<li class="sub_no"><a href="profile.phtml">Profile</a></li>
	<li class="sub_no sub_ul_true"><a href="admin_en_.phtml">Admin</a></li>
	<li class="sub_no sub_ul_true"><a href="add-ons-and-templates.phtml">Add On&#039;s and Templates</a></li>
	<li class="sub_no"><a href="deutsche_version.phtml?replacement_tags_en">Replacement Tags</a></li>
	<li class="sub_no"><a href="deutsche_version.phtml?content_parts_en">Content Parts</a></li>
</ul>
</div>

		
	</div> 
	</div> 
	  
	<div id="right">
		<div style="margin-top:24px;">			
		<form action="index.php?search" method="post" name="searchFE" onsubmit="s=document.getElementById('customSearchInput');if(s.value=='Search')return false;">
			<table width="100%" border="0" cellpadding="0" cellspacing="0">
			<tr>
					<td><input type="text" name="search_input_field" size="20" maxlength="200" id="customSearchInput" class="customSearchInput" value="" onfocus="if(this.value=='Search')this.value='';" onblur="if(this.value=='')this.value='Search';"/></td>
					<td><input type="image" name="search_go" onfocus="this.blur();" title="Search" src="/template/lang/all/submit.gif" /></td>
				</tr>
			</table>
			</form>
			
			      <script type="text/javascript" language="javascript">
			  <!-- 
			        document.getElementById("customSearchInput").value="Search";
			  //-->
			      </script>
				  
<!-- <p style="margin-top:10px;">Change font size: <a href="[FontSize-]"><img src="template/lang/all/icons/reduce.gif" width="18" height="17" alt="" title="Small" border="0" /></a>
			<a href="[FontSize+]"><img src="template/lang/all/icons/extend.gif" width="18" height="17" alt="" title="Bigger" border="0" /></a>
			</p> -->
			
	<p style="margin-top:10px;">Please choose: 
	
	 </p>

<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div>
<form action="https://www.paypal.com/cgi-bin/webscr" method="post">
<input type="hidden" name="cmd" value="_xclick" />
<input type="hidden" name="business" value="support@docu.fhss.de" />
<input type="hidden" name="item_name" value="phpwcms-docu.de" />
<input type="hidden" name="buyer_credit_promo_code" value="" />
<input type="hidden" name="buyer_credit_product_category" value="" />
<input type="hidden" name="buyer_credit_shipping_method" value="" />
<input type="hidden" name="buyer_credit_user_address_change" value="" />
<input type="hidden" name="no_shipping" value="0" />
<input type="hidden" name="no_note" value="1" />
<input type="hidden" name="currency_code" value="EUR" />
<input type="hidden" name="tax" value="0" />
<input type="hidden" name="lc" value="DE" />
<input type="hidden" name="bn" value="PP-DonationsBF" />
<input type="image" src="template/img/paypal.gif" name="submit" title="Make a donation ..." alt="Make a donation ..." />
<img alt="" border="0" src="https://www.paypal.com/de_DE/i/scr/pixel.gif" width="1" height="1" />
</form>
<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div>
<!-- <a href="http://validator.w3.org/check?uri=http%3A%2F%2Fwww.phpwcms-docu.de%2Findex.php%3Fdeutsche_version" title="W3C Standard XHTML" target="_blank"><img src="picture/w3c/w3c_xhtml.gif" border="0" alt="" /></a>
<a href="http://jigsaw.w3.org/css-validator/validator?uri=http://www.phpwcms-docu.de" title="W3C Standard CSS" target="_blank"><img src="picture/w3c/w3c_css.gif" border="0" alt="" /></a><br />			
<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div> -->
		
<div style="margin-top:10px; margin-bottom:15px;"></div>
	
</div>

	</div> 
	
	<div id="content">
	<div id="bread">You are here: <a href="english_version.phtml">English</a> <span class="breadcrumb_spacer">&gt;</span> <a href="the_docu.phtml">The Docu</a> <span class="breadcrumb_spacer">&gt;</span> <a href="article.phtml">Articles</a> <span class="breadcrumb_spacer">&gt;</span> <a href="article_organization.phtml">Article Organization</a> <span class="breadcrumb_spacer">&gt;</span> Copy Content Part</div>
		
		<a name="jump338"></a><!-- Livedate: 14.12.2005 06:05:46 / Killdate: 31.12.2030 23:59:59 -->
<h1>Copy Content Part</h1>

<p>There are two possibilities to copy content parts. <br />
<br />
First you can copy a content part in an other Article and second you can also copy a content part inside an article.<br />
<br />
First will will show you how you can copy a CP into an other Article.</p><div style="border-bottom:1px dotted #d2e2f5; margin-top:10px; margin-bottom:15px;"></div><h3>Copy a CP into an other Article</h3><div class="articleText"><p>Start as follows: <br />
<br />
Go to the article center.<br />
<br />
Press&nbsp;<img alt="" src="./img/symbole/plus_open.gif" /> in front of the article <img src="./upgrade/img/symbole/text_1.gif" alt="" /> to go to the content part overview in the case you do not already see the CP overview. <br />
<br />
Choose now the CP <img src="./upgrade/img/symbole/content_9x11.gif" alt="" /> that you want to copy. Behind the CP you can find the following symbol <img align="bottom" src="./img/button/copy_11x11_0.gif" alt="" /> . By pressing this symbol you will mark this CP to copy it. After pressing the symbol it changes to<img align="bottom" src="./img/button/copy_11x11_9.gif" alt="" /> and the line gets marked with an orange bar that also shows that the CP is marked for a copy action. (Image 1)</p></div><table width="538" border="0" cellspacing="0" cellpadding="0" align="center">
<tr><td><img src="img/leer.gif" width="1" height="5" border="0" alt="" /></td></tr>
<tr><td class="image_td2"><img src="content/images/3ef063d43a84ec942986274d49080083.png" width="538" height="122" border="0" class="image_img" alt="cp_copy_v1_1.png" /></td></tr>
<tr><td align="center" class="image_caption">Image 1</td></tr>
</table><div class="articleText"><p align="justify">Now you will see a green arrow at every structure level <img src="./img/button/copy_11x11_1.gif" alt="" />. It shows you that there it is possible to insert your selected content part. <br />
<br />
By pressing the green arrow <img alt="" src="./img/button/copy_11x11_1.gif" /> you insert the content part into the selected article. As an orientation help the line is marked light green. (Image 2)</p></div><table width="538" border="0" cellspacing="0" cellpadding="0" align="center">
<tr><td><img src="img/leer.gif" width="1" height="5" border="0" alt="" /></td></tr>
<tr><td class="image_td2"><img src="content/images/f902aebf4593b407059c9a494f60f3b5.png" width="538" height="122" border="0" class="image_img" alt="cp_copy_v1_2.png" /></td></tr>
<tr><td align="center" class="image_caption">Image 2</td></tr>
</table><div class="articleText"><p>You can now see that the CP has been inserted in the your selected article. (Image 3)</p></div><table width="538" border="0" cellspacing="0" cellpadding="0" align="center">
<tr><td><img src="img/leer.gif" width="1" height="5" border="0" alt="" /></td></tr>
<tr><td class="image_td2"><img src="content/images/0234bbbd32b1230c2642da800a835797.png" width="538" height="122" border="0" class="image_img" alt="cp_copy_v1_3.png" /></td></tr>
<tr><td align="center" class="image_caption">Image 3</td></tr>
</table><p align="justify">At the end press once more&nbsp;<img align="bottom" src="./img/button/copy_11x11_9.gif" alt="" /> of the content part that you have copied. In this way you will leave the copy mode for this content part. The green Mark of the article changes to white and the symbol changes again to <img align="bottom" src="./img/button/copy_11x11_0.gif" alt="" />.</p><div align="right"><a href="#top"><img src="img/article/top_link_0.gif" border="0" alt="" /></a></div><div style="border-bottom:1px dotted #d2e2f5; margin-top:10px; margin-bottom:15px;"></div><h3>Copy a content part inside an article</h3><div class="articleText"><p>Start as follows: <br />
<br />
Go to the article so that you can see the CP overview.</p></div><table width="426" border="0" cellspacing="0" cellpadding="0" align="center">
<tr><td><img src="img/leer.gif" width="1" height="5" border="0" alt="" /></td></tr>
<tr><td class="image_td2"><img src="content/images/5c0a4c84732a1b449caf674a78935e37.png" width="426" height="200" border="0" class="image_img" alt="cp_copy_v2_1.png" /></td></tr>
<tr><td align="center" class="image_caption">Content Part Overview inside of the Article</td></tr>
</table><div align="right"><a href="#top"><img src="img/article/top_link_0.gif" border="0" alt="" /></a></div><div style="margin:10px 0 0 0;padding:0;" class="spaceBeforeCP"></div><div class="articleText"><p>By pressing <img align="bottom" src="./img/button/copy_13x13.gif" alt="" /> you select to CP f&uuml;r copy mode. A new windows will be opened demanding for confirming the copy job. Confirm with <strong>OK</strong>, if you don't want to copy the CP, press <strong>Cancel</strong>.<br />
<br />
After pressing <strong>OK</strong> to are coming back to the normal CP overview and you can see that the CP has been copied..</p></div><table width="426" border="0" cellspacing="0" cellpadding="0" align="center">
<tr><td><img src="img/leer.gif" width="1" height="5" border="0" alt="" /></td></tr>
<tr><td class="image_td2"><a href="zoom/OGQ3NTNmNTMyN2I0MGIzYzdjNTU1YzMzMWI2Y2MzOTQucG5nP3dpZHRoPSI4MDAiIGhlaWdodD0iMzc0Ig.html" onclick="checkClickZoom();clickZoom('zoom/OGQ3NTNmNTMyN2I0MGIzYzdjNTU1YzMzMWI2Y2MzOTQucG5nP3dpZHRoPSI4MDAiIGhlaWdodD0iMzc0Ig.html','previewpic','width.html');return false;.html"><img src="content/images/3cf65abeb851813520b7044e09f52840.png" width="426" height="200" border="0" class="image_img" alt="cp_copy_v2_2.png" /></a></td></tr>
<tr><td align="center" class="image_caption">Message whether the content part shall be copied</td></tr>
</table><div align="right"><a href="#top"><img src="img/article/top_link_0.gif" border="0" alt="" /></a></div><div style="margin:10px 0 0 0;padding:0;" class="spaceBeforeCP"></div><table width="388" border="0" cellspacing="0" cellpadding="0" align="center">
<tr><td><img src="img/leer.gif" width="1" height="5" border="0" alt="" /></td></tr>
<tr><td class="image_td2"><a href="zoom/MzdmY2QwZjg2Y2RjYzk4MjlmMDE3NjY3ZjM2MjJmZjEucG5nP3dpZHRoPSI4MDAiIGhlaWdodD0iNDExIg.html" onclick="checkClickZoom();clickZoom('zoom/MzdmY2QwZjg2Y2RjYzk4MjlmMDE3NjY3ZjM2MjJmZjEucG5nP3dpZHRoPSI4MDAiIGhlaWdodD0iNDExIg.html','previewpic','width.html');return false;.html"><img src="content/images/4608fb4933e10fd24185768c74ae1fd1.png" width="388" height="200" border="0" class="image_img" alt="cp_copy_v2_3.png" /></a></td></tr>
<tr><td align="center" class="image_caption">View after the content part has been copied</td></tr>
</table><div align="right"><a href="#top"><img src="img/article/top_link_0.gif" border="0" alt="" /></a></div>
		 
		
		<br /><br />
		<div class="sub">
		Article created: Saturday, 21. July 2007 <br /> Last Changes: Tuesday, 4. January 2011	
		</div>
				
	</div>
	
<div id="footer"><br /><br />
<p style="height:30px;">&nbsp;</p>


 <script type="text/javascript" language="javascript">
<!--

var showDefaultValue =  0

function hideLayer(whichLayer) {
	if (document.getElementById) {
		// this is the way the standards work
		document.getElementById(whichLayer).style.display = "none";
	} else if (document.all) {
		// this is the way old msie versions work
		document.all[whichlayer].style.display = "none";
	} else if (document.layers) {
		// this is the way nn4 works
		document.layers[whichLayer].display = "none";
	}
}

function showLayer(whichLayer) {
		//	alert(whichLayer);
	if (document.getElementById) {
		// this is the way the standards work
		document.getElementById(whichLayer).style.display = "block";
	}
	else if (document.all) {
		// this is the way old msie versions work
		document.all[whichlayer].style.display = "block";
	}
	else if (document.layers) {
		// this is the way nn4 works
		document.layers[whichLayer].display = "block";
	}
}

function toggleLayer(whichLayer) {
	if(showDefaultValue == 0) {
		hideLayer(whichLayer);
		showDefaultValue = 1;
	} else {
		showLayer(whichLayer);
		showDefaultValue = 0;
	}
}
//-->
</script>


<div id="alles">
<div id="klapper" onclick="toggleLayer('formular');">
<table width="570" border="0" cellspacing="0" cellpadding="0">
<tr>
<td><em style="color:#275EA8;" onmouseover="this.style.color='#4F96F4';" onmouseout="this.style.color='#275EA8';">You have suggestions or criticism to this article? Write us!</em></td>   
<td align="right" style="padding-right:2px;"><img src="template/lang/all/icons/write.gif" width="16" height="21" alt="" border="0" /></td>
</tr>
</table>

</div>
<div id="formular">

<form name="form" method="post" action="index.php?id=374,338,0,1,1,0" style="margin:0;padding:0;"><input type="hidden" name="customForm" value="1" /><input type="hidden" name="docucheck" value="1" />


<div style="float:left;">
<p><select name="Betreff" id="Betreff" class="size1">
<option value="" class="deepblue"> Select </option>

</select><br /></p>


<p>Firstname:<br />
<input type="text" name="Vorname" value="" class="size1" /></p>
<p>Surname:*<br />
<input type="text" name="Name" value="" class="size1" /></p>
<p>E-Mail:*<br />
<input type="text" name="E-Mail" value="" class="size1" /></p>
</div>


<div style="float:right;">Message:*<br />
<textarea name="Nachricht" cols="40" rows="4"  class="size7"></textarea>
</div>

<p style="clear:both; text-align:right;"><input type="reset" name="reset" value="Reset" class="btstyle" style="width:100px;" />&nbsp;&nbsp;
<input type="submit" name="submit" value="Send email" class="btstyle" style="width:110px;" /></p>
<p style="margin:20px;" class="sub">* Required fields.<br />Your data is used exclusively for this inquiry.</p>

</form>
</div>
</div>
 <script type="text/javascript" language="javascript">
<!--
	// Lösung ohne Onload
	toggleLayer('formular');
//-->
</script>
<br />





	<table width="97%" border="0" cellspacing="0" cellpadding="0">
		<tr>
			<td valign="bottom">	
			&copy; phpwcms-docu 2004-2013
			<img src="img/leer.gif" border="0" width="10" height="0" alt="" /><a href="imprint.phtml" class="phpwcmsIntLink"><img src="template/lang/all/icons/imprint.gif" width="9" height="15" alt="Impressum" title="Impressum" border="0" /></a>&nbsp; 
			<a href="sitemap_en.phtml" class="phpwcmsIntLink"><img src="template/lang/all/icons/sitemap.gif" width="19" height="15" alt="Sitemap" title="Sitemap" border="0" /></a>&nbsp; 
			 
			
			     
			</td>
			<td valign="bottom" style="padding-right:25px;">
			
			
			
			</td>		
			<td width="150">
			</td>
		</tr>
	</table>
</div><br/>

</div>
</body>
</html>