<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<!--
	phpwcms | free open source content management system
	created by Oliver Georgi (oliver at phpwcms dot de) and licensed under GNU/GPL.
	phpwcms is copyright 2003-2007 of Oliver Georgi. Extensions are copyright of
	their respective owners. Visit project page for details: http://www.phpwcms.org/
//-->
<title>phpwcms-docu for  phpwcms :: web based content management system | Copy Article{D:12/15/2005,30,newR.gif} | Copy Articles</title>
  <meta http-equiv="content-type" content="text/html; charset=iso-8859-1" />
  <meta http-equiv="content-style-type" content="text/css" />
  <script src="template/inc_js/frontend.js" type="text/javascript"></script>
  <style type="text/css">
  <!-- 
    @import url("template/inc_css/mpl_frontend.css");
    @import url("template/inc_css/mpl_menu.css");
    @import url("template/inc_css/mpl_objects.css");
    @import url("template/inc_css/mpl_docu_en.css");
  //-->
  </style>
<meta name="Title" content="The phpWCMS Documentation" />
<meta name="author" content="Oliver Frohnert, Mario Perez Leal" />
<meta name="Publisher" content="Oliver Frohnert, Mario Perez Leal, creacion" />
<meta name="Copyright" content="Oliver Frohnert, Mario Perez Leal, creacion" />
<meta name="keywords" content="frohnert, perez leal, creacion, documentation, dokumentation, phpwcms, cms, opensource, open source, docu" />
<meta name="description" content="A Documentation Project for the  Open Source CMS phpWCMS" />
<meta name="Audience" content="Alle" />
<meta name="Content-language" content="EN" />
<meta name="robots"      content="index,follow" />
<meta name="expires" content="0" />
<meta name="revisit-after" content="7 days" />
<meta name="resource-type" content="document" />
<meta name="distribution" content="Global" />
<meta name="generator" content="PHPWCMS" />
<meta name="verify-v1" content="1ZpxZ7AZsjm7PxjqXQVus0eiUYqOsp5URTJn9q4KNz8=" />
  <!--[if lt IE 7]>
  <style type="text/css">
    body { behavior: url("template/inc_css/specific/csshover2.htc"); }
    img { behavior: url("template/inc_css/specific/pngbehavior.htc"); }
  </style>
  <![endif]-->
</head>
<body id="myid_366">
<div id="container"><a name="top" id="top"></a>


	<div id="head">
		
	<div id="mainnavi">
		<div class="fleft"><a href="english_version.phtml">Home</a> | <a href="news_en.phtml">News</a> | <span style="text-decoration:none;font-weight:bold;"><a href="the_docu.phtml">The Docu</a></span> | <a href="Usefull_Links_and_Tools.phtml">Links &amp; Tools</a> | <a href="contact.phtml">Contact</a> | <a href="faq_en.phtml">FAQ</a> | <a href="http://forum.phpwcms.org/" target="_blank">Forum</a> | <a href="howto_en.phtml">HowTo</a></div>				
		<div class="sys">Saturday, 27. July 2013<img src="img/leer.gif" border="0" width="5" height="1" alt="" />|<img src="img/leer.gif" border="0" width="5" height="1" alt="" />5 User online<img src="img/leer.gif" border="0" width="10" height="1" alt="" />
		<a href="deutsche_version.phtml" title="Deutsche Version"><img src="picture/../template/lang/all/flag_de.gif" border="0" alt="" /></a>
		<a href="english_version.phtml"  title="English version"><img src="picture/../template/lang/all/flag_en.gif" border="0" alt="" /></a>
		</div>
	</div>
	
	<a href="./" title="phpwcms-docu Startseite aufrufen" class="homelink">
	<span>&raquo; phpwcms-docu startpage</span></a>
	<h2>phpwcms-docu - Documentation for the Web Content Management System phpwcms</h2>
	<p>This website is targeted both to the beginner and the lateral entry following the goal to simplify the 
work with phpwcms and to focus on the essentials things.</p>
	</div>

	
	<div id="left">
	<div class="leftnav" style="margin-top:24px;">
	
<div id="ul_div_311">
<ul>
	<li class="sub_no"><a href="download-dev-versions.phtml">Download Dev Versions</a></li>
	<li class="sub_no sub_ul_true"><a href="installation_en.phtml">Installation &amp; Upgrade</a></li>
	<li class="sub_ul"><a href="article.phtml">Articles</a>
	<div id="ul_div_116">
	<ul>
		<li class="sub_no"><a href="creating_articles.phtml">Creating Articles</a></li>
		<li class="sub_no"><a href="editing_articles.phtml">Editing Articles </a></li>
		<li class="sub_ul"><a href="article_organization.phtml">Article Organization</a>
		<div id="ul_div_118">
		<ul>
			<li class="sub_no active"><a href="copy_article.phtml">Copy Article</a></li>
			<li class="sub_no"><a href="move_article.phtml">Move Article</a></li>
			<li class="sub_no"><a href="copy_content_part.phtml">Copy Content Part</a></li>
			<li class="sub_no"><a href="Move_Content_Part.phtml">Move Content Part</a></li>
		</ul>
		</div>
		</li>
		<li class="sub_no sub_ul_true"><a href="content_parts_en.phtml">Content Parts</a></li>
	</ul>
	</div>
	</li>
	<li class="sub_no sub_ul_true"><a href="file.phtml">File</a></li>
	<li class="sub_no sub_ul_true"><a href="module_en.phtml">Modules</a></li>
	<li class="sub_no sub_ul_true"><a href="communication.phtml">Communication </a></li>
	<li class="sub_no"><a href="chat_en.phtml">Chat</a></li>
	<li class="sub_no"><a href="profile.phtml">Profile</a></li>
	<li class="sub_no sub_ul_true"><a href="admin_en_.phtml">Admin</a></li>
	<li class="sub_no sub_ul_true"><a href="add-ons-and-templates.phtml">Add On&#039;s and Templates</a></li>
	<li class="sub_no"><a href="deutsche_version.phtml?replacement_tags_en">Replacement Tags</a></li>
	<li class="sub_no"><a href="deutsche_version.phtml?content_parts_en">Content Parts</a></li>
</ul>
</div>

		
	</div> 
	</div> 
	  
	<div id="right">
		<div style="margin-top:24px;">			
		<form action="index.php?search" method="post" name="searchFE" onsubmit="s=document.getElementById('customSearchInput');if(s.value=='Search')return false;">
			<table width="100%" border="0" cellpadding="0" cellspacing="0">
			<tr>
					<td><input type="text" name="search_input_field" size="20" maxlength="200" id="customSearchInput" class="customSearchInput" value="" onfocus="if(this.value=='Search')this.value='';" onblur="if(this.value=='')this.value='Search';"/></td>
					<td><input type="image" name="search_go" onfocus="this.blur();" title="Search" src="/template/lang/all/submit.gif" /></td>
				</tr>
			</table>
			</form>
			
			      <script type="text/javascript" language="javascript">
			  <!-- 
			        document.getElementById("customSearchInput").value="Search";
			  //-->
			      </script>
				  
<!-- <p style="margin-top:10px;">Change font size: <a href="[FontSize-]"><img src="template/lang/all/icons/reduce.gif" width="18" height="17" alt="" title="Small" border="0" /></a>
			<a href="[FontSize+]"><img src="template/lang/all/icons/extend.gif" width="18" height="17" alt="" title="Bigger" border="0" /></a>
			</p> -->
			
	<p style="margin-top:10px;">Please choose: 
	
	 </p>

<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div>
<form action="https://www.paypal.com/cgi-bin/webscr" method="post">
<input type="hidden" name="cmd" value="_xclick" />
<input type="hidden" name="business" value="support@docu.fhss.de" />
<input type="hidden" name="item_name" value="phpwcms-docu.de" />
<input type="hidden" name="buyer_credit_promo_code" value="" />
<input type="hidden" name="buyer_credit_product_category" value="" />
<input type="hidden" name="buyer_credit_shipping_method" value="" />
<input type="hidden" name="buyer_credit_user_address_change" value="" />
<input type="hidden" name="no_shipping" value="0" />
<input type="hidden" name="no_note" value="1" />
<input type="hidden" name="currency_code" value="EUR" />
<input type="hidden" name="tax" value="0" />
<input type="hidden" name="lc" value="DE" />
<input type="hidden" name="bn" value="PP-DonationsBF" />
<input type="image" src="template/img/paypal.gif" name="submit" title="Make a donation ..." alt="Make a donation ..." />
<img alt="" border="0" src="https://www.paypal.com/de_DE/i/scr/pixel.gif" width="1" height="1" />
</form>
<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div>
<!-- <a href="http://validator.w3.org/check?uri=http%3A%2F%2Fwww.phpwcms-docu.de%2Findex.php%3Fdeutsche_version" title="W3C Standard XHTML" target="_blank"><img src="picture/w3c/w3c_xhtml.gif" border="0" alt="" /></a>
<a href="http://jigsaw.w3.org/css-validator/validator?uri=http://www.phpwcms-docu.de" title="W3C Standard CSS" target="_blank"><img src="picture/w3c/w3c_css.gif" border="0" alt="" /></a><br />			
<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div> -->
		
<div style="margin-top:10px; margin-bottom:15px;"></div>
	
</div>

	</div> 
	
	<div id="content">
	<div id="bread">You are here: <a href="english_version.phtml">English</a> <span class="breadcrumb_spacer">&gt;</span> <a href="the_docu.phtml">The Docu</a> <span class="breadcrumb_spacer">&gt;</span> <a href="article.phtml">Articles</a> <span class="breadcrumb_spacer">&gt;</span> <a href="article_organization.phtml">Article Organization</a> <span class="breadcrumb_spacer">&gt;</span> Copy Article</div>
		
		<a name="jump316"></a><!-- Livedate: 14.12.2005 06:05:46 / Killdate: 31.12.2030 23:59:59 -->
<h1>Copy Articles</h1>

<div style="margin:10px 0 0 0;padding:0;" class="spaceBeforeCP"></div><div class="articleText"><p align="justify">When you want to copy an article into an other structure level, please proceed this way: <br />
<br />
1. Go to the article center<br />
<br />
2. Click on the icon <img src="picture/../img/button/copy_11x11_0.gif" border="0" alt="" /> of the article to move. The icon changes to <img src="picture/../img/button/copy_11x11_3.gif" border="0" alt="" /> and the line will be marked with a green bar to show that the desired article has been chosen.</p></div><table width="538" border="0" cellspacing="0" cellpadding="0" align="center">
<tr><td><img src="img/leer.gif" width="1" height="5" border="0" alt="" /></td></tr>
<tr><td class="image_td2"><img src="content/images/c2f34b4930f2d253b4881f43ce13e92f.png" width="538" height="123" border="0" class="image_img" alt="copy_article_1.png" /></td></tr>
</table><div class="articleText"><p align="justify">Now you can see a green arrow at every structure level <img src="./img/button/copy_11x11_1.gif" alt="" />, this will show you that you can insert the chosen article at this place. <br />
<br />
With a click on the green arrow you can insert the article into the desired structure level. As an orientation guide the line will be marked bright green.</p></div><table width="538" border="0" cellspacing="0" cellpadding="0" align="center">
<tr><td><img src="img/leer.gif" width="1" height="5" border="0" alt="" /></td></tr>
<tr><td class="image_td2"><img src="content/images/dcb5034475ea576c03c28e453adad6e6.png" width="538" height="123" border="0" class="image_img" alt="copy_article_2.png" /></td></tr>
</table><div class="articleText"><p>Now you can see that the article has been inserted into the desired level.</p></div><table width="538" border="0" cellspacing="0" cellpadding="0" align="center">
<tr><td><img src="img/leer.gif" width="1" height="5" border="0" alt="" /></td></tr>
<tr><td class="image_td2"><img src="content/images/a90c6fd9b96ddf0a7c057a90284de6f2.png" width="538" height="123" border="0" class="image_img" alt="copy_article_3.png" /></td></tr>
</table><p align="justify">At least you have once more to click onto the following icon&nbsp;<img alt="" src="./img/button/copy_11x11_3.gif" align="absMiddle" />&nbsp;of the copied article. Thus you leave the copy mode for this article. Die green mark of the article changes again to white and the icon will be again&nbsp;<img alt="" src="./img/button/copy_11x11_0.gif" align="absMiddle" />.</p><div align="right"><a href="#top"><img src="img/article/top_link_0.gif" border="0" alt="" /></a></div>
		 
		
		<br /><br />
		<div class="sub">
		Article created: Thursday, 15. December 2005 <br /> Last Changes: Tuesday, 4. January 2011	
		</div>
				
	</div>
	
<div id="footer"><br /><br />
<p style="height:30px;">&nbsp;</p>


 <script type="text/javascript" language="javascript">
<!--

var showDefaultValue =  0

function hideLayer(whichLayer) {
	if (document.getElementById) {
		// this is the way the standards work
		document.getElementById(whichLayer).style.display = "none";
	} else if (document.all) {
		// this is the way old msie versions work
		document.all[whichlayer].style.display = "none";
	} else if (document.layers) {
		// this is the way nn4 works
		document.layers[whichLayer].display = "none";
	}
}

function showLayer(whichLayer) {
		//	alert(whichLayer);
	if (document.getElementById) {
		// this is the way the standards work
		document.getElementById(whichLayer).style.display = "block";
	}
	else if (document.all) {
		// this is the way old msie versions work
		document.all[whichlayer].style.display = "block";
	}
	else if (document.layers) {
		// this is the way nn4 works
		document.layers[whichLayer].display = "block";
	}
}

function toggleLayer(whichLayer) {
	if(showDefaultValue == 0) {
		hideLayer(whichLayer);
		showDefaultValue = 1;
	} else {
		showLayer(whichLayer);
		showDefaultValue = 0;
	}
}
//-->
</script>


<div id="alles">
<div id="klapper" onclick="toggleLayer('formular');">
<table width="570" border="0" cellspacing="0" cellpadding="0">
<tr>
<td><em style="color:#275EA8;" onmouseover="this.style.color='#4F96F4';" onmouseout="this.style.color='#275EA8';">You have suggestions or criticism to this article? Write us!</em></td>   
<td align="right" style="padding-right:2px;"><img src="template/lang/all/icons/write.gif" width="16" height="21" alt="" border="0" /></td>
</tr>
</table>

</div>
<div id="formular">

<form name="form" method="post" action="index.php?id=366,316,0,1,1,0" style="margin:0;padding:0;"><input type="hidden" name="customForm" value="1" /><input type="hidden" name="docucheck" value="1" />


<div style="float:left;">
<p><select name="Betreff" id="Betreff" class="size1">
<option value="" class="deepblue"> Select </option>

</select><br /></p>


<p>Firstname:<br />
<input type="text" name="Vorname" value="" class="size1" /></p>
<p>Surname:*<br />
<input type="text" name="Name" value="" class="size1" /></p>
<p>E-Mail:*<br />
<input type="text" name="E-Mail" value="" class="size1" /></p>
</div>


<div style="float:right;">Message:*<br />
<textarea name="Nachricht" cols="40" rows="4"  class="size7"></textarea>
</div>

<p style="clear:both; text-align:right;"><input type="reset" name="reset" value="Reset" class="btstyle" style="width:100px;" />&nbsp;&nbsp;
<input type="submit" name="submit" value="Send email" class="btstyle" style="width:110px;" /></p>
<p style="margin:20px;" class="sub">* Required fields.<br />Your data is used exclusively for this inquiry.</p>

</form>
</div>
</div>
 <script type="text/javascript" language="javascript">
<!--
	// Lösung ohne Onload
	toggleLayer('formular');
//-->
</script>
<br />





	<table width="97%" border="0" cellspacing="0" cellpadding="0">
		<tr>
			<td valign="bottom">	
			&copy; phpwcms-docu 2004-2013
			<img src="img/leer.gif" border="0" width="10" height="0" alt="" /><a href="imprint.phtml" class="phpwcmsIntLink"><img src="template/lang/all/icons/imprint.gif" width="9" height="15" alt="Impressum" title="Impressum" border="0" /></a>&nbsp; 
			<a href="sitemap_en.phtml" class="phpwcmsIntLink"><img src="template/lang/all/icons/sitemap.gif" width="19" height="15" alt="Sitemap" title="Sitemap" border="0" /></a>&nbsp; 
			 
			
			     
			</td>
			<td valign="bottom" style="padding-right:25px;">
			
			
			
			</td>		
			<td width="150">
			</td>
		</tr>
	</table>
</div><br/>

</div>
</body>
</html>