<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<!--
	phpwcms | free open source content management system
	created by Oliver Georgi (oliver at phpwcms dot de) and licensed under GNU/GPL.
	phpwcms is copyright 2003-2007 of Oliver Georgi. Extensions are copyright of
	their respective owners. Visit project page for details: http://www.phpwcms.org/
//-->
<title>phpwcms-docu for  phpwcms :: web based content management system | Create and edit folders | Create Directory</title>
  <meta http-equiv="content-type" content="text/html; charset=iso-8859-1" />
  <meta http-equiv="content-style-type" content="text/css" />
  <script src="template/inc_js/frontend.js" type="text/javascript"></script>
  <style type="text/css">
  <!-- 
    @import url("template/inc_css/mpl_frontend.css");
    @import url("template/inc_css/mpl_menu.css");
    @import url("template/inc_css/mpl_objects.css");
    @import url("template/inc_css/mpl_docu_en.css");
  //-->
  </style>
<meta name="Title" content="The phpWCMS Documentation" />
<meta name="author" content="Oliver Frohnert, Mario Perez Leal" />
<meta name="Publisher" content="Oliver Frohnert, Mario Perez Leal, creacion" />
<meta name="Copyright" content="Oliver Frohnert, Mario Perez Leal, creacion" />
<meta name="keywords" content="frohnert, perez leal, creacion, documentation, dokumentation, phpwcms, cms, opensource, open source, docu" />
<meta name="description" content="A Documentation Project for the  Open Source CMS phpWCMS" />
<meta name="Audience" content="Alle" />
<meta name="Content-language" content="EN" />
<meta name="robots"      content="index,follow" />
<meta name="expires" content="0" />
<meta name="revisit-after" content="7 days" />
<meta name="resource-type" content="document" />
<meta name="distribution" content="Global" />
<meta name="generator" content="PHPWCMS" />

  <!--[if lt IE 7]>
  <style type="text/css">
    body { behavior: url("template/inc_css/specific/csshover2.htc"); }
    img { behavior: url("template/inc_css/specific/pngbehavior.htc"); }
  </style>
  <![endif]-->
</head>
<body id="myid_233">
<div id="container"><a name="top" id="top"></a>


	<div id="head">
		
	<div id="mainnavi">
		<div class="fleft"><a href="english_version.phtml">Home</a> | <a href="news_en.phtml">News</a> | <span style="text-decoration:none;font-weight:bold;"><a href="the_docu.phtml">The Docu</a></span> | <a href="Usefull_Links_and_Tools.phtml">Links &amp; Tools</a> | <a href="contact.phtml">Contact</a> | <a href="faq_en.phtml">FAQ</a> | <a href="http://forum.phpwcms.org/" target="_blank">Forum</a> | <a href="howto_en.phtml">HowTo</a></div>				
		<div class="sys">Monday, 21. October 2013<img src="img/leer.gif" border="0" width="5" height="1" alt="" />|<img src="img/leer.gif" border="0" width="5" height="1" alt="" />3 User online<img src="img/leer.gif" border="0" width="10" height="1" alt="" />
		<a href="deutsche_version.phtml" title="Deutsche Version"><img src="picture/../template/lang/all/flag_de.gif" border="0" alt="" /></a>
		<a href="english_version.phtml"  title="English version"><img src="picture/../template/lang/all/flag_en.gif" border="0" alt="" /></a>
		</div>
	</div>
	
	<a href="./" title="phpwcms-docu Startseite aufrufen" class="homelink">
	<span>&raquo; phpwcms-docu startpage</span></a>
	<h2>phpwcms-docu - Documentation for the Web Content Management System phpwcms</h2>
	<p>This website is targeted both to the beginner and the lateral entry following the goal to simplify the 
work with phpwcms and to focus on the essentials things.</p>
	</div>

	
	<div id="left">
	<div class="leftnav" style="margin-top:24px;">
	
<div id="ul_div_311">
<ul>
	<li class="sub_no"><a href="download-dev-versions.phtml">Download Dev Versions</a></li>
	<li class="sub_no sub_ul_true"><a href="installation_en.phtml">Installation &amp; Upgrade</a></li>
	<li class="sub_no sub_ul_true"><a href="article.phtml">Articles</a></li>
	<li class="sub_ul"><a href="file.phtml">File</a>
	<div id="ul_div_217">
	<ul>
		<li class="sub_no active"><a href="create_and_edit_folders.phtml">Create and edit folders</a></li>
		<li class="sub_no"><a href="upload_files.phtml">Upload files</a></li>
		<li class="sub_no"><a href="manage_files.phtml">Manage Files</a></li>
	</ul>
	</div>
	</li>
	<li class="sub_no sub_ul_true"><a href="module_en.phtml">Modules</a></li>
	<li class="sub_no sub_ul_true"><a href="communication.phtml">Communication </a></li>
	<li class="sub_no"><a href="chat_en.phtml">Chat</a></li>
	<li class="sub_no"><a href="profile.phtml">Profile</a></li>
	<li class="sub_no sub_ul_true"><a href="admin_en_.phtml">Admin</a></li>
	<li class="sub_no sub_ul_true"><a href="add-ons-and-templates.phtml">Add On&#039;s and Templates</a></li>
	<li class="sub_no"><a href="deutsche_version.phtml?replacement_tags_en">Replacement Tags</a></li>
	<li class="sub_no"><a href="deutsche_version.phtml?content_parts_en">Content Parts</a></li>
</ul>
</div>

		
	</div> 
	</div> 
	  
	<div id="right">
		<div style="margin-top:24px;">			
		<form action="#" method="post" name="searchFE" onsubmit="s=document.getElementById('customSearchInput');if(s.value=='Search')return false;">
			<table width="100%" border="0" cellpadding="0" cellspacing="0">
			<tr>
					<td><input type="text" name="search_input_field" size="20" maxlength="200" id="customSearchInput" class="customSearchInput" value="" onfocus="if(this.value=='Search')this.value='';" onblur="if(this.value=='')this.value='Search';"/></td>
					<td><input type="image" name="search_go" onfocus="this.blur();" title="Search" src="/template/lang/all/submit.gif" /></td>
				</tr>
			</table>
			</form>
			
			      <script type="text/javascript" language="javascript">
			  <!-- 
			        document.getElementById("customSearchInput").value="Search";
			  //-->
			      </script>
				  
<!-- <p style="margin-top:10px;">Change font size: <a href="[FontSize-]"><img src="template/lang/all/icons/reduce.gif" width="18" height="17" alt="" title="Small" border="0" /></a>
			<a href="[FontSize+]"><img src="template/lang/all/icons/extend.gif" width="18" height="17" alt="" title="Bigger" border="0" /></a>
			</p> -->
			
	<p style="margin-top:10px;">Please choose: 
	
	 </p>

<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div>

<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div>
<!-- <a href="http://validator.w3.org/check?uri=http%3A%2F%2Fwww.phpwcms-docu.de%2Findex.php%3Fdeutsche_version" title="W3C Standard XHTML" target="_blank"><img src="picture/w3c/w3c_xhtml.gif" border="0" alt="" /></a>
<a href="http://jigsaw.w3.org/css-validator/validator?uri=http://www.phpwcms-docu.de" title="W3C Standard CSS" target="_blank"><img src="picture/w3c/w3c_css.gif" border="0" alt="" /></a><br />			
<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div> -->
		
<div style="margin-top:10px; margin-bottom:15px;"></div>
	
</div>

	</div> 
	
	<div id="content">
	<div id="bread">You are here: <a href="english_version.phtml">English</a> <span class="breadcrumb_spacer">&gt;</span> <a href="the_docu.phtml">The Docu</a> <span class="breadcrumb_spacer">&gt;</span> <a href="file.phtml">File</a> <span class="breadcrumb_spacer">&gt;</span> Create and edit folders</div>
		
		<a name="jump199"></a><!-- Livedate: 25.10.2004 16:08:03 / Killdate: 31.12.2030 23:59:59 -->
<h1>Create Directory</h1>

<div style="margin:25px 0 0 0;padding:0;" class="spaceBeforeCP"></div><table width="158" border="0" cellspacing="0" cellpadding="0" align="left">
<tr><td class="image_td2"><img src="content/images/f05e166da54e98bc90f8810005b60898.png" width="150" height="86" border="0" class="image_img" alt="file_en_01.png" /></td><td><img src="img/leer.gif" width="8" height="1" border="0" alt="" /></td></tr>
<tr><td align="center" class="image_caption">click to enlarge</td><td><img src="img/leer.gif" width="8" height="1" border="0" alt="" /></td></tr>
</table><div class="articleText"><p>click on <img border="0" src="img/button/add_13x13.gif" alt="Verzeichniss erstellen" />&nbsp;to create a new own folder:<br />
<br />
<img border="0" src="img/button/close_reiter.gif" alt="Dialog schliessen" />&nbsp;Click here to abort the process and to go back to the beginning. Behind inside: you can see in which folder you create the new one. If you haven&rsquo;t created one yet you see, as in the screenshot on the left, the root directory (the highest level of your directory).<br />
<br />
It is recommendable to save only very few files in the root directory. The rest should be saved in clearly named folders, so other editors will find them very easily and quickly.<br />
<br />
<em>Name</em>: insert here the name of the directory. <br />
<em>Status</em>: choose if the directory is: </p>
<ol>
    <li>active (means that the included files can be used in articles)</li>
    <li>puplic (means that other users can open this directory)</li>
</ol>
<p><em>create new dic</em>: click here to finish with the process and create the directory.</p></div><div style="border-bottom:1px dotted #d2e2f5; margin-top:10px; margin-bottom:15px;"></div><div style="margin:15px 0 0 0;padding:0;" class="spaceBeforeCP"></div><h3>Edit Directory</h3><table width="158" border="0" cellspacing="0" cellpadding="0" align="left">
<tr><td class="image_td2"><a href="zoom/MGM1MWRkNDZkOGM2ZTZiYzk0OGYzZDk3ZWUxNTgwMTQucG5nP3dpZHRoPSI3NjgiIGhlaWdodD0iNDYwIg.html" onclick="checkClickZoom();clickZoom('zoom/MGM1MWRkNDZkOGM2ZTZiYzk0OGYzZDk3ZWUxNTgwMTQucG5nP3dpZHRoPSI3NjgiIGhlaWdodD0iNDYwIg.html','previewpic','width.html');return false;.html"><img src="content/images/a801fc70f8eb76ead48505e6a8dc1207.png" width="150" height="89" border="0" class="image_img" alt="file_en_03.png" /></a></td><td><img src="img/leer.gif" width="8" height="1" border="0" alt="" /></td></tr>
<tr><td align="center" class="image_caption">click to enlarge</td><td><img src="img/leer.gif" width="8" height="1" border="0" alt="" /></td></tr>
</table><div class="articleText">You can work on, rename or delete directories you’ve already created. Please note: you only can delete a directory when it is empty! <br />When you click on <IMG alt=Mülleimer src="img/button/trash_13x13_1.gif" border=0> the directory will be not deleted but it will be moved to the trash can as you know it in your computer’s operating system. <br />You can modify the created directories with using these icons:&nbsp;<br />&nbsp; 
<TABLE cellSpacing=1 cellPadding=1 width="100%" border=0>
<TBODY>
<TR>
<TD><IMG alt="Datei hochladen" src="img/button/upload_13x13.gif" border=0>&nbsp;<img src="img/leer.gif" border="0" width="5" height="20" alt="" /></TD>
<TD>Click here to upload a file in the directory.</TD></TR>
<TR>
<TD><IMG alt="Unterverzeichnis anlegen" src="img/button/add_13x13.gif" border=0></TD>
<TD>Click here to create a new directory.</TD></TR>
<TR>
<TD><IMG alt="Verzeichnis bearbeiten" src="img/button/edit_22x13.gif" border=0></TD>
<TD>Click here to see the settings of the directory and change them.</TD></TR>
<TR>
<TD><IMG alt=Aktiv src="img/button/aktiv_12x13_1.gif" border=0></TD>
<TD>Shows that the directory is in use and active and that the files can be used.</TD></TR>
<TR>
<TD><IMG alt="Verzeichnis inaktiv" src="img/button/aktiv_12x13_0.gif" border=0></TD>
<TD>Shows that the directory is not used and the included files are not available.</TD></TR>
<TR>
<TD><IMG alt="Öffentlich (Public)" src="img/button/public_12x13_1.gif" border=0></TD>
<TD>Shows that the directory can also be used by other users.</TD></TR>
<TR>
<TD><IMG alt="Verzeichnis privat" src="img/button/public_12x13_0.gif" border=0></TD>
<TD>Shows that the directory can not be used by other users .</TD></TR>
<TR>
<TD><IMG alt="Verzeichnis löschen" src="img/button/trash_13x13_1.gif" border=0></TD>
<TD>Click here to move that directory to the trash can (only possible if the folder is empty).</TD></TR></TBODY></TABLE></div>
		 
		
		<br /><br />
		<div class="sub">
		Article created: Monday, 25. October 2004 <br /> Last Changes: Tuesday, 4. January 2011	
		</div>
				
	</div>
	
<div id="footer">





	<table width="97%" border="0" cellspacing="0" cellpadding="0">
		<tr>
			<td valign="bottom">	
			&copy; phpwcms-docu 2004-2013
			<img src="img/leer.gif" border="0" width="10" height="0" alt="" /><a href="imprint.phtml" class="phpwcmsIntLink"><img src="template/lang/all/icons/imprint.gif" width="9" height="15" alt="Impressum" title="Impressum" border="0" /></a>&nbsp; 
			<a href="sitemap_en.phtml" class="phpwcmsIntLink"><img src="template/lang/all/icons/sitemap.gif" width="19" height="15" alt="Sitemap" title="Sitemap" border="0" /></a>&nbsp; 
			 
			
			     
			</td>
			<td valign="bottom" style="padding-right:25px;">
			
			
			
			</td>		
			<td width="150">
			</td>
		</tr>
	</table>
</div><br/>

</div>
</body>
</html>