<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<!--
	phpwcms | free open source content management system
	created by Oliver Georgi (oliver at phpwcms dot de) and licensed under GNU/GPL.
	phpwcms is copyright 2003-2007 of Oliver Georgi. Extensions are copyright of
	their respective owners. Visit project page for details: http://www.phpwcms.org/
//-->
<title>phpwcms-docu for  phpwcms :: web based content management system | Dateien suchen &amp; löschen | Dateien suchen und löschen</title>
  <meta http-equiv="content-type" content="text/html; charset=iso-8859-1" />
  <meta http-equiv="content-style-type" content="text/css" />
  <script src="template/inc_js/frontend.js" type="text/javascript"></script>
  <style type="text/css">
  <!-- 
    @import url("template/inc_css/mpl_docu.css");
    @import url("template/inc_css/mpl_frontend.css");
    @import url("template/inc_css/mpl_menu.css");
    @import url("template/inc_css/mpl_objects.css");
  //-->
  </style>
<script type="text/javascript" language="javascript">
<!--
function MM_jumpMenu(targ,selObj,restore){ //v3.0
  eval(targ+".location='"+selObj.options[selObj.selectedIndex].value+"'");
  if (restore) selObj.selectedIndex=0;
}

function MM_findObj(n, d) { //v4.01
  var p,i,x;  if(!d) d=document; if((p=n.indexOf("?"))>0&&parent.frames.length) {
    d=parent.frames[n.substring(p+1)].document; n=n.substring(0,p);}
  if(!(x=d[n])&&d.all) x=d.all[n]; for (i=0;!x&&i<d.forms.length;i++) x=d.forms[i][n];
  for(i=0;!x&&d.layers&&i<d.layers.length;i++) x=MM_findObj(n,d.layers[i].document);
  if(!x && d.getElementById) x=d.getElementById(n); return x;
}

function MM_jumpMenuGo(selName,targ,restore){ //v3.0
  var selObj = MM_findObj(selName); if (selObj) MM_jumpMenu(targ,selObj,restore);
}
//-->
</script>
<meta name="Title" content="Die phpWCMS Dokumentation" />
<meta name="author" content="Oliver Frohnert, Mario Perez Leal" />
<meta name="Publisher" content="Oliver Frohnert, Mario Perez Leal, creacion" />
<meta name="Copyright" content="Oliver Frohnert, Mario Perez Leal, creacion" />
<meta name="keywords" content="frohnert, perez leal, creacion, documentation, dokumentation, phpwcms, cms, opensource, open source, docu" />
<meta name="description" content="Das Dokumentations Projekt für das Open Source CMS phpWCMS" />
<meta name="Audience" content="Alle" />
<meta name="Content-language" content="DE" />
<meta name="robots" content="index,follow" />
<meta name="expires" content="0" />
<meta name="revisit-after" content="7 days" />
<meta name="resource-type" content="document" />
<meta name="distribution" content="Global" />
<meta name="generator" content="PHPWCMS" />

  <!--[if lt IE 7]>
  <style type="text/css">
    body { behavior: url("template/inc_css/specific/csshover2.htc"); }
    img { behavior: url("template/inc_css/specific/pngbehavior.htc"); }
  </style>
  <![endif]-->
</head>
<body id="myid_129">
<div id="container"><a name="top" id="top"></a>


	<div id="head">
		
	<div id="mainnavi">
		<div class="fleft"><a href="deutsche_version.phtml">Startseite</a> | <a href="news_de.phtml">News</a> | <span style="text-decoration:none;font-weight:bold;"><a href="die_docu.phtml">Die Docu</a></span> | <a href="Nuetzliche_Links_und_Tools.phtml">Links &amp; Tools</a> | <a href="downloads.phtml">Downloads</a> | <a href="kontakt.phtml">Kontakt</a> | <a href="faq_de.phtml">FAQ</a> | <a href="http://forum.phpwcms.org/" target="_blank">Forum</a> | <a href="howto_de.phtml">HowTo</a></div>				
		<div class="sys">Donnerstag, 31. Oktober 2013<img src="img/leer.gif" border="0" width="5" height="1" alt="" />|<img src="img/leer.gif" border="0" width="5" height="1" alt="" />2 User online<img src="img/leer.gif" border="0" width="10" height="1" alt="" />
		<a href="deutsche_version.phtml" title="Deutsche Version"><img src="picture/../template/lang/all/flag_de.gif" border="0" alt="" /></a>
		<a href="english_version.phtml"  title="English version"><img src="picture/../template/lang/all/flag_en.gif" border="0" alt="" /></a>
		</div>
	</div>
	
	<a href="./" title="phpwcms-docu Startseite aufrufen" class="homelink">
	<span>&raquo; Zur phpwcms-docu Startseite</span></a>
	<h2>phpwcms-docu - Die Dokumentation f&uuml;r f&uuml;r das CMS phpWCMS</h2>
	<p>phpwcms-docu ist eine Art Kompass, der Ihnen die M&ouml;glichkeiten von phpWcms aufzeigt und Sie erfolgreich, ohne gro&szlig;e Umwege, zu Ihrer fertigen Web-Anwendung f&uuml;hren soll.
	</p>
	</div>

	
	<div id="left">
	<div class="leftnav" style="margin-top:24px;">
	
<div id="ul_div_309">
<ul>
	<li class="sub_no"><a href="download-dev-versionen.phtml">Download Dev Versionen</a></li>
	<li class="sub_no sub_ul_true"><a href="installation_und_upgrade_von_phpwcms.phtml">Installation &amp; Upgrade</a></li>
	<li class="sub_no sub_ul_true"><a href="verwaltung_artikel.phtml">Artikel</a></li>
	<li class="sub_ul"><a href="dateizentrale.phtml">Datei</a>
	<div id="ul_div_83">
	<ul>
		<li class="sub_no"><a href="datei_verzeichnis_erstellen_und_bearbeiten.phtml">Verzeichnis erstellen und bearbeiten</a></li>
		<li class="sub_no"><a href="datei_hochladen.phtml">Dateien hochladen</a></li>
		<li class="sub_no"><a href="dateien_verwalten.phtml">Dateien verwalten</a></li>
		<li class="sub_no active"><a href="dateien_suchen_loeschen.phtml">Dateien suchen &amp; löschen</a></li>
	</ul>
	</div>
	</li>
	<li class="sub_no sub_ul_true"><a href="verwaltung_module.phtml">Module</a></li>
	<li class="sub_no sub_ul_true"><a href="Kommunikation.phtml">Kommunikation</a></li>
	<li class="sub_no"><a href="verwaltung_nachricht.phtml">Nachricht</a></li>
	<li class="sub_no"><a href="verwaltung_chat.phtml">Chat</a></li>
	<li class="sub_no"><a href="verwaltung_profil.phtml">Profil</a></li>
	<li class="sub_no sub_ul_true"><a href="verwaltung_admin.phtml">Admin</a></li>
	<li class="sub_no sub_ul_true"><a href="add-on-und-vorlagen.phtml">Add Ons und Vorlagen</a></li>
	<li class="sub_no"><a href="deutsche_version.phtml?replacement_tags_de">Replacement Tags</a></li>
	<li class="sub_no"><a href="deutsche_version.phtml?content_parts_de">Content Parts</a></li>
</ul>
</div>

		
		
		

	</div> 
	</div> 
	  
	<div id="right">
		<div style="margin-top:24px;">			
		<form action="#" method="post" name="searchFE" onsubmit="s=document.getElementById('customSearchInput');if(s.value=='Suchen')return false;">
			<table width="100%" border="0" cellpadding="0" cellspacing="0">
			<tr>
					<td><input type="text" name="search_input_field" size="20" maxlength="200" id="customSearchInput" class="customSearchInput" value="" onfocus="if(this.value=='Suchen')this.value='';" onblur="if(this.value=='')this.value='Suchen';" /></td>
					<td><input type="image" name="search_go" onfocus="this.blur();" title="Suchen" src="/template/lang/all/submit.gif" /></td>
				</tr>
			</table>
			</form>
			
			      <script type="text/javascript" language="javascript">
			  <!-- 
			        document.getElementById("customSearchInput").value="Suchen";
			  //-->
			      </script>
				  
			<!-- <p style="margin-top:10px;">Schriftgrad &auml;ndern: <a href="[FontSize-]"><img src="template/lang/all/icons/reduce.gif" width="18" height="17" alt="" title="Verkleinern" border="0" /></a>
			<a href="[FontSize+]"><img src="template/lang/all/icons/extend.gif" width="18" height="17" alt="" title="Vergr&ouml;&szlig;ern" border="0" /></a>
			</p> -->
			
	<p style="margin-top:10px;">Bitte w&auml;hlen Sie: 
	
	 </p>
<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div>


<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div>
<!-- <a href="http://validator.w3.org/check?uri=http%3A%2F%2Fwww.phpwcms-docu.de%2Findex.php%3Fdeutsche_version" title="W3C Standard XHTML" target="_blank"><img src="picture/w3c/w3c_xhtml.gif" border="0" alt="" /></a>
<a href="http://jigsaw.w3.org/css-validator/validator?uri=http://www.phpwcms-docu.de" title="W3C Standard CSS" target="_blank"><img src="picture/w3c/w3c_css.gif" border="0" alt="" /></a><br />			
<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div> -->
<h3>Partnersites</h3>






<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div>

<div style="margin-top:10px; margin-bottom:15px;"></div>


<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div>
</div>

	</div> 
	
	<div id="content">
	<div id="bread">Sie sind hier: <a href="deutsche_version.phtml">Deutsch</a> <span class="breadcrumb_spacer">&gt;</span> <a href="die_docu.phtml">Die Docu</a> <span class="breadcrumb_spacer">&gt;</span> <a href="dateizentrale.phtml">Datei</a> <span class="breadcrumb_spacer">&gt;</span> Dateien suchen &amp; löschen</div>
		
		<a name="jump81"></a><!-- Livedate: 14.08.2004 17:05:46 / Killdate: 31.12.2030 23:59:59 -->
<h1>Dateien suchen und löschen</h1>

<div style="margin:15px 0 0 0;padding:0;" class="spaceBeforeCP"></div><h3>Dateien suchen</h3><div class="imgDIVinTextLeft" align="left"><div class="image_td2"><a href="zoom/NzY0ZDhhM2I5OWM3MTdmYzM2MDU0ODFkNjNhYWNkZGUucG5nP3dpZHRoPSI0MDAiIGhlaWdodD0iMzAwIg.html" onclick="checkClickZoom();clickZoom('zoom/NzY0ZDhhM2I5OWM3MTdmYzM2MDU0ODFkNjNhYWNkZGUucG5nP3dpZHRoPSI0MDAiIGhlaWdodD0iMzAwIg.html','previewpic','width.html');return false;.html"><img src="content/images/500f4f6c8d0fed4290b60f18da9f36b5.png" width="150" height="112" border="0" class="image_img" alt="phpwcms_docu_verzeichniss_suchen.png" /></a></div></div><div class="articleText"><p>Im Bereich &bdquo;Suchen&ldquo; k&ouml;nnen Sie, wie es der Name erahnen l&auml;sst,&nbsp; sehr schnell nach Dateinamen suchen.</p>
<p><strong>Suche:</strong> <br />
Es handelt sich hierbei um eine einfache Suche nach Datei-Informationen. <br />
Es wird in den Schl&uuml;sselw&ouml;rtern, dem Dateinamen sowie der ausf&uuml;hrlichen Information gesucht. Es werden keine Platzhalter (Wildcards) unterst&uuml;tzt. Mehrere Suchworte trennen Sie bitte mit Leerzeichen voneinander.</p>
<p>&nbsp;</p>
<p><strong>UND/ODER:</strong> <br />
W&auml;hlen Sie die Option UND, um nur Dateien anzuzeigen, die allen <br />
Suchbegriffen entsprechen oder ODER, um alle Dateien anzuzeigen die mindestens <br />
einem der Suchbegriffe entsprechen.&nbsp;<br />
<br />
<strong>Alle Dateien:</strong> <br />
W&auml;hlen Sie, ob Sie alle Dateien, nur eigene oder nur &ouml;ffentliche <br />
Dateien durchsuchen m&ouml;chten.&nbsp;<br />
<br />
<strong>go:</strong> <br />
Klicken sie hier, um die Suche zu starten. <br />
<strong><font color="#cc0000">TIPP:</font></strong> Die Darstellung im Bereich &bdquo;Suche&ldquo; bietet wie der Bereich &bdquo;&Ouml;ffentlich&ldquo; eine <br />
komfortable M&ouml;glichkeit, Vorschauen von Bildern zu erzeugen. Hinter den <br />
Dateinamen von Abbildungen ohne Vorschau zeigt phpWCMS die Taste . <br />
Klicken Sie auf diese wird die Vorschau erzeugt:</p></div><div style="border-bottom:1px dotted #d2e2f5; margin-top:10px; margin-bottom:15px;"></div><h3>Dateien löschen - Der Papierkorb</h3><table width="100%" cellpadding="0" cellspacing="0" border="0" class="imgTextRight">
<tr>
<td valign="top" width="10%" class="image_td2"><div class="imgDIVblockImgLeft"><div class="image_td2"><a href="zoom/NGJjYjI1MmY2ZTBkOWNmNjVjNTM3ZWRmNTU5OGE0OGMucG5nP3dpZHRoPSI0MDAiIGhlaWdodD0iMzAwIg.html" onclick="checkClickZoom();clickZoom('zoom/NGJjYjI1MmY2ZTBkOWNmNjVjNTM3ZWRmNTU5OGE0OGMucG5nP3dpZHRoPSI0MDAiIGhlaWdodD0iMzAwIg.html','previewpic','width.html');return false;.html"><img src="content/images/9cfbf7c332d1678f2ee623d262e8cb14.png" width="150" height="112" border="0" class="image_img" alt="phpwcms_docu_verzeichniss_papierkorb.png" /></a></div></div></td>
<td valign="top" class="articleText"><p>Dateien, die Sie aus dem Bereich &bdquo;Eigene&ldquo; gel&ouml;scht haben, werden nicht sofort gel&ouml;scht, sondern werden automatisch in den Bereich &bdquo;Papierkorb&ldquo; verschoben.</p>
<p><img border="0" src="img/button/cancel_trash_13x13.gif" alt="L&ouml;schen abbrechen" /> Icon anklicken, um die Datei zur&uuml;ck in Ihr Wurzelverzeichnis zu verschieben. <br />
<br />
<img border="0" src="img/button/trash_13x13_1.gif" alt="Datei l&ouml;schen" /> Icon anklicken, um die Datei endg&uuml;ltig zu l&ouml;schen. <br />
<br />
Klicken Sie auf den Dateinamen, um alle Dateiinformationen einzusehen.</p></td>
</tr>
</table><div align="right"><a href="#top"><img src="img/article/top_link_0.gif" border="0" alt="" /></a></div>
		 
		
		<br /><br />
		<div class="sub">
		Artikel erstellt am: Dienstag, 17. August 2004 <br /> Letzte &Auml;nderung: Dienstag, 04. Januar 2011	
		</div>
				
	</div>
	
<div id="footer">





	<table width="97%" border="0" cellspacing="0" cellpadding="0">
		<tr>
			<td valign="bottom">	
			&copy; phpwcms-docu 2004-2013
			<img src="img/leer.gif" border="0" width="10" height="0" alt="" /><a href="impressum.phtml" class="phpwcmsIntLink"><img src="template/lang/all/icons/imprint.gif" width="9" height="15" alt="Impressum" title="Impressum" border="0" /></a>&nbsp; 
			<a href="sitemap_de.phtml" class="phpwcmsIntLink"><img src="template/lang/all/icons/sitemap.gif" width="19" height="15" alt="Sitemap" title="Sitemap" border="0" /></a>&nbsp; 
			<a href="gaestebuch.phtml" class="phpwcmsIntLink"><img src="template/lang/all/icons/gbook.gif" width="20" height="16" alt="Ins G&auml;stebuch eintragen" title="Ins G&auml;stebuch eintragen" border="0" /></a>&nbsp; 
			<a href="#" onclick="BookMark_Page();return false;" title="" class="phpwcmsBookmarkLink"><img src="template/lang/all/icons/favo.gif" width="12" height="15" alt="Seite als Bookmark speichern" title="Seite als Bookmark speichern" border="0" /></a>&nbsp; 
			     
			</td>
			<td valign="bottom" style="padding-right:25px;">
			
			
			
			</td>		
			<td width="150">
			</td>
		</tr>
	</table>
</div><br/>

</div>
</body>
</html>