<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<!--
	phpwcms | free open source content management system
	created by Oliver Georgi (oliver at phpwcms dot de) and licensed under GNU/GPL.
	phpwcms is copyright 2003-2007 of Oliver Georgi. Extensions are copyright of
	their respective owners. Visit project page for details: http://www.phpwcms.org/
//-->
<title>phpwcms-docu for  phpwcms :: web based content management system | Verzeichnis erstellen und bearbeiten{D:8/11/2007,30,neuR.gif} | Verzeichnis erstellen und bearbeiten</title>
  <meta http-equiv="content-type" content="text/html; charset=iso-8859-1" />
  <meta http-equiv="content-style-type" content="text/css" />
  <script src="template/inc_js/frontend.js" type="text/javascript"></script>
  <style type="text/css">
  <!-- 
    @import url("template/inc_css/mpl_docu.css");
    @import url("template/inc_css/mpl_frontend.css");
    @import url("template/inc_css/mpl_menu.css");
    @import url("template/inc_css/mpl_objects.css");
  //-->
  </style>
<script type="text/javascript" language="javascript">
<!--
function MM_jumpMenu(targ,selObj,restore){ //v3.0
  eval(targ+".location='"+selObj.options[selObj.selectedIndex].value+"'");
  if (restore) selObj.selectedIndex=0;
}

function MM_findObj(n, d) { //v4.01
  var p,i,x;  if(!d) d=document; if((p=n.indexOf("?"))>0&&parent.frames.length) {
    d=parent.frames[n.substring(p+1)].document; n=n.substring(0,p);}
  if(!(x=d[n])&&d.all) x=d.all[n]; for (i=0;!x&&i<d.forms.length;i++) x=d.forms[i][n];
  for(i=0;!x&&d.layers&&i<d.layers.length;i++) x=MM_findObj(n,d.layers[i].document);
  if(!x && d.getElementById) x=d.getElementById(n); return x;
}

function MM_jumpMenuGo(selName,targ,restore){ //v3.0
  var selObj = MM_findObj(selName); if (selObj) MM_jumpMenu(targ,selObj,restore);
}
//-->
</script>
<meta name="Title" content="Die phpWCMS Dokumentation" />
<meta name="author" content="Oliver Frohnert, Mario Perez Leal" />
<meta name="Publisher" content="Oliver Frohnert, Mario Perez Leal, creacion" />
<meta name="Copyright" content="Oliver Frohnert, Mario Perez Leal, creacion" />
<meta name="keywords" content="frohnert, perez leal, creacion, documentation, dokumentation, phpwcms, cms, opensource, open source, docu" />
<meta name="description" content="Das Dokumentations Projekt für das Open Source CMS phpWCMS" />
<meta name="Audience" content="Alle" />
<meta name="Content-language" content="DE" />
<meta name="robots" content="index,follow" />
<meta name="expires" content="0" />
<meta name="revisit-after" content="7 days" />
<meta name="resource-type" content="document" />
<meta name="distribution" content="Global" />
<meta name="generator" content="PHPWCMS" />
<meta name="verify-v1" content="1ZpxZ7AZsjm7PxjqXQVus0eiUYqOsp5URTJn9q4KNz8=" />
  <link rel="stylesheet" href="template/slimbox/css/slimbox.css" type="text/css" media="screen" />
  <script src="template/inc_js/mootools/mootools.js" type="text/javascript"></script>
  <script src="template/slimbox/js/slimbox.js" type="text/javascript"></script>
  <!--[if lt IE 7]>
  <style type="text/css">
    body { behavior: url("template/inc_css/specific/csshover2.htc"); }
    img { behavior: url("template/inc_css/specific/pngbehavior.htc"); }
  </style>
  <![endif]-->
</head>
<body id="myid_121">
<div id="container"><a name="top" id="top"></a>


	<div id="head">
		
	<div id="mainnavi">
		<div class="fleft"><a href="deutsche_version.phtml">Startseite</a> | <a href="news_de.phtml">News</a> | <span style="text-decoration:none;font-weight:bold;"><a href="die_docu.phtml">Die Docu</a></span> | <a href="Nuetzliche_Links_und_Tools.phtml">Links &amp; Tools</a> | <a href="downloads.phtml">Downloads</a> | <a href="kontakt.phtml">Kontakt</a> | <a href="faq_de.phtml">FAQ</a> | <a href="http://forum.phpwcms.org/" target="_blank">Forum</a> | <a href="howto_de.phtml">HowTo</a></div>				
		<div class="sys">Donnerstag, 31. Oktober 2013<img src="img/leer.gif" border="0" width="5" height="1" alt="" />|<img src="img/leer.gif" border="0" width="5" height="1" alt="" />2 User online<img src="img/leer.gif" border="0" width="10" height="1" alt="" />
		<a href="deutsche_version.phtml" title="Deutsche Version"><img src="picture/../template/lang/all/flag_de.gif" border="0" alt="" /></a>
		<a href="english_version.phtml"  title="English version"><img src="picture/../template/lang/all/flag_en.gif" border="0" alt="" /></a>
		</div>
	</div>
	
	<a href="./" title="phpwcms-docu Startseite aufrufen" class="homelink">
	<span>&raquo; Zur phpwcms-docu Startseite</span></a>
	<h2>phpwcms-docu - Die Dokumentation f&uuml;r f&uuml;r das CMS phpWCMS</h2>
	<p>phpwcms-docu ist eine Art Kompass, der Ihnen die M&ouml;glichkeiten von phpWcms aufzeigt und Sie erfolgreich, ohne gro&szlig;e Umwege, zu Ihrer fertigen Web-Anwendung f&uuml;hren soll.
	</p>
	</div>

	
	<div id="left">
	<div class="leftnav" style="margin-top:24px;">
	
<div id="ul_div_309">
<ul>
	<li class="sub_no"><a href="download-dev-versionen.phtml">Download Dev Versionen</a></li>
	<li class="sub_no sub_ul_true"><a href="installation_und_upgrade_von_phpwcms.phtml">Installation &amp; Upgrade</a></li>
	<li class="sub_no sub_ul_true"><a href="verwaltung_artikel.phtml">Artikel</a></li>
	<li class="sub_ul"><a href="dateizentrale.phtml">Datei</a>
	<div id="ul_div_83">
	<ul>
		<li class="sub_no active"><a href="datei_verzeichnis_erstellen_und_bearbeiten.phtml">Verzeichnis erstellen und bearbeiten</a></li>
		<li class="sub_no"><a href="datei_hochladen.phtml">Dateien hochladen</a></li>
		<li class="sub_no"><a href="dateien_verwalten.phtml">Dateien verwalten</a></li>
		<li class="sub_no"><a href="dateien_suchen_loeschen.phtml">Dateien suchen &amp; löschen</a></li>
	</ul>
	</div>
	</li>
	<li class="sub_no sub_ul_true"><a href="verwaltung_module.phtml">Module</a></li>
	<li class="sub_no sub_ul_true"><a href="Kommunikation.phtml">Kommunikation</a></li>
	<li class="sub_no"><a href="verwaltung_nachricht.phtml">Nachricht</a></li>
	<li class="sub_no"><a href="verwaltung_chat.phtml">Chat</a></li>
	<li class="sub_no"><a href="verwaltung_profil.phtml">Profil</a></li>
	<li class="sub_no sub_ul_true"><a href="verwaltung_admin.phtml">Admin</a></li>
	<li class="sub_no sub_ul_true"><a href="add-on-und-vorlagen.phtml">Add Ons und Vorlagen</a></li>
	<li class="sub_no"><a href="deutsche_version.phtml?replacement_tags_de">Replacement Tags</a></li>
	<li class="sub_no"><a href="deutsche_version.phtml?content_parts_de">Content Parts</a></li>
</ul>
</div>

		
		
		

	</div> 
	</div> 
	  
	<div id="right">
		<div style="margin-top:24px;">			
		<form action="index.php?suche" method="post" name="searchFE" onsubmit="s=document.getElementById('customSearchInput');if(s.value=='Suchen')return false;">
			<table width="100%" border="0" cellpadding="0" cellspacing="0">
			<tr>
					<td><input type="text" name="search_input_field" size="20" maxlength="200" id="customSearchInput" class="customSearchInput" value="" onfocus="if(this.value=='Suchen')this.value='';" onblur="if(this.value=='')this.value='Suchen';" /></td>
					<td><input type="image" name="search_go" onfocus="this.blur();" title="Suchen" src="/template/lang/all/submit.gif" /></td>
				</tr>
			</table>
			</form>
			
			      <script type="text/javascript" language="javascript">
			  <!-- 
			        document.getElementById("customSearchInput").value="Suchen";
			  //-->
			      </script>
				  
			<!-- <p style="margin-top:10px;">Schriftgrad &auml;ndern: <a href="[FontSize-]"><img src="template/lang/all/icons/reduce.gif" width="18" height="17" alt="" title="Verkleinern" border="0" /></a>
			<a href="[FontSize+]"><img src="template/lang/all/icons/extend.gif" width="18" height="17" alt="" title="Vergr&ouml;&szlig;ern" border="0" /></a>
			</p> -->
			
	<p style="margin-top:10px;">Bitte w&auml;hlen Sie: 
	
	 </p>
<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div>


<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div>
<!-- <a href="http://validator.w3.org/check?uri=http%3A%2F%2Fwww.phpwcms-docu.de%2Findex.php%3Fdeutsche_version" title="W3C Standard XHTML" target="_blank"><img src="picture/w3c/w3c_xhtml.gif" border="0" alt="" /></a>
<a href="http://jigsaw.w3.org/css-validator/validator?uri=http://www.phpwcms-docu.de" title="W3C Standard CSS" target="_blank"><img src="picture/w3c/w3c_css.gif" border="0" alt="" /></a><br />			
<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div> -->
<h3>Partnersites</h3>






<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div>

<div style="margin-top:10px; margin-bottom:15px;"></div>


<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div>
</div>

	</div> 
	
	<div id="content">
	<div id="bread">Sie sind hier: <a href="deutsche_version.phtml">Deutsch</a> <span class="breadcrumb_spacer">&gt;</span> <a href="die_docu.phtml">Die Docu</a> <span class="breadcrumb_spacer">&gt;</span> <a href="dateizentrale.phtml">Datei</a> <span class="breadcrumb_spacer">&gt;</span> Verzeichnis erstellen und bearbeiten</div>
		
		<a name="jump71"></a><!-- Livedate: 12.08.2004 10:23:17 / Killdate: 31.12.2030 23:59:59 -->
<h1>Verzeichnis erstellen und bearbeiten</h1>

<div style="margin:15px 0 0 0;padding:0;" class="spaceBeforeCP"></div><h3>Verzeichnis erstellen</h3>
<table border="0" cellspacing="0" width="10%" cellpadding="0" align="left" class=" imgListTableLeft" summary="">
<tr>
	<td class="imagelisttd2"><a href="content/images/cb413836387ab2bb04b78971152ebdde.png" rel="lightbox[KLcTP]" title="Bild 1 - Dateizentrale" target="_blank"><img src="content/images/6e4d39591a58b13b1c4df3e4e8d46a99.png" width="150" height="59" border="0" class="imagelistimg" alt="datei_01.png" /></a></td>
</tr>
<tr>
	<td class="imglistcaption">Bild 1 - Dateizentrale</td>
</tr>

<tr>
	<td class="imagelistSpacerRow"><img src="img/leer.gif" width="1" height="1" border="0" alt="" /></td>
</tr>
<tr>
	<td class="imagelisttd2"><a href="content/images/e2b5c1f6c92f8b7c06973aad20480185.png" rel="lightbox[KLcTP]" title="Bild 2 - Eingabemaske für Ordner" target="_blank"><img src="content/images/3b83fcee1c2e701f8219f61b3accae27.png" width="150" height="60" border="0" class="imagelistimg" alt="datei_02_verzeichnis_erstellen.png" /></a></td>
</tr>
<tr>
	<td class="imglistcaption">Bild 2 - Eingabemaske für Ordner</td>
</tr>

<tr>
	<td class="imagelistSpacerRow"><img src="img/leer.gif" width="1" height="1" border="0" alt="" /></td>
</tr>
<tr>
	<td class="imagelisttd2"><a href="content/images/faa9295a1de9f2c5bae0b9aa066fe0d7.png" rel="lightbox[KLcTP]" title="Bild 3 - Ordner erstellen" target="_blank"><img src="content/images/9a90c47e6e7ddb23e1f7a6ea49ac5b8b.png" width="150" height="60" border="0" class="imagelistimg" alt="datei_03.png" /></a></td>
</tr>
<tr>
	<td class="imglistcaption">Bild 3 - Ordner erstellen</td>
</tr>
</table>
<p>Wenn Sie das erste mal die Dateizentrale anklicken haben Sie verschiedene M&ouml;glichkeiten ein Verzeichnis zu erstellen.<br />
<br />
Durch klicken auf das Symbol <img src="./img/button/add_13x13.gif" alt="Ordner erstellen" /> oder den Textlink <br />
<strong>[<u>Verzeichnis erstellen</u>]</strong> k&ouml;nnen Sie einen Neuen Ordner Anlegen  (Bild 1).<br />
<br />
Nachdem Sie nun auf eine der beiden Schaltfl&auml;chen gedr&uuml;ckt haben sehen Sie nun die Eingabemaske f&uuml;r den Neuen Ordner (Bild 2). Geben Sie dem Ordner einen Namen. In dem Beispiel haben wie es Verzeichnis 1 genannt (Bild 3). Sie haben dazu noch die m&ouml;glichkeit die Sichtbarkeit Ihrer Datein zu bestimmen. Den Haken bei <strong>Aktiv</strong> sollten Sie setzten. Da ansonsten die Bilder im Bildbrowser nicht angezeigt werden. <strong>&Ouml;ffentlich</strong> bedeutet das auch andere auf Ihre Datein zugreifen k&ouml;nnen.<br />
<br />
Bis zu diesem Schritt haben Sie auch noch die m&ouml;glichkeit den Vorgang abzubrechen. Durch Dr&uuml;cken auf <img alt="Vorgang abbrechen" src="./img/button/close_reiter.gif" /> brechen Sie die Erstellung des Neuen Ordners ab. <br />
<br />
Um den Ordner nun zu Erstellen klicken Sie auf die Schaltf&auml;che darunter <strong>Verzeichnis Erstellen</strong> danach kommen Sie zu&uuml;ck zur Dateizentrale und sehen Ihren erstellten Ordner (Bild 4).</p><div style="margin:50px 0 0 0;padding:0;" class="spaceBeforeCP"></div><h3>Verzeichnis bearbeiten</h3>
<table border="0" cellspacing="0" width="10%" cellpadding="0" align="left" class=" imgListTableLeft" summary="">
<tr>
	<td class="imagelisttd2"><a href="content/images/2fe0b4e3fc5a6adf457554e8010c992f.png" rel="lightbox[zqnfI]" title="Bild 1 - Dateizentrale" target="_blank"><img src="content/images/d379c95a273afb4f54ef2625c320e3d2.png" width="150" height="59" border="0" class="imagelistimg" alt="datei_04.png" /></a></td>
</tr>
<tr>
	<td class="imglistcaption">Bild 1 - Dateizentrale</td>
</tr>

<tr>
	<td class="imagelistSpacerRow"><img src="img/leer.gif" width="1" height="1" border="0" alt="" /></td>
</tr>
<tr>
	<td class="imagelisttd2"><a href="content/images/7cb8966d70cdd11500b4558bcdf4960e.png" rel="lightbox[zqnfI]" title="Bild 2 - Ordner bearbeiten" target="_blank"><img src="content/images/4a5fc3eca1591bfa93d34aad02d5445e.png" width="150" height="59" border="0" class="imagelistimg" alt="datei_bearbeiten.png" /></a></td>
</tr>
<tr>
	<td class="imglistcaption">Bild 2 - Ordner bearbeiten</td>
</tr>
</table>
<p>Durch klicken auf das Symbol <img src="./img/button/edit_22x13.gif" alt="Ordner bearbeiten" /> k&ouml;nnen Sie den Ordner bearbeiten (Bild 1). Dabei geht es vorranging um die &Auml;nderung des Namens. Da Sie die Sichtbarkeit des Ordners direkt &uuml;ber die Dateizentrale durch Klicken auf <img src="./img/button/aktiv_12x13_1.gif" alt="Ordner Aktiv" /> / <img src="./img/button/aktiv_12x13_0.gif" alt="Ordner Inaktiv" /> und <img src="./img/button/public_12x13_1.gif" alt="Ordner &Ouml;ffnetlich" /> / <img src="./img/button/public_12x13_0.gif" alt="Ordner nicht &Ouml;ffentlich" /> bestimmen k&ouml;nnen.<br />
<br />
Nachdem Sie nun auf <img src="./img/button/edit_22x13.gif" alt="Ordner bearbeiten" /> geklickt haben. Sehen Sie nun wieder die Details zu diesem Ordner. Nachdem Sie dort die von Ihnen gew&uuml;nschten &Auml;nderungen vorgenommen haben. Klicken Sie auf die Schaltfl&auml;che <strong>Verzeichnis aktualisieren</strong> um die &Auml;nderungen zu &Uuml;bernehmen (Bild 2).</p>
<div style="clear: both;">&nbsp;</div><div align="right"><a href="#top"><img src="img/article/top_link_0.gif" border="0" alt="" /></a></div><div style="margin:0 0 20px 0;padding:0;" class="spaceAfterCP"></div><div class="articleText"><p>&nbsp;</p>
<p>&nbsp;</p>
<fieldset><legend><img width="21" height="22" border="0" align="middle" alt="Info" title="Info" src="template/lang/all/info_s.gif" /><strong> Feldbeschreibungen</strong></legend>
<table width="100%" cellspacing="0" cellpadding="6" border="0">
    <tbody>
        <tr>
            <td width="50"><img border="0" src="img/button/upload_13x13.gif" alt="Datei hochladen" /></td>
            <td>Klicken Sie hier, um eine Datei in dieses Verzeichnis hochzuladen.</td>
        </tr>
        <tr class="tbfield">
            <td><img border="0" src="img/button/add_13x13.gif" alt="Unterverzeichnis anlegen" /></td>
            <td>Klicken Sie hier, um ein Unterverzeichnis anzulegen.</td>
        </tr>
        <tr>
            <td><img border="0" src="img/button/edit_22x13.gif" alt="Verzeichnis bearbeiten" /></td>
            <td>Klicken Sie hier, um die Eigenschaften des Verzeichnisses zu sehen bzw. zu &auml;ndern.</td>
        </tr>
        <tr class="tbfield">
            <td><img border="0" src="img/button/aktiv_12x13_1.gif" alt="Aktiv" /> / <img border="0" src="img/button/aktiv_12x13_0.gif" alt="Verzeichnis inaktiv" /></td>
            <td><img border="0" src="img/button/aktiv_12x13_1.gif" alt="Aktiv" /> Zeigt an, dass das Verzeichnis aktiv ist, d.h. dass in ihm enthaltene Dateien in Artikeln verwendbar sind.<br />
            <img border="0" src="img/button/aktiv_12x13_0.gif" alt="Verzeichnis inaktiv" /> Zeigt an, dass das Verzeichnis inaktiv ist, d.h. dass in ihm enthaltene Dateien nicht in Artikeln verwendbar sind.</td>
        </tr>
        <tr>
            <td><img border="0" src="img/button/public_12x13_1.gif" alt="&Ouml;ffentlich (Public)" /> / <img border="0" src="img/button/public_12x13_0.gif" alt="Verzeichnis privat" /></td>
            <td><img border="0" src="img/button/public_12x13_1.gif" alt="&Ouml;ffentlich (Public)" /> Zeigt an, dass das Verzeichnis von anderen Nutzern der Verwaltungsebene ge&ouml;ffnet werden kann.<br />
            <img border="0" src="img/button/public_12x13_0.gif" alt="Verzeichnis privat" />Zeigt an, dass das Verzeichnis von anderen Nutzern der Verwaltungsebene nicht ge&ouml;ffnet werden kann.</td>
        </tr>
        <tr class="tbfield">
            <td><img border="0" src="img/button/trash_13x13_1.gif" alt="Verzeichnis l&ouml;schen" /></td>
            <td>Klicken Sie hier, um das Verzeichnis zu l&ouml;schen (ist nur bei leeren Verzeichnissen m&ouml;glich).</td>
        </tr>
    </tbody>
</table>
</fieldset></div>
		 
		
		<br /><br />
		<div class="sub">
		Artikel erstellt am: Dienstag, 17. August 2004 <br /> Letzte &Auml;nderung: Dienstag, 04. Januar 2011	
		</div>
				
	</div>
	
<div id="footer"><br /><br />
<p style="height:30px;">&nbsp;</p>


 <script type="text/javascript" language="javascript">
<!--

var showDefaultValue =  0

function hideLayer(whichLayer) {
	if (document.getElementById) {
		// this is the way the standards work
		document.getElementById(whichLayer).style.display = "none";
	} else if (document.all) {
		// this is the way old msie versions work
		document.all[whichlayer].style.display = "none";
	} else if (document.layers) {
		// this is the way nn4 works
		document.layers[whichLayer].display = "none";
	}
}

function showLayer(whichLayer) {
		//	alert(whichLayer);
	if (document.getElementById) {
		// this is the way the standards work
		document.getElementById(whichLayer).style.display = "block";
	}
	else if (document.all) {
		// this is the way old msie versions work
		document.all[whichlayer].style.display = "block";
	}
	else if (document.layers) {
		// this is the way nn4 works
		document.layers[whichLayer].display = "block";
	}
}

function toggleLayer(whichLayer) {
	if(showDefaultValue == 0) {
		hideLayer(whichLayer);
		showDefaultValue = 1;
	} else {
		showLayer(whichLayer);
		showDefaultValue = 0;
	}
}
//-->
</script>


<div id="alles">
<div id="klapper" onclick="toggleLayer('formular');">
<table width="570" border="0" cellspacing="0" cellpadding="0">
<tr>
<td><em style="color:#275EA8;" onmouseover="this.style.color='#4F96F4';" onmouseout="this.style.color='#275EA8';">Sie haben Anregungen oder Kritik zu diesem Artikel? Schreiben Sie uns!</em></td>   
<td align="right" style="padding-right:2px;"><img src="template/lang/all/icons/write.gif" width="16" height="21" alt="" border="0" /></td>
</tr>
</table>

</div>
<div id="formular">

<form name="form" method="post" action="index.php?id=121,71,0,1,1,0" style="margin:0;padding:0;"><input type="hidden" name="customForm" value="1" /><input type="hidden" name="docucheck" value="1" />


<div style="float:left;">
<p><select name="Betreff" id="Betreff" class="size1">
<option value="" class="deepblue"> Bitte ausw&auml;hlen </option>
<option value="subject_1" class="inselect">Anregungen</option>
<option value="subject_2" class="inselect">Fehlermeldung/ Kritik</option>
<option value="subject_3" class="inselect">Sonstiges</option>

</select><br /></p>


<p>Vorname:<br />
<input type="text" name="Vorname" value="" class="size1" /></p>
<p>Name:*<br />
<input type="text" name="Name" value="" class="size1" /></p>
<p>E-Mail:*<br />
<input type="text" name="E-Mail" value="" class="size1" /></p>
</div>


<div style="float:right;">Mitteilung:*<br />
<textarea name="Nachricht" cols="40" rows="4"  class="size7"></textarea>
</div>

<p style="clear:both; text-align:right;"><input type="reset" name="reset" value="Zur&uuml;cksetzen" class="btstyle" style="width:100px;" />&nbsp;&nbsp;
<input type="submit" name="submit" value="Anfrage senden" class="btstyle" style="width:110px;" /></p>
<p style="margin:20px;" class="sub">* Pflichtangaben. Ihre Daten werden ausschlie&szlig;lich für diese Anfrage verwendet.</p>

</form>
</div>
</div>
 <script type="text/javascript" language="javascript">
<!--
	// Lösung ohne Onload
	toggleLayer('formular');
//-->
</script>
<br />





	<table width="97%" border="0" cellspacing="0" cellpadding="0">
		<tr>
			<td valign="bottom">	
			&copy; phpwcms-docu 2004-2013
			<img src="img/leer.gif" border="0" width="10" height="0" alt="" /><a href="impressum.phtml" class="phpwcmsIntLink"><img src="template/lang/all/icons/imprint.gif" width="9" height="15" alt="Impressum" title="Impressum" border="0" /></a>&nbsp; 
			<a href="sitemap_de.phtml" class="phpwcmsIntLink"><img src="template/lang/all/icons/sitemap.gif" width="19" height="15" alt="Sitemap" title="Sitemap" border="0" /></a>&nbsp; 
			<a href="gaestebuch.phtml" class="phpwcmsIntLink"><img src="template/lang/all/icons/gbook.gif" width="20" height="16" alt="Ins G&auml;stebuch eintragen" title="Ins G&auml;stebuch eintragen" border="0" /></a>&nbsp; 
			<a href="#" onclick="BookMark_Page();return false;" title="" class="phpwcmsBookmarkLink"><img src="template/lang/all/icons/favo.gif" width="12" height="15" alt="Seite als Bookmark speichern" title="Seite als Bookmark speichern" border="0" /></a>&nbsp; 
			     
			</td>
			<td valign="bottom" style="padding-right:25px;">
			
			
			
			</td>		
			<td width="150">
			</td>
		</tr>
	</table>
</div><br/>

</div>
</body>
</html>