<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<!--
	phpwcms | free open source content management system
	created by Oliver Georgi (oliver at phpwcms dot de) and licensed under GNU/GPL.
	phpwcms is copyright 2003-2007 of Oliver Georgi. Extensions are copyright of
	their respective owners. Visit project page for details: http://www.phpwcms.org/
//-->
<title>phpwcms-docu for  phpwcms :: web based content management system | File{D:9/11/2007,30,newR.gif} | File Administration</title>
  <meta http-equiv="content-type" content="text/html; charset=iso-8859-1" />
  <meta http-equiv="content-style-type" content="text/css" />
  <script src="template/inc_js/frontend.js" type="text/javascript"></script>
  <style type="text/css">
  <!-- 
    @import url("template/inc_css/mpl_frontend.css");
    @import url("template/inc_css/mpl_menu.css");
    @import url("template/inc_css/mpl_objects.css");
    @import url("template/inc_css/mpl_docu_en.css");
  //-->
  </style>
<meta name="Title" content="The phpWCMS Documentation" />
<meta name="author" content="Oliver Frohnert, Mario Perez Leal" />
<meta name="Publisher" content="Oliver Frohnert, Mario Perez Leal, creacion" />
<meta name="Copyright" content="Oliver Frohnert, Mario Perez Leal, creacion" />
<meta name="keywords" content="frohnert, perez leal, creacion, documentation, dokumentation, phpwcms, cms, opensource, open source, docu" />
<meta name="description" content="A Documentation Project for the  Open Source CMS phpWCMS" />
<meta name="Audience" content="Alle" />
<meta name="Content-language" content="EN" />
<meta name="robots"      content="index,follow" />
<meta name="expires" content="0" />
<meta name="revisit-after" content="7 days" />
<meta name="resource-type" content="document" />
<meta name="distribution" content="Global" />
<meta name="generator" content="PHPWCMS" />

  <link rel="stylesheet" href="template/slimbox/css/slimbox.css" type="text/css" media="screen" />
  <script src="template/inc_js/mootools/mootools.js" type="text/javascript"></script>
  <script src="template/slimbox/js/slimbox.js" type="text/javascript"></script>
  <!--[if lt IE 7]>
  <style type="text/css">
    body { behavior: url("template/inc_css/specific/csshover2.htc"); }
    img { behavior: url("template/inc_css/specific/pngbehavior.htc"); }
  </style>
  <![endif]-->
</head>
<body id="myid_217">
<div id="container"><a name="top" id="top"></a>


	<div id="head">
		
	<div id="mainnavi">
		<div class="fleft"><a href="english_version.phtml">Home</a> | <a href="news_en.phtml">News</a> | <span style="text-decoration:none;font-weight:bold;"><a href="the_docu.phtml">The Docu</a></span> | <a href="Usefull_Links_and_Tools.phtml">Links &amp; Tools</a> | <a href="contact.phtml">Contact</a> | <a href="faq_en.phtml">FAQ</a> | <a href="http://forum.phpwcms.org/" target="_blank">Forum</a> | <a href="howto_en.phtml">HowTo</a></div>				
		<div class="sys">Monday, 1. June 2015<img src="img/leer.gif" border="0" width="5" height="1" alt="" />|<img src="img/leer.gif" border="0" width="5" height="1" alt="" />5 User online<img src="img/leer.gif" border="0" width="10" height="1" alt="" />
		<a href="deutsche_version.phtml" title="Deutsche Version"><img src="picture/../template/lang/all/flag_de.gif" border="0" alt="" /></a>
		<a href="english_version.phtml"  title="English version"><img src="picture/../template/lang/all/flag_en.gif" border="0" alt="" /></a>
		</div>
	</div>
	
	<a href="./" title="phpwcms-docu Startseite aufrufen" class="homelink">
	<span>&raquo; phpwcms-docu startpage</span></a>
	<h2>phpwcms-docu - Documentation for the Web Content Management System phpwcms</h2>
	<p>This website is targeted both to the beginner and the lateral entry following the goal to simplify the 
work with phpwcms and to focus on the essentials things.</p>
	</div>

	
	<div id="left">
	<div class="leftnav" style="margin-top:24px;">
	
<div id="ul_div_311">
<ul>
	<li class="sub_no"><a href="download-dev-versions.phtml">Download Dev Versions</a></li>
	<li class="sub_no sub_ul_true"><a href="installation_en.phtml">Installation &amp; Upgrade</a></li>
	<li class="sub_no sub_ul_true"><a href="article.phtml">Articles</a></li>
	<li class="sub_ul active"><a href="file.phtml">File</a>
	<div id="ul_div_217">
	<ul>
		<li class="sub_no"><a href="create_and_edit_folders.phtml">Create and edit folders</a></li>
		<li class="sub_no"><a href="upload_files.phtml">Upload files</a></li>
		<li class="sub_no"><a href="manage_files.phtml">Manage Files</a></li>
	</ul>
	</div>
	</li>
	<li class="sub_no sub_ul_true"><a href="module_en.phtml">Modules</a></li>
	<li class="sub_no sub_ul_true"><a href="communication.phtml">Communication </a></li>
	<li class="sub_no"><a href="chat_en.phtml">Chat</a></li>
	<li class="sub_no"><a href="profile.phtml">Profile</a></li>
	<li class="sub_no sub_ul_true"><a href="admin_en_.phtml">Admin</a></li>
	<li class="sub_no sub_ul_true"><a href="add-ons-and-templates.phtml">Add On&#039;s and Templates</a></li>
	<li class="sub_no"><a href="deutsche_version.phtml?replacement_tags_en">Replacement Tags</a></li>
	<li class="sub_no"><a href="deutsche_version.phtml?content_parts_en">Content Parts</a></li>
</ul>
</div>

		
	</div> 
	</div> 
	  
	<div id="right">
		<div style="margin-top:24px;">			
		<form action="#" method="post" name="searchFE" onsubmit="s=document.getElementById('customSearchInput');if(s.value=='Search')return false;">
			<table width="100%" border="0" cellpadding="0" cellspacing="0">
			<tr>
					<td><input type="text" name="search_input_field" size="20" maxlength="200" id="customSearchInput" class="customSearchInput" value="" onfocus="if(this.value=='Search')this.value='';" onblur="if(this.value=='')this.value='Search';"/></td>
					<td><input type="image" name="search_go" onfocus="this.blur();" title="Search" src="/template/lang/all/submit.gif" /></td>
				</tr>
			</table>
			</form>
			
			      <script type="text/javascript" language="javascript">
			  <!-- 
			        document.getElementById("customSearchInput").value="Search";
			  //-->
			      </script>
				  
<!-- <p style="margin-top:10px;">Change font size: <a href="[FontSize-]"><img src="template/lang/all/icons/reduce.gif" width="18" height="17" alt="" title="Small" border="0" /></a>
			<a href="[FontSize+]"><img src="template/lang/all/icons/extend.gif" width="18" height="17" alt="" title="Bigger" border="0" /></a>
			</p> -->
			
	<p style="margin-top:10px;">Please choose: 
	
	 </p>


<!-- <a href="http://validator.w3.org/check?uri=http%3A%2F%2Fwww.phpwcms-docu.de%2Findex.php%3Fdeutsche_version" title="W3C Standard XHTML" target="_blank"><img src="picture/w3c/w3c_xhtml.gif" border="0" alt="" /></a>
<a href="http://jigsaw.w3.org/css-validator/validator?uri=http://www.phpwcms-docu.de" title="W3C Standard CSS" target="_blank"><img src="picture/w3c/w3c_css.gif" border="0" alt="" /></a><br />			
<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div> -->
		
<div style="margin-top:10px; margin-bottom:15px;"></div>
	
</div>

	</div> 
	
	<div id="content">
	<div id="bread">You are here: <a href="english_version.phtml">English</a> <span class="breadcrumb_spacer">&gt;</span> <a href="the_docu.phtml">The Docu</a> <span class="breadcrumb_spacer">&gt;</span> File</div>
		
		<a name="jump394"></a><!-- Livedate: 12.08.2004 09:25:22 / Killdate: 31.12.2030 23:59:59 -->
<h1>File Administration</h1>
<h3>Administrating and Adding of Files</h3>

<div style="margin:15px 0 0 0;padding:0;" class="spaceBeforeCP"></div><table width="100%" cellpadding="0" cellspacing="0" border="0" class="imgTextRight">
<tr>
<td valign="top" width="10%" class="image_td2"><table width="150" border="0" cellspacing="0" cellpadding="0" >
<tr><td class="image_td2"><a href="content/images/9e298e49d0793952b9adbba020414d32.png" rel="lightbox" title="View of File Manager after the installation" target="_blank"><img src="content/images/32c968fc81aa913cdb281201042da2d3.png" width="150" height="59" border="0" class="image_img" alt="file.png" /></a></td></tr>
<tr><td align="center" class="image_caption">View of File Manager after the installation</td></tr>
</table></td>
<td valign="top" class="articleText"><p align="left">In the built-in file manager it is possible to upload images, files and document in a very simple manner. The files are then available in the different article levels.<br />
The file manager uses a windows-look-a-like file structure. So you can create your own folders, give access for all editors or only for yourself and simply upload files from your harddisk.</p>
<div align="left">&nbsp;&nbsp;</div>
<p align="left">Standard documents (Word, PDF) are marked with a corresponding icon, pictures in all known formats are shown with a thumbnail. try it, the file manager can be used very simple.&nbsp;</p>
<p>&nbsp;</p>
<table width="100%" cellspacing="5" cellpadding="1" border="0" style="">
    <tbody>
        <tr valign="top">
            <td width="50"><img border="0" alt="Upload Button" src="img/button/upload_13x13.gif" /></td>
            <td>
            <div align="left">Click here to upload a file into the root directory.</div>
            </td>
        </tr>
        <tr>
            <td><img border="0" alt="Verzeichniss anlegen" src="img/button/add_13x13.gif" /></td>
            <td>
            <div align="left">Click here to create a new directory.</div>
            </td>
        </tr>
        <tr>
            <td><img border="0" alt="Englische Hilfe" src="img/button/help_22x13.gif" /></td>
            <td>
            <div align="left">Click here to see a (english) legend of all symbols.</div>
            </td>
        </tr>
        <tr>
            <td><img border="0" alt="Alle Verzeichnisse aufklappen" src="img/button/alle_auf.gif" /></td>
            <td>
            <div align="left">Click here to enhance all folders.</div>
            </td>
        </tr>
        <tr>
            <td><img border="0" alt="Alle Verzeichnisse zuklappen" src="img/button/alle_zu.gif" /></td>
            <td>
            <div align="left">Click here to collapse all folders.</div>
            </td>
        </tr>
        <tr>
            <td><img border="0" alt="Thumbnails ausblenden" src="img/button/thumbnail_13x13_0.gif" /></td>
            <td>
            <div align="left">Click here to get a list of all files (without thumbnails).</div>
            </td>
        </tr>
    </tbody>
</table></td>
</tr>
</table>
		 
		
		<br /><br />
		<div class="sub">
		Article created: Friday, 24. August 2007 <br /> Last Changes: Tuesday, 4. January 2011	
		</div>
				
	</div>
	
<div id="footer">





	<table width="97%" border="0" cellspacing="0" cellpadding="0">
		<tr>
			<td valign="bottom">	
			&copy; phpwcms-docu 2004-2015
			<img src="img/leer.gif" border="0" width="10" height="0" alt="" /><a href="imprint.phtml" class="phpwcmsIntLink"><img src="template/lang/all/icons/imprint.gif" width="9" height="15" alt="Impressum" title="Impressum" border="0" /></a>&nbsp; 
			<a href="sitemap_en.phtml" class="phpwcmsIntLink"><img src="template/lang/all/icons/sitemap.gif" width="19" height="15" alt="Sitemap" title="Sitemap" border="0" /></a>&nbsp; 
			 
			
			     
			</td>
			<td valign="bottom" style="padding-right:25px;">
			
			
			
			</td>		
			<td width="150">
			</td>
		</tr>
	</table>
</div><br/>

</div>
</body>
</html>