<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<!--
	phpwcms | free open source content management system
	created by Oliver Georgi (oliver at phpwcms dot de) and licensed under GNU/GPL.
	phpwcms is copyright 2003-2007 of Oliver Georgi. Extensions are copyright of
	their respective owners. Visit project page for details: http://www.phpwcms.org/
//-->
<title>phpwcms-docu for  phpwcms :: web based content management system | Image Tags | Replacement Tags for Images</title>
  <meta http-equiv="content-type" content="text/html; charset=iso-8859-1" />
  <meta http-equiv="content-style-type" content="text/css" />
  <script src="template/inc_js/frontend.js" type="text/javascript"></script>
  <style type="text/css">
  <!-- 
    @import url("template/inc_css/mpl_frontend.css");
    @import url("template/inc_css/mpl_menu.css");
    @import url("template/inc_css/mpl_objects.css");
    @import url("template/inc_css/mpl_docu_en.css");
  //-->
  </style>
<meta name="Title" content="The phpWCMS Documentation" />
<meta name="author" content="Oliver Frohnert, Mario Perez Leal" />
<meta name="Publisher" content="Oliver Frohnert, Mario Perez Leal, creacion" />
<meta name="Copyright" content="Oliver Frohnert, Mario Perez Leal, creacion" />
<meta name="keywords" content="frohnert, perez leal, creacion, documentation, dokumentation, phpwcms, cms, opensource, open source, docu" />
<meta name="description" content="A Documentation Project for the  Open Source CMS phpWCMS" />
<meta name="Audience" content="Alle" />
<meta name="Content-language" content="EN" />
<meta name="robots"      content="index,follow" />
<meta name="expires" content="0" />
<meta name="revisit-after" content="7 days" />
<meta name="resource-type" content="document" />
<meta name="distribution" content="Global" />
<meta name="generator" content="PHPWCMS" />
<meta name="verify-v1" content="1ZpxZ7AZsjm7PxjqXQVus0eiUYqOsp5URTJn9q4KNz8=" />
  <!--[if lt IE 7]>
  <style type="text/css">
    body { behavior: url("template/inc_css/specific/csshover2.htc"); }
    img { behavior: url("template/inc_css/specific/pngbehavior.htc"); }
  </style>
  <![endif]-->
</head>
<body id="myid_78">
<div id="container"><a name="top" id="top"></a>


	<div id="head">
		
	<div id="mainnavi">
		<div class="fleft"><a href="english_version.phtml">Home</a> | <a href="news_en.phtml">News</a> | <span style="text-decoration:none;font-weight:bold;"><a href="the_docu.phtml">The Docu</a></span> | <a href="Usefull_Links_and_Tools.phtml">Links &amp; Tools</a> | <a href="contact.phtml">Contact</a> | <a href="faq_en.phtml">FAQ</a> | <a href="http://forum.phpwcms.org/" target="_blank">Forum</a> | <a href="howto_en.phtml">HowTo</a></div>				
		<div class="sys">Saturday, 21. February 2015<img src="img/leer.gif" border="0" width="5" height="1" alt="" />|<img src="img/leer.gif" border="0" width="5" height="1" alt="" />3 User online<img src="img/leer.gif" border="0" width="10" height="1" alt="" />
		<a href="deutsche_version.phtml" title="Deutsche Version"><img src="picture/../template/lang/all/flag_de.gif" border="0" alt="" /></a>
		<a href="english_version.phtml"  title="English version"><img src="picture/../template/lang/all/flag_en.gif" border="0" alt="" /></a>
		</div>
	</div>
	
	<a href="./" title="phpwcms-docu Startseite aufrufen" class="homelink">
	<span>&raquo; phpwcms-docu startpage</span></a>
	<h2>phpwcms-docu - Documentation for the Web Content Management System phpwcms</h2>
	<p>This website is targeted both to the beginner and the lateral entry following the goal to simplify the 
work with phpwcms and to focus on the essentials things.</p>
	</div>

	
	<div id="left">
	<div class="leftnav" style="margin-top:24px;">
	
<div id="ul_div_311">
<ul>
	<li class="sub_no"><a href="download-dev-versions.phtml">Download Dev Versions</a></li>
	<li class="sub_no sub_ul_true"><a href="installation_en.phtml">Installation &amp; Upgrade</a></li>
	<li class="sub_no sub_ul_true"><a href="article.phtml">Articles</a></li>
	<li class="sub_no sub_ul_true"><a href="file.phtml">File</a></li>
	<li class="sub_no sub_ul_true"><a href="module_en.phtml">Modules</a></li>
	<li class="sub_no sub_ul_true"><a href="communication.phtml">Communication </a></li>
	<li class="sub_no"><a href="chat_en.phtml">Chat</a></li>
	<li class="sub_no"><a href="profile.phtml">Profile</a></li>
	<li class="sub_ul"><a href="admin_en_.phtml">Admin</a>
	<div id="ul_div_312">
	<ul>
		<li class="sub_no sub_ul_true"><a href="sitestructure.phtml">Sitestructure</a></li>
		<li class="sub_no sub_ul_true"><a href="user_administration.phtml">User administration</a></li>
		<li class="sub_no"><a href="remove_delete_files.phtml">Remove delete files</a></li>
		<li class="sub_no"><a href="templating.phtml">Templating </a></li>
		<li class="sub_ul"><a href="replacement_tags_en.phtml">Replacement Tags</a>
		<div id="ul_div_75">
		<ul>
			<li class="sub_no"><a href="system_tags.phtml">System Tags</a></li>
			<li class="sub_no sub_ul_true"><a href="navigation_tags.phtml">Navigation Tags</a></li>
			<li class="sub_no"><a href="link_tags.phtml">Link Tags</a></li>
			<li class="sub_no active"><a href="image_tags.phtml">Image Tags</a></li>
			<li class="sub_no"><a href="article_tags.phtml">Article Tags</a></li>
			<li class="sub_no"><a href="language.phtml">Language</a></li>
		</ul>
		</div>
		</li>
	</ul>
	</div>
	</li>
	<li class="sub_no sub_ul_true"><a href="add-ons-and-templates.phtml">Add On&#039;s and Templates</a></li>
	<li class="sub_no"><a href="deutsche_version.phtml?replacement_tags_en">Replacement Tags</a></li>
	<li class="sub_no"><a href="deutsche_version.phtml?content_parts_en">Content Parts</a></li>
</ul>
</div>

		
	</div> 
	</div> 
	  
	<div id="right">
		<div style="margin-top:24px;">			
		<form action="index.php?search" method="post" name="searchFE" onsubmit="s=document.getElementById('customSearchInput');if(s.value=='Search')return false;">
			<table width="100%" border="0" cellpadding="0" cellspacing="0">
			<tr>
					<td><input type="text" name="search_input_field" size="20" maxlength="200" id="customSearchInput" class="customSearchInput" value="" onfocus="if(this.value=='Search')this.value='';" onblur="if(this.value=='')this.value='Search';"/></td>
					<td><input type="image" name="search_go" onfocus="this.blur();" title="Search" src="/template/lang/all/submit.gif" /></td>
				</tr>
			</table>
			</form>
			
			      <script type="text/javascript" language="javascript">
			  <!-- 
			        document.getElementById("customSearchInput").value="Search";
			  //-->
			      </script>
				  
<!-- <p style="margin-top:10px;">Change font size: <a href="[FontSize-]"><img src="template/lang/all/icons/reduce.gif" width="18" height="17" alt="" title="Small" border="0" /></a>
			<a href="[FontSize+]"><img src="template/lang/all/icons/extend.gif" width="18" height="17" alt="" title="Bigger" border="0" /></a>
			</p> -->
			
	<p style="margin-top:10px;">Please choose: 
	
	 </p>


<!-- <a href="http://validator.w3.org/check?uri=http%3A%2F%2Fwww.phpwcms-docu.de%2Findex.php%3Fdeutsche_version" title="W3C Standard XHTML" target="_blank"><img src="picture/w3c/w3c_xhtml.gif" border="0" alt="" /></a>
<a href="http://jigsaw.w3.org/css-validator/validator?uri=http://www.phpwcms-docu.de" title="W3C Standard CSS" target="_blank"><img src="picture/w3c/w3c_css.gif" border="0" alt="" /></a><br />			
<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div> -->
		
<div style="margin-top:10px; margin-bottom:15px;"></div>
	
</div>

	</div> 
	
	<div id="content">
	<div id="bread">You are here: <a href="english_version.phtml">English</a> <span class="breadcrumb_spacer">&gt;</span> <a href="the_docu.phtml">The Docu</a> <span class="breadcrumb_spacer">&gt;</span> <a href="admin_en_.phtml">Admin</a> <span class="breadcrumb_spacer">&gt;</span> <a href="replacement_tags_en.phtml">Replacement Tags</a> <span class="breadcrumb_spacer">&gt;</span> Image Tags</div>
		
		<a name="jump38"></a><!-- Livedate: 05.08.2004 19:13:17 / Killdate: 31.12.2030 23:59:59 -->
<h1>Replacement Tags for Images</h1>

<div style="margin:25px 0 0 0;padding:0;" class="spaceBeforeCP"></div><h3>Notice:</h3>All Image Replacement Tags will be linked to the Images in the Picture directory in the standard settings. So if you want to link to a picture in another directory you need to edit the link.&nbsp;<br />{<img src="img/leer.gif" border="0" width="0" height="0" alt="" />IMAGE:../content/images/picture.gif}<div style="margin:0 0 15px 0;padding:0;" class="spaceAfterCP"></div><h4>[<img src="img/leer.gif" border="0" width="0" height="0" alt="" />img=ID.FORMATxWxHxCROPxQUALITY ALT-Text]TITEL-Text[/img]</h4><table cellspacing="0" cellpadding="5" border="0" width="100%">
    <tbody bgcolor="#efefef">
        <tr>
            <td align="right" width="100" valign="top"><font color="#666666" class="v10"><strong>Use:</strong></font></td>
            <td width="5" rowspan="5"></td>
            <td valign="top">Creates an <em>&lt;img&gt;-Tag</em> with the choosen Image file. <br />
            Creates an image from filecenter (img ID) using&nbsp; the dimension, cropping, quality and alt/title-text. (since V1.3.9).</td>
        </tr>
        <tr>
            <td align="right" width="100" valign="top"><font color="#666666" class="v10"><strong>Notation:</strong></font></td>
            <td valign="top"><strong>[<img src="img/leer.gif" border="0" width="0" height="0" alt="" />img=ID.FORMATxWxHxCROPxQUALITY ALT-Text]TITLE-Text[/img]</strong></td>
        </tr>
        <tr>
            <td align="right" width="100" valign="top"><strong><font color="#666666" size="1">Result:</font></strong></td>
            <td valign="top">&nbsp;</td>
        </tr>
        <tr>
            <td align="right" width="100" valign="top"><font color="#666666" class="v10"><strong>Remark:</strong></font></td>
            <td valign="top">
            <p dir="ltr" style="margin-right: 0px;">Short form: [<img src="img/leer.gif" border="0" width="0" height="0" alt="" />img=ID.FORMATxWxHxCROPxQUALITY]<br />
            <br />
            <b>Example:</b><br />
            <br />
            [<img src="img/leer.gif" border="0" width="0" height="0" alt="" />img=1367.gifx200x200x0x80 euroboard]Europe[/img]<br />
            <br />
            Output of the picture with ID 1367 as GIF and downsized proportional to max. 200px width / 200px height, no cropping using quality 80, alt-text euroboard and the title text &quot;Europe&quot;.</p>
            </td>
        </tr>
        <tr>
            <td align="right" width="100" valign="top"></td>
            <td valign="top"></td>
        </tr>
    </tbody>
</table><div align="right"><a href="#top"><img src="img/article/top_link_0.gif" border="0" alt="" /></a></div><h4>{<img src="img/leer.gif" border="0" width="0" height="0" alt="" />IMAGE:Imagename}</h4><TABLE cellSpacing=0 cellPadding=5 width="100%" border=0>
<TBODY bgColor=#efefef>
<TR>
<TD vAlign=top align=right width=100><FONT class=v10 color=#666666><STRONG>Use:</STRONG></FONT></TD>
<TD width=5 rowSpan=5></TD>
<TD vAlign=top>Creates an <EM>&lt;img&gt;-Tag</EM> with the choosen Image file.</TD></TR>
<TR>
<TD vAlign=top align=right width=100><FONT class=v10 color=#666666><STRONG>Notation:</STRONG></FONT></TD>
<TD vAlign=top><STRONG>{<img src="img/leer.gif" border="0" width="0" height="0" alt="" />IMAGE:icon/DateiDownload.jpg}</STRONG></TD></TR>
<TR>
<TD vAlign=top align=right width=100><STRONG><FONT color=#666666 size=1>Result:</FONT></STRONG></TD>
<TD vAlign=top><img src="picture/icon/DateiDownload.jpg" border="0" alt="" /></TD></TR>
<TR>
<TD vAlign=top align=right width=100><FONT class=v10 color=#666666><STRONG>Remark:</STRONG></FONT></TD>
<TD vAlign=top>
<P dir=ltr style="MARGIN-RIGHT: 0px">The directory <STRONG>icon</STRONG> is an Subdirectory of <STRONG>picture.</STRONG><br />The complete path in in this case:<br /><br /><EM>www.my-domain.de/picture/icon/DateiDownload.jpg</EM></P></TD></TR>
<TR>
<TD vAlign=top align=right width=100><FONT class=v10 color=#666666><STRONG><EM></EM></STRONG></FONT></TD>
<TD vAlign=top><EM></EM></TD></TR></TBODY></TABLE><div align="right"><a href="#top"><img src="img/article/top_link_0.gif" border="0" alt="" /></a></div><h4>{<img src="img/leer.gif" border="0" width="0" height="0" alt="" />IMAGE_LEFT:imagename}</h4><TABLE cellSpacing=0 cellPadding=5 width="100%" border=0>
<TBODY bgColor=#efefef>
<TR>
<TD vAlign=top align=right width=100><FONT class=v10 color=#666666><STRONG>Use:</STRONG></FONT></TD>
<TD width=5 rowSpan=5></TD>
<TD vAlign=top>Creates an <EM>&lt;img&gt;-Tag</EM> with the choosen Image file.<br />The&nbsp;Image will be <EM>align left</EM>.</TD></TR>
<TR>
<TD vAlign=top align=right width=100><FONT class=v10 color=#666666><STRONG>Notation:</STRONG></FONT></TD>
<TD vAlign=top><STRONG>{<img src="img/leer.gif" border="0" width="0" height="0" alt="" />IMAGE_LEFT:Jaguar.jpg}</STRONG></TD></TR>
<TR>
<TD vAlign=top align=right width=100><STRONG><FONT color=#666666 size=1>Result:</FONT></STRONG></TD>
<TD vAlign=top><img src="picture/Jaguar.jpg" border="0" align="left" alt="" /></TD></TR>
<TR>
<TD vAlign=top align=right width=100><FONT class=v10 color=#666666><STRONG>Remark:</STRONG></FONT></TD>
<TD vAlign=top>
<P dir=ltr style="MARGIN-RIGHT: 0px">The Image&nbsp;<STRONG>Jaguar.jpg</STRONG> is stored&nbsp;<STRONG>picture </STRONG>directory.<br />The complete path to the image is in this case:<br /><br /><EM>www.meine-domain.de/picture/Jaguar.jpg</EM></P></TD></TR>
<TR>
<TD vAlign=top align=right width=100><FONT class=v10 color=#666666><STRONG></STRONG></FONT></TD>
<TD vAlign=top></TD></TR></TBODY></TABLE>&nbsp;<br /><div align="right"><a href="#top"><img src="img/article/top_link_0.gif" border="0" alt="" /></a></div><h4>{<img src="img/leer.gif" border="0" width="0" height="0" alt="" />IMAGE_RIGHT:Imagename}</h4><TABLE cellSpacing=0 cellPadding=5 width="100%" border=0>
<TBODY bgColor=#efefef>
<TR>
<TD vAlign=top align=right width=100><FONT class=v10 color=#666666><STRONG>Use:</STRONG></FONT></TD>
<TD width=5 rowSpan=5></TD>
<TD vAlign=top>Creates an <EM>&lt;img&gt;-Tag</EM> with the choosen Image file.<br />The&nbsp;Image will be <EM>align right</EM>.</TD></TR>
<TR>
<TD vAlign=top align=right width=100><FONT class=v10 color=#666666><STRONG>Notation:</STRONG></FONT></TD>
<TD vAlign=top><STRONG>{<img src="img/leer.gif" border="0" width="0" height="0" alt="" />IMAGE_RIGHT:Blatt.jpg}</STRONG></TD></TR>
<TR>
<TD vAlign=top align=right width=100><STRONG><FONT color=#666666 size=1>Result:</FONT></STRONG></TD>
<TD vAlign=top><img src="picture/Blatt.jpg" border="0" align="right" alt="" /></TD></TR>
<TR>
<TD vAlign=top align=right width=100><FONT class=v10 color=#666666><STRONG>Remark:</STRONG></FONT></TD>
<TD vAlign=top>
<P dir=ltr style="MARGIN-RIGHT: 0px">The Image&nbsp;<STRONG>Blatt.jpg</STRONG>&nbsp;is stored in the&nbsp;<STRONG>picture </STRONG>directory.<br />The complete path to the image is in this case:<br /><br /><EM>www.my-domain.de/picture/Blatt.jpg</EM></P></TD></TR>
<TR>
<TD vAlign=top align=right width=100><FONT class=v10 color=#666666><STRONG></STRONG></FONT></TD>
<TD vAlign=top></TD></TR></TBODY></TABLE>&nbsp;<br /><div align="right"><a href="#top"><img src="img/article/top_link_0.gif" border="0" alt="" /></a></div><h4>{<img src="img/leer.gif" border="0" width="0" height="0" alt="" />RANDOM:Image_Pfad}</h4><TABLE cellSpacing=0 cellPadding=5 width="100%" border=0>
<TBODY bgColor=#efefef>
<TR>
<TD vAlign=top align=right width=100><FONT class=v10 color=#666666><STRONG>Use:</STRONG></FONT></TD>
<TD width=5 rowSpan=5></TD>
<TD vAlign=top>Create an <EM>&lt;img&gt;-Tag</EM>&nbsp;for Radom Images&nbsp;from a specified folder.&nbsp;<br />At every Pagerequest it will be shown a new image.</TD></TR>
<TR>
<TD vAlign=top align=right width=100><FONT class=v10 color=#666666><STRONG>Notation:</STRONG></FONT></TD>
<TD vAlign=top><STRONG>{<img src="img/leer.gif" border="0" width="0" height="0" alt="" />RANDOM:picture/random_175}</STRONG></TD></TR>
<TR>
<TD vAlign=top align=right width=100><STRONG><FONT color=#666666 size=1>Result:</FONT></STRONG></TD>
<TD vAlign=top><img src="picture/random_175/a2.gif" width="200" height="150" border="0" alt="a2.gif" /></TD></TR>
<TR>
<TD vAlign=top align=right width=100><FONT class=v10 color=#666666><STRONG>Remark:</STRONG></FONT></TD>
<TD vAlign=top>
<P dir=ltr style="MARGIN-RIGHT: 0px">The directory&nbsp;<STRONG>random</STRONG>&nbsp;is an subdirectory of&nbsp;<STRONG>picture.</STRONG><br />The complete path to the image is in this case:<br /><br /><EM>www.my-domain.de/picture/random_175/</EM></P></TD></TR>
<TR>
<TD vAlign=top align=right width=100><FONT class=v10 color=#666666><STRONG></STRONG></FONT></TD>
<TD vAlign=top>The Images in the Random folder should&nbsp;have the same dimensions.</TD></TR></TBODY></TABLE>&nbsp;<br /><div align="right"><a href="#top"><img src="img/article/top_link_0.gif" border="0" alt="" /></a></div><h4>{<img src="img/leer.gif" border="0" width="0" height="0" alt="" />SPACER:px-Width x px-Height}</h4><TABLE cellSpacing=0 cellPadding=5 width="100%" border=0>
<TBODY bgColor=#efefef>
<TR>
<TD vAlign=top align=right width=100><FONT class=v10 color=#666666><STRONG>Use:</STRONG></FONT></TD>
<TD width=5 rowSpan=5></TD>
<TD vAlign=top>Creates an Transparent Image.&nbsp;<br />Width and height value in px.</TD></TR>
<TR>
<TD vAlign=top align=right width=100><FONT class=v10 color=#666666><STRONG>Notation:</STRONG></FONT></TD>
<TD vAlign=top><STRONG>{<img src="img/leer.gif" border="0" width="0" height="0" alt="" />SPACER:250x5}<br /></STRONG><br /><br /><STRONG>Example:<br /></STRONG><br />Start&nbsp;<STRONG>-|</STRONG>{<img src="img/leer.gif" border="0" width="0" height="0" alt="" />SPACER:250x5}<STRONG>|-</STRONG> End</TD></TR>
<TR>
<TD vAlign=top align=right width=100><STRONG><FONT color=#666666 size=1>Result:</FONT></STRONG></TD>
<TD vAlign=top>Start&nbsp;<STRONG>-|</STRONG><img src="img/leer.gif" border="0" width="250" height="5" alt="" /><STRONG>|-</STRONG> End</TD></TR>
<TR>
<TD vAlign=top align=right width=100><FONT class=v10 color=#666666><STRONG>Remark:</STRONG></FONT></TD>
<TD vAlign=top>The space between the both marks&nbsp;<STRONG>-|</STRONG>&nbsp; <STRONG>|-</STRONG>&nbsp;is in this case set to <STRONG>250 px</STRONG>.</TD></TR>
<TR>
<TD vAlign=top align=right width=100><FONT class=v10 color=#666666><STRONG></STRONG></FONT></TD>
<TD vAlign=top></TD></TR></TBODY></TABLE><div align="right"><a href="#top"><img src="img/article/top_link_0.gif" border="0" alt="" /></a></div>
		 
		
		<br /><br />
		<div class="sub">
		Article created: Friday, 6. August 2004 <br /> Last Changes: Tuesday, 4. January 2011	
		</div>
				
	</div>
	
<div id="footer"><br /><br />
<p style="height:30px;">&nbsp;</p>


 <script type="text/javascript" language="javascript">
<!--

var showDefaultValue =  0

function hideLayer(whichLayer) {
	if (document.getElementById) {
		// this is the way the standards work
		document.getElementById(whichLayer).style.display = "none";
	} else if (document.all) {
		// this is the way old msie versions work
		document.all[whichlayer].style.display = "none";
	} else if (document.layers) {
		// this is the way nn4 works
		document.layers[whichLayer].display = "none";
	}
}

function showLayer(whichLayer) {
		//	alert(whichLayer);
	if (document.getElementById) {
		// this is the way the standards work
		document.getElementById(whichLayer).style.display = "block";
	}
	else if (document.all) {
		// this is the way old msie versions work
		document.all[whichlayer].style.display = "block";
	}
	else if (document.layers) {
		// this is the way nn4 works
		document.layers[whichLayer].display = "block";
	}
}

function toggleLayer(whichLayer) {
	if(showDefaultValue == 0) {
		hideLayer(whichLayer);
		showDefaultValue = 1;
	} else {
		showLayer(whichLayer);
		showDefaultValue = 0;
	}
}
//-->
</script>


<div id="alles">
<div id="klapper" onclick="toggleLayer('formular');">
<table width="570" border="0" cellspacing="0" cellpadding="0">
<tr>
<td><em style="color:#275EA8;" onmouseover="this.style.color='#4F96F4';" onmouseout="this.style.color='#275EA8';">You have suggestions or criticism to this article? Write us!</em></td>   
<td align="right" style="padding-right:2px;"><img src="template/lang/all/icons/write.gif" width="16" height="21" alt="" border="0" /></td>
</tr>
</table>

</div>
<div id="formular">

<form name="form" method="post" action="index.php?id=78,38,0,1,1,0" style="margin:0;padding:0;"><input type="hidden" name="customForm" value="1" /><input type="hidden" name="docucheck" value="1" />


<div style="float:left;">
<p><select name="Betreff" id="Betreff" class="size1">
<option value="" class="deepblue"> Select </option>

</select><br /></p>


<p>Firstname:<br />
<input type="text" name="Vorname" value="" class="size1" /></p>
<p>Surname:*<br />
<input type="text" name="Name" value="" class="size1" /></p>
<p>E-Mail:*<br />
<input type="text" name="E-Mail" value="" class="size1" /></p>
</div>


<div style="float:right;">Message:*<br />
<textarea name="Nachricht" cols="40" rows="4"  class="size7"></textarea>
</div>

<p style="clear:both; text-align:right;"><input type="reset" name="reset" value="Reset" class="btstyle" style="width:100px;" />&nbsp;&nbsp;
<input type="submit" name="submit" value="Send email" class="btstyle" style="width:110px;" /></p>
<p style="margin:20px;" class="sub">* Required fields.<br />Your data is used exclusively for this inquiry.</p>

</form>
</div>
</div>
 <script type="text/javascript" language="javascript">
<!--
	// Lösung ohne Onload
	toggleLayer('formular');
//-->
</script>
<br />





	<table width="97%" border="0" cellspacing="0" cellpadding="0">
		<tr>
			<td valign="bottom">	
			&copy; phpwcms-docu 2004-2015
			<img src="img/leer.gif" border="0" width="10" height="0" alt="" /><a href="imprint.phtml" class="phpwcmsIntLink"><img src="template/lang/all/icons/imprint.gif" width="9" height="15" alt="Impressum" title="Impressum" border="0" /></a>&nbsp; 
			<a href="sitemap_en.phtml" class="phpwcmsIntLink"><img src="template/lang/all/icons/sitemap.gif" width="19" height="15" alt="Sitemap" title="Sitemap" border="0" /></a>&nbsp; 
			 
			
			     
			</td>
			<td valign="bottom" style="padding-right:25px;">
			
			
			
			</td>		
			<td width="150">
			</td>
		</tr>
	</table>
</div><br/>

</div>
</body>
</html>