<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<!--
	phpwcms | free open source content management system
	created by Oliver Georgi (oliver at phpwcms dot de) and licensed under GNU/GPL.
	phpwcms is copyright 2003-2007 of Oliver Georgi. Extensions are copyright of
	their respective owners. Visit project page for details: http://www.phpwcms.org/
//-->
<title>phpwcms-docu for  phpwcms :: web based content management system | Newsletter Abonnenten{D:8/13/2007,30,neuR.gif} | Newsletter Abonnenten</title>
  <meta http-equiv="content-type" content="text/html; charset=iso-8859-1" />
  <meta http-equiv="content-style-type" content="text/css" />
  <script src="template/inc_js/frontend.js" type="text/javascript"></script>
  <style type="text/css">
  <!-- 
    @import url("template/inc_css/mpl_docu.css");
    @import url("template/inc_css/mpl_frontend.css");
    @import url("template/inc_css/mpl_menu.css");
    @import url("template/inc_css/mpl_objects.css");
  //-->
  </style>
<script type="text/javascript" language="javascript">
<!--
function MM_jumpMenu(targ,selObj,restore){ //v3.0
  eval(targ+".location='"+selObj.options[selObj.selectedIndex].value+"'");
  if (restore) selObj.selectedIndex=0;
}

function MM_findObj(n, d) { //v4.01
  var p,i,x;  if(!d) d=document; if((p=n.indexOf("?"))>0&&parent.frames.length) {
    d=parent.frames[n.substring(p+1)].document; n=n.substring(0,p);}
  if(!(x=d[n])&&d.all) x=d.all[n]; for (i=0;!x&&i<d.forms.length;i++) x=d.forms[i][n];
  for(i=0;!x&&d.layers&&i<d.layers.length;i++) x=MM_findObj(n,d.layers[i].document);
  if(!x && d.getElementById) x=d.getElementById(n); return x;
}

function MM_jumpMenuGo(selName,targ,restore){ //v3.0
  var selObj = MM_findObj(selName); if (selObj) MM_jumpMenu(targ,selObj,restore);
}
//-->
</script>
<meta name="Title" content="Die phpWCMS Dokumentation" />
<meta name="author" content="Oliver Frohnert, Mario Perez Leal" />
<meta name="Publisher" content="Oliver Frohnert, Mario Perez Leal, creacion" />
<meta name="Copyright" content="Oliver Frohnert, Mario Perez Leal, creacion" />
<meta name="keywords" content="frohnert, perez leal, creacion, documentation, dokumentation, phpwcms, cms, opensource, open source, docu" />
<meta name="description" content="Das Dokumentations Projekt für das Open Source CMS phpWCMS" />
<meta name="Audience" content="Alle" />
<meta name="Content-language" content="DE" />
<meta name="robots" content="index,follow" />
<meta name="expires" content="0" />
<meta name="revisit-after" content="7 days" />
<meta name="resource-type" content="document" />
<meta name="distribution" content="Global" />
<meta name="generator" content="PHPWCMS" />
<meta name="verify-v1" content="1ZpxZ7AZsjm7PxjqXQVus0eiUYqOsp5URTJn9q4KNz8=" />
  <link rel="stylesheet" href="template/slimbox/css/slimbox.css" type="text/css" media="screen" />
  <script src="template/inc_js/mootools/mootools.js" type="text/javascript"></script>
  <script src="template/slimbox/js/slimbox.js" type="text/javascript"></script>
  <!--[if lt IE 7]>
  <style type="text/css">
    body { behavior: url("template/inc_css/specific/csshover2.htc"); }
    img { behavior: url("template/inc_css/specific/pngbehavior.htc"); }
  </style>
  <![endif]-->
</head>
<body id="myid_416">
<div id="container"><a name="top" id="top"></a>


	<div id="head">
		
	<div id="mainnavi">
		<div class="fleft"><a href="deutsche_version.phtml">Startseite</a> | <a href="news_de.phtml">News</a> | <span style="text-decoration:none;font-weight:bold;"><a href="die_docu.phtml">Die Docu</a></span> | <a href="Nuetzliche_Links_und_Tools.phtml">Links &amp; Tools</a> | <a href="downloads.phtml">Downloads</a> | <a href="kontakt.phtml">Kontakt</a> | <a href="faq_de.phtml">FAQ</a> | <a href="http://forum.phpwcms.org/" target="_blank">Forum</a> | <a href="howto_de.phtml">HowTo</a></div>				
		<div class="sys">Samstag, 23. Februar 2013<img src="img/leer.gif" border="0" width="5" height="1" alt="" />|<img src="img/leer.gif" border="0" width="5" height="1" alt="" />4 User online<img src="img/leer.gif" border="0" width="10" height="1" alt="" />
		<a href="deutsche_version.phtml" title="Deutsche Version"><img src="picture/../template/lang/all/flag_de.gif" border="0" alt="" /></a>
		<a href="english_version.phtml"  title="English version"><img src="picture/../template/lang/all/flag_en.gif" border="0" alt="" /></a>
		</div>
	</div>
	
	<a href="./" title="phpwcms-docu Startseite aufrufen" class="homelink">
	<span>&raquo; Zur phpwcms-docu Startseite</span></a>
	<h2>phpwcms-docu - Die Dokumentation f&uuml;r f&uuml;r das CMS phpWCMS</h2>
	<p>phpwcms-docu ist eine Art Kompass, der Ihnen die M&ouml;glichkeiten von phpWcms aufzeigt und Sie erfolgreich, ohne gro&szlig;e Umwege, zu Ihrer fertigen Web-Anwendung f&uuml;hren soll.
	</p>
	</div>

	
	<div id="left">
	<div class="leftnav" style="margin-top:24px;">
	
<div id="ul_div_309">
<ul>
	<li class="sub_no"><a href="download-dev-versionen.phtml">Download Dev Versionen</a></li>
	<li class="sub_no sub_ul_true"><a href="installation_und_upgrade_von_phpwcms.phtml">Installation &amp; Upgrade</a></li>
	<li class="sub_no sub_ul_true"><a href="verwaltung_artikel.phtml">Artikel</a></li>
	<li class="sub_no sub_ul_true"><a href="dateizentrale.phtml">Datei</a></li>
	<li class="sub_no sub_ul_true"><a href="verwaltung_module.phtml">Module</a></li>
	<li class="sub_ul"><a href="Kommunikation.phtml">Kommunikation</a>
	<div id="ul_div_381">
	<ul>
		<li class="sub_no"><a href="kommunikation_newsletter.phtml"><span style="text-decoration:line-through;font-size:10px;">Newsletter</span></a></li>
		<li class="sub_no active"><a href="kommunikation_newsletter_abonnenten.phtml">Newsletter Abonnenten</a></li>
		<li class="sub_no"><a href="kommunikation_newsletter_abonnoment.phtml">Newsletter Abonnoment</a></li>
		<li class="sub_no"><a href="kommunikation_nachrichtenzentrale.phtml">Nachrichtenzentrale</a></li>
		<li class="sub_no"><a href="kommunikation_neue_nachricht.phtml">Neue Nachricht</a></li>
	</ul>
	</div>
	</li>
	<li class="sub_no"><a href="verwaltung_nachricht.phtml">Nachricht</a></li>
	<li class="sub_no"><a href="verwaltung_chat.phtml">Chat</a></li>
	<li class="sub_no"><a href="verwaltung_profil.phtml">Profil</a></li>
	<li class="sub_no sub_ul_true"><a href="verwaltung_admin.phtml">Admin</a></li>
	<li class="sub_no sub_ul_true"><a href="add-on-und-vorlagen.phtml">Add Ons und Vorlagen</a></li>
	<li class="sub_no"><a href="deutsche_version.phtml?replacement_tags_de">Replacement Tags</a></li>
	<li class="sub_no"><a href="deutsche_version.phtml?content_parts_de">Content Parts</a></li>
</ul>
</div>

		
		
		

	</div> 
	</div> 
	  
	<div id="right">
		<div style="margin-top:24px;">			
		<form action="index.php?suche" method="post" name="searchFE" onsubmit="s=document.getElementById('customSearchInput');if(s.value=='Suchen')return false;">
			<table width="100%" border="0" cellpadding="0" cellspacing="0">
			<tr>
					<td><input type="text" name="search_input_field" size="20" maxlength="200" id="customSearchInput" class="customSearchInput" value="" onfocus="if(this.value=='Suchen')this.value='';" onblur="if(this.value=='')this.value='Suchen';" /></td>
					<td><input type="image" name="search_go" onfocus="this.blur();" title="Suchen" src="/template/lang/all/submit.gif" /></td>
				</tr>
			</table>
			</form>
			
			      <script type="text/javascript" language="javascript">
			  <!-- 
			        document.getElementById("customSearchInput").value="Suchen";
			  //-->
			      </script>
				  
			<!-- <p style="margin-top:10px;">Schriftgrad &auml;ndern: <a href="[FontSize-]"><img src="template/lang/all/icons/reduce.gif" width="18" height="17" alt="" title="Verkleinern" border="0" /></a>
			<a href="[FontSize+]"><img src="template/lang/all/icons/extend.gif" width="18" height="17" alt="" title="Vergr&ouml;&szlig;ern" border="0" /></a>
			</p> -->
			
	<p style="margin-top:10px;">Bitte w&auml;hlen Sie: 
	
	 </p>
<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div>


<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div>
<!-- <a href="http://validator.w3.org/check?uri=http%3A%2F%2Fwww.phpwcms-docu.de%2Findex.php%3Fdeutsche_version" title="W3C Standard XHTML" target="_blank"><img src="picture/w3c/w3c_xhtml.gif" border="0" alt="" /></a>
<a href="http://jigsaw.w3.org/css-validator/validator?uri=http://www.phpwcms-docu.de" title="W3C Standard CSS" target="_blank"><img src="picture/w3c/w3c_css.gif" border="0" alt="" /></a><br />			
<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div> -->
<h3>Partnersites</h3>






<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div>

<div style="margin-top:10px; margin-bottom:15px;"></div>


<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div>
</div>

	</div> 
	
	<div id="content">
	<div id="bread">Sie sind hier: <a href="deutsche_version.phtml">Deutsch</a> <span class="breadcrumb_spacer">&gt;</span> <a href="die_docu.phtml">Die Docu</a> <span class="breadcrumb_spacer">&gt;</span> <a href="Kommunikation.phtml">Kommunikation</a> <span class="breadcrumb_spacer">&gt;</span> Newsletter Abonnenten</div>
		
		<a name="jump392"></a><!-- Livedate: 13.08.2007 00:40:46 / Killdate: 10.08.2017 23:59:59 -->
<h1>Newsletter Abonnenten</h1>

<h3>Übersicht</h3><table width="100%" cellpadding="0" cellspacing="0" border="0" class="imgTextRight">
<tr>
<td valign="top" width="10%" class="image_td2"><div class="imgDIVblockImgLeft"><div class="image_td2"><a href="content/images/ae3aa21949ff093258432081d241c4c0.png" rel="lightbox" title="Bild 1 - Newsletter Abonnenten" target="_blank"><img src="content/images/cbc895cbfdf5c3bf0bd9bd8df619843a.png" width="150" height="59" border="0" class="image_img" alt="newsletter_abonnenten.png" /></a></div><p class="image_caption">Bild 1 - Newsletter Abonnenten</p></div></td>
<td valign="top" class="articleText"><p>In diesem Bereich Verwalten Sie Ihre Newsletter Abonnenten. D.h. Sie k&ouml;nnen <a href="#cpid1800">neue Abonnenten zuf&uuml;gen</a> <img border="0" alt="Abonnementen hinzuf&uuml;gen" src="./img/famfamfam/silk_icons_gif/vcard_add.gif" />,&nbsp; <a href="#cpid1803">doppelte Empf&auml;nger l&ouml;schen</a>&nbsp;<img alt="Doppelte Empf&auml;nger l&ouml;schen" src="./img/famfamfam/silk_icons_gif/vcard_delete.gif" /> , <a href="#cpid1808">Empf&auml;nger importieren </a><img alt="Empf&auml;nger Importieren" src="./img/famfamfam/silk_icons_gif/table_add.gif" /> und in eine <a href="#cpid1807">Excel Datei exportieren </a><img alt="Empf&auml;nger Exportieren" src="./img/famfamfam/mini/icon_download.gif" />.<br />
<br />
Dar&uuml;berhinaus k&ouml;nnen Sie &uuml;ber diese Ansicht nach angemeldeten Usern suchen. bzw. auf Aktive oder Inaktive Newsletter Abonnenten einen Filter setzten. <br />
<br />
<strong> Sie haben folgende M&ouml;glichkeiten:</strong></p>
<table width="100%" cellspacing="0" cellpadding="6" border="0">
    <tbody>
        <tr class="tbfield">
            <td width="50"><strong><img alt="Filter auf Aktive Empf&auml;nger" src="./img/button/aktiv_12x13_1.gif" /></strong></td>
            <td>Durch setzten dieses Filters sehen Sie nur Abonnementen die den Newsletter erhalten. Da Sie die Verifizierung durchgef&uuml;hrt&nbsp; haben um den Newsletter zu erhalten.</td>
        </tr>
        <tr>
            <td><img alt="Filter auf Inaktive Empf&auml;nger" src="./img/button/aktiv_12x13_0.gif" /></td>
            <td>Durch setzten dieses Filters sehen Sie nur Abonnementen die den Newsletter nicht erhalten. Da Sie die Verifizierung nicht durchgef&uuml;hrt haben.</td>
        </tr>
        <tr class="tbfield">
            <td><strong>&nbsp;<img alt="Icon" src="./img/symbole/newsletter_susbcription.gif" /></strong></td>
            <td>&nbsp;</td>
        </tr>
        <tr>
            <td>&nbsp;<strong><img alt="filter feld" src="/picture/upload/filter.png" /></strong></td>
            <td>Geben Sie hier einen Namen, eine Emailadresse ein und bestimmen Sie so Ihren eigenen Filter.</td>
        </tr>
    </tbody>
</table>
<p>Am Ende der Zeile k&ouml;nnen Sie ausserdem ausw&auml;hlen wieviele Newsletterempf&auml;nger angezeigt werden sollen, Sie haben die Auswahl zwischen &quot;<strong>10  25  50  100  250  Alle</strong>&quot;.</p></td>
</tr>
</table><div style="border-bottom:1px dotted #d2e2f5; margin-top:10px; margin-bottom:15px;"></div><a name="cpid1800" id="cpid1800" class="cpidClass"></a><h3><img src="picture/../img/famfamfam/silk_icons_gif/vcard_add.gif" border="0" alt="" /> Neuen Empfänger anlegen</h3>
<table border="0" cellspacing="0" width="10%" cellpadding="0" align="left" class=" imgListTableLeft" summary="">
<tr>
	<td class="imagelisttd2"><a href="content/images/ae3aa21949ff093258432081d241c4c0.png" rel="lightbox[wxJhJ]" title="Bild 1 -&lt;br /&gt;Newsletter Abonnenten Übersicht leer" target="_blank"><img src="content/images/988752f34d1777b3843455d80991d5cf.png" width="150" height="59" border="0" class="imagelistimg" alt="newsletter_abonnenten.png" /></a></td>
</tr>
<tr>
	<td class="imglistcaption">Bild 1 -<br />Newsletter Abonnenten Übersicht leer</td>
</tr>

<tr>
	<td class="imagelistSpacerRow"><img src="img/leer.gif" width="1" height="1" border="0" alt="" /></td>
</tr>
<tr>
	<td class="imagelisttd2"><a href="content/images/5bc7aa0d4430bd00dacd2fe79e3b2b56.png" rel="lightbox[wxJhJ]" title="Bild 2 -&lt;br /&gt;Newsletter Abonnenten Eingabemaske" target="_blank"><img src="content/images/85d752efb092c725578099648d92dcaa.png" width="150" height="74" border="0" class="imagelistimg" alt="Newsletter_Abonnenten1.png" /></a></td>
</tr>
<tr>
	<td class="imglistcaption">Bild 2 -<br />Newsletter Abonnenten Eingabemaske</td>
</tr>

<tr>
	<td class="imagelistSpacerRow"><img src="img/leer.gif" width="1" height="1" border="0" alt="" /></td>
</tr>
<tr>
	<td class="imagelisttd2"><a href="content/images/a80c8752c9872db71cfd38df574699b0.png" rel="lightbox[wxJhJ]" title="Bild 3 -&lt;br /&gt;Newsletter Abonnenten Übersicht mit Empfänger" target="_blank"><img src="content/images/cd414a0cea319370893a5e3b455e6e93.png" width="150" height="59" border="0" class="imagelistimg" alt="Newsletter_Abonnenten2.png" /></a></td>
</tr>
<tr>
	<td class="imglistcaption">Bild 3 -<br />Newsletter Abonnenten Übersicht mit Empfänger</td>
</tr>
</table>
<a name="cpid1799" id="cpid1799" class="cpidClass"></a><p>Um einen Neuen Empf&auml;nger hinzuzuf&uuml;gen Klicken Sie auf <br />
&quot; <strong>Neuer Empf&auml;nger</strong>&quot; (Bild 1).<br />
<br />
Es erscheint eine Eingabemaske (Bild 2).<br />
<strong>Dort sehen Sie folgende Felder:</strong></p>
<table cellspacing="0" cellpadding="6" border="0">
    <tbody>
        <tr class="tbfield">
            <td width="50"><strong>E-mail</strong></td>
            <td>Geben Sie hier die Emailadresse des neuen Empf&auml;ngers ein</td>
        </tr>
        <tr>
            <td><strong>Name</strong></td>
            <td>Geben Sie hier den Namen des neuen Empf&auml;ngers ein</td>
        </tr>
        <tr class="tbfield">
            <td><strong>Abos/Kanal</strong></td>
            <td>Hier w&auml;hlen Sie den / die Newsletter aus die der Empf&auml;nger erhalten will. Wenn der Empf&auml;nger alle Newsletter erhalten m&ouml;chte w&auml;hlen Sie hier&nbsp; &quot;<strong>Alle Abonnements</strong>&quot; ansonsten w&auml;hlen Sie den Newsletter aus den er erhalten m&ouml;chte. Eine Auflistung aller verf&uuml;gbaren Newsletter sehen Sie unter &quot;Alle Abonnements&quot; in diesem Beispiel wird nur ein Newsletter mit dem Titel &quot;phpwcms-docu News&quot; angeboten.</td>
        </tr>
        <tr>
            <td><strong>Status</strong></td>
            <td>Setzten Sie hier einen Haken damit der Empf&auml;nger Aktiv ist und somit den Newsletter auch erh&auml;lt.</td>
        </tr>
    </tbody>
</table>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>Dr&uuml;cken Sie zum endg&uuml;ltigem Anlegen des Empf&auml;ngers auf &quot;<strong>Erstellen</strong>&quot;&nbsp; oder &quot;<strong>Speichern</strong>&quot;. Der Unterschied zwischen den Feldern ist. Das Sie bei &quot;<strong>Erstellen</strong>&quot; in der Eingabemaske bleiben (Bild 2). Bei &quot;<strong>Speichern</strong>&quot; gelangen Sie zur&uuml;ck zur Abonnenten&uuml;bersicht (Bild 3) wo Sie nun auch den gerade erstellten Empf&auml;nger sehen k&ouml;nnen.<br />
<br />
In dieser &Uuml;bersicht sehen Sie neben der Emailadresse und dem Namen, am Ende der Zeile folgende Symbole.</p>
<p>&nbsp;</p>
<table width="100%" cellspacing="0" cellpadding="6" border="0">
    <tbody>
        <tr class="tbfield">
            <td width="50"><strong>&nbsp;<img src="./upgrade/img/button/edit_22x13.gif" alt="Empf&auml;nger bearbeiten" /></strong></td>
            <td>Durch Klicken auf dieses Symbol k&ouml;nnen Sie die Empf&auml;ngerangaben bearbeiten</td>
        </tr>
        <tr>
            <td>&nbsp;<img src="./upgrade/img/button/aktiv_12x13_1.gif" alt="Empf&auml;nger Aktiv" /> /&nbsp;<img src="./upgrade/img/button/aktiv_12x13_0.gif" alt="Empf&auml;nger Inaktiv" /></td>
            <td>Durch Klicken auf die Symbole k&ouml;nnen Sie den Empf&auml;nger&nbsp; Aktiv oder Inaktiv (er erh&auml;lt dann keinen Newsletter mehr) schalten.</td>
        </tr>
        <tr class="tbfield">
            <td align="center">&nbsp;<img src="./upgrade/img/button/trash_13x13_1.gif" alt="Empf&auml;nger L&ouml;schen" /></td>
            <td>Empf&auml;nger aus der Liste l&ouml;schen.</td>
        </tr>
    </tbody>
</table><div align="right"><a href="#top"><img src="img/article/top_link_0.gif" border="0" alt="" /></a></div><a name="cpid1803" id="cpid1803" class="cpidClass"></a><h3><img src="picture/../img/famfamfam/silk_icons_gif/vcard_delete.gif" border="0" alt="" /> Duplikate löschen</h3><h4>Doppelte Emailadressen entfernen</h4><table width="100%" cellpadding="0" cellspacing="0" border="0" class="imgTextRight">
<tr>
<td valign="top" width="10%" class="image_td2"><div class="imgDIVblockImgLeft"><div class="image_td2"><a href="content/images/de77eecc2da896e82bff8f60ae7e27c4.png" rel="lightbox" title="Bild 1 - Duplikate löschen" target="_blank"><img src="content/images/0edba84873394303bfdfa6810fbe45ac.png" width="150" height="65" border="0" class="image_img" alt="duplikate_löschen.png" /></a></div><p class="image_caption">Bild 1 - Duplikate löschen</p></div></td>
<td valign="top" class="articleText"><p>Durch Klicken auf &quot;<strong>Duplikate l&ouml;schen</strong>&quot; k&ouml;nnen Sie doppelte Newsletter Anmeldungen aus der Empf&auml;ngerliste l&ouml;schen. Nachdem Sie auf &quot;<strong>Duplikate l&ouml;schen</strong>&quot; geklickt haben, &ouml;ffnet sich ein neues Fenster (Bild 1).</p>
<p>Mit &quot;<strong>OK</strong>&quot; best&auml;tigen Sie den Vorgang und es werden alle Duplikate gel&ouml;scht. Mit &quot;Abbrechen&quot; schlie&szlig;t sich das Fenster ohne das &Auml;nderungen vorgenommen werden.</p></td>
</tr>
</table><div align="right"><a href="#top"><img src="img/article/top_link_0.gif" border="0" alt="" /></a></div><div style="border-bottom:1px dotted #d2e2f5; margin-top:10px; margin-bottom:15px;"></div><a name="cpid1808" id="cpid1808" class="cpidClass"></a><h3><img src="picture/../img/famfamfam/silk_icons_gif/table_add.gif" border="0" alt="" /> Import</h3><h4>Empfängerliste importieren</h4>
<table border="0" cellspacing="0" width="10%" cellpadding="0" align="left" class=" imgListTableLeft" summary="">
<tr>
	<td class="imagelisttd2"><a href="content/images/ea358c3037cd7e0226cc277bfc79d897.png" rel="lightbox[8BRTd]" title="Bild 1 -&lt;br /&gt;Abonnenten Importieren" target="_blank"><img src="content/images/c0ae46f395be26db4090f82028b8e165.png" width="150" height="89" border="0" class="imagelistimg" alt="Newsletter_Abonnenten_import.png" /></a></td>
</tr>
<tr>
	<td class="imglistcaption">Bild 1 -<br />Abonnenten Importieren</td>
</tr>

<tr>
	<td class="imagelistSpacerRow"><img src="img/leer.gif" width="1" height="1" border="0" alt="" /></td>
</tr>
<tr>
	<td class="imagelisttd2"><a href="content/images/29302574a234ee8a8c776bb307b7779a.png" rel="lightbox[8BRTd]" title="Bild 2 -&lt;br /&gt; Import bestätigung" target="_blank"><img src="content/images/784c3fad90ad88a52e7f6ab36d86f15d.png" width="150" height="47" border="0" class="imagelistimg" alt="Newsletter_Abonnenten_import1.png" /></a></td>
</tr>
<tr>
	<td class="imglistcaption">Bild 2 -<br /> Import bestätigung</td>
</tr>
</table>
<p>&Uuml;ber den Punkt &quot;<strong>Import</strong>&quot; haben Sie die m&ouml;glichkeit mit einer CSV oder TXT Datei Newsletter Empf&auml;nger zuzuf&uuml;gen.<br />
<br />
Um eine CSV/Text Datei zu Importieren (Bild 1) dr&uuml;cken Sie Bitte auf &quot;<strong>Durchsuchen</strong>&quot; und w&auml;hlen Sie die gew&uuml;nschte Datei auf ihrer Festplatte aus.<br />
<br />
Wenn Sie eine CSV Datei Importieren wollen muss der Inhalt der Datei wie folgt aussehen.<br />
<br />
<strong>Email1;Empf&auml;ngername1<br />
Email2;Empf&auml;ngername2<br />
Email3;Empf&auml;ngername3 .... usw</strong>   <br />
<br />
Wenn Sie eine TXT Datei Importieren wollen muss der Inhalt der Datei wie folgt aussehen<br />
<br />
&quot;<strong>Email1&quot;;&quot;Empf&auml;ngername1&quot;<br />
&quot;Email2&quot;;&quot;Empf&auml;ngername2&quot;<br />
&quot;Email3&quot;;&quot;Empf&auml;ngername3&quot;.... usw</strong>   <br />
<br />
Als Trenner der Datens&auml;tze ist bei beiden ein ; (semikolon) definiert. Falls Ihre Datei einen anderen Trenner verwendet. So &auml;ndern Sie es Bitte im Feld &quot;<strong>Delimeter</strong>&quot;.<br />
<br />
W&auml;hlen Sie nun Bitte aus welchen Newsletter die Empf&auml;nger erhalten sollen. Dies tun Sie indem Sie bei &quot;<strong>Abos/Kanal</strong>&quot; den gew&uuml;nschten Newsletter ausw&auml;hlen. <br />
<br />
Zum Abschlu&szlig; setzten Sie den Haken bei Status &quot;<strong>Aktiviert</strong>&quot; somit gelten die Empf&auml;nger als Verifiziert und erhalten ab sofort den Newsletter.<br />
<br />
Klicken Sie auf &quot;<strong>Import</strong>&quot; um den Vorgang zu starten. Durch Klicken auf &quot;<strong>Schliessen</strong>&quot; verwerfen Sie diesen Vorgang und keine Empf&auml;nger werden Importiert.<br />
<br />
Nachdem Sie auf &quot;<strong>Import</strong>&quot; geklickt haben sehen Sie eine &Uuml;bersicht wieviele Adressen Importiert wurden (Bild 2) desweiteren werden dort auch Fehler ausgegeben. Wenn die Datei nicht korrekt erstellt wurde.<br />
<br />
Druch dr&uuml;cken auf &quot;Schliessen&quot; gelangen Sie wieder zur&uuml;ck zu Abonnenten&uuml;bersicht.</p><div align="right"><a href="#top"><img src="img/article/top_link_0.gif" border="0" alt="" /></a></div><div style="border-bottom:1px dotted #d2e2f5; margin-top:10px; margin-bottom:15px;"></div><a name="cpid1807" id="cpid1807" class="cpidClass"></a><h3><img src="picture/../img/famfamfam/mini/icon_download.gif" border="0" alt="" /> Auswahl exportieren</h3><h4>Empfängerliste exportieren</h4><table width="100%" cellpadding="0" cellspacing="0" border="0" class="imgTextRight">
<tr>
<td valign="top" width="10%" class="image_td2"><div class="imgDIVblockImgLeft"><div class="image_td2"><a href="content/images/61e12c7eff3548c15e211fa41f018c84.png" rel="lightbox" title="Bild 1 -&lt;br /&gt;Newsletter Abonnenten Exportieren" target="_blank"><img src="content/images/5770ffea401723f011dbfbb4f55c7b93.png" width="150" height="65" border="0" class="image_img" alt="Newsletter_Abonnenten_export.png" /></a></div><p class="image_caption">Bild 1 -<br />Newsletter Abonnenten Exportieren</p></div></td>
<td valign="top" class="articleText"><p>&Uuml;ber diesen Punkt &quot;<strong>Auswahl exportieren</strong>&quot; haben Sie die m&ouml;glichkeit Ihre Newsletterempf&auml;nger in eine Excel Datei zu exportieren. Sie k&ouml;nnen hierbei auch den Filter benutzten. Das bedeutet das Sie z.b. nur den Haken bei <img src="./img/button/aktiv_12x13_1.gif" alt="Aktive Empf&auml;nger" /> (Verifitierte Empf&auml;nger) setzten und somit eine Excel Datei bekommen in der alle Verfizierten Empf&auml;nger erhalten. <br />
<br />
Nachdem Sie auf &quot;<strong>Auswahl exportieren</strong>&quot; geklickt haben &ouml;ffnet sich ein neues Fenster best&auml;tigen Sie in diesem mit &quot;<strong>OK</strong>&quot; das Sie die Excel Datei runterladen wollen. Mit &quot;<strong>Abbrechen</strong>&quot; brechen Sie diesen Vorgang ab.</p></td>
</tr>
</table><div align="right"><a href="#top"><img src="img/article/top_link_0.gif" border="0" alt="" /></a></div>
		 
		
		<br /><br />
		<div class="sub">
		Artikel erstellt am: Montag, 13. August 2007 <br /> Letzte &Auml;nderung: Montag, 22. Oktober 2007	
		</div>
				
	</div>
	
<div id="footer"><br /><br />
<p style="height:30px;">&nbsp;</p>


 <script type="text/javascript" language="javascript">
<!--

var showDefaultValue =  0

function hideLayer(whichLayer) {
	if (document.getElementById) {
		// this is the way the standards work
		document.getElementById(whichLayer).style.display = "none";
	} else if (document.all) {
		// this is the way old msie versions work
		document.all[whichlayer].style.display = "none";
	} else if (document.layers) {
		// this is the way nn4 works
		document.layers[whichLayer].display = "none";
	}
}

function showLayer(whichLayer) {
		//	alert(whichLayer);
	if (document.getElementById) {
		// this is the way the standards work
		document.getElementById(whichLayer).style.display = "block";
	}
	else if (document.all) {
		// this is the way old msie versions work
		document.all[whichlayer].style.display = "block";
	}
	else if (document.layers) {
		// this is the way nn4 works
		document.layers[whichLayer].display = "block";
	}
}

function toggleLayer(whichLayer) {
	if(showDefaultValue == 0) {
		hideLayer(whichLayer);
		showDefaultValue = 1;
	} else {
		showLayer(whichLayer);
		showDefaultValue = 0;
	}
}
//-->
</script>


<div id="alles">
<div id="klapper" onclick="toggleLayer('formular');">
<table width="570" border="0" cellspacing="0" cellpadding="0">
<tr>
<td><em style="color:#275EA8;" onmouseover="this.style.color='#4F96F4';" onmouseout="this.style.color='#275EA8';">Sie haben Anregungen oder Kritik zu diesem Artikel? Schreiben Sie uns!</em></td>   
<td align="right" style="padding-right:2px;"><img src="template/lang/all/icons/write.gif" width="16" height="21" alt="" border="0" /></td>
</tr>
</table>

</div>
<div id="formular">

<form name="form" method="post" action="index.php?id=416,392,0,1,1,0" style="margin:0;padding:0;"><input type="hidden" name="customForm" value="1" /><input type="hidden" name="docucheck" value="1" />


<div style="float:left;">
<p><select name="Betreff" id="Betreff" class="size1">
<option value="" class="deepblue"> Bitte ausw&auml;hlen </option>
<option value="subject_1" class="inselect">Anregungen</option>
<option value="subject_2" class="inselect">Fehlermeldung/ Kritik</option>
<option value="subject_3" class="inselect">Sonstiges</option>

</select><br /></p>


<p>Vorname:<br />
<input type="text" name="Vorname" value="" class="size1" /></p>
<p>Name:*<br />
<input type="text" name="Name" value="" class="size1" /></p>
<p>E-Mail:*<br />
<input type="text" name="E-Mail" value="" class="size1" /></p>
</div>


<div style="float:right;">Mitteilung:*<br />
<textarea name="Nachricht" cols="40" rows="4"  class="size7"></textarea>
</div>

<p style="clear:both; text-align:right;"><input type="reset" name="reset" value="Zur&uuml;cksetzen" class="btstyle" style="width:100px;" />&nbsp;&nbsp;
<input type="submit" name="submit" value="Anfrage senden" class="btstyle" style="width:110px;" /></p>
<p style="margin:20px;" class="sub">* Pflichtangaben. Ihre Daten werden ausschlie&szlig;lich für diese Anfrage verwendet.</p>

</form>
</div>
</div>
 <script type="text/javascript" language="javascript">
<!--
	// Lösung ohne Onload
	toggleLayer('formular');
//-->
</script>
<br />





	<table width="97%" border="0" cellspacing="0" cellpadding="0">
		<tr>
			<td valign="bottom">	
			&copy; phpwcms-docu 2004-2013
			<img src="img/leer.gif" border="0" width="10" height="0" alt="" /><a href="impressum.phtml" class="phpwcmsIntLink"><img src="template/lang/all/icons/imprint.gif" width="9" height="15" alt="Impressum" title="Impressum" border="0" /></a>&nbsp; 
			<a href="sitemap_de.phtml" class="phpwcmsIntLink"><img src="template/lang/all/icons/sitemap.gif" width="19" height="15" alt="Sitemap" title="Sitemap" border="0" /></a>&nbsp; 
			<a href="gaestebuch.phtml" class="phpwcmsIntLink"><img src="template/lang/all/icons/gbook.gif" width="20" height="16" alt="Ins G&auml;stebuch eintragen" title="Ins G&auml;stebuch eintragen" border="0" /></a>&nbsp; 
			<a href="#" onclick="BookMark_Page();return false;" title="" class="phpwcmsBookmarkLink"><img src="template/lang/all/icons/favo.gif" width="12" height="15" alt="Seite als Bookmark speichern" title="Seite als Bookmark speichern" border="0" /></a>&nbsp; 
			     
			</td>
			<td valign="bottom" style="padding-right:25px;">
			
			
			
			</td>		
			<td width="150">
			</td>
		</tr>
	</table>
</div><br/>

</div>
</body>
</html>