<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<!--
	phpwcms | free open source content management system
	created by Oliver Georgi (oliver at phpwcms dot de) and licensed under GNU/GPL.
	phpwcms is copyright 2003-2007 of Oliver Georgi. Extensions are copyright of
	their respective owners. Visit project page for details: http://www.phpwcms.org/
//-->
<title>phpwcms-docu for  phpwcms :: web based content management system | Nachrichtenzentrale | Nachricht lesen</title>
  <meta http-equiv="content-type" content="text/html; charset=iso-8859-1" />
  <meta http-equiv="content-style-type" content="text/css" />
  <script src="template/inc_js/frontend.js" type="text/javascript"></script>
  <style type="text/css">
  <!-- 
    @import url("template/inc_css/mpl_docu.css");
    @import url("template/inc_css/mpl_frontend.css");
    @import url("template/inc_css/mpl_menu.css");
    @import url("template/inc_css/mpl_objects.css");
  //-->
  </style>
<script type="text/javascript" language="javascript">
<!--
function MM_jumpMenu(targ,selObj,restore){ //v3.0
  eval(targ+".location='"+selObj.options[selObj.selectedIndex].value+"'");
  if (restore) selObj.selectedIndex=0;
}

function MM_findObj(n, d) { //v4.01
  var p,i,x;  if(!d) d=document; if((p=n.indexOf("?"))>0&&parent.frames.length) {
    d=parent.frames[n.substring(p+1)].document; n=n.substring(0,p);}
  if(!(x=d[n])&&d.all) x=d.all[n]; for (i=0;!x&&i<d.forms.length;i++) x=d.forms[i][n];
  for(i=0;!x&&d.layers&&i<d.layers.length;i++) x=MM_findObj(n,d.layers[i].document);
  if(!x && d.getElementById) x=d.getElementById(n); return x;
}

function MM_jumpMenuGo(selName,targ,restore){ //v3.0
  var selObj = MM_findObj(selName); if (selObj) MM_jumpMenu(targ,selObj,restore);
}
//-->
</script>
<meta name="Title" content="Die phpWCMS Dokumentation" />
<meta name="author" content="Oliver Frohnert, Mario Perez Leal" />
<meta name="Publisher" content="Oliver Frohnert, Mario Perez Leal, creacion" />
<meta name="Copyright" content="Oliver Frohnert, Mario Perez Leal, creacion" />
<meta name="keywords" content="frohnert, perez leal, creacion, documentation, dokumentation, phpwcms, cms, opensource, open source, docu" />
<meta name="description" content="Das Dokumentations Projekt für das Open Source CMS phpWCMS" />
<meta name="Audience" content="Alle" />
<meta name="Content-language" content="DE" />
<meta name="robots" content="index,follow" />
<meta name="expires" content="0" />
<meta name="revisit-after" content="7 days" />
<meta name="resource-type" content="document" />
<meta name="distribution" content="Global" />
<meta name="generator" content="PHPWCMS" />
<meta name="verify-v1" content="1ZpxZ7AZsjm7PxjqXQVus0eiUYqOsp5URTJn9q4KNz8=" />
  <!--[if lt IE 7]>
  <style type="text/css">
    body { behavior: url("template/inc_css/specific/csshover2.htc"); }
    img { behavior: url("template/inc_css/specific/pngbehavior.htc"); }
  </style>
  <![endif]-->
</head>
<body id="myid_417">
<div id="container"><a name="top" id="top"></a>


	<div id="head">
		
	<div id="mainnavi">
		<div class="fleft"><a href="deutsche_version.phtml">Startseite</a> | <a href="news_de.phtml">News</a> | <span style="text-decoration:none;font-weight:bold;"><a href="die_docu.phtml">Die Docu</a></span> | <a href="Nuetzliche_Links_und_Tools.phtml">Links &amp; Tools</a> | <a href="downloads.phtml">Downloads</a> | <a href="kontakt.phtml">Kontakt</a> | <a href="faq_de.phtml">FAQ</a> | <a href="http://forum.phpwcms.org/" target="_blank">Forum</a> | <a href="howto_de.phtml">HowTo</a></div>				
		<div class="sys">Sonntag, 3. März 2013<img src="img/leer.gif" border="0" width="5" height="1" alt="" />|<img src="img/leer.gif" border="0" width="5" height="1" alt="" />3 User online<img src="img/leer.gif" border="0" width="10" height="1" alt="" />
		<a href="deutsche_version.phtml" title="Deutsche Version"><img src="picture/../template/lang/all/flag_de.gif" border="0" alt="" /></a>
		<a href="english_version.phtml"  title="English version"><img src="picture/../template/lang/all/flag_en.gif" border="0" alt="" /></a>
		</div>
	</div>
	
	<a href="./" title="phpwcms-docu Startseite aufrufen" class="homelink">
	<span>&raquo; Zur phpwcms-docu Startseite</span></a>
	<h2>phpwcms-docu - Die Dokumentation f&uuml;r f&uuml;r das CMS phpWCMS</h2>
	<p>phpwcms-docu ist eine Art Kompass, der Ihnen die M&ouml;glichkeiten von phpWcms aufzeigt und Sie erfolgreich, ohne gro&szlig;e Umwege, zu Ihrer fertigen Web-Anwendung f&uuml;hren soll.
	</p>
	</div>

	
	<div id="left">
	<div class="leftnav" style="margin-top:24px;">
	
<div id="ul_div_309">
<ul>
	<li class="sub_no"><a href="download-dev-versionen.phtml">Download Dev Versionen</a></li>
	<li class="sub_no sub_ul_true"><a href="installation_und_upgrade_von_phpwcms.phtml">Installation &amp; Upgrade</a></li>
	<li class="sub_no sub_ul_true"><a href="verwaltung_artikel.phtml">Artikel</a></li>
	<li class="sub_no sub_ul_true"><a href="dateizentrale.phtml">Datei</a></li>
	<li class="sub_no sub_ul_true"><a href="verwaltung_module.phtml">Module</a></li>
	<li class="sub_ul"><a href="Kommunikation.phtml">Kommunikation</a>
	<div id="ul_div_381">
	<ul>
		<li class="sub_no"><a href="kommunikation_newsletter.phtml"><span style="text-decoration:line-through;font-size:10px;">Newsletter</span></a></li>
		<li class="sub_no"><a href="kommunikation_newsletter_abonnenten.phtml">Newsletter Abonnenten</a></li>
		<li class="sub_no"><a href="kommunikation_newsletter_abonnoment.phtml">Newsletter Abonnoment</a></li>
		<li class="sub_no active"><a href="kommunikation_nachrichtenzentrale.phtml">Nachrichtenzentrale</a></li>
		<li class="sub_no"><a href="kommunikation_neue_nachricht.phtml">Neue Nachricht</a></li>
	</ul>
	</div>
	</li>
	<li class="sub_no"><a href="verwaltung_nachricht.phtml">Nachricht</a></li>
	<li class="sub_no"><a href="verwaltung_chat.phtml">Chat</a></li>
	<li class="sub_no"><a href="verwaltung_profil.phtml">Profil</a></li>
	<li class="sub_no sub_ul_true"><a href="verwaltung_admin.phtml">Admin</a></li>
	<li class="sub_no sub_ul_true"><a href="add-on-und-vorlagen.phtml">Add Ons und Vorlagen</a></li>
	<li class="sub_no"><a href="deutsche_version.phtml?replacement_tags_de">Replacement Tags</a></li>
	<li class="sub_no"><a href="deutsche_version.phtml?content_parts_de">Content Parts</a></li>
</ul>
</div>

		
		
		

	</div> 
	</div> 
	  
	<div id="right">
		<div style="margin-top:24px;">			
		<form action="index.php?suche" method="post" name="searchFE" onsubmit="s=document.getElementById('customSearchInput');if(s.value=='Suchen')return false;">
			<table width="100%" border="0" cellpadding="0" cellspacing="0">
			<tr>
					<td><input type="text" name="search_input_field" size="20" maxlength="200" id="customSearchInput" class="customSearchInput" value="" onfocus="if(this.value=='Suchen')this.value='';" onblur="if(this.value=='')this.value='Suchen';" /></td>
					<td><input type="image" name="search_go" onfocus="this.blur();" title="Suchen" src="/template/lang/all/submit.gif" /></td>
				</tr>
			</table>
			</form>
			
			      <script type="text/javascript" language="javascript">
			  <!-- 
			        document.getElementById("customSearchInput").value="Suchen";
			  //-->
			      </script>
				  
			<!-- <p style="margin-top:10px;">Schriftgrad &auml;ndern: <a href="[FontSize-]"><img src="template/lang/all/icons/reduce.gif" width="18" height="17" alt="" title="Verkleinern" border="0" /></a>
			<a href="[FontSize+]"><img src="template/lang/all/icons/extend.gif" width="18" height="17" alt="" title="Vergr&ouml;&szlig;ern" border="0" /></a>
			</p> -->
			
	<p style="margin-top:10px;">Bitte w&auml;hlen Sie: 
	
	 </p>
<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div>


<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div>
<!-- <a href="http://validator.w3.org/check?uri=http%3A%2F%2Fwww.phpwcms-docu.de%2Findex.php%3Fdeutsche_version" title="W3C Standard XHTML" target="_blank"><img src="picture/w3c/w3c_xhtml.gif" border="0" alt="" /></a>
<a href="http://jigsaw.w3.org/css-validator/validator?uri=http://www.phpwcms-docu.de" title="W3C Standard CSS" target="_blank"><img src="picture/w3c/w3c_css.gif" border="0" alt="" /></a><br />			
<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div> -->
<h3>Partnersites</h3>






<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div>

<div style="margin-top:10px; margin-bottom:15px;"></div>


<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div>
</div>

	</div> 
	
	<div id="content">
	<div id="bread">Sie sind hier: <a href="deutsche_version.phtml">Deutsch</a> <span class="breadcrumb_spacer">&gt;</span> <a href="die_docu.phtml">Die Docu</a> <span class="breadcrumb_spacer">&gt;</span> <a href="Kommunikation.phtml">Kommunikation</a> <span class="breadcrumb_spacer">&gt;</span> Nachrichtenzentrale</div>
		
		<a name="jump223"></a><!-- Livedate: 27.11.2004 11:00:40 / Killdate: 31.12.2030 23:59:59 -->
<h1>Nachricht lesen</h1>
<h3>und beantworten</h3>

<table width="100%" cellpadding="0" cellspacing="0" border="0" class="imgTextRight">
<tr>
<td valign="top" width="10%" class="image_td2"><div class="imgDIVblockImgLeft"><div class="image_td2"><a href="zoom/MzY1YmYzZDdjOGJhNGM2ZTVhNGUxMTdmNzc3N2NjN2UucG5nP3dpZHRoPSI3NjciIGhlaWdodD0iNDk2Ig.html" onclick="checkClickZoom();clickZoom('zoom/MzY1YmYzZDdjOGJhNGM2ZTVhNGUxMTdmNzc3N2NjN2UucG5nP3dpZHRoPSI3NjciIGhlaWdodD0iNDk2Ig.html','previewpic','width.html');return false;.html"><img src="content/images/647187a66d4bd5a298f9de51779863fa.png" width="150" height="97" border="0" class="image_img" alt="nachricht_lesen_01.png" /></a></div></div></td>
<td valign="top" class="articleText"><p>Wenn Sie eine Interne Nachricht erhalten haben sehen Sie, dass sofort nach dem Einloggen in das System oben rechts im roten Balken sehen Sie dieses <img src="picture/../img/symbole/new_mail.gif" border="0" alt="" /> Symbol.</p>
<p>Jetzt haben Sie 2 M&ouml;glichkeiten die Nachricht aufzurufen. Entweder Sie klicken das Symbol an oder Sie klicken in der gleichen Zeile auf &quot;<strong>Nachricht</strong>&quot;</p></td>
</tr>
</table><div style="border-bottom:1px dotted #d2e2f5; margin-top:10px; margin-bottom:15px;"></div><div style="margin:30px 0 0 0;padding:0;" class="spaceBeforeCP"></div><h3>Nachrichten Überblick</h3><div class="imgDIVinTextRight" align="right"><div class="image_td2"><a href="zoom/NWU2NGEzMzlmNTg0YmJjZmFiNDJjYzhiOGY5MWZiMDgucG5nP3dpZHRoPSI3NjciIGhlaWdodD0iMzk3Ig.html" onclick="checkClickZoom();clickZoom('zoom/NWU2NGEzMzlmNTg0YmJjZmFiNDJjYzhiOGY5MWZiMDgucG5nP3dpZHRoPSI3NjciIGhlaWdodD0iMzk3Ig.html','previewpic','width.html');return false;.html"><img src="content/images/d0299324d6e3800170c9c5c51e6c852d.png" width="150" height="77" border="0" class="image_img" alt="nachricht_lesen_02.png" /></a></div></div><div class="articleText"><p>Nachdem Sie nun auf eine der beiden M&ouml;glichkeiten geklickt haben, gelangen Sie zur Nachrichten &Uuml;bersicht. Dort k&ouml;nnen sehen Sie nun wer Ihnen eine Nachricht und mit welchem Betreff gesendet hat.&nbsp;Am Ende der Zeile sehen Sie 2 Icons.<br />
<br />
Das erste Icon <img src="picture/../img/button/reply_mini.gif" border="0" alt="" /> leitet Sie zur Antwortseite weiter. <br />
Das zweite Icon <img src="picture/../img/icons/trash.gif" border="0" alt="" /> l&ouml;scht die Nachricht. Gel&ouml;schte Nachrichten werden aber nicht sofort unwiderbringlich gel&ouml;scht, sondern werden in den Ordner &quot;Gel&ouml;scht&quot; verschoben.<br />
<br />
Wenn Sie jetzt entweder auf den Absender der Nachricht oder den Betreff klicken k&ouml;nnen Sie die Nachricht lesen.</p></div><div style="border-bottom:1px dotted #d2e2f5; margin-top:10px; margin-bottom:15px;"></div><div style="margin:20px 0 0 0;padding:0;" class="spaceBeforeCP"></div><h3>Nachricht lesen</h3><table width="100%" cellpadding="0" cellspacing="0" border="0" class="imgTextRight">
<tr>
<td valign="top" width="10%" class="image_td2"><div class="imgDIVblockImgLeft"><div class="image_td2"><a href="zoom/NWY3OTQzZjU3NGNmMGRkNDA5N2RjMmJhYjAyNGI5OWQucG5nP3dpZHRoPSI3NjciIGhlaWdodD0iMzk4Ig.html" onclick="checkClickZoom();clickZoom('zoom/NWY3OTQzZjU3NGNmMGRkNDA5N2RjMmJhYjAyNGI5OWQucG5nP3dpZHRoPSI3NjciIGhlaWdodD0iMzk4Ig.html','previewpic','width.html');return false;.html"><img src="content/images/fb26e44fdc5688f5f2c765c93882bd78.png" width="150" height="77" border="0" class="image_img" alt="nachricht_lesen_04.png" /></a></div></div></td>
<td valign="top" class="articleText"><p>Hier k&ouml;nnen Sie nun die Ihre Nachricht lesen. Unter der Nachricht sehen Sie 4 Schaltfl&auml;chen.<br />
<br />
Dies sind die Bedeutungen der einzelnen Schaltfl&auml;chen:<br />
&nbsp;</p></td>
</tr>
</table><div style="margin:20px 0 0 0;padding:0;" class="spaceBeforeCP"></div><table width="100%" cellspacing="0" cellpadding="6" border="0">
    <tbody>
        <tr class="tbfield">
            <td width="50"><img src="picture/../img/button/close_message.gif" border="0" alt="" /></td>
            <td>Schlie&szlig;en Sie&nbsp;die Nachricht</td>
        </tr>
        <tr>
            <td><img src="picture/../img/button/new_message1.gif" border="0" alt="" /></td>
            <td>Erstellen einer neuen Nachricht ohne auf die Nachricht die Sie gerade lesen Bezug zu nehmen.</td>
        </tr>
        <tr class="tbfield">
            <td><img src="picture/../img/button/reply_to_message1.gif" border="0" alt="" /></td>
            <td>Gelangen Sie zur Antwortseite</td>
        </tr>
        <tr>
            <td><img src="picture/../img/button/message_to_trash.gif" border="0" alt="" /></td>
            <td>L&ouml;scht die Nachricht.</td>
        </tr>
    </tbody>
</table><div style="border-bottom:1px dotted #d2e2f5; margin-top:10px; margin-bottom:15px;"></div><div style="margin:20px 0 0 0;padding:0;" class="spaceBeforeCP"></div><h3>Nachricht beantworten</h3><table width="100%" cellpadding="0" cellspacing="0" border="0" class="imgTextRight">
<tr>
<td valign="top" width="10%" class="image_td2"><div class="imgDIVblockImgLeft"><div class="image_td2"><a href="zoom/ZGVmMTc4YjE1ZjczYThiOTNkNDZiYjM0M2U3NjgzMzUucG5nP3dpZHRoPSI3NjciIGhlaWdodD0iNTQyIg.html" onclick="checkClickZoom();clickZoom('zoom/ZGVmMTc4YjE1ZjczYThiOTNkNDZiYjM0M2U3NjgzMzUucG5nP3dpZHRoPSI3NjciIGhlaWdodD0iNTQyIg.html','previewpic','width.html');return false;.html"><img src="content/images/b0c6db89e25f0f7e80c482045dbd75a6.png" width="150" height="105" border="0" class="image_img" alt="nachricht_lesen_03.png" /></a></div></div></td>
<td valign="top" class="articleText"><p>Hier k&ouml;nnen Sie nun die Nachricht beantworten. Es funktioniert genauso wie wenn Sie eine <a href="nachricht_schreiben.phtml" class="phpwcmsIntLink">Nachricht verfassen</a>, mit&nbsp;der einzigen&nbsp;&Auml;nderung, dass Sie hier keinen Empf&auml;nger ausw&auml;hlen m&uuml;ssen.<br />
<br />
&nbsp;</p></td>
</tr>
</table><div align="right"><a href="#top"><img src="img/article/top_link_0.gif" border="0" alt="" /></a></div>
		 
		
		<br /><br />
		<div class="sub">
		Artikel erstellt am: Samstag, 27. November 2004 <br /> Letzte &Auml;nderung: Dienstag, 04. Januar 2011	
		</div>
				
	</div>
	
<div id="footer"><br /><br />
<p style="height:30px;">&nbsp;</p>


 <script type="text/javascript" language="javascript">
<!--

var showDefaultValue =  0

function hideLayer(whichLayer) {
	if (document.getElementById) {
		// this is the way the standards work
		document.getElementById(whichLayer).style.display = "none";
	} else if (document.all) {
		// this is the way old msie versions work
		document.all[whichlayer].style.display = "none";
	} else if (document.layers) {
		// this is the way nn4 works
		document.layers[whichLayer].display = "none";
	}
}

function showLayer(whichLayer) {
		//	alert(whichLayer);
	if (document.getElementById) {
		// this is the way the standards work
		document.getElementById(whichLayer).style.display = "block";
	}
	else if (document.all) {
		// this is the way old msie versions work
		document.all[whichlayer].style.display = "block";
	}
	else if (document.layers) {
		// this is the way nn4 works
		document.layers[whichLayer].display = "block";
	}
}

function toggleLayer(whichLayer) {
	if(showDefaultValue == 0) {
		hideLayer(whichLayer);
		showDefaultValue = 1;
	} else {
		showLayer(whichLayer);
		showDefaultValue = 0;
	}
}
//-->
</script>


<div id="alles">
<div id="klapper" onclick="toggleLayer('formular');">
<table width="570" border="0" cellspacing="0" cellpadding="0">
<tr>
<td><em style="color:#275EA8;" onmouseover="this.style.color='#4F96F4';" onmouseout="this.style.color='#275EA8';">Sie haben Anregungen oder Kritik zu diesem Artikel? Schreiben Sie uns!</em></td>   
<td align="right" style="padding-right:2px;"><img src="template/lang/all/icons/write.gif" width="16" height="21" alt="" border="0" /></td>
</tr>
</table>

</div>
<div id="formular">

<form name="form" method="post" action="index.php?id=417,223,0,1,1,0" style="margin:0;padding:0;"><input type="hidden" name="customForm" value="1" /><input type="hidden" name="docucheck" value="1" />


<div style="float:left;">
<p><select name="Betreff" id="Betreff" class="size1">
<option value="" class="deepblue"> Bitte ausw&auml;hlen </option>
<option value="subject_1" class="inselect">Anregungen</option>
<option value="subject_2" class="inselect">Fehlermeldung/ Kritik</option>
<option value="subject_3" class="inselect">Sonstiges</option>

</select><br /></p>


<p>Vorname:<br />
<input type="text" name="Vorname" value="" class="size1" /></p>
<p>Name:*<br />
<input type="text" name="Name" value="" class="size1" /></p>
<p>E-Mail:*<br />
<input type="text" name="E-Mail" value="" class="size1" /></p>
</div>


<div style="float:right;">Mitteilung:*<br />
<textarea name="Nachricht" cols="40" rows="4"  class="size7"></textarea>
</div>

<p style="clear:both; text-align:right;"><input type="reset" name="reset" value="Zur&uuml;cksetzen" class="btstyle" style="width:100px;" />&nbsp;&nbsp;
<input type="submit" name="submit" value="Anfrage senden" class="btstyle" style="width:110px;" /></p>
<p style="margin:20px;" class="sub">* Pflichtangaben. Ihre Daten werden ausschlie&szlig;lich für diese Anfrage verwendet.</p>

</form>
</div>
</div>
 <script type="text/javascript" language="javascript">
<!--
	// Lösung ohne Onload
	toggleLayer('formular');
//-->
</script>
<br />





	<table width="97%" border="0" cellspacing="0" cellpadding="0">
		<tr>
			<td valign="bottom">	
			&copy; phpwcms-docu 2004-2013
			<img src="img/leer.gif" border="0" width="10" height="0" alt="" /><a href="impressum.phtml" class="phpwcmsIntLink"><img src="template/lang/all/icons/imprint.gif" width="9" height="15" alt="Impressum" title="Impressum" border="0" /></a>&nbsp; 
			<a href="sitemap_de.phtml" class="phpwcmsIntLink"><img src="template/lang/all/icons/sitemap.gif" width="19" height="15" alt="Sitemap" title="Sitemap" border="0" /></a>&nbsp; 
			<a href="gaestebuch.phtml" class="phpwcmsIntLink"><img src="template/lang/all/icons/gbook.gif" width="20" height="16" alt="Ins G&auml;stebuch eintragen" title="Ins G&auml;stebuch eintragen" border="0" /></a>&nbsp; 
			<a href="#" onclick="BookMark_Page();return false;" title="" class="phpwcmsBookmarkLink"><img src="template/lang/all/icons/favo.gif" width="12" height="15" alt="Seite als Bookmark speichern" title="Seite als Bookmark speichern" border="0" /></a>&nbsp; 
			     
			</td>
			<td valign="bottom" style="padding-right:25px;">
			
			
			
			</td>		
			<td width="150">
			</td>
		</tr>
	</table>
</div><br/>

</div>
</body>
</html>