<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<!--
	phpwcms | free open source content management system
	created by Oliver Georgi (oliver at phpwcms dot de) and licensed under GNU/GPL.
	phpwcms is copyright 2003-2007 of Oliver Georgi. Extensions are copyright of
	their respective owners. Visit project page for details: http://www.phpwcms.org/
//-->
<title>phpwcms-docu for  phpwcms :: web based content management system | Profile{D:7/30/2007,30,newR.gif} | Administration of your own profile</title>
  <meta http-equiv="content-type" content="text/html; charset=iso-8859-1" />
  <meta http-equiv="content-style-type" content="text/css" />
  <script src="template/inc_js/frontend.js" type="text/javascript"></script>
  <style type="text/css">
  <!-- 
    @import url("template/inc_css/mpl_frontend.css");
    @import url("template/inc_css/mpl_menu.css");
    @import url("template/inc_css/mpl_objects.css");
    @import url("template/inc_css/mpl_docu_en.css");
  //-->
  </style>
<meta name="Title" content="The phpWCMS Documentation" />
<meta name="author" content="Oliver Frohnert, Mario Perez Leal" />
<meta name="Publisher" content="Oliver Frohnert, Mario Perez Leal, creacion" />
<meta name="Copyright" content="Oliver Frohnert, Mario Perez Leal, creacion" />
<meta name="keywords" content="frohnert, perez leal, creacion, documentation, dokumentation, phpwcms, cms, opensource, open source, docu" />
<meta name="description" content="A Documentation Project for the  Open Source CMS phpWCMS" />
<meta name="Audience" content="Alle" />
<meta name="Content-language" content="EN" />
<meta name="robots"      content="index,follow" />
<meta name="expires" content="0" />
<meta name="revisit-after" content="7 days" />
<meta name="resource-type" content="document" />
<meta name="distribution" content="Global" />
<meta name="generator" content="PHPWCMS" />

  <link rel="stylesheet" href="template/slimbox/css/slimbox.css" type="text/css" media="screen" />
  <script src="template/inc_js/mootools/mootools.js" type="text/javascript"></script>
  <script src="template/slimbox/js/slimbox.js" type="text/javascript"></script>
  <!--[if lt IE 7]>
  <style type="text/css">
    body { behavior: url("template/inc_css/specific/csshover2.htc"); }
    img { behavior: url("template/inc_css/specific/pngbehavior.htc"); }
  </style>
  <![endif]-->
</head>
<body id="myid_221">
<div id="container"><a name="top" id="top"></a>


	<div id="head">
		
	<div id="mainnavi">
		<div class="fleft"><a href="english_version.phtml">Home</a> | <a href="news_en.phtml">News</a> | <span style="text-decoration:none;font-weight:bold;"><a href="the_docu.phtml">The Docu</a></span> | <a href="Usefull_Links_and_Tools.phtml">Links &amp; Tools</a> | <a href="contact.phtml">Contact</a> | <a href="faq_en.phtml">FAQ</a> | <a href="http://forum.phpwcms.org/" target="_blank">Forum</a> | <a href="howto_en.phtml">HowTo</a></div>				
		<div class="sys">Monday, 1. June 2015<img src="img/leer.gif" border="0" width="5" height="1" alt="" />|<img src="img/leer.gif" border="0" width="5" height="1" alt="" />5 User online<img src="img/leer.gif" border="0" width="10" height="1" alt="" />
		<a href="deutsche_version.phtml" title="Deutsche Version"><img src="picture/../template/lang/all/flag_de.gif" border="0" alt="" /></a>
		<a href="english_version.phtml"  title="English version"><img src="picture/../template/lang/all/flag_en.gif" border="0" alt="" /></a>
		</div>
	</div>
	
	<a href="./" title="phpwcms-docu Startseite aufrufen" class="homelink">
	<span>&raquo; phpwcms-docu startpage</span></a>
	<h2>phpwcms-docu - Documentation for the Web Content Management System phpwcms</h2>
	<p>This website is targeted both to the beginner and the lateral entry following the goal to simplify the 
work with phpwcms and to focus on the essentials things.</p>
	</div>

	
	<div id="left">
	<div class="leftnav" style="margin-top:24px;">
	
<div id="ul_div_311">
<ul>
	<li class="sub_no"><a href="download-dev-versions.phtml">Download Dev Versions</a></li>
	<li class="sub_no sub_ul_true"><a href="installation_en.phtml">Installation &amp; Upgrade</a></li>
	<li class="sub_no sub_ul_true"><a href="article.phtml">Articles</a></li>
	<li class="sub_no sub_ul_true"><a href="file.phtml">File</a></li>
	<li class="sub_no sub_ul_true"><a href="module_en.phtml">Modules</a></li>
	<li class="sub_no sub_ul_true"><a href="communication.phtml">Communication </a></li>
	<li class="sub_no"><a href="chat_en.phtml">Chat</a></li>
	<li class="sub_no active"><a href="profile.phtml">Profile</a></li>
	<li class="sub_no sub_ul_true"><a href="admin_en_.phtml">Admin</a></li>
	<li class="sub_no sub_ul_true"><a href="add-ons-and-templates.phtml">Add On&#039;s and Templates</a></li>
	<li class="sub_no"><a href="deutsche_version.phtml?replacement_tags_en">Replacement Tags</a></li>
	<li class="sub_no"><a href="deutsche_version.phtml?content_parts_en">Content Parts</a></li>
</ul>
</div>

		
	</div> 
	</div> 
	  
	<div id="right">
		<div style="margin-top:24px;">			
		<form action="#" method="post" name="searchFE" onsubmit="s=document.getElementById('customSearchInput');if(s.value=='Search')return false;">
			<table width="100%" border="0" cellpadding="0" cellspacing="0">
			<tr>
					<td><input type="text" name="search_input_field" size="20" maxlength="200" id="customSearchInput" class="customSearchInput" value="" onfocus="if(this.value=='Search')this.value='';" onblur="if(this.value=='')this.value='Search';"/></td>
					<td><input type="image" name="search_go" onfocus="this.blur();" title="Search" src="/template/lang/all/submit.gif" /></td>
				</tr>
			</table>
			</form>
			
			      <script type="text/javascript" language="javascript">
			  <!-- 
			        document.getElementById("customSearchInput").value="Search";
			  //-->
			      </script>
				  
<!-- <p style="margin-top:10px;">Change font size: <a href="[FontSize-]"><img src="template/lang/all/icons/reduce.gif" width="18" height="17" alt="" title="Small" border="0" /></a>
			<a href="[FontSize+]"><img src="template/lang/all/icons/extend.gif" width="18" height="17" alt="" title="Bigger" border="0" /></a>
			</p> -->
			
	<p style="margin-top:10px;">Please choose: 
	
	 </p>


<!-- <a href="http://validator.w3.org/check?uri=http%3A%2F%2Fwww.phpwcms-docu.de%2Findex.php%3Fdeutsche_version" title="W3C Standard XHTML" target="_blank"><img src="picture/w3c/w3c_xhtml.gif" border="0" alt="" /></a>
<a href="http://jigsaw.w3.org/css-validator/validator?uri=http://www.phpwcms-docu.de" title="W3C Standard CSS" target="_blank"><img src="picture/w3c/w3c_css.gif" border="0" alt="" /></a><br />			
<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div> -->
		
<div style="margin-top:10px; margin-bottom:15px;"></div>
	
</div>

	</div> 
	
	<div id="content">
	<div id="bread">You are here: <a href="english_version.phtml">English</a> <span class="breadcrumb_spacer">&gt;</span> <a href="the_docu.phtml">The Docu</a> <span class="breadcrumb_spacer">&gt;</span> Profile</div>
		
		<a name="jump345"></a><!-- Livedate: 09.09.2004 23:41:52 / Killdate: 31.12.2030 23:59:59 -->
<h1>Administration of your own profile</h1>

<div style="margin:25px 0 0 0;padding:0;" class="spaceBeforeCP"></div><table width="100%" cellpadding="0" cellspacing="0" border="0" class="imgTextRight">
<tr>
<td valign="top" width="10%" class="image_td2"><table width="150" border="0" cellspacing="0" cellpadding="0" >
<tr><td class="image_td2"><a href="content/images/732ce63d7edf3c3657f74b2c9187ce97.png" rel="lightbox" title="Profil bearbeiten" target="_blank"><img src="content/images/62f461537ec0a8186af6940839f2db39.png" width="150" height="74" border="0" class="image_img" alt="profil_1.png" /></a></td></tr>
<tr><td align="center" class="image_caption">Profil bearbeiten</td></tr>
</table></td>
<td valign="top" class="articleText"><p>In the profile settings the personal settings of every backend user can be adjusted.<br />
<br />
For security reasons the password should be changed regularly, in minimum all 2 months. Please don't use words that can be found in dictionaries of any language or dialects. Instead use combinations with numbers and letters.</p>
<p align="justify">he field email should contain a valid email address, because the system send all changes to this address. This address is only visible for backend users and not for spambots.<br />
<br />
The most important setting in Profiles is the language. Please choose here your most used language and save your settings. From now the backend will be shown in your selected language at every login, it doesn't matter which language the dropdown field at the <a href="aid=311.phtml" class="phpwcmsIntLink">Login Page</a> contains.</p></td>
</tr>
</table><div style="border-bottom:1px dotted #d2e2f5; margin-top:10px; margin-bottom:15px;"></div><h3>WYSIWYG Editors</h3><p>Using the item &quot;WYSIWYG Editor&quot; you can decide whether you want to work with a WYSIWYG editor and if yes with which one..<br />
<br />
You can choose <br />
<br />
- <strong>WYSIWYG editor disabled</strong> (None of the shown editors will be used). <br />
In this case the CP &quot;HTML&quot; will automatically be used.</p>
<p>-<strong> SPAW2</strong></p>
<p>- <strong>FCKeditor</strong> (Standard after the installation)<strong><br />
<br />
</strong>Below you can find a selction menu containing &quot;phpwcms_default&quot; as a standard. With this Selection you can define the functionality of the editor. <br />
In the following you will find some screenshots with some settings.</p><div style="border-bottom:1px dotted #d2e2f5; margin-top:10px; margin-bottom:15px;"></div><h3>FCKeditor</h3>
<table border="0" cellspacing="0" width="10%" cellpadding="0" align="center" class=" imgListTableCenter" summary="">
<tr>
	<td class="imagelisttd2"><img src="content/images/c17c563ade9d4661e2ca35edd4b125ce.png" width="530" height="94" border="0" class="imagelistimg" alt="fck_phpwcms_default.png" /></td>
</tr>
<tr>
	<td class="imglistcaption">Selection: FCKeditor: phpwcms_default</td>
</tr>

<tr>
	<td class="imagelistSpacerRow"><img src="img/leer.gif" width="1" height="1" border="0" alt="" /></td>
</tr>
<tr>
	<td class="imagelisttd2"><img src="content/images/c70adf6a981f4aa7e3eb5d4c7b8c5c30.png" width="532" height="24" border="0" class="imagelistimg" alt="fck_phpwcms_basic.png" /></td>
</tr>
<tr>
	<td class="imglistcaption">Selection: FCKeditor: phpwcms_basic</td>
</tr>

<tr>
	<td class="imagelistSpacerRow"><img src="img/leer.gif" width="1" height="1" border="0" alt="" /></td>
</tr>
<tr>
	<td class="imagelisttd2"><img src="content/images/744fdacc5b7e5f3b01b800dfd346d197.png" width="530" height="118" border="0" class="imagelistimg" alt="fck_default.png" /></td>
</tr>
<tr>
	<td class="imglistcaption">Selection: FCKeditor: Default</td>
</tr>

<tr>
	<td class="imagelistSpacerRow"><img src="img/leer.gif" width="1" height="1" border="0" alt="" /></td>
</tr>
<tr>
	<td class="imagelisttd2"><img src="content/images/0c7dd0706bf7383c7559c40c3328c30b.png" width="530" height="23" border="0" class="imagelistimg" alt="fck_basic.png" /></td>
</tr>
<tr>
	<td class="imglistcaption">Selection: FCKeditor: Basic</td>
</tr>
</table>
<div style="border-bottom:1px dotted #d2e2f5; margin-top:10px; margin-bottom:15px;"></div><h3>SPAW2</h3>
<table border="0" cellspacing="0" width="10%" cellpadding="0" align="center" class=" imgListTableCenter" summary="">
<tr>
	<td class="imagelisttd2"><img src="content/images/18790c5f8e99b91ef80ea37a1356a902.png" width="538" height="90" border="0" class="imagelistimg" alt="spaw2_tbs_standard.png" /></td>
</tr>
<tr>
	<td class="imglistcaption">Selection: SPAW2: toolbarset_standard</td>
</tr>

<tr>
	<td class="imagelistSpacerRow"><img src="img/leer.gif" width="1" height="1" border="0" alt="" /></td>
</tr>
<tr>
	<td class="imagelisttd2"><img src="content/images/24d505a69b56f52d2fe18e195a09df5b.png" width="538" height="89" border="0" class="imagelistimg" alt="spaw2_tbs_all.png" /></td>
</tr>
<tr>
	<td class="imglistcaption">Selection: SPAW2: toolbarset_all</td>
</tr>

<tr>
	<td class="imagelistSpacerRow"><img src="img/leer.gif" width="1" height="1" border="0" alt="" /></td>
</tr>
<tr>
	<td class="imagelisttd2"><img src="content/images/4d6c249944f00301db7e02fb0846a8ca.png" width="538" height="90" border="0" class="imagelistimg" alt="spaw2_tbs_mini.png" /></td>
</tr>
<tr>
	<td class="imglistcaption">Selection: SPAW2: toolbarset_mini</td>
</tr>
</table>

		 
		
		<br /><br />
		<div class="sub">
		Article created: Tuesday, 24. July 2007 <br /> Last Changes: Tuesday, 4. January 2011	
		</div>
				
	</div>
	
<div id="footer">





	<table width="97%" border="0" cellspacing="0" cellpadding="0">
		<tr>
			<td valign="bottom">	
			&copy; phpwcms-docu 2004-2015
			<img src="img/leer.gif" border="0" width="10" height="0" alt="" /><a href="imprint.phtml" class="phpwcmsIntLink"><img src="template/lang/all/icons/imprint.gif" width="9" height="15" alt="Impressum" title="Impressum" border="0" /></a>&nbsp; 
			<a href="sitemap_en.phtml" class="phpwcmsIntLink"><img src="template/lang/all/icons/sitemap.gif" width="19" height="15" alt="Sitemap" title="Sitemap" border="0" /></a>&nbsp; 
			 
			
			     
			</td>
			<td valign="bottom" style="padding-right:25px;">
			
			
			
			</td>		
			<td width="150">
			</td>
		</tr>
	</table>
</div><br/>

</div>
</body>
</html>