<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<!--
     phpwcms | free open source content management system
     created by Oliver Georgi (oliver at phpwcms dot de) and licensed under GNU/GPL.
     phpwcms is copyright 2003-2005 of Oliver Georgi. Extensions are copyright of
     their respective owners. Visit project page http://www.phpwcms.org for details.
//-->
<html>
<head>
<title>phpwcms documentation | Content Part &quot;Sitemap&quot;</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<script src="template/inc_js/frontend.js" type="text/javascript"></script>
<link rel="stylesheet" type="text/css" href="template/inc_css/frontend.css">
<META NAME="Title" CONTENT="The phpWCMS Documentation">
<meta name="author" content="Oliver Frohnert">
<meta name="Publisher" content="Oliver Frohnert">
<meta name="Copyright" content="Oliver Frohnert">
<meta name="keywords" content="frohnert,documentation, dokumentation, phpwcms, cms. opensource, open source">
<meta name="description" content="A Documentation Project for the  Open Source CMS phpWCMS">
<meta name="Audience" content="Alle">
<meta name="Content-language" content="EN">
<META NAME="robots"      CONTENT="index,follow">
<META NAME="expires" CONTENT="0">
<meta name="revisit-after" content="7 days">
<meta name="resource-type" content="document">
<meta name="distribution" content="Global">
<meta name="generator" content="PHPWCMS">
<script language="JavaScript" type="text/javascript" src="pphlogger.js"></script>
<noscript><img alt="" src="./pphlogger/pphlogger.php?id=phpwcms&st=img"></noscript>
<!-- Start of StatCounter Code -->
<script type="text/javascript" language="javascript">
var sc_project=644539;
var sc_partition=5;
var sc_security="2e37fa21";
</script>

</head>

<body bgcolor="#FFFFFF" text="#000000" link="#FF9900" vlink="#FF9900" alink="#FF9900" style="margin:0px 0px 0px 0px;">
<table border="0" cellspacing="0" cellpadding="0" width="760" bgcolor="#ffffff" class="maintable" align="center">
<tr>
<td colspan="2" style="height:60px;"  bgcolor="#ffffff"><table width="760" height="135" border="0" cellpadding="0" cellspacing="0">
  <tr valign="top">
    <td width="1334" height="122" colspan="6"><IMG src="/template/lang/en/header_chris.jpg" alt="" border="0"></td>
  </tr>
  <tr>
	<td height="27" background="template/lang/all/top_menu.jpg"><table width="570" border="0" align="left" cellpadding="0" cellspacing="0">
      <tr>
        <td align="center" width="254"><a href="deutsche_version.phtml"><img src="picture/flags/de.gif" width="16" height="10" hspace="10" border="0"  alt="Deutsche Version" title="Deutsche Version"></a>
<a href="english_version.phtml"><img src="picture/flags/gb.gif" width="16" height="10" hspace="10" border="0"  alt="English Version" title="English Version"></a></td>
        <td valign="middle"><div align="center"><a href="replacement_tags_en.phtml"><img src="content/gt/8c10fcb16c44a7b9c26a5a932c5e4ae9.png" alt="Replacement Tags" title="Replacement Tags" border="0" /></a></div></td>
        <td width="30" valign="middle"><div align="center"><img src="template/lang/all/sep.gif" width="5" height="5" border="0"></div></td>
        <td valign="middle"><div align="center"><a href="content_parts_en.phtml"><img src="content/gt/02725c45a346fbf433a4c83e02d8dc5a.png" alt="Content Parts" title="Content Parts" border="0" /></a></div></td>
        <td width="30" valign="middle"><div align="center"><img src="template/lang/all/sep.gif" width="5" height="5" border="0"></div></td>
        <td valign="middle"><div align="center"><a href="links_de.phtml"><img src="content/gt/2c41bfb28d6dd3d4bbc8bb7688fd62ee.png" alt="Links" title="Links" border="0" /></a></div></td>
        <td width="30" valign="middle"><div align="center"><img src="template/lang/all/sep.gif" width="5 " height="5" border="0"></div></td>
        <td valign="middle"><div align="center"><a href="imprint.phtml"><img src="content/gt/8b40044a8de89d790c10c1671094a297.png" alt="Imprint" title="Imprint" border="0" /></a></div></td>
     </tr>
    </table>    </td>
  </tr>
</table>
</td>
</tr>
<tr>
<td valign="top" width="185" background="img/menu.gif"><table width="180" border="0" cellpadding="0" cellspacing="0">
  <tr>
    <td width="180" height="20">&nbsp;</td>
  </tr>
  <tr>
    <td style="padding-left: 7px;"><table border="0" cellspacing="0" cellpadding="0" width="100%">
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='deutsche_version.phtml?cvs_info_en';return false;" onMouseOver="MM_swapImage('linkid0Z00Sc','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td width="7" colspan="2"><img src="img/leer.gif" width="7" height="15" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkid0Z00Sc" id="linkid0Z00Sc"></td>
<td valign="top" style="height:15px;"  width="100%" class="nav_table" colspan="4"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="deutsche_version.phtml?cvs_info_en">News<img src="picture/myRT1/newR.gif" alt="12/14/2005" border="0"></a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="7"><img src="img/leer.gif" width="10" height="15" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='installation_en.phtml';return false;" onMouseOver="MM_swapImage('linkid2FiQYC','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td width="7" colspan="2"><img src="img/leer.gif" width="7" height="15" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkid2FiQYC" id="linkid2FiQYC"></td>
<td valign="top" style="height:15px;"  width="100%" class="nav_table" colspan="4"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="installation_en.phtml">Installation &amp; Upgrade<img src="picture/myRT1/editR.gif" alt="11/25/2005" border="0"></a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="7"><img src="img/leer.gif" width="10" height="15" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='the_docu.phtml';return false;">
<td width="7" colspan="2"><img src="img/leer.gif" width="7" height="15" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_2" alt="" border="" name="linkidUsqKV1" id="linkidUsqKV1"></td>
<td valign="top" style="height:15px;"  width="100%" class="nav_table_active" colspan="4"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="the_docu.phtml">The Docu<img src="picture/myRT1/editR.gif" alt="25/11/2005" border="0"><img src="picture/myRT1/newR.gif" alt="12/15/2005" border="0"></a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="7"><img src="img/leer.gif" width="10" height="15" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='article.phtml';return false;">
<td width="7" colspan="3"><img src="img/leer.gif" width="7" height="15" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_2" alt="" border="" name="linkidZlX14w" id="linkidZlX14w"></td>
<td valign="top" style="height:15px;"  width="100%" class="nav_table_active" colspan="3"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="article.phtml">Articles<img src="picture/myRT1/newR.gif" alt="12/15/2005" border="0"></a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="7"><img src="img/leer.gif" width="10" height="15" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='creating_articles.phtml';return false;" onMouseOver="MM_swapImage('linkid2vNVLH','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td width="7" colspan="4"><img src="img/leer.gif" width="7" height="15" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkid2vNVLH" id="linkid2vNVLH"></td>
<td valign="top" style="height:15px;"  width="100%" class="nav_table" colspan="2"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="creating_articles.phtml">Creating Articles</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="7"><img src="img/leer.gif" width="10" height="15" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='editing_articles.phtml';return false;" onMouseOver="MM_swapImage('linkidyTnwQX','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td width="7" colspan="4"><img src="img/leer.gif" width="7" height="15" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkidyTnwQX" id="linkidyTnwQX"></td>
<td valign="top" style="height:15px;"  width="100%" class="nav_table" colspan="2"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="editing_articles.phtml">Editing Articles </a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="7"><img src="img/leer.gif" width="10" height="15" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='article_organization.phtml';return false;" onMouseOver="MM_swapImage('linkid2ZFhvh','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td width="7" colspan="4"><img src="img/leer.gif" width="7" height="15" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkid2ZFhvh" id="linkid2ZFhvh"></td>
<td valign="top" style="height:15px;"  width="100%" class="nav_table" colspan="2"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="article_organization.phtml">Article Organization<img src="picture/myRT1/newR.gif" alt="12/15/2005" border="0"></a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="7"><img src="img/leer.gif" width="10" height="15" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='content_parts_en.phtml';return false;">
<td width="7" colspan="4"><img src="img/leer.gif" width="7" height="15" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_2" alt="" border="" name="linkidRhCN3T" id="linkidRhCN3T"></td>
<td valign="top" style="height:15px;"  width="100%" class="nav_table_active" colspan="2"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="content_parts_en.phtml">Content Parts</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="7"><img src="img/leer.gif" width="10" height="15" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='plain_text.phtml';return false;" onMouseOver="MM_swapImage('linkidaaWGiL','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td width="7" colspan="5"><img src="img/leer.gif" width="7" height="15" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkidaaWGiL" id="linkidaaWGiL"></td>
<td valign="top" style="height:15px;"  width="100%" class="nav_table"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="plain_text.phtml">Plain Text</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="7"><img src="img/leer.gif" width="10" height="15" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='html.phtml';return false;" onMouseOver="MM_swapImage('linkidAOzqDT','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td width="7" colspan="5"><img src="img/leer.gif" width="7" height="15" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkidAOzqDT" id="linkidAOzqDT"></td>
<td valign="top" style="height:15px;"  width="100%" class="nav_table"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="html.phtml">Html</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="7"><img src="img/leer.gif" width="10" height="15" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='wysiwyg_html.phtml';return false;" onMouseOver="MM_swapImage('linkidooH8oj','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td width="7" colspan="5"><img src="img/leer.gif" width="7" height="15" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkidooH8oj" id="linkidooH8oj"></td>
<td valign="top" style="height:15px;"  width="100%" class="nav_table"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="wysiwyg_html.phtml">WYSIWYG HTML</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="7"><img src="img/leer.gif" width="10" height="15" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='code.phtml';return false;" onMouseOver="MM_swapImage('linkidw13aJx','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td width="7" colspan="5"><img src="img/leer.gif" width="7" height="15" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkidw13aJx" id="linkidw13aJx"></td>
<td valign="top" style="height:15px;"  width="100%" class="nav_table"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="code.phtml">Code</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="7"><img src="img/leer.gif" width="10" height="15" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='text_with_image.phtml';return false;" onMouseOver="MM_swapImage('linkidSgJ9Qk','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td width="7" colspan="5"><img src="img/leer.gif" width="7" height="15" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkidSgJ9Qk" id="linkidSgJ9Qk"></td>
<td valign="top" style="height:15px;"  width="100%" class="nav_table"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="text_with_image.phtml">Text with image</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="7"><img src="img/leer.gif" width="10" height="15" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='images.phtml';return false;" onMouseOver="MM_swapImage('linkid4GFgge','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td width="7" colspan="5"><img src="img/leer.gif" width="7" height="15" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkid4GFgge" id="linkid4GFgge"></td>
<td valign="top" style="height:15px;"  width="100%" class="nav_table"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="images.phtml">Images</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="7"><img src="img/leer.gif" width="10" height="15" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='index.php?list_(table)';return false;" onMouseOver="MM_swapImage('linkidyIb4H8','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td width="7" colspan="5"><img src="img/leer.gif" width="7" height="15" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkidyIb4H8" id="linkidyIb4H8"></td>
<td valign="top" style="height:15px;"  width="100%" class="nav_table"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="index.php?list_(table)">List (Table)</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="7"><img src="img/leer.gif" width="10" height="15" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='list.phtml';return false;" onMouseOver="MM_swapImage('linkidNtGDw8','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td width="7" colspan="5"><img src="img/leer.gif" width="7" height="15" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkidNtGDw8" id="linkidNtGDw8"></td>
<td valign="top" style="height:15px;"  width="100%" class="nav_table"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="list.phtml">List</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="7"><img src="img/leer.gif" width="10" height="15" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='link_e-mail.phtml';return false;" onMouseOver="MM_swapImage('linkidUaHzEa','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td width="7" colspan="5"><img src="img/leer.gif" width="7" height="15" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkidUaHzEa" id="linkidUaHzEa"></td>
<td valign="top" style="height:15px;"  width="100%" class="nav_table"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="link_e-mail.phtml">Link &amp; E-Mail</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="7"><img src="img/leer.gif" width="10" height="15" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='link_list.phtml';return false;" onMouseOver="MM_swapImage('linkidBiUXdZ','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td width="7" colspan="5"><img src="img/leer.gif" width="7" height="15" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkidBiUXdZ" id="linkidBiUXdZ"></td>
<td valign="top" style="height:15px;"  width="100%" class="nav_table"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="link_list.phtml">Link list</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="7"><img src="img/leer.gif" width="10" height="15" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='link_article.phtml';return false;" onMouseOver="MM_swapImage('linkidmCoyWX','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td width="7" colspan="5"><img src="img/leer.gif" width="7" height="15" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkidmCoyWX" id="linkidmCoyWX"></td>
<td valign="top" style="height:15px;"  width="100%" class="nav_table"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="link_article.phtml">Link article</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="7"><img src="img/leer.gif" width="10" height="15" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='article_menu.phtml';return false;" onMouseOver="MM_swapImage('linkidDLp8an','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td width="7" colspan="5"><img src="img/leer.gif" width="7" height="15" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkidDLp8an" id="linkidDLp8an"></td>
<td valign="top" style="height:15px;"  width="100%" class="nav_table"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="article_menu.phtml">Article Menu</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="7"><img src="img/leer.gif" width="10" height="15" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='multimedia.phtml';return false;" onMouseOver="MM_swapImage('linkidxmDuYp','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td width="7" colspan="5"><img src="img/leer.gif" width="7" height="15" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkidxmDuYp" id="linkidxmDuYp"></td>
<td valign="top" style="height:15px;"  width="100%" class="nav_table"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="multimedia.phtml">Multimedia</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="7"><img src="img/leer.gif" width="10" height="15" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='file_list.phtml';return false;" onMouseOver="MM_swapImage('linkid9wlWwV','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td width="7" colspan="5"><img src="img/leer.gif" width="7" height="15" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkid9wlWwV" id="linkid9wlWwV"></td>
<td valign="top" style="height:15px;"  width="100%" class="nav_table"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="file_list.phtml">File List</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="7"><img src="img/leer.gif" width="10" height="15" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='e-card.phtml';return false;" onMouseOver="MM_swapImage('linkidwrxgiC','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td width="7" colspan="5"><img src="img/leer.gif" width="7" height="15" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkidwrxgiC" id="linkidwrxgiC"></td>
<td valign="top" style="height:15px;"  width="100%" class="nav_table"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="e-card.phtml">E-Card</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="7"><img src="img/leer.gif" width="10" height="15" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='email_form.phtml';return false;" onMouseOver="MM_swapImage('linkidvIF0Fl','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td width="7" colspan="5"><img src="img/leer.gif" width="7" height="15" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkidvIF0Fl" id="linkidvIF0Fl"></td>
<td valign="top" style="height:15px;"  width="100%" class="nav_table"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="email_form.phtml">Email form</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="7"><img src="img/leer.gif" width="10" height="15" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='e-mail_contact_form.phtml';return false;" onMouseOver="MM_swapImage('linkidtGixSL','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td width="7" colspan="5"><img src="img/leer.gif" width="7" height="15" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkidtGixSL" id="linkidtGixSL"></td>
<td valign="top" style="height:15px;"  width="100%" class="nav_table"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="e-mail_contact_form.phtml">Email contact form</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="7"><img src="img/leer.gif" width="10" height="15" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='newsletter_en.phtml';return false;" onMouseOver="MM_swapImage('linkidtFDkPC','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td width="7" colspan="5"><img src="img/leer.gif" width="7" height="15" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkidtFDkPC" id="linkidtFDkPC"></td>
<td valign="top" style="height:15px;"  width="100%" class="nav_table"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="newsletter_en.phtml">Newsletter</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="7"><img src="img/leer.gif" width="10" height="15" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='searchcp.phtml';return false;" onMouseOver="MM_swapImage('linkidmlmOYQ','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td width="7" colspan="5"><img src="img/leer.gif" width="7" height="15" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkidmlmOYQ" id="linkidmlmOYQ"></td>
<td valign="top" style="height:15px;"  width="100%" class="nav_table"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="searchcp.phtml">Search</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="7"><img src="img/leer.gif" width="10" height="15" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='guestbook__comm.phtml';return false;" onMouseOver="MM_swapImage('linkid2k4e3h','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td width="7" colspan="5"><img src="img/leer.gif" width="7" height="15" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkid2k4e3h" id="linkid2k4e3h"></td>
<td valign="top" style="height:15px;"  width="100%" class="nav_table"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="guestbook__comm.phtml">Guestbook / Comm.</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="7"><img src="img/leer.gif" width="10" height="15" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='sitemap_en_cws.phtml';return false;">
<td width="7" colspan="5"><img src="img/leer.gif" width="7" height="15" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_2" alt="" border="" name="linkidPmzsBL" id="linkidPmzsBL"></td>
<td valign="top" style="height:15px;"  width="100%" class="nav_table_active"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="sitemap_en_cws.phtml">Sitemap</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="7"><img src="img/leer.gif" width="10" height="15" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='bid.phtml';return false;" onMouseOver="MM_swapImage('linkid4vi2YY','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td width="7" colspan="5"><img src="img/leer.gif" width="7" height="15" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkid4vi2YY" id="linkid4vi2YY"></td>
<td valign="top" style="height:15px;"  width="100%" class="nav_table"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="bid.phtml">Bid</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="7"><img src="img/leer.gif" width="10" height="15" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='ext._content.phtml';return false;" onMouseOver="MM_swapImage('linkidogTzvc','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td width="7" colspan="5"><img src="img/leer.gif" width="7" height="15" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkidogTzvc" id="linkidogTzvc"></td>
<td valign="top" style="height:15px;"  width="100%" class="nav_table"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="ext._content.phtml">Ext. content</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="7"><img src="img/leer.gif" width="10" height="15" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='rss_feed_en.phtml';return false;" onMouseOver="MM_swapImage('linkid47lzWf','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td width="7" colspan="5"><img src="img/leer.gif" width="7" height="15" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkid47lzWf" id="linkid47lzWf"></td>
<td valign="top" style="height:15px;"  width="100%" class="nav_table"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="rss_feed_en.phtml">RSS Feed</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="7"><img src="img/leer.gif" width="10" height="15" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='contentpart_alias_en.phtml';return false;" onMouseOver="MM_swapImage('linkid106omH','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td width="7" colspan="5"><img src="img/leer.gif" width="7" height="15" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkid106omH" id="linkid106omH"></td>
<td valign="top" style="height:15px;"  width="100%" class="nav_table"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="contentpart_alias_en.phtml">Contentpart Alias</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="7"><img src="img/leer.gif" width="10" height="15" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='deutsche_version.phtml?File_Administration';return false;" onMouseOver="MM_swapImage('linkidll8Cuu','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td width="7" colspan="3"><img src="img/leer.gif" width="7" height="15" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkidll8Cuu" id="linkidll8Cuu"></td>
<td valign="top" style="height:15px;"  width="100%" class="nav_table" colspan="3"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="deutsche_version.phtml?File_Administration">File</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="7"><img src="img/leer.gif" width="10" height="15" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='module_en.phtml';return false;" onMouseOver="MM_swapImage('linkidExrUny','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td width="7" colspan="3"><img src="img/leer.gif" width="7" height="15" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkidExrUny" id="linkidExrUny"></td>
<td valign="top" style="height:15px;"  width="100%" class="nav_table" colspan="3"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="module_en.phtml">Modules</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="7"><img src="img/leer.gif" width="10" height="15" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='message.phtml';return false;" onMouseOver="MM_swapImage('linkidNV6bUe','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td width="7" colspan="3"><img src="img/leer.gif" width="7" height="15" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkidNV6bUe" id="linkidNV6bUe"></td>
<td valign="top" style="height:15px;"  width="100%" class="nav_table" colspan="3"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="message.phtml">Message </a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="7"><img src="img/leer.gif" width="10" height="15" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='chat_en.phtml';return false;" onMouseOver="MM_swapImage('linkidbrwE09','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td width="7" colspan="3"><img src="img/leer.gif" width="7" height="15" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkidbrwE09" id="linkidbrwE09"></td>
<td valign="top" style="height:15px;"  width="100%" class="nav_table" colspan="3"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="chat_en.phtml">Chat</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="7"><img src="img/leer.gif" width="10" height="15" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='profile.phtml';return false;" onMouseOver="MM_swapImage('linkidJBawek','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td width="7" colspan="3"><img src="img/leer.gif" width="7" height="15" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkidJBawek" id="linkidJBawek"></td>
<td valign="top" style="height:15px;"  width="100%" class="nav_table" colspan="3"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="profile.phtml">Profile</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="7"><img src="img/leer.gif" width="10" height="15" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='admin_en_wpj.phtml';return false;" onMouseOver="MM_swapImage('linkid6hEPxq','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td width="7" colspan="3"><img src="img/leer.gif" width="7" height="15" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkid6hEPxq" id="linkid6hEPxq"></td>
<td valign="top" style="height:15px;"  width="100%" class="nav_table" colspan="3"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="admin_en_wpj.phtml">Admin<img src="picture/myRT1/editR.gif" alt="11/24/2005" border="0"><img src="picture/myRT1/newR.gif" alt="11/25/2005" border="0"></a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="7"><img src="img/leer.gif" width="10" height="15" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='add_on_en.phtml';return false;" onMouseOver="MM_swapImage('linkidMJ7cwQ','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td width="7" colspan="2"><img src="img/leer.gif" width="7" height="15" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkidMJ7cwQ" id="linkidMJ7cwQ"></td>
<td valign="top" style="height:15px;"  width="100%" class="nav_table" colspan="4"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="add_on_en.phtml">Add On&#039;s</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="7"><img src="img/leer.gif" width="10" height="15" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='error_messages.phtml';return false;" onMouseOver="MM_swapImage('linkidHDaXWa','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td width="7" colspan="2"><img src="img/leer.gif" width="7" height="15" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkidHDaXWa" id="linkidHDaXWa"></td>
<td valign="top" style="height:15px;"  width="100%" class="nav_table" colspan="4"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="error_messages.phtml">Error messages</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="7"><img src="img/leer.gif" width="10" height="15" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='search.phtml';return false;" onMouseOver="MM_swapImage('linkidLx6fVX','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td width="7" colspan="2"><img src="img/leer.gif" width="7" height="15" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkidLx6fVX" id="linkidLx6fVX"></td>
<td valign="top" style="height:15px;"  width="100%" class="nav_table" colspan="4"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="search.phtml">Search</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="7"><img src="img/leer.gif" width="10" height="15" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="location.href='contact.phtml';return false;" onMouseOver="MM_swapImage('linkidTeWoUc','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td width="7" colspan="2"><img src="img/leer.gif" width="7" height="15" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkidTeWoUc" id="linkidTeWoUc"></td>
<td valign="top" style="height:15px;"  width="100%" class="nav_table" colspan="4"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="contact.phtml">Contact</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="7"><img src="img/leer.gif" width="10" height="15" alt="" /></td>
</tr>
<tr style="cursor:pointer;cursor:hand;" onClick="window.open('http://chat.phpwcms-docu.de', 'phpwcmnewwin');return false;" onMouseOver="MM_swapImage('linkidUixLlU','','img/pfeil10x20_2',1);" onMouseOut="MM_swapImgRestore();">
<td width="7" colspan="2"><img src="img/leer.gif" width="7" height="15" alt="" /></td>
<td valign="top"><img src="img/pfeil10x20_1" alt="" border="" name="linkidUixLlU" id="linkidUixLlU"></td>
<td valign="top" style="height:15px;"  width="100%" class="nav_table" colspan="4"><img src="img/leer.gif" width="1" height="2" alt="" /><br /><a href="http://chat.phpwcms-docu.de" target="_blank">LIVE Chat</a><br /><img src="img/leer.gif" width="1" height="2" alt="" /></td>
<td width="7"><img src="img/leer.gif" width="10" height="15" alt="" /></td>
</tr>
</table></td>
  </tr>
 <tr>
    <td style="padding:10px; color:#000000;"><img src="picture/seperate.gif" border="0" alt="" /><BR><BR>
<a href="http://www.phpwcms.de/index.php?id=1,38,0,0,1,0" target="Blank">
<img src="content/gt/0bdf1abd9b924ef5db1c4d8b0ee60b57.png" alt="Important!!!" title="Important!!!" border="0" /><br>
<img src="content/gt/9053324adb81af310e436b5603bba41a.png" alt="Security fixes" title="Security fixes" border="0" /><br>
<img src="content/gt/8d03f106ba326cbce77da5e9d2a6fabe.png" alt="for the releases" title="for the releases" border="0" /><br>
<img src="content/gt/f6b3d6651de467e44cfdc1170eaba9d3.png" alt="1.1-RC4 / 1.1.9 / 1.2.3" title="1.1-RC4 / 1.1.9 / 1.2.3" border="0" /><br>
<img src="content/gt/9661ea0c3a00342c05e40467dd5ec5e5.png" alt="more..." title="more..." border="0" /></a><br><BR>
<img src="picture/seperate.gif" border="0" alt="" /><BR><BR>
<img src="content/gt/c71f316069deb34233025e9c4f057258.png" alt="Latest Version:" title="Latest Version:" border="0" /><br>
<img src="content/gt/e1fd75b3780539bb61dee5207be17344.png" alt="phpwcms 1.2.5-DEV" title="phpwcms 1.2.5-DEV" border="0" /><br><br>
<img src="content/gt/8dc723ca158601224d90ffc1e8ce1cf9.png" alt="Release Date:" title="Release Date:" border="0" /><img src="content/gt/03b1359638c5aa316e71c675a057924b.png" alt="14.08.2005" title="14.08.2005" border="0" /><BR>
<span style="align: right;"><a href="deutsche_version.phtml?id=286,216,0,0,1,0"><img src="content/gt/52a225872f962dd15d7991a1bb034024.png" alt="more..." title="more..." border="0" /></a></span><BR><BR>
<img src="picture/seperate.gif" border="0" alt="" /><BR><BR>
<a href="deutsche_version.phtml?cvs_info_en">
<img src="content/gt/f704f104d78353285df1da0d71934909.png" alt="Latest CVS Version:" title="Latest CVS Version:" border="0" /><br>
<img src="content/gt/146e33b31b78f1788072a33538f9b258.png" alt="phpwcms 1.2.6-DEV" title="phpwcms 1.2.6-DEV" border="0" /><BR>
<img src="content/gt/4af2b02fae456293d46da339f5a6ff76.png" alt="(patched)" title="(patched)" border="0" /><br><br>
<img src="content/gt/8dc723ca158601224d90ffc1e8ce1cf9.png" alt="Release Date:" title="Release Date:" border="0" /><BR>
<img src="content/gt/6667ead159ad3bb94a22870751be31a0.png" alt="14.12.2005" title="14.12.2005" border="0" /><BR>
<span style="align: right;"><img src="content/gt/11c0da7af1db5732850053c45a24a778.png" alt="DOWNLOAD" title="DOWNLOAD" border="0" /></a></span><BR><BR>
<img src="picture/seperate.gif" border="0" alt="" /></TD><BR>
  </tr>
<tr>
    <td height="20">&nbsp;</td>
  </tr>
  <tr>
    <td align="center"></td>
  </tr>
  <tr>
    <td height="20">&nbsp;</td>
  </tr>
</table>


</body>
</html>
</td>
<td valign="top" width="555" bgcolor="#ffffff" class="maincontent"><img src="img/leer.gif" border="0" width="10" height="1" alt="" />
<BR>
<a href="english_version.phtml">English</a> <span class="breadcrumb_spacer">&gt;</span> <a href="the_docu.phtml">The Docu<img src="picture/myRT1/editR.gif" alt="25/11/2005" border="0"><img src="picture/myRT1/newR.gif" alt="12/15/2005" border="0"></a> <span class="breadcrumb_spacer">&gt;</span> <a href="article.phtml">Articles<img src="picture/myRT1/newR.gif" alt="12/15/2005" border="0"></a> <span class="breadcrumb_spacer">&gt;</span> <a href="content_parts_en.phtml">Content Parts</a> <span class="breadcrumb_spacer">&gt;</span> Sitemap
<br>
<HR>
<br>
<a name="jump137"></a><h1>Content Part &quot;Sitemap&quot;</h1><div style="margin:25px 0 0 0; padding:0 0 0 0; clear:both;"></div><table width="158" border="0" cellspacing="0" cellpadding="0" align="left">
<tr><td class="image_td"><a href="zoom/NjgwMDNlODUyMGUzOTA1ODNhNzQyNzAzOWU3ZjdmMjkucG5nP3dpZHRoPSI2ODUiIGhlaWdodD0iNjAwIg.html" onClick="checkClickZoom();clickZoom('zoom/NjgwMDNlODUyMGUzOTA1ODNhNzQyNzAzOWU3ZjdmMjkucG5nP3dpZHRoPSI2ODUiIGhlaWdodD0iNjAwIg.html','previewpic','width=685,height=600');return false;.html" target="_blank"><img src="content/images/becf0c3cd75786ff991eeddfec24956e.png" width="150" height="131" border="0" class="image_img" alt="sitemap_en.png"></a></td><td><img src="img/leer.gif" width="8" height="1" alt="" /></td></tr>
</table><div class="articleText"><table height="150" cellspacing="0" cellpadding="0" width="70%" border="0">
    <tbody>
        <tr>
            <td valign="top">
            <p align="justify">With this content part you can offer your visitors a sitemap.</p>
            </td>
        </tr>
    </tbody>
</table></div><HR><table cellspacing="1" cellpadding="0" border="0">
    <tbody>
        <tr>
            <td bgcolor="#cccccc">
            <table cellspacing="1" cellpadding="5" border="0">
                <tbody>
                    <tr valign="top">
                        <td width="60" bgcolor="#ffffff" colspan="2"><strong>before (optional):</strong></td>
                        <td bgcolor="#ffffff" colspan="2">Here you enter the text that appears before the sitemap</td>
                    </tr>
                    <tr valign="top">
                        <td bgcolor="#ffffff" colspan="2"><!--StartFragment --><strong>after (optional):</strong><!--StartFragment --></td>
                        <td bgcolor="#ffffff" colspan="2">Here you enter the text that&nbsp;appears after the sitemap</td>
                    </tr>
                    <tr valign="top">
                        <td bgcolor="#ffffff" colspan="2">
                        <p align="left"><strong>level icon (optional):</strong><!--StartFragment --></p>
                        </td>
                        <td bgcolor="#ffffff" colspan="2">Here can you&nbsp;choose your own image for the levels&nbsp;e.g.&nbsp; <span style="FONT-STYLE: italic">img/article/fill_in_here.gif&nbsp;</span> for <img src="picture/../img/article/fill_in_here.gif" border="0" alt="" /></td>
                    </tr>
                    <tr>
                        <td bgcolor="#ffffff" colspan="2"><strong>article icon (optional):</strong></td>
                        <td bgcolor="#ffffff" colspan="2">Here you can choose&nbsp;your&nbsp;own image for the articles e.g.&nbsp;<br/>
                        <span style="FONT-STYLE: italic">img/usricon/usr_admin.gif</span> for <img src="picture/../img/usricon/usr_admin.gif" border="0" alt="" /></td>
                    </tr>
                    <tr valign="top">
                        <td bgcolor="#ffffff" colspan="2"><strong>display:</strong></td>
                        <td bgcolor="#ffffff" colspan="2">
                        <div align="left">Here you select from one of the following options:<br/>
                        <strong>1. structure levels only:</strong> the generated sitemap will only display the structure levels <br/>
                        <strong>2. structure levels + articles:</strong> the generated sitemap will display both structure levels and articles&nbsp;</div>
                        </td>
                    </tr>
                    <tr>
                        <td valign="top" bgcolor="#ffffff" colspan="2"><strong>level class (optional):</strong></td>
                        <td bgcolor="#ffffff" colspan="2">Create a class in the frontend.css&nbsp;for the levels and type only the class name in this field.</td>
                    </tr>
                    <tr valign="top">
                        <td bgcolor="#ffffff" colspan="2"><strong>article class (optional):</strong></td>
                        <td bgcolor="#ffffff" colspan="2">Create a class in the frontend.css for the article view and type only the class name into this field.</td>
                    </tr>
                    <tr>
                        <td bgcolor="#ffffff" colspan="2"><strong>counter:</strong></td>
                        <td bgcolor="#ffffff" colspan="2">Here you select from one of the following options: <br/>
                        <strong>1. don&rsquo;t add to class name:</strong> (no data available) <br/>
                        <strong>2. add to class name:</strong> (no data available)</td>
                    </tr>
                </tbody>
            </table>
            </td>
        </tr>
    </tbody>
</table>
<strong></strong>
<table width="100%"  border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td colspan="2"><HR></td>
  </tr>
  <tr>
    <td width="50%">Article created: 2004/08/27</td>
    <td align="right" width="50%">Last Changes: 2005/05/29</td>
  </tr>
  <tr>
    <td colspan="2">&nbsp;</td>
  </tr>
  <tr>
    <td colspan="2" class="comment">In case you find any mistakes or have enhancments, please use this <a href="#" onClick="javascript:window.open('./content/pages/message.htm','frage','width=400, height=250, screenX=440,screenY=200,menubar=no,statusbar=yes,scrollbar=yes,resizable=no');" target="" style="max-width:148px; overflow:hidden;"><u>form</u></a> .<br><BR>
Have you found this website a helpful resource in understanding the Phpwcms content management system? If so, would you consider making a donation?  Please click here: <a href="#paypal">PayPal</a>. We welcome any donation amount. Your contribution helps make this website an even better resource and helps underwrite the associated server expenses of accomodating a growing number of visitors.<BR>
This page use the version:</td>
  </tr>
  <tr>

    <td colspan="2"><img src="img/leer.gif" border="0" width="10" height="10" alt="" /></td>
  </tr>
</table>
</td>
</tr>
<tr>
<td colspan="2" style="height:10px;"  bgcolor="#ffffff" class="footer"><table width="100%" height="20" background="img/footer.gif" cellpadding="0" cellspacing="0" border="0">
	<tr><td width="180" align="center" valign="middle">9 User online</td>
	<td>
	<table width="100%"cellpadding="0" cellspacing="0" border="0">
   <tr>
    <td align="center"><a href="javascript:history.back();" target="_top" title="go back"><img src="picture/back_.gif" border="0" alt="Back"><img src="content/gt/a8cf006b46d2d29bf7161aa985b04a42.png" alt="Back" title="Back" border="0" /></a></td>
	<td align="center"><a href="sitemap_en.phtml"><img src="picture/sitemap_.gif" border="0"  alt="Sitemap"><img src="content/gt/38062c01670c74843cc0b291d94966c6.png" alt="Sitemap" title="Sitemap" border="0" /></a></td>
	<td align="center"><a href="169.137.1.1.1.0.phtml" target="_blank"><img src="picture/print_.gif" border="0" alt="Print"><img src="content/gt/b4fe92ce3b96c84ca1ee38340fc2a4e6.png" alt="Print" title="Print" border="0" /></a></td>
	<td align="center"><a href="guestbook.phtml"><img src="picture/icon_gaestebuch.gif" border="0" align="top" alt="Guestbook"><img src="content/gt/a8891d2da470901a9086f978d5a7dc3d.png" alt="Guestbook" title="Guestbook" border="0" /></a></td>
	<td align="center"><a href="#" onClick="BookMark_Page();return false;" title=""><img src="picture/favoriten_.gif" border="0"  alt="Bookmark"><img src="content/gt/a8d175704cefbe0ee8222b9bde55b692.png" alt="Bookmark" title="Bookmark" border="0" /></a></td>
    </tr>
</table></td>
	</tr>
</table>
<img src="img/leer.gif" border="0" width="760" height="10" alt="" /></td>
</tr>
</table>
</body>
</html>