<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<!--
	phpwcms | free open source content management system
	created by Oliver Georgi (oliver at phpwcms dot de) and licensed under GNU/GPL.
	phpwcms is copyright 2003-2007 of Oliver Georgi. Extensions are copyright of
	their respective owners. Visit project page for details: http://www.phpwcms.org/
//-->
<title>phpwcms-docu for  phpwcms :: web based content management system | Sitemap | Sitemap</title>
  <meta http-equiv="content-type" content="text/html; charset=iso-8859-1" />
  <meta http-equiv="content-style-type" content="text/css" />
  <script src="template/inc_js/frontend.js" type="text/javascript"></script>
  <style type="text/css">
  <!-- 
    @import url("template/inc_css/mpl_docu.css");
    @import url("template/inc_css/mpl_frontend.css");
    @import url("template/inc_css/mpl_menu.css");
    @import url("template/inc_css/mpl_objects.css");
  //-->
  </style>
<script type="text/javascript" language="javascript">
<!--
function MM_jumpMenu(targ,selObj,restore){ //v3.0
  eval(targ+".location='"+selObj.options[selObj.selectedIndex].value+"'");
  if (restore) selObj.selectedIndex=0;
}

function MM_findObj(n, d) { //v4.01
  var p,i,x;  if(!d) d=document; if((p=n.indexOf("?"))>0&&parent.frames.length) {
    d=parent.frames[n.substring(p+1)].document; n=n.substring(0,p);}
  if(!(x=d[n])&&d.all) x=d.all[n]; for (i=0;!x&&i<d.forms.length;i++) x=d.forms[i][n];
  for(i=0;!x&&d.layers&&i<d.layers.length;i++) x=MM_findObj(n,d.layers[i].document);
  if(!x && d.getElementById) x=d.getElementById(n); return x;
}

function MM_jumpMenuGo(selName,targ,restore){ //v3.0
  var selObj = MM_findObj(selName); if (selObj) MM_jumpMenu(targ,selObj,restore);
}
//-->
</script>
<meta name="Title" content="Die phpWCMS Dokumentation" />
<meta name="author" content="Oliver Frohnert, Mario Perez Leal" />
<meta name="Publisher" content="Oliver Frohnert, Mario Perez Leal, creacion" />
<meta name="Copyright" content="Oliver Frohnert, Mario Perez Leal, creacion" />
<meta name="keywords" content="frohnert, perez leal, creacion, documentation, dokumentation, phpwcms, cms, opensource, open source, docu" />
<meta name="description" content="Das Dokumentations Projekt für das Open Source CMS phpWCMS" />
<meta name="Audience" content="Alle" />
<meta name="Content-language" content="DE" />
<meta name="robots" content="index,follow" />
<meta name="expires" content="0" />
<meta name="revisit-after" content="7 days" />
<meta name="resource-type" content="document" />
<meta name="distribution" content="Global" />
<meta name="generator" content="PHPWCMS" />

  <!--[if lt IE 7]>
  <style type="text/css">
    body { behavior: url("template/inc_css/specific/csshover2.htc"); }
    img { behavior: url("template/inc_css/specific/pngbehavior.htc"); }
  </style>
  <![endif]-->
</head>
<body id="myid_35">
<div id="container"><a name="top" id="top"></a>


	<div id="head">
		
	<div id="mainnavi">
		<div class="fleft"><a href="deutsche_version.phtml">Startseite</a> | <a href="news_de.phtml">News</a> | <a href="die_docu.phtml">Die Docu</a> | <a href="Nuetzliche_Links_und_Tools.phtml">Links &amp; Tools</a> | <a href="downloads.phtml">Downloads</a> | <a href="kontakt.phtml">Kontakt</a> | <a href="faq_de.phtml">FAQ</a> | <a href="http://forum.phpwcms.org/" target="_blank">Forum</a> | <a href="howto_de.phtml">HowTo</a></div>				
		<div class="sys">Sonntag, 18. Oktober 2015<img src="img/leer.gif" border="0" width="5" height="1" alt="" />|<img src="img/leer.gif" border="0" width="5" height="1" alt="" />3 User online<img src="img/leer.gif" border="0" width="10" height="1" alt="" />
		<a href="deutsche_version.phtml" title="Deutsche Version"><img src="picture/../template/lang/all/flag_de.gif" border="0" alt="" /></a>
		<a href="english_version.phtml"  title="English version"><img src="picture/../template/lang/all/flag_en.gif" border="0" alt="" /></a>
		</div>
	</div>
	
	<a href="./" title="phpwcms-docu Startseite aufrufen" class="homelink">
	<span>&raquo; Zur phpwcms-docu Startseite</span></a>
	<h2>phpwcms-docu - Die Dokumentation f&uuml;r f&uuml;r das CMS phpWCMS</h2>
	<p>phpwcms-docu ist eine Art Kompass, der Ihnen die M&ouml;glichkeiten von phpWcms aufzeigt und Sie erfolgreich, ohne gro&szlig;e Umwege, zu Ihrer fertigen Web-Anwendung f&uuml;hren soll.
	</p>
	</div>

	
	<div id="left">
	<div class="leftnav" style="margin-top:24px;">
	
		
		
		

	</div> 
	</div> 
	  
	<div id="right">
		<div style="margin-top:24px;">			
		<form action="#" method="post" name="searchFE" onsubmit="s=document.getElementById('customSearchInput');if(s.value=='Suchen')return false;">
			<table width="100%" border="0" cellpadding="0" cellspacing="0">
			<tr>
					<td><input type="text" name="search_input_field" size="20" maxlength="200" id="customSearchInput" class="customSearchInput" value="" onfocus="if(this.value=='Suchen')this.value='';" onblur="if(this.value=='')this.value='Suchen';" /></td>
					<td><input type="image" name="search_go" onfocus="this.blur();" title="Suchen" src="/template/lang/all/submit.gif" /></td>
				</tr>
			</table>
			</form>
			
			      <script type="text/javascript" language="javascript">
			  <!-- 
			        document.getElementById("customSearchInput").value="Suchen";
			  //-->
			      </script>
				  
			<!-- <p style="margin-top:10px;">Schriftgrad &auml;ndern: <a href="[FontSize-]"><img src="template/lang/all/icons/reduce.gif" width="18" height="17" alt="" title="Verkleinern" border="0" /></a>
			<a href="[FontSize+]"><img src="template/lang/all/icons/extend.gif" width="18" height="17" alt="" title="Vergr&ouml;&szlig;ern" border="0" /></a>
			</p> -->
			
	
<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div>


<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div>
<!-- <a href="http://validator.w3.org/check?uri=http%3A%2F%2Fwww.phpwcms-docu.de%2Findex.php%3Fdeutsche_version" title="W3C Standard XHTML" target="_blank"><img src="picture/w3c/w3c_xhtml.gif" border="0" alt="" /></a>
<a href="http://jigsaw.w3.org/css-validator/validator?uri=http://www.phpwcms-docu.de" title="W3C Standard CSS" target="_blank"><img src="picture/w3c/w3c_css.gif" border="0" alt="" /></a><br />			
<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div> -->
<h3>Partnersites</h3>






<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div>

<div style="margin-top:10px; margin-bottom:15px;"></div>


<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div>
</div>

	</div> 
	
	<div id="content">
	<div id="bread">Sie sind hier: <a href="deutsche_version.phtml">Deutsch</a></div>
		
		<a name="jump7"></a><!-- Livedate: 28.04.2004 19:57:15 / Killdate: 31.12.2030 23:59:59 -->
<h1>Sitemap</h1>

<ul class="sitemap_art">
<li><a href="deutsche_version.phtml">Deutsch</a>
<ul class="sitemap_art1">
<li><a href="deutsche_version.phtml">Startseite</a></li>
<li><a href="news_de.phtml">News</a></li>
<li><a href="die_docu.phtml">Die Docu</a>
<ul class="sitemap_art2">
<li><a href="download-dev-versionen.phtml">Download Dev Versionen</a></li>
<li><a href="installation_und_upgrade_von_phpwcms.phtml">Installation &amp; Upgrade</a>
<ul class="sitemap_art3">
<li><a href="upgrade_phpwcms_deutsch.phtml">Upgrade</a>
<ul class="sitemap_art4">
<li><a href="upgrade_RC11_bis_129_nach_13x.phtml">RC 1.1 bis 1.2.9 -&gt; 1.3.x</a></li>
</ul></li>
<li><a href="db_sichern.phtml">DB sichern</a></li>
<li><a href="db_wiederherstellen.phtml">DB wiederherstellen</a></li>
<li><a href="config_dateien.phtml">Config Dateien</a>
<ul class="sitemap_art4">
<li><a href="confincphp_de.phtml">conf.inc.php</a></li>
</ul></li>
</ul></li>
<li><a href="verwaltung_artikel.phtml">Artikel</a>
<ul class="sitemap_art3">
<li><a href="artikel_erstellen.phtml">Artikel erstellen</a></li>
<li><a href="artikel_editieren.phtml">Artikel bearbeiten</a></li>
<li><a href="artikel_organisation.phtml">Artikel Organisation</a>
<ul class="sitemap_art4">
<li><a href="artikel_kopieren.phtml">Artikel kopieren</a></li>
<li><a href="artikel_verschieben.phtml">Artikel verschieben</a></li>
<li><a href="content_part_kopieren.phtml">Content Part kopieren</a></li>
<li><a href="content_part_verschieben.phtml">Content Part verschieben</a></li>
</ul></li>
<li><a href="content_parts_de.phtml">Content Parts</a>
<ul class="sitemap_art4">
<li><a href="einfacher_text.phtml">Einfacher Text</a></li>
<li><a href="content_part_html_de.phtml">HTML</a></li>
<li><a href="content_part_wysiwyg_html_de.phtml">WYSIWYG HTML</a></li>
<li><a href="content_part_code_de.phtml">Code</a></li>
<li><a href="content_part_text_mit_bild.phtml">Text mit Bild</a></li>
<li><a href="content_part_bilder_div.phtml"><span style="text-decoration:line-through;font-size:10px;">Bilder &lt;DIV&gt;</span></a></li>
<li><a href="content_part_bilder.phtml">Bilder</a></li>
<li><a href="content_part_aufzaehlung.phtml">Aufzählung</a></li>
<li><a href="content_part_liste.phtml">Liste</a></li>
<li><a href="content_part_link_und_e-mail.phtml">Link &amp; E-Mail</a></li>
<li><a href="content_part_linkliste.phtml">Linkliste</a></li>
<li><a href="content_part_artikellink.phtml">Artikellink</a></li>
<li><a href="content_part_teaser_artikellink.phtml"><span style="text-decoration:line-through;font-size:10px;">Teaser / Artikellink</span></a></li>
<li><a href="content_part_artikelmenue.phtml">Artikelmenü</a></li>
<li><a href="content_part_multimedia_de.phtml">Multimedia</a></li>
<li><a href="content_part_dateiliste.phtml">Dateiliste</a></li>
<li><a href="content_part_ecard_de.phtml">E-Card</a>
<ul class="sitemap_art5">
<li><a href="beispiel_content_part_ecard.phtml">E-Card Beispiel</a></li>
</ul></li>
<li><a href="content_part_formular.phtml">Formular</a></li>
<li><a href="content_part_e-mail_formulargenerator.phtml">E-Mail Form. [OLD]</a>
<ul class="sitemap_art5">
<li><a href="beispiel_content_part_e-mail_formulargenerator_eigene_weiterleitung.phtml">Eigene Weiterleitung</a></li>
</ul></li>
<li><a href="content_part_newsletter_de.phtml">Newsletter</a>
<ul class="sitemap_art5">
<li><a href="beispiel_content_part_newsletter.phtml">Newsletter Beispiel</a></li>
</ul></li>
<li><a href="content_part_suche.phtml">Suche</a></li>
<li><a href="content_part_gaestebuch_kommentar.phtml">Gästebuch / Komm.</a>
<ul class="sitemap_art5">
<li><a href="beispiel_content_part_gaestebuch_kommentar.phtml">GB. / Kom. Beispiel</a></li>
</ul></li>
<li><a href="content_part_sitemap_de.phtml">Sitemap</a></li>
<li><a href="content_part_externer_content.phtml">Ext. Content</a></li>
<li><a href="content_part_bildwechsel.phtml">Bildwechsel</a></li>
<li><a href="content_part_rss_feed_de.phtml">RSS Feed</a></li>
<li><a href="content_part_landkarte.phtml">Landkarte</a></li>
<li><a href="content_part_php_variablen.phtml">PHP Variablen</a></li>
<li><a href="content_part_contentpart_alias_de.phtml">Contentpart Alias</a></li>
<li><a href="content_part_poll_de.phtml"><span style="text-decoration:line-through;font-size:10px;">Poll</span></a></li>
<li><a href="content_part_kochrezept.phtml">Kochrezept</a></li>
<li><a href="content_part_faq_de.phtml">FAQ</a></li>
<li><a href="content_part_frontend_login_de.phtml"><span style="text-decoration:line-through;font-size:10px;">Frontend Login</span></a></li>
<li><a href="content_part_glossar.phtml"><span style="text-decoration:line-through;font-size:10px;">Plug-in: Glossar</span></a></li>
</ul></li>
</ul></li>
<li><a href="dateizentrale.phtml">Datei</a>
<ul class="sitemap_art3">
<li><a href="datei_verzeichnis_erstellen_und_bearbeiten.phtml">Verzeichnis erstellen und bearbeiten</a></li>
<li><a href="datei_hochladen.phtml">Dateien hochladen</a></li>
<li><a href="dateien_verwalten.phtml">Dateien verwalten</a></li>
<li><a href="dateien_suchen_loeschen.phtml">Dateien suchen &amp; löschen</a></li>
</ul></li>
<li><a href="verwaltung_module.phtml">Module</a>
<ul class="sitemap_art3">
<li><a href="modul_gt.phtml">Graphical Text</a>
<ul class="sitemap_art4">
<li><a href="modul_gt_farben-und_stile.phtml">Farben und Stile</a></li>
<li><a href="modul_gt_replacement_tag_de.phtml">Replacement Tags</a></li>
</ul></li>
<li><a href="Glossar_Modul.phtml"><span style="text-decoration:line-through;font-size:10px;">Glossar Modul</span></a></li>
<li><a href="Bannerwerbung.phtml"><span style="text-decoration:line-through;font-size:10px;">Bannerwerbung</span></a></li>
<li><a href="shop_produkte.phtml"><span style="text-decoration:line-through;font-size:10px;">Shop/Produkte</span></a></li>
</ul></li>
<li><a href="Kommunikation.phtml">Kommunikation</a>
<ul class="sitemap_art3">
<li><a href="kommunikation_newsletter.phtml"><span style="text-decoration:line-through;font-size:10px;">Newsletter</span></a></li>
<li><a href="kommunikation_newsletter_abonnenten.phtml">Newsletter Abonnenten</a></li>
<li><a href="kommunikation_newsletter_abonnoment.phtml">Newsletter Abonnoment</a></li>
<li><a href="kommunikation_nachrichtenzentrale.phtml">Nachrichtenzentrale</a></li>
<li><a href="kommunikation_neue_nachricht.phtml">Neue Nachricht</a></li>
</ul></li>
<li><a href="verwaltung_nachricht.phtml">Nachricht</a></li>
<li><a href="verwaltung_chat.phtml">Chat</a></li>
<li><a href="verwaltung_profil.phtml">Profil</a></li>
<li><a href="verwaltung_admin.phtml">Admin</a>
<ul class="sitemap_art3">
<li><a href="seitenstruktur.phtml">Seitenstruktur</a>
<ul class="sitemap_art4">
<li><a href="ebene_erstellen_und_bearbeiten.phtml">Ebene erstellen / bearbeiten</a></li>
<li><a href="ebene_verschieben.phtml">Ebene verschieben</a></li>
<li><a href="ebene_kopieren.phtml">Ebene kopieren</a></li>
</ul></li>
<li><a href="seitenlayout.phtml">Seitenlayout</a></li>
<li><a href="vorlagen_de.phtml">Vorlagen</a></li>
<li><a href="standard_css.phtml">Standard CSS</a></li>
<li><a href="benutzerverwaltung.phtml">Benutzerverwaltung</a>
<ul class="sitemap_art4">
<li><a href="benutzer_anlegen.phtml">Benutzer Anlegen</a></li>
</ul></li>
<li><a href="keywords_de.phtml"><span style="text-decoration:line-through;font-size:10px;">Keywords</span></a></li>
<li><a href="dateikategorien.phtml"><span style="text-decoration:line-through;font-size:10px;">Dateikategorien</span></a></li>
<li><a href="backend_standardtext.phtml">Backend Standardtext</a></li>
<li><a href="cache_zuruecksetzten.phtml">Cache zurücksetzten</a></li>
<li><a href="cache_loeschen.phtml">Cache löschen</a></li>
<li><a href="dateien_final_loeschen.phtml">Dateien final löschen</a></li>
<li><a href="replacement_tags_de.phtml">Replacement-Tags</a>
<ul class="sitemap_art4">
<li><a href="system_tags_.phtml">System Tags</a></li>
<li><a href="navigations_tags_.phtml">Navigations Tags</a></li>
<li><a href="link_tags_.phtml">Link Tags</a></li>
<li><a href="grafik_tags.phtml">Grafik Tags</a></li>
<li><a href="artikel_tags.phtml">Artikel Tags</a></li>
<li><a href="spracheinstellungen.phtml">Spracheinstellungen<br /></a></li>
</ul></li>
</ul></li>
<li><a href="add-on-und-vorlagen.phtml">Add Ons und Vorlagen</a>
<ul class="sitemap_art3">
<li><a href="system-add-ons-de.phtml">System Add Ons</a></li>
<li><a href="add_on_replacementtags_de.phtml">Replacement Tags</a></li>
<li><a href="teilt-eure-vorlagen.phtml">Teilt eure Vorlagen</a>
<ul class="sitemap_art4">
<li><a href="fuer-content-parts.phtml">für Content Parts</a>
<ul class="sitemap_art5">
<li><a href="cp_template_gaestebuch.phtml">Gästebuch</a></li>
</ul></li>
</ul></li>
</ul></li>
<li><a href="deutsche_version.phtml?replacement_tags_de">Replacement Tags</a></li>
<li><a href="deutsche_version.phtml?content_parts_de">Content Parts</a></li>
</ul></li>
<li><a href="Nuetzliche_Links_und_Tools.phtml">Links &amp; Tools</a></li>
<li><a href="downloads.phtml">Downloads</a></li>
<li><a href="kontakt.phtml">Kontakt</a>
<ul class="sitemap_art2">
<li><a href="impressum.phtml">Impressum</a></li>
<li><a href="nutzung.phtml">Nutzungsbedingungen</a></li>
<li><a href="linkus.phtml">Link us</a></li>
<li><a href="newsletter_de.phtml">Newsletter</a></li>
</ul></li>
<li><a href="faq_de.phtml">FAQ</a></li>
<li><a href="http://forum.phpwcms.org/" target="_blank">Forum</a></li>
<li><a href="howto_de.phtml">HowTo</a></li>
</ul></li>
</ul>
		 
		
		<br /><br />
		<div class="sub">
			
		</div>
				
	</div>
	
<div id="footer"><br /><br />
<br />





	<table width="97%" border="0" cellspacing="0" cellpadding="0">
		<tr>
			<td valign="bottom">	
			&copy; phpwcms-docu 2004-2015
			<img src="img/leer.gif" border="0" width="10" height="0" alt="" /><a href="impressum.phtml" class="phpwcmsIntLink"><img src="template/lang/all/icons/imprint.gif" width="9" height="15" alt="Impressum" title="Impressum" border="0" /></a>&nbsp; 
			<a href="sitemap_de.phtml" class="phpwcmsIntLink"><img src="template/lang/all/icons/sitemap.gif" width="19" height="15" alt="Sitemap" title="Sitemap" border="0" /></a>&nbsp; 
			<a href="gaestebuch.phtml" class="phpwcmsIntLink"><img src="template/lang/all/icons/gbook.gif" width="20" height="16" alt="Ins G&auml;stebuch eintragen" title="Ins G&auml;stebuch eintragen" border="0" /></a>&nbsp; 
			<a href="#" onclick="BookMark_Page();return false;" title="" class="phpwcmsBookmarkLink"><img src="template/lang/all/icons/favo.gif" width="12" height="15" alt="Seite als Bookmark speichern" title="Seite als Bookmark speichern" border="0" /></a>&nbsp; 
			     
			</td>
			<td valign="bottom" style="padding-right:25px;">
			
			
			
			</td>		
			<td width="150">
			</td>
		</tr>
	</table>
</div><br/>

</div>
</body>
</html>