<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<!--
	phpwcms | free open source content management system
	created by Oliver Georgi (oliver at phpwcms dot de) and licensed under GNU/GPL.
	phpwcms is copyright 2003-2007 of Oliver Georgi. Extensions are copyright of
	their respective owners. Visit project page for details: http://www.phpwcms.org/
//-->
<title>phpwcms-docu for  phpwcms :: web based content management system | System Tags{D:8/2/2007,30,neuR.gif} | System Replacement Tags</title>
  <meta http-equiv="content-type" content="text/html; charset=iso-8859-1" />
  <meta http-equiv="content-style-type" content="text/css" />
  <script src="template/inc_js/frontend.js" type="text/javascript"></script>
  <style type="text/css">
  <!-- 
    @import url("template/inc_css/mpl_docu.css");
    @import url("template/inc_css/mpl_frontend.css");
    @import url("template/inc_css/mpl_menu.css");
    @import url("template/inc_css/mpl_objects.css");
  //-->
  </style>
<script type="text/javascript" language="javascript">
<!--
function MM_jumpMenu(targ,selObj,restore){ //v3.0
  eval(targ+".location='"+selObj.options[selObj.selectedIndex].value+"'");
  if (restore) selObj.selectedIndex=0;
}

function MM_findObj(n, d) { //v4.01
  var p,i,x;  if(!d) d=document; if((p=n.indexOf("?"))>0&&parent.frames.length) {
    d=parent.frames[n.substring(p+1)].document; n=n.substring(0,p);}
  if(!(x=d[n])&&d.all) x=d.all[n]; for (i=0;!x&&i<d.forms.length;i++) x=d.forms[i][n];
  for(i=0;!x&&d.layers&&i<d.layers.length;i++) x=MM_findObj(n,d.layers[i].document);
  if(!x && d.getElementById) x=d.getElementById(n); return x;
}

function MM_jumpMenuGo(selName,targ,restore){ //v3.0
  var selObj = MM_findObj(selName); if (selObj) MM_jumpMenu(targ,selObj,restore);
}
//-->
</script>
<meta name="Title" content="Die phpWCMS Dokumentation" />
<meta name="author" content="Oliver Frohnert, Mario Perez Leal" />
<meta name="Publisher" content="Oliver Frohnert, Mario Perez Leal, creacion" />
<meta name="Copyright" content="Oliver Frohnert, Mario Perez Leal, creacion" />
<meta name="keywords" content="frohnert, perez leal, creacion, documentation, dokumentation, phpwcms, cms, opensource, open source, docu" />
<meta name="description" content="Das Dokumentations Projekt für das Open Source CMS phpWCMS" />
<meta name="Audience" content="Alle" />
<meta name="Content-language" content="DE" />
<meta name="robots" content="index,follow" />
<meta name="expires" content="0" />
<meta name="revisit-after" content="7 days" />
<meta name="resource-type" content="document" />
<meta name="distribution" content="Global" />
<meta name="generator" content="PHPWCMS" />

  <!--[if lt IE 7]>
  <style type="text/css">
    body { behavior: url("template/inc_css/specific/csshover2.htc"); }
    img { behavior: url("template/inc_css/specific/pngbehavior.htc"); }
  </style>
  <![endif]-->
</head>
<body id="myid_91">
<div id="container"><a name="top" id="top"></a>


	<div id="head">
		
	<div id="mainnavi">
		<div class="fleft"><a href="deutsche_version.phtml">Startseite</a> | <a href="news_de.phtml">News</a> | <span style="text-decoration:none;font-weight:bold;"><a href="die_docu.phtml">Die Docu</a></span> | <a href="Nuetzliche_Links_und_Tools.phtml">Links &amp; Tools</a> | <a href="downloads.phtml">Downloads</a> | <a href="kontakt.phtml">Kontakt</a> | <a href="faq_de.phtml">FAQ</a> | <a href="http://forum.phpwcms.org/" target="_blank">Forum</a> | <a href="howto_de.phtml">HowTo</a></div>				
		<div class="sys">Donnerstag, 16. Juli 2015<img src="img/leer.gif" border="0" width="5" height="1" alt="" />|<img src="img/leer.gif" border="0" width="5" height="1" alt="" />3 User online<img src="img/leer.gif" border="0" width="10" height="1" alt="" />
		<a href="deutsche_version.phtml" title="Deutsche Version"><img src="picture/../template/lang/all/flag_de.gif" border="0" alt="" /></a>
		<a href="english_version.phtml"  title="English version"><img src="picture/../template/lang/all/flag_en.gif" border="0" alt="" /></a>
		</div>
	</div>
	
	<a href="./" title="phpwcms-docu Startseite aufrufen" class="homelink">
	<span>&raquo; Zur phpwcms-docu Startseite</span></a>
	<h2>phpwcms-docu - Die Dokumentation f&uuml;r f&uuml;r das CMS phpWCMS</h2>
	<p>phpwcms-docu ist eine Art Kompass, der Ihnen die M&ouml;glichkeiten von phpWcms aufzeigt und Sie erfolgreich, ohne gro&szlig;e Umwege, zu Ihrer fertigen Web-Anwendung f&uuml;hren soll.
	</p>
	</div>

	
	<div id="left">
	<div class="leftnav" style="margin-top:24px;">
	
<div id="ul_div_309">
<ul>
	<li class="sub_no"><a href="download-dev-versionen.phtml">Download Dev Versionen</a></li>
	<li class="sub_no sub_ul_true"><a href="installation_und_upgrade_von_phpwcms.phtml">Installation &amp; Upgrade</a></li>
	<li class="sub_no sub_ul_true"><a href="verwaltung_artikel.phtml">Artikel</a></li>
	<li class="sub_no sub_ul_true"><a href="dateizentrale.phtml">Datei</a></li>
	<li class="sub_no sub_ul_true"><a href="verwaltung_module.phtml">Module</a></li>
	<li class="sub_no sub_ul_true"><a href="Kommunikation.phtml">Kommunikation</a></li>
	<li class="sub_no"><a href="verwaltung_nachricht.phtml">Nachricht</a></li>
	<li class="sub_no"><a href="verwaltung_chat.phtml">Chat</a></li>
	<li class="sub_no"><a href="verwaltung_profil.phtml">Profil</a></li>
	<li class="sub_ul"><a href="verwaltung_admin.phtml">Admin</a>
	<div id="ul_div_81">
	<ul>
		<li class="sub_no sub_ul_true"><a href="seitenstruktur.phtml">Seitenstruktur</a></li>
		<li class="sub_no"><a href="seitenlayout.phtml">Seitenlayout</a></li>
		<li class="sub_no"><a href="vorlagen_de.phtml">Vorlagen</a></li>
		<li class="sub_no"><a href="standard_css.phtml">Standard CSS</a></li>
		<li class="sub_no sub_ul_true"><a href="benutzerverwaltung.phtml">Benutzerverwaltung</a></li>
		<li class="sub_no"><a href="keywords_de.phtml"><span style="text-decoration:line-through;font-size:10px;">Keywords</span></a></li>
		<li class="sub_no"><a href="dateikategorien.phtml"><span style="text-decoration:line-through;font-size:10px;">Dateikategorien</span></a></li>
		<li class="sub_no"><a href="backend_standardtext.phtml">Backend Standardtext</a></li>
		<li class="sub_no"><a href="cache_zuruecksetzten.phtml">Cache zurücksetzten</a></li>
		<li class="sub_no"><a href="cache_loeschen.phtml">Cache löschen</a></li>
		<li class="sub_no"><a href="dateien_final_loeschen.phtml">Dateien final löschen</a></li>
		<li class="sub_ul"><a href="replacement_tags_de.phtml">Replacement-Tags</a>
		<div id="ul_div_69">
		<ul>
			<li class="sub_no active"><a href="system_tags_.phtml">System Tags</a></li>
			<li class="sub_no"><a href="navigations_tags_.phtml">Navigations Tags</a></li>
			<li class="sub_no"><a href="link_tags_.phtml">Link Tags</a></li>
			<li class="sub_no"><a href="grafik_tags.phtml">Grafik Tags</a></li>
			<li class="sub_no"><a href="artikel_tags.phtml">Artikel Tags</a></li>
			<li class="sub_no"><a href="spracheinstellungen.phtml">Spracheinstellungen<br /></a></li>
		</ul>
		</div>
		</li>
	</ul>
	</div>
	</li>
	<li class="sub_no sub_ul_true"><a href="add-on-und-vorlagen.phtml">Add Ons und Vorlagen</a></li>
	<li class="sub_no"><a href="deutsche_version.phtml?replacement_tags_de">Replacement Tags</a></li>
	<li class="sub_no"><a href="deutsche_version.phtml?content_parts_de">Content Parts</a></li>
</ul>
</div>

		
		
		

	</div> 
	</div> 
	  
	<div id="right">
		<div style="margin-top:24px;">			
		<form action="#" method="post" name="searchFE" onsubmit="s=document.getElementById('customSearchInput');if(s.value=='Suchen')return false;">
			<table width="100%" border="0" cellpadding="0" cellspacing="0">
			<tr>
					<td><input type="text" name="search_input_field" size="20" maxlength="200" id="customSearchInput" class="customSearchInput" value="" onfocus="if(this.value=='Suchen')this.value='';" onblur="if(this.value=='')this.value='Suchen';" /></td>
					<td><input type="image" name="search_go" onfocus="this.blur();" title="Suchen" src="/template/lang/all/submit.gif" /></td>
				</tr>
			</table>
			</form>
			
			      <script type="text/javascript" language="javascript">
			  <!-- 
			        document.getElementById("customSearchInput").value="Suchen";
			  //-->
			      </script>
				  
			<!-- <p style="margin-top:10px;">Schriftgrad &auml;ndern: <a href="[FontSize-]"><img src="template/lang/all/icons/reduce.gif" width="18" height="17" alt="" title="Verkleinern" border="0" /></a>
			<a href="[FontSize+]"><img src="template/lang/all/icons/extend.gif" width="18" height="17" alt="" title="Vergr&ouml;&szlig;ern" border="0" /></a>
			</p> -->
			
	<p style="margin-top:10px;">Bitte w&auml;hlen Sie: 
	
	 </p>
<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div>


<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div>
<!-- <a href="http://validator.w3.org/check?uri=http%3A%2F%2Fwww.phpwcms-docu.de%2Findex.php%3Fdeutsche_version" title="W3C Standard XHTML" target="_blank"><img src="picture/w3c/w3c_xhtml.gif" border="0" alt="" /></a>
<a href="http://jigsaw.w3.org/css-validator/validator?uri=http://www.phpwcms-docu.de" title="W3C Standard CSS" target="_blank"><img src="picture/w3c/w3c_css.gif" border="0" alt="" /></a><br />			
<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div> -->
<h3>Partnersites</h3>






<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div>

<div style="margin-top:10px; margin-bottom:15px;"></div>


<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div>
</div>

	</div> 
	
	<div id="content">
	<div id="bread">Sie sind hier: <a href="deutsche_version.phtml">Deutsch</a> <span class="breadcrumb_spacer">&gt;</span> <a href="die_docu.phtml">Die Docu</a> <span class="breadcrumb_spacer">&gt;</span> <a href="verwaltung_admin.phtml">Admin</a> <span class="breadcrumb_spacer">&gt;</span> <a href="replacement_tags_de.phtml">Replacement-Tags</a> <span class="breadcrumb_spacer">&gt;</span> System Tags</div>
		
		<a name="jump41"></a><!-- Livedate: 06.08.2004 09:47:48 / Killdate: 31.12.2030 23:59:59 -->
<h1>System Replacement Tags</h1>

<div align="right">
<form action="" name="insidejumper" id="insidejumper">
    <table cellspacing="0" cellpadding="0" border="0">
        <tbody>
            <tr>
                <td align="right">Replacement-Tags f&uuml;r &nbsp;</td>
                <td align="right"><select style="width: 150px;" onchange="MM_jumpMenu('parent',this,1)" name="jumper">
                <option value="#datumzeit">Datum &amp; Zeit</option>
                <option value="#php">Php</option>
                <option value="#nutzen">N&uuml;tzliches</option>
                <option value="#vorlagen">Vorlagen</option>
                <option value="#urls">Url</option>
                </select>  <input type="button" onclick="MM_jumpMenuGo('menu1','parent',1)" value="anzeigen" name="goto" class="globalbtstyle" /></td>
            </tr>
        </tbody>
    </table>
</form>
</div><div style="border-bottom:1px dotted #d2e2f5; margin-top:10px; margin-bottom:15px;"></div><h3>Datum und Zeit</h3><a name="datumzeit"></a><div style="margin-top:10px;">
<table width="100%" cellspacing="0" cellpadding="5" border="0">
    <tbody class="reptab">
        <tr class="reptab_head">
            <td colspan="2">RT: {<img src="img/leer.gif" border="0" width="0" height="0" alt="" />DATE_LONG} </td>
		</tr>
        <tr>
            <td width="100" valign="top"><strong>Verwendung:</strong></td>
            <td valign="top">
	Gibt das aktuelle Tagesdatum aus - in langer Schreibweise

</td>
        </tr>
        <tr>
            <td width="100" valign="top"><strong>Schreibweise:</strong></td>
            <td valign="top">{<img src="img/leer.gif" border="0" width="0" height="0" alt="" />DATE_LONG}</td>
        </tr>
        <tr>
            <td width="100" valign="top"><strong>Ausgabe-Format:</strong></td>
            <td valign="top"> Donnerstag, 16. Juli 2015</td>
        </tr>
        <tr>
            <td width="100" valign="top"><strong>Bemerkung:</strong></td>
            <td valign="top"><p>Um das Ausgabeformat oder die Sprache zu &auml;ndern schauen Sie bitte hier vorbei. <a href="spracheinstellungen.phtml" class="phpwcmsIntLink">Spracheinstellungen</a></p></td>
        </tr>
    </tbody>
</table>
</div><div style="margin-top:10px;">
<table width="100%" cellspacing="0" cellpadding="5" border="0">
    <tbody class="reptab">
        <tr class="reptab_head">
            <td colspan="2">RT: {<img src="img/leer.gif" border="0" width="0" height="0" alt="" />DATE_MEDIUM} </td>
		</tr>
        <tr>
            <td width="100" valign="top"><strong>Verwendung:</strong></td>
            <td valign="top">
	Gibt das aktuelle Tagesdatum aus - in mittellanger Schreibweise

</td>
        </tr>
        <tr>
            <td width="100" valign="top"><strong>Schreibweise:</strong></td>
            <td valign="top">{<img src="img/leer.gif" border="0" width="0" height="0" alt="" />DATE_MEDIUM}</td>
        </tr>
        <tr>
            <td width="100" valign="top"><strong>Ausgabe-Format:</strong></td>
            <td valign="top"> Do, 16. Juli 15</td>
        </tr>
        <tr>
            <td width="100" valign="top"><strong>Bemerkung:</strong></td>
            <td valign="top"><p>Um das Ausgabeformat oder die Sprache zu &auml;ndern schauen Sie bitte hier vorbei. <a href="spracheinstellungen.phtml" class="phpwcmsIntLink">Spracheinstellungen</a></p></td>
        </tr>
    </tbody>
</table>
</div><div style="margin-top:10px;">
<table width="100%" cellspacing="0" cellpadding="5" border="0">
    <tbody class="reptab">
        <tr class="reptab_head">
            <td colspan="2">RT: {<img src="img/leer.gif" border="0" width="0" height="0" alt="" />DATE_SHORT} </td>
		</tr>
        <tr>
            <td width="100" valign="top"><strong>Verwendung:</strong></td>
            <td valign="top">
	Gibt das aktuelle Tagesdatum aus - in kurzer Schreibweise

</td>
        </tr>
        <tr>
            <td width="100" valign="top"><strong>Schreibweise:</strong></td>
            <td valign="top">{<img src="img/leer.gif" border="0" width="0" height="0" alt="" />DATE_SHORT}</td>
        </tr>
        <tr>
            <td width="100" valign="top"><strong>Ausgabe-Format:</strong></td>
            <td valign="top"> 16.07.2015</td>
        </tr>
        <tr>
            <td width="100" valign="top"><strong>Bemerkung:</strong></td>
            <td valign="top"><p>Um das Ausgabeformat oder die Sprache zu &auml;ndern schauen Sie bitte hier vorbei. <a href="spracheinstellungen.phtml" class="phpwcmsIntLink">Spracheinstellungen</a></p></td>
        </tr>
    </tbody>
</table>
</div><div style="margin-top:10px;">
<table width="100%" cellspacing="0" cellpadding="5" border="0">
    <tbody class="reptab">
        <tr class="reptab_head">
            <td colspan="2">RT: {<img src="img/leer.gif" border="0" width="0" height="0" alt="" />TIME_SHORT} </td>
		</tr>
        <tr>
            <td width="100" valign="top"><strong>Verwendung:</strong></td>
            <td valign="top">
	Gibt die aktuelle Tageszeit aus - in kurzer Schreibweise.

</td>
        </tr>
        <tr>
            <td width="100" valign="top"><strong>Schreibweise:</strong></td>
            <td valign="top">{<img src="img/leer.gif" border="0" width="0" height="0" alt="" />TIME_SHORT}</td>
        </tr>
        <tr>
            <td width="100" valign="top"><strong>Ausgabe-Format:</strong></td>
            <td valign="top"> 09:01</td>
        </tr>
        <tr>
            <td width="100" valign="top"><strong>Bemerkung:</strong></td>
            <td valign="top"><p>Um das Ausgabeformat oder die Sprache zu &auml;ndern schauen Sie bitte hier vorbei. <a href="spracheinstellungen.phtml" class="phpwcmsIntLink">Spracheinstellungen</a></p></td>
        </tr>
    </tbody>
</table>
</div><div style="margin-top:10px;">
<table width="100%" cellspacing="0" cellpadding="5" border="0">
    <tbody class="reptab">
        <tr class="reptab_head">
            <td colspan="2">RT: {<img src="img/leer.gif" border="0" width="0" height="0" alt="" />TIME_LONG} </td>
		</tr>
        <tr>
            <td width="100" valign="top"><strong>Verwendung:</strong></td>
            <td valign="top">
	Gibt die aktuelle Tageszeit aus - in langer Schreibweise.

</td>
        </tr>
        <tr>
            <td width="100" valign="top"><strong>Schreibweise:</strong></td>
            <td valign="top">{<img src="img/leer.gif" border="0" width="0" height="0" alt="" />TIME_LONG}</td>
        </tr>
        <tr>
            <td width="100" valign="top"><strong>Ausgabe-Format:</strong></td>
            <td valign="top"> 09:01:59</td>
        </tr>
        <tr>
            <td width="100" valign="top"><strong>Bemerkung:</strong></td>
            <td valign="top"><p>Um das Ausgabeformat oder die Sprache zu &auml;ndern schauen Sie bitte hier vorbei. <a href="spracheinstellungen.phtml" class="phpwcmsIntLink">Spracheinstellungen</a></p></td>
        </tr>
    </tbody>
</table>
</div><div style="border-bottom:1px dotted #d2e2f5; margin-top:10px; margin-bottom:15px;"></div><h3>PHP</h3><a name="php"></a><div style="margin-top:10px;">
<table width="100%" cellspacing="0" cellpadding="5" border="0">
    <tbody class="reptab">
        <tr class="reptab_head">
            <td colspan="2">RT: [<img src="img/leer.gif" border="0" width="0" height="0" alt="" />PHP] mein_PHP_code ; mehr_PHP_code [/PHP] </td>
		</tr>
        <tr>
            <td width="100" valign="top"><strong>Verwendung:</strong></td>
            <td valign="top">
	Hiermit kann benötigter PHP-Code direkt eingegeben werden.

</td>
        </tr>
        <tr>
            <td width="100" valign="top"><strong>Schreibweise:</strong></td>
            <td valign="top">[<img src="img/leer.gif" border="0" width="0" height="0" alt="" />PHP] mein_PHP_code ; mehr_PHP_code [/PHP]</td>
        </tr>
        <tr>
            <td width="100" valign="top"><strong>Ausgabe-Format:</strong></td>
            <td valign="top"> --</td>
        </tr>
        <tr>
            <td width="100" valign="top"><strong>Bemerkung:</strong></td>
            <td valign="top"><p>Eignet sich insbesondere f&uuml;r kurze PHP-Anweisungen.</p></td>
        </tr>
    </tbody>
</table>
</div><div style="margin-top:10px;">
<table width="100%" cellspacing="0" cellpadding="5" border="0">
    <tbody class="reptab">
        <tr class="reptab_head">
            <td colspan="2">RT: {<img src="img/leer.gif" border="0" width="0" height="0" alt="" />PHP:mein_externe_PHP_Datei.php} </td>
		</tr>
        <tr>
            <td width="100" valign="top"><strong>Verwendung:</strong></td>
            <td valign="top">
	Hiermit wird ein komplettes PHP-Script eingebunden.

</td>
        </tr>
        <tr>
            <td width="100" valign="top"><strong>Schreibweise:</strong></td>
            <td valign="top">{<img src="img/leer.gif" border="0" width="0" height="0" alt="" />PHP:mein_externe_PHP_Datei.php}</td>
        </tr>
        <tr>
            <td width="100" valign="top"><strong>Ausgabe-Format:</strong></td>
            <td valign="top"> --</td>
        </tr>
        <tr>
            <td width="100" valign="top"><strong>Bemerkung:</strong></td>
            <td valign="top"><p>Es ist der Dateiname einschlie&szlig;lich der notwendigen Pfadangabe einzugeben!<br />
L&auml;ngere PHP-Scripte sollten ggf. innerhalb eines <em>iframe</em> in php<strong>WCMS</strong> eingebunden werden.</p></td>
        </tr>
    </tbody>
</table>
</div><div style="border-bottom:1px dotted #d2e2f5; margin-top:10px; margin-bottom:15px;"></div><h3>Nützliches ...</h3><a name="nutzen"></a><div style="margin-top:10px;">
<table width="100%" cellspacing="0" cellpadding="5" border="0">
    <tbody class="reptab">
        <tr class="reptab_head">
            <td colspan="2">RT: [<img src="img/leer.gif" border="0" width="0" height="0" alt="" />BACK] Text oder Bild [/BACK] </td>
		</tr>
        <tr>
            <td width="100" valign="top"><strong>Verwendung:</strong></td>
            <td valign="top">
	Erzeugt eine Zurück-Funktion.
	Bei Klick auf den Text oder das Icon springt die Anzeige auf die vorhergehende Seite der Historie.

</td>
        </tr>
        <tr>
            <td width="100" valign="top"><strong>Schreibweise:</strong></td>
            <td valign="top">[<img src="img/leer.gif" border="0" width="0" height="0" alt="" />BACK] Text oder Bild [/BACK]</td>
        </tr>
        <tr>
            <td width="100" valign="top"><strong>Ausgabe-Format:</strong></td>
            <td valign="top"> <a href="#" target="_top" title="go back" onclick="history.back();return false;" class="phpwcmsBackLink">eine Seite zurück</a></td>
        </tr>
        <tr>
            <td width="100" valign="top"><strong>Bemerkung:</strong></td>
            <td valign="top"><p>Anstelle des Textes kann auch eine Grafik eingef&uuml;gt werden,<br />
in der Form:<br />
<br />
[<img src="img/leer.gif" border="0" width="0" height="0" alt="" />BACK]{<img src="img/leer.gif" border="0" width="0" height="0" alt="" />IMAGE:back_link_.gif}[/BACK]</p>
<p><a href="#" target="_top" title="go back" onclick="history.back();return false;" class="phpwcmsBackLink"><img src="picture/back_link_.gif" border="0" alt="" /></a></p></td>
        </tr>
    </tbody>
</table>
</div><div style="margin-top:10px;">
<table width="100%" cellspacing="0" cellpadding="5" border="0">
    <tbody class="reptab">
        <tr class="reptab_head">
            <td colspan="2">RT: [<img src="img/leer.gif" border="0" width="0" height="0" alt="" />BOOKMARK] Text oder Bild [/BOOKMARK] </td>
		</tr>
        <tr>
            <td width="100" valign="top"><strong>Verwendung:</strong></td>
            <td valign="top">
	Erstellt einen Link zum Öffnen des Fensters
	Zu Favoriten hinzufügen

</td>
        </tr>
        <tr>
            <td width="100" valign="top"><strong>Schreibweise:</strong></td>
            <td valign="top">[<img src="img/leer.gif" border="0" width="0" height="0" alt="" />BOOKMARK] Text oder Bild [/BOOKMARK]</td>
        </tr>
        <tr>
            <td width="100" valign="top"><strong>Ausgabe-Format:</strong></td>
            <td valign="top"> <a href="#" onclick="BookMark_Page();return false;" title="" class="phpwcmsBookmarkLink">Zu Favoriten hinzufügen</a></td>
        </tr>
        <tr>
            <td width="100" valign="top"><strong>Bemerkung:</strong></td>
            <td valign="top"><p>Anstelle des Textes kann auch eine Grafik eingef&uuml;gt werden in der Form:<br />
<br />
[<img src="img/leer.gif" border="0" width="0" height="0" alt="" />BOOKMARK]{<img src="img/leer.gif" border="0" width="0" height="0" alt="" />IMAGE:bookmark_link_.gif}[/BOOKMARK]</p>
<p><a href="#" onclick="BookMark_Page();return false;" title="" class="phpwcmsBookmarkLink"><img src="picture/bookmark_link_.gif" border="0" alt="" /></a></p></td>
        </tr>
    </tbody>
</table>
</div><div style="margin-top:10px;">
<table width="100%" cellspacing="0" cellpadding="5" border="0">
    <tbody class="reptab">
        <tr class="reptab_head">
            <td colspan="2">RT: [<img src="img/leer.gif" border="0" width="0" height="0" alt="" />PRINT_PDF]Text oder Bild[<img src="img/leer.gif" border="0" width="0" height="0" alt="" />/PRINT_PDF] </td>
		</tr>
        <tr>
            <td width="100" valign="top"><strong>Verwendung:</strong></td>
            <td valign="top">
	Erstellt von der Aktuellen Seite eine PDF Datei. Diese Funktion ist verfügar ab Version 1.3.2

</td>
        </tr>
        <tr>
            <td width="100" valign="top"><strong>Schreibweise:</strong></td>
            <td valign="top">[<img src="img/leer.gif" border="0" width="0" height="0" alt="" />PRINT_PDF]Text oder Bild[<img src="img/leer.gif" border="0" width="0" height="0" alt="" />/PRINT_PDF]</td>
        </tr>
        <tr>
            <td width="100" valign="top"><strong>Ausgabe-Format:</strong></td>
            <td valign="top"> </td>
        </tr>
        <tr>
            <td width="100" valign="top"><strong>Bemerkung:</strong></td>
            <td valign="top"><p>Anstelle des Textes kann auch eine Grafik eingef&uuml;gt werden, in der Form:<br />
<br />
[PRINT_PDF<img src="img/leer.gif" border="0" width="0" height="0" alt="" />]{<img src="img/leer.gif" border="0" width="0" height="0" alt="" />IMAGE:icon_pdf.gif}[/PRINT_PDF<img src="img/leer.gif" border="0" width="0" height="0" alt="" />]<br />
 &nbsp;</p>
<p><b>Hinweis:</b><br />
Die Ausgabe der PDF Datei k&ouml;nnen Sie &uuml;ber eine vorlagen/template Datei steuern.<br />
Die Datei finden Sie im Ordner <strong>template/inc_default/pdf.tmpl</strong></p></td>
        </tr>
    </tbody>
</table>
</div><div style="margin-top:10px;">
<table width="100%" cellspacing="0" cellpadding="5" border="0">
    <tbody class="reptab">
        <tr class="reptab_head">
            <td colspan="2">RT: [<img src="img/leer.gif" border="0" width="0" height="0" alt="" />PRINT] Text oder Bild [<img src="img/leer.gif" border="0" width="0" height="0" alt="" />/PRINT] </td>
		</tr>
        <tr>
            <td width="100" valign="top"><strong>Verwendung:</strong></td>
            <td valign="top">
	Erzeugt einen Link zu einer druckerfreundlichen Ansicht, in der nur die Inhalts-Elemente des Content-Bereichs aufgeführt sind.
	Alle Header-, Footer- und Navigationselemente sind entfernt.

</td>
        </tr>
        <tr>
            <td width="100" valign="top"><strong>Schreibweise:</strong></td>
            <td valign="top">[<img src="img/leer.gif" border="0" width="0" height="0" alt="" />PRINT] Text oder Bild [<img src="img/leer.gif" border="0" width="0" height="0" alt="" />/PRINT]</td>
        </tr>
        <tr>
            <td width="100" valign="top"><strong>Ausgabe-Format:</strong></td>
            <td valign="top"> </td>
        </tr>
        <tr>
            <td width="100" valign="top"><strong>Bemerkung:</strong></td>
            <td valign="top"><p>Anstelle des Textes kann auch eine Grafik eingef&uuml;gt werden, in der Form:</p>
<p><br />
<strong>[<img src="img/leer.gif" border="0" width="0" height="0" alt="" />PRINT]{<img src="img/leer.gif" border="0" width="0" height="0" alt="" />IMAGE:print_link_.gif}[<img src="img/leer.gif" border="0" width="0" height="0" alt="" />/PRINT]</strong></p>
<p></p>
<p>&nbsp;</p>
<p><b>Tipp:</b></p>
<p>Um das Druckergebnis zu optimieren verwenden Sie in Ihrer Vorlage:</p>
<p>&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &lt;!--NO_PRINT_START//--&gt;</p>
<p>&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &lt;!--NO_PRINT_END//--&gt;</p>
<p>Der Bereich der sich dazwischen befindet wird beim Druck nicht ber&uuml;cksichtigt. Diese Tag's k&ouml;nnen mehrfach verwendet werden.</p></td>
        </tr>
    </tbody>
</table>
</div><div style="margin-top:10px;">
<table width="100%" cellspacing="0" cellpadding="5" border="0">
    <tbody class="reptab">
        <tr class="reptab_head">
            <td colspan="2">RT: [<img src="img/leer.gif" border="0" width="0" height="0" alt="" />RSS all] Text oder Bild [/RSS] </td>
		</tr>
        <tr>
            <td width="100" valign="top"><strong>Verwendung:</strong></td>
            <td valign="top">
	Mit diesem Replacement Tag können Sie Ihren Inhalt als RSS Feed anbieten

</td>
        </tr>
        <tr>
            <td width="100" valign="top"><strong>Schreibweise:</strong></td>
            <td valign="top">[<img src="img/leer.gif" border="0" width="0" height="0" alt="" />RSS all] Text oder Bild [/RSS]</td>
        </tr>
        <tr>
            <td width="100" valign="top"><strong>Ausgabe-Format:</strong></td>
            <td valign="top"> <a href="feeds.php?feed=91" target="_blank" class="phpwcmsRSSLink">RSS</a></td>
        </tr>
        <tr>
            <td width="100" valign="top"><strong>Bemerkung:</strong></td>
            <td valign="top"><p>Folgende Einstellungen sind m&ouml;glich:</p>
<p><strong>[<img src="img/leer.gif" border="0" width="0" height="0" alt="" />RSS all]RSS-Feed[/RSS]</strong><br />
gibt die komplette Webseite als RSS Feed aus.</p>
<p align="justify"><strong>[<img src="img/leer.gif" border="0" width="0" height="0" alt="" />RSS INT]RSS-Feed[/RSS]<br />
</strong>ersetzen Sie INT durch eine ID einer Strukturebene und es wird nur diese als RSS Feed ausgegeben.</p>
<p align="justify"><strong>[<img src="img/leer.gif" border="0" width="0" height="0" alt="" />RSS ALIAS]RSS-Feed[/RSS]</strong><br />
ersetzen Sie ALIAS durch einen auf Ihrer Webseite bestehenden Alias und es wird nur diese Ebene als RSS Feed ausgegeben.</p>
<p align="justify">Anstelle des Textes kann auch eine Grafik eingef&uuml;gt werden.<br />
<br />
<strong>[<img src="img/leer.gif" border="0" width="0" height="0" alt="" />RSS all]{<img src="img/leer.gif" border="0" width="0" height="0" alt="" />IMAGE:rss_valid.gif}[/RSS]<br />
<br />
</strong><a href="feeds.php?feed=all" target="_blank" class="phpwcmsRSSLink"><img src="picture/rss_valid.gif" border="0" alt="" /></a></p></td>
        </tr>
    </tbody>
</table>
</div><div style="border-bottom:1px dotted #d2e2f5; margin-top:10px; margin-bottom:15px;"></div><div style="margin-top:10px;">
<table width="100%" cellspacing="0" cellpadding="5" border="0">
    <tbody class="reptab">
        <tr class="reptab_head">
            <td colspan="2">RT: [<img src="img/leer.gif" border="0" width="0" height="0" alt="" />download=ID,ID,ID]Datei-1 Datei-2 Datei-3[/download] </td>
		</tr>
        <tr>
            <td width="100" valign="top"><strong>Verwendung:</strong></td>
            <td valign="top">
	Mit diesem Replacement Tag können Sie Dateien aus der Dateizentrale direkt zum Download anbieten. (Verfügbar ab V1.39 r187 - 21.05.2008)

</td>
        </tr>
        <tr>
            <td width="100" valign="top"><strong>Schreibweise:</strong></td>
            <td valign="top">[<img src="img/leer.gif" border="0" width="0" height="0" alt="" />download=ID,ID,ID]Datei-1 Datei-2 Datei-3[/download]</td>
        </tr>
        <tr>
            <td width="100" valign="top"><strong>Ausgabe-Format:</strong></td>
            <td valign="top"></td>
        </tr>
        <tr>
            <td width="100" valign="top"><strong>Bemerkung:</strong></td>
            <td valign="top">Die IDs werden in der Dateizentrale ermittelt. Beim &Uuml;berfahren der Datei/des Bildes mit der Maus wird die ID angezeigt. <br />
<br />
Inline-Download wird eingeschaltet. Die Ausgabe wird durch das Template /template/inc_default/filelist.html gesteuert.<br />
<br />
<br />
Folgende Einstellungen sind m&ouml;glich:<br />
<p><strong>[<img src="img/leer.gif" border="0" width="0" height="0" alt="" />download=ID,ID,ID]Datei-1 Datei-2 Datei-3[/download]</strong><br />
Bietet die drei Dateien Datei-1 Datei-2 Datei-3 zum Download an.</p>
<p align="justify"><strong>[<img src="img/leer.gif" border="0" width="0" height="0" alt="" />download=ID,ID,ID/]</strong><br />
Kurze Schreibweise ohne Namen.</p></td>
        </tr>
    </tbody>
</table>
</div><div style="border-bottom:1px dotted #d2e2f5; margin-top:10px; margin-bottom:15px;"></div><h3>Vorlagen</h3><a name="vorlagen"></a><div style="margin-top:10px;">
<table width="100%" cellspacing="0" cellpadding="5" border="0">
    <tbody class="reptab">
        <tr class="reptab_head">
            <td colspan="2">RT: {<img src="img/leer.gif" border="0" width="0" height="0" alt="" />BREADCRUMB} </td>
		</tr>
        <tr>
            <td width="100" valign="top"><strong>Verwendung:</strong></td>
            <td valign="top">
	Erzeugt ein sog. Brotkrümel-Menü, welches dem Besucher zeigt, an welcher Stelle der Navigation er sich befindet.
	Ermöglicht ein gezieltes, schrittweises Zurückgehen.

</td>
        </tr>
        <tr>
            <td width="100" valign="top"><strong>Schreibweise:</strong></td>
            <td valign="top">{<img src="img/leer.gif" border="0" width="0" height="0" alt="" />BREADCRUMB} oder {<img src="img/leer.gif" border="0" width="0" height="0" alt="" />BREADCRUMB:ID}</td>
        </tr>
        <tr>
            <td width="100" valign="top"><strong>Ausgabe-Format:</strong></td>
            <td valign="top"> <a href="index.phtml">Home</a> <span class="breadcrumb_spacer">&gt;</span> <a href="deutsche_version.phtml">Deutsch</a> <span class="breadcrumb_spacer">&gt;</span> <a href="die_docu.phtml">Die Docu</a> <span class="breadcrumb_spacer">&gt;</span> <a href="verwaltung_admin.phtml">Admin</a> <span class="breadcrumb_spacer">&gt;</span> <a href="replacement_tags_de.phtml">Replacement-Tags</a> <span class="breadcrumb_spacer">&gt;</span> System Tags oder (ID=309) <a href="die_docu.phtml">Die Docu</a> <span class="breadcrumb_spacer">&gt;</span> <a href="verwaltung_admin.phtml">Admin</a> <span class="breadcrumb_spacer">&gt;</span> <a href="replacement_tags_de.phtml">Replacement-Tags</a> <span class="breadcrumb_spacer">&gt;</span> System Tags</td>
        </tr>
        <tr>
            <td width="100" valign="top"><strong>Bemerkung:</strong></td>
            <td valign="top"><p>Sinnvoll bei Sites mit einer tiefen Navigations-Struktur.<br />
Wird normalerweise in der Vorlage eingesetzt. </p>
<p>Bei Verwendung der ID muss der aktive Link immer auf oder hinter der ID in der Seitenstruktur liegen, sonst wird ein Fallback generiert mit der Ausgabe von {<img src="img/leer.gif" border="0" width="0" height="0" alt="" />BREADCRUMB}</p></td>
        </tr>
    </tbody>
</table>
</div><div style="margin-top:10px;">
<table width="100%" cellspacing="0" cellpadding="5" border="0">
    <tbody class="reptab">
        <tr class="reptab_head">
            <td colspan="2">RT: {<img src="img/leer.gif" border="0" width="0" height="0" alt="" />CONTENT} </td>
		</tr>
        <tr>
            <td width="100" valign="top"><strong>Verwendung:</strong></td>
            <td valign="top">
	Verantwortlich für die Wiedegabe aller Inhalts-Elemente.
	Kann nur einmal vergeben werden! Steht sinnvoller weise innerhalb der Vorlage im Feld Haupt.

</td>
        </tr>
        <tr>
            <td width="100" valign="top"><strong>Schreibweise:</strong></td>
            <td valign="top">{<img src="img/leer.gif" border="0" width="0" height="0" alt="" />CONTENT}</td>
        </tr>
        <tr>
            <td width="100" valign="top"><strong>Ausgabe-Format:</strong></td>
            <td valign="top"> --</td>
        </tr>
        <tr>
            <td width="100" valign="top"><strong>Bemerkung:</strong></td>
            <td valign="top"><p>Sollte keine Vorlage eingegeben werden, ist diese RT im Haupt-Feld vorgegeben!</p>
<p>Neben diesem RT, gibt es weitere &quot;Vorlagen-RT's&quot;,&nbsp; die ebenfalls in den Vorlagen zum Einsatz kommen sollten:</p>
<ul>
    <li>{<img src="img/leer.gif" border="0" width="0" height="0" alt="" />HEADER<img src="img/leer.gif" border="0" width="0" height="0" alt="" />}</li>
    <li>{<img src="img/leer.gif" border="0" width="0" height="0" alt="" />RIGHT<img src="img/leer.gif" border="0" width="0" height="0" alt="" />}</li>
    <li>{<img src="img/leer.gif" border="0" width="0" height="0" alt="" />LEFT<img src="img/leer.gif" border="0" width="0" height="0" alt="" />}</li>
    <li>{<img src="img/leer.gif" border="0" width="0" height="0" alt="" />FOOTER<img src="img/leer.gif" border="0" width="0" height="0" alt="" />}</li>
</ul>
<p>Auch hier muss bemerkt werden, dass sie nur einmalig verwendet werden k&ouml;nnen.</p></td>
        </tr>
    </tbody>
</table>
</div><div style="border-bottom:1px dotted #d2e2f5; margin-top:10px; margin-bottom:15px;"></div><h3>URL</h3><a name="url"></a><div style="margin-top:10px;">
<table width="100%" cellspacing="0" cellpadding="5" border="0">
    <tbody class="reptab">
        <tr class="reptab_head">
            <td colspan="2">RT: {<img src="img/leer.gif" border="0" width="0" height="0" alt="" />SITE} </td>
		</tr>
        <tr>
            <td width="100" valign="top"><strong>Verwendung:</strong></td>
            <td valign="top">
	Gibt die Aktuelle URL aus.

</td>
        </tr>
        <tr>
            <td width="100" valign="top"><strong>Schreibweise:</strong></td>
            <td valign="top">{<img src="img/leer.gif" border="0" width="0" height="0" alt="" />SITE}index.php?hallo</td>
        </tr>
        <tr>
            <td width="100" valign="top"><strong>Ausgabe-Format:</strong></td>
            <td valign="top"> ./</td>
        </tr>
        <tr>
            <td width="100" valign="top"><strong>Bemerkung:</strong></td>
            <td valign="top"><p>Kann&nbsp;vor allem bei Weiterleitungen benutzt werden. Sehr n&uuml;tzlich wenn man z.B. die Domain wechselt oder die Seite lokal entwirft.</p></td>
        </tr>
    </tbody>
</table>
</div><div style="margin-top:10px;">
<table width="100%" cellspacing="0" cellpadding="5" border="0">
    <tbody class="reptab">
        <tr class="reptab_head">
            <td colspan="2">RT: {<img src="img/leer.gif" border="0" width="0" height="0" alt="" />URL:url_der_externen_site} </td>
		</tr>
        <tr>
            <td width="100" valign="top"><strong>Verwendung:</strong></td>
            <td valign="top">
	Hierdurch wird eine externe Internetseite eingebunden.

</td>
        </tr>
        <tr>
            <td width="100" valign="top"><strong>Schreibweise:</strong></td>
            <td valign="top">{<img src="img/leer.gif" border="0" width="0" height="0" alt="" />URL:url_der_externen_site}</td>
        </tr>
        <tr>
            <td width="100" valign="top"><strong>Ausgabe-Format:</strong></td>
            <td valign="top"> --</td>
        </tr>
        <tr>
            <td width="100" valign="top"><strong>Bemerkung:</strong></td>
            <td valign="top"><p><strong><em>Einschr&auml;nkung</em></strong>:&nbsp;<br />
Nur der Bereich zwischen&nbsp;&lt;BODY&gt; und &lt;/BODY&gt; wird &uuml;bernommen!</p></td>
        </tr>
    </tbody>
</table>
</div><div style="margin-top:10px;">
<table width="100%" cellspacing="0" cellpadding="5" border="0">
    <tbody class="reptab">
        <tr class="reptab_head">
            <td colspan="2">RT: [<img src="img/leer.gif" border="0" width="0" height="0" alt="" />PHP]echo FE_CURRENT_URL[/PHP] </td>
		</tr>
        <tr>
            <td width="100" valign="top"><strong>Verwendung:</strong></td>
            <td valign="top">
	Hierdurch wird die aktuelle URL im Content angezeigt.

</td>
        </tr>
        <tr>
            <td width="100" valign="top"><strong>Schreibweise:</strong></td>
            <td valign="top">[<img src="img/leer.gif" border="0" width="0" height="0" alt="" />PHP]echo FE_CURRENT_URL[/PHP]
oder
[<img src="img/leer.gif" border="0" width="0" height="0" alt="" />PHP]echo abs_url()[/PHP]</td>
        </tr>
        <tr>
            <td width="100" valign="top"><strong>Ausgabe-Format:</strong></td>
            <td valign="top"> deutsche_version.phtml?system_tags_</td>
        </tr>
        <tr>
            <td width="100" valign="top"><strong>Bemerkung:</strong></td>
            <td valign="top"><p><strong><em>Einschr&auml;nkung</em></strong>:&nbsp;<br />
Nur der Bereich zwischen&nbsp;&lt;BODY&gt; und &lt;/BODY&gt; wird &uuml;bernommen!</p></td>
        </tr>
    </tbody>
</table>
</div>
		 
		
		<br /><br />
		<div class="sub">
		Artikel erstellt am: Montag, 23. August 2004 <br /> Letzte &Auml;nderung: Dienstag, 04. Januar 2011	
		</div>
				
	</div>
	
<div id="footer">





	<table width="97%" border="0" cellspacing="0" cellpadding="0">
		<tr>
			<td valign="bottom">	
			&copy; phpwcms-docu 2004-2015
			<img src="img/leer.gif" border="0" width="10" height="0" alt="" /><a href="impressum.phtml" class="phpwcmsIntLink"><img src="template/lang/all/icons/imprint.gif" width="9" height="15" alt="Impressum" title="Impressum" border="0" /></a>&nbsp; 
			<a href="sitemap_de.phtml" class="phpwcmsIntLink"><img src="template/lang/all/icons/sitemap.gif" width="19" height="15" alt="Sitemap" title="Sitemap" border="0" /></a>&nbsp; 
			<a href="gaestebuch.phtml" class="phpwcmsIntLink"><img src="template/lang/all/icons/gbook.gif" width="20" height="16" alt="Ins G&auml;stebuch eintragen" title="Ins G&auml;stebuch eintragen" border="0" /></a>&nbsp; 
			<a href="#" onclick="BookMark_Page();return false;" title="" class="phpwcmsBookmarkLink"><img src="template/lang/all/icons/favo.gif" width="12" height="15" alt="Seite als Bookmark speichern" title="Seite als Bookmark speichern" border="0" /></a>&nbsp; 
			     
			</td>
			<td valign="bottom" style="padding-right:25px;">
			
			
			
			</td>		
			<td width="150">
			</td>
		</tr>
	</table>
</div><br/>

</div>
</body>
</html>