<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<!--
	phpwcms | free open source content management system
	created by Oliver Georgi (oliver at phpwcms dot de) and licensed under GNU/GPL.
	phpwcms is copyright 2003-2007 of Oliver Georgi. Extensions are copyright of
	their respective owners. Visit project page for details: http://www.phpwcms.org/
//-->
<title>phpwcms-docu for  phpwcms :: web based content management system | RC 1.1 bis 1.2.9 -&gt; 1.3.x{D:7/27/2007,30,neuR.gif} | Update von RC 1.1 bis 1.2.9 auf 1.3.x</title>
  <meta http-equiv="content-type" content="text/html; charset=iso-8859-1" />
  <meta http-equiv="content-style-type" content="text/css" />
  <script src="template/inc_js/frontend.js" type="text/javascript"></script>
  <style type="text/css">
  <!-- 
    @import url("template/inc_css/mpl_docu.css");
    @import url("template/inc_css/mpl_frontend.css");
    @import url("template/inc_css/mpl_menu.css");
    @import url("template/inc_css/mpl_objects.css");
  //-->
  </style>
<script type="text/javascript" language="javascript">
<!--
function MM_jumpMenu(targ,selObj,restore){ //v3.0
  eval(targ+".location='"+selObj.options[selObj.selectedIndex].value+"'");
  if (restore) selObj.selectedIndex=0;
}

function MM_findObj(n, d) { //v4.01
  var p,i,x;  if(!d) d=document; if((p=n.indexOf("?"))>0&&parent.frames.length) {
    d=parent.frames[n.substring(p+1)].document; n=n.substring(0,p);}
  if(!(x=d[n])&&d.all) x=d.all[n]; for (i=0;!x&&i<d.forms.length;i++) x=d.forms[i][n];
  for(i=0;!x&&d.layers&&i<d.layers.length;i++) x=MM_findObj(n,d.layers[i].document);
  if(!x && d.getElementById) x=d.getElementById(n); return x;
}

function MM_jumpMenuGo(selName,targ,restore){ //v3.0
  var selObj = MM_findObj(selName); if (selObj) MM_jumpMenu(targ,selObj,restore);
}
//-->
</script>
<meta name="Title" content="Die phpWCMS Dokumentation" />
<meta name="author" content="Oliver Frohnert, Mario Perez Leal" />
<meta name="Publisher" content="Oliver Frohnert, Mario Perez Leal, creacion" />
<meta name="Copyright" content="Oliver Frohnert, Mario Perez Leal, creacion" />
<meta name="keywords" content="frohnert, perez leal, creacion, documentation, dokumentation, phpwcms, cms, opensource, open source, docu" />
<meta name="description" content="Das Dokumentations Projekt für das Open Source CMS phpWCMS" />
<meta name="Audience" content="Alle" />
<meta name="Content-language" content="DE" />
<meta name="robots" content="index,follow" />
<meta name="expires" content="0" />
<meta name="revisit-after" content="7 days" />
<meta name="resource-type" content="document" />
<meta name="distribution" content="Global" />
<meta name="generator" content="PHPWCMS" />

  <link rel="stylesheet" href="template/slimbox/css/slimbox.css" type="text/css" media="screen" />
  <script src="template/inc_js/mootools/mootools.js" type="text/javascript"></script>
  <script src="template/slimbox/js/slimbox.js" type="text/javascript"></script>
  <!--[if lt IE 7]>
  <style type="text/css">
    body { behavior: url("template/inc_css/specific/csshover2.htc"); }
    img { behavior: url("template/inc_css/specific/pngbehavior.htc"); }
  </style>
  <![endif]-->
</head>
<body id="myid_390">
<div id="container"><a name="top" id="top"></a>


	<div id="head">
		
	<div id="mainnavi">
		<div class="fleft"><a href="deutsche_version.phtml">Startseite</a> | <a href="news_de.phtml">News</a> | <span style="text-decoration:none;font-weight:bold;"><a href="die_docu.phtml">Die Docu</a></span> | <a href="Nuetzliche_Links_und_Tools.phtml">Links &amp; Tools</a> | <a href="downloads.phtml">Downloads</a> | <a href="kontakt.phtml">Kontakt</a> | <a href="faq_de.phtml">FAQ</a> | <a href="http://forum.phpwcms.org/" target="_blank">Forum</a> | <a href="howto_de.phtml">HowTo</a></div>				
		<div class="sys">Sonntag, 2. März 2014<img src="img/leer.gif" border="0" width="5" height="1" alt="" />|<img src="img/leer.gif" border="0" width="5" height="1" alt="" />3 User online<img src="img/leer.gif" border="0" width="10" height="1" alt="" />
		<a href="deutsche_version.phtml" title="Deutsche Version"><img src="picture/../template/lang/all/flag_de.gif" border="0" alt="" /></a>
		<a href="english_version.phtml"  title="English version"><img src="picture/../template/lang/all/flag_en.gif" border="0" alt="" /></a>
		</div>
	</div>
	
	<a href="./" title="phpwcms-docu Startseite aufrufen" class="homelink">
	<span>&raquo; Zur phpwcms-docu Startseite</span></a>
	<h2>phpwcms-docu - Die Dokumentation f&uuml;r f&uuml;r das CMS phpWCMS</h2>
	<p>phpwcms-docu ist eine Art Kompass, der Ihnen die M&ouml;glichkeiten von phpWcms aufzeigt und Sie erfolgreich, ohne gro&szlig;e Umwege, zu Ihrer fertigen Web-Anwendung f&uuml;hren soll.
	</p>
	</div>

	
	<div id="left">
	<div class="leftnav" style="margin-top:24px;">
	
<div id="ul_div_309">
<ul>
	<li class="sub_no"><a href="download-dev-versionen.phtml">Download Dev Versionen</a></li>
	<li class="sub_ul"><a href="installation_und_upgrade_von_phpwcms.phtml">Installation &amp; Upgrade</a>
	<div id="ul_div_3">
	<ul>
		<li class="sub_ul"><a href="upgrade_phpwcms_deutsch.phtml">Upgrade</a>
		<div id="ul_div_389">
		<ul>
			<li class="sub_no active"><a href="upgrade_RC11_bis_129_nach_13x.phtml">RC 1.1 bis 1.2.9 -&gt; 1.3.x</a></li>
		</ul>
		</div>
		</li>
		<li class="sub_no"><a href="db_sichern.phtml">DB sichern</a></li>
		<li class="sub_no"><a href="db_wiederherstellen.phtml">DB wiederherstellen</a></li>
		<li class="sub_no sub_ul_true"><a href="config_dateien.phtml">Config Dateien</a></li>
	</ul>
	</div>
	</li>
	<li class="sub_no sub_ul_true"><a href="verwaltung_artikel.phtml">Artikel</a></li>
	<li class="sub_no sub_ul_true"><a href="dateizentrale.phtml">Datei</a></li>
	<li class="sub_no sub_ul_true"><a href="verwaltung_module.phtml">Module</a></li>
	<li class="sub_no sub_ul_true"><a href="Kommunikation.phtml">Kommunikation</a></li>
	<li class="sub_no"><a href="verwaltung_nachricht.phtml">Nachricht</a></li>
	<li class="sub_no"><a href="verwaltung_chat.phtml">Chat</a></li>
	<li class="sub_no"><a href="verwaltung_profil.phtml">Profil</a></li>
	<li class="sub_no sub_ul_true"><a href="verwaltung_admin.phtml">Admin</a></li>
	<li class="sub_no sub_ul_true"><a href="add-on-und-vorlagen.phtml">Add Ons und Vorlagen</a></li>
	<li class="sub_no"><a href="deutsche_version.phtml?replacement_tags_de">Replacement Tags</a></li>
	<li class="sub_no"><a href="deutsche_version.phtml?content_parts_de">Content Parts</a></li>
</ul>
</div>

		
		
		

	</div> 
	</div> 
	  
	<div id="right">
		<div style="margin-top:24px;">			
		<form action="#" method="post" name="searchFE" onsubmit="s=document.getElementById('customSearchInput');if(s.value=='Suchen')return false;">
			<table width="100%" border="0" cellpadding="0" cellspacing="0">
			<tr>
					<td><input type="text" name="search_input_field" size="20" maxlength="200" id="customSearchInput" class="customSearchInput" value="" onfocus="if(this.value=='Suchen')this.value='';" onblur="if(this.value=='')this.value='Suchen';" /></td>
					<td><input type="image" name="search_go" onfocus="this.blur();" title="Suchen" src="/template/lang/all/submit.gif" /></td>
				</tr>
			</table>
			</form>
			
			      <script type="text/javascript" language="javascript">
			  <!-- 
			        document.getElementById("customSearchInput").value="Suchen";
			  //-->
			      </script>
				  
			<!-- <p style="margin-top:10px;">Schriftgrad &auml;ndern: <a href="[FontSize-]"><img src="template/lang/all/icons/reduce.gif" width="18" height="17" alt="" title="Verkleinern" border="0" /></a>
			<a href="[FontSize+]"><img src="template/lang/all/icons/extend.gif" width="18" height="17" alt="" title="Vergr&ouml;&szlig;ern" border="0" /></a>
			</p> -->
			
	<p style="margin-top:10px;">Bitte w&auml;hlen Sie: 
	
	 </p>
<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div>


<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div>
<!-- <a href="http://validator.w3.org/check?uri=http%3A%2F%2Fwww.phpwcms-docu.de%2Findex.php%3Fdeutsche_version" title="W3C Standard XHTML" target="_blank"><img src="picture/w3c/w3c_xhtml.gif" border="0" alt="" /></a>
<a href="http://jigsaw.w3.org/css-validator/validator?uri=http://www.phpwcms-docu.de" title="W3C Standard CSS" target="_blank"><img src="picture/w3c/w3c_css.gif" border="0" alt="" /></a><br />			
<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div> -->
<h3>Partnersites</h3>






<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div>

<div style="margin-top:10px; margin-bottom:15px;"></div>


<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div>
</div>

	</div> 
	
	<div id="content">
	<div id="bread">Sie sind hier: <a href="deutsche_version.phtml">Deutsch</a> <span class="breadcrumb_spacer">&gt;</span> <a href="die_docu.phtml">Die Docu</a> <span class="breadcrumb_spacer">&gt;</span> <a href="installation_und_upgrade_von_phpwcms.phtml">Installation &amp; Upgrade</a> <span class="breadcrumb_spacer">&gt;</span> <a href="upgrade_phpwcms_deutsch.phtml">Upgrade</a> <span class="breadcrumb_spacer">&gt;</span> RC 1.1 bis 1.2.9 -&gt; 1.3.x</div>
		
		<a name="jump351"></a><!-- Livedate: 25.02.2005 13:27:15 / Killdate: 31.12.2030 23:59:59 -->
<h1>Update von RC 1.1 bis 1.2.9 auf 1.3.x</h1>
<h3>(Stand: Version 1.3.3)</h3>

<p><strong class="error">Hinweis: <br />
Bevor Sie mit dem eigentlichen Update beginnen sichern Sie ALLE Dateien und machen Sie ein Datenbank Backup.</strong></p><div style="margin:10px 0 0 0;padding:0;" class="spaceBeforeCP"></div><h4>Wie sichert man eine Datenbank?</h4>

<ul class="articleLinkInternal">

	<li><a href="aid=159.phtml">Datenbank sichern</a></li>

</ul>

<div style="border-bottom:1px dotted #d2e2f5; margin-top:10px; margin-bottom:15px;"></div><h3>1. Vorbereitungen</h3><p>Nachdem Sie nun alles gesichert&nbsp;und die aktuelle Version heruntergeladen und entpackt haben, editieren Sie bitte zuerst die <strong>conf.inc.php</strong>. Die <strong>conf.inc.php</strong> finden Sie ab sofort in folgendem Ordner: <strong>config/phpwcms/</strong>. Sie tr&auml;gt den namen <strong>dist.conf.inc.php</strong> nch dem bearbeiten bennen Sie diese Bitte in <strong>conf.inc.php</strong> um.<br />
Bitte bearbeiten Sie die <strong>neue conf.inc.php,</strong> so dass die Einstellungen mit denen der alten Version &uuml;bereinstimmen.<br />
<br />
<strong class="error">Wichtiger Hinweis: <br />
Die Ordnernamen haben sich mit Erscheinen der Version 1.2.9 ge&auml;ndert.</strong><br />
<br />
<code> // paths<br />
$phpwcms['DOC_ROOT']          = $_SERVER['DOCUMENT_ROOT'];<br />
$phpwcms['root']              = '';<br />
$phpwcms['file_path']         = '<strong>filearchive</strong>'; alter Name&nbsp; &quot;<strong>phpwcms_filestorage</strong>&quot;<br />
$phpwcms['templates']         = '<strong>template</strong>'; alter Name &quot;<strong>phpwcms_template&quot;</strong><br />
</code><br />
F&uuml;r das Update benennen Sie bitte den Ordner <strong>phpwcms_filestorage</strong> in <strong>filearchive</strong> und den Ordner <strong>phpwcms_template</strong> in <strong>template</strong> um.<br />
<br />
<strong> Dar&uuml;berhinaus m&uuml;ssen folgende Dateien angepasst werden</strong>.<br />
<br />
1. /config/phpwcms/conf.template_default.inc.php<br />
2. /template/inc_css/frontend.css<br />
<br />
<strong class="error"> Vergleichen Sie bitte nun noch das alte ( phpwcms_template ) und das neue Template ( template ) Verzeichnis, da viele neue Vorlagen dazugekommen sind. Wenn Sie f&uuml;r bestimmte Content Parts eigene Templates erstellt haben, m&uuml;ssen diese wieder in die entsprechende Verzeichnis kopiert werden, bzw. passen Sie die Neuen an, da dort in vielen F&auml;llen auch neue Einstellungen hinzugekommen sind.</strong><br />
<br />
Dies sind die Dateien, die sehr oft ver&auml;ndert werden. Sollten Sie an anderer Stelle noch &Auml;nderungen vorgenommen haben, passen Sie diese bitte auch an.</p><div style="border-bottom:1px dotted #d2e2f5; margin-top:10px; margin-bottom:15px;"></div><h3>2. Dateien hochladen</h3><p>Bevor Sie die Dateien mit einem FTP Programm hochladen.<br />
<br />
<strong class="error">An dieser Stelle nochmal der Hinweis das sie ein komplettes Backup aller Dateien machen sollten.</strong><br />
<br />
L&ouml;schen Sie bitte alle Ordner, die mit phpwcms zusammen h&auml;ngen auf ihrem Server / Webspace bis auf<br />
<strong><br />
content<br />
content/pages</strong>(seit 1.1-RC4 22.05.2004)<br />
<strong>filearchive</strong>(vorher phpwcms_filestorage)<br />
<strong>template</strong> (vorher phpwcms_template)<br />
<br />
L&ouml;schen Sie bitte auch noch <strong>den Inhalt</strong> folgender Ordner<br />
<br />
<strong>content/images</strong><br />
<strong>content/gt</strong> (seit 1.1-RC4 03.06.2004)<br />
<strong>content/rss</strong> (seit Version 1.1.5)<br />
<br />
<br />
Warum l&ouml;schen ? Dies ist nur eine Vorsichtsma&szlig;nahme, da es bei manchen Webspace Anbietern zu Problemen kommt, wenn man Dateien &uuml;berschreiben will. Ausserdem gibt es soviele &Auml;nderungen und somit wird sicher gestellt, dass keine alten Dateien im System bleiben.<br />
<br />
Laden Sie nun die die aktuelle Version hoch. Danach sollten Sie folgende Ordner auf Ihrem Webspace sehen.</p><div align="right"><a href="#top"><img src="img/article/top_link_0.gif" border="0" alt="" /></a></div><div style="border-bottom:1px dotted #d2e2f5; margin-top:10px; margin-bottom:15px;"></div><h3>3. Datei- und Verzeichnis-Rechte setzen</h3><h3>Setzen der Dateirechte</h3><p>Sie m&uuml;ssen nun die folgenden Dateien und Ordnern, die zum Funktionieren von phpwcms notwendig sind, die n&ouml;tigen Rechte geben. Diese k&ouml;nnen Sie mit Ihrem FTP-Programm setzen.</p>
<p>&nbsp;</p>
<fieldset> <legend>&nbsp;<img height="21" width="21" border="0" align="middle" title="Info" alt="Info" src="picture/lang/all/info_s.gif" /> <strong>CHMOD Werte setzen</strong>  </legend>
<table width="100%" cellspacing="0" cellpadding="6" border="0">
    <tbody>
        <tr>
            <td colspan="2"><strong class="btag">Objekt</strong></td>
            <td><strong class="btag">Pfad</strong></td>
            <td><strong class="btag">Rechte</strong></td>
        </tr>
        <tr class="tbfield">
            <td width="15"><img src="picture/icons/folder.gif" border="0" alt="" /></td>
            <td>Verzeichnis</td>
            <td>upload</td>
            <td>777</td>
        </tr>
        <tr>
            <td><img src="picture/icons/folder.gif" border="0" alt="" /></td>
            <td>Verzeichnis</td>
            <td>filearchive</td>
            <td>777</td>
        </tr>
        <tr class="tbfield">
            <td><img src="picture/icons/folder.gif" border="0" alt="" /></td>
            <td>Verzeichnis</td>
            <td>filearchive/can_be_deleted</td>
            <td>777</td>
        </tr>
        <tr>
            <td><img src="picture/icons/folder.gif" border="0" alt="" /></td>
            <td>Verzeichnis</td>
            <td>template</td>
            <td>777</td>
        </tr>
        <tr>
            <td><img src="picture/icons/folder.gif" border="0" alt="" /></td>
            <td>Verzeichnis</td>
            <td><span style="color: rgb(255, 0, 0);">template/template_lang</span></td>
            <td>777</td>
        </tr>
        <tr class="tbfield">
            <td><img src="picture/icons/folder.gif" border="0" alt="" /></td>
            <td>Verzeichnis</td>
            <td>content</td>
            <td>777</td>
        </tr>
        <tr>
            <td><img src="picture/icons/folder.gif" border="0" alt="" /></td>
            <td>Verzeichnis</td>
            <td>content/ads</td>
            <td>777</td>
        </tr>
        <tr class="tbfield">
            <td><img src="picture/icons/folder.gif" border="0" alt="" /></td>
            <td>Verzeichnis</td>
            <td>content/images</td>
            <td>777</td>
        </tr>
        <tr>
            <td><img src="picture/icons/folder.gif" border="0" alt="" /></td>
            <td>Verzeichnis</td>
            <td>content/gt</td>
            <td>777</td>
        </tr>
        <tr class="tbfield">
            <td><img src="picture/icons/folder.gif" border="0" alt="" /></td>
            <td>Verzeichnis</td>
            <td>content/form</td>
            <td>777</td>
        </tr>
        <tr>
            <td><img src="picture/icons/folder.gif" border="0" alt="" /></td>
            <td>Verzeichnis</td>
            <td>content/rss</td>
            <td>777</td>
        </tr>
        <tr class="tbfield">
            <td><img src="picture/icons/folder.gif" border="0" alt="" /></td>
            <td>Verzeichnis</td>
            <td>content/tmp</td>
            <td>777</td>
        </tr>
        <tr>
            <td><img src="picture/icons/folder.gif" border="0" alt="" /></td>
            <td>Verzeichnis</td>
            <td>content/pages</td>
            <td>777</td>
        </tr>
        <tr>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
        <tr class="tbfield">
            <td colspan="4">&nbsp;</td>
        </tr>
        <tr>
            <td><img src="picture/icons/paper.gif" border="0" alt="" /></td>
            <td>Datei</td>
            <td>setup/setup.conf.inc.php</td>
            <td>666</td>
        </tr>
        <tr class="tbfield">
            <td><img src="picture/icons/paper.gif" border="0" alt="" /></td>
            <td>Datei</td>
            <td>template/inc_css/frontend.css</td>
            <td>666</td>
        </tr>
        <tr>
            <td><img src="picture/icons/paper.gif" border="0" alt="" /></td>
            <td>Datei</td>
            <td>config/phpwcms/conf.indexpage.inc.php</td>
            <td>666</td>
        </tr>
        <tr class="tbfield">
            <td><img src="picture/icons/paper.gif" border="0" alt="" /></td>
            <td>Datei</td>
            <td>template/inc_default/startup.php</td>
            <td>666</td>
        </tr>
    </tbody>
</table>
</fieldset><div style="margin:0 033px 0;padding:0;clear:both;"></div><div style="border-bottom:1px dotted #d2e2f5; margin-top:10px; margin-bottom:15px;"></div>
<table border="0" cellspacing="0" width="10%" cellpadding="0" align="left" class=" imgListTableLeft" summary="">
<tr>
	<td class="imagelisttd2"><a href="content/images/80f034e868ec6463daa5f447d593cb6f.png" rel="lightbox[LsoSB]" title="Bild 2 - Bestätigung der GPL" target="_blank"><img src="content/images/adba981185db810958f96a570e1ff055.png" width="150" height="114" border="0" class="imagelistimg" alt="update_01.png" /></a></td>
</tr>
<tr>
	<td class="imglistcaption">Bild 2 - Bestätigung der GPL</td>
</tr>

<tr>
	<td class="imagelistSpacerRow"><img src="img/leer.gif" width="1" height="1" border="0" alt="" /></td>
</tr>
<tr>
	<td class="imagelisttd2"><a href="content/images/7f383d584fcf1fcd7e6167ff14affb75.png" rel="lightbox[LsoSB]" title="Bild 3 - Überprüfung der Servereinstellungen" target="_blank"><img src="content/images/4d9f23304336a3420d067c513ca05665.png" width="150" height="112" border="0" class="imagelistimg" alt="update_02.png" /></a></td>
</tr>
<tr>
	<td class="imglistcaption">Bild 3 - Überprüfung der Servereinstellungen</td>
</tr>

<tr>
	<td class="imagelistSpacerRow"><img src="img/leer.gif" width="1" height="1" border="0" alt="" /></td>
</tr>
<tr>
	<td class="imagelisttd2"><a href="content/images/4bb5efa61fb7bf2c29aebab2f655321b.png" rel="lightbox[LsoSB]" title="Bild 4 - Datenbank Datei auswählen" target="_blank"><img src="content/images/c02ced163fd903248cc728f0f6a23ddf.png" width="119" height="175" border="0" class="imagelistimg" alt="update_03.png" /></a></td>
</tr>
<tr>
	<td class="imglistcaption">Bild 4 - Datenbank Datei auswählen</td>
</tr>

<tr>
	<td class="imagelistSpacerRow"><img src="img/leer.gif" width="1" height="1" border="0" alt="" /></td>
</tr>
<tr>
	<td class="imagelisttd2"><a href="content/images/dfe8d90d3c95279c1bbb748ca007faf7.png" rel="lightbox[LsoSB]" title="Bild 5 - Datenbank Datei bestätigen" target="_blank"><img src="content/images/2b53a9c9326b1d94e7ad92c8b16983a1.png" width="119" height="175" border="0" class="imagelistimg" alt="update_04.png" /></a></td>
</tr>
<tr>
	<td class="imglistcaption">Bild 5 - Datenbank Datei bestätigen</td>
</tr>

<tr>
	<td class="imagelistSpacerRow"><img src="img/leer.gif" width="1" height="1" border="0" alt="" /></td>
</tr>
<tr>
	<td class="imagelisttd2"><a href="content/images/bfbbd6dd0b10ec91875bdf6f946b28fe.png" rel="lightbox[LsoSB]" title="Bild 6 - Bestätigung nach Update" target="_blank"><img src="content/images/b8b4513df3843ed9b89b42434b3c25a5.png" width="146" height="175" border="0" class="imagelistimg" alt="update_04a.png" /></a></td>
</tr>
<tr>
	<td class="imglistcaption">Bild 6 - Bestätigung nach Update</td>
</tr>
</table>
<h3>4. Datenbank updaten</h3><p>Rufen Sie die <strong>index.php</strong> auf um nun mit dem Update der Datenbank zu beginnen. Diese finden Sie im Setup Ordner Ihrer phpwcms Installation. (http://www.ihre_domain.com/setup/index..php oder http://www.ihre_domain.com/unterordner/setup/index.php) <br />
<br />
Als erstes werden Sie gebeten die Lizenzbestimmungen (Bild 2) zu Akzeptieren. Tun Sie dies indem Sie auf &quot;<strong>I agree the GPL, continue...</strong>&quot; klicken.<br />
<br />
Nun werden nochmal die Servereinstellungen abgefragt ob phpwcms auf Ihrem Webspace / Server auch l&auml;uft (Bild 3).&nbsp; Klicken Sie unten auf &quot;<strong>Upgrade Existing Installation</strong>&quot; um nun zum eigentlich Datenbank Update zu gelangen.</p>
<p><br />
<strong class="error">Hinweis: Bitte lassen Sie folgende Punkte (Bild 4) erstmal unbeachtet. Wenn Sie einen der nachfolgenden Links  &quot;JETZT&quot; dr&uuml;cken ist das Update fehlgeschlagen. </strong><br />
<strong>Bei einem Upgrade von phpWCMS Versionen &auml;lter als 1.1.9:</strong><br />
There are some deeper changes. After upgrading db frame the following files needs to be processed.<br />
1) UPGRADE FILESTORAGE (all files will be moved and renamed)<br />
2) UPGRADE ARTICLE CONTENT IMAGE<br />
3) UPGRADE ARTICLE CONTENT IMAGELIST<br />
4) UPGRADE ARTICLE SUMMARY IMAGE<br />
<br />
<strong>Bei einem Upgrade von phpWCMS Versionen &auml;lter als 1.2.9:</strong><br />
5) UPGRADE PAGELAYOUT<br />
<br />
<strong>Bei einem Upgrade von phpWCMS Versionen &auml;lter als 1.3.1:</strong><br />
6) UPGRADE CONTENT PART MULTIMEDIA</p>
<p>Gehen sie bis zum Punkt: <br />
<strong>&quot;Please proof! Upgrade script will use following data:&quot;<br />
<br />
</strong>Darunter sehen Sie eine Tabelle in der nochmal alle Angaben zu Ihrer Datenbank zu sehen sind. Stimmen diese &uuml;berein.  Klicken sie nun mit der Maus auf das Feld &quot; <strong>select SQL file: please select</strong>&quot;. <br />
<br />
<strong>Sie sehen nun folgende Auswahl:</strong><br />
<br />
00__phpwcms_update_older.sql<br />
01__phpwcms_1.1-RC4_22-04-2004.sql<br />
02__phpwcms_1.1-RC4_31-05-2004.sql<br />
03__phpwcms_1.1-RC4_08-06-2004.sql<br />
04__phpwcms_1.1-RC4_13-08-004.sql<br />
05__phpwcms_1.1-RC4_25-08-004.sql<br />
06__phpwcms_1.1-RC4_15-10-004.sql<br />
07__1.1.5-DEV_to_1.1.9-DEV.sql<br />
07__27-08-2004_to_1.2.7.sql<br />
08__1.1.9-DEV_to_1.2-DEV.sql<br />
09__1.2.1-DEV_to_1.2.2-DEV.sql<br />
10__1.2.2-DEV_to_1.2.3-DEV.sql<br />
11__1.2.3-DEV_to_1.2.4-DEV.sql<br />
12__1.2.4-DEV_to_1.2.5-DEV.sql<br />
13__1.2.5-DEV_to_1.2.6-DEV.sql<br />
14__1.2.6-DEV_to_1.2.7-DEV.sql<br />
15__1.2.7-DEV_to_1.2.9.sql<br />
16__1.2.9-DEV_to_1.3.0.sql<br />
17__1.3.0_to_1.3.2.sql<br />
18__1.3.2_to_1.3.3.sql<br />
<br />
Dies sind die einzelen Datenbank Updates. W&auml;hlen Sie aus dieser Liste das erste Datum nach dem Release, das Sie installiert haben.</p><div style="margin:10px 0 0 0;padding:0;" class="spaceBeforeCP"></div><p>Wenn Ihre Installation vor der Version vom 22.04.2004 ist dann nehmen Sie zuerst das Update 00__phpwcms_update_older.sql. Nachdem Sie ein  Update ausgew&auml;hlt haben erscheint der im Textfeld darunter welche &auml;nderungen dieses Update hervorruft (Bild 5) . Best&auml;tigen Sie das  Ausf&uuml;hren des Updates druch klicken auf &quot;<strong>Upgrade Database</strong>&quot;</p>
<p>Wenn das Update ausgef&uuml;hrt wurde (Bild 6). Sehen Sie im Textfeld nochmal was gemacht wurde. Fehler werden mit rotem Text dargestellt.</p>
<p>Wiederholen Sie nun die Schritte indem Sie auf &quot;<strong>Choose another SQL file...</strong>&quot;  klicken bis sie zur letzten Update Datei kommen,&nbsp; lassen aber bitte die Datei &quot; <strong>07__1.1.5-DEV_to_1.1.9-DEV.sql</strong>&quot; aus und nehmen als n&auml;chste die &quot; <strong>07__27-08-2004_to_1.2.7.sql</strong>&quot; Datei, da diese nur f&uuml;r Nutzer der Version 1.1.5 ist.</p><div align="right"><a href="#top"><img src="img/article/top_link_0.gif" border="0" alt="" /></a></div><div style="border-bottom:1px dotted #d2e2f5; margin-top:10px; margin-bottom:15px;"></div>
<table border="0" cellspacing="0" width="10%" cellpadding="0" align="left" class=" imgListTableLeft" summary="">
<tr>
	<td class="imagelisttd2"><a href="content/images/c129524dd5d6fc7717b66ca2099f1e8b.png" rel="lightbox[8AJWM]" title="Bild 7 - Zusätzliche Datenbank Updates" target="_blank"><img src="content/images/b9e7236a17f742099ce7f1571f58ead9.png" width="119" height="175" border="0" class="imagelistimg" alt="add_upgrade.png" /></a></td>
</tr>
<tr>
	<td class="imglistcaption">Bild 7 - Zusätzliche Datenbank Updates</td>
</tr>

<tr>
	<td class="imagelistSpacerRow"><img src="img/leer.gif" width="1" height="1" border="0" alt="" /></td>
</tr>
<tr>
	<td class="imagelisttd2"><a href="content/images/709b36e8c10349f6192fc4ced2ab9e2f.png" rel="lightbox[8AJWM]" title="Bild 8 - UPGRADE&lt;br /&gt;FILESTORAGE" target="_blank"><img src="content/images/bb45528a458b2af42a82440ee6b60fff.png" width="150" height="71" border="0" class="imagelistimg" alt="update_05(upd_fs).png" /></a></td>
</tr>
<tr>
	<td class="imglistcaption">Bild 8 - UPGRADE<br />FILESTORAGE</td>
</tr>
</table>
<div style="margin:5px 0 0 0;padding:0;" class="spaceBeforeCP"></div><h3>5. Zusätzliche Updates ausführen</h3><p>Nun f&uuml;hren Sie die Updates aus die Sie am Anfang &uuml;berspringen sollten. (Bild 7)<br />
<br />
1) UPGRADE FILESTORAGE<br />
<br />
Da mit ab der Version 1.2.x die Unterordner 1-10 im Verzeichnis phpwcms_filestorage &uuml;berfl&uuml;ssig werden, m&uuml;ssen alle Dateien, die in den Ordnern liegen, umkopiert werden. Dies geschieht, indem Sie den Link &quot;<strong>UPGRADE FILESTORAGE</strong>&quot; anklicken.<br />
<br />
Es &ouml;ffnet sich nun ein neues Fenster (Bild 8) und Sie sehen dort folgenden Inhalt. Falls Sie sich nicht sicher sind, dass alle Dateien verschoben wurden, klicken sie auf <strong>&quot;click here</strong>&quot;. Dann k&ouml;nnen Sie dieses Fenster schliessen und die Unterordner 1-xx im Verzeichnis &quot;<strong>filearchive&quot; </strong>l&ouml;schen.<br />
<br />
Wiederholen Sie dieses f&uuml;r:<br />
<br />
2) UPGRADE ARTICLE CONTENT IMAGE<br />
3) UPGRADE ARTICLE CONTENT IMAGELIST<br />
4) UPGRADE ARTICLE SUMMARY IMAGE<br />
5) UPGRADE PAGELAYOUT<br />
6) UPGRADE CONTENT PART MULTIMEDIA</p><div style="margin:25px 0 0 0;padding:0;" class="spaceBeforeCP"></div><p>&nbsp;</p>
<p>Bei jedem der Datenbankupdate Links &ouml;ffnet sich ein neues Fenster, in dem entweder best&auml;tigt wurde, was gemacht wurde, das keine Aktualisierung notwendig war oder die Zeile &quot;<strong>if last number is &lt; xx click here</strong>&quot; (siehe auch Bild 8).&nbsp; Das bedeutet, dass das Upgrade Script die Updates f&uuml;r einen Bereich in Bl&ouml;cken ausf&uuml;hrt.</p>
<p>Wenn dort also steht &quot;<strong>if last number is &lt; 19 click here</strong>&quot; (wie auf dem Bild 8) und Sie sehen, dass die letzte &Auml;nderung z.b. Zeile <strong>18</strong> w&auml;re , m&uuml;ssten Sie auf jeden Fall nochmal auf &quot;<strong>click here</strong>&quot; dr&uuml;cken, um die letzten &Auml;nderungen durchzuf&uuml;hren, bis entweder keine Zeilen mehr da sind oder halt die letzte Zeile die Nummer tr&auml;gt wie in der <strong>&quot;if last number is &lt; xx click here&quot;</strong> angezeigt. Zur Sicherheit k&ouml;nnen Sie aber nochmal auf &quot;klicke here&quot; dr&uuml;cken. Somit erhalten Sie dann eine leere Seite wo nur noch der Text steht &quot;<strong>if last number is &lt; xx click here</strong>&quot;.<br />
<br />
Wenn Sie alle Updates durchgef&uuml;hrt haben, <strong>l&ouml;schen </strong>Sie bitte noch den &quot;<strong>setup</strong>&quot; Ordner und die Ordner <strong>1-10</strong> unter <strong>filearchive</strong> auf Ihrem&nbsp; Server / Webspace.<br />
<br />
Nun sollten Sie sich wie gewohnt anmelden k&ouml;nnen.</p>
		 
		
		<br /><br />
		<div class="sub">
		Artikel erstellt am: Donnerstag, 26. Juli 2007 <br /> Letzte &Auml;nderung: Dienstag, 04. Januar 2011	
		</div>
				
	</div>
	
<div id="footer">





	<table width="97%" border="0" cellspacing="0" cellpadding="0">
		<tr>
			<td valign="bottom">	
			&copy; phpwcms-docu 2004-2014
			<img src="img/leer.gif" border="0" width="10" height="0" alt="" /><a href="impressum.phtml" class="phpwcmsIntLink"><img src="template/lang/all/icons/imprint.gif" width="9" height="15" alt="Impressum" title="Impressum" border="0" /></a>&nbsp; 
			<a href="sitemap_de.phtml" class="phpwcmsIntLink"><img src="template/lang/all/icons/sitemap.gif" width="19" height="15" alt="Sitemap" title="Sitemap" border="0" /></a>&nbsp; 
			<a href="gaestebuch.phtml" class="phpwcmsIntLink"><img src="template/lang/all/icons/gbook.gif" width="20" height="16" alt="Ins G&auml;stebuch eintragen" title="Ins G&auml;stebuch eintragen" border="0" /></a>&nbsp; 
			<a href="#" onclick="BookMark_Page();return false;" title="" class="phpwcmsBookmarkLink"><img src="template/lang/all/icons/favo.gif" width="12" height="15" alt="Seite als Bookmark speichern" title="Seite als Bookmark speichern" border="0" /></a>&nbsp; 
			     
			</td>
			<td valign="bottom" style="padding-right:25px;">
			
			
			
			</td>		
			<td width="150">
			</td>
		</tr>
	</table>
</div><br/>

</div>
</body>
</html>