<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<!--
	phpwcms | free open source content management system
	created by Oliver Georgi (oliver at phpwcms dot de) and licensed under GNU/GPL.
	phpwcms is copyright 2003-2007 of Oliver Georgi. Extensions are copyright of
	their respective owners. Visit project page for details: http://www.phpwcms.org/
//-->
<title>phpwcms-docu for  phpwcms :: web based content management system | User administration{D:4/1/2005,30,newR.gif} | User administration</title>
  <meta http-equiv="content-type" content="text/html; charset=iso-8859-1" />
  <meta http-equiv="content-style-type" content="text/css" />
  <script src="template/inc_js/frontend.js" type="text/javascript"></script>
  <style type="text/css">
  <!-- 
    @import url("template/inc_css/mpl_frontend.css");
    @import url("template/inc_css/mpl_menu.css");
    @import url("template/inc_css/mpl_objects.css");
    @import url("template/inc_css/mpl_docu_en.css");
  //-->
  </style>
<meta name="Title" content="The phpWCMS Documentation" />
<meta name="author" content="Oliver Frohnert, Mario Perez Leal" />
<meta name="Publisher" content="Oliver Frohnert, Mario Perez Leal, creacion" />
<meta name="Copyright" content="Oliver Frohnert, Mario Perez Leal, creacion" />
<meta name="keywords" content="frohnert, perez leal, creacion, documentation, dokumentation, phpwcms, cms, opensource, open source, docu" />
<meta name="description" content="A Documentation Project for the  Open Source CMS phpWCMS" />
<meta name="Audience" content="Alle" />
<meta name="Content-language" content="EN" />
<meta name="robots"      content="index,follow" />
<meta name="expires" content="0" />
<meta name="revisit-after" content="7 days" />
<meta name="resource-type" content="document" />
<meta name="distribution" content="Global" />
<meta name="generator" content="PHPWCMS" />

  <!--[if lt IE 7]>
  <style type="text/css">
    body { behavior: url("template/inc_css/specific/csshover2.htc"); }
    img { behavior: url("template/inc_css/specific/pngbehavior.htc"); }
  </style>
  <![endif]-->
</head>
<body id="myid_326">
<div id="container"><a name="top" id="top"></a>


	<div id="head">
		
	<div id="mainnavi">
		<div class="fleft"><a href="english_version.phtml">Home</a> | <a href="news_en.phtml">News</a> | <span style="text-decoration:none;font-weight:bold;"><a href="the_docu.phtml">The Docu</a></span> | <a href="Usefull_Links_and_Tools.phtml">Links &amp; Tools</a> | <a href="contact.phtml">Contact</a> | <a href="faq_en.phtml">FAQ</a> | <a href="http://forum.phpwcms.org/" target="_blank">Forum</a> | <a href="howto_en.phtml">HowTo</a></div>				
		<div class="sys">Saturday, 21. February 2015<img src="img/leer.gif" border="0" width="5" height="1" alt="" />|<img src="img/leer.gif" border="0" width="5" height="1" alt="" />5 User online<img src="img/leer.gif" border="0" width="10" height="1" alt="" />
		<a href="deutsche_version.phtml" title="Deutsche Version"><img src="picture/../template/lang/all/flag_de.gif" border="0" alt="" /></a>
		<a href="english_version.phtml"  title="English version"><img src="picture/../template/lang/all/flag_en.gif" border="0" alt="" /></a>
		</div>
	</div>
	
	<a href="./" title="phpwcms-docu Startseite aufrufen" class="homelink">
	<span>&raquo; phpwcms-docu startpage</span></a>
	<h2>phpwcms-docu - Documentation for the Web Content Management System phpwcms</h2>
	<p>This website is targeted both to the beginner and the lateral entry following the goal to simplify the 
work with phpwcms and to focus on the essentials things.</p>
	</div>

	
	<div id="left">
	<div class="leftnav" style="margin-top:24px;">
	
<div id="ul_div_311">
<ul>
	<li class="sub_no"><a href="download-dev-versions.phtml">Download Dev Versions</a></li>
	<li class="sub_no sub_ul_true"><a href="installation_en.phtml">Installation &amp; Upgrade</a></li>
	<li class="sub_no sub_ul_true"><a href="article.phtml">Articles</a></li>
	<li class="sub_no sub_ul_true"><a href="file.phtml">File</a></li>
	<li class="sub_no sub_ul_true"><a href="module_en.phtml">Modules</a></li>
	<li class="sub_no sub_ul_true"><a href="communication.phtml">Communication </a></li>
	<li class="sub_no"><a href="chat_en.phtml">Chat</a></li>
	<li class="sub_no"><a href="profile.phtml">Profile</a></li>
	<li class="sub_ul"><a href="admin_en_.phtml">Admin</a>
	<div id="ul_div_312">
	<ul>
		<li class="sub_no sub_ul_true"><a href="sitestructure.phtml">Sitestructure</a></li>
		<li class="sub_ul active"><a href="user_administration.phtml">User administration</a>
		<div id="ul_div_326">
		<ul>
			<li class="sub_no"><a href="create_user.phtml">Create user</a></li>
		</ul>
		</div>
		</li>
		<li class="sub_no"><a href="remove_delete_files.phtml">Remove delete files</a></li>
		<li class="sub_no"><a href="templating.phtml">Templating </a></li>
		<li class="sub_no sub_ul_true"><a href="replacement_tags_en.phtml">Replacement Tags</a></li>
	</ul>
	</div>
	</li>
	<li class="sub_no sub_ul_true"><a href="add-ons-and-templates.phtml">Add On&#039;s and Templates</a></li>
	<li class="sub_no"><a href="deutsche_version.phtml?replacement_tags_en">Replacement Tags</a></li>
	<li class="sub_no"><a href="deutsche_version.phtml?content_parts_en">Content Parts</a></li>
</ul>
</div>

		
	</div> 
	</div> 
	  
	<div id="right">
		<div style="margin-top:24px;">			
		<form action="#" method="post" name="searchFE" onsubmit="s=document.getElementById('customSearchInput');if(s.value=='Search')return false;">
			<table width="100%" border="0" cellpadding="0" cellspacing="0">
			<tr>
					<td><input type="text" name="search_input_field" size="20" maxlength="200" id="customSearchInput" class="customSearchInput" value="" onfocus="if(this.value=='Search')this.value='';" onblur="if(this.value=='')this.value='Search';"/></td>
					<td><input type="image" name="search_go" onfocus="this.blur();" title="Search" src="/template/lang/all/submit.gif" /></td>
				</tr>
			</table>
			</form>
			
			      <script type="text/javascript" language="javascript">
			  <!-- 
			        document.getElementById("customSearchInput").value="Search";
			  //-->
			      </script>
				  
<!-- <p style="margin-top:10px;">Change font size: <a href="[FontSize-]"><img src="template/lang/all/icons/reduce.gif" width="18" height="17" alt="" title="Small" border="0" /></a>
			<a href="[FontSize+]"><img src="template/lang/all/icons/extend.gif" width="18" height="17" alt="" title="Bigger" border="0" /></a>
			</p> -->
			
	<p style="margin-top:10px;">Please choose: 
	
	 </p>


<!-- <a href="http://validator.w3.org/check?uri=http%3A%2F%2Fwww.phpwcms-docu.de%2Findex.php%3Fdeutsche_version" title="W3C Standard XHTML" target="_blank"><img src="picture/w3c/w3c_xhtml.gif" border="0" alt="" /></a>
<a href="http://jigsaw.w3.org/css-validator/validator?uri=http://www.phpwcms-docu.de" title="W3C Standard CSS" target="_blank"><img src="picture/w3c/w3c_css.gif" border="0" alt="" /></a><br />			
<div style="border-bottom:1px dotted #dae7f6; margin-top:10px; margin-bottom:15px;"></div> -->
		
<div style="margin-top:10px; margin-bottom:15px;"></div>
	
</div>

	</div> 
	
	<div id="content">
	<div id="bread">You are here: <a href="english_version.phtml">English</a> <span class="breadcrumb_spacer">&gt;</span> <a href="the_docu.phtml">The Docu</a> <span class="breadcrumb_spacer">&gt;</span> <a href="admin_en_.phtml">Admin</a> <span class="breadcrumb_spacer">&gt;</span> User administration</div>
		
		<a name="jump260"></a><!-- Livedate: 16.01.2005 21:25:21 / Killdate: 31.12.2030 23:59:59 -->
<h1>User administration</h1>
<h3>creation and management</h3>

<div style="margin:25px 0 0 0;padding:0;" class="spaceBeforeCP"></div><h3>User Administration</h3><h4>creation and management</h4><table width="158" border="0" cellspacing="0" cellpadding="0" align="left">
<tr><td class="image_td2"><a href="zoom/MDI3ZGQwY2YzZTdiOTZlYWM5OGU3MjdhNzZkOTMyMzIucG5nP3dpZHRoPSI3NjkiIGhlaWdodD0iNDAwIg.html" onclick="checkClickZoom();clickZoom('zoom/MDI3ZGQwY2YzZTdiOTZlYWM5OGU3MjdhNzZkOTMyMzIucG5nP3dpZHRoPSI3NjkiIGhlaWdodD0iNDAwIg.html','previewpic','width.html');return false;.html"><img src="content/images/3d2dd615dc67ac221cea5fb7a65b0615.png" width="150" height="78" border="0" class="image_img" alt="benutzer_01.png" /></a></td><td><img src="img/leer.gif" width="8" height="1" border="0" alt="" /></td></tr>
</table><div class="articleText"><TABLE height=95 cellSpacing=0 cellPadding=0 width="70%" border=0>
<TBODY>
<TR>
<TD>In the user administration area you can create and manage the user accounts. Here you can grant a user simple user rights or administration rights. <br /><br />If you visit the user administration area for the first time the only user listed is the webmaster. <br /><br />Here is an overview with descriptions for all icons in the user administration area: </TD></TR></TBODY></TABLE></div><div style="margin:10px 0 0 0;padding:0;" class="spaceBeforeCP"></div><TABLE cellSpacing=1 cellPadding=0 width="100%" border=0>
<TBODY>
<TR>
<TD bgColor=#cccccc>
<TABLE cellSpacing=1 cellPadding=5 width="100%" border=0>
<TBODY>
<TR>
<TD colSpan=3><STRONG>Legend</STRONG></TD></TR>
<TR>
<TD bgColor=#ffffff><U>Icon</U></TD>
<TD bgColor=#ffffff><U>Description</U></TD></TR>
<TR>
<TD bgColor=#ffffff>
<P align=center><img src="picture/../img/usricon/usr_admin.gif" border="0" alt="" /></P></TD>
<TD bgColor=#ffffff>Users with administration rights </TD></TR>
<TR>
<TD bgColor=#ffffff>
<P align=center><img src="picture/../img/usricon/usr_norm.gif" border="0" alt="" /></P></TD>
<TD bgColor=#ffffff>Users with basic user rights (<STRONG>no access to the ADMIN area</STRONG>)</TD></TR>
<TR>
<TD bgColor=#ffffff>
<P align=center><img src="picture/../img/button/aktiv_mini.gif" border="0" alt="" /><img src="picture/../img/button/inaktiv_mini.gif" border="0" alt="" /></P></TD>
<TD bgColor=#ffffff>User status<br /><br /><img src="picture/../img/button/aktiv_mini.gif" border="0" alt="" /> User can log into the backend<img src="picture/../img/button/inaktiv_mini.gif" border="0" alt="" /> User is barred from logging into the backend<br /><br />You can change the users status by clicking the icon. <img src="picture/../img/button/aktiv_mini.gif" border="0" alt="" />|<img src="picture/../img/button/inaktiv_mini.gif" border="0" alt="" /></TD></TR>
<TR>
<TD bgColor=#ffffff>
<P align=center><img src="picture/../img/button/edit.gif" border="0" alt="" /></P></TD>
<TD bgColor=#ffffff>Edit user details – change username, password or email address.</TD></TR>
<TR>
<TD bgColor=#ffffff>
<P align=center><img src="picture/../img/button/del_message_final.gif" border="0" alt="" /></P></TD>
<TD bgColor=#ffffff>Delete user account</TD></TR>
<TR>
<TD bgColor=#ffffff>
<P align=center><img src="picture/benutzer_anlegen.png" border="0" alt="" /></P></TD>
<TD bgColor=#ffffff>Set up new user account</TD></TR></TBODY></TABLE></TD></TR></TBODY></TABLE><div style="margin:10px 0 0 0;padding:0;" class="spaceBeforeCP"></div><strong>Next ...<br/><a href="create_user.phtml" class="phpwcmsIntLink">Create User</a></strong><div align="right"><a href="#top"><img src="img/article/top_link_0.gif" border="0" alt="" /></a></div>
		 
		
		<br /><br />
		<div class="sub">
		Article created: Monday, 17. January 2005 <br /> Last Changes: Tuesday, 4. January 2011	
		</div>
				
	</div>
	
<div id="footer">





	<table width="97%" border="0" cellspacing="0" cellpadding="0">
		<tr>
			<td valign="bottom">	
			&copy; phpwcms-docu 2004-2015
			<img src="img/leer.gif" border="0" width="10" height="0" alt="" /><a href="imprint.phtml" class="phpwcmsIntLink"><img src="template/lang/all/icons/imprint.gif" width="9" height="15" alt="Impressum" title="Impressum" border="0" /></a>&nbsp; 
			<a href="sitemap_en.phtml" class="phpwcmsIntLink"><img src="template/lang/all/icons/sitemap.gif" width="19" height="15" alt="Sitemap" title="Sitemap" border="0" /></a>&nbsp; 
			 
			
			     
			</td>
			<td valign="bottom" style="padding-right:25px;">
			
			
			
			</td>		
			<td width="150">
			</td>
		</tr>
	</table>
</div><br/>

</div>
</body>
</html>